#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc { ptr : * mut u8 } unsafe impl Send for Adc { } unsafe impl Sync for Adc { } impl Adc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn adc_stat (self) -> crate :: common :: Reg < regs :: AdcStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn adc_ctl0 (self) -> crate :: common :: Reg < regs :: AdcCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn adc_ctl1 (self) -> crate :: common :: Reg < regs :: AdcCtl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn adc_sampt0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn adc_sampt1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn adc_ioff0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn adc_ioff1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn adc_ioff2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn adc_ioff3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn adc_wdht (self) -> crate :: common :: Reg < regs :: AdcWdht , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn adc_wdlt (self) -> crate :: common :: Reg < regs :: AdcWdlt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn adc_rsq0 (self) -> crate :: common :: Reg < regs :: AdcRsq0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn adc_rsq1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn adc_rsq2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn adc_isq (self) -> crate :: common :: Reg < regs :: AdcIsq , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn adc_idata0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn adc_idata1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn adc_idata2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn adc_idata3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x48usize) as _) } } # [inline (always)]
pub const fn adc_rdata (self) -> crate :: common :: Reg < regs :: AdcRdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x4cusize) as _) } } # [inline (always)]
pub const fn adc_ovsampctl (self) -> crate :: common :: Reg < regs :: AdcOvsampctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x80usize) as _) } } # [inline (always)]
pub const fn adc_cctl (self) -> crate :: common :: Reg < regs :: AdcCctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0304usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcCctl (pub u32) ; impl AdcCctl { # [must_use]
# [inline (always)]
pub const fn adc_cctl_adcck (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_adc_cctl_adcck (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_cctl_vbaten (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_cctl_vbaten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_cctl_tsvren (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_cctl_tsvren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for AdcCctl { # [inline (always)]
fn default () -> AdcCctl { AdcCctl (0) } } impl core :: fmt :: Debug for AdcCctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcCctl") . field ("adc_cctl_adcck" , & self . adc_cctl_adcck ()) . field ("adc_cctl_vbaten" , & self . adc_cctl_vbaten ()) . field ("adc_cctl_tsvren" , & self . adc_cctl_tsvren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcCctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcCctl {{ adc_cctl_adcck: {=u8:?}, adc_cctl_vbaten: {=bool:?}, adc_cctl_tsvren: {=bool:?} }}" , self . adc_cctl_adcck () , self . adc_cctl_vbaten () , self . adc_cctl_tsvren ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcCtl0 (pub u32) ; impl AdcCtl0 { # [must_use]
# [inline (always)]
pub const fn adc_ctl0_wdchsel (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_adc_ctl0_wdchsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_eocie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_eocie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_wdeie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_wdeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_eoicie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_eoicie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_sm (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_sm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_wdsc (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_wdsc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_ica (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_ica (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_disrc (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_disrc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_disic (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_disic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_disnum (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_adc_ctl0_disnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 13usize)) | (((val as u32) & 0x07) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_iwden (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_iwden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_rwden (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_rwden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl0_rovfie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl0_rovfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } } impl Default for AdcCtl0 { # [inline (always)]
fn default () -> AdcCtl0 { AdcCtl0 (0) } } impl core :: fmt :: Debug for AdcCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcCtl0") . field ("adc_ctl0_wdchsel" , & self . adc_ctl0_wdchsel ()) . field ("adc_ctl0_eocie" , & self . adc_ctl0_eocie ()) . field ("adc_ctl0_wdeie" , & self . adc_ctl0_wdeie ()) . field ("adc_ctl0_eoicie" , & self . adc_ctl0_eoicie ()) . field ("adc_ctl0_sm" , & self . adc_ctl0_sm ()) . field ("adc_ctl0_wdsc" , & self . adc_ctl0_wdsc ()) . field ("adc_ctl0_ica" , & self . adc_ctl0_ica ()) . field ("adc_ctl0_disrc" , & self . adc_ctl0_disrc ()) . field ("adc_ctl0_disic" , & self . adc_ctl0_disic ()) . field ("adc_ctl0_disnum" , & self . adc_ctl0_disnum ()) . field ("adc_ctl0_iwden" , & self . adc_ctl0_iwden ()) . field ("adc_ctl0_rwden" , & self . adc_ctl0_rwden ()) . field ("adc_ctl0_rovfie" , & self . adc_ctl0_rovfie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcCtl0 {{ adc_ctl0_wdchsel: {=u8:?}, adc_ctl0_eocie: {=bool:?}, adc_ctl0_wdeie: {=bool:?}, adc_ctl0_eoicie: {=bool:?}, adc_ctl0_sm: {=bool:?}, adc_ctl0_wdsc: {=bool:?}, adc_ctl0_ica: {=bool:?}, adc_ctl0_disrc: {=bool:?}, adc_ctl0_disic: {=bool:?}, adc_ctl0_disnum: {=u8:?}, adc_ctl0_iwden: {=bool:?}, adc_ctl0_rwden: {=bool:?}, adc_ctl0_rovfie: {=bool:?} }}" , self . adc_ctl0_wdchsel () , self . adc_ctl0_eocie () , self . adc_ctl0_wdeie () , self . adc_ctl0_eoicie () , self . adc_ctl0_sm () , self . adc_ctl0_wdsc () , self . adc_ctl0_ica () , self . adc_ctl0_disrc () , self . adc_ctl0_disic () , self . adc_ctl0_disnum () , self . adc_ctl0_iwden () , self . adc_ctl0_rwden () , self . adc_ctl0_rovfie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcCtl1 (pub u32) ; impl AdcCtl1 { # [must_use]
# [inline (always)]
pub const fn adc_ctl1_adcon (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_adcon (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_ctn (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_ctn (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_dma (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_dma (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_ddm (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_ddm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_eocm (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_eocm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_dal (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_dal (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_etsic (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_adc_ctl1_etsic (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_etmic (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_adc_ctl1_etmic (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_swicst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_swicst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_etsrc (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_adc_ctl1_etsrc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_etmrc (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_adc_ctl1_etmrc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ctl1_swrcst (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ctl1_swrcst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for AdcCtl1 { # [inline (always)]
fn default () -> AdcCtl1 { AdcCtl1 (0) } } impl core :: fmt :: Debug for AdcCtl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcCtl1") . field ("adc_ctl1_adcon" , & self . adc_ctl1_adcon ()) . field ("adc_ctl1_ctn" , & self . adc_ctl1_ctn ()) . field ("adc_ctl1_dma" , & self . adc_ctl1_dma ()) . field ("adc_ctl1_ddm" , & self . adc_ctl1_ddm ()) . field ("adc_ctl1_eocm" , & self . adc_ctl1_eocm ()) . field ("adc_ctl1_dal" , & self . adc_ctl1_dal ()) . field ("adc_ctl1_etsic" , & self . adc_ctl1_etsic ()) . field ("adc_ctl1_etmic" , & self . adc_ctl1_etmic ()) . field ("adc_ctl1_swicst" , & self . adc_ctl1_swicst ()) . field ("adc_ctl1_etsrc" , & self . adc_ctl1_etsrc ()) . field ("adc_ctl1_etmrc" , & self . adc_ctl1_etmrc ()) . field ("adc_ctl1_swrcst" , & self . adc_ctl1_swrcst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcCtl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcCtl1 {{ adc_ctl1_adcon: {=bool:?}, adc_ctl1_ctn: {=bool:?}, adc_ctl1_dma: {=bool:?}, adc_ctl1_ddm: {=bool:?}, adc_ctl1_eocm: {=bool:?}, adc_ctl1_dal: {=bool:?}, adc_ctl1_etsic: {=u8:?}, adc_ctl1_etmic: {=u8:?}, adc_ctl1_swicst: {=bool:?}, adc_ctl1_etsrc: {=u8:?}, adc_ctl1_etmrc: {=u8:?}, adc_ctl1_swrcst: {=bool:?} }}" , self . adc_ctl1_adcon () , self . adc_ctl1_ctn () , self . adc_ctl1_dma () , self . adc_ctl1_ddm () , self . adc_ctl1_eocm () , self . adc_ctl1_dal () , self . adc_ctl1_etsic () , self . adc_ctl1_etmic () , self . adc_ctl1_swicst () , self . adc_ctl1_etsrc () , self . adc_ctl1_etmrc () , self . adc_ctl1_swrcst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcIsq (pub u32) ; impl AdcIsq { # [must_use]
# [inline (always)]
pub const fn adc_isq_isqn (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_adc_isq_isqn (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_isq_il (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_adc_isq_il (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } } impl Default for AdcIsq { # [inline (always)]
fn default () -> AdcIsq { AdcIsq (0) } } impl core :: fmt :: Debug for AdcIsq { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcIsq") . field ("adc_isq_isqn" , & self . adc_isq_isqn ()) . field ("adc_isq_il" , & self . adc_isq_il ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcIsq { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcIsq {{ adc_isq_isqn: {=u8:?}, adc_isq_il: {=u8:?} }}" , self . adc_isq_isqn () , self . adc_isq_il ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcOvsampctl (pub u32) ; impl AdcOvsampctl { # [must_use]
# [inline (always)]
pub const fn adc_ovsampctl_ovsen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ovsampctl_ovsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ovsampctl_ovsr (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_adc_ovsampctl_ovsr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 2usize)) | (((val as u32) & 0x07) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ovsampctl_ovss (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_adc_ovsampctl_ovss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 5usize)) | (((val as u32) & 0x0f) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_ovsampctl_tovs (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_ovsampctl_tovs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } } impl Default for AdcOvsampctl { # [inline (always)]
fn default () -> AdcOvsampctl { AdcOvsampctl (0) } } impl core :: fmt :: Debug for AdcOvsampctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcOvsampctl") . field ("adc_ovsampctl_ovsen" , & self . adc_ovsampctl_ovsen ()) . field ("adc_ovsampctl_ovsr" , & self . adc_ovsampctl_ovsr ()) . field ("adc_ovsampctl_ovss" , & self . adc_ovsampctl_ovss ()) . field ("adc_ovsampctl_tovs" , & self . adc_ovsampctl_tovs ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcOvsampctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcOvsampctl {{ adc_ovsampctl_ovsen: {=bool:?}, adc_ovsampctl_ovsr: {=u8:?}, adc_ovsampctl_ovss: {=u8:?}, adc_ovsampctl_tovs: {=bool:?} }}" , self . adc_ovsampctl_ovsen () , self . adc_ovsampctl_ovsr () , self . adc_ovsampctl_ovss () , self . adc_ovsampctl_tovs ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcRdata (pub u32) ; impl AdcRdata { # [must_use]
# [inline (always)]
pub const fn adc_rdata_rdata (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_adc_rdata_rdata (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for AdcRdata { # [inline (always)]
fn default () -> AdcRdata { AdcRdata (0) } } impl core :: fmt :: Debug for AdcRdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcRdata") . field ("adc_rdata_rdata" , & self . adc_rdata_rdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcRdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcRdata {{ adc_rdata_rdata: {=u16:?} }}" , self . adc_rdata_rdata ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcRsq0 (pub u32) ; impl AdcRsq0 { # [must_use]
# [inline (always)]
pub const fn adc_rsq0_rl (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_adc_rsq0_rl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } } impl Default for AdcRsq0 { # [inline (always)]
fn default () -> AdcRsq0 { AdcRsq0 (0) } } impl core :: fmt :: Debug for AdcRsq0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcRsq0") . field ("adc_rsq0_rl" , & self . adc_rsq0_rl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcRsq0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcRsq0 {{ adc_rsq0_rl: {=u8:?} }}" , self . adc_rsq0_rl ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcStat (pub u32) ; impl AdcStat { # [must_use]
# [inline (always)]
pub const fn adc_stat_wde (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_stat_wde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_stat_eoc (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_stat_eoc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_stat_eoic (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_stat_eoic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_stat_stic (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_stat_stic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_stat_strc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_stat_strc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn adc_stat_rovf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_adc_stat_rovf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for AdcStat { # [inline (always)]
fn default () -> AdcStat { AdcStat (0) } } impl core :: fmt :: Debug for AdcStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcStat") . field ("adc_stat_wde" , & self . adc_stat_wde ()) . field ("adc_stat_eoc" , & self . adc_stat_eoc ()) . field ("adc_stat_eoic" , & self . adc_stat_eoic ()) . field ("adc_stat_stic" , & self . adc_stat_stic ()) . field ("adc_stat_strc" , & self . adc_stat_strc ()) . field ("adc_stat_rovf" , & self . adc_stat_rovf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcStat {{ adc_stat_wde: {=bool:?}, adc_stat_eoc: {=bool:?}, adc_stat_eoic: {=bool:?}, adc_stat_stic: {=bool:?}, adc_stat_strc: {=bool:?}, adc_stat_rovf: {=bool:?} }}" , self . adc_stat_wde () , self . adc_stat_eoc () , self . adc_stat_eoic () , self . adc_stat_stic () , self . adc_stat_strc () , self . adc_stat_rovf ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcWdht (pub u32) ; impl AdcWdht { # [must_use]
# [inline (always)]
pub const fn adc_wdht_wdht (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x0fff ; val as u16 } # [inline (always)]
pub const fn set_adc_wdht_wdht (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 0usize)) | (((val as u32) & 0x0fff) << 0usize) ; } } impl Default for AdcWdht { # [inline (always)]
fn default () -> AdcWdht { AdcWdht (0) } } impl core :: fmt :: Debug for AdcWdht { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcWdht") . field ("adc_wdht_wdht" , & self . adc_wdht_wdht ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcWdht { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcWdht {{ adc_wdht_wdht: {=u16:?} }}" , self . adc_wdht_wdht ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct AdcWdlt (pub u32) ; impl AdcWdlt { # [must_use]
# [inline (always)]
pub const fn adc_wdlt_wdlt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x0fff ; val as u16 } # [inline (always)]
pub const fn set_adc_wdlt_wdlt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 0usize)) | (((val as u32) & 0x0fff) << 0usize) ; } } impl Default for AdcWdlt { # [inline (always)]
fn default () -> AdcWdlt { AdcWdlt (0) } } impl core :: fmt :: Debug for AdcWdlt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("AdcWdlt") . field ("adc_wdlt_wdlt" , & self . adc_wdlt_wdlt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for AdcWdlt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "AdcWdlt {{ adc_wdlt_wdlt: {=u16:?} }}" , self . adc_wdlt_wdlt ()) } } }