#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Cryptographic acceleration unit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cau { ptr : * mut u8 } unsafe impl Send for Cau { } unsafe impl Sync for Cau { } impl Cau { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "CAU control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "CAU status register 0"]
# [inline (always)]
pub const fn stat0 (self) -> crate :: common :: Reg < regs :: Stat0 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "CAU data input register"]
# [inline (always)]
pub const fn di (self) -> crate :: common :: Reg < regs :: Di , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "CAU data output register"]
# [inline (always)]
pub const fn do_ (self) -> crate :: common :: Reg < regs :: Do , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "CAU DMA enable register"]
# [inline (always)]
pub const fn dmaen (self) -> crate :: common :: Reg < regs :: Dmaen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "CAU interrupt enable register"]
# [inline (always)]
pub const fn inten (self) -> crate :: common :: Reg < regs :: Inten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "CAU interrupt status flag register 1"]
# [inline (always)]
pub const fn stat1 (self) -> crate :: common :: Reg < regs :: Stat1 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "CAU enable interrupt status flag register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key0h (self) -> crate :: common :: Reg < regs :: Key0h , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key0l (self) -> crate :: common :: Reg < regs :: Key0l , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key1h (self) -> crate :: common :: Reg < regs :: Key1h , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key1l (self) -> crate :: common :: Reg < regs :: Key1l , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key2h (self) -> crate :: common :: Reg < regs :: Key2h , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key2l (self) -> crate :: common :: Reg < regs :: Key2l , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key3h (self) -> crate :: common :: Reg < regs :: Key3h , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "CAU key register"]
# [inline (always)]
pub const fn key3l (self) -> crate :: common :: Reg < regs :: Key3l , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } } pub mod regs { # [doc = "CAU control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "CAU direction"]
# [inline (always)]
pub const fn caudir (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "CAU direction"]
# [inline (always)]
pub fn set_caudir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Encryption/decryption algorithm mode"]
# [inline (always)]
pub const fn algm (& self) -> u8 { let val = (self . 0 >> 3usize) & 0x07 ; val as u8 } # [doc = "Encryption/decryption algorithm mode"]
# [inline (always)]
pub fn set_algm (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 3usize)) | (((val as u32) & 0x07) << 3usize) ; } # [doc = "Data swapping type mode configuration"]
# [inline (always)]
pub const fn datam (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Data swapping type mode configuration"]
# [inline (always)]
pub fn set_datam (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "AES key size mode configuration"]
# [inline (always)]
pub const fn keym (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "AES key size mode configuration"]
# [inline (always)]
pub fn set_keym (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "FIFO flush"]
# [inline (always)]
pub const fn fflush (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "FIFO flush"]
# [inline (always)]
pub fn set_fflush (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Cryptographic module enable"]
# [inline (always)]
pub const fn cauen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Cryptographic module enable"]
# [inline (always)]
pub fn set_cauen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("caudir" , & self . caudir ()) . field ("algm" , & self . algm ()) . field ("datam" , & self . datam ()) . field ("keym" , & self . keym ()) . field ("fflush" , & self . fflush ()) . field ("cauen" , & self . cauen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ caudir: {=bool:?}, algm: {=u8:?}, datam: {=u8:?}, keym: {=u8:?}, fflush: {=bool:?}, cauen: {=bool:?} }}" , self . caudir () , self . algm () , self . datam () , self . keym () , self . fflush () , self . cauen ()) } } # [doc = "CAU data input register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Di (pub u32) ; impl Di { # [doc = "Data input"]
# [inline (always)]
pub const fn di (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Data input"]
# [inline (always)]
pub fn set_di (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Di { # [inline (always)]
fn default () -> Di { Di (0) } } impl core :: fmt :: Debug for Di { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Di") . field ("di" , & self . di ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Di { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Di {{ di: {=u32:?} }}" , self . di ()) } } # [doc = "CAU DMA enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmaen (pub u32) ; impl Dmaen { # [doc = "In FIFO DMA enable"]
# [inline (always)]
pub const fn dmaien (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "In FIFO DMA enable"]
# [inline (always)]
pub fn set_dmaien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Out FIFO DMA enable"]
# [inline (always)]
pub const fn dmaoen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Out FIFO DMA enable"]
# [inline (always)]
pub fn set_dmaoen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Dmaen { # [inline (always)]
fn default () -> Dmaen { Dmaen (0) } } impl core :: fmt :: Debug for Dmaen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmaen") . field ("dmaien" , & self . dmaien ()) . field ("dmaoen" , & self . dmaoen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmaen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmaen {{ dmaien: {=bool:?}, dmaoen: {=bool:?} }}" , self . dmaien () , self . dmaoen ()) } } # [doc = "CAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do (pub u32) ; impl Do { # [doc = "Data output"]
# [inline (always)]
pub const fn do_ (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Data output"]
# [inline (always)]
pub fn set_do_ (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do { # [inline (always)]
fn default () -> Do { Do (0) } } impl core :: fmt :: Debug for Do { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do") . field ("do_" , & self . do_ ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do {{ do_: {=u32:?} }}" , self . do_ ()) } } # [doc = "CAU interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Inten (pub u32) ; impl Inten { # [doc = "In FIFO interrupt enable"]
# [inline (always)]
pub const fn iinten (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "In FIFO interrupt enable"]
# [inline (always)]
pub fn set_iinten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Out FIFO interrupt enable"]
# [inline (always)]
pub const fn ointen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Out FIFO interrupt enable"]
# [inline (always)]
pub fn set_ointen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Inten { # [inline (always)]
fn default () -> Inten { Inten (0) } } impl core :: fmt :: Debug for Inten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Inten") . field ("iinten" , & self . iinten ()) . field ("ointen" , & self . ointen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Inten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Inten {{ iinten: {=bool:?}, ointen: {=bool:?} }}" , self . iinten () , self . ointen ()) } } # [doc = "CAU enable interrupt status flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "In FIFO enabled interrupt flag"]
# [inline (always)]
pub const fn iintf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "In FIFO enabled interrupt flag"]
# [inline (always)]
pub fn set_iintf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Out FIFO enabled interrupt flag"]
# [inline (always)]
pub const fn ointf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Out FIFO enabled interrupt flag"]
# [inline (always)]
pub fn set_ointf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("iintf" , & self . iintf ()) . field ("ointf" , & self . ointf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ iintf: {=bool:?}, ointf: {=bool:?} }}" , self . iintf () , self . ointf ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key0h (pub u32) ; impl Key0h { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key0h (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key0h (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key0h { # [inline (always)]
fn default () -> Key0h { Key0h (0) } } impl core :: fmt :: Debug for Key0h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key0h") . field ("key0h" , & self . key0h ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key0h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key0h {{ key0h: {=u32:?} }}" , self . key0h ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key0l (pub u32) ; impl Key0l { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key0l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key0l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key0l { # [inline (always)]
fn default () -> Key0l { Key0l (0) } } impl core :: fmt :: Debug for Key0l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key0l") . field ("key0l" , & self . key0l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key0l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key0l {{ key0l: {=u32:?} }}" , self . key0l ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key1h (pub u32) ; impl Key1h { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key1h (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key1h (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key1h { # [inline (always)]
fn default () -> Key1h { Key1h (0) } } impl core :: fmt :: Debug for Key1h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key1h") . field ("key1h" , & self . key1h ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key1h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key1h {{ key1h: {=u32:?} }}" , self . key1h ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key1l (pub u32) ; impl Key1l { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key1l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key1l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key1l { # [inline (always)]
fn default () -> Key1l { Key1l (0) } } impl core :: fmt :: Debug for Key1l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key1l") . field ("key1l" , & self . key1l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key1l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key1l {{ key1l: {=u32:?} }}" , self . key1l ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key2h (pub u32) ; impl Key2h { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key2h (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key2h (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key2h { # [inline (always)]
fn default () -> Key2h { Key2h (0) } } impl core :: fmt :: Debug for Key2h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key2h") . field ("key2h" , & self . key2h ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key2h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key2h {{ key2h: {=u32:?} }}" , self . key2h ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key2l (pub u32) ; impl Key2l { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key2l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key2l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key2l { # [inline (always)]
fn default () -> Key2l { Key2l (0) } } impl core :: fmt :: Debug for Key2l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key2l") . field ("key2l" , & self . key2l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key2l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key2l {{ key2l: {=u32:?} }}" , self . key2l ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key3h (pub u32) ; impl Key3h { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key3h (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key3h (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key3h { # [inline (always)]
fn default () -> Key3h { Key3h (0) } } impl core :: fmt :: Debug for Key3h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key3h") . field ("key3h" , & self . key3h ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key3h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key3h {{ key3h: {=u32:?} }}" , self . key3h ()) } } # [doc = "CAU key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key3l (pub u32) ; impl Key3l { # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub const fn key3l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Key for DES,TDES,AES"]
# [inline (always)]
pub fn set_key3l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key3l { # [inline (always)]
fn default () -> Key3l { Key3l (0) } } impl core :: fmt :: Debug for Key3l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key3l") . field ("key3l" , & self . key3l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key3l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key3l {{ key3l: {=u32:?} }}" , self . key3l ()) } } # [doc = "CAU status register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat0 (pub u32) ; impl Stat0 { # [doc = "IN FIFO empty flag"]
# [inline (always)]
pub const fn iem (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "IN FIFO empty flag"]
# [inline (always)]
pub fn set_iem (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "IN FIFO not full flag"]
# [inline (always)]
pub const fn inf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "IN FIFO not full flag"]
# [inline (always)]
pub fn set_inf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "OUT FIFO not empty flag"]
# [inline (always)]
pub const fn one (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "OUT FIFO not empty flag"]
# [inline (always)]
pub fn set_one (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "OUT FIFO full flag"]
# [inline (always)]
pub const fn ofu (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "OUT FIFO full flag"]
# [inline (always)]
pub fn set_ofu (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "BUSY flag"]
# [inline (always)]
pub const fn busy (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "BUSY flag"]
# [inline (always)]
pub fn set_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } } impl Default for Stat0 { # [inline (always)]
fn default () -> Stat0 { Stat0 (0) } } impl core :: fmt :: Debug for Stat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat0") . field ("iem" , & self . iem ()) . field ("inf" , & self . inf ()) . field ("one" , & self . one ()) . field ("ofu" , & self . ofu ()) . field ("busy" , & self . busy ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat0 {{ iem: {=bool:?}, inf: {=bool:?}, one: {=bool:?}, ofu: {=bool:?}, busy: {=bool:?} }}" , self . iem () , self . inf () , self . one () , self . ofu () , self . busy ()) } } # [doc = "CAU interrupt status flag register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat1 (pub u32) ; impl Stat1 { # [doc = "In FIFO interrupt flag"]
# [inline (always)]
pub const fn ista (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "In FIFO interrupt flag"]
# [inline (always)]
pub fn set_ista (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Out FIFO interrupt flag"]
# [inline (always)]
pub const fn osta (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Out FIFO interrupt flag"]
# [inline (always)]
pub fn set_osta (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Stat1 { # [inline (always)]
fn default () -> Stat1 { Stat1 (0) } } impl core :: fmt :: Debug for Stat1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat1") . field ("ista" , & self . ista ()) . field ("osta" , & self . osta ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat1 {{ ista: {=bool:?}, osta: {=bool:?} }}" , self . ista () , self . osta ()) } } }