#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Comparator"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cmp { ptr : * mut u8 } unsafe impl Send for Cmp { } unsafe impl Sync for Cmp { } impl Cmp { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Status register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Interrupt flag clear register"]
# [inline (always)]
pub const fn ifc (self) -> crate :: common :: Reg < regs :: Ifc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "CMP0 control/status register"]
# [inline (always)]
pub const fn cmp0_cs (self) -> crate :: common :: Reg < regs :: Cmp0Cs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } } pub mod regs { # [doc = "CMP0 control/status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cmp0Cs (pub u32) ; impl Cmp0Cs { # [doc = "CMP0 enable"]
# [inline (always)]
pub const fn cmp0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "CMP0 enable"]
# [inline (always)]
pub fn set_cmp0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Scaler bridge enable bit"]
# [inline (always)]
pub const fn cmp0ben (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Scaler bridge enable bit"]
# [inline (always)]
pub fn set_cmp0ben (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Voltage scaler enable bit"]
# [inline (always)]
pub const fn cmp0sen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Voltage scaler enable bit"]
# [inline (always)]
pub fn set_cmp0sen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Polarity of CMP0 output"]
# [inline (always)]
pub const fn cmp0pl (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Polarity of CMP0 output"]
# [inline (always)]
pub fn set_cmp0pl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "CMP0 interrupt enable"]
# [inline (always)]
pub const fn cmp0inten (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "CMP0 interrupt enable"]
# [inline (always)]
pub fn set_cmp0inten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "CMP0 hysteresis"]
# [inline (always)]
pub const fn cmp0hst (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "CMP0 hysteresis"]
# [inline (always)]
pub fn set_cmp0hst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "CMP0_IM internal input selection"]
# [inline (always)]
pub const fn cmp0msel (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "CMP0_IM internal input selection"]
# [inline (always)]
pub fn set_cmp0msel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "CMP0 output blanking source"]
# [inline (always)]
pub const fn cmp0blk (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "CMP0 output blanking source"]
# [inline (always)]
pub fn set_cmp0blk (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [doc = "CMP0 digital noise sampling selection."]
# [inline (always)]
pub const fn cmp0dnssel (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [doc = "CMP0 digital noise sampling selection."]
# [inline (always)]
pub fn set_cmp0dnssel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [doc = "Noise filter mode"]
# [inline (always)]
pub const fn cmp0nfm (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Noise filter mode"]
# [inline (always)]
pub fn set_cmp0nfm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "CMP0 lock"]
# [inline (always)]
pub const fn cmp0lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "CMP0 lock"]
# [inline (always)]
pub fn set_cmp0lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cmp0Cs { # [inline (always)]
fn default () -> Cmp0Cs { Cmp0Cs (0) } } impl core :: fmt :: Debug for Cmp0Cs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cmp0Cs") . field ("cmp0en" , & self . cmp0en ()) . field ("cmp0ben" , & self . cmp0ben ()) . field ("cmp0sen" , & self . cmp0sen ()) . field ("cmp0pl" , & self . cmp0pl ()) . field ("cmp0inten" , & self . cmp0inten ()) . field ("cmp0hst" , & self . cmp0hst ()) . field ("cmp0msel" , & self . cmp0msel ()) . field ("cmp0blk" , & self . cmp0blk ()) . field ("cmp0dnssel" , & self . cmp0dnssel ()) . field ("cmp0nfm" , & self . cmp0nfm ()) . field ("cmp0lk" , & self . cmp0lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cmp0Cs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cmp0Cs {{ cmp0en: {=bool:?}, cmp0ben: {=bool:?}, cmp0sen: {=bool:?}, cmp0pl: {=bool:?}, cmp0inten: {=bool:?}, cmp0hst: {=u8:?}, cmp0msel: {=u8:?}, cmp0blk: {=u8:?}, cmp0dnssel: {=u8:?}, cmp0nfm: {=bool:?}, cmp0lk: {=bool:?} }}" , self . cmp0en () , self . cmp0ben () , self . cmp0sen () , self . cmp0pl () , self . cmp0inten () , self . cmp0hst () , self . cmp0msel () , self . cmp0blk () , self . cmp0dnssel () , self . cmp0nfm () , self . cmp0lk ()) } } # [doc = "Interrupt flag clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ifc (pub u32) ; impl Ifc { # [doc = "CMP0 interrupt flag clear"]
# [inline (always)]
pub const fn cmp0ic (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "CMP0 interrupt flag clear"]
# [inline (always)]
pub fn set_cmp0ic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for Ifc { # [inline (always)]
fn default () -> Ifc { Ifc (0) } } impl core :: fmt :: Debug for Ifc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ifc") . field ("cmp0ic" , & self . cmp0ic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ifc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ifc {{ cmp0ic: {=bool:?} }}" , self . cmp0ic ()) } } # [doc = "Status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "CMP0 output state"]
# [inline (always)]
pub const fn cmp0o (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "CMP0 output state"]
# [inline (always)]
pub fn set_cmp0o (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "CMP0 interrupt flag"]
# [inline (always)]
pub const fn cmp0if (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "CMP0 interrupt flag"]
# [inline (always)]
pub fn set_cmp0if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } impl core :: fmt :: Debug for Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat") . field ("cmp0o" , & self . cmp0o ()) . field ("cmp0if" , & self . cmp0if ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat {{ cmp0o: {=bool:?}, cmp0if: {=bool:?} }}" , self . cmp0o () , self . cmp0if ()) } } }