#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Crc { ptr : * mut u8 } unsafe impl Send for Crc { } unsafe impl Sync for Crc { } impl Crc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn crc_data (self) -> crate :: common :: Reg < regs :: CrcData , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn crc_fdata (self) -> crate :: common :: Reg < regs :: CrcFdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn crc_ctl (self) -> crate :: common :: Reg < regs :: CrcCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct CrcCtl (pub u32) ; impl CrcCtl { # [must_use]
# [inline (always)]
pub const fn crc_ctl_rst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_crc_ctl_rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for CrcCtl { # [inline (always)]
fn default () -> CrcCtl { CrcCtl (0) } } impl core :: fmt :: Debug for CrcCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("CrcCtl") . field ("crc_ctl_rst" , & self . crc_ctl_rst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for CrcCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "CrcCtl {{ crc_ctl_rst: {=bool:?} }}" , self . crc_ctl_rst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct CrcData (pub u32) ; impl CrcData { # [must_use]
# [inline (always)]
pub const fn crc_data_data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_crc_data_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for CrcData { # [inline (always)]
fn default () -> CrcData { CrcData (0) } } impl core :: fmt :: Debug for CrcData { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("CrcData") . field ("crc_data_data" , & self . crc_data_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for CrcData { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "CrcData {{ crc_data_data: {=u32:?} }}" , self . crc_data_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct CrcFdata (pub u32) ; impl CrcFdata { # [must_use]
# [inline (always)]
pub const fn crc_fdata_fdata (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_crc_fdata_fdata (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for CrcFdata { # [inline (always)]
fn default () -> CrcFdata { CrcFdata (0) } } impl core :: fmt :: Debug for CrcFdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("CrcFdata") . field ("crc_fdata_fdata" , & self . crc_fdata_fdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for CrcFdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "CrcFdata {{ crc_fdata_fdata: {=u8:?} }}" , self . crc_fdata_fdata ()) } } }