#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dac { ptr : * mut u8 } unsafe impl Send for Dac { } unsafe impl Sync for Dac { } impl Dac { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn dac_ctl0 (self) -> crate :: common :: Reg < regs :: DacCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn dac_swt (self) -> crate :: common :: Reg < regs :: DacSwt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn dac_out0_r12dh (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn dac_out0_l12dh (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn dac_out0_r8dh (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn dac_out0_do (self) -> crate :: common :: Reg < regs :: DacOut0Do , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn dac_stat0 (self) -> crate :: common :: Reg < regs :: DacStat0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DacCtl0 (pub u32) ; impl DacCtl0 { # [must_use]
# [inline (always)]
pub const fn dac_ctl0_den0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_ctl0_den0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn dac_ctl0_dboff0 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_ctl0_dboff0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn dac_ctl0_dten0 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_ctl0_dten0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn dac_ctl0_dtsel0 (& self) -> u8 { let val = (self . 0 >> 3usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_dac_ctl0_dtsel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 3usize)) | (((val as u32) & 0x07) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn dac_ctl0_ddmaen0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_ctl0_ddmaen0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn dac_ctl0_ddudrie0 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_ctl0_ddudrie0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } } impl Default for DacCtl0 { # [inline (always)]
fn default () -> DacCtl0 { DacCtl0 (0) } } impl core :: fmt :: Debug for DacCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DacCtl0") . field ("dac_ctl0_den0" , & self . dac_ctl0_den0 ()) . field ("dac_ctl0_dboff0" , & self . dac_ctl0_dboff0 ()) . field ("dac_ctl0_dten0" , & self . dac_ctl0_dten0 ()) . field ("dac_ctl0_dtsel0" , & self . dac_ctl0_dtsel0 ()) . field ("dac_ctl0_ddmaen0" , & self . dac_ctl0_ddmaen0 ()) . field ("dac_ctl0_ddudrie0" , & self . dac_ctl0_ddudrie0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DacCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DacCtl0 {{ dac_ctl0_den0: {=bool:?}, dac_ctl0_dboff0: {=bool:?}, dac_ctl0_dten0: {=bool:?}, dac_ctl0_dtsel0: {=u8:?}, dac_ctl0_ddmaen0: {=bool:?}, dac_ctl0_ddudrie0: {=bool:?} }}" , self . dac_ctl0_den0 () , self . dac_ctl0_dboff0 () , self . dac_ctl0_dten0 () , self . dac_ctl0_dtsel0 () , self . dac_ctl0_ddmaen0 () , self . dac_ctl0_ddudrie0 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DacOut0Do (pub u32) ; impl DacOut0Do { # [must_use]
# [inline (always)]
pub const fn dac_out0_do_bits (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x0fff ; val as u16 } # [inline (always)]
pub const fn set_dac_out0_do_bits (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 0usize)) | (((val as u32) & 0x0fff) << 0usize) ; } } impl Default for DacOut0Do { # [inline (always)]
fn default () -> DacOut0Do { DacOut0Do (0) } } impl core :: fmt :: Debug for DacOut0Do { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DacOut0Do") . field ("dac_out0_do_bits" , & self . dac_out0_do_bits ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DacOut0Do { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DacOut0Do {{ dac_out0_do_bits: {=u16:?} }}" , self . dac_out0_do_bits ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DacStat0 (pub u32) ; impl DacStat0 { # [must_use]
# [inline (always)]
pub const fn dac_stat0_ddudr0 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_stat0_ddudr0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } } impl Default for DacStat0 { # [inline (always)]
fn default () -> DacStat0 { DacStat0 (0) } } impl core :: fmt :: Debug for DacStat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DacStat0") . field ("dac_stat0_ddudr0" , & self . dac_stat0_ddudr0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DacStat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DacStat0 {{ dac_stat0_ddudr0: {=bool:?} }}" , self . dac_stat0_ddudr0 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DacSwt (pub u32) ; impl DacSwt { # [must_use]
# [inline (always)]
pub const fn dac_swt_swtr0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_dac_swt_swtr0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for DacSwt { # [inline (always)]
fn default () -> DacSwt { DacSwt (0) } } impl core :: fmt :: Debug for DacSwt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DacSwt") . field ("dac_swt_swtr0" , & self . dac_swt_swtr0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DacSwt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DacSwt {{ dac_swt_swtr0: {=bool:?} }}" , self . dac_swt_swtr0 ()) } } }