#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Debug support"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dbg { ptr : * mut u8 } unsafe impl Send for Dbg { } unsafe impl Sync for Dbg { } impl Dbg { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "ID code register"]
# [inline (always)]
pub const fn id (self) -> crate :: common :: Reg < regs :: Id , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } } pub mod regs { # [doc = "Control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Sleep mode hold bit"]
# [inline (always)]
pub const fn slp_hold (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Sleep mode hold bit"]
# [inline (always)]
pub fn set_slp_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Deep-sleep mode hold bit"]
# [inline (always)]
pub const fn dslp_hold (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Deep-sleep mode hold bit"]
# [inline (always)]
pub fn set_dslp_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Standby mode hold bit"]
# [inline (always)]
pub const fn stb_hold (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Standby mode hold bit"]
# [inline (always)]
pub fn set_stb_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "FWDGT hold bit"]
# [inline (always)]
pub const fn fwdgt_hold (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "FWDGT hold bit"]
# [inline (always)]
pub fn set_fwdgt_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "WWDGT hold bit"]
# [inline (always)]
pub const fn wwdgt_hold (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "WWDGT hold bit"]
# [inline (always)]
pub fn set_wwdgt_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "TIMER 0 hold bit"]
# [inline (always)]
pub const fn timer0_hold (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "TIMER 0 hold bit"]
# [inline (always)]
pub fn set_timer0_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "TIMER 1 hold bit"]
# [inline (always)]
pub const fn timer1_hold (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "TIMER 1 hold bit"]
# [inline (always)]
pub fn set_timer1_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "I2C0 hold bit"]
# [inline (always)]
pub const fn i2c0_hold (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "I2C0 hold bit"]
# [inline (always)]
pub fn set_i2c0_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "I2C1 hold bit"]
# [inline (always)]
pub const fn i2c1_hold (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "I2C1 hold bit"]
# [inline (always)]
pub fn set_i2c1_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TIMER 7 hold bit"]
# [inline (always)]
pub const fn timer7_hold (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "TIMER 7 hold bit"]
# [inline (always)]
pub fn set_timer7_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "TIMER 5 hold bit"]
# [inline (always)]
pub const fn timer5_hold (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "TIMER 5 hold bit"]
# [inline (always)]
pub fn set_timer5_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "TIMER 6 hold bit"]
# [inline (always)]
pub const fn timer6_hold (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "TIMER 6 hold bit"]
# [inline (always)]
pub fn set_timer6_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "MFCOM hold bit"]
# [inline (always)]
pub const fn mfcom_hold (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "MFCOM hold bit"]
# [inline (always)]
pub fn set_mfcom_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "CAN0 hold bit"]
# [inline (always)]
pub const fn can0_hold (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "CAN0 hold bit"]
# [inline (always)]
pub fn set_can0_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "CAN1 hold bit"]
# [inline (always)]
pub const fn can1_hold (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "CAN1 hold bit"]
# [inline (always)]
pub fn set_can1_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "TIMER20 hold bit"]
# [inline (always)]
pub const fn timer20_hold (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "TIMER20 hold bit"]
# [inline (always)]
pub fn set_timer20_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "TIMER19 hold bit"]
# [inline (always)]
pub const fn timer19_hold (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TIMER19 hold bit"]
# [inline (always)]
pub fn set_timer19_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("slp_hold" , & self . slp_hold ()) . field ("dslp_hold" , & self . dslp_hold ()) . field ("stb_hold" , & self . stb_hold ()) . field ("fwdgt_hold" , & self . fwdgt_hold ()) . field ("wwdgt_hold" , & self . wwdgt_hold ()) . field ("timer0_hold" , & self . timer0_hold ()) . field ("timer1_hold" , & self . timer1_hold ()) . field ("i2c0_hold" , & self . i2c0_hold ()) . field ("i2c1_hold" , & self . i2c1_hold ()) . field ("timer7_hold" , & self . timer7_hold ()) . field ("timer5_hold" , & self . timer5_hold ()) . field ("timer6_hold" , & self . timer6_hold ()) . field ("mfcom_hold" , & self . mfcom_hold ()) . field ("can0_hold" , & self . can0_hold ()) . field ("can1_hold" , & self . can1_hold ()) . field ("timer20_hold" , & self . timer20_hold ()) . field ("timer19_hold" , & self . timer19_hold ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ slp_hold: {=bool:?}, dslp_hold: {=bool:?}, stb_hold: {=bool:?}, fwdgt_hold: {=bool:?}, wwdgt_hold: {=bool:?}, timer0_hold: {=bool:?}, timer1_hold: {=bool:?}, i2c0_hold: {=bool:?}, i2c1_hold: {=bool:?}, timer7_hold: {=bool:?}, timer5_hold: {=bool:?}, timer6_hold: {=bool:?}, mfcom_hold: {=bool:?}, can0_hold: {=bool:?}, can1_hold: {=bool:?}, timer20_hold: {=bool:?}, timer19_hold: {=bool:?} }}" , self . slp_hold () , self . dslp_hold () , self . stb_hold () , self . fwdgt_hold () , self . wwdgt_hold () , self . timer0_hold () , self . timer1_hold () , self . i2c0_hold () , self . i2c1_hold () , self . timer7_hold () , self . timer5_hold () , self . timer6_hold () , self . mfcom_hold () , self . can0_hold () , self . can1_hold () , self . timer20_hold () , self . timer19_hold ()) } } # [doc = "ID code register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Id (pub u32) ; impl Id { # [doc = "DBG ID code register"]
# [inline (always)]
pub const fn id_code (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "DBG ID code register"]
# [inline (always)]
pub fn set_id_code (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Id { # [inline (always)]
fn default () -> Id { Id (0) } } impl core :: fmt :: Debug for Id { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Id") . field ("id_code" , & self . id_code ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Id { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Id {{ id_code: {=u32:?} }}" , self . id_code ()) } } }