#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Debug support"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dbg { ptr : * mut u8 } unsafe impl Send for Dbg { } unsafe impl Sync for Dbg { } impl Dbg { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "ID code register"]
# [inline (always)]
pub const fn id (self) -> crate :: common :: Reg < regs :: Id , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } } pub mod regs { # [doc = "Control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Sleep mode hold bit"]
# [inline (always)]
pub const fn slp_hold (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Sleep mode hold bit"]
# [inline (always)]
pub fn set_slp_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Deep-sleep mode hold bit"]
# [inline (always)]
pub const fn dslp_hold (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Deep-sleep mode hold bit"]
# [inline (always)]
pub fn set_dslp_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Standby mode hold bit"]
# [inline (always)]
pub const fn stb_hold (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Standby mode hold bit"]
# [inline (always)]
pub fn set_stb_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "FWDGT hold bit"]
# [inline (always)]
pub const fn fwdgt_hold (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "FWDGT hold bit"]
# [inline (always)]
pub fn set_fwdgt_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "WWDGT hold bit"]
# [inline (always)]
pub const fn wwdgt_hold (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "WWDGT hold bit"]
# [inline (always)]
pub fn set_wwdgt_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "TIMER 0 hold bit"]
# [inline (always)]
pub const fn timer0_hold (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "TIMER 0 hold bit"]
# [inline (always)]
pub fn set_timer0_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "TIMER 2 hold bit"]
# [inline (always)]
pub const fn timer2_hold (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "TIMER 2 hold bit"]
# [inline (always)]
pub fn set_timer2_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "TIMER 13 hold bit"]
# [inline (always)]
pub const fn timer13_hold (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "TIMER 13 hold bit"]
# [inline (always)]
pub fn set_timer13_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "I2C0 hold bit"]
# [inline (always)]
pub const fn i2c0_hold (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "I2C0 hold bit"]
# [inline (always)]
pub fn set_i2c0_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "I2C1 hold bit"]
# [inline (always)]
pub const fn i2c1_hold (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "I2C1 hold bit"]
# [inline (always)]
pub fn set_i2c1_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TIMER 15 hold bit"]
# [inline (always)]
pub const fn timer15_hold (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "TIMER 15 hold bit"]
# [inline (always)]
pub fn set_timer15_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "TIMER 16 hold bit"]
# [inline (always)]
pub const fn timer16_hold (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "TIMER 16 hold bit"]
# [inline (always)]
pub fn set_timer16_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("slp_hold" , & self . slp_hold ()) . field ("dslp_hold" , & self . dslp_hold ()) . field ("stb_hold" , & self . stb_hold ()) . field ("fwdgt_hold" , & self . fwdgt_hold ()) . field ("wwdgt_hold" , & self . wwdgt_hold ()) . field ("timer0_hold" , & self . timer0_hold ()) . field ("timer2_hold" , & self . timer2_hold ()) . field ("timer13_hold" , & self . timer13_hold ()) . field ("i2c0_hold" , & self . i2c0_hold ()) . field ("i2c1_hold" , & self . i2c1_hold ()) . field ("timer15_hold" , & self . timer15_hold ()) . field ("timer16_hold" , & self . timer16_hold ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ slp_hold: {=bool:?}, dslp_hold: {=bool:?}, stb_hold: {=bool:?}, fwdgt_hold: {=bool:?}, wwdgt_hold: {=bool:?}, timer0_hold: {=bool:?}, timer2_hold: {=bool:?}, timer13_hold: {=bool:?}, i2c0_hold: {=bool:?}, i2c1_hold: {=bool:?}, timer15_hold: {=bool:?}, timer16_hold: {=bool:?} }}" , self . slp_hold () , self . dslp_hold () , self . stb_hold () , self . fwdgt_hold () , self . wwdgt_hold () , self . timer0_hold () , self . timer2_hold () , self . timer13_hold () , self . i2c0_hold () , self . i2c1_hold () , self . timer15_hold () , self . timer16_hold ()) } } # [doc = "Control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "RTC hold bit"]
# [inline (always)]
pub const fn rtc_hold (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "RTC hold bit"]
# [inline (always)]
pub fn set_rtc_hold (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("rtc_hold" , & self . rtc_hold ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ rtc_hold: {=bool:?} }}" , self . rtc_hold ()) } } # [doc = "ID code register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Id (pub u32) ; impl Id { # [doc = "DBG ID code register"]
# [inline (always)]
pub const fn id_code (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "DBG ID code register"]
# [inline (always)]
pub fn set_id_code (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Id { # [inline (always)]
fn default () -> Id { Id (0) } } impl core :: fmt :: Debug for Id { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Id") . field ("id_code" , & self . id_code ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Id { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Id {{ id_code: {=u32:?} }}" , self . id_code ()) } } }