#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmt { ptr : * mut u8 } unsafe impl Send for EdimTfmt { } unsafe impl Sync for EdimTfmt { } impl EdimTfmt { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn edim_tfmt_dataid (self) -> crate :: common :: Reg < regs :: EdimTfmtDataid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_eeprom (self) -> crate :: common :: Reg < regs :: EdimTfmtEeprom , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_cfg (self) -> crate :: common :: Reg < regs :: EdimTfmtCfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_swt (self) -> crate :: common :: Reg < regs :: EdimTfmtSwt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [inline (always)]
pub const fn edim_tfmt_stat (self) -> crate :: common :: Reg < regs :: EdimTfmtStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_inten (self) -> crate :: common :: Reg < regs :: EdimTfmtInten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_rdata_0 (self) -> crate :: common :: Reg < regs :: EdimTfmtRdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_rdata_1 (self) -> crate :: common :: Reg < regs :: EdimTfmtRdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [inline (always)]
pub const fn edim_tfmt_rdata_2 (self) -> crate :: common :: Reg < regs :: EdimTfmtRdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_rdata_3 (self) -> crate :: common :: Reg < regs :: EdimTfmtRdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [inline (always)]
pub const fn edim_tfmt_fifodata (self) -> crate :: common :: Reg < regs :: EdimTfmtFifodata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0128usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtCfg (pub u32) ; impl EdimTfmtCfg { # [inline (always)]
pub const fn edim_tfmt_cfg_transtsel (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_transtsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_dfen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_dfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_fifofh (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_fifofh (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_dfen0 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_dfen0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_dfen_mask (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [inline (always)]
pub fn set_edim_tfmt_cfg_dfen_mask (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_dfen1 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_dfen1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_dfen2 (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_dfen2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [inline (always)]
pub const fn edim_tfmt_cfg_dfen3 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_cfg_dfen3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for EdimTfmtCfg { # [inline (always)]
fn default () -> EdimTfmtCfg { EdimTfmtCfg (0) } } impl core :: fmt :: Debug for EdimTfmtCfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtCfg") . field ("edim_tfmt_cfg_transtsel" , & self . edim_tfmt_cfg_transtsel ()) . field ("edim_tfmt_cfg_dfen" , & self . edim_tfmt_cfg_dfen ()) . field ("edim_tfmt_cfg_fifofh" , & self . edim_tfmt_cfg_fifofh ()) . field ("edim_tfmt_cfg_dfen0" , & self . edim_tfmt_cfg_dfen0 ()) . field ("edim_tfmt_cfg_dfen_mask" , & self . edim_tfmt_cfg_dfen_mask ()) . field ("edim_tfmt_cfg_dfen1" , & self . edim_tfmt_cfg_dfen1 ()) . field ("edim_tfmt_cfg_dfen2" , & self . edim_tfmt_cfg_dfen2 ()) . field ("edim_tfmt_cfg_dfen3" , & self . edim_tfmt_cfg_dfen3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtCfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtCfg {{ edim_tfmt_cfg_transtsel: {=bool:?}, edim_tfmt_cfg_dfen: {=bool:?}, edim_tfmt_cfg_fifofh: {=bool:?}, edim_tfmt_cfg_dfen0: {=bool:?}, edim_tfmt_cfg_dfen_mask: {=u8:?}, edim_tfmt_cfg_dfen1: {=bool:?}, edim_tfmt_cfg_dfen2: {=bool:?}, edim_tfmt_cfg_dfen3: {=bool:?} }}" , self . edim_tfmt_cfg_transtsel () , self . edim_tfmt_cfg_dfen () , self . edim_tfmt_cfg_fifofh () , self . edim_tfmt_cfg_dfen0 () , self . edim_tfmt_cfg_dfen_mask () , self . edim_tfmt_cfg_dfen1 () , self . edim_tfmt_cfg_dfen2 () , self . edim_tfmt_cfg_dfen3 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtDataid (pub u32) ; impl EdimTfmtDataid { # [inline (always)]
pub const fn edim_tfmt_dataid_cc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub fn set_edim_tfmt_dataid_cc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } } impl Default for EdimTfmtDataid { # [inline (always)]
fn default () -> EdimTfmtDataid { EdimTfmtDataid (0) } } impl core :: fmt :: Debug for EdimTfmtDataid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtDataid") . field ("edim_tfmt_dataid_cc" , & self . edim_tfmt_dataid_cc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtDataid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtDataid {{ edim_tfmt_dataid_cc: {=u8:?} }}" , self . edim_tfmt_dataid_cc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtEeprom (pub u32) ; impl EdimTfmtEeprom { # [inline (always)]
pub const fn edim_tfmt_eeprom_eepromdata (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub fn set_edim_tfmt_eeprom_eepromdata (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [inline (always)]
pub const fn edim_tfmt_eeprom_eepromaddr (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x7f ; val as u8 } # [inline (always)]
pub fn set_edim_tfmt_eeprom_eepromaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 8usize)) | (((val as u32) & 0x7f) << 8usize) ; } } impl Default for EdimTfmtEeprom { # [inline (always)]
fn default () -> EdimTfmtEeprom { EdimTfmtEeprom (0) } } impl core :: fmt :: Debug for EdimTfmtEeprom { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtEeprom") . field ("edim_tfmt_eeprom_eepromdata" , & self . edim_tfmt_eeprom_eepromdata ()) . field ("edim_tfmt_eeprom_eepromaddr" , & self . edim_tfmt_eeprom_eepromaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtEeprom { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtEeprom {{ edim_tfmt_eeprom_eepromdata: {=u8:?}, edim_tfmt_eeprom_eepromaddr: {=u8:?} }}" , self . edim_tfmt_eeprom_eepromdata () , self . edim_tfmt_eeprom_eepromaddr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtFifodata (pub u32) ; impl EdimTfmtFifodata { # [inline (always)]
pub const fn edim_tfmt_fifodata_fifodata (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub fn set_edim_tfmt_fifodata_fifodata (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for EdimTfmtFifodata { # [inline (always)]
fn default () -> EdimTfmtFifodata { EdimTfmtFifodata (0) } } impl core :: fmt :: Debug for EdimTfmtFifodata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtFifodata") . field ("edim_tfmt_fifodata_fifodata" , & self . edim_tfmt_fifodata_fifodata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtFifodata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtFifodata {{ edim_tfmt_fifodata_fifodata: {=u32:?} }}" , self . edim_tfmt_fifodata_fifodata ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtInten (pub u32) ; impl EdimTfmtInten { # [inline (always)]
pub const fn edim_tfmt_inten_eocie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_eocie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_toie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_toie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_crcie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_crcie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_sdelie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_sdelie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_pctlie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_pctlie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_ccie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_ccie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_eeprombusyie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_eeprombusyie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_delie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_delie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_preqie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_preqie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_alrmie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_alrmie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_cntie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_cntie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_fifoovrie (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_fifoovrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_fifounrie (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_fifounrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [inline (always)]
pub const fn edim_tfmt_inten_dmatoie (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_inten_dmatoie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for EdimTfmtInten { # [inline (always)]
fn default () -> EdimTfmtInten { EdimTfmtInten (0) } } impl core :: fmt :: Debug for EdimTfmtInten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtInten") . field ("edim_tfmt_inten_eocie" , & self . edim_tfmt_inten_eocie ()) . field ("edim_tfmt_inten_toie" , & self . edim_tfmt_inten_toie ()) . field ("edim_tfmt_inten_crcie" , & self . edim_tfmt_inten_crcie ()) . field ("edim_tfmt_inten_sdelie" , & self . edim_tfmt_inten_sdelie ()) . field ("edim_tfmt_inten_pctlie" , & self . edim_tfmt_inten_pctlie ()) . field ("edim_tfmt_inten_ccie" , & self . edim_tfmt_inten_ccie ()) . field ("edim_tfmt_inten_eeprombusyie" , & self . edim_tfmt_inten_eeprombusyie ()) . field ("edim_tfmt_inten_delie" , & self . edim_tfmt_inten_delie ()) . field ("edim_tfmt_inten_preqie" , & self . edim_tfmt_inten_preqie ()) . field ("edim_tfmt_inten_alrmie" , & self . edim_tfmt_inten_alrmie ()) . field ("edim_tfmt_inten_cntie" , & self . edim_tfmt_inten_cntie ()) . field ("edim_tfmt_inten_fifoovrie" , & self . edim_tfmt_inten_fifoovrie ()) . field ("edim_tfmt_inten_fifounrie" , & self . edim_tfmt_inten_fifounrie ()) . field ("edim_tfmt_inten_dmatoie" , & self . edim_tfmt_inten_dmatoie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtInten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtInten {{ edim_tfmt_inten_eocie: {=bool:?}, edim_tfmt_inten_toie: {=bool:?}, edim_tfmt_inten_crcie: {=bool:?}, edim_tfmt_inten_sdelie: {=bool:?}, edim_tfmt_inten_pctlie: {=bool:?}, edim_tfmt_inten_ccie: {=bool:?}, edim_tfmt_inten_eeprombusyie: {=bool:?}, edim_tfmt_inten_delie: {=bool:?}, edim_tfmt_inten_preqie: {=bool:?}, edim_tfmt_inten_alrmie: {=bool:?}, edim_tfmt_inten_cntie: {=bool:?}, edim_tfmt_inten_fifoovrie: {=bool:?}, edim_tfmt_inten_fifounrie: {=bool:?}, edim_tfmt_inten_dmatoie: {=bool:?} }}" , self . edim_tfmt_inten_eocie () , self . edim_tfmt_inten_toie () , self . edim_tfmt_inten_crcie () , self . edim_tfmt_inten_sdelie () , self . edim_tfmt_inten_pctlie () , self . edim_tfmt_inten_ccie () , self . edim_tfmt_inten_eeprombusyie () , self . edim_tfmt_inten_delie () , self . edim_tfmt_inten_preqie () , self . edim_tfmt_inten_alrmie () , self . edim_tfmt_inten_cntie () , self . edim_tfmt_inten_fifoovrie () , self . edim_tfmt_inten_fifounrie () , self . edim_tfmt_inten_dmatoie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtRdata (pub u32) ; impl EdimTfmtRdata { # [inline (always)]
pub const fn edim_tfmt_rdata_rdata (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub fn set_edim_tfmt_rdata_rdata (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for EdimTfmtRdata { # [inline (always)]
fn default () -> EdimTfmtRdata { EdimTfmtRdata (0) } } impl core :: fmt :: Debug for EdimTfmtRdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtRdata") . field ("edim_tfmt_rdata_rdata" , & self . edim_tfmt_rdata_rdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtRdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtRdata {{ edim_tfmt_rdata_rdata: {=u32:?} }}" , self . edim_tfmt_rdata_rdata ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtStat (pub u32) ; impl EdimTfmtStat { # [inline (always)]
pub const fn edim_tfmt_stat_eoc (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_eoc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_tbusyf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_tbusyf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_rbusyf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_rbusyf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_toif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_toif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_crcif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_crcif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_sdelif (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_sdelif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_pctlif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_pctlif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_ccif (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_ccif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_eeprombusyif (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_eeprombusyif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_delif (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_delif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_preqif (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_preqif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_alrmif (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_alrmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_cntif (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_cntif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_fifoovrif (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_fifoovrif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_fifounrif (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_fifounrif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [inline (always)]
pub const fn edim_tfmt_stat_dmatoif (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_stat_dmatoif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for EdimTfmtStat { # [inline (always)]
fn default () -> EdimTfmtStat { EdimTfmtStat (0) } } impl core :: fmt :: Debug for EdimTfmtStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtStat") . field ("edim_tfmt_stat_eoc" , & self . edim_tfmt_stat_eoc ()) . field ("edim_tfmt_stat_tbusyf" , & self . edim_tfmt_stat_tbusyf ()) . field ("edim_tfmt_stat_rbusyf" , & self . edim_tfmt_stat_rbusyf ()) . field ("edim_tfmt_stat_toif" , & self . edim_tfmt_stat_toif ()) . field ("edim_tfmt_stat_crcif" , & self . edim_tfmt_stat_crcif ()) . field ("edim_tfmt_stat_sdelif" , & self . edim_tfmt_stat_sdelif ()) . field ("edim_tfmt_stat_pctlif" , & self . edim_tfmt_stat_pctlif ()) . field ("edim_tfmt_stat_ccif" , & self . edim_tfmt_stat_ccif ()) . field ("edim_tfmt_stat_eeprombusyif" , & self . edim_tfmt_stat_eeprombusyif ()) . field ("edim_tfmt_stat_delif" , & self . edim_tfmt_stat_delif ()) . field ("edim_tfmt_stat_preqif" , & self . edim_tfmt_stat_preqif ()) . field ("edim_tfmt_stat_alrmif" , & self . edim_tfmt_stat_alrmif ()) . field ("edim_tfmt_stat_cntif" , & self . edim_tfmt_stat_cntif ()) . field ("edim_tfmt_stat_fifoovrif" , & self . edim_tfmt_stat_fifoovrif ()) . field ("edim_tfmt_stat_fifounrif" , & self . edim_tfmt_stat_fifounrif ()) . field ("edim_tfmt_stat_dmatoif" , & self . edim_tfmt_stat_dmatoif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtStat {{ edim_tfmt_stat_eoc: {=bool:?}, edim_tfmt_stat_tbusyf: {=bool:?}, edim_tfmt_stat_rbusyf: {=bool:?}, edim_tfmt_stat_toif: {=bool:?}, edim_tfmt_stat_crcif: {=bool:?}, edim_tfmt_stat_sdelif: {=bool:?}, edim_tfmt_stat_pctlif: {=bool:?}, edim_tfmt_stat_ccif: {=bool:?}, edim_tfmt_stat_eeprombusyif: {=bool:?}, edim_tfmt_stat_delif: {=bool:?}, edim_tfmt_stat_preqif: {=bool:?}, edim_tfmt_stat_alrmif: {=bool:?}, edim_tfmt_stat_cntif: {=bool:?}, edim_tfmt_stat_fifoovrif: {=bool:?}, edim_tfmt_stat_fifounrif: {=bool:?}, edim_tfmt_stat_dmatoif: {=bool:?} }}" , self . edim_tfmt_stat_eoc () , self . edim_tfmt_stat_tbusyf () , self . edim_tfmt_stat_rbusyf () , self . edim_tfmt_stat_toif () , self . edim_tfmt_stat_crcif () , self . edim_tfmt_stat_sdelif () , self . edim_tfmt_stat_pctlif () , self . edim_tfmt_stat_ccif () , self . edim_tfmt_stat_eeprombusyif () , self . edim_tfmt_stat_delif () , self . edim_tfmt_stat_preqif () , self . edim_tfmt_stat_alrmif () , self . edim_tfmt_stat_cntif () , self . edim_tfmt_stat_fifoovrif () , self . edim_tfmt_stat_fifounrif () , self . edim_tfmt_stat_dmatoif ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EdimTfmtSwt (pub u32) ; impl EdimTfmtSwt { # [inline (always)]
pub const fn edim_tfmt_swt_swtr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_edim_tfmt_swt_swtr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for EdimTfmtSwt { # [inline (always)]
fn default () -> EdimTfmtSwt { EdimTfmtSwt (0) } } impl core :: fmt :: Debug for EdimTfmtSwt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EdimTfmtSwt") . field ("edim_tfmt_swt_swtr" , & self . edim_tfmt_swt_swtr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EdimTfmtSwt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EdimTfmtSwt {{ edim_tfmt_swt_swtr: {=bool:?} }}" , self . edim_tfmt_swt_swtr ()) } } }