#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Efuse { ptr : * mut u8 } unsafe impl Send for Efuse { } unsafe impl Sync for Efuse { } impl Efuse { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn efuse_cs (self) -> crate :: common :: Reg < regs :: EfuseCs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn efuse_addr (self) -> crate :: common :: Reg < regs :: EfuseAddr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn efuse_ctl0 (self) -> crate :: common :: Reg < regs :: EfuseCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn efuse_ctl1 (self) -> crate :: common :: Reg < regs :: EfuseCtl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn efuse_fpctl (self) -> crate :: common :: Reg < regs :: EfuseFpctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn efuse_userctl (self) -> crate :: common :: Reg < regs :: EfuseUserctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn efuse_res0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn efuse_res1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn efuse_res2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn efuse_aeskey0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn efuse_aeskey1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn efuse_aeskey2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn efuse_aeskey3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x48usize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x4cusize) as _) } } # [inline (always)]
pub const fn efuse_rotpkkey7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x50usize) as _) } } # [inline (always)]
pub const fn efuse_puid0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x54usize) as _) } } # [inline (always)]
pub const fn efuse_puid1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x58usize) as _) } } # [inline (always)]
pub const fn efuse_puid2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x5cusize) as _) } } # [inline (always)]
pub const fn efuse_puid3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x60usize) as _) } } # [inline (always)]
pub const fn efuse_hukkey0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x64usize) as _) } } # [inline (always)]
pub const fn efuse_hukkey1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x68usize) as _) } } # [inline (always)]
pub const fn efuse_hukkey2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x6cusize) as _) } } # [inline (always)]
pub const fn efuse_hukkey3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x70usize) as _) } } # [inline (always)]
pub const fn efuse_user_data0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x74usize) as _) } } # [inline (always)]
pub const fn efuse_user_data1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x78usize) as _) } } # [inline (always)]
pub const fn efuse_user_data2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x7cusize) as _) } } # [inline (always)]
pub const fn efuse_user_data3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x80usize) as _) } } # [inline (always)]
pub const fn efuse_user_data4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x84usize) as _) } } # [inline (always)]
pub const fn efuse_user_data5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x88usize) as _) } } # [inline (always)]
pub const fn efuse_user_data6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x8cusize) as _) } } # [inline (always)]
pub const fn efuse_user_data7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x90usize) as _) } } # [inline (always)]
pub const fn efuse_bootaddr (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0124usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseAddr (pub u32) ; impl EfuseAddr { # [must_use]
# [inline (always)]
pub const fn efuse_addr_efaddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_efuse_addr_efaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_addr_efsize (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_efuse_addr_efsize (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 8usize)) | (((val as u32) & 0x3f) << 8usize) ; } } impl Default for EfuseAddr { # [inline (always)]
fn default () -> EfuseAddr { EfuseAddr (0) } } impl core :: fmt :: Debug for EfuseAddr { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseAddr") . field ("efuse_addr_efaddr" , & self . efuse_addr_efaddr ()) . field ("efuse_addr_efsize" , & self . efuse_addr_efsize ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseAddr { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseAddr {{ efuse_addr_efaddr: {=u8:?}, efuse_addr_efsize: {=u8:?} }}" , self . efuse_addr_efaddr () , self . efuse_addr_efsize ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseCs (pub u32) ; impl EfuseCs { # [must_use]
# [inline (always)]
pub const fn efuse_cs_efstr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_efstr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_efrw (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_efrw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_pgif (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_pgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_rdif (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_rdif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_ovberif (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_ovberif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_pgie (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_pgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_rdie (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_rdie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_ovberie (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_ovberie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_pgic (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_pgic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_rdic (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_rdic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_ovberic (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_ovberic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } } impl Default for EfuseCs { # [inline (always)]
fn default () -> EfuseCs { EfuseCs (0) } } impl core :: fmt :: Debug for EfuseCs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseCs") . field ("efuse_cs_efstr" , & self . efuse_cs_efstr ()) . field ("efuse_cs_efrw" , & self . efuse_cs_efrw ()) . field ("efuse_cs_pgif" , & self . efuse_cs_pgif ()) . field ("efuse_cs_rdif" , & self . efuse_cs_rdif ()) . field ("efuse_cs_ovberif" , & self . efuse_cs_ovberif ()) . field ("efuse_cs_pgie" , & self . efuse_cs_pgie ()) . field ("efuse_cs_rdie" , & self . efuse_cs_rdie ()) . field ("efuse_cs_ovberie" , & self . efuse_cs_ovberie ()) . field ("efuse_cs_pgic" , & self . efuse_cs_pgic ()) . field ("efuse_cs_rdic" , & self . efuse_cs_rdic ()) . field ("efuse_cs_ovberic" , & self . efuse_cs_ovberic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseCs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseCs {{ efuse_cs_efstr: {=bool:?}, efuse_cs_efrw: {=bool:?}, efuse_cs_pgif: {=bool:?}, efuse_cs_rdif: {=bool:?}, efuse_cs_ovberif: {=bool:?}, efuse_cs_pgie: {=bool:?}, efuse_cs_rdie: {=bool:?}, efuse_cs_ovberie: {=bool:?}, efuse_cs_pgic: {=bool:?}, efuse_cs_rdic: {=bool:?}, efuse_cs_ovberic: {=bool:?} }}" , self . efuse_cs_efstr () , self . efuse_cs_efrw () , self . efuse_cs_pgif () , self . efuse_cs_rdif () , self . efuse_cs_ovberif () , self . efuse_cs_pgie () , self . efuse_cs_rdie () , self . efuse_cs_ovberie () , self . efuse_cs_pgic () , self . efuse_cs_rdic () , self . efuse_cs_ovberic ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseCtl0 (pub u32) ; impl EfuseCtl0 { # [must_use]
# [inline (always)]
pub const fn efuse_ctl0_efsb (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl0_efsb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl0_efbootlk (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl0_efbootlk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl0_efboot1 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl0_efboot1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl0_swboot1 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl0_swboot1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl0_efboot0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl0_efboot0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl0_swboot0 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl0_swboot0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for EfuseCtl0 { # [inline (always)]
fn default () -> EfuseCtl0 { EfuseCtl0 (0) } } impl core :: fmt :: Debug for EfuseCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseCtl0") . field ("efuse_ctl0_efsb" , & self . efuse_ctl0_efsb ()) . field ("efuse_ctl0_efbootlk" , & self . efuse_ctl0_efbootlk ()) . field ("efuse_ctl0_efboot1" , & self . efuse_ctl0_efboot1 ()) . field ("efuse_ctl0_swboot1" , & self . efuse_ctl0_swboot1 ()) . field ("efuse_ctl0_efboot0" , & self . efuse_ctl0_efboot0 ()) . field ("efuse_ctl0_swboot0" , & self . efuse_ctl0_swboot0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseCtl0 {{ efuse_ctl0_efsb: {=bool:?}, efuse_ctl0_efbootlk: {=bool:?}, efuse_ctl0_efboot1: {=bool:?}, efuse_ctl0_swboot1: {=bool:?}, efuse_ctl0_efboot0: {=bool:?}, efuse_ctl0_swboot0: {=bool:?} }}" , self . efuse_ctl0_efsb () , self . efuse_ctl0_efbootlk () , self . efuse_ctl0_efboot1 () , self . efuse_ctl0_swboot1 () , self . efuse_ctl0_efboot0 () , self . efuse_ctl0_swboot0 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseCtl1 (pub u32) ; impl EfuseCtl1 { # [must_use]
# [inline (always)]
pub const fn efuse_ctl1_ndbg (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl1_ndbg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl1_rotlk (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl1_rotlk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl1_vfimg (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl1_vfimg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl1_vfcert (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl1_vfcert (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for EfuseCtl1 { # [inline (always)]
fn default () -> EfuseCtl1 { EfuseCtl1 (0) } } impl core :: fmt :: Debug for EfuseCtl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseCtl1") . field ("efuse_ctl1_ndbg" , & self . efuse_ctl1_ndbg ()) . field ("efuse_ctl1_rotlk" , & self . efuse_ctl1_rotlk ()) . field ("efuse_ctl1_vfimg" , & self . efuse_ctl1_vfimg ()) . field ("efuse_ctl1_vfcert" , & self . efuse_ctl1_vfcert ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseCtl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseCtl1 {{ efuse_ctl1_ndbg: {=bool:?}, efuse_ctl1_rotlk: {=bool:?}, efuse_ctl1_vfimg: {=bool:?}, efuse_ctl1_vfcert: {=bool:?} }}" , self . efuse_ctl1_ndbg () , self . efuse_ctl1_rotlk () , self . efuse_ctl1_vfimg () , self . efuse_ctl1_vfcert ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseFpctl (pub u32) ; impl EfuseFpctl { # [must_use]
# [inline (always)]
pub const fn efuse_fpctl_fp (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_efuse_fpctl_fp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } } impl Default for EfuseFpctl { # [inline (always)]
fn default () -> EfuseFpctl { EfuseFpctl (0) } } impl core :: fmt :: Debug for EfuseFpctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseFpctl") . field ("efuse_fpctl_fp" , & self . efuse_fpctl_fp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseFpctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseFpctl {{ efuse_fpctl_fp: {=u8:?} }}" , self . efuse_fpctl_fp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseUserctl (pub u32) ; impl EfuseUserctl { # [must_use]
# [inline (always)]
pub const fn efuse_userctl_sbclk (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_userctl_sbclk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_userctl_loguart (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_userctl_loguart (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_userctl_efoplk (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_userctl_efoplk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_userctl_aesen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_userctl_aesen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_userctl_udlk (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_userctl_udlk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for EfuseUserctl { # [inline (always)]
fn default () -> EfuseUserctl { EfuseUserctl (0) } } impl core :: fmt :: Debug for EfuseUserctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseUserctl") . field ("efuse_userctl_sbclk" , & self . efuse_userctl_sbclk ()) . field ("efuse_userctl_loguart" , & self . efuse_userctl_loguart ()) . field ("efuse_userctl_efoplk" , & self . efuse_userctl_efoplk ()) . field ("efuse_userctl_aesen" , & self . efuse_userctl_aesen ()) . field ("efuse_userctl_udlk" , & self . efuse_userctl_udlk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseUserctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseUserctl {{ efuse_userctl_sbclk: {=bool:?}, efuse_userctl_loguart: {=bool:?}, efuse_userctl_efoplk: {=bool:?}, efuse_userctl_aesen: {=bool:?}, efuse_userctl_udlk: {=bool:?} }}" , self . efuse_userctl_sbclk () , self . efuse_userctl_loguart () , self . efuse_userctl_efoplk () , self . efuse_userctl_aesen () , self . efuse_userctl_udlk ()) } } }