#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Exmc { ptr : * mut u8 } unsafe impl Send for Exmc { } unsafe impl Sync for Exmc { } impl Exmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn exmc_pnctl (self) -> crate :: common :: Reg < regs :: ExmcPnctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn exmc_pntcfg (self) -> crate :: common :: Reg < regs :: ExmcPntcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn exmc_nctl (self) -> crate :: common :: Reg < regs :: ExmcNctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x60usize) as _) } } # [inline (always)]
pub const fn exmc_nstat (self) -> crate :: common :: Reg < regs :: ExmcNstat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x64usize) as _) } } # [inline (always)]
pub const fn exmc_nctcfg (self) -> crate :: common :: Reg < regs :: ExmcNctcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x68usize) as _) } } # [inline (always)]
pub const fn exmc_natcfg (self) -> crate :: common :: Reg < regs :: ExmcNatcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x6cusize) as _) } } # [inline (always)]
pub const fn exmc_necc (self) -> crate :: common :: Reg < regs :: ExmcNecc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x74usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcNatcfg (pub u32) ; impl ExmcNatcfg { # [must_use]
# [inline (always)]
pub const fn exmc_natcfg_attset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_natcfg_attset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_natcfg_attwait (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_natcfg_attwait (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_natcfg_atthld (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_natcfg_atthld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_natcfg_atthiz (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_natcfg_atthiz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for ExmcNatcfg { # [inline (always)]
fn default () -> ExmcNatcfg { ExmcNatcfg (0) } } impl core :: fmt :: Debug for ExmcNatcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcNatcfg") . field ("exmc_natcfg_attset" , & self . exmc_natcfg_attset ()) . field ("exmc_natcfg_attwait" , & self . exmc_natcfg_attwait ()) . field ("exmc_natcfg_atthld" , & self . exmc_natcfg_atthld ()) . field ("exmc_natcfg_atthiz" , & self . exmc_natcfg_atthiz ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcNatcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcNatcfg {{ exmc_natcfg_attset: {=u8:?}, exmc_natcfg_attwait: {=u8:?}, exmc_natcfg_atthld: {=u8:?}, exmc_natcfg_atthiz: {=u8:?} }}" , self . exmc_natcfg_attset () , self . exmc_natcfg_attwait () , self . exmc_natcfg_atthld () , self . exmc_natcfg_atthiz ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcNctcfg (pub u32) ; impl ExmcNctcfg { # [must_use]
# [inline (always)]
pub const fn exmc_nctcfg_comset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctcfg_comset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctcfg_comwait (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctcfg_comwait (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctcfg_comhld (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctcfg_comhld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctcfg_comhiz (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctcfg_comhiz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for ExmcNctcfg { # [inline (always)]
fn default () -> ExmcNctcfg { ExmcNctcfg (0) } } impl core :: fmt :: Debug for ExmcNctcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcNctcfg") . field ("exmc_nctcfg_comset" , & self . exmc_nctcfg_comset ()) . field ("exmc_nctcfg_comwait" , & self . exmc_nctcfg_comwait ()) . field ("exmc_nctcfg_comhld" , & self . exmc_nctcfg_comhld ()) . field ("exmc_nctcfg_comhiz" , & self . exmc_nctcfg_comhiz ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcNctcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcNctcfg {{ exmc_nctcfg_comset: {=u8:?}, exmc_nctcfg_comwait: {=u8:?}, exmc_nctcfg_comhld: {=u8:?}, exmc_nctcfg_comhiz: {=u8:?} }}" , self . exmc_nctcfg_comset () , self . exmc_nctcfg_comwait () , self . exmc_nctcfg_comhld () , self . exmc_nctcfg_comhiz ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcNctl (pub u32) ; impl ExmcNctl { # [must_use]
# [inline (always)]
pub const fn exmc_nctl_ndwten (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_nctl_ndwten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_ndbken (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_nctl_ndbken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_ndtp (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_nctl_ndtp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_ndw (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctl_ndw (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_eccen (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_nctl_eccen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_ctr (& self) -> u8 { let val = (self . 0 >> 9usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctl_ctr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 9usize)) | (((val as u32) & 0x0f) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_atr (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctl_atr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 13usize)) | (((val as u32) & 0x0f) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_nctl_eccsz (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_exmc_nctl_eccsz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 17usize)) | (((val as u32) & 0x07) << 17usize) ; } } impl Default for ExmcNctl { # [inline (always)]
fn default () -> ExmcNctl { ExmcNctl (0) } } impl core :: fmt :: Debug for ExmcNctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcNctl") . field ("exmc_nctl_ndwten" , & self . exmc_nctl_ndwten ()) . field ("exmc_nctl_ndbken" , & self . exmc_nctl_ndbken ()) . field ("exmc_nctl_ndtp" , & self . exmc_nctl_ndtp ()) . field ("exmc_nctl_ndw" , & self . exmc_nctl_ndw ()) . field ("exmc_nctl_eccen" , & self . exmc_nctl_eccen ()) . field ("exmc_nctl_ctr" , & self . exmc_nctl_ctr ()) . field ("exmc_nctl_atr" , & self . exmc_nctl_atr ()) . field ("exmc_nctl_eccsz" , & self . exmc_nctl_eccsz ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcNctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcNctl {{ exmc_nctl_ndwten: {=bool:?}, exmc_nctl_ndbken: {=bool:?}, exmc_nctl_ndtp: {=bool:?}, exmc_nctl_ndw: {=u8:?}, exmc_nctl_eccen: {=bool:?}, exmc_nctl_ctr: {=u8:?}, exmc_nctl_atr: {=u8:?}, exmc_nctl_eccsz: {=u8:?} }}" , self . exmc_nctl_ndwten () , self . exmc_nctl_ndbken () , self . exmc_nctl_ndtp () , self . exmc_nctl_ndw () , self . exmc_nctl_eccen () , self . exmc_nctl_ctr () , self . exmc_nctl_atr () , self . exmc_nctl_eccsz ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcNecc (pub u32) ; impl ExmcNecc { # [must_use]
# [inline (always)]
pub const fn exmc_necc_ecc (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_exmc_necc_ecc (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for ExmcNecc { # [inline (always)]
fn default () -> ExmcNecc { ExmcNecc (0) } } impl core :: fmt :: Debug for ExmcNecc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcNecc") . field ("exmc_necc_ecc" , & self . exmc_necc_ecc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcNecc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcNecc {{ exmc_necc_ecc: {=u32:?} }}" , self . exmc_necc_ecc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcNstat (pub u32) ; impl ExmcNstat { # [must_use]
# [inline (always)]
pub const fn exmc_nstat_ffept (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_nstat_ffept (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for ExmcNstat { # [inline (always)]
fn default () -> ExmcNstat { ExmcNstat (0) } } impl core :: fmt :: Debug for ExmcNstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcNstat") . field ("exmc_nstat_ffept" , & self . exmc_nstat_ffept ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcNstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcNstat {{ exmc_nstat_ffept: {=bool:?} }}" , self . exmc_nstat_ffept ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcPnctl (pub u32) ; impl ExmcPnctl { # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrbken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_nrbken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrmux (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_nrmux (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrtp (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_pnctl_nrtp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrw (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_pnctl_nrw (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nren (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_nren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_sbrsten (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_sbrsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrwtpol (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_nrwtpol (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_wrapen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_wrapen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrwtcfg (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_nrwtcfg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_wren (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_wren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_nrwten (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_nrwten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_asyncwait (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_asyncwait (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_cps (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_exmc_pnctl_cps (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pnctl_syncwr (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_pnctl_syncwr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } } impl Default for ExmcPnctl { # [inline (always)]
fn default () -> ExmcPnctl { ExmcPnctl (0) } } impl core :: fmt :: Debug for ExmcPnctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcPnctl") . field ("exmc_pnctl_nrbken" , & self . exmc_pnctl_nrbken ()) . field ("exmc_pnctl_nrmux" , & self . exmc_pnctl_nrmux ()) . field ("exmc_pnctl_nrtp" , & self . exmc_pnctl_nrtp ()) . field ("exmc_pnctl_nrw" , & self . exmc_pnctl_nrw ()) . field ("exmc_pnctl_nren" , & self . exmc_pnctl_nren ()) . field ("exmc_pnctl_sbrsten" , & self . exmc_pnctl_sbrsten ()) . field ("exmc_pnctl_nrwtpol" , & self . exmc_pnctl_nrwtpol ()) . field ("exmc_pnctl_wrapen" , & self . exmc_pnctl_wrapen ()) . field ("exmc_pnctl_nrwtcfg" , & self . exmc_pnctl_nrwtcfg ()) . field ("exmc_pnctl_wren" , & self . exmc_pnctl_wren ()) . field ("exmc_pnctl_nrwten" , & self . exmc_pnctl_nrwten ()) . field ("exmc_pnctl_asyncwait" , & self . exmc_pnctl_asyncwait ()) . field ("exmc_pnctl_cps" , & self . exmc_pnctl_cps ()) . field ("exmc_pnctl_syncwr" , & self . exmc_pnctl_syncwr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcPnctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcPnctl {{ exmc_pnctl_nrbken: {=bool:?}, exmc_pnctl_nrmux: {=bool:?}, exmc_pnctl_nrtp: {=u8:?}, exmc_pnctl_nrw: {=u8:?}, exmc_pnctl_nren: {=bool:?}, exmc_pnctl_sbrsten: {=bool:?}, exmc_pnctl_nrwtpol: {=bool:?}, exmc_pnctl_wrapen: {=bool:?}, exmc_pnctl_nrwtcfg: {=bool:?}, exmc_pnctl_wren: {=bool:?}, exmc_pnctl_nrwten: {=bool:?}, exmc_pnctl_asyncwait: {=bool:?}, exmc_pnctl_cps: {=u8:?}, exmc_pnctl_syncwr: {=bool:?} }}" , self . exmc_pnctl_nrbken () , self . exmc_pnctl_nrmux () , self . exmc_pnctl_nrtp () , self . exmc_pnctl_nrw () , self . exmc_pnctl_nren () , self . exmc_pnctl_sbrsten () , self . exmc_pnctl_nrwtpol () , self . exmc_pnctl_wrapen () , self . exmc_pnctl_nrwtcfg () , self . exmc_pnctl_wren () , self . exmc_pnctl_nrwten () , self . exmc_pnctl_asyncwait () , self . exmc_pnctl_cps () , self . exmc_pnctl_syncwr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcPntcfg (pub u32) ; impl ExmcPntcfg { # [must_use]
# [inline (always)]
pub const fn exmc_pntcfg_aset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_pntcfg_aset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pntcfg_ahld (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_pntcfg_ahld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pntcfg_dset (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_pntcfg_dset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pntcfg_buslat (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_pntcfg_buslat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pntcfg_ckdiv (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_pntcfg_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_pntcfg_dlat (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_pntcfg_dlat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } } impl Default for ExmcPntcfg { # [inline (always)]
fn default () -> ExmcPntcfg { ExmcPntcfg (0) } } impl core :: fmt :: Debug for ExmcPntcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcPntcfg") . field ("exmc_pntcfg_aset" , & self . exmc_pntcfg_aset ()) . field ("exmc_pntcfg_ahld" , & self . exmc_pntcfg_ahld ()) . field ("exmc_pntcfg_dset" , & self . exmc_pntcfg_dset ()) . field ("exmc_pntcfg_buslat" , & self . exmc_pntcfg_buslat ()) . field ("exmc_pntcfg_ckdiv" , & self . exmc_pntcfg_ckdiv ()) . field ("exmc_pntcfg_dlat" , & self . exmc_pntcfg_dlat ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcPntcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcPntcfg {{ exmc_pntcfg_aset: {=u8:?}, exmc_pntcfg_ahld: {=u8:?}, exmc_pntcfg_dset: {=u8:?}, exmc_pntcfg_buslat: {=u8:?}, exmc_pntcfg_ckdiv: {=u8:?}, exmc_pntcfg_dlat: {=u8:?} }}" , self . exmc_pntcfg_aset () , self . exmc_pntcfg_ahld () , self . exmc_pntcfg_dset () , self . exmc_pntcfg_buslat () , self . exmc_pntcfg_ckdiv () , self . exmc_pntcfg_dlat ()) } } }