#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Exmc { ptr : * mut u8 } unsafe impl Send for Exmc { } unsafe impl Sync for Exmc { } impl Exmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn exmc_snctl (self) -> crate :: common :: Reg < regs :: ExmcSnctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn exmc_sntcfg (self) -> crate :: common :: Reg < regs :: ExmcSntcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn exmc_snwtcfg (self) -> crate :: common :: Reg < regs :: ExmcSnwtcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0104usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcSnctl (pub u32) ; impl ExmcSnctl { # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrbken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_nrbken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrmux (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_nrmux (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrtp (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_snctl_nrtp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrw (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_snctl_nrw (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nren (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_nren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_sbrsten (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_sbrsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrwtpol (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_nrwtpol (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_wrapen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_wrapen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrwtcfg (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_nrwtcfg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_wren (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_wren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_nrwten (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_nrwten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_exmoden (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_exmoden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_asyncwait (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_asyncwait (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_cps (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_exmc_snctl_cps (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snctl_syncwr (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_exmc_snctl_syncwr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } } impl Default for ExmcSnctl { # [inline (always)]
fn default () -> ExmcSnctl { ExmcSnctl (0) } } impl core :: fmt :: Debug for ExmcSnctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcSnctl") . field ("exmc_snctl_nrbken" , & self . exmc_snctl_nrbken ()) . field ("exmc_snctl_nrmux" , & self . exmc_snctl_nrmux ()) . field ("exmc_snctl_nrtp" , & self . exmc_snctl_nrtp ()) . field ("exmc_snctl_nrw" , & self . exmc_snctl_nrw ()) . field ("exmc_snctl_nren" , & self . exmc_snctl_nren ()) . field ("exmc_snctl_sbrsten" , & self . exmc_snctl_sbrsten ()) . field ("exmc_snctl_nrwtpol" , & self . exmc_snctl_nrwtpol ()) . field ("exmc_snctl_wrapen" , & self . exmc_snctl_wrapen ()) . field ("exmc_snctl_nrwtcfg" , & self . exmc_snctl_nrwtcfg ()) . field ("exmc_snctl_wren" , & self . exmc_snctl_wren ()) . field ("exmc_snctl_nrwten" , & self . exmc_snctl_nrwten ()) . field ("exmc_snctl_exmoden" , & self . exmc_snctl_exmoden ()) . field ("exmc_snctl_asyncwait" , & self . exmc_snctl_asyncwait ()) . field ("exmc_snctl_cps" , & self . exmc_snctl_cps ()) . field ("exmc_snctl_syncwr" , & self . exmc_snctl_syncwr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcSnctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcSnctl {{ exmc_snctl_nrbken: {=bool:?}, exmc_snctl_nrmux: {=bool:?}, exmc_snctl_nrtp: {=u8:?}, exmc_snctl_nrw: {=u8:?}, exmc_snctl_nren: {=bool:?}, exmc_snctl_sbrsten: {=bool:?}, exmc_snctl_nrwtpol: {=bool:?}, exmc_snctl_wrapen: {=bool:?}, exmc_snctl_nrwtcfg: {=bool:?}, exmc_snctl_wren: {=bool:?}, exmc_snctl_nrwten: {=bool:?}, exmc_snctl_exmoden: {=bool:?}, exmc_snctl_asyncwait: {=bool:?}, exmc_snctl_cps: {=u8:?}, exmc_snctl_syncwr: {=bool:?} }}" , self . exmc_snctl_nrbken () , self . exmc_snctl_nrmux () , self . exmc_snctl_nrtp () , self . exmc_snctl_nrw () , self . exmc_snctl_nren () , self . exmc_snctl_sbrsten () , self . exmc_snctl_nrwtpol () , self . exmc_snctl_wrapen () , self . exmc_snctl_nrwtcfg () , self . exmc_snctl_wren () , self . exmc_snctl_nrwten () , self . exmc_snctl_exmoden () , self . exmc_snctl_asyncwait () , self . exmc_snctl_cps () , self . exmc_snctl_syncwr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcSntcfg (pub u32) ; impl ExmcSntcfg { # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_aset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_aset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_ahld (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_ahld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_dset (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_dset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_buslat (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_buslat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_ckdiv (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_dlat (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_dlat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_sntcfg_asyncmod (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_sntcfg_asyncmod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } } impl Default for ExmcSntcfg { # [inline (always)]
fn default () -> ExmcSntcfg { ExmcSntcfg (0) } } impl core :: fmt :: Debug for ExmcSntcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcSntcfg") . field ("exmc_sntcfg_aset" , & self . exmc_sntcfg_aset ()) . field ("exmc_sntcfg_ahld" , & self . exmc_sntcfg_ahld ()) . field ("exmc_sntcfg_dset" , & self . exmc_sntcfg_dset ()) . field ("exmc_sntcfg_buslat" , & self . exmc_sntcfg_buslat ()) . field ("exmc_sntcfg_ckdiv" , & self . exmc_sntcfg_ckdiv ()) . field ("exmc_sntcfg_dlat" , & self . exmc_sntcfg_dlat ()) . field ("exmc_sntcfg_asyncmod" , & self . exmc_sntcfg_asyncmod ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcSntcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcSntcfg {{ exmc_sntcfg_aset: {=u8:?}, exmc_sntcfg_ahld: {=u8:?}, exmc_sntcfg_dset: {=u8:?}, exmc_sntcfg_buslat: {=u8:?}, exmc_sntcfg_ckdiv: {=u8:?}, exmc_sntcfg_dlat: {=u8:?}, exmc_sntcfg_asyncmod: {=u8:?} }}" , self . exmc_sntcfg_aset () , self . exmc_sntcfg_ahld () , self . exmc_sntcfg_dset () , self . exmc_sntcfg_buslat () , self . exmc_sntcfg_ckdiv () , self . exmc_sntcfg_dlat () , self . exmc_sntcfg_asyncmod ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct ExmcSnwtcfg (pub u32) ; impl ExmcSnwtcfg { # [must_use]
# [inline (always)]
pub const fn exmc_snwtcfg_waset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_snwtcfg_waset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snwtcfg_wahld (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_snwtcfg_wahld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snwtcfg_wdset (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_exmc_snwtcfg_wdset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snwtcfg_wbuslat (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_exmc_snwtcfg_wbuslat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn exmc_snwtcfg_wasyncmod (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_exmc_snwtcfg_wasyncmod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } } impl Default for ExmcSnwtcfg { # [inline (always)]
fn default () -> ExmcSnwtcfg { ExmcSnwtcfg (0) } } impl core :: fmt :: Debug for ExmcSnwtcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("ExmcSnwtcfg") . field ("exmc_snwtcfg_waset" , & self . exmc_snwtcfg_waset ()) . field ("exmc_snwtcfg_wahld" , & self . exmc_snwtcfg_wahld ()) . field ("exmc_snwtcfg_wdset" , & self . exmc_snwtcfg_wdset ()) . field ("exmc_snwtcfg_wbuslat" , & self . exmc_snwtcfg_wbuslat ()) . field ("exmc_snwtcfg_wasyncmod" , & self . exmc_snwtcfg_wasyncmod ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for ExmcSnwtcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "ExmcSnwtcfg {{ exmc_snwtcfg_waset: {=u8:?}, exmc_snwtcfg_wahld: {=u8:?}, exmc_snwtcfg_wdset: {=u8:?}, exmc_snwtcfg_wbuslat: {=u8:?}, exmc_snwtcfg_wasyncmod: {=u8:?} }}" , self . exmc_snwtcfg_waset () , self . exmc_snwtcfg_wahld () , self . exmc_snwtcfg_wdset () , self . exmc_snwtcfg_wbuslat () , self . exmc_snwtcfg_wasyncmod ()) } } }