#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "External memory controller"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Exmc { ptr : * mut u8 } unsafe impl Send for Exmc { } unsafe impl Sync for Exmc { } impl Exmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "PSRAM/NOR Flash control registers"]
# [inline (always)]
pub const fn pnctl (self) -> crate :: common :: Reg < regs :: Pnctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "PSRAM/NOR Flash timing configuration registers"]
# [inline (always)]
pub const fn pntcfg (self) -> crate :: common :: Reg < regs :: Pntcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "NAND Flash control registers"]
# [inline (always)]
pub const fn nctl (self) -> crate :: common :: Reg < regs :: Nctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x60usize) as _) } } # [doc = "NAND Flash state registers"]
# [inline (always)]
pub const fn nstat (self) -> crate :: common :: Reg < regs :: Nstat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x64usize) as _) } } # [doc = "NAND Flash common space timing configuration registers"]
# [inline (always)]
pub const fn nctcfg (self) -> crate :: common :: Reg < regs :: Nctcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x68usize) as _) } } # [doc = "NAND Flash attribute space timing configuration registers"]
# [inline (always)]
pub const fn natcfg (self) -> crate :: common :: Reg < regs :: Natcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x6cusize) as _) } } # [doc = "NAND Flash ECC registers"]
# [inline (always)]
pub const fn necc (self) -> crate :: common :: Reg < regs :: Necc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x74usize) as _) } } } pub mod regs { # [doc = "NAND Flash attribute space timing configuration registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Natcfg (pub u32) ; impl Natcfg { # [doc = "Attribute memory setup time"]
# [inline (always)]
pub const fn attset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Attribute memory setup time"]
# [inline (always)]
pub fn set_attset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Attribute memory wait time"]
# [inline (always)]
pub const fn attwait (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Attribute memory wait time"]
# [inline (always)]
pub fn set_attwait (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Attribute memory hold time"]
# [inline (always)]
pub const fn atthld (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Attribute memory hold time"]
# [inline (always)]
pub fn set_atthld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Attribute memory data bus HiZ time"]
# [inline (always)]
pub const fn atthiz (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Attribute memory data bus HiZ time"]
# [inline (always)]
pub fn set_atthiz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for Natcfg { # [inline (always)]
fn default () -> Natcfg { Natcfg (0) } } impl core :: fmt :: Debug for Natcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Natcfg") . field ("attset" , & self . attset ()) . field ("attwait" , & self . attwait ()) . field ("atthld" , & self . atthld ()) . field ("atthiz" , & self . atthiz ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Natcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Natcfg {{ attset: {=u8:?}, attwait: {=u8:?}, atthld: {=u8:?}, atthiz: {=u8:?} }}" , self . attset () , self . attwait () , self . atthld () , self . atthiz ()) } } # [doc = "NAND Flash common space timing configuration registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Nctcfg (pub u32) ; impl Nctcfg { # [doc = "Common memory setup time"]
# [inline (always)]
pub const fn comset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Common memory setup time"]
# [inline (always)]
pub fn set_comset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Common memory wait time"]
# [inline (always)]
pub const fn comwait (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Common memory wait time"]
# [inline (always)]
pub fn set_comwait (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Common memory hold time"]
# [inline (always)]
pub const fn comhld (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Common memory hold time"]
# [inline (always)]
pub fn set_comhld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Common memory data bus HiZ time"]
# [inline (always)]
pub const fn comhiz (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Common memory data bus HiZ time"]
# [inline (always)]
pub fn set_comhiz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for Nctcfg { # [inline (always)]
fn default () -> Nctcfg { Nctcfg (0) } } impl core :: fmt :: Debug for Nctcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Nctcfg") . field ("comset" , & self . comset ()) . field ("comwait" , & self . comwait ()) . field ("comhld" , & self . comhld ()) . field ("comhiz" , & self . comhiz ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Nctcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Nctcfg {{ comset: {=u8:?}, comwait: {=u8:?}, comhld: {=u8:?}, comhiz: {=u8:?} }}" , self . comset () , self . comwait () , self . comhld () , self . comhiz ()) } } # [doc = "NAND Flash control registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Nctl (pub u32) ; impl Nctl { # [doc = "Wait function enable"]
# [inline (always)]
pub const fn ndwten (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Wait function enable"]
# [inline (always)]
pub fn set_ndwten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "NAND bank enable"]
# [inline (always)]
pub const fn ndbken (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "NAND bank enable"]
# [inline (always)]
pub fn set_ndbken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "NAND bank memory type"]
# [inline (always)]
pub const fn ndtp (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "NAND bank memory type"]
# [inline (always)]
pub fn set_ndtp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "NAND bank memory data bus width"]
# [inline (always)]
pub const fn ndw (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "NAND bank memory data bus width"]
# [inline (always)]
pub fn set_ndw (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "ECC enable"]
# [inline (always)]
pub const fn eccen (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "ECC enable"]
# [inline (always)]
pub fn set_eccen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "CLE to RE delay"]
# [inline (always)]
pub const fn ctr (& self) -> u8 { let val = (self . 0 >> 9usize) & 0x0f ; val as u8 } # [doc = "CLE to RE delay"]
# [inline (always)]
pub fn set_ctr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 9usize)) | (((val as u32) & 0x0f) << 9usize) ; } # [doc = "ALE to RE delay"]
# [inline (always)]
pub const fn atr (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x0f ; val as u8 } # [doc = "ALE to RE delay"]
# [inline (always)]
pub fn set_atr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 13usize)) | (((val as u32) & 0x0f) << 13usize) ; } # [doc = "ECC size"]
# [inline (always)]
pub const fn eccsz (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x07 ; val as u8 } # [doc = "ECC size"]
# [inline (always)]
pub fn set_eccsz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 17usize)) | (((val as u32) & 0x07) << 17usize) ; } } impl Default for Nctl { # [inline (always)]
fn default () -> Nctl { Nctl (0) } } impl core :: fmt :: Debug for Nctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Nctl") . field ("ndwten" , & self . ndwten ()) . field ("ndbken" , & self . ndbken ()) . field ("ndtp" , & self . ndtp ()) . field ("ndw" , & self . ndw ()) . field ("eccen" , & self . eccen ()) . field ("ctr" , & self . ctr ()) . field ("atr" , & self . atr ()) . field ("eccsz" , & self . eccsz ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Nctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Nctl {{ ndwten: {=bool:?}, ndbken: {=bool:?}, ndtp: {=bool:?}, ndw: {=u8:?}, eccen: {=bool:?}, ctr: {=u8:?}, atr: {=u8:?}, eccsz: {=u8:?} }}" , self . ndwten () , self . ndbken () , self . ndtp () , self . ndw () , self . eccen () , self . ctr () , self . atr () , self . eccsz ()) } } # [doc = "NAND Flash ECC registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Necc (pub u32) ; impl Necc { # [doc = "ECC result"]
# [inline (always)]
pub const fn ecc (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC result"]
# [inline (always)]
pub fn set_ecc (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Necc { # [inline (always)]
fn default () -> Necc { Necc (0) } } impl core :: fmt :: Debug for Necc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Necc") . field ("ecc" , & self . ecc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Necc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Necc {{ ecc: {=u32:?} }}" , self . ecc ()) } } # [doc = "NAND Flash state registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Nstat (pub u32) ; impl Nstat { # [doc = "FIFO empty flag"]
# [inline (always)]
pub const fn ffept (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "FIFO empty flag"]
# [inline (always)]
pub fn set_ffept (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for Nstat { # [inline (always)]
fn default () -> Nstat { Nstat (0) } } impl core :: fmt :: Debug for Nstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Nstat") . field ("ffept" , & self . ffept ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Nstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Nstat {{ ffept: {=bool:?} }}" , self . ffept ()) } } # [doc = "PSRAM/NOR Flash control registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pnctl (pub u32) ; impl Pnctl { # [doc = "NOR region enable"]
# [inline (always)]
pub const fn nrbken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "NOR region enable"]
# [inline (always)]
pub fn set_nrbken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "NOR region memory address/data multiplexing"]
# [inline (always)]
pub const fn nrmux (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "NOR region memory address/data multiplexing"]
# [inline (always)]
pub fn set_nrmux (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "NOR region memory type"]
# [inline (always)]
pub const fn nrtp (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "NOR region memory type"]
# [inline (always)]
pub fn set_nrtp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "NOR region memory data bus width"]
# [inline (always)]
pub const fn nrw (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "NOR region memory data bus width"]
# [inline (always)]
pub fn set_nrw (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "NOR Flash access enable"]
# [inline (always)]
pub const fn nren (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "NOR Flash access enable"]
# [inline (always)]
pub fn set_nren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Synchronous burst enable"]
# [inline (always)]
pub const fn sbrsten (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Synchronous burst enable"]
# [inline (always)]
pub fn set_sbrsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "NWAIT signal polarity"]
# [inline (always)]
pub const fn nrwtpol (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "NWAIT signal polarity"]
# [inline (always)]
pub fn set_nrwtpol (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Wrapped burst mode enable"]
# [inline (always)]
pub const fn wrapen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Wrapped burst mode enable"]
# [inline (always)]
pub fn set_wrapen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "NWAIT signal configuration, only work in synchronous mode"]
# [inline (always)]
pub const fn nrwtcfg (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "NWAIT signal configuration, only work in synchronous mode"]
# [inline (always)]
pub fn set_nrwtcfg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Write enable"]
# [inline (always)]
pub const fn wren (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Write enable"]
# [inline (always)]
pub fn set_wren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "NWAIT signal enable"]
# [inline (always)]
pub const fn nrwten (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "NWAIT signal enable"]
# [inline (always)]
pub fn set_nrwten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Asynchronous wait"]
# [inline (always)]
pub const fn asyncwait (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Asynchronous wait"]
# [inline (always)]
pub fn set_asyncwait (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "CRAM page size"]
# [inline (always)]
pub const fn cps (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [doc = "CRAM page size"]
# [inline (always)]
pub fn set_cps (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [doc = "Synchronous write"]
# [inline (always)]
pub const fn syncwr (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Synchronous write"]
# [inline (always)]
pub fn set_syncwr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } } impl Default for Pnctl { # [inline (always)]
fn default () -> Pnctl { Pnctl (0) } } impl core :: fmt :: Debug for Pnctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pnctl") . field ("nrbken" , & self . nrbken ()) . field ("nrmux" , & self . nrmux ()) . field ("nrtp" , & self . nrtp ()) . field ("nrw" , & self . nrw ()) . field ("nren" , & self . nren ()) . field ("sbrsten" , & self . sbrsten ()) . field ("nrwtpol" , & self . nrwtpol ()) . field ("wrapen" , & self . wrapen ()) . field ("nrwtcfg" , & self . nrwtcfg ()) . field ("wren" , & self . wren ()) . field ("nrwten" , & self . nrwten ()) . field ("asyncwait" , & self . asyncwait ()) . field ("cps" , & self . cps ()) . field ("syncwr" , & self . syncwr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pnctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pnctl {{ nrbken: {=bool:?}, nrmux: {=bool:?}, nrtp: {=u8:?}, nrw: {=u8:?}, nren: {=bool:?}, sbrsten: {=bool:?}, nrwtpol: {=bool:?}, wrapen: {=bool:?}, nrwtcfg: {=bool:?}, wren: {=bool:?}, nrwten: {=bool:?}, asyncwait: {=bool:?}, cps: {=u8:?}, syncwr: {=bool:?} }}" , self . nrbken () , self . nrmux () , self . nrtp () , self . nrw () , self . nren () , self . sbrsten () , self . nrwtpol () , self . wrapen () , self . nrwtcfg () , self . wren () , self . nrwten () , self . asyncwait () , self . cps () , self . syncwr ()) } } # [doc = "PSRAM/NOR Flash timing configuration registers"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pntcfg (pub u32) ; impl Pntcfg { # [doc = "Address setup time"]
# [inline (always)]
pub const fn aset (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Address setup time"]
# [inline (always)]
pub fn set_aset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Address hold time"]
# [inline (always)]
pub const fn ahld (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Address hold time"]
# [inline (always)]
pub fn set_ahld (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Data setup time"]
# [inline (always)]
pub const fn dset (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Data setup time"]
# [inline (always)]
pub fn set_dset (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Bus latency"]
# [inline (always)]
pub const fn buslat (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "Bus latency"]
# [inline (always)]
pub fn set_buslat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "Synchronous clock divide ratio. This filed is only effect in synchronous mode."]
# [inline (always)]
pub const fn ckdiv (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [doc = "Synchronous clock divide ratio. This filed is only effect in synchronous mode."]
# [inline (always)]
pub fn set_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } # [doc = "Data latency for NOR Flash. Only valid in synchronous access"]
# [inline (always)]
pub const fn dlat (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "Data latency for NOR Flash. Only valid in synchronous access"]
# [inline (always)]
pub fn set_dlat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } } impl Default for Pntcfg { # [inline (always)]
fn default () -> Pntcfg { Pntcfg (0) } } impl core :: fmt :: Debug for Pntcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pntcfg") . field ("aset" , & self . aset ()) . field ("ahld" , & self . ahld ()) . field ("dset" , & self . dset ()) . field ("buslat" , & self . buslat ()) . field ("ckdiv" , & self . ckdiv ()) . field ("dlat" , & self . dlat ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pntcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pntcfg {{ aset: {=u8:?}, ahld: {=u8:?}, dset: {=u8:?}, buslat: {=u8:?}, ckdiv: {=u8:?}, dlat: {=u8:?} }}" , self . aset () , self . ahld () , self . dset () , self . buslat () , self . ckdiv () , self . dlat ()) } } }