#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Fmc { ptr : * mut u8 } unsafe impl Send for Fmc { } unsafe impl Sync for Fmc { } impl Fmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn fmc_key0 (self) -> crate :: common :: Reg < regs :: FmcKey0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn fmc_obkey (self) -> crate :: common :: Reg < regs :: FmcObkey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn fmc_stat0 (self) -> crate :: common :: Reg < regs :: FmcStat0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn fmc_ctl0 (self) -> crate :: common :: Reg < regs :: FmcCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn fmc_addr0 (self) -> crate :: common :: Reg < regs :: FmcAddr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn fmc_obctl0 (self) -> crate :: common :: Reg < regs :: FmcObctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn fmc_obctl1 (self) -> crate :: common :: Reg < regs :: FmcObctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn fmc_obctl2 (self) -> crate :: common :: Reg < regs :: FmcObctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn fmc_otp1cfg (self) -> crate :: common :: Reg < regs :: FmcOtp1cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn fmc_obstat (self) -> crate :: common :: Reg < regs :: FmcObstat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn fmc_key1 (self) -> crate :: common :: Reg < regs :: FmcKey1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn fmc_stat1 (self) -> crate :: common :: Reg < regs :: FmcStat1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x4cusize) as _) } } # [inline (always)]
pub const fn fmc_ctl1 (self) -> crate :: common :: Reg < regs :: FmcCtl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x50usize) as _) } } # [inline (always)]
pub const fn fmc_addr1 (self) -> crate :: common :: Reg < regs :: FmcAddr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x54usize) as _) } } # [inline (always)]
pub const fn fmc_otp3_stat (self) -> crate :: common :: Reg < regs :: FmcOtp3Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x60usize) as _) } } # [inline (always)]
pub const fn fmc_pid (self) -> crate :: common :: Reg < regs :: FmcPid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0100usize) as _) } } # [inline (always)]
pub const fn fmc_size (self) -> crate :: common :: Reg < u16 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1fff_f7e0usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcAddr0 (pub u32) ; impl FmcAddr0 { # [must_use]
# [inline (always)]
pub const fn fmc_addr0_addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_addr0_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcAddr0 { # [inline (always)]
fn default () -> FmcAddr0 { FmcAddr0 (0) } } impl core :: fmt :: Debug for FmcAddr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcAddr0") . field ("fmc_addr0_addr" , & self . fmc_addr0_addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcAddr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcAddr0 {{ fmc_addr0_addr: {=u32:?} }}" , self . fmc_addr0_addr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcAddr1 (pub u32) ; impl FmcAddr1 { # [must_use]
# [inline (always)]
pub const fn fmc_addr1_addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_addr1_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcAddr1 { # [inline (always)]
fn default () -> FmcAddr1 { FmcAddr1 (0) } } impl core :: fmt :: Debug for FmcAddr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcAddr1") . field ("fmc_addr1_addr" , & self . fmc_addr1_addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcAddr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcAddr1 {{ fmc_addr1_addr: {=u32:?} }}" , self . fmc_addr1_addr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcCtl0 (pub u32) ; impl FmcCtl0 { # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_start (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_errie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_endie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_rlbe (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_rlbe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_pwdn (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_pwdn (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_nwlde (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_nwlde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for FmcCtl0 { # [inline (always)]
fn default () -> FmcCtl0 { FmcCtl0 (0) } } impl core :: fmt :: Debug for FmcCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcCtl0") . field ("fmc_ctl0_pg" , & self . fmc_ctl0_pg ()) . field ("fmc_ctl0_per" , & self . fmc_ctl0_per ()) . field ("fmc_ctl0_mer" , & self . fmc_ctl0_mer ()) . field ("fmc_ctl0_start" , & self . fmc_ctl0_start ()) . field ("fmc_ctl0_lk" , & self . fmc_ctl0_lk ()) . field ("fmc_ctl0_errie" , & self . fmc_ctl0_errie ()) . field ("fmc_ctl0_endie" , & self . fmc_ctl0_endie ()) . field ("fmc_ctl0_rlbe" , & self . fmc_ctl0_rlbe ()) . field ("fmc_ctl0_pwdn" , & self . fmc_ctl0_pwdn ()) . field ("fmc_ctl0_nwlde" , & self . fmc_ctl0_nwlde ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcCtl0 {{ fmc_ctl0_pg: {=bool:?}, fmc_ctl0_per: {=bool:?}, fmc_ctl0_mer: {=bool:?}, fmc_ctl0_start: {=bool:?}, fmc_ctl0_lk: {=bool:?}, fmc_ctl0_errie: {=bool:?}, fmc_ctl0_endie: {=bool:?}, fmc_ctl0_rlbe: {=bool:?}, fmc_ctl0_pwdn: {=bool:?}, fmc_ctl0_nwlde: {=bool:?} }}" , self . fmc_ctl0_pg () , self . fmc_ctl0_per () , self . fmc_ctl0_mer () , self . fmc_ctl0_start () , self . fmc_ctl0_lk () , self . fmc_ctl0_errie () , self . fmc_ctl0_endie () , self . fmc_ctl0_rlbe () , self . fmc_ctl0_pwdn () , self . fmc_ctl0_nwlde ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcCtl1 (pub u32) ; impl FmcCtl1 { # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_start (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_errie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_endie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for FmcCtl1 { # [inline (always)]
fn default () -> FmcCtl1 { FmcCtl1 (0) } } impl core :: fmt :: Debug for FmcCtl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcCtl1") . field ("fmc_ctl1_pg" , & self . fmc_ctl1_pg ()) . field ("fmc_ctl1_per" , & self . fmc_ctl1_per ()) . field ("fmc_ctl1_mer" , & self . fmc_ctl1_mer ()) . field ("fmc_ctl1_start" , & self . fmc_ctl1_start ()) . field ("fmc_ctl1_lk" , & self . fmc_ctl1_lk ()) . field ("fmc_ctl1_errie" , & self . fmc_ctl1_errie ()) . field ("fmc_ctl1_endie" , & self . fmc_ctl1_endie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcCtl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcCtl1 {{ fmc_ctl1_pg: {=bool:?}, fmc_ctl1_per: {=bool:?}, fmc_ctl1_mer: {=bool:?}, fmc_ctl1_start: {=bool:?}, fmc_ctl1_lk: {=bool:?}, fmc_ctl1_errie: {=bool:?}, fmc_ctl1_endie: {=bool:?} }}" , self . fmc_ctl1_pg () , self . fmc_ctl1_per () , self . fmc_ctl1_mer () , self . fmc_ctl1_start () , self . fmc_ctl1_lk () , self . fmc_ctl1_errie () , self . fmc_ctl1_endie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcKey0 (pub u32) ; impl FmcKey0 { # [must_use]
# [inline (always)]
pub const fn fmc_key0_key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_key0_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcKey0 { # [inline (always)]
fn default () -> FmcKey0 { FmcKey0 (0) } } impl core :: fmt :: Debug for FmcKey0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcKey0") . field ("fmc_key0_key" , & self . fmc_key0_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcKey0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcKey0 {{ fmc_key0_key: {=u32:?} }}" , self . fmc_key0_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcKey1 (pub u32) ; impl FmcKey1 { # [must_use]
# [inline (always)]
pub const fn fmc_key1_key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_key1_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcKey1 { # [inline (always)]
fn default () -> FmcKey1 { FmcKey1 (0) } } impl core :: fmt :: Debug for FmcKey1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcKey1") . field ("fmc_key1_key" , & self . fmc_key1_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcKey1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcKey1 {{ fmc_key1_key: {=u32:?} }}" , self . fmc_key1_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObctl0 (pub u32) ; impl FmcObctl0 { # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_ob_lk (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_ob_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_ob_start (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_ob_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_spc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_fmc_obctl0_spc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } } impl Default for FmcObctl0 { # [inline (always)]
fn default () -> FmcObctl0 { FmcObctl0 (0) } } impl core :: fmt :: Debug for FmcObctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObctl0") . field ("fmc_obctl0_ob_lk" , & self . fmc_obctl0_ob_lk ()) . field ("fmc_obctl0_ob_start" , & self . fmc_obctl0_ob_start ()) . field ("fmc_obctl0_spc" , & self . fmc_obctl0_spc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObctl0 {{ fmc_obctl0_ob_lk: {=bool:?}, fmc_obctl0_ob_start: {=bool:?}, fmc_obctl0_spc: {=u8:?} }}" , self . fmc_obctl0_ob_lk () , self . fmc_obctl0_ob_start () , self . fmc_obctl0_spc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObctl1 (pub u32) ; impl FmcObctl1 { # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_oberr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl1_oberr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_nwdg_hw (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl1_nwdg_hw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_nrst_dpslp (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl1_nrst_dpslp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_nrst_stdby (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl1_nrst_stdby (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_sram_rst (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl1_sram_rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_ecc_en (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl1_ecc_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_nwld_sel (& self) -> u8 { let val = (self . 0 >> 7usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_fmc_obctl1_nwld_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 7usize)) | (((val as u32) & 0x03) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_data (& self) -> u16 { let val = (self . 0 >> 10usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_fmc_obctl1_data (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 10usize)) | (((val as u32) & 0xffff) << 10usize) ; } } impl Default for FmcObctl1 { # [inline (always)]
fn default () -> FmcObctl1 { FmcObctl1 (0) } } impl core :: fmt :: Debug for FmcObctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObctl1") . field ("fmc_obctl1_oberr" , & self . fmc_obctl1_oberr ()) . field ("fmc_obctl1_nwdg_hw" , & self . fmc_obctl1_nwdg_hw ()) . field ("fmc_obctl1_nrst_dpslp" , & self . fmc_obctl1_nrst_dpslp ()) . field ("fmc_obctl1_nrst_stdby" , & self . fmc_obctl1_nrst_stdby ()) . field ("fmc_obctl1_sram_rst" , & self . fmc_obctl1_sram_rst ()) . field ("fmc_obctl1_ecc_en" , & self . fmc_obctl1_ecc_en ()) . field ("fmc_obctl1_nwld_sel" , & self . fmc_obctl1_nwld_sel ()) . field ("fmc_obctl1_data" , & self . fmc_obctl1_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObctl1 {{ fmc_obctl1_oberr: {=bool:?}, fmc_obctl1_nwdg_hw: {=bool:?}, fmc_obctl1_nrst_dpslp: {=bool:?}, fmc_obctl1_nrst_stdby: {=bool:?}, fmc_obctl1_sram_rst: {=bool:?}, fmc_obctl1_ecc_en: {=bool:?}, fmc_obctl1_nwld_sel: {=u8:?}, fmc_obctl1_data: {=u16:?} }}" , self . fmc_obctl1_oberr () , self . fmc_obctl1_nwdg_hw () , self . fmc_obctl1_nrst_dpslp () , self . fmc_obctl1_nrst_stdby () , self . fmc_obctl1_sram_rst () , self . fmc_obctl1_ecc_en () , self . fmc_obctl1_nwld_sel () , self . fmc_obctl1_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObctl2 (pub u32) ; impl FmcObctl2 { # [must_use]
# [inline (always)]
pub const fn fmc_obctl2_wp (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_obctl2_wp (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcObctl2 { # [inline (always)]
fn default () -> FmcObctl2 { FmcObctl2 (0) } } impl core :: fmt :: Debug for FmcObctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObctl2") . field ("fmc_obctl2_wp" , & self . fmc_obctl2_wp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObctl2 {{ fmc_obctl2_wp: {=u32:?} }}" , self . fmc_obctl2_wp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObkey (pub u32) ; impl FmcObkey { # [must_use]
# [inline (always)]
pub const fn fmc_obkey_obkey (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_obkey_obkey (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcObkey { # [inline (always)]
fn default () -> FmcObkey { FmcObkey (0) } } impl core :: fmt :: Debug for FmcObkey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObkey") . field ("fmc_obkey_obkey" , & self . fmc_obkey_obkey ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObkey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObkey {{ fmc_obkey_obkey: {=u32:?} }}" , self . fmc_obkey_obkey ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObstat (pub u32) ; impl FmcObstat { # [must_use]
# [inline (always)]
pub const fn fmc_obstat_spcl (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obstat_spcl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obstat_spch (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obstat_spch (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for FmcObstat { # [inline (always)]
fn default () -> FmcObstat { FmcObstat (0) } } impl core :: fmt :: Debug for FmcObstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObstat") . field ("fmc_obstat_spcl" , & self . fmc_obstat_spcl ()) . field ("fmc_obstat_spch" , & self . fmc_obstat_spch ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObstat {{ fmc_obstat_spcl: {=bool:?}, fmc_obstat_spch: {=bool:?} }}" , self . fmc_obstat_spcl () , self . fmc_obstat_spch ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcOtp1cfg (pub u32) ; impl FmcOtp1cfg { # [must_use]
# [inline (always)]
pub const fn fmc_otp1cfg_otp1ren (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_fmc_otp1cfg_otp1ren (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for FmcOtp1cfg { # [inline (always)]
fn default () -> FmcOtp1cfg { FmcOtp1cfg (0) } } impl core :: fmt :: Debug for FmcOtp1cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcOtp1cfg") . field ("fmc_otp1cfg_otp1ren" , & self . fmc_otp1cfg_otp1ren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcOtp1cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcOtp1cfg {{ fmc_otp1cfg_otp1ren: {=u16:?} }}" , self . fmc_otp1cfg_otp1ren ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcOtp3Stat (pub u32) ; impl FmcOtp3Stat { # [must_use]
# [inline (always)]
pub const fn fmc_otp3_stat_ndbg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_otp3_stat_ndbg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_otp3_stat_nbtsb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_otp3_stat_nbtsb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_otp3_stat_btfosel (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_otp3_stat_btfosel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_otp3_stat_ndbg_lk (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_otp3_stat_ndbg_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_otp3_stat_nbtsb_lk (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_otp3_stat_nbtsb_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_otp3_stat_btfosel_lk (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_otp3_stat_btfosel_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for FmcOtp3Stat { # [inline (always)]
fn default () -> FmcOtp3Stat { FmcOtp3Stat (0) } } impl core :: fmt :: Debug for FmcOtp3Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcOtp3Stat") . field ("fmc_otp3_stat_ndbg" , & self . fmc_otp3_stat_ndbg ()) . field ("fmc_otp3_stat_nbtsb" , & self . fmc_otp3_stat_nbtsb ()) . field ("fmc_otp3_stat_btfosel" , & self . fmc_otp3_stat_btfosel ()) . field ("fmc_otp3_stat_ndbg_lk" , & self . fmc_otp3_stat_ndbg_lk ()) . field ("fmc_otp3_stat_nbtsb_lk" , & self . fmc_otp3_stat_nbtsb_lk ()) . field ("fmc_otp3_stat_btfosel_lk" , & self . fmc_otp3_stat_btfosel_lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcOtp3Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcOtp3Stat {{ fmc_otp3_stat_ndbg: {=bool:?}, fmc_otp3_stat_nbtsb: {=bool:?}, fmc_otp3_stat_btfosel: {=bool:?}, fmc_otp3_stat_ndbg_lk: {=bool:?}, fmc_otp3_stat_nbtsb_lk: {=bool:?}, fmc_otp3_stat_btfosel_lk: {=bool:?} }}" , self . fmc_otp3_stat_ndbg () , self . fmc_otp3_stat_nbtsb () , self . fmc_otp3_stat_btfosel () , self . fmc_otp3_stat_ndbg_lk () , self . fmc_otp3_stat_nbtsb_lk () , self . fmc_otp3_stat_btfosel_lk ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcPid (pub u32) ; impl FmcPid { # [must_use]
# [inline (always)]
pub const fn fmc_pid_pid (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_pid_pid (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcPid { # [inline (always)]
fn default () -> FmcPid { FmcPid (0) } } impl core :: fmt :: Debug for FmcPid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcPid") . field ("fmc_pid_pid" , & self . fmc_pid_pid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcPid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcPid {{ fmc_pid_pid: {=u32:?} }}" , self . fmc_pid_pid ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcStat0 (pub u32) ; impl FmcStat0 { # [must_use]
# [inline (always)]
pub const fn fmc_stat0_busy (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat0_pgerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat0_wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat0_endf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for FmcStat0 { # [inline (always)]
fn default () -> FmcStat0 { FmcStat0 (0) } } impl core :: fmt :: Debug for FmcStat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcStat0") . field ("fmc_stat0_busy" , & self . fmc_stat0_busy ()) . field ("fmc_stat0_pgerr" , & self . fmc_stat0_pgerr ()) . field ("fmc_stat0_wperr" , & self . fmc_stat0_wperr ()) . field ("fmc_stat0_endf" , & self . fmc_stat0_endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcStat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcStat0 {{ fmc_stat0_busy: {=bool:?}, fmc_stat0_pgerr: {=bool:?}, fmc_stat0_wperr: {=bool:?}, fmc_stat0_endf: {=bool:?} }}" , self . fmc_stat0_busy () , self . fmc_stat0_pgerr () , self . fmc_stat0_wperr () , self . fmc_stat0_endf ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcStat1 (pub u32) ; impl FmcStat1 { # [must_use]
# [inline (always)]
pub const fn fmc_stat1_busy (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat1_pgerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat1_wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat1_endf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for FmcStat1 { # [inline (always)]
fn default () -> FmcStat1 { FmcStat1 (0) } } impl core :: fmt :: Debug for FmcStat1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcStat1") . field ("fmc_stat1_busy" , & self . fmc_stat1_busy ()) . field ("fmc_stat1_pgerr" , & self . fmc_stat1_pgerr ()) . field ("fmc_stat1_wperr" , & self . fmc_stat1_wperr ()) . field ("fmc_stat1_endf" , & self . fmc_stat1_endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcStat1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcStat1 {{ fmc_stat1_busy: {=bool:?}, fmc_stat1_pgerr: {=bool:?}, fmc_stat1_wperr: {=bool:?}, fmc_stat1_endf: {=bool:?} }}" , self . fmc_stat1_busy () , self . fmc_stat1_pgerr () , self . fmc_stat1_wperr () , self . fmc_stat1_endf ()) } } }