#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Flash memory controller"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Fmc { ptr : * mut u8 } unsafe impl Send for Fmc { } unsafe impl Sync for Fmc { } impl Fmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Unlock key register"]
# [inline (always)]
pub const fn key0 (self) -> crate :: common :: Reg < regs :: Key0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Option byte unlock key register"]
# [inline (always)]
pub const fn obkey (self) -> crate :: common :: Reg < regs :: Obkey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Status register 0"]
# [inline (always)]
pub const fn stat0 (self) -> crate :: common :: Reg < regs :: Stat0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Control register"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Address register 0"]
# [inline (always)]
pub const fn addr0 (self) -> crate :: common :: Reg < regs :: Addr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Option byte control register 0"]
# [inline (always)]
pub const fn obctl0 (self) -> crate :: common :: Reg < regs :: Obctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Option byte control register 1"]
# [inline (always)]
pub const fn obctl1 (self) -> crate :: common :: Reg < regs :: Obctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Option byte control register 2"]
# [inline (always)]
pub const fn obctl2 (self) -> crate :: common :: Reg < regs :: Obctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "OTP1 configuration register"]
# [inline (always)]
pub const fn otp1cfg (self) -> crate :: common :: Reg < regs :: Otp1cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Option bytes status register"]
# [inline (always)]
pub const fn obstat (self) -> crate :: common :: Reg < regs :: Obstat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "Unlock key register"]
# [inline (always)]
pub const fn key1 (self) -> crate :: common :: Reg < regs :: Key1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "Status register 1"]
# [inline (always)]
pub const fn stat1 (self) -> crate :: common :: Reg < regs :: Stat1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "Control register"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x50usize) as _) } } # [doc = "Address register 1"]
# [inline (always)]
pub const fn addr1 (self) -> crate :: common :: Reg < regs :: Addr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize) as _) } } # [doc = "OTP3 status register"]
# [inline (always)]
pub const fn otp3_stat (self) -> crate :: common :: Reg < regs :: Otp3Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x60usize) as _) } } # [doc = "Product ID register"]
# [inline (always)]
pub const fn pid (self) -> crate :: common :: Reg < regs :: Pid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0100usize) as _) } } } pub mod regs { # [doc = "Address register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Addr0 (pub u32) ; impl Addr0 { # [doc = "Flash erase command address bits"]
# [inline (always)]
pub const fn addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Flash erase command address bits"]
# [inline (always)]
pub fn set_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Addr0 { # [inline (always)]
fn default () -> Addr0 { Addr0 (0) } } impl core :: fmt :: Debug for Addr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Addr0") . field ("addr" , & self . addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Addr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Addr0 {{ addr: {=u32:?} }}" , self . addr ()) } } # [doc = "Address register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Addr1 (pub u32) ; impl Addr1 { # [doc = "Flash erase command address bits"]
# [inline (always)]
pub const fn addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Flash erase command address bits"]
# [inline (always)]
pub fn set_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Addr1 { # [inline (always)]
fn default () -> Addr1 { Addr1 (0) } } impl core :: fmt :: Debug for Addr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Addr1") . field ("addr" , & self . addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Addr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Addr1 {{ addr: {=u32:?} }}" , self . addr ()) } } # [doc = "Control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Main flash program for bank0 command bit"]
# [inline (always)]
pub const fn pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Main flash program for bank0 command bit"]
# [inline (always)]
pub fn set_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Main flash page erase for bank0 command bit"]
# [inline (always)]
pub const fn per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Main flash page erase for bank0 command bit"]
# [inline (always)]
pub fn set_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Main flash mass erase for bank0 command bit"]
# [inline (always)]
pub const fn mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Main flash mass erase for bank0 command bit"]
# [inline (always)]
pub fn set_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Send erase command to FMC bit"]
# [inline (always)]
pub const fn start (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Send erase command to FMC bit"]
# [inline (always)]
pub fn set_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "FMC_CTL0 lock bit"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "FMC_CTL0 lock bit"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Error interrupt enable bit"]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Error interrupt enable bit"]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "End of operation interrupt enable bit"]
# [inline (always)]
pub const fn endie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "End of operation interrupt enable bit"]
# [inline (always)]
pub fn set_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Enable read lock block for OTP2."]
# [inline (always)]
pub const fn rlbe (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Enable read lock block for OTP2."]
# [inline (always)]
pub fn set_rlbe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Flash enter to Deep Power Down mode when no operation."]
# [inline (always)]
pub const fn pwdn (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Flash enter to Deep Power Down mode when no operation."]
# [inline (always)]
pub fn set_pwdn (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Enable no waiting time area load when system reset. No waiting time area load include load option bytes, OTP, main flash code area."]
# [inline (always)]
pub const fn nwlde (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Enable no waiting time area load when system reset. No waiting time area load include load option bytes, OTP, main flash code area."]
# [inline (always)]
pub fn set_nwlde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("pg" , & self . pg ()) . field ("per" , & self . per ()) . field ("mer" , & self . mer ()) . field ("start" , & self . start ()) . field ("lk" , & self . lk ()) . field ("errie" , & self . errie ()) . field ("endie" , & self . endie ()) . field ("rlbe" , & self . rlbe ()) . field ("pwdn" , & self . pwdn ()) . field ("nwlde" , & self . nwlde ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ pg: {=bool:?}, per: {=bool:?}, mer: {=bool:?}, start: {=bool:?}, lk: {=bool:?}, errie: {=bool:?}, endie: {=bool:?}, rlbe: {=bool:?}, pwdn: {=bool:?}, nwlde: {=bool:?} }}" , self . pg () , self . per () , self . mer () , self . start () , self . lk () , self . errie () , self . endie () , self . rlbe () , self . pwdn () , self . nwlde ()) } } # [doc = "Control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Main flash program for bank1 command bit"]
# [inline (always)]
pub const fn pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Main flash program for bank1 command bit"]
# [inline (always)]
pub fn set_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Main flash page erase for bank1 command bit"]
# [inline (always)]
pub const fn per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Main flash page erase for bank1 command bit"]
# [inline (always)]
pub fn set_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Main flash mass erase for bank1 command bit"]
# [inline (always)]
pub const fn mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Main flash mass erase for bank1 command bit"]
# [inline (always)]
pub fn set_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Send erase command to FMC bit"]
# [inline (always)]
pub const fn start (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Send erase command to FMC bit"]
# [inline (always)]
pub fn set_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "FMC_CTL1 lock bit"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "FMC_CTL1 lock bit"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Error interrupt enable bit"]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Error interrupt enable bit"]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "End of operation interrupt enable bit"]
# [inline (always)]
pub const fn endie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "End of operation interrupt enable bit"]
# [inline (always)]
pub fn set_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("pg" , & self . pg ()) . field ("per" , & self . per ()) . field ("mer" , & self . mer ()) . field ("start" , & self . start ()) . field ("lk" , & self . lk ()) . field ("errie" , & self . errie ()) . field ("endie" , & self . endie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ pg: {=bool:?}, per: {=bool:?}, mer: {=bool:?}, start: {=bool:?}, lk: {=bool:?}, errie: {=bool:?}, endie: {=bool:?} }}" , self . pg () , self . per () , self . mer () , self . start () , self . lk () , self . errie () , self . endie ()) } } # [doc = "Unlock key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key0 (pub u32) ; impl Key0 { # [doc = "FMC_CTL0 unlock register"]
# [inline (always)]
pub const fn key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "FMC_CTL0 unlock register"]
# [inline (always)]
pub fn set_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key0 { # [inline (always)]
fn default () -> Key0 { Key0 (0) } } impl core :: fmt :: Debug for Key0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key0") . field ("key" , & self . key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key0 {{ key: {=u32:?} }}" , self . key ()) } } # [doc = "Unlock key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key1 (pub u32) ; impl Key1 { # [doc = "FMC_CTL1 unlock register"]
# [inline (always)]
pub const fn key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "FMC_CTL1 unlock register"]
# [inline (always)]
pub fn set_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key1 { # [inline (always)]
fn default () -> Key1 { Key1 (0) } } impl core :: fmt :: Debug for Key1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key1") . field ("key" , & self . key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key1 {{ key: {=u32:?} }}" , self . key ()) } } # [doc = "Option byte control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obctl0 (pub u32) ; impl Obctl0 { # [doc = "FMC_OBCTL0/1/2 lock bit"]
# [inline (always)]
pub const fn ob_lk (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "FMC_OBCTL0/1/2 lock bit"]
# [inline (always)]
pub fn set_ob_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Send option byte change command to FMC bit."]
# [inline (always)]
pub const fn ob_start (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Send option byte change command to FMC bit."]
# [inline (always)]
pub fn set_ob_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Option byte security protection code."]
# [inline (always)]
pub const fn spc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Option byte security protection code."]
# [inline (always)]
pub fn set_spc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } } impl Default for Obctl0 { # [inline (always)]
fn default () -> Obctl0 { Obctl0 (0) } } impl core :: fmt :: Debug for Obctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obctl0") . field ("ob_lk" , & self . ob_lk ()) . field ("ob_start" , & self . ob_start ()) . field ("spc" , & self . spc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obctl0 {{ ob_lk: {=bool:?}, ob_start: {=bool:?}, spc: {=u8:?} }}" , self . ob_lk () , self . ob_start () , self . spc ()) } } # [doc = "Option byte control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obctl1 (pub u32) ; impl Obctl1 { # [doc = "Option bytes read error bit."]
# [inline (always)]
pub const fn oberr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Option bytes read error bit."]
# [inline (always)]
pub fn set_oberr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Store USER of option bytes block after system reset."]
# [inline (always)]
pub const fn user (& self) -> u8 { let val = (self . 0 >> 2usize) & 0xff ; val as u8 } # [doc = "Store USER of option bytes block after system reset."]
# [inline (always)]
pub fn set_user (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 2usize)) | (((val as u32) & 0xff) << 2usize) ; } # [doc = "Store DATA of option bytes block after system reset."]
# [inline (always)]
pub const fn data (& self) -> u16 { let val = (self . 0 >> 10usize) & 0xffff ; val as u16 } # [doc = "Store DATA of option bytes block after system reset."]
# [inline (always)]
pub fn set_data (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 10usize)) | (((val as u32) & 0xffff) << 10usize) ; } } impl Default for Obctl1 { # [inline (always)]
fn default () -> Obctl1 { Obctl1 (0) } } impl core :: fmt :: Debug for Obctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obctl1") . field ("oberr" , & self . oberr ()) . field ("user" , & self . user ()) . field ("data" , & self . data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obctl1 {{ oberr: {=bool:?}, user: {=u8:?}, data: {=u16:?} }}" , self . oberr () , self . user () , self . data ()) } } # [doc = "Option byte control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obctl2 (pub u32) ; impl Obctl2 { # [doc = "Store WP of option bytes block after system reset."]
# [inline (always)]
pub const fn wp (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Store WP of option bytes block after system reset."]
# [inline (always)]
pub fn set_wp (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Obctl2 { # [inline (always)]
fn default () -> Obctl2 { Obctl2 (0) } } impl core :: fmt :: Debug for Obctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obctl2") . field ("wp" , & self . wp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obctl2 {{ wp: {=u32:?} }}" , self . wp ()) } } # [doc = "Option byte unlock key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obkey (pub u32) ; impl Obkey { # [doc = "Option bytes operation unlock register."]
# [inline (always)]
pub const fn obkey (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Option bytes operation unlock register."]
# [inline (always)]
pub fn set_obkey (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Obkey { # [inline (always)]
fn default () -> Obkey { Obkey (0) } } impl core :: fmt :: Debug for Obkey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obkey") . field ("obkey" , & self . obkey ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obkey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obkey {{ obkey: {=u32:?} }}" , self . obkey ()) } } # [doc = "Option bytes status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obstat (pub u32) ; impl Obstat { # [doc = "Security protection is level low now."]
# [inline (always)]
pub const fn spcl (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Security protection is level low now."]
# [inline (always)]
pub fn set_spcl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Security protection is level high now."]
# [inline (always)]
pub const fn spch (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Security protection is level high now."]
# [inline (always)]
pub fn set_spch (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Obstat { # [inline (always)]
fn default () -> Obstat { Obstat (0) } } impl core :: fmt :: Debug for Obstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obstat") . field ("spcl" , & self . spcl ()) . field ("spch" , & self . spch ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obstat {{ spcl: {=bool:?}, spch: {=bool:?} }}" , self . spcl () , self . spch ()) } } # [doc = "OTP1 configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Otp1cfg (pub u32) ; impl Otp1cfg { # [doc = "OTP1 read enable."]
# [inline (always)]
pub const fn otp1ren (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "OTP1 read enable."]
# [inline (always)]
pub fn set_otp1ren (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Otp1cfg { # [inline (always)]
fn default () -> Otp1cfg { Otp1cfg (0) } } impl core :: fmt :: Debug for Otp1cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Otp1cfg") . field ("otp1ren" , & self . otp1ren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Otp1cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Otp1cfg {{ otp1ren: {=u16:?} }}" , self . otp1ren ()) } } # [doc = "OTP3 status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Otp3Stat (pub u32) ; impl Otp3Stat { # [doc = "Debugging permission setting."]
# [inline (always)]
pub const fn ndbg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Debugging permission setting."]
# [inline (always)]
pub fn set_ndbg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Not boot from SRAM or bootloader."]
# [inline (always)]
pub const fn nbtsb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Not boot from SRAM or bootloader."]
# [inline (always)]
pub fn set_nbtsb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Select Boot from flash or OTP1. This bit actives when NBTSB is 1 or BOOT0 is 0."]
# [inline (always)]
pub const fn btfosel (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Select Boot from flash or OTP1. This bit actives when NBTSB is 1 or BOOT0 is 0."]
# [inline (always)]
pub fn set_btfosel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "NDBG lock status."]
# [inline (always)]
pub const fn ndbg_lk (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "NDBG lock status."]
# [inline (always)]
pub fn set_ndbg_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "NBTSB lock status."]
# [inline (always)]
pub const fn nbtsb_lk (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "NBTSB lock status."]
# [inline (always)]
pub fn set_nbtsb_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "BTFOSEL lock status."]
# [inline (always)]
pub const fn btfosel_lk (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "BTFOSEL lock status."]
# [inline (always)]
pub fn set_btfosel_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for Otp3Stat { # [inline (always)]
fn default () -> Otp3Stat { Otp3Stat (0) } } impl core :: fmt :: Debug for Otp3Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Otp3Stat") . field ("ndbg" , & self . ndbg ()) . field ("nbtsb" , & self . nbtsb ()) . field ("btfosel" , & self . btfosel ()) . field ("ndbg_lk" , & self . ndbg_lk ()) . field ("nbtsb_lk" , & self . nbtsb_lk ()) . field ("btfosel_lk" , & self . btfosel_lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Otp3Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Otp3Stat {{ ndbg: {=bool:?}, nbtsb: {=bool:?}, btfosel: {=bool:?}, ndbg_lk: {=bool:?}, nbtsb_lk: {=bool:?}, btfosel_lk: {=bool:?} }}" , self . ndbg () , self . nbtsb () , self . btfosel () , self . ndbg_lk () , self . nbtsb_lk () , self . btfosel_lk ()) } } # [doc = "Product ID register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pid (pub u32) ; impl Pid { # [doc = "Product reserved ID code register"]
# [inline (always)]
pub const fn pid (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Product reserved ID code register"]
# [inline (always)]
pub fn set_pid (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Pid { # [inline (always)]
fn default () -> Pid { Pid (0) } } impl core :: fmt :: Debug for Pid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pid") . field ("pid" , & self . pid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pid {{ pid: {=u32:?} }}" , self . pid ()) } } # [doc = "Status register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat0 (pub u32) ; impl Stat0 { # [doc = "The flash is busy bit"]
# [inline (always)]
pub const fn busy (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "The flash is busy bit"]
# [inline (always)]
pub fn set_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Program error flag bit"]
# [inline (always)]
pub const fn pgerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Program error flag bit"]
# [inline (always)]
pub fn set_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Erase/Program protection error flag bit"]
# [inline (always)]
pub const fn wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Erase/Program protection error flag bit"]
# [inline (always)]
pub fn set_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "End of operation flag bit"]
# [inline (always)]
pub const fn endf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "End of operation flag bit"]
# [inline (always)]
pub fn set_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for Stat0 { # [inline (always)]
fn default () -> Stat0 { Stat0 (0) } } impl core :: fmt :: Debug for Stat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat0") . field ("busy" , & self . busy ()) . field ("pgerr" , & self . pgerr ()) . field ("wperr" , & self . wperr ()) . field ("endf" , & self . endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat0 {{ busy: {=bool:?}, pgerr: {=bool:?}, wperr: {=bool:?}, endf: {=bool:?} }}" , self . busy () , self . pgerr () , self . wperr () , self . endf ()) } } # [doc = "Status register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat1 (pub u32) ; impl Stat1 { # [doc = "The flash is busy bit."]
# [inline (always)]
pub const fn busy (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "The flash is busy bit."]
# [inline (always)]
pub fn set_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Program error flag bit"]
# [inline (always)]
pub const fn pgerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Program error flag bit"]
# [inline (always)]
pub fn set_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Erase/Program protection error flag bit"]
# [inline (always)]
pub const fn wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Erase/Program protection error flag bit"]
# [inline (always)]
pub fn set_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "End of operation flag bit"]
# [inline (always)]
pub const fn endf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "End of operation flag bit"]
# [inline (always)]
pub fn set_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for Stat1 { # [inline (always)]
fn default () -> Stat1 { Stat1 (0) } } impl core :: fmt :: Debug for Stat1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat1") . field ("busy" , & self . busy ()) . field ("pgerr" , & self . pgerr ()) . field ("wperr" , & self . wperr ()) . field ("endf" , & self . endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat1 {{ busy: {=bool:?}, pgerr: {=bool:?}, wperr: {=bool:?}, endf: {=bool:?} }}" , self . busy () , self . pgerr () , self . wperr () , self . endf ()) } } }