#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Fmc { ptr : * mut u8 } unsafe impl Send for Fmc { } unsafe impl Sync for Fmc { } impl Fmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn fmc_ws (self) -> crate :: common :: Reg < regs :: FmcWs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn fmc_key0 (self) -> crate :: common :: Reg < regs :: FmcKey0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn fmc_obkey (self) -> crate :: common :: Reg < regs :: FmcObkey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn fmc_stat0 (self) -> crate :: common :: Reg < regs :: FmcStat0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn fmc_ctl0 (self) -> crate :: common :: Reg < regs :: FmcCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn fmc_addr0 (self) -> crate :: common :: Reg < regs :: FmcAddr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn fmc_obstat (self) -> crate :: common :: Reg < regs :: FmcObstat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn fmc_wp (self) -> crate :: common :: Reg < regs :: FmcWp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn fmc_key1 (self) -> crate :: common :: Reg < regs :: FmcKey1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn fmc_stat1 (self) -> crate :: common :: Reg < regs :: FmcStat1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x4cusize) as _) } } # [inline (always)]
pub const fn fmc_ctl1 (self) -> crate :: common :: Reg < regs :: FmcCtl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x50usize) as _) } } # [inline (always)]
pub const fn fmc_addr1 (self) -> crate :: common :: Reg < regs :: FmcAddr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x54usize) as _) } } # [inline (always)]
pub const fn fmc_wsen (self) -> crate :: common :: Reg < regs :: FmcWsen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0xfcusize) as _) } } # [inline (always)]
pub const fn fmc_pid (self) -> crate :: common :: Reg < regs :: FmcPid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0100usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcAddr0 (pub u32) ; impl FmcAddr0 { # [must_use]
# [inline (always)]
pub const fn fmc_addr0_addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_addr0_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcAddr0 { # [inline (always)]
fn default () -> FmcAddr0 { FmcAddr0 (0) } } impl core :: fmt :: Debug for FmcAddr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcAddr0") . field ("fmc_addr0_addr" , & self . fmc_addr0_addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcAddr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcAddr0 {{ fmc_addr0_addr: {=u32:?} }}" , self . fmc_addr0_addr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcAddr1 (pub u32) ; impl FmcAddr1 { # [must_use]
# [inline (always)]
pub const fn fmc_addr1_addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_addr1_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcAddr1 { # [inline (always)]
fn default () -> FmcAddr1 { FmcAddr1 (0) } } impl core :: fmt :: Debug for FmcAddr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcAddr1") . field ("fmc_addr1_addr" , & self . fmc_addr1_addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcAddr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcAddr1 {{ fmc_addr1_addr: {=u32:?} }}" , self . fmc_addr1_addr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcCtl0 (pub u32) ; impl FmcCtl0 { # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_obpg (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_obpg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_ober (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_ober (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_start (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_obwen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_obwen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_errie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl0_endie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl0_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for FmcCtl0 { # [inline (always)]
fn default () -> FmcCtl0 { FmcCtl0 (0) } } impl core :: fmt :: Debug for FmcCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcCtl0") . field ("fmc_ctl0_pg" , & self . fmc_ctl0_pg ()) . field ("fmc_ctl0_per" , & self . fmc_ctl0_per ()) . field ("fmc_ctl0_mer" , & self . fmc_ctl0_mer ()) . field ("fmc_ctl0_obpg" , & self . fmc_ctl0_obpg ()) . field ("fmc_ctl0_ober" , & self . fmc_ctl0_ober ()) . field ("fmc_ctl0_start" , & self . fmc_ctl0_start ()) . field ("fmc_ctl0_lk" , & self . fmc_ctl0_lk ()) . field ("fmc_ctl0_obwen" , & self . fmc_ctl0_obwen ()) . field ("fmc_ctl0_errie" , & self . fmc_ctl0_errie ()) . field ("fmc_ctl0_endie" , & self . fmc_ctl0_endie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcCtl0 {{ fmc_ctl0_pg: {=bool:?}, fmc_ctl0_per: {=bool:?}, fmc_ctl0_mer: {=bool:?}, fmc_ctl0_obpg: {=bool:?}, fmc_ctl0_ober: {=bool:?}, fmc_ctl0_start: {=bool:?}, fmc_ctl0_lk: {=bool:?}, fmc_ctl0_obwen: {=bool:?}, fmc_ctl0_errie: {=bool:?}, fmc_ctl0_endie: {=bool:?} }}" , self . fmc_ctl0_pg () , self . fmc_ctl0_per () , self . fmc_ctl0_mer () , self . fmc_ctl0_obpg () , self . fmc_ctl0_ober () , self . fmc_ctl0_start () , self . fmc_ctl0_lk () , self . fmc_ctl0_obwen () , self . fmc_ctl0_errie () , self . fmc_ctl0_endie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcCtl1 (pub u32) ; impl FmcCtl1 { # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_start (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_errie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl1_endie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl1_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for FmcCtl1 { # [inline (always)]
fn default () -> FmcCtl1 { FmcCtl1 (0) } } impl core :: fmt :: Debug for FmcCtl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcCtl1") . field ("fmc_ctl1_pg" , & self . fmc_ctl1_pg ()) . field ("fmc_ctl1_per" , & self . fmc_ctl1_per ()) . field ("fmc_ctl1_mer" , & self . fmc_ctl1_mer ()) . field ("fmc_ctl1_start" , & self . fmc_ctl1_start ()) . field ("fmc_ctl1_lk" , & self . fmc_ctl1_lk ()) . field ("fmc_ctl1_errie" , & self . fmc_ctl1_errie ()) . field ("fmc_ctl1_endie" , & self . fmc_ctl1_endie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcCtl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcCtl1 {{ fmc_ctl1_pg: {=bool:?}, fmc_ctl1_per: {=bool:?}, fmc_ctl1_mer: {=bool:?}, fmc_ctl1_start: {=bool:?}, fmc_ctl1_lk: {=bool:?}, fmc_ctl1_errie: {=bool:?}, fmc_ctl1_endie: {=bool:?} }}" , self . fmc_ctl1_pg () , self . fmc_ctl1_per () , self . fmc_ctl1_mer () , self . fmc_ctl1_start () , self . fmc_ctl1_lk () , self . fmc_ctl1_errie () , self . fmc_ctl1_endie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcKey0 (pub u32) ; impl FmcKey0 { # [must_use]
# [inline (always)]
pub const fn fmc_key0_key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_key0_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcKey0 { # [inline (always)]
fn default () -> FmcKey0 { FmcKey0 (0) } } impl core :: fmt :: Debug for FmcKey0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcKey0") . field ("fmc_key0_key" , & self . fmc_key0_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcKey0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcKey0 {{ fmc_key0_key: {=u32:?} }}" , self . fmc_key0_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcKey1 (pub u32) ; impl FmcKey1 { # [must_use]
# [inline (always)]
pub const fn fmc_key1_key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_key1_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcKey1 { # [inline (always)]
fn default () -> FmcKey1 { FmcKey1 (0) } } impl core :: fmt :: Debug for FmcKey1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcKey1") . field ("fmc_key1_key" , & self . fmc_key1_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcKey1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcKey1 {{ fmc_key1_key: {=u32:?} }}" , self . fmc_key1_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObkey (pub u32) ; impl FmcObkey { # [must_use]
# [inline (always)]
pub const fn fmc_obkey_obkey (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_obkey_obkey (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcObkey { # [inline (always)]
fn default () -> FmcObkey { FmcObkey (0) } } impl core :: fmt :: Debug for FmcObkey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObkey") . field ("fmc_obkey_obkey" , & self . fmc_obkey_obkey ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObkey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObkey {{ fmc_obkey_obkey: {=u32:?} }}" , self . fmc_obkey_obkey ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObstat (pub u32) ; impl FmcObstat { # [must_use]
# [inline (always)]
pub const fn fmc_obstat_oberr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obstat_oberr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obstat_spc (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obstat_spc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obstat_user (& self) -> u8 { let val = (self . 0 >> 2usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_fmc_obstat_user (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 2usize)) | (((val as u32) & 0xff) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obstat_data (& self) -> u16 { let val = (self . 0 >> 10usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_fmc_obstat_data (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 10usize)) | (((val as u32) & 0xffff) << 10usize) ; } } impl Default for FmcObstat { # [inline (always)]
fn default () -> FmcObstat { FmcObstat (0) } } impl core :: fmt :: Debug for FmcObstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObstat") . field ("fmc_obstat_oberr" , & self . fmc_obstat_oberr ()) . field ("fmc_obstat_spc" , & self . fmc_obstat_spc ()) . field ("fmc_obstat_user" , & self . fmc_obstat_user ()) . field ("fmc_obstat_data" , & self . fmc_obstat_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObstat {{ fmc_obstat_oberr: {=bool:?}, fmc_obstat_spc: {=bool:?}, fmc_obstat_user: {=u8:?}, fmc_obstat_data: {=u16:?} }}" , self . fmc_obstat_oberr () , self . fmc_obstat_spc () , self . fmc_obstat_user () , self . fmc_obstat_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcPid (pub u32) ; impl FmcPid { # [must_use]
# [inline (always)]
pub const fn fmc_pid_pid (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_pid_pid (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcPid { # [inline (always)]
fn default () -> FmcPid { FmcPid (0) } } impl core :: fmt :: Debug for FmcPid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcPid") . field ("fmc_pid_pid" , & self . fmc_pid_pid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcPid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcPid {{ fmc_pid_pid: {=u32:?} }}" , self . fmc_pid_pid ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcStat0 (pub u32) ; impl FmcStat0 { # [must_use]
# [inline (always)]
pub const fn fmc_stat0_busy (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat0_pgerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat0_wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat0_endf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat0_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for FmcStat0 { # [inline (always)]
fn default () -> FmcStat0 { FmcStat0 (0) } } impl core :: fmt :: Debug for FmcStat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcStat0") . field ("fmc_stat0_busy" , & self . fmc_stat0_busy ()) . field ("fmc_stat0_pgerr" , & self . fmc_stat0_pgerr ()) . field ("fmc_stat0_wperr" , & self . fmc_stat0_wperr ()) . field ("fmc_stat0_endf" , & self . fmc_stat0_endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcStat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcStat0 {{ fmc_stat0_busy: {=bool:?}, fmc_stat0_pgerr: {=bool:?}, fmc_stat0_wperr: {=bool:?}, fmc_stat0_endf: {=bool:?} }}" , self . fmc_stat0_busy () , self . fmc_stat0_pgerr () , self . fmc_stat0_wperr () , self . fmc_stat0_endf ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcStat1 (pub u32) ; impl FmcStat1 { # [must_use]
# [inline (always)]
pub const fn fmc_stat1_busy (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat1_pgerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat1_wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat1_endf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat1_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for FmcStat1 { # [inline (always)]
fn default () -> FmcStat1 { FmcStat1 (0) } } impl core :: fmt :: Debug for FmcStat1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcStat1") . field ("fmc_stat1_busy" , & self . fmc_stat1_busy ()) . field ("fmc_stat1_pgerr" , & self . fmc_stat1_pgerr ()) . field ("fmc_stat1_wperr" , & self . fmc_stat1_wperr ()) . field ("fmc_stat1_endf" , & self . fmc_stat1_endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcStat1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcStat1 {{ fmc_stat1_busy: {=bool:?}, fmc_stat1_pgerr: {=bool:?}, fmc_stat1_wperr: {=bool:?}, fmc_stat1_endf: {=bool:?} }}" , self . fmc_stat1_busy () , self . fmc_stat1_pgerr () , self . fmc_stat1_wperr () , self . fmc_stat1_endf ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcWp (pub u32) ; impl FmcWp { # [must_use]
# [inline (always)]
pub const fn fmc_wp_wp (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_wp_wp (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcWp { # [inline (always)]
fn default () -> FmcWp { FmcWp (0) } } impl core :: fmt :: Debug for FmcWp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcWp") . field ("fmc_wp_wp" , & self . fmc_wp_wp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcWp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcWp {{ fmc_wp_wp: {=u32:?} }}" , self . fmc_wp_wp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcWs (pub u32) ; impl FmcWs { # [must_use]
# [inline (always)]
pub const fn fmc_ws_wscnt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_fmc_ws_wscnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } } impl Default for FmcWs { # [inline (always)]
fn default () -> FmcWs { FmcWs (0) } } impl core :: fmt :: Debug for FmcWs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcWs") . field ("fmc_ws_wscnt" , & self . fmc_ws_wscnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcWs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcWs {{ fmc_ws_wscnt: {=u8:?} }}" , self . fmc_ws_wscnt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcWsen (pub u32) ; impl FmcWsen { # [must_use]
# [inline (always)]
pub const fn fmc_wsen_wsen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_wsen_wsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for FmcWsen { # [inline (always)]
fn default () -> FmcWsen { FmcWsen (0) } } impl core :: fmt :: Debug for FmcWsen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcWsen") . field ("fmc_wsen_wsen" , & self . fmc_wsen_wsen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcWsen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcWsen {{ fmc_wsen_wsen: {=bool:?} }}" , self . fmc_wsen_wsen ()) } } }