#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Flash memory controller"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Fmc { ptr : * mut u8 } unsafe impl Send for Fmc { } unsafe impl Sync for Fmc { } impl Fmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Wait state register"]
# [inline (always)]
pub const fn ws (self) -> crate :: common :: Reg < regs :: Ws , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Unlock key register"]
# [inline (always)]
pub const fn key (self) -> crate :: common :: Reg < regs :: Key , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Option byte unlock key register"]
# [inline (always)]
pub const fn obkey (self) -> crate :: common :: Reg < regs :: Obkey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Status register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Option byte control register"]
# [inline (always)]
pub const fn obctl (self) -> crate :: common :: Reg < regs :: Obctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "DCRP start address register 0"]
# [inline (always)]
pub const fn dcrp_saddr0 (self) -> crate :: common :: Reg < regs :: DcrpSaddr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "DCRP end address register"]
# [inline (always)]
pub const fn dcrp_eaddr0 (self) -> crate :: common :: Reg < regs :: DcrpEaddr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Write protection area 0 register"]
# [inline (always)]
pub const fn wp0 (self) -> crate :: common :: Reg < regs :: Wp0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Write protection area 1 register"]
# [inline (always)]
pub const fn wp1 (self) -> crate :: common :: Reg < regs :: Wp1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "DCRP start address register"]
# [inline (always)]
pub const fn dcrp_saddr1 (self) -> crate :: common :: Reg < regs :: DcrpSaddr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "DCRP end address register"]
# [inline (always)]
pub const fn dcrp_eaddr1 (self) -> crate :: common :: Reg < regs :: DcrpEaddr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Secure user area register"]
# [inline (always)]
pub const fn scr (self) -> crate :: common :: Reg < regs :: Scr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x80usize) as _) } } } pub mod regs { # [doc = "Control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Main flash page program command bit"]
# [inline (always)]
pub const fn pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Main flash page program command bit"]
# [inline (always)]
pub fn set_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Main flash page erase command bit"]
# [inline (always)]
pub const fn per (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Main flash page erase command bit"]
# [inline (always)]
pub fn set_per (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Main flash mass erase command bit"]
# [inline (always)]
pub const fn mer (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Main flash mass erase command bit"]
# [inline (always)]
pub fn set_mer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Page number selection"]
# [inline (always)]
pub const fn pn (& self) -> u8 { let val = (self . 0 >> 3usize) & 0x3f ; val as u8 } # [doc = "Page number selection"]
# [inline (always)]
pub fn set_pn (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 3usize)) | (((val as u32) & 0x3f) << 3usize) ; } # [doc = "Send erase command to FMC bit"]
# [inline (always)]
pub const fn start (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Send erase command to FMC bit"]
# [inline (always)]
pub fn set_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Send option byte change command to FMC bit."]
# [inline (always)]
pub const fn obstart (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Send option byte change command to FMC bit."]
# [inline (always)]
pub fn set_obstart (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Main flash fast program command bit"]
# [inline (always)]
pub const fn fstpg (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Main flash fast program command bit"]
# [inline (always)]
pub fn set_fstpg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "End of operation interrupt enable bit"]
# [inline (always)]
pub const fn endie (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "End of operation interrupt enable bit"]
# [inline (always)]
pub fn set_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "OPRERR error interrupt enable bit"]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "OPRERR error interrupt enable bit"]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Read protection error interrupt enable bit"]
# [inline (always)]
pub const fn rperrie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Read protection error interrupt enable bit"]
# [inline (always)]
pub fn set_rperrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "Option byte reload bit"]
# [inline (always)]
pub const fn obrld (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "Option byte reload bit"]
# [inline (always)]
pub fn set_obrld (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "Secure-access area enable bit."]
# [inline (always)]
pub const fn scr (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Secure-access area enable bit."]
# [inline (always)]
pub fn set_scr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "FMC_OBCTL lock bit"]
# [inline (always)]
pub const fn oblk (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "FMC_OBCTL lock bit"]
# [inline (always)]
pub fn set_oblk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "FMC_CTL lock bit"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "FMC_CTL lock bit"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("pg" , & self . pg ()) . field ("per" , & self . per ()) . field ("mer" , & self . mer ()) . field ("pn" , & self . pn ()) . field ("start" , & self . start ()) . field ("obstart" , & self . obstart ()) . field ("fstpg" , & self . fstpg ()) . field ("endie" , & self . endie ()) . field ("errie" , & self . errie ()) . field ("rperrie" , & self . rperrie ()) . field ("obrld" , & self . obrld ()) . field ("scr" , & self . scr ()) . field ("oblk" , & self . oblk ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ pg: {=bool:?}, per: {=bool:?}, mer: {=bool:?}, pn: {=u8:?}, start: {=bool:?}, obstart: {=bool:?}, fstpg: {=bool:?}, endie: {=bool:?}, errie: {=bool:?}, rperrie: {=bool:?}, obrld: {=bool:?}, scr: {=bool:?}, oblk: {=bool:?}, lk: {=bool:?} }}" , self . pg () , self . per () , self . mer () , self . pn () , self . start () , self . obstart () , self . fstpg () , self . endie () , self . errie () , self . rperrie () , self . obrld () , self . scr () , self . oblk () , self . lk ()) } } # [doc = "DCRP end address register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DcrpEaddr0 (pub u32) ; impl DcrpEaddr0 { # [doc = "DCRP area 0 end address offset"]
# [inline (always)]
pub const fn dcrp0_eaddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "DCRP area 0 end address offset"]
# [inline (always)]
pub fn set_dcrp0_eaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } # [doc = "DCRP area erase enable configuration bit."]
# [inline (always)]
pub const fn dcrp_eren (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "DCRP area erase enable configuration bit."]
# [inline (always)]
pub fn set_dcrp_eren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for DcrpEaddr0 { # [inline (always)]
fn default () -> DcrpEaddr0 { DcrpEaddr0 (0) } } impl core :: fmt :: Debug for DcrpEaddr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DcrpEaddr0") . field ("dcrp0_eaddr" , & self . dcrp0_eaddr ()) . field ("dcrp_eren" , & self . dcrp_eren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DcrpEaddr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DcrpEaddr0 {{ dcrp0_eaddr: {=u8:?}, dcrp_eren: {=bool:?} }}" , self . dcrp0_eaddr () , self . dcrp_eren ()) } } # [doc = "DCRP end address register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DcrpEaddr1 (pub u32) ; impl DcrpEaddr1 { # [doc = "DCRP area 1 end address offset"]
# [inline (always)]
pub const fn dcrp1_eaddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "DCRP area 1 end address offset"]
# [inline (always)]
pub fn set_dcrp1_eaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } } impl Default for DcrpEaddr1 { # [inline (always)]
fn default () -> DcrpEaddr1 { DcrpEaddr1 (0) } } impl core :: fmt :: Debug for DcrpEaddr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DcrpEaddr1") . field ("dcrp1_eaddr" , & self . dcrp1_eaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DcrpEaddr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DcrpEaddr1 {{ dcrp1_eaddr: {=u8:?} }}" , self . dcrp1_eaddr ()) } } # [doc = "DCRP start address register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DcrpSaddr0 (pub u32) ; impl DcrpSaddr0 { # [doc = "DCRP area 0 start address"]
# [inline (always)]
pub const fn dcrp0_saddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "DCRP area 0 start address"]
# [inline (always)]
pub fn set_dcrp0_saddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } } impl Default for DcrpSaddr0 { # [inline (always)]
fn default () -> DcrpSaddr0 { DcrpSaddr0 (0) } } impl core :: fmt :: Debug for DcrpSaddr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DcrpSaddr0") . field ("dcrp0_saddr" , & self . dcrp0_saddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DcrpSaddr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DcrpSaddr0 {{ dcrp0_saddr: {=u8:?} }}" , self . dcrp0_saddr ()) } } # [doc = "DCRP start address register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct DcrpSaddr1 (pub u32) ; impl DcrpSaddr1 { # [doc = "DCRP area 1 start address offset"]
# [inline (always)]
pub const fn dcrp1_saddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "DCRP area 1 start address offset"]
# [inline (always)]
pub fn set_dcrp1_saddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } } impl Default for DcrpSaddr1 { # [inline (always)]
fn default () -> DcrpSaddr1 { DcrpSaddr1 (0) } } impl core :: fmt :: Debug for DcrpSaddr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("DcrpSaddr1") . field ("dcrp1_saddr" , & self . dcrp1_saddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for DcrpSaddr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "DcrpSaddr1 {{ dcrp1_saddr: {=u8:?} }}" , self . dcrp1_saddr ()) } } # [doc = "Unlock key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Key (pub u32) ; impl Key { # [doc = "FMC_CTL unlock register"]
# [inline (always)]
pub const fn key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "FMC_CTL unlock register"]
# [inline (always)]
pub fn set_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Key { # [inline (always)]
fn default () -> Key { Key (0) } } impl core :: fmt :: Debug for Key { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Key") . field ("key" , & self . key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Key { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Key {{ key: {=u32:?} }}" , self . key ()) } } # [doc = "Option byte control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obctl (pub u32) ; impl Obctl { # [doc = "Security protection level option byte status bits"]
# [inline (always)]
pub const fn spc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Security protection level option byte status bits"]
# [inline (always)]
pub fn set_spc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Brown out reset enable"]
# [inline (always)]
pub const fn borst_en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Brown out reset enable"]
# [inline (always)]
pub fn set_borst_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "BOR threshold at rising VDD supply"]
# [inline (always)]
pub const fn borr_th (& self) -> u8 { let val = (self . 0 >> 9usize) & 0x03 ; val as u8 } # [doc = "BOR threshold at rising VDD supply"]
# [inline (always)]
pub fn set_borr_th (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 9usize)) | (((val as u32) & 0x03) << 9usize) ; } # [doc = "BOR threshold at falling VDD supply"]
# [inline (always)]
pub const fn borf_th (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x03 ; val as u8 } # [doc = "BOR threshold at falling VDD supply"]
# [inline (always)]
pub fn set_borf_th (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 11usize)) | (((val as u32) & 0x03) << 11usize) ; } # [doc = "Option byte deepsleep reset value"]
# [inline (always)]
pub const fn n_rst_dpslp (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Option byte deepsleep reset value"]
# [inline (always)]
pub fn set_n_rst_dpslp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Option byte standby reset value"]
# [inline (always)]
pub const fn n_rst_stdby (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Option byte standby reset value"]
# [inline (always)]
pub fn set_n_rst_stdby (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Free watchdog configuration bit"]
# [inline (always)]
pub const fn n_fwdg_hw (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Free watchdog configuration bit"]
# [inline (always)]
pub fn set_n_fwdg_hw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Window watchdog configuration bit"]
# [inline (always)]
pub const fn n_wwdg_hw (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Window watchdog configuration bit"]
# [inline (always)]
pub fn set_n_wwdg_hw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "HXTAL remapping"]
# [inline (always)]
pub const fn hxtal_remap (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "HXTAL remapping"]
# [inline (always)]
pub fn set_hxtal_remap (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "SRAM ECC disable"]
# [inline (always)]
pub const fn sram_eccen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "SRAM ECC disable"]
# [inline (always)]
pub fn set_sram_eccen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "Software BOOT0"]
# [inline (always)]
pub const fn swbt0 (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Software BOOT0"]
# [inline (always)]
pub fn set_swbt0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "BOOT1 option bit"]
# [inline (always)]
pub const fn n_boot1 (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "BOOT1 option bit"]
# [inline (always)]
pub fn set_n_boot1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "BOOT0 option bit"]
# [inline (always)]
pub const fn n_boot0 (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "BOOT0 option bit"]
# [inline (always)]
pub fn set_n_boot0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "NRST pin mode selection."]
# [inline (always)]
pub const fn nrst_mdsel (& self) -> u8 { let val = (self . 0 >> 27usize) & 0x03 ; val as u8 } # [doc = "NRST pin mode selection."]
# [inline (always)]
pub fn set_nrst_mdsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 27usize)) | (((val as u32) & 0x03) << 27usize) ; } } impl Default for Obctl { # [inline (always)]
fn default () -> Obctl { Obctl (0) } } impl core :: fmt :: Debug for Obctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obctl") . field ("spc" , & self . spc ()) . field ("borst_en" , & self . borst_en ()) . field ("borr_th" , & self . borr_th ()) . field ("borf_th" , & self . borf_th ()) . field ("n_rst_dpslp" , & self . n_rst_dpslp ()) . field ("n_rst_stdby" , & self . n_rst_stdby ()) . field ("n_fwdg_hw" , & self . n_fwdg_hw ()) . field ("n_wwdg_hw" , & self . n_wwdg_hw ()) . field ("hxtal_remap" , & self . hxtal_remap ()) . field ("sram_eccen" , & self . sram_eccen ()) . field ("swbt0" , & self . swbt0 ()) . field ("n_boot1" , & self . n_boot1 ()) . field ("n_boot0" , & self . n_boot0 ()) . field ("nrst_mdsel" , & self . nrst_mdsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obctl {{ spc: {=u8:?}, borst_en: {=bool:?}, borr_th: {=u8:?}, borf_th: {=u8:?}, n_rst_dpslp: {=bool:?}, n_rst_stdby: {=bool:?}, n_fwdg_hw: {=bool:?}, n_wwdg_hw: {=bool:?}, hxtal_remap: {=bool:?}, sram_eccen: {=bool:?}, swbt0: {=bool:?}, n_boot1: {=bool:?}, n_boot0: {=bool:?}, nrst_mdsel: {=u8:?} }}" , self . spc () , self . borst_en () , self . borr_th () , self . borf_th () , self . n_rst_dpslp () , self . n_rst_stdby () , self . n_fwdg_hw () , self . n_wwdg_hw () , self . hxtal_remap () , self . sram_eccen () , self . swbt0 () , self . n_boot1 () , self . n_boot0 () , self . nrst_mdsel ()) } } # [doc = "Option byte unlock key register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Obkey (pub u32) ; impl Obkey { # [doc = "FMC_CTL option bytes operation unlock register"]
# [inline (always)]
pub const fn obkey (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "FMC_CTL option bytes operation unlock register"]
# [inline (always)]
pub fn set_obkey (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Obkey { # [inline (always)]
fn default () -> Obkey { Obkey (0) } } impl core :: fmt :: Debug for Obkey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Obkey") . field ("obkey" , & self . obkey ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Obkey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Obkey {{ obkey: {=u32:?} }}" , self . obkey ()) } } # [doc = "Secure user area register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Scr (pub u32) ; impl Scr { # [doc = "Configure the number of pages in secure user area."]
# [inline (always)]
pub const fn scr_page_cnt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "Configure the number of pages in secure user area."]
# [inline (always)]
pub fn set_scr_page_cnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } # [doc = "This bit is set to force boot from user Flash area."]
# [inline (always)]
pub const fn bootlk (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "This bit is set to force boot from user Flash area."]
# [inline (always)]
pub fn set_bootlk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for Scr { # [inline (always)]
fn default () -> Scr { Scr (0) } } impl core :: fmt :: Debug for Scr { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Scr") . field ("scr_page_cnt" , & self . scr_page_cnt ()) . field ("bootlk" , & self . bootlk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Scr { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Scr {{ scr_page_cnt: {=u8:?}, bootlk: {=bool:?} }}" , self . scr_page_cnt () , self . bootlk ()) } } # [doc = "Status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "End of operation flag bit"]
# [inline (always)]
pub const fn endf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "End of operation flag bit"]
# [inline (always)]
pub fn set_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Operation error flag bit"]
# [inline (always)]
pub const fn oprerr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Operation error flag bit"]
# [inline (always)]
pub fn set_oprerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Program error flag bit"]
# [inline (always)]
pub const fn pgerr (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Program error flag bit"]
# [inline (always)]
pub fn set_pgerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Erase / program protection error flag bit."]
# [inline (always)]
pub const fn wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Erase / program protection error flag bit."]
# [inline (always)]
pub fn set_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Program alignment error flag bit"]
# [inline (always)]
pub const fn pgaerr (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Program alignment error flag bit"]
# [inline (always)]
pub fn set_pgaerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Program size not match error flag bit. This bit is set by hardware when program size is a half-word/word access. The only correct programming size is double word."]
# [inline (always)]
pub const fn pgmerr (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Program size not match error flag bit. This bit is set by hardware when program size is a half-word/word access. The only correct programming size is double word."]
# [inline (always)]
pub fn set_pgmerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Program sequence error flag bit."]
# [inline (always)]
pub const fn pgserr (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Program sequence error flag bit."]
# [inline (always)]
pub fn set_pgserr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Fast programming error flag bit."]
# [inline (always)]
pub const fn fstperr (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Fast programming error flag bit."]
# [inline (always)]
pub fn set_fstperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Read protection error flag bit."]
# [inline (always)]
pub const fn rperr (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Read protection error flag bit."]
# [inline (always)]
pub fn set_rperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Option byte read error bit."]
# [inline (always)]
pub const fn oberr (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Option byte read error bit."]
# [inline (always)]
pub fn set_oberr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "The flash is busy bit"]
# [inline (always)]
pub const fn busy (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "The flash is busy bit"]
# [inline (always)]
pub fn set_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } impl core :: fmt :: Debug for Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat") . field ("endf" , & self . endf ()) . field ("oprerr" , & self . oprerr ()) . field ("pgerr" , & self . pgerr ()) . field ("wperr" , & self . wperr ()) . field ("pgaerr" , & self . pgaerr ()) . field ("pgmerr" , & self . pgmerr ()) . field ("pgserr" , & self . pgserr ()) . field ("fstperr" , & self . fstperr ()) . field ("rperr" , & self . rperr ()) . field ("oberr" , & self . oberr ()) . field ("busy" , & self . busy ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat {{ endf: {=bool:?}, oprerr: {=bool:?}, pgerr: {=bool:?}, wperr: {=bool:?}, pgaerr: {=bool:?}, pgmerr: {=bool:?}, pgserr: {=bool:?}, fstperr: {=bool:?}, rperr: {=bool:?}, oberr: {=bool:?}, busy: {=bool:?} }}" , self . endf () , self . oprerr () , self . pgerr () , self . wperr () , self . pgaerr () , self . pgmerr () , self . pgserr () , self . fstperr () , self . rperr () , self . oberr () , self . busy ()) } } # [doc = "Write protection area 0 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wp0 (pub u32) ; impl Wp0 { # [doc = "Write protection area 0 end address offset"]
# [inline (always)]
pub const fn wp0_saddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [doc = "Write protection area 0 end address offset"]
# [inline (always)]
pub fn set_wp0_saddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [doc = "Write protection area 0 end address offset"]
# [inline (always)]
pub const fn wp0_eaddr (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x3f ; val as u8 } # [doc = "Write protection area 0 end address offset"]
# [inline (always)]
pub fn set_wp0_eaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 16usize)) | (((val as u32) & 0x3f) << 16usize) ; } } impl Default for Wp0 { # [inline (always)]
fn default () -> Wp0 { Wp0 (0) } } impl core :: fmt :: Debug for Wp0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Wp0") . field ("wp0_saddr" , & self . wp0_saddr ()) . field ("wp0_eaddr" , & self . wp0_eaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Wp0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Wp0 {{ wp0_saddr: {=u8:?}, wp0_eaddr: {=u8:?} }}" , self . wp0_saddr () , self . wp0_eaddr ()) } } # [doc = "Write protection area 1 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wp1 (pub u32) ; impl Wp1 { # [doc = "Write protection area 1 start address offset"]
# [inline (always)]
pub const fn wp1_saddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [doc = "Write protection area 1 start address offset"]
# [inline (always)]
pub fn set_wp1_saddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [doc = "Write protection area 1 end address offset"]
# [inline (always)]
pub const fn wp1_eaddr (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x3f ; val as u8 } # [doc = "Write protection area 1 end address offset"]
# [inline (always)]
pub fn set_wp1_eaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 16usize)) | (((val as u32) & 0x3f) << 16usize) ; } } impl Default for Wp1 { # [inline (always)]
fn default () -> Wp1 { Wp1 (0) } } impl core :: fmt :: Debug for Wp1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Wp1") . field ("wp1_saddr" , & self . wp1_saddr ()) . field ("wp1_eaddr" , & self . wp1_eaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Wp1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Wp1 {{ wp1_saddr: {=u8:?}, wp1_eaddr: {=u8:?} }}" , self . wp1_saddr () , self . wp1_eaddr ()) } } # [doc = "Wait state register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ws (pub u32) ; impl Ws { # [doc = "Wait state counter register"]
# [inline (always)]
pub const fn wscnt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "Wait state counter register"]
# [inline (always)]
pub fn set_wscnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "Pre-fetch enable"]
# [inline (always)]
pub const fn pfen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Pre-fetch enable"]
# [inline (always)]
pub fn set_pfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "IBUS cache enable"]
# [inline (always)]
pub const fn icen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "IBUS cache enable"]
# [inline (always)]
pub fn set_icen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "IBUS cache reset."]
# [inline (always)]
pub const fn icrst (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "IBUS cache reset."]
# [inline (always)]
pub fn set_icrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Main flash programmed or empty flag"]
# [inline (always)]
pub const fn mfpe (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Main flash programmed or empty flag"]
# [inline (always)]
pub fn set_mfpe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Debugger enable"]
# [inline (always)]
pub const fn dbgen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Debugger enable"]
# [inline (always)]
pub fn set_dbgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for Ws { # [inline (always)]
fn default () -> Ws { Ws (0) } } impl core :: fmt :: Debug for Ws { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ws") . field ("wscnt" , & self . wscnt ()) . field ("pfen" , & self . pfen ()) . field ("icen" , & self . icen ()) . field ("icrst" , & self . icrst ()) . field ("mfpe" , & self . mfpe ()) . field ("dbgen" , & self . dbgen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ws { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ws {{ wscnt: {=u8:?}, pfen: {=bool:?}, icen: {=bool:?}, icrst: {=bool:?}, mfpe: {=bool:?}, dbgen: {=bool:?} }}" , self . wscnt () , self . pfen () , self . icen () , self . icrst () , self . mfpe () , self . dbgen ()) } } }