#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Fmc { ptr : * mut u8 } unsafe impl Send for Fmc { } unsafe impl Sync for Fmc { } impl Fmc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn fmc_key (self) -> crate :: common :: Reg < regs :: FmcKey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn fmc_obkey (self) -> crate :: common :: Reg < regs :: FmcObkey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn fmc_stat (self) -> crate :: common :: Reg < regs :: FmcStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn fmc_ctl (self) -> crate :: common :: Reg < regs :: FmcCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn fmc_obctl0 (self) -> crate :: common :: Reg < regs :: FmcObctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn fmc_obctl1 (self) -> crate :: common :: Reg < regs :: FmcObctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn fmc_pecfg (self) -> crate :: common :: Reg < regs :: FmcPecfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn fmc_pekey (self) -> crate :: common :: Reg < regs :: FmcPekey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn fmc_otp1cfg (self) -> crate :: common :: Reg < regs :: FmcOtp1cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn fmc_ldeccaddr0 (self) -> crate :: common :: Reg < regs :: FmcLdeccaddr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn fmc_ldeccaddr1 (self) -> crate :: common :: Reg < regs :: FmcLdeccaddr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn fmc_ldeccaddr2 (self) -> crate :: common :: Reg < regs :: FmcLdeccaddr2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn fmc_obstat (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn fmc_pid (self) -> crate :: common :: Reg < regs :: FmcPid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0100usize) as _) } } # [inline (always)]
pub const fn efuse_cs (self) -> crate :: common :: Reg < regs :: EfuseCs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0200usize) as _) } } # [inline (always)]
pub const fn efuse_addr (self) -> crate :: common :: Reg < regs :: EfuseAddr , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0204usize) as _) } } # [inline (always)]
pub const fn efuse_ctl (self) -> crate :: common :: Reg < regs :: EfuseCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0208usize) as _) } } # [inline (always)]
pub const fn efuse_user_data (self) -> crate :: common :: Reg < regs :: EfuseUserData , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x020cusize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseAddr (pub u32) ; impl EfuseAddr { # [must_use]
# [inline (always)]
pub const fn efuse_addr_efaddr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_efuse_addr_efaddr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_addr_efsize (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_efuse_addr_efsize (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize) ; } } impl Default for EfuseAddr { # [inline (always)]
fn default () -> EfuseAddr { EfuseAddr (0) } } impl core :: fmt :: Debug for EfuseAddr { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseAddr") . field ("efuse_addr_efaddr" , & self . efuse_addr_efaddr ()) . field ("efuse_addr_efsize" , & self . efuse_addr_efsize ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseAddr { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseAddr {{ efuse_addr_efaddr: {=u8:?}, efuse_addr_efsize: {=u8:?} }}" , self . efuse_addr_efaddr () , self . efuse_addr_efsize ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseCs (pub u32) ; impl EfuseCs { # [must_use]
# [inline (always)]
pub const fn efuse_cs_efstr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_efstr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_efrw (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_efrw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_efbyp (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_efbyp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_pgif (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_pgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_rdif (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_rdif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_ovberif (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_ovberif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_pgie (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_pgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_rdie (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_rdie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_ovberie (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_ovberie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_pgic (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_pgic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_rdic (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_rdic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_cs_ovberic (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_cs_ovberic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } } impl Default for EfuseCs { # [inline (always)]
fn default () -> EfuseCs { EfuseCs (0) } } impl core :: fmt :: Debug for EfuseCs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseCs") . field ("efuse_cs_efstr" , & self . efuse_cs_efstr ()) . field ("efuse_cs_efrw" , & self . efuse_cs_efrw ()) . field ("efuse_cs_efbyp" , & self . efuse_cs_efbyp ()) . field ("efuse_cs_pgif" , & self . efuse_cs_pgif ()) . field ("efuse_cs_rdif" , & self . efuse_cs_rdif ()) . field ("efuse_cs_ovberif" , & self . efuse_cs_ovberif ()) . field ("efuse_cs_pgie" , & self . efuse_cs_pgie ()) . field ("efuse_cs_rdie" , & self . efuse_cs_rdie ()) . field ("efuse_cs_ovberie" , & self . efuse_cs_ovberie ()) . field ("efuse_cs_pgic" , & self . efuse_cs_pgic ()) . field ("efuse_cs_rdic" , & self . efuse_cs_rdic ()) . field ("efuse_cs_ovberic" , & self . efuse_cs_ovberic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseCs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseCs {{ efuse_cs_efstr: {=bool:?}, efuse_cs_efrw: {=bool:?}, efuse_cs_efbyp: {=bool:?}, efuse_cs_pgif: {=bool:?}, efuse_cs_rdif: {=bool:?}, efuse_cs_ovberif: {=bool:?}, efuse_cs_pgie: {=bool:?}, efuse_cs_rdie: {=bool:?}, efuse_cs_ovberie: {=bool:?}, efuse_cs_pgic: {=bool:?}, efuse_cs_rdic: {=bool:?}, efuse_cs_ovberic: {=bool:?} }}" , self . efuse_cs_efstr () , self . efuse_cs_efrw () , self . efuse_cs_efbyp () , self . efuse_cs_pgif () , self . efuse_cs_rdif () , self . efuse_cs_ovberif () , self . efuse_cs_pgie () , self . efuse_cs_rdie () , self . efuse_cs_ovberie () , self . efuse_cs_pgic () , self . efuse_cs_rdic () , self . efuse_cs_ovberic ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseCtl (pub u32) ; impl EfuseCtl { # [must_use]
# [inline (always)]
pub const fn efuse_ctl_efspc (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl_efspc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl_ndbg (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl_ndbg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl_nbtsb (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl_nbtsb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl_btfosel (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl_btfosel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl_udlk (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl_udlk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn efuse_ctl_lk (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_efuse_ctl_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for EfuseCtl { # [inline (always)]
fn default () -> EfuseCtl { EfuseCtl (0) } } impl core :: fmt :: Debug for EfuseCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseCtl") . field ("efuse_ctl_efspc" , & self . efuse_ctl_efspc ()) . field ("efuse_ctl_ndbg" , & self . efuse_ctl_ndbg ()) . field ("efuse_ctl_nbtsb" , & self . efuse_ctl_nbtsb ()) . field ("efuse_ctl_btfosel" , & self . efuse_ctl_btfosel ()) . field ("efuse_ctl_udlk" , & self . efuse_ctl_udlk ()) . field ("efuse_ctl_lk" , & self . efuse_ctl_lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseCtl {{ efuse_ctl_efspc: {=bool:?}, efuse_ctl_ndbg: {=bool:?}, efuse_ctl_nbtsb: {=bool:?}, efuse_ctl_btfosel: {=bool:?}, efuse_ctl_udlk: {=bool:?}, efuse_ctl_lk: {=bool:?} }}" , self . efuse_ctl_efspc () , self . efuse_ctl_ndbg () , self . efuse_ctl_nbtsb () , self . efuse_ctl_btfosel () , self . efuse_ctl_udlk () , self . efuse_ctl_lk ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EfuseUserData (pub u32) ; impl EfuseUserData { # [must_use]
# [inline (always)]
pub const fn efuse_user_data_userdata (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_efuse_user_data_userdata (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for EfuseUserData { # [inline (always)]
fn default () -> EfuseUserData { EfuseUserData (0) } } impl core :: fmt :: Debug for EfuseUserData { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("EfuseUserData") . field ("efuse_user_data_userdata" , & self . efuse_user_data_userdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for EfuseUserData { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "EfuseUserData {{ efuse_user_data_userdata: {=u8:?} }}" , self . efuse_user_data_userdata ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcCtl (pub u32) ; impl FmcCtl { # [must_use]
# [inline (always)]
pub const fn fmc_ctl_pg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_pg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_ser (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_ser (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_mer0 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_mer0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_sn (& self) -> u8 { let val = (self . 0 >> 3usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_fmc_ctl_sn (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 3usize)) | (((val as u32) & 0x1f) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_psz (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_fmc_ctl_psz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_dwpge (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_dwpge (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_sn_5 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_sn_5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_mer1 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_mer1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_start (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_endie (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_endie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_errie (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_ldeccie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_ldeccie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_nwlde (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_nwlde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_rlbp (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_rlbp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_ctl_lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_ctl_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for FmcCtl { # [inline (always)]
fn default () -> FmcCtl { FmcCtl (0) } } impl core :: fmt :: Debug for FmcCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcCtl") . field ("fmc_ctl_pg" , & self . fmc_ctl_pg ()) . field ("fmc_ctl_ser" , & self . fmc_ctl_ser ()) . field ("fmc_ctl_mer0" , & self . fmc_ctl_mer0 ()) . field ("fmc_ctl_sn" , & self . fmc_ctl_sn ()) . field ("fmc_ctl_psz" , & self . fmc_ctl_psz ()) . field ("fmc_ctl_dwpge" , & self . fmc_ctl_dwpge ()) . field ("fmc_ctl_sn_5" , & self . fmc_ctl_sn_5 ()) . field ("fmc_ctl_mer1" , & self . fmc_ctl_mer1 ()) . field ("fmc_ctl_start" , & self . fmc_ctl_start ()) . field ("fmc_ctl_endie" , & self . fmc_ctl_endie ()) . field ("fmc_ctl_errie" , & self . fmc_ctl_errie ()) . field ("fmc_ctl_ldeccie" , & self . fmc_ctl_ldeccie ()) . field ("fmc_ctl_nwlde" , & self . fmc_ctl_nwlde ()) . field ("fmc_ctl_rlbp" , & self . fmc_ctl_rlbp ()) . field ("fmc_ctl_lk" , & self . fmc_ctl_lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcCtl {{ fmc_ctl_pg: {=bool:?}, fmc_ctl_ser: {=bool:?}, fmc_ctl_mer0: {=bool:?}, fmc_ctl_sn: {=u8:?}, fmc_ctl_psz: {=u8:?}, fmc_ctl_dwpge: {=bool:?}, fmc_ctl_sn_5: {=bool:?}, fmc_ctl_mer1: {=bool:?}, fmc_ctl_start: {=bool:?}, fmc_ctl_endie: {=bool:?}, fmc_ctl_errie: {=bool:?}, fmc_ctl_ldeccie: {=bool:?}, fmc_ctl_nwlde: {=bool:?}, fmc_ctl_rlbp: {=bool:?}, fmc_ctl_lk: {=bool:?} }}" , self . fmc_ctl_pg () , self . fmc_ctl_ser () , self . fmc_ctl_mer0 () , self . fmc_ctl_sn () , self . fmc_ctl_psz () , self . fmc_ctl_dwpge () , self . fmc_ctl_sn_5 () , self . fmc_ctl_mer1 () , self . fmc_ctl_start () , self . fmc_ctl_endie () , self . fmc_ctl_errie () , self . fmc_ctl_ldeccie () , self . fmc_ctl_nwlde () , self . fmc_ctl_rlbp () , self . fmc_ctl_lk ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcKey (pub u32) ; impl FmcKey { # [must_use]
# [inline (always)]
pub const fn fmc_key_key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_key_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcKey { # [inline (always)]
fn default () -> FmcKey { FmcKey (0) } } impl core :: fmt :: Debug for FmcKey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcKey") . field ("fmc_key_key" , & self . fmc_key_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcKey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcKey {{ fmc_key_key: {=u32:?} }}" , self . fmc_key_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcLdeccaddr0 (pub u32) ; impl FmcLdeccaddr0 { # [must_use]
# [inline (always)]
pub const fn fmc_ldeccaddr0_ldeccaddr0 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_ldeccaddr0_ldeccaddr0 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcLdeccaddr0 { # [inline (always)]
fn default () -> FmcLdeccaddr0 { FmcLdeccaddr0 (0) } } impl core :: fmt :: Debug for FmcLdeccaddr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcLdeccaddr0") . field ("fmc_ldeccaddr0_ldeccaddr0" , & self . fmc_ldeccaddr0_ldeccaddr0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcLdeccaddr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcLdeccaddr0 {{ fmc_ldeccaddr0_ldeccaddr0: {=u32:?} }}" , self . fmc_ldeccaddr0_ldeccaddr0 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcLdeccaddr1 (pub u32) ; impl FmcLdeccaddr1 { # [must_use]
# [inline (always)]
pub const fn fmc_ldeccaddr1_ldeccaddr1 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_ldeccaddr1_ldeccaddr1 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcLdeccaddr1 { # [inline (always)]
fn default () -> FmcLdeccaddr1 { FmcLdeccaddr1 (0) } } impl core :: fmt :: Debug for FmcLdeccaddr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcLdeccaddr1") . field ("fmc_ldeccaddr1_ldeccaddr1" , & self . fmc_ldeccaddr1_ldeccaddr1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcLdeccaddr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcLdeccaddr1 {{ fmc_ldeccaddr1_ldeccaddr1: {=u32:?} }}" , self . fmc_ldeccaddr1_ldeccaddr1 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcLdeccaddr2 (pub u32) ; impl FmcLdeccaddr2 { # [must_use]
# [inline (always)]
pub const fn fmc_ldeccaddr2_ldeccaddr2 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_ldeccaddr2_ldeccaddr2 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcLdeccaddr2 { # [inline (always)]
fn default () -> FmcLdeccaddr2 { FmcLdeccaddr2 (0) } } impl core :: fmt :: Debug for FmcLdeccaddr2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcLdeccaddr2") . field ("fmc_ldeccaddr2_ldeccaddr2" , & self . fmc_ldeccaddr2_ldeccaddr2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcLdeccaddr2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcLdeccaddr2 {{ fmc_ldeccaddr2_ldeccaddr2: {=u32:?} }}" , self . fmc_ldeccaddr2_ldeccaddr2 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObctl0 (pub u32) ; impl FmcObctl0 { # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_ob_lk (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_ob_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_ob_start (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_ob_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_bor_th (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_fmc_obctl0_bor_th (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_bb (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_bb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_nwdg_hw (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_nwdg_hw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_nrst_dpslp (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_nrst_dpslp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_nrst_stdby (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_nrst_stdby (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_spc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_fmc_obctl0_spc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_wp0 (& self) -> u16 { let val = (self . 0 >> 16usize) & 0x0fff ; val as u16 } # [inline (always)]
pub const fn set_fmc_obctl0_wp0 (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 16usize)) | (((val as u32) & 0x0fff) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_eccen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_eccen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_nwa (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_nwa (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl0_drp (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_obctl0_drp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for FmcObctl0 { # [inline (always)]
fn default () -> FmcObctl0 { FmcObctl0 (0) } } impl core :: fmt :: Debug for FmcObctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObctl0") . field ("fmc_obctl0_ob_lk" , & self . fmc_obctl0_ob_lk ()) . field ("fmc_obctl0_ob_start" , & self . fmc_obctl0_ob_start ()) . field ("fmc_obctl0_bor_th" , & self . fmc_obctl0_bor_th ()) . field ("fmc_obctl0_bb" , & self . fmc_obctl0_bb ()) . field ("fmc_obctl0_nwdg_hw" , & self . fmc_obctl0_nwdg_hw ()) . field ("fmc_obctl0_nrst_dpslp" , & self . fmc_obctl0_nrst_dpslp ()) . field ("fmc_obctl0_nrst_stdby" , & self . fmc_obctl0_nrst_stdby ()) . field ("fmc_obctl0_spc" , & self . fmc_obctl0_spc ()) . field ("fmc_obctl0_wp0" , & self . fmc_obctl0_wp0 ()) . field ("fmc_obctl0_eccen" , & self . fmc_obctl0_eccen ()) . field ("fmc_obctl0_nwa" , & self . fmc_obctl0_nwa ()) . field ("fmc_obctl0_drp" , & self . fmc_obctl0_drp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObctl0 {{ fmc_obctl0_ob_lk: {=bool:?}, fmc_obctl0_ob_start: {=bool:?}, fmc_obctl0_bor_th: {=u8:?}, fmc_obctl0_bb: {=bool:?}, fmc_obctl0_nwdg_hw: {=bool:?}, fmc_obctl0_nrst_dpslp: {=bool:?}, fmc_obctl0_nrst_stdby: {=bool:?}, fmc_obctl0_spc: {=u8:?}, fmc_obctl0_wp0: {=u16:?}, fmc_obctl0_eccen: {=bool:?}, fmc_obctl0_nwa: {=bool:?}, fmc_obctl0_drp: {=bool:?} }}" , self . fmc_obctl0_ob_lk () , self . fmc_obctl0_ob_start () , self . fmc_obctl0_bor_th () , self . fmc_obctl0_bb () , self . fmc_obctl0_nwdg_hw () , self . fmc_obctl0_nrst_dpslp () , self . fmc_obctl0_nrst_stdby () , self . fmc_obctl0_spc () , self . fmc_obctl0_wp0 () , self . fmc_obctl0_eccen () , self . fmc_obctl0_nwa () , self . fmc_obctl0_drp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObctl1 (pub u32) ; impl FmcObctl1 { # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_wp0_h (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_fmc_obctl1_wp0_h (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_wp1_h (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_fmc_obctl1_wp1_h (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_obctl1_wp1_l (& self) -> u16 { let val = (self . 0 >> 16usize) & 0x0fff ; val as u16 } # [inline (always)]
pub const fn set_fmc_obctl1_wp1_l (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 16usize)) | (((val as u32) & 0x0fff) << 16usize) ; } } impl Default for FmcObctl1 { # [inline (always)]
fn default () -> FmcObctl1 { FmcObctl1 (0) } } impl core :: fmt :: Debug for FmcObctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObctl1") . field ("fmc_obctl1_wp0_h" , & self . fmc_obctl1_wp0_h ()) . field ("fmc_obctl1_wp1_h" , & self . fmc_obctl1_wp1_h ()) . field ("fmc_obctl1_wp1_l" , & self . fmc_obctl1_wp1_l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObctl1 {{ fmc_obctl1_wp0_h: {=u8:?}, fmc_obctl1_wp1_h: {=u8:?}, fmc_obctl1_wp1_l: {=u16:?} }}" , self . fmc_obctl1_wp0_h () , self . fmc_obctl1_wp1_h () , self . fmc_obctl1_wp1_l ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcObkey (pub u32) ; impl FmcObkey { # [must_use]
# [inline (always)]
pub const fn fmc_obkey_obkey (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_obkey_obkey (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcObkey { # [inline (always)]
fn default () -> FmcObkey { FmcObkey (0) } } impl core :: fmt :: Debug for FmcObkey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcObkey") . field ("fmc_obkey_obkey" , & self . fmc_obkey_obkey ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcObkey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcObkey {{ fmc_obkey_obkey: {=u32:?} }}" , self . fmc_obkey_obkey ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcOtp1cfg (pub u32) ; impl FmcOtp1cfg { # [must_use]
# [inline (always)]
pub const fn fmc_otp1cfg_otp1ren (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_fmc_otp1cfg_otp1ren (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for FmcOtp1cfg { # [inline (always)]
fn default () -> FmcOtp1cfg { FmcOtp1cfg (0) } } impl core :: fmt :: Debug for FmcOtp1cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcOtp1cfg") . field ("fmc_otp1cfg_otp1ren" , & self . fmc_otp1cfg_otp1ren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcOtp1cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcOtp1cfg {{ fmc_otp1cfg_otp1ren: {=u16:?} }}" , self . fmc_otp1cfg_otp1ren ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcPecfg (pub u32) ; impl FmcPecfg { # [must_use]
# [inline (always)]
pub const fn fmc_pecfg_pe_addr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0x1fff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_pecfg_pe_addr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0x1fff_ffff << 0usize)) | (((val as u32) & 0x1fff_ffff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_pecfg_pe_en (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_pecfg_pe_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for FmcPecfg { # [inline (always)]
fn default () -> FmcPecfg { FmcPecfg (0) } } impl core :: fmt :: Debug for FmcPecfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcPecfg") . field ("fmc_pecfg_pe_addr" , & self . fmc_pecfg_pe_addr ()) . field ("fmc_pecfg_pe_en" , & self . fmc_pecfg_pe_en ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcPecfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcPecfg {{ fmc_pecfg_pe_addr: {=u32:?}, fmc_pecfg_pe_en: {=bool:?} }}" , self . fmc_pecfg_pe_addr () , self . fmc_pecfg_pe_en ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcPekey (pub u32) ; impl FmcPekey { # [must_use]
# [inline (always)]
pub const fn fmc_pekey_pe_key (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_pekey_pe_key (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcPekey { # [inline (always)]
fn default () -> FmcPekey { FmcPekey (0) } } impl core :: fmt :: Debug for FmcPekey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcPekey") . field ("fmc_pekey_pe_key" , & self . fmc_pekey_pe_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcPekey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcPekey {{ fmc_pekey_pe_key: {=u32:?} }}" , self . fmc_pekey_pe_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcPid (pub u32) ; impl FmcPid { # [must_use]
# [inline (always)]
pub const fn fmc_pid_pid (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_fmc_pid_pid (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for FmcPid { # [inline (always)]
fn default () -> FmcPid { FmcPid (0) } } impl core :: fmt :: Debug for FmcPid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcPid") . field ("fmc_pid_pid" , & self . fmc_pid_pid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcPid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcPid {{ fmc_pid_pid: {=u32:?} }}" , self . fmc_pid_pid ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct FmcStat (pub u32) ; impl FmcStat { # [must_use]
# [inline (always)]
pub const fn fmc_stat_end (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_end (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_operr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_operr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_ldeccdet (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_ldeccdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_wperr (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_wperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_pgaerr (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_pgaerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_pgmerr (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_pgmerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_pgserr (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_pgserr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_rdcerr (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_rdcerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn fmc_stat_busy (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_fmc_stat_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for FmcStat { # [inline (always)]
fn default () -> FmcStat { FmcStat (0) } } impl core :: fmt :: Debug for FmcStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("FmcStat") . field ("fmc_stat_end" , & self . fmc_stat_end ()) . field ("fmc_stat_operr" , & self . fmc_stat_operr ()) . field ("fmc_stat_ldeccdet" , & self . fmc_stat_ldeccdet ()) . field ("fmc_stat_wperr" , & self . fmc_stat_wperr ()) . field ("fmc_stat_pgaerr" , & self . fmc_stat_pgaerr ()) . field ("fmc_stat_pgmerr" , & self . fmc_stat_pgmerr ()) . field ("fmc_stat_pgserr" , & self . fmc_stat_pgserr ()) . field ("fmc_stat_rdcerr" , & self . fmc_stat_rdcerr ()) . field ("fmc_stat_busy" , & self . fmc_stat_busy ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for FmcStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "FmcStat {{ fmc_stat_end: {=bool:?}, fmc_stat_operr: {=bool:?}, fmc_stat_ldeccdet: {=bool:?}, fmc_stat_wperr: {=bool:?}, fmc_stat_pgaerr: {=bool:?}, fmc_stat_pgmerr: {=bool:?}, fmc_stat_pgserr: {=bool:?}, fmc_stat_rdcerr: {=bool:?}, fmc_stat_busy: {=bool:?} }}" , self . fmc_stat_end () , self . fmc_stat_operr () , self . fmc_stat_ldeccdet () , self . fmc_stat_wperr () , self . fmc_stat_pgaerr () , self . fmc_stat_pgmerr () , self . fmc_stat_pgserr () , self . fmc_stat_rdcerr () , self . fmc_stat_busy ()) } } }