#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "General-purpose I/Os"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gpiob { ptr : * mut u8 } unsafe impl Send for Gpiob { } unsafe impl Sync for Gpiob { } impl Gpiob { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "GPIO port control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "GPIO port output mode register"]
# [inline (always)]
pub const fn omode (self) -> crate :: common :: Reg < regs :: Omode , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "GPIO port output speed register"]
# [inline (always)]
pub const fn ospd (self) -> crate :: common :: Reg < regs :: Ospd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "GPIO port pull-up/pull-down register"]
# [inline (always)]
pub const fn pud (self) -> crate :: common :: Reg < regs :: Pud , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "GPIO port input status register"]
# [inline (always)]
pub const fn istat (self) -> crate :: common :: Reg < regs :: Istat , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "GPIO port output control register"]
# [inline (always)]
pub const fn octl (self) -> crate :: common :: Reg < regs :: Octl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "GPIO port bit operate register"]
# [inline (always)]
pub const fn bop (self) -> crate :: common :: Reg < regs :: Bop , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "GPIO port configuration lock register"]
# [inline (always)]
pub const fn lock (self) -> crate :: common :: Reg < regs :: Lock , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "GPIO alternate function selected register 0"]
# [inline (always)]
pub const fn afsel0 (self) -> crate :: common :: Reg < regs :: Afsel0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "GPIO alternate function selected register 1"]
# [inline (always)]
pub const fn afsel1 (self) -> crate :: common :: Reg < regs :: Afsel1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Bit clear register"]
# [inline (always)]
pub const fn bc (self) -> crate :: common :: Reg < regs :: Bc , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Port bit toggle register"]
# [inline (always)]
pub const fn tg (self) -> crate :: common :: Reg < regs :: Tg , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } } pub mod regs { # [doc = "GPIO alternate function selected register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Afsel0 (pub u32) ; impl Afsel0 { # [doc = "Port 0 alternate function selected"]
# [inline (always)]
pub const fn sel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Port 0 alternate function selected"]
# [inline (always)]
pub fn set_sel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Port 1 alternate function selected"]
# [inline (always)]
pub const fn sel1 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Port 1 alternate function selected"]
# [inline (always)]
pub fn set_sel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Port 2 alternate function selected"]
# [inline (always)]
pub const fn sel2 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "Port 2 alternate function selected"]
# [inline (always)]
pub fn set_sel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "Port 3 alternate function selected"]
# [inline (always)]
pub const fn sel3 (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Port 3 alternate function selected"]
# [inline (always)]
pub fn set_sel3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } # [doc = "Port 4 alternate function selected"]
# [inline (always)]
pub const fn sel4 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "Port 4 alternate function selected"]
# [inline (always)]
pub fn set_sel4 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "Port 5 alternate function selected"]
# [inline (always)]
pub const fn sel5 (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [doc = "Port 5 alternate function selected"]
# [inline (always)]
pub fn set_sel5 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } # [doc = "Port 6 alternate function selected"]
# [inline (always)]
pub const fn sel6 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "Port 6 alternate function selected"]
# [inline (always)]
pub fn set_sel6 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [doc = "Port 7 alternate function selected"]
# [inline (always)]
pub const fn sel7 (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x0f ; val as u8 } # [doc = "Port 7 alternate function selected"]
# [inline (always)]
pub fn set_sel7 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize) ; } } impl Default for Afsel0 { # [inline (always)]
fn default () -> Afsel0 { Afsel0 (0) } } impl core :: fmt :: Debug for Afsel0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Afsel0") . field ("sel0" , & self . sel0 ()) . field ("sel1" , & self . sel1 ()) . field ("sel2" , & self . sel2 ()) . field ("sel3" , & self . sel3 ()) . field ("sel4" , & self . sel4 ()) . field ("sel5" , & self . sel5 ()) . field ("sel6" , & self . sel6 ()) . field ("sel7" , & self . sel7 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Afsel0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Afsel0 {{ sel0: {=u8:?}, sel1: {=u8:?}, sel2: {=u8:?}, sel3: {=u8:?}, sel4: {=u8:?}, sel5: {=u8:?}, sel6: {=u8:?}, sel7: {=u8:?} }}" , self . sel0 () , self . sel1 () , self . sel2 () , self . sel3 () , self . sel4 () , self . sel5 () , self . sel6 () , self . sel7 ()) } } # [doc = "GPIO alternate function selected register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Afsel1 (pub u32) ; impl Afsel1 { # [doc = "Port 8 alternate function selected"]
# [inline (always)]
pub const fn sel8 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Port 8 alternate function selected"]
# [inline (always)]
pub fn set_sel8 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Port 9 alternate function selected"]
# [inline (always)]
pub const fn sel9 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Port 9 alternate function selected"]
# [inline (always)]
pub fn set_sel9 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Port 10 alternate function selected"]
# [inline (always)]
pub const fn sel10 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "Port 10 alternate function selected"]
# [inline (always)]
pub fn set_sel10 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "Port 11 alternate function selected"]
# [inline (always)]
pub const fn sel11 (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Port 11 alternate function selected"]
# [inline (always)]
pub fn set_sel11 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } # [doc = "Port 12 alternate function selected"]
# [inline (always)]
pub const fn sel12 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "Port 12 alternate function selected"]
# [inline (always)]
pub fn set_sel12 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "Port 13 alternate function selected"]
# [inline (always)]
pub const fn sel13 (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [doc = "Port 13 alternate function selected"]
# [inline (always)]
pub fn set_sel13 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } # [doc = "Port 14 alternate function selected"]
# [inline (always)]
pub const fn sel14 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "Port 14 alternate function selected"]
# [inline (always)]
pub fn set_sel14 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [doc = "Port 15 alternate function selected"]
# [inline (always)]
pub const fn sel15 (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x0f ; val as u8 } # [doc = "Port 15 alternate function selected"]
# [inline (always)]
pub fn set_sel15 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize) ; } } impl Default for Afsel1 { # [inline (always)]
fn default () -> Afsel1 { Afsel1 (0) } } impl core :: fmt :: Debug for Afsel1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Afsel1") . field ("sel8" , & self . sel8 ()) . field ("sel9" , & self . sel9 ()) . field ("sel10" , & self . sel10 ()) . field ("sel11" , & self . sel11 ()) . field ("sel12" , & self . sel12 ()) . field ("sel13" , & self . sel13 ()) . field ("sel14" , & self . sel14 ()) . field ("sel15" , & self . sel15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Afsel1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Afsel1 {{ sel8: {=u8:?}, sel9: {=u8:?}, sel10: {=u8:?}, sel11: {=u8:?}, sel12: {=u8:?}, sel13: {=u8:?}, sel14: {=u8:?}, sel15: {=u8:?} }}" , self . sel8 () , self . sel9 () , self . sel10 () , self . sel11 () , self . sel12 () , self . sel13 () , self . sel14 () , self . sel15 ()) } } # [doc = "Bit clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Bc (pub u32) ; impl Bc { # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port cleat bit"]
# [inline (always)]
pub const fn cr15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port cleat bit"]
# [inline (always)]
pub fn set_cr15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Bc { # [inline (always)]
fn default () -> Bc { Bc (0) } } impl core :: fmt :: Debug for Bc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Bc") . field ("cr0" , & self . cr0 ()) . field ("cr1" , & self . cr1 ()) . field ("cr2" , & self . cr2 ()) . field ("cr3" , & self . cr3 ()) . field ("cr4" , & self . cr4 ()) . field ("cr5" , & self . cr5 ()) . field ("cr6" , & self . cr6 ()) . field ("cr7" , & self . cr7 ()) . field ("cr8" , & self . cr8 ()) . field ("cr9" , & self . cr9 ()) . field ("cr10" , & self . cr10 ()) . field ("cr11" , & self . cr11 ()) . field ("cr12" , & self . cr12 ()) . field ("cr13" , & self . cr13 ()) . field ("cr14" , & self . cr14 ()) . field ("cr15" , & self . cr15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Bc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Bc {{ cr0: {=bool:?}, cr1: {=bool:?}, cr2: {=bool:?}, cr3: {=bool:?}, cr4: {=bool:?}, cr5: {=bool:?}, cr6: {=bool:?}, cr7: {=bool:?}, cr8: {=bool:?}, cr9: {=bool:?}, cr10: {=bool:?}, cr11: {=bool:?}, cr12: {=bool:?}, cr13: {=bool:?}, cr14: {=bool:?}, cr15: {=bool:?} }}" , self . cr0 () , self . cr1 () , self . cr2 () , self . cr3 () , self . cr4 () , self . cr5 () , self . cr6 () , self . cr7 () , self . cr8 () , self . cr9 () , self . cr10 () , self . cr11 () , self . cr12 () , self . cr13 () , self . cr14 () , self . cr15 ()) } } # [doc = "GPIO port bit operate register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Bop (pub u32) ; impl Bop { # [doc = "Port Set bit 0"]
# [inline (always)]
pub const fn bop0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 0"]
# [inline (always)]
pub fn set_bop0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port Set bit 1"]
# [inline (always)]
pub const fn bop1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 1"]
# [inline (always)]
pub fn set_bop1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port Set bit 2"]
# [inline (always)]
pub const fn bop2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 2"]
# [inline (always)]
pub fn set_bop2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port Set bit 3"]
# [inline (always)]
pub const fn bop3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 3"]
# [inline (always)]
pub fn set_bop3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port Set bit 4"]
# [inline (always)]
pub const fn bop4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 4"]
# [inline (always)]
pub fn set_bop4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port Set bit 5"]
# [inline (always)]
pub const fn bop5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 5"]
# [inline (always)]
pub fn set_bop5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port Set bit 6"]
# [inline (always)]
pub const fn bop6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 6"]
# [inline (always)]
pub fn set_bop6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port Set bit 7"]
# [inline (always)]
pub const fn bop7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 7"]
# [inline (always)]
pub fn set_bop7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port Set bit 8"]
# [inline (always)]
pub const fn bop8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 8"]
# [inline (always)]
pub fn set_bop8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port Set bit 9"]
# [inline (always)]
pub const fn bop9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 9"]
# [inline (always)]
pub fn set_bop9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port Set bit 10"]
# [inline (always)]
pub const fn bop10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 10"]
# [inline (always)]
pub fn set_bop10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port Set bit 11"]
# [inline (always)]
pub const fn bop11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 11"]
# [inline (always)]
pub fn set_bop11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port Set bit 12"]
# [inline (always)]
pub const fn bop12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 12"]
# [inline (always)]
pub fn set_bop12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port Set bit 13"]
# [inline (always)]
pub const fn bop13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 13"]
# [inline (always)]
pub fn set_bop13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port Set bit 14"]
# [inline (always)]
pub const fn bop14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 14"]
# [inline (always)]
pub fn set_bop14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port Set bit 15"]
# [inline (always)]
pub const fn bop15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port Set bit 15"]
# [inline (always)]
pub fn set_bop15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Port Clear bit 0"]
# [inline (always)]
pub const fn cr0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 0"]
# [inline (always)]
pub fn set_cr0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Port Clear bit 1"]
# [inline (always)]
pub const fn cr1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 1"]
# [inline (always)]
pub fn set_cr1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Port Clear bit 2"]
# [inline (always)]
pub const fn cr2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 2"]
# [inline (always)]
pub fn set_cr2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Port Clear bit 3"]
# [inline (always)]
pub const fn cr3 (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 3"]
# [inline (always)]
pub fn set_cr3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Port Clear bit 4"]
# [inline (always)]
pub const fn cr4 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 4"]
# [inline (always)]
pub fn set_cr4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "Port Clear bit 5"]
# [inline (always)]
pub const fn cr5 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 5"]
# [inline (always)]
pub fn set_cr5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Port Clear bit 6"]
# [inline (always)]
pub const fn cr6 (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 6"]
# [inline (always)]
pub fn set_cr6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "Port Clear bit 7"]
# [inline (always)]
pub const fn cr7 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 7"]
# [inline (always)]
pub fn set_cr7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "Port Clear bit 8"]
# [inline (always)]
pub const fn cr8 (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 8"]
# [inline (always)]
pub fn set_cr8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Port Clear bit 9"]
# [inline (always)]
pub const fn cr9 (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 9"]
# [inline (always)]
pub fn set_cr9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Port Clear bit 10"]
# [inline (always)]
pub const fn cr10 (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 10"]
# [inline (always)]
pub fn set_cr10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "Port Clear bit 11"]
# [inline (always)]
pub const fn cr11 (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 11"]
# [inline (always)]
pub fn set_cr11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "Port Clear bit 12"]
# [inline (always)]
pub const fn cr12 (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 12"]
# [inline (always)]
pub fn set_cr12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Port Clear bit 13"]
# [inline (always)]
pub const fn cr13 (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 13"]
# [inline (always)]
pub fn set_cr13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Port Clear bit 14"]
# [inline (always)]
pub const fn cr14 (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 14"]
# [inline (always)]
pub fn set_cr14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Port Clear bit 15"]
# [inline (always)]
pub const fn cr15 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Port Clear bit 15"]
# [inline (always)]
pub fn set_cr15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Bop { # [inline (always)]
fn default () -> Bop { Bop (0) } } impl core :: fmt :: Debug for Bop { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Bop") . field ("bop0" , & self . bop0 ()) . field ("bop1" , & self . bop1 ()) . field ("bop2" , & self . bop2 ()) . field ("bop3" , & self . bop3 ()) . field ("bop4" , & self . bop4 ()) . field ("bop5" , & self . bop5 ()) . field ("bop6" , & self . bop6 ()) . field ("bop7" , & self . bop7 ()) . field ("bop8" , & self . bop8 ()) . field ("bop9" , & self . bop9 ()) . field ("bop10" , & self . bop10 ()) . field ("bop11" , & self . bop11 ()) . field ("bop12" , & self . bop12 ()) . field ("bop13" , & self . bop13 ()) . field ("bop14" , & self . bop14 ()) . field ("bop15" , & self . bop15 ()) . field ("cr0" , & self . cr0 ()) . field ("cr1" , & self . cr1 ()) . field ("cr2" , & self . cr2 ()) . field ("cr3" , & self . cr3 ()) . field ("cr4" , & self . cr4 ()) . field ("cr5" , & self . cr5 ()) . field ("cr6" , & self . cr6 ()) . field ("cr7" , & self . cr7 ()) . field ("cr8" , & self . cr8 ()) . field ("cr9" , & self . cr9 ()) . field ("cr10" , & self . cr10 ()) . field ("cr11" , & self . cr11 ()) . field ("cr12" , & self . cr12 ()) . field ("cr13" , & self . cr13 ()) . field ("cr14" , & self . cr14 ()) . field ("cr15" , & self . cr15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Bop { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Bop {{ bop0: {=bool:?}, bop1: {=bool:?}, bop2: {=bool:?}, bop3: {=bool:?}, bop4: {=bool:?}, bop5: {=bool:?}, bop6: {=bool:?}, bop7: {=bool:?}, bop8: {=bool:?}, bop9: {=bool:?}, bop10: {=bool:?}, bop11: {=bool:?}, bop12: {=bool:?}, bop13: {=bool:?}, bop14: {=bool:?}, bop15: {=bool:?}, cr0: {=bool:?}, cr1: {=bool:?}, cr2: {=bool:?}, cr3: {=bool:?}, cr4: {=bool:?}, cr5: {=bool:?}, cr6: {=bool:?}, cr7: {=bool:?}, cr8: {=bool:?}, cr9: {=bool:?}, cr10: {=bool:?}, cr11: {=bool:?}, cr12: {=bool:?}, cr13: {=bool:?}, cr14: {=bool:?}, cr15: {=bool:?} }}" , self . bop0 () , self . bop1 () , self . bop2 () , self . bop3 () , self . bop4 () , self . bop5 () , self . bop6 () , self . bop7 () , self . bop8 () , self . bop9 () , self . bop10 () , self . bop11 () , self . bop12 () , self . bop13 () , self . bop14 () , self . bop15 () , self . cr0 () , self . cr1 () , self . cr2 () , self . cr3 () , self . cr4 () , self . cr5 () , self . cr6 () , self . cr7 () , self . cr8 () , self . cr9 () , self . cr10 () , self . cr11 () , self . cr12 () , self . cr13 () , self . cr14 () , self . cr15 ()) } } # [doc = "GPIO port control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Port x configuration bits (x = 0)"]
# [inline (always)]
pub const fn ctl0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 0)"]
# [inline (always)]
pub fn set_ctl0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Port x configuration bits (x = 1)"]
# [inline (always)]
pub const fn ctl1 (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 1)"]
# [inline (always)]
pub fn set_ctl1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Port x configuration bits (x = 2)"]
# [inline (always)]
pub const fn ctl2 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 2)"]
# [inline (always)]
pub fn set_ctl2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "Port x configuration bits (x = 3)"]
# [inline (always)]
pub const fn ctl3 (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 3)"]
# [inline (always)]
pub fn set_ctl3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "Port x configuration bits (x = 4 )"]
# [inline (always)]
pub const fn ctl4 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 4 )"]
# [inline (always)]
pub fn set_ctl4 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Port x configuration bits (x = 5)"]
# [inline (always)]
pub const fn ctl5 (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 5)"]
# [inline (always)]
pub fn set_ctl5 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Port x configuration bits (x = 6 )"]
# [inline (always)]
pub const fn ctl6 (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 6 )"]
# [inline (always)]
pub fn set_ctl6 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Port x configuration bits (x = 7)"]
# [inline (always)]
pub const fn ctl7 (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 7)"]
# [inline (always)]
pub fn set_ctl7 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } # [doc = "Port x configuration bits (x = 8)"]
# [inline (always)]
pub const fn ctl8 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 8)"]
# [inline (always)]
pub fn set_ctl8 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 16usize)) | (((val as u32) & 0x03) << 16usize) ; } # [doc = "Port x configuration bits (x = 9)"]
# [inline (always)]
pub const fn ctl9 (& self) -> u8 { let val = (self . 0 >> 18usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 9)"]
# [inline (always)]
pub fn set_ctl9 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 18usize)) | (((val as u32) & 0x03) << 18usize) ; } # [doc = "Port x configuration bits (x = 10)"]
# [inline (always)]
pub const fn ctl10 (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 10)"]
# [inline (always)]
pub fn set_ctl10 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [doc = "Port x configuration bits (x = 11)"]
# [inline (always)]
pub const fn ctl11 (& self) -> u8 { let val = (self . 0 >> 22usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 11)"]
# [inline (always)]
pub fn set_ctl11 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 22usize)) | (((val as u32) & 0x03) << 22usize) ; } # [doc = "Port x configuration bits (x = 12)"]
# [inline (always)]
pub const fn ctl12 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 12)"]
# [inline (always)]
pub fn set_ctl12 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 24usize)) | (((val as u32) & 0x03) << 24usize) ; } # [doc = "Port x configuration bits (x = 13)"]
# [inline (always)]
pub const fn ctl13 (& self) -> u8 { let val = (self . 0 >> 26usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 13)"]
# [inline (always)]
pub fn set_ctl13 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 26usize)) | (((val as u32) & 0x03) << 26usize) ; } # [doc = "Port x configuration bits (x = 14)"]
# [inline (always)]
pub const fn ctl14 (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 14)"]
# [inline (always)]
pub fn set_ctl14 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [doc = "Port x configuration bits (x = 15)"]
# [inline (always)]
pub const fn ctl15 (& self) -> u8 { let val = (self . 0 >> 30usize) & 0x03 ; val as u8 } # [doc = "Port x configuration bits (x = 15)"]
# [inline (always)]
pub fn set_ctl15 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 30usize)) | (((val as u32) & 0x03) << 30usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("ctl0" , & self . ctl0 ()) . field ("ctl1" , & self . ctl1 ()) . field ("ctl2" , & self . ctl2 ()) . field ("ctl3" , & self . ctl3 ()) . field ("ctl4" , & self . ctl4 ()) . field ("ctl5" , & self . ctl5 ()) . field ("ctl6" , & self . ctl6 ()) . field ("ctl7" , & self . ctl7 ()) . field ("ctl8" , & self . ctl8 ()) . field ("ctl9" , & self . ctl9 ()) . field ("ctl10" , & self . ctl10 ()) . field ("ctl11" , & self . ctl11 ()) . field ("ctl12" , & self . ctl12 ()) . field ("ctl13" , & self . ctl13 ()) . field ("ctl14" , & self . ctl14 ()) . field ("ctl15" , & self . ctl15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ ctl0: {=u8:?}, ctl1: {=u8:?}, ctl2: {=u8:?}, ctl3: {=u8:?}, ctl4: {=u8:?}, ctl5: {=u8:?}, ctl6: {=u8:?}, ctl7: {=u8:?}, ctl8: {=u8:?}, ctl9: {=u8:?}, ctl10: {=u8:?}, ctl11: {=u8:?}, ctl12: {=u8:?}, ctl13: {=u8:?}, ctl14: {=u8:?}, ctl15: {=u8:?} }}" , self . ctl0 () , self . ctl1 () , self . ctl2 () , self . ctl3 () , self . ctl4 () , self . ctl5 () , self . ctl6 () , self . ctl7 () , self . ctl8 () , self . ctl9 () , self . ctl10 () , self . ctl11 () , self . ctl12 () , self . ctl13 () , self . ctl14 () , self . ctl15 ()) } } # [doc = "GPIO port input status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Istat (pub u32) ; impl Istat { # [doc = "Port input status (y = 0)"]
# [inline (always)]
pub const fn istat0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 0)"]
# [inline (always)]
pub fn set_istat0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port input status (y = 1)"]
# [inline (always)]
pub const fn istat1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 1)"]
# [inline (always)]
pub fn set_istat1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port input status (y = 2)"]
# [inline (always)]
pub const fn istat2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 2)"]
# [inline (always)]
pub fn set_istat2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port input status (y = 3)"]
# [inline (always)]
pub const fn istat3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 3)"]
# [inline (always)]
pub fn set_istat3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port input status (y = 4)"]
# [inline (always)]
pub const fn istat4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 4)"]
# [inline (always)]
pub fn set_istat4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port input status (y = 5)"]
# [inline (always)]
pub const fn istat5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 5)"]
# [inline (always)]
pub fn set_istat5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port input status (y = 6)"]
# [inline (always)]
pub const fn istat6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 6)"]
# [inline (always)]
pub fn set_istat6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port input status (y = 7)"]
# [inline (always)]
pub const fn istat7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 7)"]
# [inline (always)]
pub fn set_istat7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port input status (y = 8)"]
# [inline (always)]
pub const fn istat8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 8)"]
# [inline (always)]
pub fn set_istat8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port input status (y = 9)"]
# [inline (always)]
pub const fn istat9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 9)"]
# [inline (always)]
pub fn set_istat9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port input status (y = 10)"]
# [inline (always)]
pub const fn istat10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 10)"]
# [inline (always)]
pub fn set_istat10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port input status (y = 11)"]
# [inline (always)]
pub const fn istat11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 11)"]
# [inline (always)]
pub fn set_istat11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port input status (y = 12)"]
# [inline (always)]
pub const fn istat12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 12)"]
# [inline (always)]
pub fn set_istat12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port input status (y = 13)"]
# [inline (always)]
pub const fn istat13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 13)"]
# [inline (always)]
pub fn set_istat13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port input status (y = 14)"]
# [inline (always)]
pub const fn istat14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 14)"]
# [inline (always)]
pub fn set_istat14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port input status (y = 15)"]
# [inline (always)]
pub const fn istat15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port input status (y = 15)"]
# [inline (always)]
pub fn set_istat15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Istat { # [inline (always)]
fn default () -> Istat { Istat (0) } } impl core :: fmt :: Debug for Istat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Istat") . field ("istat0" , & self . istat0 ()) . field ("istat1" , & self . istat1 ()) . field ("istat2" , & self . istat2 ()) . field ("istat3" , & self . istat3 ()) . field ("istat4" , & self . istat4 ()) . field ("istat5" , & self . istat5 ()) . field ("istat6" , & self . istat6 ()) . field ("istat7" , & self . istat7 ()) . field ("istat8" , & self . istat8 ()) . field ("istat9" , & self . istat9 ()) . field ("istat10" , & self . istat10 ()) . field ("istat11" , & self . istat11 ()) . field ("istat12" , & self . istat12 ()) . field ("istat13" , & self . istat13 ()) . field ("istat14" , & self . istat14 ()) . field ("istat15" , & self . istat15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Istat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Istat {{ istat0: {=bool:?}, istat1: {=bool:?}, istat2: {=bool:?}, istat3: {=bool:?}, istat4: {=bool:?}, istat5: {=bool:?}, istat6: {=bool:?}, istat7: {=bool:?}, istat8: {=bool:?}, istat9: {=bool:?}, istat10: {=bool:?}, istat11: {=bool:?}, istat12: {=bool:?}, istat13: {=bool:?}, istat14: {=bool:?}, istat15: {=bool:?} }}" , self . istat0 () , self . istat1 () , self . istat2 () , self . istat3 () , self . istat4 () , self . istat5 () , self . istat6 () , self . istat7 () , self . istat8 () , self . istat9 () , self . istat10 () , self . istat11 () , self . istat12 () , self . istat13 () , self . istat14 () , self . istat15 ()) } } # [doc = "GPIO port configuration lock register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Lock (pub u32) ; impl Lock { # [doc = "Port Lock bit 0"]
# [inline (always)]
pub const fn lk0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 0"]
# [inline (always)]
pub fn set_lk0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port Lock bit 1"]
# [inline (always)]
pub const fn lk1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 1"]
# [inline (always)]
pub fn set_lk1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port Lock bit 2"]
# [inline (always)]
pub const fn lk2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 2"]
# [inline (always)]
pub fn set_lk2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port Lock bit 3"]
# [inline (always)]
pub const fn lk3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 3"]
# [inline (always)]
pub fn set_lk3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port Lock bit 4"]
# [inline (always)]
pub const fn lk4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 4"]
# [inline (always)]
pub fn set_lk4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port Lock bit 5"]
# [inline (always)]
pub const fn lk5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 5"]
# [inline (always)]
pub fn set_lk5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port Lock bit 6"]
# [inline (always)]
pub const fn lk6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 6"]
# [inline (always)]
pub fn set_lk6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port Lock bit 7"]
# [inline (always)]
pub const fn lk7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 7"]
# [inline (always)]
pub fn set_lk7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port Lock bit 8"]
# [inline (always)]
pub const fn lk8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 8"]
# [inline (always)]
pub fn set_lk8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port Lock bit 9"]
# [inline (always)]
pub const fn lk9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 9"]
# [inline (always)]
pub fn set_lk9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port Lock bit 10"]
# [inline (always)]
pub const fn lk10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 10"]
# [inline (always)]
pub fn set_lk10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port Lock bit 11"]
# [inline (always)]
pub const fn lk11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 11"]
# [inline (always)]
pub fn set_lk11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port Lock bit 12"]
# [inline (always)]
pub const fn lk12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 12"]
# [inline (always)]
pub fn set_lk12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port Lock bit 13"]
# [inline (always)]
pub const fn lk13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 13"]
# [inline (always)]
pub fn set_lk13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port Lock bit 14"]
# [inline (always)]
pub const fn lk14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 14"]
# [inline (always)]
pub fn set_lk14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port Lock bit 15"]
# [inline (always)]
pub const fn lk15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port Lock bit 15"]
# [inline (always)]
pub fn set_lk15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Lock sequence key"]
# [inline (always)]
pub const fn lkk (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Lock sequence key"]
# [inline (always)]
pub fn set_lkk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for Lock { # [inline (always)]
fn default () -> Lock { Lock (0) } } impl core :: fmt :: Debug for Lock { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Lock") . field ("lk0" , & self . lk0 ()) . field ("lk1" , & self . lk1 ()) . field ("lk2" , & self . lk2 ()) . field ("lk3" , & self . lk3 ()) . field ("lk4" , & self . lk4 ()) . field ("lk5" , & self . lk5 ()) . field ("lk6" , & self . lk6 ()) . field ("lk7" , & self . lk7 ()) . field ("lk8" , & self . lk8 ()) . field ("lk9" , & self . lk9 ()) . field ("lk10" , & self . lk10 ()) . field ("lk11" , & self . lk11 ()) . field ("lk12" , & self . lk12 ()) . field ("lk13" , & self . lk13 ()) . field ("lk14" , & self . lk14 ()) . field ("lk15" , & self . lk15 ()) . field ("lkk" , & self . lkk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Lock { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Lock {{ lk0: {=bool:?}, lk1: {=bool:?}, lk2: {=bool:?}, lk3: {=bool:?}, lk4: {=bool:?}, lk5: {=bool:?}, lk6: {=bool:?}, lk7: {=bool:?}, lk8: {=bool:?}, lk9: {=bool:?}, lk10: {=bool:?}, lk11: {=bool:?}, lk12: {=bool:?}, lk13: {=bool:?}, lk14: {=bool:?}, lk15: {=bool:?}, lkk: {=bool:?} }}" , self . lk0 () , self . lk1 () , self . lk2 () , self . lk3 () , self . lk4 () , self . lk5 () , self . lk6 () , self . lk7 () , self . lk8 () , self . lk9 () , self . lk10 () , self . lk11 () , self . lk12 () , self . lk13 () , self . lk14 () , self . lk15 () , self . lkk ()) } } # [doc = "GPIO port output control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Octl (pub u32) ; impl Octl { # [doc = "Port output control (y = 0)"]
# [inline (always)]
pub const fn octl0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 0)"]
# [inline (always)]
pub fn set_octl0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port output control (y = 1)"]
# [inline (always)]
pub const fn octl1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 1)"]
# [inline (always)]
pub fn set_octl1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port output control (y = 2)"]
# [inline (always)]
pub const fn octl2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 2)"]
# [inline (always)]
pub fn set_octl2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port output control (y = 3)"]
# [inline (always)]
pub const fn octl3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 3)"]
# [inline (always)]
pub fn set_octl3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port output control (y = 4)"]
# [inline (always)]
pub const fn octl4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 4)"]
# [inline (always)]
pub fn set_octl4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port output control (y = 5)"]
# [inline (always)]
pub const fn octl5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 5)"]
# [inline (always)]
pub fn set_octl5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port output control (y = 6)"]
# [inline (always)]
pub const fn octl6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 6)"]
# [inline (always)]
pub fn set_octl6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port output control (y = 7)"]
# [inline (always)]
pub const fn octl7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 7)"]
# [inline (always)]
pub fn set_octl7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port output control (y = 8)"]
# [inline (always)]
pub const fn octl8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 8)"]
# [inline (always)]
pub fn set_octl8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port output control (y = 9)"]
# [inline (always)]
pub const fn octl9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 9)"]
# [inline (always)]
pub fn set_octl9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port output control (y = 10)"]
# [inline (always)]
pub const fn octl10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 10)"]
# [inline (always)]
pub fn set_octl10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port output control (y = 11)"]
# [inline (always)]
pub const fn octl11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 11)"]
# [inline (always)]
pub fn set_octl11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port output control (y = 12)"]
# [inline (always)]
pub const fn octl12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 12)"]
# [inline (always)]
pub fn set_octl12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port output control (y = 13)"]
# [inline (always)]
pub const fn octl13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 13)"]
# [inline (always)]
pub fn set_octl13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port output control (y = 14)"]
# [inline (always)]
pub const fn octl14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 14)"]
# [inline (always)]
pub fn set_octl14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port output control (y = 15)"]
# [inline (always)]
pub const fn octl15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port output control (y = 15)"]
# [inline (always)]
pub fn set_octl15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Octl { # [inline (always)]
fn default () -> Octl { Octl (0) } } impl core :: fmt :: Debug for Octl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Octl") . field ("octl0" , & self . octl0 ()) . field ("octl1" , & self . octl1 ()) . field ("octl2" , & self . octl2 ()) . field ("octl3" , & self . octl3 ()) . field ("octl4" , & self . octl4 ()) . field ("octl5" , & self . octl5 ()) . field ("octl6" , & self . octl6 ()) . field ("octl7" , & self . octl7 ()) . field ("octl8" , & self . octl8 ()) . field ("octl9" , & self . octl9 ()) . field ("octl10" , & self . octl10 ()) . field ("octl11" , & self . octl11 ()) . field ("octl12" , & self . octl12 ()) . field ("octl13" , & self . octl13 ()) . field ("octl14" , & self . octl14 ()) . field ("octl15" , & self . octl15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Octl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Octl {{ octl0: {=bool:?}, octl1: {=bool:?}, octl2: {=bool:?}, octl3: {=bool:?}, octl4: {=bool:?}, octl5: {=bool:?}, octl6: {=bool:?}, octl7: {=bool:?}, octl8: {=bool:?}, octl9: {=bool:?}, octl10: {=bool:?}, octl11: {=bool:?}, octl12: {=bool:?}, octl13: {=bool:?}, octl14: {=bool:?}, octl15: {=bool:?} }}" , self . octl0 () , self . octl1 () , self . octl2 () , self . octl3 () , self . octl4 () , self . octl5 () , self . octl6 () , self . octl7 () , self . octl8 () , self . octl9 () , self . octl10 () , self . octl11 () , self . octl12 () , self . octl13 () , self . octl14 () , self . octl15 ()) } } # [doc = "GPIO port output mode register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Omode (pub u32) ; impl Omode { # [doc = "Port 0 output mode bit"]
# [inline (always)]
pub const fn om0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port 0 output mode bit"]
# [inline (always)]
pub fn set_om0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port 1 output mode bit"]
# [inline (always)]
pub const fn om1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port 1 output mode bit"]
# [inline (always)]
pub fn set_om1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port 2 output mode bit"]
# [inline (always)]
pub const fn om2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port 2 output mode bit"]
# [inline (always)]
pub fn set_om2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port 3 output mode bit"]
# [inline (always)]
pub const fn om3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port 3 output mode bit"]
# [inline (always)]
pub fn set_om3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port 4 output mode bit"]
# [inline (always)]
pub const fn om4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port 4 output mode bit"]
# [inline (always)]
pub fn set_om4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port 5 output mode bit"]
# [inline (always)]
pub const fn om5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port 5 output mode bit"]
# [inline (always)]
pub fn set_om5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port 6 output mode bit"]
# [inline (always)]
pub const fn om6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port 6 output mode bit"]
# [inline (always)]
pub fn set_om6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port 7 output mode bit"]
# [inline (always)]
pub const fn om7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port 7 output mode bit"]
# [inline (always)]
pub fn set_om7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port 8 output mode bit"]
# [inline (always)]
pub const fn om8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port 8 output mode bit"]
# [inline (always)]
pub fn set_om8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port 9 output mode bit"]
# [inline (always)]
pub const fn om9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port 9 output mode bit"]
# [inline (always)]
pub fn set_om9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port 10 output mode bit"]
# [inline (always)]
pub const fn om10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port 10 output mode bit"]
# [inline (always)]
pub fn set_om10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port 11 output mode bit"]
# [inline (always)]
pub const fn om11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port 11 output mode bit"]
# [inline (always)]
pub fn set_om11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port 12 output mode bit"]
# [inline (always)]
pub const fn om12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port 12 output mode bit"]
# [inline (always)]
pub fn set_om12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port 13 output mode bit"]
# [inline (always)]
pub const fn om13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port 13 output mode bit"]
# [inline (always)]
pub fn set_om13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port 14 output mode bit"]
# [inline (always)]
pub const fn om14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port 14 output mode bit"]
# [inline (always)]
pub fn set_om14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port 15 output mode bit"]
# [inline (always)]
pub const fn om15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port 15 output mode bit"]
# [inline (always)]
pub fn set_om15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Omode { # [inline (always)]
fn default () -> Omode { Omode (0) } } impl core :: fmt :: Debug for Omode { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Omode") . field ("om0" , & self . om0 ()) . field ("om1" , & self . om1 ()) . field ("om2" , & self . om2 ()) . field ("om3" , & self . om3 ()) . field ("om4" , & self . om4 ()) . field ("om5" , & self . om5 ()) . field ("om6" , & self . om6 ()) . field ("om7" , & self . om7 ()) . field ("om8" , & self . om8 ()) . field ("om9" , & self . om9 ()) . field ("om10" , & self . om10 ()) . field ("om11" , & self . om11 ()) . field ("om12" , & self . om12 ()) . field ("om13" , & self . om13 ()) . field ("om14" , & self . om14 ()) . field ("om15" , & self . om15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Omode { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Omode {{ om0: {=bool:?}, om1: {=bool:?}, om2: {=bool:?}, om3: {=bool:?}, om4: {=bool:?}, om5: {=bool:?}, om6: {=bool:?}, om7: {=bool:?}, om8: {=bool:?}, om9: {=bool:?}, om10: {=bool:?}, om11: {=bool:?}, om12: {=bool:?}, om13: {=bool:?}, om14: {=bool:?}, om15: {=bool:?} }}" , self . om0 () , self . om1 () , self . om2 () , self . om3 () , self . om4 () , self . om5 () , self . om6 () , self . om7 () , self . om8 () , self . om9 () , self . om10 () , self . om11 () , self . om12 () , self . om13 () , self . om14 () , self . om15 ()) } } # [doc = "GPIO port output speed register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ospd (pub u32) ; impl Ospd { # [doc = "Port 0 output max speed bits"]
# [inline (always)]
pub const fn ospd0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Port 0 output max speed bits"]
# [inline (always)]
pub fn set_ospd0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Port 1 output max speed bits"]
# [inline (always)]
pub const fn ospd1 (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Port 1 output max speed bits"]
# [inline (always)]
pub fn set_ospd1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Port 2 output max speed bits"]
# [inline (always)]
pub const fn ospd2 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Port 2 output max speed bits"]
# [inline (always)]
pub fn set_ospd2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "Port 3 output max speed bits"]
# [inline (always)]
pub const fn ospd3 (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Port 3 output max speed bits"]
# [inline (always)]
pub fn set_ospd3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "Port 4 output max speed bits"]
# [inline (always)]
pub const fn ospd4 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Port 4 output max speed bits"]
# [inline (always)]
pub fn set_ospd4 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Port 5 output max speed bits"]
# [inline (always)]
pub const fn ospd5 (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Port 5 output max speed bits"]
# [inline (always)]
pub fn set_ospd5 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Port 6 output max speed bits"]
# [inline (always)]
pub const fn ospd6 (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "Port 6 output max speed bits"]
# [inline (always)]
pub fn set_ospd6 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Port 7 output max speed bits"]
# [inline (always)]
pub const fn ospd7 (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Port 7 output max speed bits"]
# [inline (always)]
pub fn set_ospd7 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } # [doc = "Port 8 output max speed bits"]
# [inline (always)]
pub const fn ospd8 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x03 ; val as u8 } # [doc = "Port 8 output max speed bits"]
# [inline (always)]
pub fn set_ospd8 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 16usize)) | (((val as u32) & 0x03) << 16usize) ; } # [doc = "Port 9 output max speed bits"]
# [inline (always)]
pub const fn ospd9 (& self) -> u8 { let val = (self . 0 >> 18usize) & 0x03 ; val as u8 } # [doc = "Port 9 output max speed bits"]
# [inline (always)]
pub fn set_ospd9 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 18usize)) | (((val as u32) & 0x03) << 18usize) ; } # [doc = "Port 10 output max speed bits"]
# [inline (always)]
pub const fn ospd10 (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [doc = "Port 10 output max speed bits"]
# [inline (always)]
pub fn set_ospd10 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [doc = "Port 11 output max speed bits"]
# [inline (always)]
pub const fn ospd11 (& self) -> u8 { let val = (self . 0 >> 22usize) & 0x03 ; val as u8 } # [doc = "Port 11 output max speed bits"]
# [inline (always)]
pub fn set_ospd11 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 22usize)) | (((val as u32) & 0x03) << 22usize) ; } # [doc = "Port 12 output max speed bits"]
# [inline (always)]
pub const fn ospd12 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x03 ; val as u8 } # [doc = "Port 12 output max speed bits"]
# [inline (always)]
pub fn set_ospd12 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 24usize)) | (((val as u32) & 0x03) << 24usize) ; } # [doc = "Port 13 output max speed bits"]
# [inline (always)]
pub const fn ospd13 (& self) -> u8 { let val = (self . 0 >> 26usize) & 0x03 ; val as u8 } # [doc = "Port 13 output max speed bits"]
# [inline (always)]
pub fn set_ospd13 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 26usize)) | (((val as u32) & 0x03) << 26usize) ; } # [doc = "Port 14 output max speed bits"]
# [inline (always)]
pub const fn ospd14 (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [doc = "Port 14 output max speed bits"]
# [inline (always)]
pub fn set_ospd14 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [doc = "Port 15 output max speed bits"]
# [inline (always)]
pub const fn ospd15 (& self) -> u8 { let val = (self . 0 >> 30usize) & 0x03 ; val as u8 } # [doc = "Port 15 output max speed bits"]
# [inline (always)]
pub fn set_ospd15 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 30usize)) | (((val as u32) & 0x03) << 30usize) ; } } impl Default for Ospd { # [inline (always)]
fn default () -> Ospd { Ospd (0) } } impl core :: fmt :: Debug for Ospd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ospd") . field ("ospd0" , & self . ospd0 ()) . field ("ospd1" , & self . ospd1 ()) . field ("ospd2" , & self . ospd2 ()) . field ("ospd3" , & self . ospd3 ()) . field ("ospd4" , & self . ospd4 ()) . field ("ospd5" , & self . ospd5 ()) . field ("ospd6" , & self . ospd6 ()) . field ("ospd7" , & self . ospd7 ()) . field ("ospd8" , & self . ospd8 ()) . field ("ospd9" , & self . ospd9 ()) . field ("ospd10" , & self . ospd10 ()) . field ("ospd11" , & self . ospd11 ()) . field ("ospd12" , & self . ospd12 ()) . field ("ospd13" , & self . ospd13 ()) . field ("ospd14" , & self . ospd14 ()) . field ("ospd15" , & self . ospd15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ospd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ospd {{ ospd0: {=u8:?}, ospd1: {=u8:?}, ospd2: {=u8:?}, ospd3: {=u8:?}, ospd4: {=u8:?}, ospd5: {=u8:?}, ospd6: {=u8:?}, ospd7: {=u8:?}, ospd8: {=u8:?}, ospd9: {=u8:?}, ospd10: {=u8:?}, ospd11: {=u8:?}, ospd12: {=u8:?}, ospd13: {=u8:?}, ospd14: {=u8:?}, ospd15: {=u8:?} }}" , self . ospd0 () , self . ospd1 () , self . ospd2 () , self . ospd3 () , self . ospd4 () , self . ospd5 () , self . ospd6 () , self . ospd7 () , self . ospd8 () , self . ospd9 () , self . ospd10 () , self . ospd11 () , self . ospd12 () , self . ospd13 () , self . ospd14 () , self . ospd15 ()) } } # [doc = "GPIO port pull-up/pull-down register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pud (pub u32) ; impl Pud { # [doc = "Port 0 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Port 0 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Port 1 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud1 (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Port 1 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Port 2 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud2 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Port 2 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "Port 3 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud3 (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Port 3 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "Port 4 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud4 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Port 4 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud4 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Port 5 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud5 (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Port 5 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud5 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Port 6 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud6 (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "Port 6 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud6 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Port 7 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud7 (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Port 7 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud7 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } # [doc = "Port 8 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud8 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x03 ; val as u8 } # [doc = "Port 8 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud8 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 16usize)) | (((val as u32) & 0x03) << 16usize) ; } # [doc = "Port 9 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud9 (& self) -> u8 { let val = (self . 0 >> 18usize) & 0x03 ; val as u8 } # [doc = "Port 9 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud9 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 18usize)) | (((val as u32) & 0x03) << 18usize) ; } # [doc = "Port 10 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud10 (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [doc = "Port 10 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud10 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [doc = "Port 11 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud11 (& self) -> u8 { let val = (self . 0 >> 22usize) & 0x03 ; val as u8 } # [doc = "Port 11 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud11 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 22usize)) | (((val as u32) & 0x03) << 22usize) ; } # [doc = "Port 12 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud12 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x03 ; val as u8 } # [doc = "Port 12 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud12 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 24usize)) | (((val as u32) & 0x03) << 24usize) ; } # [doc = "Port 13 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud13 (& self) -> u8 { let val = (self . 0 >> 26usize) & 0x03 ; val as u8 } # [doc = "Port 13 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud13 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 26usize)) | (((val as u32) & 0x03) << 26usize) ; } # [doc = "Port 14 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud14 (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [doc = "Port 14 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud14 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [doc = "Port 15 pull-up or pull-down bits"]
# [inline (always)]
pub const fn pud15 (& self) -> u8 { let val = (self . 0 >> 30usize) & 0x03 ; val as u8 } # [doc = "Port 15 pull-up or pull-down bits"]
# [inline (always)]
pub fn set_pud15 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 30usize)) | (((val as u32) & 0x03) << 30usize) ; } } impl Default for Pud { # [inline (always)]
fn default () -> Pud { Pud (0) } } impl core :: fmt :: Debug for Pud { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pud") . field ("pud0" , & self . pud0 ()) . field ("pud1" , & self . pud1 ()) . field ("pud2" , & self . pud2 ()) . field ("pud3" , & self . pud3 ()) . field ("pud4" , & self . pud4 ()) . field ("pud5" , & self . pud5 ()) . field ("pud6" , & self . pud6 ()) . field ("pud7" , & self . pud7 ()) . field ("pud8" , & self . pud8 ()) . field ("pud9" , & self . pud9 ()) . field ("pud10" , & self . pud10 ()) . field ("pud11" , & self . pud11 ()) . field ("pud12" , & self . pud12 ()) . field ("pud13" , & self . pud13 ()) . field ("pud14" , & self . pud14 ()) . field ("pud15" , & self . pud15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pud { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pud {{ pud0: {=u8:?}, pud1: {=u8:?}, pud2: {=u8:?}, pud3: {=u8:?}, pud4: {=u8:?}, pud5: {=u8:?}, pud6: {=u8:?}, pud7: {=u8:?}, pud8: {=u8:?}, pud9: {=u8:?}, pud10: {=u8:?}, pud11: {=u8:?}, pud12: {=u8:?}, pud13: {=u8:?}, pud14: {=u8:?}, pud15: {=u8:?} }}" , self . pud0 () , self . pud1 () , self . pud2 () , self . pud3 () , self . pud4 () , self . pud5 () , self . pud6 () , self . pud7 () , self . pud8 () , self . pud9 () , self . pud10 () , self . pud11 () , self . pud12 () , self . pud13 () , self . pud14 () , self . pud15 ()) } } # [doc = "Port bit toggle register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tg (pub u32) ; impl Tg { # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg6 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg6 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg7 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg7 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg8 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg9 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg9 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg10 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg10 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg11 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg11 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg12 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg12 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg13 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg13 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg14 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg14 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Port toggle bit"]
# [inline (always)]
pub const fn tg15 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Port toggle bit"]
# [inline (always)]
pub fn set_tg15 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Tg { # [inline (always)]
fn default () -> Tg { Tg (0) } } impl core :: fmt :: Debug for Tg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Tg") . field ("tg0" , & self . tg0 ()) . field ("tg1" , & self . tg1 ()) . field ("tg2" , & self . tg2 ()) . field ("tg3" , & self . tg3 ()) . field ("tg4" , & self . tg4 ()) . field ("tg5" , & self . tg5 ()) . field ("tg6" , & self . tg6 ()) . field ("tg7" , & self . tg7 ()) . field ("tg8" , & self . tg8 ()) . field ("tg9" , & self . tg9 ()) . field ("tg10" , & self . tg10 ()) . field ("tg11" , & self . tg11 ()) . field ("tg12" , & self . tg12 ()) . field ("tg13" , & self . tg13 ()) . field ("tg14" , & self . tg14 ()) . field ("tg15" , & self . tg15 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Tg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Tg {{ tg0: {=bool:?}, tg1: {=bool:?}, tg2: {=bool:?}, tg3: {=bool:?}, tg4: {=bool:?}, tg5: {=bool:?}, tg6: {=bool:?}, tg7: {=bool:?}, tg8: {=bool:?}, tg9: {=bool:?}, tg10: {=bool:?}, tg11: {=bool:?}, tg12: {=bool:?}, tg13: {=bool:?}, tg14: {=bool:?}, tg15: {=bool:?} }}" , self . tg0 () , self . tg1 () , self . tg2 () , self . tg3 () , self . tg4 () , self . tg5 () , self . tg6 () , self . tg7 () , self . tg8 () , self . tg9 () , self . tg10 () , self . tg11 () , self . tg12 () , self . tg13 () , self . tg14 () , self . tg15 ()) } } }