#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "HAU acceleration unit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hau { ptr : * mut u8 } unsafe impl Send for Hau { } unsafe impl Sync for Hau { } impl Hau { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "HAU control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "HAU data input register"]
# [inline (always)]
pub const fn di (self) -> crate :: common :: Reg < regs :: Di , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "HAU configuration register"]
# [inline (always)]
pub const fn cfg (self) -> crate :: common :: Reg < regs :: Cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do0 (self) -> crate :: common :: Reg < regs :: Do0 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do1 (self) -> crate :: common :: Reg < regs :: Do1 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do2 (self) -> crate :: common :: Reg < regs :: Do2 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do3 (self) -> crate :: common :: Reg < regs :: Do3 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do4 (self) -> crate :: common :: Reg < regs :: Do4 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "HAU interrupt enable register"]
# [inline (always)]
pub const fn inten (self) -> crate :: common :: Reg < regs :: Inten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "HAU status and interrupt flag register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do5 (self) -> crate :: common :: Reg < regs :: Do5 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0324usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do6 (self) -> crate :: common :: Reg < regs :: Do6 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0328usize) as _) } } # [doc = "HAU data output register"]
# [inline (always)]
pub const fn do7 (self) -> crate :: common :: Reg < regs :: Do7 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x032cusize) as _) } } } pub mod regs { # [doc = "HAU configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg (pub u32) ; impl Cfg { # [doc = "Valid bits length in the last word"]
# [inline (always)]
pub const fn vbl (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [doc = "Valid bits length in the last word"]
# [inline (always)]
pub fn set_vbl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [doc = "Digest calculation enable"]
# [inline (always)]
pub const fn calen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Digest calculation enable"]
# [inline (always)]
pub fn set_calen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for Cfg { # [inline (always)]
fn default () -> Cfg { Cfg (0) } } impl core :: fmt :: Debug for Cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg") . field ("vbl" , & self . vbl ()) . field ("calen" , & self . calen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg {{ vbl: {=u8:?}, calen: {=bool:?} }}" , self . vbl () , self . calen ()) } } # [doc = "HAU control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Start message digest calculation"]
# [inline (always)]
pub const fn start (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Start message digest calculation"]
# [inline (always)]
pub fn set_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "DMA enable"]
# [inline (always)]
pub const fn dmae (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "DMA enable"]
# [inline (always)]
pub fn set_dmae (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Data type mode"]
# [inline (always)]
pub const fn datam (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Data type mode"]
# [inline (always)]
pub fn set_datam (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "HAU mode selection"]
# [inline (always)]
pub const fn hms (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "HAU mode selection"]
# [inline (always)]
pub fn set_hms (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Algorithm selection bit 0"]
# [inline (always)]
pub const fn algm0 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Algorithm selection bit 0"]
# [inline (always)]
pub fn set_algm0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Number of words in IN FIFO"]
# [inline (always)]
pub const fn nwif (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "Number of words in IN FIFO"]
# [inline (always)]
pub fn set_nwif (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "DI register is not empty"]
# [inline (always)]
pub const fn dine (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "DI register is not empty"]
# [inline (always)]
pub fn set_dine (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Multiple DMA selection"]
# [inline (always)]
pub const fn mds (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Multiple DMA selection"]
# [inline (always)]
pub fn set_mds (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Key length mode"]
# [inline (always)]
pub const fn klm (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Key length mode"]
# [inline (always)]
pub fn set_klm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Algorithm selection bit 1"]
# [inline (always)]
pub const fn algm1 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Algorithm selection bit 1"]
# [inline (always)]
pub fn set_algm1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("start" , & self . start ()) . field ("dmae" , & self . dmae ()) . field ("datam" , & self . datam ()) . field ("hms" , & self . hms ()) . field ("algm0" , & self . algm0 ()) . field ("nwif" , & self . nwif ()) . field ("dine" , & self . dine ()) . field ("mds" , & self . mds ()) . field ("klm" , & self . klm ()) . field ("algm1" , & self . algm1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ start: {=bool:?}, dmae: {=bool:?}, datam: {=u8:?}, hms: {=bool:?}, algm0: {=bool:?}, nwif: {=u8:?}, dine: {=bool:?}, mds: {=bool:?}, klm: {=bool:?}, algm1: {=bool:?} }}" , self . start () , self . dmae () , self . datam () , self . hms () , self . algm0 () , self . nwif () , self . dine () , self . mds () , self . klm () , self . algm1 ()) } } # [doc = "HAU data input register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Di (pub u32) ; impl Di { # [doc = "Message data input"]
# [inline (always)]
pub const fn di (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Message data input"]
# [inline (always)]
pub fn set_di (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Di { # [inline (always)]
fn default () -> Di { Di (0) } } impl core :: fmt :: Debug for Di { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Di") . field ("di" , & self . di ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Di { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Di {{ di: {=u32:?} }}" , self . di ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do0 (pub u32) ; impl Do0 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do0 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do0 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do0 { # [inline (always)]
fn default () -> Do0 { Do0 (0) } } impl core :: fmt :: Debug for Do0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do0") . field ("do0" , & self . do0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do0 {{ do0: {=u32:?} }}" , self . do0 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do1 (pub u32) ; impl Do1 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do1 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do1 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do1 { # [inline (always)]
fn default () -> Do1 { Do1 (0) } } impl core :: fmt :: Debug for Do1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do1") . field ("do1" , & self . do1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do1 {{ do1: {=u32:?} }}" , self . do1 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do2 (pub u32) ; impl Do2 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do2 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do2 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do2 { # [inline (always)]
fn default () -> Do2 { Do2 (0) } } impl core :: fmt :: Debug for Do2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do2") . field ("do2" , & self . do2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do2 {{ do2: {=u32:?} }}" , self . do2 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do3 (pub u32) ; impl Do3 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do3 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do3 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do3 { # [inline (always)]
fn default () -> Do3 { Do3 (0) } } impl core :: fmt :: Debug for Do3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do3") . field ("do3" , & self . do3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do3 {{ do3: {=u32:?} }}" , self . do3 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do4 (pub u32) ; impl Do4 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do4 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do4 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do4 { # [inline (always)]
fn default () -> Do4 { Do4 (0) } } impl core :: fmt :: Debug for Do4 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do4") . field ("do4" , & self . do4 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do4 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do4 {{ do4: {=u32:?} }}" , self . do4 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do5 (pub u32) ; impl Do5 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do5 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do5 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do5 { # [inline (always)]
fn default () -> Do5 { Do5 (0) } } impl core :: fmt :: Debug for Do5 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do5") . field ("do5" , & self . do5 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do5 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do5 {{ do5: {=u32:?} }}" , self . do5 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do6 (pub u32) ; impl Do6 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do6 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do6 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do6 { # [inline (always)]
fn default () -> Do6 { Do6 (0) } } impl core :: fmt :: Debug for Do6 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do6") . field ("do6" , & self . do6 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do6 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do6 {{ do6: {=u32:?} }}" , self . do6 ()) } } # [doc = "HAU data output register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Do7 (pub u32) ; impl Do7 { # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub const fn do7 (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "message digest result of hash algorithm"]
# [inline (always)]
pub fn set_do7 (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Do7 { # [inline (always)]
fn default () -> Do7 { Do7 (0) } } impl core :: fmt :: Debug for Do7 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Do7") . field ("do7" , & self . do7 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Do7 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Do7 {{ do7: {=u32:?} }}" , self . do7 ()) } } # [doc = "HAU interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Inten (pub u32) ; impl Inten { # [doc = "Data input interrupt enable"]
# [inline (always)]
pub const fn diie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Data input interrupt enable"]
# [inline (always)]
pub fn set_diie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "calculation completion interrupt enable"]
# [inline (always)]
pub const fn ccie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "calculation completion interrupt enable"]
# [inline (always)]
pub fn set_ccie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Inten { # [inline (always)]
fn default () -> Inten { Inten (0) } } impl core :: fmt :: Debug for Inten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Inten") . field ("diie" , & self . diie ()) . field ("ccie" , & self . ccie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Inten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Inten {{ diie: {=bool:?}, ccie: {=bool:?} }}" , self . diie () , self . ccie ()) } } # [doc = "HAU status and interrupt flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "Data input interrupt status flag"]
# [inline (always)]
pub const fn dint (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Data input interrupt status flag"]
# [inline (always)]
pub fn set_dint (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Digest calculation completion interrupt flag"]
# [inline (always)]
pub const fn cint (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Digest calculation completion interrupt flag"]
# [inline (always)]
pub fn set_cint (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "DMA status flag"]
# [inline (always)]
pub const fn dmas (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "DMA status flag"]
# [inline (always)]
pub fn set_dmas (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Busy flag bit"]
# [inline (always)]
pub const fn busy (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Busy flag bit"]
# [inline (always)]
pub fn set_busy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } impl core :: fmt :: Debug for Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat") . field ("dint" , & self . dint ()) . field ("cint" , & self . cint ()) . field ("dmas" , & self . dmas ()) . field ("busy" , & self . busy ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat {{ dint: {=bool:?}, cint: {=bool:?}, dmas: {=bool:?}, busy: {=bool:?} }}" , self . dint () , self . cint () , self . dmas () , self . busy ()) } } }