#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Inter integrated circuit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct I2c0 { ptr : * mut u8 } unsafe impl Send for I2c0 { } unsafe impl Sync for I2c0 { } impl I2c0 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Slave address register 0"]
# [inline (always)]
pub const fn saddr0 (self) -> crate :: common :: Reg < regs :: Saddr0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Slave address register 1"]
# [inline (always)]
pub const fn saddr1 (self) -> crate :: common :: Reg < regs :: Saddr1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Transfer buffer register"]
# [inline (always)]
pub const fn data (self) -> crate :: common :: Reg < regs :: Data , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Transfer status register 0"]
# [inline (always)]
pub const fn stat0 (self) -> crate :: common :: Reg < regs :: Stat0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Transfer status register 1"]
# [inline (always)]
pub const fn stat1 (self) -> crate :: common :: Reg < regs :: Stat1 , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Clock configure register"]
# [inline (always)]
pub const fn ckcfg (self) -> crate :: common :: Reg < regs :: Ckcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Rise time register"]
# [inline (always)]
pub const fn rt (self) -> crate :: common :: Reg < regs :: Rt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "SAM control and status register"]
# [inline (always)]
pub const fn samcs (self) -> crate :: common :: Reg < regs :: Samcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x80usize) as _) } } # [doc = "Control register 2"]
# [inline (always)]
pub const fn ctl2 (self) -> crate :: common :: Reg < regs :: Ctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x90usize) as _) } } # [doc = "Control and status register"]
# [inline (always)]
pub const fn cs (self) -> crate :: common :: Reg < regs :: Cs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x94usize) as _) } } # [doc = "Status clear register"]
# [inline (always)]
pub const fn statc (self) -> crate :: common :: Reg < regs :: Statc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x98usize) as _) } } } pub mod regs { # [doc = "Clock configure register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ckcfg (pub u32) ; impl Ckcfg { # [doc = "I2C Clock control in master mode"]
# [inline (always)]
pub const fn clkc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x0fff ; val as u16 } # [doc = "I2C Clock control in master mode"]
# [inline (always)]
pub fn set_clkc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 0usize)) | (((val as u32) & 0x0fff) << 0usize) ; } # [doc = "Duty cycle in fast mode"]
# [inline (always)]
pub const fn dtcy (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Duty cycle in fast mode"]
# [inline (always)]
pub fn set_dtcy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "I2C speed selection in master mode"]
# [inline (always)]
pub const fn fast (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "I2C speed selection in master mode"]
# [inline (always)]
pub fn set_fast (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Ckcfg { # [inline (always)]
fn default () -> Ckcfg { Ckcfg (0) } } impl core :: fmt :: Debug for Ckcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ckcfg") . field ("clkc" , & self . clkc ()) . field ("dtcy" , & self . dtcy ()) . field ("fast" , & self . fast ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ckcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ckcfg {{ clkc: {=u16:?}, dtcy: {=bool:?}, fast: {=bool:?} }}" , self . clkc () , self . dtcy () , self . fast ()) } } # [doc = "Control and status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cs (pub u32) ; impl Cs { # [doc = "Start lost flag"]
# [inline (always)]
pub const fn stlo (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Start lost flag"]
# [inline (always)]
pub fn set_stlo (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Stop condition sent out in master mode"]
# [inline (always)]
pub const fn stpsend (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Stop condition sent out in master mode"]
# [inline (always)]
pub fn set_stpsend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Interrupt enable for start lost"]
# [inline (always)]
pub const fn stloie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Interrupt enable for start lost"]
# [inline (always)]
pub fn set_stloie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Interrupt enable for stop condition sent"]
# [inline (always)]
pub const fn stpsendie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Interrupt enable for stop condition sent"]
# [inline (always)]
pub fn set_stpsendie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } } impl Default for Cs { # [inline (always)]
fn default () -> Cs { Cs (0) } } impl core :: fmt :: Debug for Cs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cs") . field ("stlo" , & self . stlo ()) . field ("stpsend" , & self . stpsend ()) . field ("stloie" , & self . stloie ()) . field ("stpsendie" , & self . stpsendie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cs {{ stlo: {=bool:?}, stpsend: {=bool:?}, stloie: {=bool:?}, stpsendie: {=bool:?} }}" , self . stlo () , self . stpsend () , self . stloie () , self . stpsendie ()) } } # [doc = "Control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "I2C peripheral enable"]
# [inline (always)]
pub const fn i2cen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "I2C peripheral enable"]
# [inline (always)]
pub fn set_i2cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SMBus/I2C mode switch"]
# [inline (always)]
pub const fn smben (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SMBus/I2C mode switch"]
# [inline (always)]
pub fn set_smben (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "SMBusType Selection"]
# [inline (always)]
pub const fn smbsel (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "SMBusType Selection"]
# [inline (always)]
pub fn set_smbsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "ARP protocol in SMBus switch"]
# [inline (always)]
pub const fn arpen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "ARP protocol in SMBus switch"]
# [inline (always)]
pub fn set_arpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "PEC Calculation Switch"]
# [inline (always)]
pub const fn pecen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "PEC Calculation Switch"]
# [inline (always)]
pub fn set_pecen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Whether or not to response to a General Call (0x00)"]
# [inline (always)]
pub const fn gcen (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Whether or not to response to a General Call (0x00)"]
# [inline (always)]
pub fn set_gcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Whether to stretch SCL low when data is not ready in slave mode"]
# [inline (always)]
pub const fn ss (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Whether to stretch SCL low when data is not ready in slave mode"]
# [inline (always)]
pub fn set_ss (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Generate a START condition on I2C bus"]
# [inline (always)]
pub const fn start (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Generate a START condition on I2C bus"]
# [inline (always)]
pub fn set_start (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Generate a STOP condition on I2C bus"]
# [inline (always)]
pub const fn stop (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Generate a STOP condition on I2C bus"]
# [inline (always)]
pub fn set_stop (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Whether or not to send an ACK"]
# [inline (always)]
pub const fn acken (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Whether or not to send an ACK"]
# [inline (always)]
pub fn set_acken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Position of ACK and PEC when receiving"]
# [inline (always)]
pub const fn poap (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Position of ACK and PEC when receiving"]
# [inline (always)]
pub fn set_poap (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "PEC Transfer"]
# [inline (always)]
pub const fn pectrans (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "PEC Transfer"]
# [inline (always)]
pub fn set_pectrans (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "SMBus alert"]
# [inline (always)]
pub const fn salt (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "SMBus alert"]
# [inline (always)]
pub fn set_salt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Software reset"]
# [inline (always)]
pub const fn sreset (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Software reset"]
# [inline (always)]
pub fn set_sreset (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("i2cen" , & self . i2cen ()) . field ("smben" , & self . smben ()) . field ("smbsel" , & self . smbsel ()) . field ("arpen" , & self . arpen ()) . field ("pecen" , & self . pecen ()) . field ("gcen" , & self . gcen ()) . field ("ss" , & self . ss ()) . field ("start" , & self . start ()) . field ("stop" , & self . stop ()) . field ("acken" , & self . acken ()) . field ("poap" , & self . poap ()) . field ("pectrans" , & self . pectrans ()) . field ("salt" , & self . salt ()) . field ("sreset" , & self . sreset ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ i2cen: {=bool:?}, smben: {=bool:?}, smbsel: {=bool:?}, arpen: {=bool:?}, pecen: {=bool:?}, gcen: {=bool:?}, ss: {=bool:?}, start: {=bool:?}, stop: {=bool:?}, acken: {=bool:?}, poap: {=bool:?}, pectrans: {=bool:?}, salt: {=bool:?}, sreset: {=bool:?} }}" , self . i2cen () , self . smben () , self . smbsel () , self . arpen () , self . pecen () , self . gcen () , self . ss () , self . start () , self . stop () , self . acken () , self . poap () , self . pectrans () , self . salt () , self . sreset ()) } } # [doc = "Control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "I2C Peripheral clock frequency"]
# [inline (always)]
pub const fn i2cclk (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "I2C Peripheral clock frequency"]
# [inline (always)]
pub fn set_i2cclk (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } # [doc = "Error interrupt enable"]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Error interrupt enable"]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Event interrupt enable"]
# [inline (always)]
pub const fn evie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Event interrupt enable"]
# [inline (always)]
pub fn set_evie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Buffer interrupt enable"]
# [inline (always)]
pub const fn bufie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Buffer interrupt enable"]
# [inline (always)]
pub fn set_bufie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "DMA mode switch"]
# [inline (always)]
pub const fn dmaon (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "DMA mode switch"]
# [inline (always)]
pub fn set_dmaon (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Flag indicating DMA last transfer"]
# [inline (always)]
pub const fn dmalst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Flag indicating DMA last transfer"]
# [inline (always)]
pub fn set_dmalst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("i2cclk" , & self . i2cclk ()) . field ("errie" , & self . errie ()) . field ("evie" , & self . evie ()) . field ("bufie" , & self . bufie ()) . field ("dmaon" , & self . dmaon ()) . field ("dmalst" , & self . dmalst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ i2cclk: {=u8:?}, errie: {=bool:?}, evie: {=bool:?}, bufie: {=bool:?}, dmaon: {=bool:?}, dmalst: {=bool:?} }}" , self . i2cclk () , self . errie () , self . evie () , self . bufie () , self . dmaon () , self . dmalst ()) } } # [doc = "Control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl2 (pub u32) ; impl Ctl2 { # [doc = "Fast mode plus enable"]
# [inline (always)]
pub const fn fmpen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Fast mode plus enable"]
# [inline (always)]
pub fn set_fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Start Early Termination Mode"]
# [inline (always)]
pub const fn setm (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Start Early Termination Mode"]
# [inline (always)]
pub fn set_setm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Timeout calculation enable"]
# [inline (always)]
pub const fn toen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Timeout calculation enable"]
# [inline (always)]
pub fn set_toen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "slave address recorde enable"]
# [inline (always)]
pub const fn radd (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "slave address recorde enable"]
# [inline (always)]
pub fn set_radd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "ingnore specify bits"]
# [inline (always)]
pub const fn addm (& self) -> u8 { let val = (self . 0 >> 9usize) & 0x7f ; val as u8 } # [doc = "ingnore specify bits"]
# [inline (always)]
pub fn set_addm (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 9usize)) | (((val as u32) & 0x7f) << 9usize) ; } } impl Default for Ctl2 { # [inline (always)]
fn default () -> Ctl2 { Ctl2 (0) } } impl core :: fmt :: Debug for Ctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl2") . field ("fmpen" , & self . fmpen ()) . field ("setm" , & self . setm ()) . field ("toen" , & self . toen ()) . field ("radd" , & self . radd ()) . field ("addm" , & self . addm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl2 {{ fmpen: {=bool:?}, setm: {=bool:?}, toen: {=bool:?}, radd: {=bool:?}, addm: {=u8:?} }}" , self . fmpen () , self . setm () , self . toen () , self . radd () , self . addm ()) } } # [doc = "Transfer buffer register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Data (pub u32) ; impl Data { # [doc = "Transmission or reception data buffer register"]
# [inline (always)]
pub const fn trb (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Transmission or reception data buffer register"]
# [inline (always)]
pub fn set_trb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for Data { # [inline (always)]
fn default () -> Data { Data (0) } } impl core :: fmt :: Debug for Data { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Data") . field ("trb" , & self . trb ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Data { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Data {{ trb: {=u8:?} }}" , self . trb ()) } } # [doc = "Rise time register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rt (pub u32) ; impl Rt { # [doc = "Maximum rise time in master mode"]
# [inline (always)]
pub const fn risetime (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [doc = "Maximum rise time in master mode"]
# [inline (always)]
pub fn set_risetime (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } } impl Default for Rt { # [inline (always)]
fn default () -> Rt { Rt (0) } } impl core :: fmt :: Debug for Rt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rt") . field ("risetime" , & self . risetime ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rt {{ risetime: {=u8:?} }}" , self . risetime ()) } } # [doc = "Slave address register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Saddr0 (pub u32) ; impl Saddr0 { # [doc = "Bit 0 of a 10-bit address"]
# [inline (always)]
pub const fn address0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Bit 0 of a 10-bit address"]
# [inline (always)]
pub fn set_address0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "7-bit address or bits 7:1 of a 10-bit address"]
# [inline (always)]
pub const fn address7_1 (& self) -> u8 { let val = (self . 0 >> 1usize) & 0x7f ; val as u8 } # [doc = "7-bit address or bits 7:1 of a 10-bit address"]
# [inline (always)]
pub fn set_address7_1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 1usize)) | (((val as u32) & 0x7f) << 1usize) ; } # [doc = "Highest two bits of a 10-bit address"]
# [inline (always)]
pub const fn address9_8 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Highest two bits of a 10-bit address"]
# [inline (always)]
pub fn set_address9_8 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Address mode for the I2C slave"]
# [inline (always)]
pub const fn addformat (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Address mode for the I2C slave"]
# [inline (always)]
pub fn set_addformat (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Saddr0 { # [inline (always)]
fn default () -> Saddr0 { Saddr0 (0) } } impl core :: fmt :: Debug for Saddr0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Saddr0") . field ("address0" , & self . address0 ()) . field ("address7_1" , & self . address7_1 ()) . field ("address9_8" , & self . address9_8 ()) . field ("addformat" , & self . addformat ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Saddr0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Saddr0 {{ address0: {=bool:?}, address7_1: {=u8:?}, address9_8: {=u8:?}, addformat: {=bool:?} }}" , self . address0 () , self . address7_1 () , self . address9_8 () , self . addformat ()) } } # [doc = "Slave address register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Saddr1 (pub u32) ; impl Saddr1 { # [doc = "Dual-Address mode switch"]
# [inline (always)]
pub const fn duaden (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Dual-Address mode switch"]
# [inline (always)]
pub fn set_duaden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Second I2C address for the slave in Dual-Address mode"]
# [inline (always)]
pub const fn address2 (& self) -> u8 { let val = (self . 0 >> 1usize) & 0x7f ; val as u8 } # [doc = "Second I2C address for the slave in Dual-Address mode"]
# [inline (always)]
pub fn set_address2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 1usize)) | (((val as u32) & 0x7f) << 1usize) ; } } impl Default for Saddr1 { # [inline (always)]
fn default () -> Saddr1 { Saddr1 (0) } } impl core :: fmt :: Debug for Saddr1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Saddr1") . field ("duaden" , & self . duaden ()) . field ("address2" , & self . address2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Saddr1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Saddr1 {{ duaden: {=bool:?}, address2: {=u8:?} }}" , self . duaden () , self . address2 ()) } } # [doc = "SAM control and status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Samcs (pub u32) ; impl Samcs { # [doc = "SAM_V interface enable"]
# [inline (always)]
pub const fn samen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "SAM_V interface enable"]
# [inline (always)]
pub fn set_samen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SAM_V interface timeout detect enable"]
# [inline (always)]
pub const fn stoen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SAM_V interface timeout detect enable"]
# [inline (always)]
pub fn set_stoen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Tx frame fall interrupt enable"]
# [inline (always)]
pub const fn tffie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Tx frame fall interrupt enable"]
# [inline (always)]
pub fn set_tffie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Tx frame rise interrupt enable"]
# [inline (always)]
pub const fn tfrie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Tx frame rise interrupt enable"]
# [inline (always)]
pub fn set_tfrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Rx frame fall interrupt enable"]
# [inline (always)]
pub const fn rffie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Rx frame fall interrupt enable"]
# [inline (always)]
pub fn set_rffie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Rx frame rise interrupt enable"]
# [inline (always)]
pub const fn rfrie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Rx frame rise interrupt enable"]
# [inline (always)]
pub fn set_rfrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "level of tx frame signal"]
# [inline (always)]
pub const fn txf (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "level of tx frame signal"]
# [inline (always)]
pub fn set_txf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "level of rx frame signal"]
# [inline (always)]
pub const fn rxf (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "level of rx frame signal"]
# [inline (always)]
pub fn set_rxf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Txframe fall flag"]
# [inline (always)]
pub const fn tff (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Txframe fall flag"]
# [inline (always)]
pub fn set_tff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Txframe rise flag"]
# [inline (always)]
pub const fn tfr (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Txframe rise flag"]
# [inline (always)]
pub fn set_tfr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Rxframe fall flag"]
# [inline (always)]
pub const fn rff (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Rxframe fall flag"]
# [inline (always)]
pub fn set_rff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Rxframe rise flag"]
# [inline (always)]
pub const fn rfr (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Rxframe rise flag"]
# [inline (always)]
pub fn set_rfr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Samcs { # [inline (always)]
fn default () -> Samcs { Samcs (0) } } impl core :: fmt :: Debug for Samcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Samcs") . field ("samen" , & self . samen ()) . field ("stoen" , & self . stoen ()) . field ("tffie" , & self . tffie ()) . field ("tfrie" , & self . tfrie ()) . field ("rffie" , & self . rffie ()) . field ("rfrie" , & self . rfrie ()) . field ("txf" , & self . txf ()) . field ("rxf" , & self . rxf ()) . field ("tff" , & self . tff ()) . field ("tfr" , & self . tfr ()) . field ("rff" , & self . rff ()) . field ("rfr" , & self . rfr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Samcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Samcs {{ samen: {=bool:?}, stoen: {=bool:?}, tffie: {=bool:?}, tfrie: {=bool:?}, rffie: {=bool:?}, rfrie: {=bool:?}, txf: {=bool:?}, rxf: {=bool:?}, tff: {=bool:?}, tfr: {=bool:?}, rff: {=bool:?}, rfr: {=bool:?} }}" , self . samen () , self . stoen () , self . tffie () , self . tfrie () , self . rffie () , self . rfrie () , self . txf () , self . rxf () , self . tff () , self . tfr () , self . rff () , self . rfr ()) } } # [doc = "Transfer status register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat0 (pub u32) ; impl Stat0 { # [doc = "START condition sent out in master mode"]
# [inline (always)]
pub const fn sbsend (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "START condition sent out in master mode"]
# [inline (always)]
pub fn set_sbsend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Address is sent in master mode or received and matches in slave mode"]
# [inline (always)]
pub const fn addsend (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Address is sent in master mode or received and matches in slave mode"]
# [inline (always)]
pub fn set_addsend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Byte transmission completed"]
# [inline (always)]
pub const fn btc (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Byte transmission completed"]
# [inline (always)]
pub fn set_btc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Header of 10-bit address is sent in master mode"]
# [inline (always)]
pub const fn add10send (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Header of 10-bit address is sent in master mode"]
# [inline (always)]
pub fn set_add10send (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "STOP condition detected in slave mode"]
# [inline (always)]
pub const fn stpdet (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "STOP condition detected in slave mode"]
# [inline (always)]
pub fn set_stpdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "I2C_DATA is not Empty during receiving"]
# [inline (always)]
pub const fn rbne (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "I2C_DATA is not Empty during receiving"]
# [inline (always)]
pub fn set_rbne (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "I2C_DATA is Empty during transmitting"]
# [inline (always)]
pub const fn tbe (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "I2C_DATA is Empty during transmitting"]
# [inline (always)]
pub fn set_tbe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "A bus error occurs indication a unexpected START or STOP condition on I2C bus"]
# [inline (always)]
pub const fn berr (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "A bus error occurs indication a unexpected START or STOP condition on I2C bus"]
# [inline (always)]
pub fn set_berr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Arbitration Lost in master mode"]
# [inline (always)]
pub const fn lostarb (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Arbitration Lost in master mode"]
# [inline (always)]
pub fn set_lostarb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Acknowledge error"]
# [inline (always)]
pub const fn aerr (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Acknowledge error"]
# [inline (always)]
pub fn set_aerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Over-run or under-run situation occurs in slave mode"]
# [inline (always)]
pub const fn ouerr (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Over-run or under-run situation occurs in slave mode"]
# [inline (always)]
pub fn set_ouerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "PEC error when receiving data"]
# [inline (always)]
pub const fn pecerr (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "PEC error when receiving data"]
# [inline (always)]
pub fn set_pecerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Timeout signal in SMBus mode"]
# [inline (always)]
pub const fn smbto (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Timeout signal in SMBus mode"]
# [inline (always)]
pub fn set_smbto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "SMBus Alert status"]
# [inline (always)]
pub const fn smbalt (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "SMBus Alert status"]
# [inline (always)]
pub fn set_smbalt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Stat0 { # [inline (always)]
fn default () -> Stat0 { Stat0 (0) } } impl core :: fmt :: Debug for Stat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat0") . field ("sbsend" , & self . sbsend ()) . field ("addsend" , & self . addsend ()) . field ("btc" , & self . btc ()) . field ("add10send" , & self . add10send ()) . field ("stpdet" , & self . stpdet ()) . field ("rbne" , & self . rbne ()) . field ("tbe" , & self . tbe ()) . field ("berr" , & self . berr ()) . field ("lostarb" , & self . lostarb ()) . field ("aerr" , & self . aerr ()) . field ("ouerr" , & self . ouerr ()) . field ("pecerr" , & self . pecerr ()) . field ("smbto" , & self . smbto ()) . field ("smbalt" , & self . smbalt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat0 {{ sbsend: {=bool:?}, addsend: {=bool:?}, btc: {=bool:?}, add10send: {=bool:?}, stpdet: {=bool:?}, rbne: {=bool:?}, tbe: {=bool:?}, berr: {=bool:?}, lostarb: {=bool:?}, aerr: {=bool:?}, ouerr: {=bool:?}, pecerr: {=bool:?}, smbto: {=bool:?}, smbalt: {=bool:?} }}" , self . sbsend () , self . addsend () , self . btc () , self . add10send () , self . stpdet () , self . rbne () , self . tbe () , self . berr () , self . lostarb () , self . aerr () , self . ouerr () , self . pecerr () , self . smbto () , self . smbalt ()) } } # [doc = "Transfer status register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat1 (pub u32) ; impl Stat1 { # [doc = "A flag indicating whether I2C block is in master or slave mode"]
# [inline (always)]
pub const fn master (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "A flag indicating whether I2C block is in master or slave mode"]
# [inline (always)]
pub fn set_master (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Busy flag"]
# [inline (always)]
pub const fn i2cbsy (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Busy flag"]
# [inline (always)]
pub fn set_i2cbsy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Whether the I2C is a transmitter or a receiver"]
# [inline (always)]
pub const fn tr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Whether the I2C is a transmitter or a receiver"]
# [inline (always)]
pub fn set_tr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "General call address (00h) received"]
# [inline (always)]
pub const fn rxgc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "General call address (00h) received"]
# [inline (always)]
pub fn set_rxgc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Default address of SMBusDevice"]
# [inline (always)]
pub const fn defsmb (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Default address of SMBusDevice"]
# [inline (always)]
pub fn set_defsmb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "SMBus Host Header detected in slave mode"]
# [inline (always)]
pub const fn hstsmb (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "SMBus Host Header detected in slave mode"]
# [inline (always)]
pub fn set_hstsmb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Dual Flag in slave mode"]
# [inline (always)]
pub const fn dumodf (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Dual Flag in slave mode"]
# [inline (always)]
pub fn set_dumodf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Packet Error Checking Value that calculated by hardware when PEC is enabled"]
# [inline (always)]
pub const fn pecv (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Packet Error Checking Value that calculated by hardware when PEC is enabled"]
# [inline (always)]
pub fn set_pecv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } } impl Default for Stat1 { # [inline (always)]
fn default () -> Stat1 { Stat1 (0) } } impl core :: fmt :: Debug for Stat1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat1") . field ("master" , & self . master ()) . field ("i2cbsy" , & self . i2cbsy ()) . field ("tr" , & self . tr ()) . field ("rxgc" , & self . rxgc ()) . field ("defsmb" , & self . defsmb ()) . field ("hstsmb" , & self . hstsmb ()) . field ("dumodf" , & self . dumodf ()) . field ("pecv" , & self . pecv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat1 {{ master: {=bool:?}, i2cbsy: {=bool:?}, tr: {=bool:?}, rxgc: {=bool:?}, defsmb: {=bool:?}, hstsmb: {=bool:?}, dumodf: {=bool:?}, pecv: {=u8:?} }}" , self . master () , self . i2cbsy () , self . tr () , self . rxgc () , self . defsmb () , self . hstsmb () , self . dumodf () , self . pecv ()) } } # [doc = "Status clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Statc (pub u32) ; impl Statc { # [doc = "Start send status clear"]
# [inline (always)]
pub const fn sbsendc (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Start send status clear"]
# [inline (always)]
pub fn set_sbsendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "ADDSEND status clear"]
# [inline (always)]
pub const fn addsendc (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "ADDSEND status clear"]
# [inline (always)]
pub fn set_addsendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "BTC status clear"]
# [inline (always)]
pub const fn btcc (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "BTC status clear"]
# [inline (always)]
pub fn set_btcc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "ADD10SEND status clear"]
# [inline (always)]
pub const fn add10sendc (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "ADD10SEND status clear"]
# [inline (always)]
pub fn set_add10sendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "STOPF status clear"]
# [inline (always)]
pub const fn stopfc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "STOPF status clear"]
# [inline (always)]
pub fn set_stopfc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Status register clear enable"]
# [inline (always)]
pub const fn srcen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Status register clear enable"]
# [inline (always)]
pub fn set_srcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Statc { # [inline (always)]
fn default () -> Statc { Statc (0) } } impl core :: fmt :: Debug for Statc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Statc") . field ("sbsendc" , & self . sbsendc ()) . field ("addsendc" , & self . addsendc ()) . field ("btcc" , & self . btcc ()) . field ("add10sendc" , & self . add10sendc ()) . field ("stopfc" , & self . stopfc ()) . field ("srcen" , & self . srcen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Statc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Statc {{ sbsendc: {=bool:?}, addsendc: {=bool:?}, btcc: {=bool:?}, add10sendc: {=bool:?}, stopfc: {=bool:?}, srcen: {=bool:?} }}" , self . sbsendc () , self . addsendc () , self . btcc () , self . add10sendc () , self . stopfc () , self . srcen ()) } } }