#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Iref { ptr : * mut u8 } unsafe impl Send for Iref { } unsafe impl Sync for Iref { } impl Iref { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn iref_ctl (self) -> crate :: common :: Reg < regs :: IrefCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0300usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct IrefCtl (pub u32) ; impl IrefCtl { # [must_use]
# [inline (always)]
pub const fn iref_ctl_csdt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_iref_ctl_csdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn iref_ctl_scmod (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_iref_ctl_scmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn iref_ctl_cpt (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_iref_ctl_cpt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn iref_ctl_ssel (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_iref_ctl_ssel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn iref_ctl_cren (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_iref_ctl_cren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for IrefCtl { # [inline (always)]
fn default () -> IrefCtl { IrefCtl (0) } } impl core :: fmt :: Debug for IrefCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("IrefCtl") . field ("iref_ctl_csdt" , & self . iref_ctl_csdt ()) . field ("iref_ctl_scmod" , & self . iref_ctl_scmod ()) . field ("iref_ctl_cpt" , & self . iref_ctl_cpt ()) . field ("iref_ctl_ssel" , & self . iref_ctl_ssel ()) . field ("iref_ctl_cren" , & self . iref_ctl_cren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for IrefCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "IrefCtl {{ iref_ctl_csdt: {=u8:?}, iref_ctl_scmod: {=bool:?}, iref_ctl_cpt: {=u8:?}, iref_ctl_ssel: {=bool:?}, iref_ctl_cren: {=bool:?} }}" , self . iref_ctl_csdt () , self . iref_ctl_scmod () , self . iref_ctl_cpt () , self . iref_ctl_ssel () , self . iref_ctl_cren ()) } } }