#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Lpdts { ptr : * mut u8 } unsafe impl Send for Lpdts { } unsafe impl Sync for Lpdts { } impl Lpdts { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn lpdts_cfg (self) -> crate :: common :: Reg < regs :: LpdtsCfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn lpdts_sdata (self) -> crate :: common :: Reg < regs :: LpdtsSdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn lpdts_rdata (self) -> crate :: common :: Reg < regs :: LpdtsRdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn lpdts_it (self) -> crate :: common :: Reg < regs :: LpdtsIt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn lpdts_data (self) -> crate :: common :: Reg < regs :: LpdtsData , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn lpdts_stat (self) -> crate :: common :: Reg < regs :: LpdtsStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn lpdts_inten (self) -> crate :: common :: Reg < regs :: LpdtsInten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn lpdts_intc (self) -> crate :: common :: Reg < regs :: LpdtsIntc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn lpdts_op (self) -> crate :: common :: Reg < regs :: LpdtsOp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsCfg (pub u32) ; impl LpdtsCfg { # [must_use]
# [inline (always)]
pub const fn lpdts_cfg_tsen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_cfg_tsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_cfg_trgs (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_cfg_trgs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_cfg_itsel (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_lpdts_cfg_itsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_cfg_spt (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_lpdts_cfg_spt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_cfg_refsel (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_cfg_refsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } } impl Default for LpdtsCfg { # [inline (always)]
fn default () -> LpdtsCfg { LpdtsCfg (0) } } impl core :: fmt :: Debug for LpdtsCfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsCfg") . field ("lpdts_cfg_tsen" , & self . lpdts_cfg_tsen ()) . field ("lpdts_cfg_trgs" , & self . lpdts_cfg_trgs ()) . field ("lpdts_cfg_itsel" , & self . lpdts_cfg_itsel ()) . field ("lpdts_cfg_spt" , & self . lpdts_cfg_spt ()) . field ("lpdts_cfg_refsel" , & self . lpdts_cfg_refsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsCfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsCfg {{ lpdts_cfg_tsen: {=bool:?}, lpdts_cfg_trgs: {=bool:?}, lpdts_cfg_itsel: {=u8:?}, lpdts_cfg_spt: {=u8:?}, lpdts_cfg_refsel: {=bool:?} }}" , self . lpdts_cfg_tsen () , self . lpdts_cfg_trgs () , self . lpdts_cfg_itsel () , self . lpdts_cfg_spt () , self . lpdts_cfg_refsel ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsData (pub u32) ; impl LpdtsData { # [must_use]
# [inline (always)]
pub const fn lpdts_data_coval (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_lpdts_data_coval (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for LpdtsData { # [inline (always)]
fn default () -> LpdtsData { LpdtsData (0) } } impl core :: fmt :: Debug for LpdtsData { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsData") . field ("lpdts_data_coval" , & self . lpdts_data_coval ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsData { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsData {{ lpdts_data_coval: {=u16:?} }}" , self . lpdts_data_coval ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsIntc (pub u32) ; impl LpdtsIntc { # [must_use]
# [inline (always)]
pub const fn lpdts_intc_emic (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_intc_emic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_intc_ltic (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_intc_ltic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_intc_htic (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_intc_htic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_intc_emaic (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_intc_emaic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_intc_ltaic (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_intc_ltaic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_intc_htaic (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_intc_htaic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for LpdtsIntc { # [inline (always)]
fn default () -> LpdtsIntc { LpdtsIntc (0) } } impl core :: fmt :: Debug for LpdtsIntc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsIntc") . field ("lpdts_intc_emic" , & self . lpdts_intc_emic ()) . field ("lpdts_intc_ltic" , & self . lpdts_intc_ltic ()) . field ("lpdts_intc_htic" , & self . lpdts_intc_htic ()) . field ("lpdts_intc_emaic" , & self . lpdts_intc_emaic ()) . field ("lpdts_intc_ltaic" , & self . lpdts_intc_ltaic ()) . field ("lpdts_intc_htaic" , & self . lpdts_intc_htaic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsIntc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsIntc {{ lpdts_intc_emic: {=bool:?}, lpdts_intc_ltic: {=bool:?}, lpdts_intc_htic: {=bool:?}, lpdts_intc_emaic: {=bool:?}, lpdts_intc_ltaic: {=bool:?}, lpdts_intc_htaic: {=bool:?} }}" , self . lpdts_intc_emic () , self . lpdts_intc_ltic () , self . lpdts_intc_htic () , self . lpdts_intc_emaic () , self . lpdts_intc_ltaic () , self . lpdts_intc_htaic ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsInten (pub u32) ; impl LpdtsInten { # [must_use]
# [inline (always)]
pub const fn lpdts_inten_emie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_inten_emie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_inten_ltie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_inten_ltie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_inten_htie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_inten_htie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_inten_emaie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_inten_emaie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_inten_ltaie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_inten_ltaie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_inten_htaie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_inten_htaie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for LpdtsInten { # [inline (always)]
fn default () -> LpdtsInten { LpdtsInten (0) } } impl core :: fmt :: Debug for LpdtsInten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsInten") . field ("lpdts_inten_emie" , & self . lpdts_inten_emie ()) . field ("lpdts_inten_ltie" , & self . lpdts_inten_ltie ()) . field ("lpdts_inten_htie" , & self . lpdts_inten_htie ()) . field ("lpdts_inten_emaie" , & self . lpdts_inten_emaie ()) . field ("lpdts_inten_ltaie" , & self . lpdts_inten_ltaie ()) . field ("lpdts_inten_htaie" , & self . lpdts_inten_htaie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsInten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsInten {{ lpdts_inten_emie: {=bool:?}, lpdts_inten_ltie: {=bool:?}, lpdts_inten_htie: {=bool:?}, lpdts_inten_emaie: {=bool:?}, lpdts_inten_ltaie: {=bool:?}, lpdts_inten_htaie: {=bool:?} }}" , self . lpdts_inten_emie () , self . lpdts_inten_ltie () , self . lpdts_inten_htie () , self . lpdts_inten_emaie () , self . lpdts_inten_ltaie () , self . lpdts_inten_htaie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsIt (pub u32) ; impl LpdtsIt { # [must_use]
# [inline (always)]
pub const fn lpdts_it_intlt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_lpdts_it_intlt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_it_intht (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_lpdts_it_intht (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for LpdtsIt { # [inline (always)]
fn default () -> LpdtsIt { LpdtsIt (0) } } impl core :: fmt :: Debug for LpdtsIt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsIt") . field ("lpdts_it_intlt" , & self . lpdts_it_intlt ()) . field ("lpdts_it_intht" , & self . lpdts_it_intht ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsIt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsIt {{ lpdts_it_intlt: {=u16:?}, lpdts_it_intht: {=u16:?} }}" , self . lpdts_it_intlt () , self . lpdts_it_intht ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsOp (pub u32) ; impl LpdtsOp { # [must_use]
# [inline (always)]
pub const fn lpdts_op_op (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_lpdts_op_op (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for LpdtsOp { # [inline (always)]
fn default () -> LpdtsOp { LpdtsOp (0) } } impl core :: fmt :: Debug for LpdtsOp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsOp") . field ("lpdts_op_op" , & self . lpdts_op_op ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsOp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsOp {{ lpdts_op_op: {=u32:?} }}" , self . lpdts_op_op ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsRdata (pub u32) ; impl LpdtsRdata { # [must_use]
# [inline (always)]
pub const fn lpdts_rdata_rcval (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_lpdts_rdata_rcval (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for LpdtsRdata { # [inline (always)]
fn default () -> LpdtsRdata { LpdtsRdata (0) } } impl core :: fmt :: Debug for LpdtsRdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsRdata") . field ("lpdts_rdata_rcval" , & self . lpdts_rdata_rcval ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsRdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsRdata {{ lpdts_rdata_rcval: {=u16:?} }}" , self . lpdts_rdata_rcval ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsSdata (pub u32) ; impl LpdtsSdata { # [must_use]
# [inline (always)]
pub const fn lpdts_sdata_freq (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_lpdts_sdata_freq (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_sdata_val (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_lpdts_sdata_val (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 16usize)) | (((val as u32) & 0x03) << 16usize) ; } } impl Default for LpdtsSdata { # [inline (always)]
fn default () -> LpdtsSdata { LpdtsSdata (0) } } impl core :: fmt :: Debug for LpdtsSdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsSdata") . field ("lpdts_sdata_freq" , & self . lpdts_sdata_freq ()) . field ("lpdts_sdata_val" , & self . lpdts_sdata_val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsSdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsSdata {{ lpdts_sdata_freq: {=u16:?}, lpdts_sdata_val: {=u8:?} }}" , self . lpdts_sdata_freq () , self . lpdts_sdata_val ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct LpdtsStat (pub u32) ; impl LpdtsStat { # [must_use]
# [inline (always)]
pub const fn lpdts_stat_emif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_emif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_stat_ltif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_ltif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_stat_htif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_htif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_stat_emaif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_emaif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_stat_ltaif (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_ltaif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_stat_htaif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_htaif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn lpdts_stat_tsrf (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_lpdts_stat_tsrf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for LpdtsStat { # [inline (always)]
fn default () -> LpdtsStat { LpdtsStat (0) } } impl core :: fmt :: Debug for LpdtsStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("LpdtsStat") . field ("lpdts_stat_emif" , & self . lpdts_stat_emif ()) . field ("lpdts_stat_ltif" , & self . lpdts_stat_ltif ()) . field ("lpdts_stat_htif" , & self . lpdts_stat_htif ()) . field ("lpdts_stat_emaif" , & self . lpdts_stat_emaif ()) . field ("lpdts_stat_ltaif" , & self . lpdts_stat_ltaif ()) . field ("lpdts_stat_htaif" , & self . lpdts_stat_htaif ()) . field ("lpdts_stat_tsrf" , & self . lpdts_stat_tsrf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for LpdtsStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "LpdtsStat {{ lpdts_stat_emif: {=bool:?}, lpdts_stat_ltif: {=bool:?}, lpdts_stat_htif: {=bool:?}, lpdts_stat_emaif: {=bool:?}, lpdts_stat_ltaif: {=bool:?}, lpdts_stat_htaif: {=bool:?}, lpdts_stat_tsrf: {=bool:?} }}" , self . lpdts_stat_emif () , self . lpdts_stat_ltif () , self . lpdts_stat_htif () , self . lpdts_stat_emaif () , self . lpdts_stat_ltaif () , self . lpdts_stat_htaif () , self . lpdts_stat_tsrf ()) } } }