#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ospim { ptr : * mut u8 } unsafe impl Send for Ospim { } unsafe impl Sync for Ospim { } impl Ospim { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn ospim_ctl (self) -> crate :: common :: Reg < regs :: OspimCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn ospim_pcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn ospim_pcfg_0 (self) -> crate :: common :: Reg < regs :: OspimPcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn ospim_pcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn ospim_pcfg_1 (self) -> crate :: common :: Reg < regs :: OspimPcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct OspimCtl (pub u32) ; impl OspimCtl { # [must_use]
# [inline (always)]
pub const fn ospim_ctl_mulen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_ctl_mulen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_ctl_acktm (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_ospim_ctl_acktm (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } } impl Default for OspimCtl { # [inline (always)]
fn default () -> OspimCtl { OspimCtl (0) } } impl core :: fmt :: Debug for OspimCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("OspimCtl") . field ("ospim_ctl_mulen" , & self . ospim_ctl_mulen ()) . field ("ospim_ctl_acktm" , & self . ospim_ctl_acktm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for OspimCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "OspimCtl {{ ospim_ctl_mulen: {=bool:?}, ospim_ctl_acktm: {=u8:?} }}" , self . ospim_ctl_mulen () , self . ospim_ctl_acktm ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct OspimPcfg (pub u32) ; impl OspimPcfg { # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_scken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_scken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_srcpck (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_srcpck (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_dqsen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_dqsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_srcpdqs (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_srcpdqs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_csnen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_csnen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_srcpcs (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_srcpcs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_polen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_polen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_srcplio (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_ospim_pcfg_srcplio (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 17usize)) | (((val as u32) & 0x03) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_pohen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_ospim_pcfg_pohen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn ospim_pcfg_srcphio (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_ospim_pcfg_srcphio (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 25usize)) | (((val as u32) & 0x03) << 25usize) ; } } impl Default for OspimPcfg { # [inline (always)]
fn default () -> OspimPcfg { OspimPcfg (0) } } impl core :: fmt :: Debug for OspimPcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("OspimPcfg") . field ("ospim_pcfg_scken" , & self . ospim_pcfg_scken ()) . field ("ospim_pcfg_srcpck" , & self . ospim_pcfg_srcpck ()) . field ("ospim_pcfg_dqsen" , & self . ospim_pcfg_dqsen ()) . field ("ospim_pcfg_srcpdqs" , & self . ospim_pcfg_srcpdqs ()) . field ("ospim_pcfg_csnen" , & self . ospim_pcfg_csnen ()) . field ("ospim_pcfg_srcpcs" , & self . ospim_pcfg_srcpcs ()) . field ("ospim_pcfg_polen" , & self . ospim_pcfg_polen ()) . field ("ospim_pcfg_srcplio" , & self . ospim_pcfg_srcplio ()) . field ("ospim_pcfg_pohen" , & self . ospim_pcfg_pohen ()) . field ("ospim_pcfg_srcphio" , & self . ospim_pcfg_srcphio ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for OspimPcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "OspimPcfg {{ ospim_pcfg_scken: {=bool:?}, ospim_pcfg_srcpck: {=bool:?}, ospim_pcfg_dqsen: {=bool:?}, ospim_pcfg_srcpdqs: {=bool:?}, ospim_pcfg_csnen: {=bool:?}, ospim_pcfg_srcpcs: {=bool:?}, ospim_pcfg_polen: {=bool:?}, ospim_pcfg_srcplio: {=u8:?}, ospim_pcfg_pohen: {=bool:?}, ospim_pcfg_srcphio: {=u8:?} }}" , self . ospim_pcfg_scken () , self . ospim_pcfg_srcpck () , self . ospim_pcfg_dqsen () , self . ospim_pcfg_srcpdqs () , self . ospim_pcfg_csnen () , self . ospim_pcfg_srcpcs () , self . ospim_pcfg_polen () , self . ospim_pcfg_srcplio () , self . ospim_pcfg_pohen () , self . ospim_pcfg_srcphio ()) } } }