#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Power management unit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pmu { ptr : * mut u8 } unsafe impl Send for Pmu { } unsafe impl Sync for Pmu { } impl Pmu { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control and status register"]
# [inline (always)]
pub const fn cs (self) -> crate :: common :: Reg < regs :: Cs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Control register"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } } pub mod regs { # [doc = "Control and status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cs (pub u32) ; impl Cs { # [doc = "Wakeup Flag"]
# [inline (always)]
pub const fn wuf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Wakeup Flag"]
# [inline (always)]
pub fn set_wuf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Standby Flag"]
# [inline (always)]
pub const fn stbf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Standby Flag"]
# [inline (always)]
pub fn set_stbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Low Voltage Detector Status Flag"]
# [inline (always)]
pub const fn lvdf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Low Voltage Detector Status Flag"]
# [inline (always)]
pub fn set_lvdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "VDDA analog voltage detector voltage output on VDDA flag bit."]
# [inline (always)]
pub const fn vavdf (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "VDDA analog voltage detector voltage output on VDDA flag bit."]
# [inline (always)]
pub fn set_vavdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "V1.2v under voltage detector flag bit"]
# [inline (always)]
pub const fn vuvdf0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "V1.2v under voltage detector flag bit"]
# [inline (always)]
pub fn set_vuvdf0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "V1.2v over voltage detector flag bit after digital filter."]
# [inline (always)]
pub const fn vovdf (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "V1.2v over voltage detector flag bit after digital filter."]
# [inline (always)]
pub fn set_vovdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "V1.2v under voltage detector flag bit after digital filter."]
# [inline (always)]
pub const fn vuvdf1 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "V1.2v under voltage detector flag bit after digital filter."]
# [inline (always)]
pub fn set_vuvdf1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "WKUP Pin Enable"]
# [inline (always)]
pub const fn wupen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "WKUP Pin Enable"]
# [inline (always)]
pub fn set_wupen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "LDO voltage select ready flag"]
# [inline (always)]
pub const fn ldovsrf (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "LDO voltage select ready flag"]
# [inline (always)]
pub fn set_ldovsrf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Low-driver mode ready flag"]
# [inline (always)]
pub const fn ldrf (& self) -> u8 { let val = (self . 0 >> 18usize) & 0x03 ; val as u8 } # [doc = "Low-driver mode ready flag"]
# [inline (always)]
pub fn set_ldrf (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 18usize)) | (((val as u32) & 0x03) << 18usize) ; } } impl Default for Cs { # [inline (always)]
fn default () -> Cs { Cs (0) } } impl core :: fmt :: Debug for Cs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cs") . field ("wuf" , & self . wuf ()) . field ("stbf" , & self . stbf ()) . field ("lvdf" , & self . lvdf ()) . field ("vavdf" , & self . vavdf ()) . field ("vuvdf0" , & self . vuvdf0 ()) . field ("vovdf" , & self . vovdf ()) . field ("vuvdf1" , & self . vuvdf1 ()) . field ("wupen" , & self . wupen ()) . field ("ldovsrf" , & self . ldovsrf ()) . field ("ldrf" , & self . ldrf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cs {{ wuf: {=bool:?}, stbf: {=bool:?}, lvdf: {=bool:?}, vavdf: {=bool:?}, vuvdf0: {=bool:?}, vovdf: {=bool:?}, vuvdf1: {=bool:?}, wupen: {=bool:?}, ldovsrf: {=bool:?}, ldrf: {=u8:?} }}" , self . wuf () , self . stbf () , self . lvdf () , self . vavdf () , self . vuvdf0 () , self . vovdf () , self . vuvdf1 () , self . wupen () , self . ldovsrf () , self . ldrf ()) } } # [doc = "Control register0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "LDO Low Power Mode"]
# [inline (always)]
pub const fn ldolp (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "LDO Low Power Mode"]
# [inline (always)]
pub fn set_ldolp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Standby Mode"]
# [inline (always)]
pub const fn stbmod (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Standby Mode"]
# [inline (always)]
pub fn set_stbmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Wakeup Flag Reset"]
# [inline (always)]
pub const fn wurst (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Wakeup Flag Reset"]
# [inline (always)]
pub fn set_wurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Standby Flag Reset"]
# [inline (always)]
pub const fn stbrst (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Standby Flag Reset"]
# [inline (always)]
pub fn set_stbrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Low Voltage Detector Enable"]
# [inline (always)]
pub const fn lvden (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Low Voltage Detector Enable"]
# [inline (always)]
pub fn set_lvden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Low Voltage Detector Threshold"]
# [inline (always)]
pub const fn lvdt (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x07 ; val as u8 } # [doc = "Low Voltage Detector Threshold"]
# [inline (always)]
pub fn set_lvdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 5usize)) | (((val as u32) & 0x07) << 5usize) ; } # [doc = "Backup Domain Write Enable"]
# [inline (always)]
pub const fn bkpwen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Backup Domain Write Enable"]
# [inline (always)]
pub fn set_bkpwen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "PDR threshold selection"]
# [inline (always)]
pub const fn pdrvs (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "PDR threshold selection"]
# [inline (always)]
pub fn set_pdrvs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Low-driver mode when use low power LDO."]
# [inline (always)]
pub const fn ldlp (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Low-driver mode when use low power LDO."]
# [inline (always)]
pub fn set_ldlp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Low-driver mode when use normal power LDO"]
# [inline (always)]
pub const fn ldnp (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Low-driver mode when use normal power LDO"]
# [inline (always)]
pub fn set_ldnp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "LDO output voltage select"]
# [inline (always)]
pub const fn ldovs (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "LDO output voltage select"]
# [inline (always)]
pub fn set_ldovs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Low-driver mode enable in Deep-sleep mode"]
# [inline (always)]
pub const fn lden (& self) -> u8 { let val = (self . 0 >> 18usize) & 0x03 ; val as u8 } # [doc = "Low-driver mode enable in Deep-sleep mode"]
# [inline (always)]
pub fn set_lden (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 18usize)) | (((val as u32) & 0x03) << 18usize) ; } # [doc = "VDDA analog voltage detector voltage enable bit"]
# [inline (always)]
pub const fn vavden (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "VDDA analog voltage detector voltage enable bit"]
# [inline (always)]
pub fn set_vavden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "VDDA analog voltage detector voltage level configure bits"]
# [inline (always)]
pub const fn vavdvc (& self) -> u8 { let val = (self . 0 >> 21usize) & 0x03 ; val as u8 } # [doc = "VDDA analog voltage detector voltage level configure bits"]
# [inline (always)]
pub fn set_vavdvc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 21usize)) | (((val as u32) & 0x03) << 21usize) ; } # [doc = "V1.2V over Voltage detector enable"]
# [inline (always)]
pub const fn vovden (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "V1.2V over Voltage detector enable"]
# [inline (always)]
pub fn set_vovden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "V1.2V under Voltage detector enable"]
# [inline (always)]
pub const fn vuvden (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "V1.2V under Voltage detector enable"]
# [inline (always)]
pub fn set_vuvden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "V1.2v over voltage detector voltage level configure bits"]
# [inline (always)]
pub const fn vovdvc (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x03 ; val as u8 } # [doc = "V1.2v over voltage detector voltage level configure bits"]
# [inline (always)]
pub fn set_vovdvc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 25usize)) | (((val as u32) & 0x03) << 25usize) ; } # [doc = "V1.2v under voltage detector voltage level configure bits"]
# [inline (always)]
pub const fn vuvdvc (& self) -> u8 { let val = (self . 0 >> 27usize) & 0x03 ; val as u8 } # [doc = "V1.2v under voltage detector voltage level configure bits"]
# [inline (always)]
pub fn set_vuvdvc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 27usize)) | (((val as u32) & 0x03) << 27usize) ; } # [doc = "Register lock"]
# [inline (always)]
pub const fn lock (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Register lock"]
# [inline (always)]
pub fn set_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("ldolp" , & self . ldolp ()) . field ("stbmod" , & self . stbmod ()) . field ("wurst" , & self . wurst ()) . field ("stbrst" , & self . stbrst ()) . field ("lvden" , & self . lvden ()) . field ("lvdt" , & self . lvdt ()) . field ("bkpwen" , & self . bkpwen ()) . field ("pdrvs" , & self . pdrvs ()) . field ("ldlp" , & self . ldlp ()) . field ("ldnp" , & self . ldnp ()) . field ("ldovs" , & self . ldovs ()) . field ("lden" , & self . lden ()) . field ("vavden" , & self . vavden ()) . field ("vavdvc" , & self . vavdvc ()) . field ("vovden" , & self . vovden ()) . field ("vuvden" , & self . vuvden ()) . field ("vovdvc" , & self . vovdvc ()) . field ("vuvdvc" , & self . vuvdvc ()) . field ("lock" , & self . lock ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ ldolp: {=bool:?}, stbmod: {=bool:?}, wurst: {=bool:?}, stbrst: {=bool:?}, lvden: {=bool:?}, lvdt: {=u8:?}, bkpwen: {=bool:?}, pdrvs: {=bool:?}, ldlp: {=bool:?}, ldnp: {=bool:?}, ldovs: {=u8:?}, lden: {=u8:?}, vavden: {=bool:?}, vavdvc: {=u8:?}, vovden: {=bool:?}, vuvden: {=bool:?}, vovdvc: {=u8:?}, vuvdvc: {=u8:?}, lock: {=bool:?} }}" , self . ldolp () , self . stbmod () , self . wurst () , self . stbrst () , self . lvden () , self . lvdt () , self . bkpwen () , self . pdrvs () , self . ldlp () , self . ldnp () , self . ldovs () , self . lden () , self . vavden () , self . vavdvc () , self . vovden () , self . vuvden () , self . vovdvc () , self . vuvdvc () , self . lock ()) } } # [doc = "Control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "VOVD analog output digital noise filter"]
# [inline (always)]
pub const fn vovdo_dnf (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "VOVD analog output digital noise filter"]
# [inline (always)]
pub fn set_vovdo_dnf (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "VUVD analog output digital noise filter"]
# [inline (always)]
pub const fn vuvdo_dnf (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "VUVD analog output digital noise filter"]
# [inline (always)]
pub fn set_vuvdo_dnf (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("vovdo_dnf" , & self . vovdo_dnf ()) . field ("vuvdo_dnf" , & self . vuvdo_dnf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ vovdo_dnf: {=u8:?}, vuvdo_dnf: {=u8:?} }}" , self . vovdo_dnf () , self . vuvdo_dnf ()) } } }