#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rcu { ptr : * mut u8 } unsafe impl Send for Rcu { } unsafe impl Sync for Rcu { } impl Rcu { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn rcu_ctl (self) -> crate :: common :: Reg < regs :: RcuCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn rcu_cfg0 (self) -> crate :: common :: Reg < regs :: RcuCfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn rcu_int (self) -> crate :: common :: Reg < regs :: RcuInt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn rcu_apb2rst (self) -> crate :: common :: Reg < regs :: RcuApb2rst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn rcu_apb1rst (self) -> crate :: common :: Reg < regs :: RcuApb1rst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn rcu_ahben (self) -> crate :: common :: Reg < regs :: RcuAhben , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn rcu_apb2en (self) -> crate :: common :: Reg < regs :: RcuApb2en , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn rcu_apb1en (self) -> crate :: common :: Reg < regs :: RcuApb1en , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn rcu_rstsck (self) -> crate :: common :: Reg < regs :: RcuRstsck , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn rcu_ahbrst (self) -> crate :: common :: Reg < regs :: RcuAhbrst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn rcu_cfg1 (self) -> crate :: common :: Reg < regs :: RcuCfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn rcu_cfg2 (self) -> crate :: common :: Reg < regs :: RcuCfg2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhben (pub u32) ; impl RcuAhben { # [must_use]
# [inline (always)]
pub const fn rcu_ahben_dma0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_dma0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_dma1en (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_dma1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_sramspen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_sramspen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_dmamuxen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_dmamuxen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_crcen (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_crcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_paen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_paen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pben (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pben (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pcen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pden (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_peen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_peen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pfen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pgen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pnen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pnen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_pocen (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_pocen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_gtocen (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_gtocen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_svpwmen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_svpwmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahben_tmuen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahben_tmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for RcuAhben { # [inline (always)]
fn default () -> RcuAhben { RcuAhben (0) } } impl core :: fmt :: Debug for RcuAhben { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhben") . field ("rcu_ahben_dma0en" , & self . rcu_ahben_dma0en ()) . field ("rcu_ahben_dma1en" , & self . rcu_ahben_dma1en ()) . field ("rcu_ahben_sramspen" , & self . rcu_ahben_sramspen ()) . field ("rcu_ahben_dmamuxen" , & self . rcu_ahben_dmamuxen ()) . field ("rcu_ahben_crcen" , & self . rcu_ahben_crcen ()) . field ("rcu_ahben_paen" , & self . rcu_ahben_paen ()) . field ("rcu_ahben_pben" , & self . rcu_ahben_pben ()) . field ("rcu_ahben_pcen" , & self . rcu_ahben_pcen ()) . field ("rcu_ahben_pden" , & self . rcu_ahben_pden ()) . field ("rcu_ahben_peen" , & self . rcu_ahben_peen ()) . field ("rcu_ahben_pfen" , & self . rcu_ahben_pfen ()) . field ("rcu_ahben_pgen" , & self . rcu_ahben_pgen ()) . field ("rcu_ahben_pnen" , & self . rcu_ahben_pnen ()) . field ("rcu_ahben_pocen" , & self . rcu_ahben_pocen ()) . field ("rcu_ahben_gtocen" , & self . rcu_ahben_gtocen ()) . field ("rcu_ahben_svpwmen" , & self . rcu_ahben_svpwmen ()) . field ("rcu_ahben_tmuen" , & self . rcu_ahben_tmuen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhben { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhben {{ rcu_ahben_dma0en: {=bool:?}, rcu_ahben_dma1en: {=bool:?}, rcu_ahben_sramspen: {=bool:?}, rcu_ahben_dmamuxen: {=bool:?}, rcu_ahben_crcen: {=bool:?}, rcu_ahben_paen: {=bool:?}, rcu_ahben_pben: {=bool:?}, rcu_ahben_pcen: {=bool:?}, rcu_ahben_pden: {=bool:?}, rcu_ahben_peen: {=bool:?}, rcu_ahben_pfen: {=bool:?}, rcu_ahben_pgen: {=bool:?}, rcu_ahben_pnen: {=bool:?}, rcu_ahben_pocen: {=bool:?}, rcu_ahben_gtocen: {=bool:?}, rcu_ahben_svpwmen: {=bool:?}, rcu_ahben_tmuen: {=bool:?} }}" , self . rcu_ahben_dma0en () , self . rcu_ahben_dma1en () , self . rcu_ahben_sramspen () , self . rcu_ahben_dmamuxen () , self . rcu_ahben_crcen () , self . rcu_ahben_paen () , self . rcu_ahben_pben () , self . rcu_ahben_pcen () , self . rcu_ahben_pden () , self . rcu_ahben_peen () , self . rcu_ahben_pfen () , self . rcu_ahben_pgen () , self . rcu_ahben_pnen () , self . rcu_ahben_pocen () , self . rcu_ahben_gtocen () , self . rcu_ahben_svpwmen () , self . rcu_ahben_tmuen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhbrst (pub u32) ; impl RcuAhbrst { # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_dma0rst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_dma0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_dma1rst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_dma1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_dmamuxrst (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_dmamuxrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_crcrst (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_crcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_parst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_parst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pbrst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pbrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pcrst (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pdrst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pdrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_perst (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_perst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pfrst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pfrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pgrst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pgrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pnrst (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pnrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_pocrst (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_pocrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_gtocrst (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_gtocrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_svpwmrst (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_svpwmrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahbrst_tmurst (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahbrst_tmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for RcuAhbrst { # [inline (always)]
fn default () -> RcuAhbrst { RcuAhbrst (0) } } impl core :: fmt :: Debug for RcuAhbrst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhbrst") . field ("rcu_ahbrst_dma0rst" , & self . rcu_ahbrst_dma0rst ()) . field ("rcu_ahbrst_dma1rst" , & self . rcu_ahbrst_dma1rst ()) . field ("rcu_ahbrst_dmamuxrst" , & self . rcu_ahbrst_dmamuxrst ()) . field ("rcu_ahbrst_crcrst" , & self . rcu_ahbrst_crcrst ()) . field ("rcu_ahbrst_parst" , & self . rcu_ahbrst_parst ()) . field ("rcu_ahbrst_pbrst" , & self . rcu_ahbrst_pbrst ()) . field ("rcu_ahbrst_pcrst" , & self . rcu_ahbrst_pcrst ()) . field ("rcu_ahbrst_pdrst" , & self . rcu_ahbrst_pdrst ()) . field ("rcu_ahbrst_perst" , & self . rcu_ahbrst_perst ()) . field ("rcu_ahbrst_pfrst" , & self . rcu_ahbrst_pfrst ()) . field ("rcu_ahbrst_pgrst" , & self . rcu_ahbrst_pgrst ()) . field ("rcu_ahbrst_pnrst" , & self . rcu_ahbrst_pnrst ()) . field ("rcu_ahbrst_pocrst" , & self . rcu_ahbrst_pocrst ()) . field ("rcu_ahbrst_gtocrst" , & self . rcu_ahbrst_gtocrst ()) . field ("rcu_ahbrst_svpwmrst" , & self . rcu_ahbrst_svpwmrst ()) . field ("rcu_ahbrst_tmurst" , & self . rcu_ahbrst_tmurst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhbrst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhbrst {{ rcu_ahbrst_dma0rst: {=bool:?}, rcu_ahbrst_dma1rst: {=bool:?}, rcu_ahbrst_dmamuxrst: {=bool:?}, rcu_ahbrst_crcrst: {=bool:?}, rcu_ahbrst_parst: {=bool:?}, rcu_ahbrst_pbrst: {=bool:?}, rcu_ahbrst_pcrst: {=bool:?}, rcu_ahbrst_pdrst: {=bool:?}, rcu_ahbrst_perst: {=bool:?}, rcu_ahbrst_pfrst: {=bool:?}, rcu_ahbrst_pgrst: {=bool:?}, rcu_ahbrst_pnrst: {=bool:?}, rcu_ahbrst_pocrst: {=bool:?}, rcu_ahbrst_gtocrst: {=bool:?}, rcu_ahbrst_svpwmrst: {=bool:?}, rcu_ahbrst_tmurst: {=bool:?} }}" , self . rcu_ahbrst_dma0rst () , self . rcu_ahbrst_dma1rst () , self . rcu_ahbrst_dmamuxrst () , self . rcu_ahbrst_crcrst () , self . rcu_ahbrst_parst () , self . rcu_ahbrst_pbrst () , self . rcu_ahbrst_pcrst () , self . rcu_ahbrst_pdrst () , self . rcu_ahbrst_perst () , self . rcu_ahbrst_pfrst () , self . rcu_ahbrst_pgrst () , self . rcu_ahbrst_pnrst () , self . rcu_ahbrst_pocrst () , self . rcu_ahbrst_gtocrst () , self . rcu_ahbrst_svpwmrst () , self . rcu_ahbrst_tmurst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApb1en (pub u32) ; impl RcuApb1en { # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_cptimer0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_cptimer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_cptimer1en (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_cptimer1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_cptimerwen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_cptimerwen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_wwdgten (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_wwdgten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_uart0en (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_uart0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_uart1en (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_uart1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_uart2en (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_uart2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_uart3en (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_uart3en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_i2cen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_i2cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_cfmuen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_cfmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_pmuen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_pmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1en_dacen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1en_dacen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for RcuApb1en { # [inline (always)]
fn default () -> RcuApb1en { RcuApb1en (0) } } impl core :: fmt :: Debug for RcuApb1en { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApb1en") . field ("rcu_apb1en_cptimer0en" , & self . rcu_apb1en_cptimer0en ()) . field ("rcu_apb1en_cptimer1en" , & self . rcu_apb1en_cptimer1en ()) . field ("rcu_apb1en_cptimerwen" , & self . rcu_apb1en_cptimerwen ()) . field ("rcu_apb1en_wwdgten" , & self . rcu_apb1en_wwdgten ()) . field ("rcu_apb1en_uart0en" , & self . rcu_apb1en_uart0en ()) . field ("rcu_apb1en_uart1en" , & self . rcu_apb1en_uart1en ()) . field ("rcu_apb1en_uart2en" , & self . rcu_apb1en_uart2en ()) . field ("rcu_apb1en_uart3en" , & self . rcu_apb1en_uart3en ()) . field ("rcu_apb1en_i2cen" , & self . rcu_apb1en_i2cen ()) . field ("rcu_apb1en_cfmuen" , & self . rcu_apb1en_cfmuen ()) . field ("rcu_apb1en_pmuen" , & self . rcu_apb1en_pmuen ()) . field ("rcu_apb1en_dacen" , & self . rcu_apb1en_dacen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApb1en { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApb1en {{ rcu_apb1en_cptimer0en: {=bool:?}, rcu_apb1en_cptimer1en: {=bool:?}, rcu_apb1en_cptimerwen: {=bool:?}, rcu_apb1en_wwdgten: {=bool:?}, rcu_apb1en_uart0en: {=bool:?}, rcu_apb1en_uart1en: {=bool:?}, rcu_apb1en_uart2en: {=bool:?}, rcu_apb1en_uart3en: {=bool:?}, rcu_apb1en_i2cen: {=bool:?}, rcu_apb1en_cfmuen: {=bool:?}, rcu_apb1en_pmuen: {=bool:?}, rcu_apb1en_dacen: {=bool:?} }}" , self . rcu_apb1en_cptimer0en () , self . rcu_apb1en_cptimer1en () , self . rcu_apb1en_cptimerwen () , self . rcu_apb1en_wwdgten () , self . rcu_apb1en_uart0en () , self . rcu_apb1en_uart1en () , self . rcu_apb1en_uart2en () , self . rcu_apb1en_uart3en () , self . rcu_apb1en_i2cen () , self . rcu_apb1en_cfmuen () , self . rcu_apb1en_pmuen () , self . rcu_apb1en_dacen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApb1rst (pub u32) ; impl RcuApb1rst { # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_cptimer0rst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_cptimer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_cptimer1rst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_cptimer1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_cptimerwrst (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_cptimerwrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_wwdgtrst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_wwdgtrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_uart0rst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_uart0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_uart1rst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_uart1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_uart2rst (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_uart2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_uart3rst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_uart3rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_i2crst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_i2crst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_cfmurst (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_cfmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_pmurst (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_pmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb1rst_dacrst (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb1rst_dacrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for RcuApb1rst { # [inline (always)]
fn default () -> RcuApb1rst { RcuApb1rst (0) } } impl core :: fmt :: Debug for RcuApb1rst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApb1rst") . field ("rcu_apb1rst_cptimer0rst" , & self . rcu_apb1rst_cptimer0rst ()) . field ("rcu_apb1rst_cptimer1rst" , & self . rcu_apb1rst_cptimer1rst ()) . field ("rcu_apb1rst_cptimerwrst" , & self . rcu_apb1rst_cptimerwrst ()) . field ("rcu_apb1rst_wwdgtrst" , & self . rcu_apb1rst_wwdgtrst ()) . field ("rcu_apb1rst_uart0rst" , & self . rcu_apb1rst_uart0rst ()) . field ("rcu_apb1rst_uart1rst" , & self . rcu_apb1rst_uart1rst ()) . field ("rcu_apb1rst_uart2rst" , & self . rcu_apb1rst_uart2rst ()) . field ("rcu_apb1rst_uart3rst" , & self . rcu_apb1rst_uart3rst ()) . field ("rcu_apb1rst_i2crst" , & self . rcu_apb1rst_i2crst ()) . field ("rcu_apb1rst_cfmurst" , & self . rcu_apb1rst_cfmurst ()) . field ("rcu_apb1rst_pmurst" , & self . rcu_apb1rst_pmurst ()) . field ("rcu_apb1rst_dacrst" , & self . rcu_apb1rst_dacrst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApb1rst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApb1rst {{ rcu_apb1rst_cptimer0rst: {=bool:?}, rcu_apb1rst_cptimer1rst: {=bool:?}, rcu_apb1rst_cptimerwrst: {=bool:?}, rcu_apb1rst_wwdgtrst: {=bool:?}, rcu_apb1rst_uart0rst: {=bool:?}, rcu_apb1rst_uart1rst: {=bool:?}, rcu_apb1rst_uart2rst: {=bool:?}, rcu_apb1rst_uart3rst: {=bool:?}, rcu_apb1rst_i2crst: {=bool:?}, rcu_apb1rst_cfmurst: {=bool:?}, rcu_apb1rst_pmurst: {=bool:?}, rcu_apb1rst_dacrst: {=bool:?} }}" , self . rcu_apb1rst_cptimer0rst () , self . rcu_apb1rst_cptimer1rst () , self . rcu_apb1rst_cptimerwrst () , self . rcu_apb1rst_wwdgtrst () , self . rcu_apb1rst_uart0rst () , self . rcu_apb1rst_uart1rst () , self . rcu_apb1rst_uart2rst () , self . rcu_apb1rst_uart3rst () , self . rcu_apb1rst_i2crst () , self . rcu_apb1rst_cfmurst () , self . rcu_apb1rst_pmurst () , self . rcu_apb1rst_dacrst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApb2en (pub u32) ; impl RcuApb2en { # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_cfgen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_cfgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_cmpen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_cmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_adc0en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_adc0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_adc2en (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_adc2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_timer0en (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_timer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_spien (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_spien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_timer7en (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_timer7en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_timer1en (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_timer1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_timer2en (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_timer2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_gptimer0en (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_gptimer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_gptimer1en (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_gptimer1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_evicen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_evicen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2en_canen (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2en_canen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for RcuApb2en { # [inline (always)]
fn default () -> RcuApb2en { RcuApb2en (0) } } impl core :: fmt :: Debug for RcuApb2en { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApb2en") . field ("rcu_apb2en_cfgen" , & self . rcu_apb2en_cfgen ()) . field ("rcu_apb2en_cmpen" , & self . rcu_apb2en_cmpen ()) . field ("rcu_apb2en_adc0en" , & self . rcu_apb2en_adc0en ()) . field ("rcu_apb2en_adc2en" , & self . rcu_apb2en_adc2en ()) . field ("rcu_apb2en_timer0en" , & self . rcu_apb2en_timer0en ()) . field ("rcu_apb2en_spien" , & self . rcu_apb2en_spien ()) . field ("rcu_apb2en_timer7en" , & self . rcu_apb2en_timer7en ()) . field ("rcu_apb2en_timer1en" , & self . rcu_apb2en_timer1en ()) . field ("rcu_apb2en_timer2en" , & self . rcu_apb2en_timer2en ()) . field ("rcu_apb2en_gptimer0en" , & self . rcu_apb2en_gptimer0en ()) . field ("rcu_apb2en_gptimer1en" , & self . rcu_apb2en_gptimer1en ()) . field ("rcu_apb2en_evicen" , & self . rcu_apb2en_evicen ()) . field ("rcu_apb2en_canen" , & self . rcu_apb2en_canen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApb2en { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApb2en {{ rcu_apb2en_cfgen: {=bool:?}, rcu_apb2en_cmpen: {=bool:?}, rcu_apb2en_adc0en: {=bool:?}, rcu_apb2en_adc2en: {=bool:?}, rcu_apb2en_timer0en: {=bool:?}, rcu_apb2en_spien: {=bool:?}, rcu_apb2en_timer7en: {=bool:?}, rcu_apb2en_timer1en: {=bool:?}, rcu_apb2en_timer2en: {=bool:?}, rcu_apb2en_gptimer0en: {=bool:?}, rcu_apb2en_gptimer1en: {=bool:?}, rcu_apb2en_evicen: {=bool:?}, rcu_apb2en_canen: {=bool:?} }}" , self . rcu_apb2en_cfgen () , self . rcu_apb2en_cmpen () , self . rcu_apb2en_adc0en () , self . rcu_apb2en_adc2en () , self . rcu_apb2en_timer0en () , self . rcu_apb2en_spien () , self . rcu_apb2en_timer7en () , self . rcu_apb2en_timer1en () , self . rcu_apb2en_timer2en () , self . rcu_apb2en_gptimer0en () , self . rcu_apb2en_gptimer1en () , self . rcu_apb2en_evicen () , self . rcu_apb2en_canen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApb2rst (pub u32) ; impl RcuApb2rst { # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_cfgrst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_cfgrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_cmprst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_cmprst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_adc0rst (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_adc0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_adc2rst (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_adc2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_timer0rst (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_timer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_spirst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_spirst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_timer7rst (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_timer7rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_timer1rst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_timer1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_timer2rst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_timer2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_gptimer0rst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_gptimer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_gptimer1rst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_gptimer1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apb2rst_canrst (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apb2rst_canrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for RcuApb2rst { # [inline (always)]
fn default () -> RcuApb2rst { RcuApb2rst (0) } } impl core :: fmt :: Debug for RcuApb2rst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApb2rst") . field ("rcu_apb2rst_cfgrst" , & self . rcu_apb2rst_cfgrst ()) . field ("rcu_apb2rst_cmprst" , & self . rcu_apb2rst_cmprst ()) . field ("rcu_apb2rst_adc0rst" , & self . rcu_apb2rst_adc0rst ()) . field ("rcu_apb2rst_adc2rst" , & self . rcu_apb2rst_adc2rst ()) . field ("rcu_apb2rst_timer0rst" , & self . rcu_apb2rst_timer0rst ()) . field ("rcu_apb2rst_spirst" , & self . rcu_apb2rst_spirst ()) . field ("rcu_apb2rst_timer7rst" , & self . rcu_apb2rst_timer7rst ()) . field ("rcu_apb2rst_timer1rst" , & self . rcu_apb2rst_timer1rst ()) . field ("rcu_apb2rst_timer2rst" , & self . rcu_apb2rst_timer2rst ()) . field ("rcu_apb2rst_gptimer0rst" , & self . rcu_apb2rst_gptimer0rst ()) . field ("rcu_apb2rst_gptimer1rst" , & self . rcu_apb2rst_gptimer1rst ()) . field ("rcu_apb2rst_canrst" , & self . rcu_apb2rst_canrst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApb2rst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApb2rst {{ rcu_apb2rst_cfgrst: {=bool:?}, rcu_apb2rst_cmprst: {=bool:?}, rcu_apb2rst_adc0rst: {=bool:?}, rcu_apb2rst_adc2rst: {=bool:?}, rcu_apb2rst_timer0rst: {=bool:?}, rcu_apb2rst_spirst: {=bool:?}, rcu_apb2rst_timer7rst: {=bool:?}, rcu_apb2rst_timer1rst: {=bool:?}, rcu_apb2rst_timer2rst: {=bool:?}, rcu_apb2rst_gptimer0rst: {=bool:?}, rcu_apb2rst_gptimer1rst: {=bool:?}, rcu_apb2rst_canrst: {=bool:?} }}" , self . rcu_apb2rst_cfgrst () , self . rcu_apb2rst_cmprst () , self . rcu_apb2rst_adc0rst () , self . rcu_apb2rst_adc2rst () , self . rcu_apb2rst_timer0rst () , self . rcu_apb2rst_spirst () , self . rcu_apb2rst_timer7rst () , self . rcu_apb2rst_timer1rst () , self . rcu_apb2rst_timer2rst () , self . rcu_apb2rst_gptimer0rst () , self . rcu_apb2rst_gptimer1rst () , self . rcu_apb2rst_canrst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCfg0 (pub u32) ; impl RcuCfg0 { # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_scs (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_scs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_scss (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_scss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ahbpsc (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ahbpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_apb1psc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_apb1psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 8usize)) | (((val as u32) & 0x07) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_apb2psc (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_apb2psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 11usize)) | (((val as u32) & 0x07) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_pllsel (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_cfg0_pllsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_pllmf (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x7f ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_pllmf (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 17usize)) | (((val as u32) & 0x7f) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ckoutsel (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ckoutsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 24usize)) | (((val as u32) & 0x07) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ckoutdiv (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ckoutdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 28usize)) | (((val as u32) & 0x07) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_plldv (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_cfg0_plldv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for RcuCfg0 { # [inline (always)]
fn default () -> RcuCfg0 { RcuCfg0 (0) } } impl core :: fmt :: Debug for RcuCfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCfg0") . field ("rcu_cfg0_scs" , & self . rcu_cfg0_scs ()) . field ("rcu_cfg0_scss" , & self . rcu_cfg0_scss ()) . field ("rcu_cfg0_ahbpsc" , & self . rcu_cfg0_ahbpsc ()) . field ("rcu_cfg0_apb1psc" , & self . rcu_cfg0_apb1psc ()) . field ("rcu_cfg0_apb2psc" , & self . rcu_cfg0_apb2psc ()) . field ("rcu_cfg0_pllsel" , & self . rcu_cfg0_pllsel ()) . field ("rcu_cfg0_pllmf" , & self . rcu_cfg0_pllmf ()) . field ("rcu_cfg0_ckoutsel" , & self . rcu_cfg0_ckoutsel ()) . field ("rcu_cfg0_ckoutdiv" , & self . rcu_cfg0_ckoutdiv ()) . field ("rcu_cfg0_plldv" , & self . rcu_cfg0_plldv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCfg0 {{ rcu_cfg0_scs: {=u8:?}, rcu_cfg0_scss: {=u8:?}, rcu_cfg0_ahbpsc: {=u8:?}, rcu_cfg0_apb1psc: {=u8:?}, rcu_cfg0_apb2psc: {=u8:?}, rcu_cfg0_pllsel: {=bool:?}, rcu_cfg0_pllmf: {=u8:?}, rcu_cfg0_ckoutsel: {=u8:?}, rcu_cfg0_ckoutdiv: {=u8:?}, rcu_cfg0_plldv: {=bool:?} }}" , self . rcu_cfg0_scs () , self . rcu_cfg0_scss () , self . rcu_cfg0_ahbpsc () , self . rcu_cfg0_apb1psc () , self . rcu_cfg0_apb2psc () , self . rcu_cfg0_pllsel () , self . rcu_cfg0_pllmf () , self . rcu_cfg0_ckoutsel () , self . rcu_cfg0_ckoutdiv () , self . rcu_cfg0_plldv ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCfg1 (pub u32) ; impl RcuCfg1 { # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_predv (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_predv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } } impl Default for RcuCfg1 { # [inline (always)]
fn default () -> RcuCfg1 { RcuCfg1 (0) } } impl core :: fmt :: Debug for RcuCfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCfg1") . field ("rcu_cfg1_predv" , & self . rcu_cfg1_predv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCfg1 {{ rcu_cfg1_predv: {=u8:?} }}" , self . rcu_cfg1_predv ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCfg2 (pub u32) ; impl RcuCfg2 { # [must_use]
# [inline (always)]
pub const fn rcu_cfg2_i2csel (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg2_i2csel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg2_adcsel (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg2_adcsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 25usize)) | (((val as u32) & 0x03) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg2_adcpsc (& self) -> u8 { let val = (self . 0 >> 27usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg2_adcpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 27usize)) | (((val as u32) & 0x1f) << 27usize) ; } } impl Default for RcuCfg2 { # [inline (always)]
fn default () -> RcuCfg2 { RcuCfg2 (0) } } impl core :: fmt :: Debug for RcuCfg2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCfg2") . field ("rcu_cfg2_i2csel" , & self . rcu_cfg2_i2csel ()) . field ("rcu_cfg2_adcsel" , & self . rcu_cfg2_adcsel ()) . field ("rcu_cfg2_adcpsc" , & self . rcu_cfg2_adcpsc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCfg2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCfg2 {{ rcu_cfg2_i2csel: {=u8:?}, rcu_cfg2_adcsel: {=u8:?}, rcu_cfg2_adcpsc: {=u8:?} }}" , self . rcu_cfg2_i2csel () , self . rcu_cfg2_adcsel () , self . rcu_cfg2_adcpsc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCtl (pub u32) ; impl RcuCtl { # [must_use]
# [inline (always)]
pub const fn rcu_ctl_irc32men (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_irc32men (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_irc32mstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_irc32mstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_irc32madj (& self) -> u8 { let val = (self . 0 >> 3usize) & 0x1f ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl_irc32madj (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 3usize)) | (((val as u32) & 0x1f) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_irc32mcalib (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl_irc32mcalib (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_hxtalen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_hxtalen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_hxtarst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_hxtarst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_hxtalstb (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_hxtalstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_hxtalbps (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_hxtalbps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_ckmen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_ckmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_pllmen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_pllmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_hxtalscal (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_hxtalscal (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_pllen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_pllen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl_pllstb (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl_pllstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } } impl Default for RcuCtl { # [inline (always)]
fn default () -> RcuCtl { RcuCtl (0) } } impl core :: fmt :: Debug for RcuCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCtl") . field ("rcu_ctl_irc32men" , & self . rcu_ctl_irc32men ()) . field ("rcu_ctl_irc32mstb" , & self . rcu_ctl_irc32mstb ()) . field ("rcu_ctl_irc32madj" , & self . rcu_ctl_irc32madj ()) . field ("rcu_ctl_irc32mcalib" , & self . rcu_ctl_irc32mcalib ()) . field ("rcu_ctl_hxtalen" , & self . rcu_ctl_hxtalen ()) . field ("rcu_ctl_hxtarst" , & self . rcu_ctl_hxtarst ()) . field ("rcu_ctl_hxtalstb" , & self . rcu_ctl_hxtalstb ()) . field ("rcu_ctl_hxtalbps" , & self . rcu_ctl_hxtalbps ()) . field ("rcu_ctl_ckmen" , & self . rcu_ctl_ckmen ()) . field ("rcu_ctl_pllmen" , & self . rcu_ctl_pllmen ()) . field ("rcu_ctl_hxtalscal" , & self . rcu_ctl_hxtalscal ()) . field ("rcu_ctl_pllen" , & self . rcu_ctl_pllen ()) . field ("rcu_ctl_pllstb" , & self . rcu_ctl_pllstb ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCtl {{ rcu_ctl_irc32men: {=bool:?}, rcu_ctl_irc32mstb: {=bool:?}, rcu_ctl_irc32madj: {=u8:?}, rcu_ctl_irc32mcalib: {=u8:?}, rcu_ctl_hxtalen: {=bool:?}, rcu_ctl_hxtarst: {=bool:?}, rcu_ctl_hxtalstb: {=bool:?}, rcu_ctl_hxtalbps: {=bool:?}, rcu_ctl_ckmen: {=bool:?}, rcu_ctl_pllmen: {=bool:?}, rcu_ctl_hxtalscal: {=bool:?}, rcu_ctl_pllen: {=bool:?}, rcu_ctl_pllstb: {=bool:?} }}" , self . rcu_ctl_irc32men () , self . rcu_ctl_irc32mstb () , self . rcu_ctl_irc32madj () , self . rcu_ctl_irc32mcalib () , self . rcu_ctl_hxtalen () , self . rcu_ctl_hxtarst () , self . rcu_ctl_hxtalstb () , self . rcu_ctl_hxtalbps () , self . rcu_ctl_ckmen () , self . rcu_ctl_pllmen () , self . rcu_ctl_hxtalscal () , self . rcu_ctl_pllen () , self . rcu_ctl_pllstb ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuInt (pub u32) ; impl RcuInt { # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32kstbif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32kstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32mstbif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32mstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_hxtalstbif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_hxtalstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_pllstbif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_pllstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_pllmif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_pllmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_ckmif (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_ckmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32kstbie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32kstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32mstbie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32mstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_hxtalstbie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_hxtalstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_pllstbie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_pllstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_pllmie (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_pllmie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32kstbic (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32kstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32mstbic (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32mstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_hxtalstbic (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_hxtalstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_pllstbic (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_pllstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_pllmic (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_pllmic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_ckmic (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_ckmic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RcuInt { # [inline (always)]
fn default () -> RcuInt { RcuInt (0) } } impl core :: fmt :: Debug for RcuInt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuInt") . field ("rcu_int_irc32kstbif" , & self . rcu_int_irc32kstbif ()) . field ("rcu_int_irc32mstbif" , & self . rcu_int_irc32mstbif ()) . field ("rcu_int_hxtalstbif" , & self . rcu_int_hxtalstbif ()) . field ("rcu_int_pllstbif" , & self . rcu_int_pllstbif ()) . field ("rcu_int_pllmif" , & self . rcu_int_pllmif ()) . field ("rcu_int_ckmif" , & self . rcu_int_ckmif ()) . field ("rcu_int_irc32kstbie" , & self . rcu_int_irc32kstbie ()) . field ("rcu_int_irc32mstbie" , & self . rcu_int_irc32mstbie ()) . field ("rcu_int_hxtalstbie" , & self . rcu_int_hxtalstbie ()) . field ("rcu_int_pllstbie" , & self . rcu_int_pllstbie ()) . field ("rcu_int_pllmie" , & self . rcu_int_pllmie ()) . field ("rcu_int_irc32kstbic" , & self . rcu_int_irc32kstbic ()) . field ("rcu_int_irc32mstbic" , & self . rcu_int_irc32mstbic ()) . field ("rcu_int_hxtalstbic" , & self . rcu_int_hxtalstbic ()) . field ("rcu_int_pllstbic" , & self . rcu_int_pllstbic ()) . field ("rcu_int_pllmic" , & self . rcu_int_pllmic ()) . field ("rcu_int_ckmic" , & self . rcu_int_ckmic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuInt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuInt {{ rcu_int_irc32kstbif: {=bool:?}, rcu_int_irc32mstbif: {=bool:?}, rcu_int_hxtalstbif: {=bool:?}, rcu_int_pllstbif: {=bool:?}, rcu_int_pllmif: {=bool:?}, rcu_int_ckmif: {=bool:?}, rcu_int_irc32kstbie: {=bool:?}, rcu_int_irc32mstbie: {=bool:?}, rcu_int_hxtalstbie: {=bool:?}, rcu_int_pllstbie: {=bool:?}, rcu_int_pllmie: {=bool:?}, rcu_int_irc32kstbic: {=bool:?}, rcu_int_irc32mstbic: {=bool:?}, rcu_int_hxtalstbic: {=bool:?}, rcu_int_pllstbic: {=bool:?}, rcu_int_pllmic: {=bool:?}, rcu_int_ckmic: {=bool:?} }}" , self . rcu_int_irc32kstbif () , self . rcu_int_irc32mstbif () , self . rcu_int_hxtalstbif () , self . rcu_int_pllstbif () , self . rcu_int_pllmif () , self . rcu_int_ckmif () , self . rcu_int_irc32kstbie () , self . rcu_int_irc32mstbie () , self . rcu_int_hxtalstbie () , self . rcu_int_pllstbie () , self . rcu_int_pllmie () , self . rcu_int_irc32kstbic () , self . rcu_int_irc32mstbic () , self . rcu_int_hxtalstbic () , self . rcu_int_pllstbic () , self . rcu_int_pllmic () , self . rcu_int_ckmic ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuRstsck (pub u32) ; impl RcuRstsck { # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_irc32ken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_irc32ken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_irc32kstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_irc32kstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lockuprsten (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lockuprsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lohrsten (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lohrsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_loprsten (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_loprsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lvd0rstf (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lvd0rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lockuprstf (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lockuprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lvd1rstf (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lvd1rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lvd2rstf (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lvd2rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lohrstf (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lohrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_loprstf (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_loprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_v11rstf (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_v11rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_rstfc (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_rstfc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_oblrstf (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_oblrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_eprstf (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_eprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_porrstf (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_porrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_swrstf (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_swrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_fwdgtrstf (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_fwdgtrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_wwdgtrstf (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_wwdgtrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lprstf (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for RcuRstsck { # [inline (always)]
fn default () -> RcuRstsck { RcuRstsck (0) } } impl core :: fmt :: Debug for RcuRstsck { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuRstsck") . field ("rcu_rstsck_irc32ken" , & self . rcu_rstsck_irc32ken ()) . field ("rcu_rstsck_irc32kstb" , & self . rcu_rstsck_irc32kstb ()) . field ("rcu_rstsck_lockuprsten" , & self . rcu_rstsck_lockuprsten ()) . field ("rcu_rstsck_lohrsten" , & self . rcu_rstsck_lohrsten ()) . field ("rcu_rstsck_loprsten" , & self . rcu_rstsck_loprsten ()) . field ("rcu_rstsck_lvd0rstf" , & self . rcu_rstsck_lvd0rstf ()) . field ("rcu_rstsck_lockuprstf" , & self . rcu_rstsck_lockuprstf ()) . field ("rcu_rstsck_lvd1rstf" , & self . rcu_rstsck_lvd1rstf ()) . field ("rcu_rstsck_lvd2rstf" , & self . rcu_rstsck_lvd2rstf ()) . field ("rcu_rstsck_lohrstf" , & self . rcu_rstsck_lohrstf ()) . field ("rcu_rstsck_loprstf" , & self . rcu_rstsck_loprstf ()) . field ("rcu_rstsck_v11rstf" , & self . rcu_rstsck_v11rstf ()) . field ("rcu_rstsck_rstfc" , & self . rcu_rstsck_rstfc ()) . field ("rcu_rstsck_oblrstf" , & self . rcu_rstsck_oblrstf ()) . field ("rcu_rstsck_eprstf" , & self . rcu_rstsck_eprstf ()) . field ("rcu_rstsck_porrstf" , & self . rcu_rstsck_porrstf ()) . field ("rcu_rstsck_swrstf" , & self . rcu_rstsck_swrstf ()) . field ("rcu_rstsck_fwdgtrstf" , & self . rcu_rstsck_fwdgtrstf ()) . field ("rcu_rstsck_wwdgtrstf" , & self . rcu_rstsck_wwdgtrstf ()) . field ("rcu_rstsck_lprstf" , & self . rcu_rstsck_lprstf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuRstsck { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuRstsck {{ rcu_rstsck_irc32ken: {=bool:?}, rcu_rstsck_irc32kstb: {=bool:?}, rcu_rstsck_lockuprsten: {=bool:?}, rcu_rstsck_lohrsten: {=bool:?}, rcu_rstsck_loprsten: {=bool:?}, rcu_rstsck_lvd0rstf: {=bool:?}, rcu_rstsck_lockuprstf: {=bool:?}, rcu_rstsck_lvd1rstf: {=bool:?}, rcu_rstsck_lvd2rstf: {=bool:?}, rcu_rstsck_lohrstf: {=bool:?}, rcu_rstsck_loprstf: {=bool:?}, rcu_rstsck_v11rstf: {=bool:?}, rcu_rstsck_rstfc: {=bool:?}, rcu_rstsck_oblrstf: {=bool:?}, rcu_rstsck_eprstf: {=bool:?}, rcu_rstsck_porrstf: {=bool:?}, rcu_rstsck_swrstf: {=bool:?}, rcu_rstsck_fwdgtrstf: {=bool:?}, rcu_rstsck_wwdgtrstf: {=bool:?}, rcu_rstsck_lprstf: {=bool:?} }}" , self . rcu_rstsck_irc32ken () , self . rcu_rstsck_irc32kstb () , self . rcu_rstsck_lockuprsten () , self . rcu_rstsck_lohrsten () , self . rcu_rstsck_loprsten () , self . rcu_rstsck_lvd0rstf () , self . rcu_rstsck_lockuprstf () , self . rcu_rstsck_lvd1rstf () , self . rcu_rstsck_lvd2rstf () , self . rcu_rstsck_lohrstf () , self . rcu_rstsck_loprstf () , self . rcu_rstsck_v11rstf () , self . rcu_rstsck_rstfc () , self . rcu_rstsck_oblrstf () , self . rcu_rstsck_eprstf () , self . rcu_rstsck_porrstf () , self . rcu_rstsck_swrstf () , self . rcu_rstsck_fwdgtrstf () , self . rcu_rstsck_wwdgtrstf () , self . rcu_rstsck_lprstf ()) } } }