#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Reset and clock unit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rcu { ptr : * mut u8 } unsafe impl Send for Rcu { } unsafe impl Sync for Rcu { } impl Rcu { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Configuration register 0"]
# [inline (always)]
pub const fn cfg0 (self) -> crate :: common :: Reg < regs :: Cfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Interrupt register"]
# [inline (always)]
pub const fn int (self) -> crate :: common :: Reg < regs :: Int , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "APB2 reset register"]
# [inline (always)]
pub const fn apb2rst (self) -> crate :: common :: Reg < regs :: Apb2rst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "APB1 reset register"]
# [inline (always)]
pub const fn apb1rst (self) -> crate :: common :: Reg < regs :: Apb1rst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "AHB enable register"]
# [inline (always)]
pub const fn ahben (self) -> crate :: common :: Reg < regs :: Ahben , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "APB2 enable register"]
# [inline (always)]
pub const fn apb2en (self) -> crate :: common :: Reg < regs :: Apb2en , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "APB1 enable register"]
# [inline (always)]
pub const fn apb1en (self) -> crate :: common :: Reg < regs :: Apb1en , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Reset source/clock register"]
# [inline (always)]
pub const fn rstsck (self) -> crate :: common :: Reg < regs :: Rstsck , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "AHB reset register"]
# [inline (always)]
pub const fn ahbrst (self) -> crate :: common :: Reg < regs :: Ahbrst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Configuration register 1"]
# [inline (always)]
pub const fn cfg1 (self) -> crate :: common :: Reg < regs :: Cfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Configuration register 2"]
# [inline (always)]
pub const fn cfg2 (self) -> crate :: common :: Reg < regs :: Cfg2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } } pub mod regs { # [doc = "AHB enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ahben (pub u32) ; impl Ahben { # [doc = "DMA0 clock enable"]
# [inline (always)]
pub const fn dma0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "DMA0 clock enable"]
# [inline (always)]
pub fn set_dma0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "DMA1 clock enable"]
# [inline (always)]
pub const fn dma1en (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "DMA1 clock enable"]
# [inline (always)]
pub fn set_dma1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "SRAM interface clock enable"]
# [inline (always)]
pub const fn sramspen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "SRAM interface clock enable"]
# [inline (always)]
pub fn set_sramspen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "DMAMUX clock enable"]
# [inline (always)]
pub const fn dmamuxen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "DMAMUX clock enable"]
# [inline (always)]
pub fn set_dmamuxen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "CRC clock enable"]
# [inline (always)]
pub const fn crcen (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "CRC clock enable"]
# [inline (always)]
pub fn set_crcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "GPIO port A clock enable"]
# [inline (always)]
pub const fn paen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "GPIO port A clock enable"]
# [inline (always)]
pub fn set_paen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "GPIO port B clock enable"]
# [inline (always)]
pub const fn pben (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "GPIO port B clock enable"]
# [inline (always)]
pub fn set_pben (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "GPIO port C clock enable"]
# [inline (always)]
pub const fn pcen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "GPIO port C clock enable"]
# [inline (always)]
pub fn set_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "GPIO port D clock enable"]
# [inline (always)]
pub const fn pden (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "GPIO port D clock enable"]
# [inline (always)]
pub fn set_pden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "GPIO port E clock enable"]
# [inline (always)]
pub const fn peen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "GPIO port E clock enable"]
# [inline (always)]
pub fn set_peen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "GPIO port F clock enable"]
# [inline (always)]
pub const fn pfen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "GPIO port F clock enable"]
# [inline (always)]
pub fn set_pfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "GPIO port G clock enable"]
# [inline (always)]
pub const fn pgen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "GPIO port G clock enable"]
# [inline (always)]
pub fn set_pgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "GPIO port N clock enable"]
# [inline (always)]
pub const fn pnen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "GPIO port N clock enable"]
# [inline (always)]
pub fn set_pnen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "POC clock enable"]
# [inline (always)]
pub const fn pocen (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "POC clock enable"]
# [inline (always)]
pub fn set_pocen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "GTOC clock enable"]
# [inline (always)]
pub const fn gtocen (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "GTOC clock enable"]
# [inline (always)]
pub fn set_gtocen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "SVPWM clock enable"]
# [inline (always)]
pub const fn svpwmen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "SVPWM clock enable"]
# [inline (always)]
pub fn set_svpwmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "TMU clock enable"]
# [inline (always)]
pub const fn tmuen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "TMU clock enable"]
# [inline (always)]
pub fn set_tmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for Ahben { # [inline (always)]
fn default () -> Ahben { Ahben (0) } } impl core :: fmt :: Debug for Ahben { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ahben") . field ("dma0en" , & self . dma0en ()) . field ("dma1en" , & self . dma1en ()) . field ("sramspen" , & self . sramspen ()) . field ("dmamuxen" , & self . dmamuxen ()) . field ("crcen" , & self . crcen ()) . field ("paen" , & self . paen ()) . field ("pben" , & self . pben ()) . field ("pcen" , & self . pcen ()) . field ("pden" , & self . pden ()) . field ("peen" , & self . peen ()) . field ("pfen" , & self . pfen ()) . field ("pgen" , & self . pgen ()) . field ("pnen" , & self . pnen ()) . field ("pocen" , & self . pocen ()) . field ("gtocen" , & self . gtocen ()) . field ("svpwmen" , & self . svpwmen ()) . field ("tmuen" , & self . tmuen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ahben { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ahben {{ dma0en: {=bool:?}, dma1en: {=bool:?}, sramspen: {=bool:?}, dmamuxen: {=bool:?}, crcen: {=bool:?}, paen: {=bool:?}, pben: {=bool:?}, pcen: {=bool:?}, pden: {=bool:?}, peen: {=bool:?}, pfen: {=bool:?}, pgen: {=bool:?}, pnen: {=bool:?}, pocen: {=bool:?}, gtocen: {=bool:?}, svpwmen: {=bool:?}, tmuen: {=bool:?} }}" , self . dma0en () , self . dma1en () , self . sramspen () , self . dmamuxen () , self . crcen () , self . paen () , self . pben () , self . pcen () , self . pden () , self . peen () , self . pfen () , self . pgen () , self . pnen () , self . pocen () , self . gtocen () , self . svpwmen () , self . tmuen ()) } } # [doc = "AHB reset register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ahbrst (pub u32) ; impl Ahbrst { # [doc = "DMA0 reset"]
# [inline (always)]
pub const fn dma0rst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "DMA0 reset"]
# [inline (always)]
pub fn set_dma0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "DMA1 reset"]
# [inline (always)]
pub const fn dma1rst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "DMA1 reset"]
# [inline (always)]
pub fn set_dma1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "DMAMUX reset"]
# [inline (always)]
pub const fn dmamuxrst (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "DMAMUX reset"]
# [inline (always)]
pub fn set_dmamuxrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "CRC reset"]
# [inline (always)]
pub const fn crcrst (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "CRC reset"]
# [inline (always)]
pub fn set_crcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "GPIO port A reset"]
# [inline (always)]
pub const fn parst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "GPIO port A reset"]
# [inline (always)]
pub fn set_parst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "GPIO port B reset"]
# [inline (always)]
pub const fn pbrst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "GPIO port B reset"]
# [inline (always)]
pub fn set_pbrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "GPIO port C reset"]
# [inline (always)]
pub const fn pcrst (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "GPIO port C reset"]
# [inline (always)]
pub fn set_pcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "GPIO port D reset"]
# [inline (always)]
pub const fn pdrst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "GPIO port D reset"]
# [inline (always)]
pub fn set_pdrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "GPIO port E reset"]
# [inline (always)]
pub const fn perst (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "GPIO port E reset"]
# [inline (always)]
pub fn set_perst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "GPIO port F reset"]
# [inline (always)]
pub const fn pfrst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "GPIO port F reset"]
# [inline (always)]
pub fn set_pfrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "GPIO port G reset"]
# [inline (always)]
pub const fn pgrst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "GPIO port G reset"]
# [inline (always)]
pub fn set_pgrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "GPIO port N reset"]
# [inline (always)]
pub const fn pnrst (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "GPIO port N reset"]
# [inline (always)]
pub fn set_pnrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "POC reset"]
# [inline (always)]
pub const fn pocrst (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "POC reset"]
# [inline (always)]
pub fn set_pocrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "GTOC reset"]
# [inline (always)]
pub const fn gtocrst (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "GTOC reset"]
# [inline (always)]
pub fn set_gtocrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "SVPWM reset"]
# [inline (always)]
pub const fn svpwmrst (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "SVPWM reset"]
# [inline (always)]
pub fn set_svpwmrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "TMU reset"]
# [inline (always)]
pub const fn tmurst (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "TMU reset"]
# [inline (always)]
pub fn set_tmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for Ahbrst { # [inline (always)]
fn default () -> Ahbrst { Ahbrst (0) } } impl core :: fmt :: Debug for Ahbrst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ahbrst") . field ("dma0rst" , & self . dma0rst ()) . field ("dma1rst" , & self . dma1rst ()) . field ("dmamuxrst" , & self . dmamuxrst ()) . field ("crcrst" , & self . crcrst ()) . field ("parst" , & self . parst ()) . field ("pbrst" , & self . pbrst ()) . field ("pcrst" , & self . pcrst ()) . field ("pdrst" , & self . pdrst ()) . field ("perst" , & self . perst ()) . field ("pfrst" , & self . pfrst ()) . field ("pgrst" , & self . pgrst ()) . field ("pnrst" , & self . pnrst ()) . field ("pocrst" , & self . pocrst ()) . field ("gtocrst" , & self . gtocrst ()) . field ("svpwmrst" , & self . svpwmrst ()) . field ("tmurst" , & self . tmurst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ahbrst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ahbrst {{ dma0rst: {=bool:?}, dma1rst: {=bool:?}, dmamuxrst: {=bool:?}, crcrst: {=bool:?}, parst: {=bool:?}, pbrst: {=bool:?}, pcrst: {=bool:?}, pdrst: {=bool:?}, perst: {=bool:?}, pfrst: {=bool:?}, pgrst: {=bool:?}, pnrst: {=bool:?}, pocrst: {=bool:?}, gtocrst: {=bool:?}, svpwmrst: {=bool:?}, tmurst: {=bool:?} }}" , self . dma0rst () , self . dma1rst () , self . dmamuxrst () , self . crcrst () , self . parst () , self . pbrst () , self . pcrst () , self . pdrst () , self . perst () , self . pfrst () , self . pgrst () , self . pnrst () , self . pocrst () , self . gtocrst () , self . svpwmrst () , self . tmurst ()) } } # [doc = "APB1 enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Apb1en (pub u32) ; impl Apb1en { # [doc = "CPTIMER0 timer clock enable"]
# [inline (always)]
pub const fn cptimer0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "CPTIMER0 timer clock enable"]
# [inline (always)]
pub fn set_cptimer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "CPTIMER1 timer clock enable"]
# [inline (always)]
pub const fn cptimer1en (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "CPTIMER1 timer clock enable"]
# [inline (always)]
pub fn set_cptimer1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "CPTIMERW timer clock enable"]
# [inline (always)]
pub const fn cptimerwen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "CPTIMERW timer clock enable"]
# [inline (always)]
pub fn set_cptimerwen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Window watchdog timer clock enable"]
# [inline (always)]
pub const fn wwdgten (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Window watchdog timer clock enable"]
# [inline (always)]
pub fn set_wwdgten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "UART0 clock enable"]
# [inline (always)]
pub const fn uart0en (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "UART0 clock enable"]
# [inline (always)]
pub fn set_uart0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "UART1 clock enable"]
# [inline (always)]
pub const fn uart1en (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "UART1 clock enable"]
# [inline (always)]
pub fn set_uart1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "UART2 clock enable"]
# [inline (always)]
pub const fn uart2en (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "UART2 clock enable"]
# [inline (always)]
pub fn set_uart2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "UART3 clock enable"]
# [inline (always)]
pub const fn uart3en (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "UART3 clock enable"]
# [inline (always)]
pub fn set_uart3en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "I2C clock enable"]
# [inline (always)]
pub const fn i2cen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "I2C clock enable"]
# [inline (always)]
pub fn set_i2cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "CFMU clock enable"]
# [inline (always)]
pub const fn cfmuen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "CFMU clock enable"]
# [inline (always)]
pub fn set_cfmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Power interface clock enable"]
# [inline (always)]
pub const fn pmuen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Power interface clock enable"]
# [inline (always)]
pub fn set_pmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "DAC clock enable"]
# [inline (always)]
pub const fn dacen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "DAC clock enable"]
# [inline (always)]
pub fn set_dacen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for Apb1en { # [inline (always)]
fn default () -> Apb1en { Apb1en (0) } } impl core :: fmt :: Debug for Apb1en { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Apb1en") . field ("cptimer0en" , & self . cptimer0en ()) . field ("cptimer1en" , & self . cptimer1en ()) . field ("cptimerwen" , & self . cptimerwen ()) . field ("wwdgten" , & self . wwdgten ()) . field ("uart0en" , & self . uart0en ()) . field ("uart1en" , & self . uart1en ()) . field ("uart2en" , & self . uart2en ()) . field ("uart3en" , & self . uart3en ()) . field ("i2cen" , & self . i2cen ()) . field ("cfmuen" , & self . cfmuen ()) . field ("pmuen" , & self . pmuen ()) . field ("dacen" , & self . dacen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Apb1en { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Apb1en {{ cptimer0en: {=bool:?}, cptimer1en: {=bool:?}, cptimerwen: {=bool:?}, wwdgten: {=bool:?}, uart0en: {=bool:?}, uart1en: {=bool:?}, uart2en: {=bool:?}, uart3en: {=bool:?}, i2cen: {=bool:?}, cfmuen: {=bool:?}, pmuen: {=bool:?}, dacen: {=bool:?} }}" , self . cptimer0en () , self . cptimer1en () , self . cptimerwen () , self . wwdgten () , self . uart0en () , self . uart1en () , self . uart2en () , self . uart3en () , self . i2cen () , self . cfmuen () , self . pmuen () , self . dacen ()) } } # [doc = "APB1 reset register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Apb1rst (pub u32) ; impl Apb1rst { # [doc = "CPTIMER0 timer reset"]
# [inline (always)]
pub const fn cptimer0rst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "CPTIMER0 timer reset"]
# [inline (always)]
pub fn set_cptimer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "CPTIMER1 timer reset"]
# [inline (always)]
pub const fn cptimer1rst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "CPTIMER1 timer reset"]
# [inline (always)]
pub fn set_cptimer1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "CPTIMERW timer reset"]
# [inline (always)]
pub const fn cptimerwrst (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "CPTIMERW timer reset"]
# [inline (always)]
pub fn set_cptimerwrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Window watchdog timer reset"]
# [inline (always)]
pub const fn wwdgtrst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Window watchdog timer reset"]
# [inline (always)]
pub fn set_wwdgtrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "UART0 reset"]
# [inline (always)]
pub const fn uart0rst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "UART0 reset"]
# [inline (always)]
pub fn set_uart0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "UART1 reset"]
# [inline (always)]
pub const fn uart1rst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "UART1 reset"]
# [inline (always)]
pub fn set_uart1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "UART2 reset"]
# [inline (always)]
pub const fn uart2rst (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "UART2 reset"]
# [inline (always)]
pub fn set_uart2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "UART3 reset"]
# [inline (always)]
pub const fn uart3rst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "UART3 reset"]
# [inline (always)]
pub fn set_uart3rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "I2C reset"]
# [inline (always)]
pub const fn i2crst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "I2C reset"]
# [inline (always)]
pub fn set_i2crst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "CFMU reset"]
# [inline (always)]
pub const fn cfmurst (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "CFMU reset"]
# [inline (always)]
pub fn set_cfmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Power control reset"]
# [inline (always)]
pub const fn pmurst (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Power control reset"]
# [inline (always)]
pub fn set_pmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "DAC reset"]
# [inline (always)]
pub const fn dacrst (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "DAC reset"]
# [inline (always)]
pub fn set_dacrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } } impl Default for Apb1rst { # [inline (always)]
fn default () -> Apb1rst { Apb1rst (0) } } impl core :: fmt :: Debug for Apb1rst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Apb1rst") . field ("cptimer0rst" , & self . cptimer0rst ()) . field ("cptimer1rst" , & self . cptimer1rst ()) . field ("cptimerwrst" , & self . cptimerwrst ()) . field ("wwdgtrst" , & self . wwdgtrst ()) . field ("uart0rst" , & self . uart0rst ()) . field ("uart1rst" , & self . uart1rst ()) . field ("uart2rst" , & self . uart2rst ()) . field ("uart3rst" , & self . uart3rst ()) . field ("i2crst" , & self . i2crst ()) . field ("cfmurst" , & self . cfmurst ()) . field ("pmurst" , & self . pmurst ()) . field ("dacrst" , & self . dacrst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Apb1rst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Apb1rst {{ cptimer0rst: {=bool:?}, cptimer1rst: {=bool:?}, cptimerwrst: {=bool:?}, wwdgtrst: {=bool:?}, uart0rst: {=bool:?}, uart1rst: {=bool:?}, uart2rst: {=bool:?}, uart3rst: {=bool:?}, i2crst: {=bool:?}, cfmurst: {=bool:?}, pmurst: {=bool:?}, dacrst: {=bool:?} }}" , self . cptimer0rst () , self . cptimer1rst () , self . cptimerwrst () , self . wwdgtrst () , self . uart0rst () , self . uart1rst () , self . uart2rst () , self . uart3rst () , self . i2crst () , self . cfmurst () , self . pmurst () , self . dacrst ()) } } # [doc = "APB2 enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Apb2en (pub u32) ; impl Apb2en { # [doc = "System configuration clock enable"]
# [inline (always)]
pub const fn cfgen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "System configuration clock enable"]
# [inline (always)]
pub fn set_cfgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Comparator clock enable"]
# [inline (always)]
pub const fn cmpen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Comparator clock enable"]
# [inline (always)]
pub fn set_cmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "ADC interface clock enable"]
# [inline (always)]
pub const fn adc0en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "ADC interface clock enable"]
# [inline (always)]
pub fn set_adc0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "ADC2 interface clock enable"]
# [inline (always)]
pub const fn adc2en (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "ADC2 interface clock enable"]
# [inline (always)]
pub fn set_adc2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "TIMER0 timer clock enable"]
# [inline (always)]
pub const fn timer0en (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "TIMER0 timer clock enable"]
# [inline (always)]
pub fn set_timer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "SPI clock enable"]
# [inline (always)]
pub const fn spien (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "SPI clock enable"]
# [inline (always)]
pub fn set_spien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "TIMER7 timer clock enable"]
# [inline (always)]
pub const fn timer7en (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "TIMER7 timer clock enable"]
# [inline (always)]
pub fn set_timer7en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "TIMER1 timer clock enable"]
# [inline (always)]
pub const fn timer1en (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "TIMER1 timer clock enable"]
# [inline (always)]
pub fn set_timer1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TIMER2 timer clock enable"]
# [inline (always)]
pub const fn timer2en (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "TIMER2 timer clock enable"]
# [inline (always)]
pub fn set_timer2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "GPTIMER0 timer clock enable"]
# [inline (always)]
pub const fn gptimer0en (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "GPTIMER0 timer clock enable"]
# [inline (always)]
pub fn set_gptimer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "GPTIMER1 timer clock enable"]
# [inline (always)]
pub const fn gptimer1en (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "GPTIMER1 timer clock enable"]
# [inline (always)]
pub fn set_gptimer1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "EVIC clock enable"]
# [inline (always)]
pub const fn evicen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "EVIC clock enable"]
# [inline (always)]
pub fn set_evicen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "CAN clock enable"]
# [inline (always)]
pub const fn canen (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "CAN clock enable"]
# [inline (always)]
pub fn set_canen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for Apb2en { # [inline (always)]
fn default () -> Apb2en { Apb2en (0) } } impl core :: fmt :: Debug for Apb2en { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Apb2en") . field ("cfgen" , & self . cfgen ()) . field ("cmpen" , & self . cmpen ()) . field ("adc0en" , & self . adc0en ()) . field ("adc2en" , & self . adc2en ()) . field ("timer0en" , & self . timer0en ()) . field ("spien" , & self . spien ()) . field ("timer7en" , & self . timer7en ()) . field ("timer1en" , & self . timer1en ()) . field ("timer2en" , & self . timer2en ()) . field ("gptimer0en" , & self . gptimer0en ()) . field ("gptimer1en" , & self . gptimer1en ()) . field ("evicen" , & self . evicen ()) . field ("canen" , & self . canen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Apb2en { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Apb2en {{ cfgen: {=bool:?}, cmpen: {=bool:?}, adc0en: {=bool:?}, adc2en: {=bool:?}, timer0en: {=bool:?}, spien: {=bool:?}, timer7en: {=bool:?}, timer1en: {=bool:?}, timer2en: {=bool:?}, gptimer0en: {=bool:?}, gptimer1en: {=bool:?}, evicen: {=bool:?}, canen: {=bool:?} }}" , self . cfgen () , self . cmpen () , self . adc0en () , self . adc2en () , self . timer0en () , self . spien () , self . timer7en () , self . timer1en () , self . timer2en () , self . gptimer0en () , self . gptimer1en () , self . evicen () , self . canen ()) } } # [doc = "APB2 reset register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Apb2rst (pub u32) ; impl Apb2rst { # [doc = "System configuration reset"]
# [inline (always)]
pub const fn cfgrst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "System configuration reset"]
# [inline (always)]
pub fn set_cfgrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Comparator reset"]
# [inline (always)]
pub const fn cmprst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Comparator reset"]
# [inline (always)]
pub fn set_cmprst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "ADC0 reset"]
# [inline (always)]
pub const fn adc0rst (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "ADC0 reset"]
# [inline (always)]
pub fn set_adc0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "ADC2 reset"]
# [inline (always)]
pub const fn adc2rst (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "ADC2 reset"]
# [inline (always)]
pub fn set_adc2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "TIMER0 reset"]
# [inline (always)]
pub const fn timer0rst (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "TIMER0 reset"]
# [inline (always)]
pub fn set_timer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "SPI reset"]
# [inline (always)]
pub const fn spirst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "SPI reset"]
# [inline (always)]
pub fn set_spirst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "TIMER7 reset"]
# [inline (always)]
pub const fn timer7rst (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "TIMER7 reset"]
# [inline (always)]
pub fn set_timer7rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "TIMER1 reset"]
# [inline (always)]
pub const fn timer1rst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "TIMER1 reset"]
# [inline (always)]
pub fn set_timer1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TIMER2 reset"]
# [inline (always)]
pub const fn timer2rst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "TIMER2 reset"]
# [inline (always)]
pub fn set_timer2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "GPTIMER0 reset"]
# [inline (always)]
pub const fn gptimer0rst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "GPTIMER0 reset"]
# [inline (always)]
pub fn set_gptimer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "GPTIMER1 reset"]
# [inline (always)]
pub const fn gptimer1rst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "GPTIMER1 reset"]
# [inline (always)]
pub fn set_gptimer1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "CAN reset"]
# [inline (always)]
pub const fn canrst (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "CAN reset"]
# [inline (always)]
pub fn set_canrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for Apb2rst { # [inline (always)]
fn default () -> Apb2rst { Apb2rst (0) } } impl core :: fmt :: Debug for Apb2rst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Apb2rst") . field ("cfgrst" , & self . cfgrst ()) . field ("cmprst" , & self . cmprst ()) . field ("adc0rst" , & self . adc0rst ()) . field ("adc2rst" , & self . adc2rst ()) . field ("timer0rst" , & self . timer0rst ()) . field ("spirst" , & self . spirst ()) . field ("timer7rst" , & self . timer7rst ()) . field ("timer1rst" , & self . timer1rst ()) . field ("timer2rst" , & self . timer2rst ()) . field ("gptimer0rst" , & self . gptimer0rst ()) . field ("gptimer1rst" , & self . gptimer1rst ()) . field ("canrst" , & self . canrst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Apb2rst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Apb2rst {{ cfgrst: {=bool:?}, cmprst: {=bool:?}, adc0rst: {=bool:?}, adc2rst: {=bool:?}, timer0rst: {=bool:?}, spirst: {=bool:?}, timer7rst: {=bool:?}, timer1rst: {=bool:?}, timer2rst: {=bool:?}, gptimer0rst: {=bool:?}, gptimer1rst: {=bool:?}, canrst: {=bool:?} }}" , self . cfgrst () , self . cmprst () , self . adc0rst () , self . adc2rst () , self . timer0rst () , self . spirst () , self . timer7rst () , self . timer1rst () , self . timer2rst () , self . gptimer0rst () , self . gptimer1rst () , self . canrst ()) } } # [doc = "Configuration register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg0 (pub u32) ; impl Cfg0 { # [doc = "System clock switch"]
# [inline (always)]
pub const fn scs (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "System clock switch"]
# [inline (always)]
pub fn set_scs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "System clock switch status"]
# [inline (always)]
pub const fn scss (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "System clock switch status"]
# [inline (always)]
pub fn set_scss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "AHB prescaler selection"]
# [inline (always)]
pub const fn ahbpsc (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "AHB prescaler selection"]
# [inline (always)]
pub fn set_ahbpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "APB1 prescaler selection"]
# [inline (always)]
pub const fn apb1psc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x07 ; val as u8 } # [doc = "APB1 prescaler selection"]
# [inline (always)]
pub fn set_apb1psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 8usize)) | (((val as u32) & 0x07) << 8usize) ; } # [doc = "APB2 prescaler selection"]
# [inline (always)]
pub const fn apb2psc (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x07 ; val as u8 } # [doc = "APB2 prescaler selection"]
# [inline (always)]
pub fn set_apb2psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 11usize)) | (((val as u32) & 0x07) << 11usize) ; } # [doc = "PLL clock source selection"]
# [inline (always)]
pub const fn pllsel (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "PLL clock source selection"]
# [inline (always)]
pub fn set_pllsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "PLL multiply factor"]
# [inline (always)]
pub const fn pllmf (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x7f ; val as u8 } # [doc = "PLL multiply factor"]
# [inline (always)]
pub fn set_pllmf (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 17usize)) | (((val as u32) & 0x7f) << 17usize) ; } # [doc = "CK_OUT clock source selection"]
# [inline (always)]
pub const fn ckoutsel (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x07 ; val as u8 } # [doc = "CK_OUT clock source selection"]
# [inline (always)]
pub fn set_ckoutsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 24usize)) | (((val as u32) & 0x07) << 24usize) ; } # [doc = "The CK_OUT divider which the CK_OUT frequency can be reduced, see bits 26:24 of RCU_CFG0 for CK_OUT."]
# [inline (always)]
pub const fn ckoutdiv (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x07 ; val as u8 } # [doc = "The CK_OUT divider which the CK_OUT frequency can be reduced, see bits 26:24 of RCU_CFG0 for CK_OUT."]
# [inline (always)]
pub fn set_ckoutdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 28usize)) | (((val as u32) & 0x07) << 28usize) ; } # [doc = "The CK_PLL divide by 1 or 8 for CK_OUT"]
# [inline (always)]
pub const fn plldv (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "The CK_PLL divide by 1 or 8 for CK_OUT"]
# [inline (always)]
pub fn set_plldv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cfg0 { # [inline (always)]
fn default () -> Cfg0 { Cfg0 (0) } } impl core :: fmt :: Debug for Cfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg0") . field ("scs" , & self . scs ()) . field ("scss" , & self . scss ()) . field ("ahbpsc" , & self . ahbpsc ()) . field ("apb1psc" , & self . apb1psc ()) . field ("apb2psc" , & self . apb2psc ()) . field ("pllsel" , & self . pllsel ()) . field ("pllmf" , & self . pllmf ()) . field ("ckoutsel" , & self . ckoutsel ()) . field ("ckoutdiv" , & self . ckoutdiv ()) . field ("plldv" , & self . plldv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg0 {{ scs: {=u8:?}, scss: {=u8:?}, ahbpsc: {=u8:?}, apb1psc: {=u8:?}, apb2psc: {=u8:?}, pllsel: {=bool:?}, pllmf: {=u8:?}, ckoutsel: {=u8:?}, ckoutdiv: {=u8:?}, plldv: {=bool:?} }}" , self . scs () , self . scss () , self . ahbpsc () , self . apb1psc () , self . apb2psc () , self . pllsel () , self . pllmf () , self . ckoutsel () , self . ckoutdiv () , self . plldv ()) } } # [doc = "Configuration register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg1 (pub u32) ; impl Cfg1 { # [doc = "CK_HXTAL divider previous PLL"]
# [inline (always)]
pub const fn predv (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "CK_HXTAL divider previous PLL"]
# [inline (always)]
pub fn set_predv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } } impl Default for Cfg1 { # [inline (always)]
fn default () -> Cfg1 { Cfg1 (0) } } impl core :: fmt :: Debug for Cfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg1") . field ("predv" , & self . predv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg1 {{ predv: {=u8:?} }}" , self . predv ()) } } # [doc = "Configuration register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg2 (pub u32) ; impl Cfg2 { # [doc = "CK_I2C clock source selection"]
# [inline (always)]
pub const fn i2csel (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "CK_I2C clock source selection"]
# [inline (always)]
pub fn set_i2csel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "CK_ADCPRE clock source selection"]
# [inline (always)]
pub const fn adcsel (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x03 ; val as u8 } # [doc = "CK_ADCPRE clock source selection"]
# [inline (always)]
pub fn set_adcsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 25usize)) | (((val as u32) & 0x03) << 25usize) ; } # [doc = "ADC clock prescaler selection"]
# [inline (always)]
pub const fn adcpsc (& self) -> u8 { let val = (self . 0 >> 27usize) & 0x1f ; val as u8 } # [doc = "ADC clock prescaler selection"]
# [inline (always)]
pub fn set_adcpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 27usize)) | (((val as u32) & 0x1f) << 27usize) ; } } impl Default for Cfg2 { # [inline (always)]
fn default () -> Cfg2 { Cfg2 (0) } } impl core :: fmt :: Debug for Cfg2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg2") . field ("i2csel" , & self . i2csel ()) . field ("adcsel" , & self . adcsel ()) . field ("adcpsc" , & self . adcpsc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg2 {{ i2csel: {=u8:?}, adcsel: {=u8:?}, adcpsc: {=u8:?} }}" , self . i2csel () , self . adcsel () , self . adcpsc ()) } } # [doc = "Control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Internal high speed oscillator enable"]
# [inline (always)]
pub const fn irc32men (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Internal high speed oscillator enable"]
# [inline (always)]
pub fn set_irc32men (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "IRC32M high speed internal oscillator stabilization flag"]
# [inline (always)]
pub const fn irc32mstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "IRC32M high speed internal oscillator stabilization flag"]
# [inline (always)]
pub fn set_irc32mstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Internal 32M RC oscillator clock trim adjust value"]
# [inline (always)]
pub const fn irc32madj (& self) -> u8 { let val = (self . 0 >> 3usize) & 0x1f ; val as u8 } # [doc = "Internal 32M RC oscillator clock trim adjust value"]
# [inline (always)]
pub fn set_irc32madj (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 3usize)) | (((val as u32) & 0x1f) << 3usize) ; } # [doc = "Internal 32M RC oscillator calibration value register"]
# [inline (always)]
pub const fn irc32mcalib (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Internal 32M RC oscillator calibration value register"]
# [inline (always)]
pub fn set_irc32mcalib (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "External high speed oscillator enable"]
# [inline (always)]
pub const fn hxtalen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "External high speed oscillator enable"]
# [inline (always)]
pub fn set_hxtalen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "External high speed oscillator ready reset"]
# [inline (always)]
pub const fn hxtalrst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "External high speed oscillator ready reset"]
# [inline (always)]
pub fn set_hxtalrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "External crystal oscillator (HXTAL) clock stabilization flag"]
# [inline (always)]
pub const fn hxtalstb (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "External crystal oscillator (HXTAL) clock stabilization flag"]
# [inline (always)]
pub fn set_hxtalstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "External crystal oscillator (HXTAL) clock bypass mode enable"]
# [inline (always)]
pub const fn hxtalbps (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "External crystal oscillator (HXTAL) clock bypass mode enable"]
# [inline (always)]
pub fn set_hxtalbps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "HXTAL clock monitor enable"]
# [inline (always)]
pub const fn ckmen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "HXTAL clock monitor enable"]
# [inline (always)]
pub fn set_ckmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "PLL clock monitor enable"]
# [inline (always)]
pub const fn pllmen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "PLL clock monitor enable"]
# [inline (always)]
pub fn set_pllmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "HXTAL frequency scale select"]
# [inline (always)]
pub const fn hxtalscal (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "HXTAL frequency scale select"]
# [inline (always)]
pub fn set_hxtalscal (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "PLL enable"]
# [inline (always)]
pub const fn pllen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "PLL enable"]
# [inline (always)]
pub fn set_pllen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "PLL clock stabilization flag"]
# [inline (always)]
pub const fn pllstb (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "PLL clock stabilization flag"]
# [inline (always)]
pub fn set_pllstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("irc32men" , & self . irc32men ()) . field ("irc32mstb" , & self . irc32mstb ()) . field ("irc32madj" , & self . irc32madj ()) . field ("irc32mcalib" , & self . irc32mcalib ()) . field ("hxtalen" , & self . hxtalen ()) . field ("hxtalrst" , & self . hxtalrst ()) . field ("hxtalstb" , & self . hxtalstb ()) . field ("hxtalbps" , & self . hxtalbps ()) . field ("ckmen" , & self . ckmen ()) . field ("pllmen" , & self . pllmen ()) . field ("hxtalscal" , & self . hxtalscal ()) . field ("pllen" , & self . pllen ()) . field ("pllstb" , & self . pllstb ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ irc32men: {=bool:?}, irc32mstb: {=bool:?}, irc32madj: {=u8:?}, irc32mcalib: {=u8:?}, hxtalen: {=bool:?}, hxtalrst: {=bool:?}, hxtalstb: {=bool:?}, hxtalbps: {=bool:?}, ckmen: {=bool:?}, pllmen: {=bool:?}, hxtalscal: {=bool:?}, pllen: {=bool:?}, pllstb: {=bool:?} }}" , self . irc32men () , self . irc32mstb () , self . irc32madj () , self . irc32mcalib () , self . hxtalen () , self . hxtalrst () , self . hxtalstb () , self . hxtalbps () , self . ckmen () , self . pllmen () , self . hxtalscal () , self . pllen () , self . pllstb ()) } } # [doc = "Interrupt register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Int (pub u32) ; impl Int { # [doc = "IRC32K stabilization interrupt flag"]
# [inline (always)]
pub const fn irc32kstbif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "IRC32K stabilization interrupt flag"]
# [inline (always)]
pub fn set_irc32kstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "IRC32M stabilization interrupt flag"]
# [inline (always)]
pub const fn irc32mstbif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "IRC32M stabilization interrupt flag"]
# [inline (always)]
pub fn set_irc32mstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "HXTAL stabilization interrupt flag"]
# [inline (always)]
pub const fn hxtalstbif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "HXTAL stabilization interrupt flag"]
# [inline (always)]
pub fn set_hxtalstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "PLL stabilization interrupt flag"]
# [inline (always)]
pub const fn pllstbif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "PLL stabilization interrupt flag"]
# [inline (always)]
pub fn set_pllstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "PLL clock monitor interrupt flag"]
# [inline (always)]
pub const fn pllmif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "PLL clock monitor interrupt flag"]
# [inline (always)]
pub fn set_pllmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "HXTAL clock stuck interrupt flag"]
# [inline (always)]
pub const fn ckmif (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "HXTAL clock stuck interrupt flag"]
# [inline (always)]
pub fn set_ckmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "IRC32K stabilization interrupt enable"]
# [inline (always)]
pub const fn irc32kstbie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "IRC32K stabilization interrupt enable"]
# [inline (always)]
pub fn set_irc32kstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "IRC32M stabilization interrupt enable"]
# [inline (always)]
pub const fn irc32mstbie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "IRC32M stabilization interrupt enable"]
# [inline (always)]
pub fn set_irc32mstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "HXTAL stabilization interrupt enable"]
# [inline (always)]
pub const fn hxtalstbie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "HXTAL stabilization interrupt enable"]
# [inline (always)]
pub fn set_hxtalstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "PLL stabilization interrupt enable"]
# [inline (always)]
pub const fn pllstbie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "PLL stabilization interrupt enable"]
# [inline (always)]
pub fn set_pllstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "PLL clock monitor interrupt enable"]
# [inline (always)]
pub const fn pllmie (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "PLL clock monitor interrupt enable"]
# [inline (always)]
pub fn set_pllmie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "IRC32K stabilization interrupt clear"]
# [inline (always)]
pub const fn irc32kstbic (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "IRC32K stabilization interrupt clear"]
# [inline (always)]
pub fn set_irc32kstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "IRC32M stabilization interrupt clear"]
# [inline (always)]
pub const fn irc32mstbic (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "IRC32M stabilization interrupt clear"]
# [inline (always)]
pub fn set_irc32mstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "HXTAL stabilization interrupt clear"]
# [inline (always)]
pub const fn hxtalstbic (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "HXTAL stabilization interrupt clear"]
# [inline (always)]
pub fn set_hxtalstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "PLL stabilization interrupt clear"]
# [inline (always)]
pub const fn pllstbic (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "PLL stabilization interrupt clear"]
# [inline (always)]
pub fn set_pllstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "PLL clock monitor interrupt clear"]
# [inline (always)]
pub const fn pllmic (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "PLL clock monitor interrupt clear"]
# [inline (always)]
pub fn set_pllmic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "HXTAL clock stuck interrupt clear"]
# [inline (always)]
pub const fn ckmic (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "HXTAL clock stuck interrupt clear"]
# [inline (always)]
pub fn set_ckmic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for Int { # [inline (always)]
fn default () -> Int { Int (0) } } impl core :: fmt :: Debug for Int { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Int") . field ("irc32kstbif" , & self . irc32kstbif ()) . field ("irc32mstbif" , & self . irc32mstbif ()) . field ("hxtalstbif" , & self . hxtalstbif ()) . field ("pllstbif" , & self . pllstbif ()) . field ("pllmif" , & self . pllmif ()) . field ("ckmif" , & self . ckmif ()) . field ("irc32kstbie" , & self . irc32kstbie ()) . field ("irc32mstbie" , & self . irc32mstbie ()) . field ("hxtalstbie" , & self . hxtalstbie ()) . field ("pllstbie" , & self . pllstbie ()) . field ("pllmie" , & self . pllmie ()) . field ("irc32kstbic" , & self . irc32kstbic ()) . field ("irc32mstbic" , & self . irc32mstbic ()) . field ("hxtalstbic" , & self . hxtalstbic ()) . field ("pllstbic" , & self . pllstbic ()) . field ("pllmic" , & self . pllmic ()) . field ("ckmic" , & self . ckmic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Int { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Int {{ irc32kstbif: {=bool:?}, irc32mstbif: {=bool:?}, hxtalstbif: {=bool:?}, pllstbif: {=bool:?}, pllmif: {=bool:?}, ckmif: {=bool:?}, irc32kstbie: {=bool:?}, irc32mstbie: {=bool:?}, hxtalstbie: {=bool:?}, pllstbie: {=bool:?}, pllmie: {=bool:?}, irc32kstbic: {=bool:?}, irc32mstbic: {=bool:?}, hxtalstbic: {=bool:?}, pllstbic: {=bool:?}, pllmic: {=bool:?}, ckmic: {=bool:?} }}" , self . irc32kstbif () , self . irc32mstbif () , self . hxtalstbif () , self . pllstbif () , self . pllmif () , self . ckmif () , self . irc32kstbie () , self . irc32mstbie () , self . hxtalstbie () , self . pllstbie () , self . pllmie () , self . irc32kstbic () , self . irc32mstbic () , self . hxtalstbic () , self . pllstbic () , self . pllmic () , self . ckmic ()) } } # [doc = "Reset source/clock register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rstsck (pub u32) ; impl Rstsck { # [doc = "IRC32K enable"]
# [inline (always)]
pub const fn irc32ken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "IRC32K enable"]
# [inline (always)]
pub fn set_irc32ken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "IRC32K stabilization"]
# [inline (always)]
pub const fn irc32kstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "IRC32K stabilization"]
# [inline (always)]
pub fn set_irc32kstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "CPU Lock-Up reset enable"]
# [inline (always)]
pub const fn lockuprsten (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "CPU Lock-Up reset enable"]
# [inline (always)]
pub fn set_lockuprsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Lost of HXTAL reset enable"]
# [inline (always)]
pub const fn lohrsten (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Lost of HXTAL reset enable"]
# [inline (always)]
pub fn set_lohrsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Lost of PLL reset enable"]
# [inline (always)]
pub const fn loprsten (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Lost of PLL reset enable"]
# [inline (always)]
pub fn set_loprsten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Low voltage 0 detect error reset flag"]
# [inline (always)]
pub const fn lvd0rstf (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Low voltage 0 detect error reset flag"]
# [inline (always)]
pub fn set_lvd0rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "CPU Lock-Up error reset flag"]
# [inline (always)]
pub const fn lockuprstf (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "CPU Lock-Up error reset flag"]
# [inline (always)]
pub fn set_lockuprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Low voltage 1 detect error reset flag"]
# [inline (always)]
pub const fn lvd1rstf (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Low voltage 1 detect error reset flag"]
# [inline (always)]
pub fn set_lvd1rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Low voltage 2 detect error reset flag"]
# [inline (always)]
pub const fn lvd2rstf (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Low voltage 2 detect error reset flag"]
# [inline (always)]
pub fn set_lvd2rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "Lost of HXTAL error reset flag"]
# [inline (always)]
pub const fn lohrstf (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "Lost of HXTAL error reset flag"]
# [inline (always)]
pub fn set_lohrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Lost of PLL error reset flag"]
# [inline (always)]
pub const fn loprstf (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Lost of PLL error reset flag"]
# [inline (always)]
pub fn set_loprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "1.1V domain power reset flag"]
# [inline (always)]
pub const fn v11rstf (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "1.1V domain power reset flag"]
# [inline (always)]
pub fn set_v11rstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "Reset flag clear"]
# [inline (always)]
pub const fn rstfc (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Reset flag clear"]
# [inline (always)]
pub fn set_rstfc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Option byte loader reset flag"]
# [inline (always)]
pub const fn oblrstf (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Option byte loader reset flag"]
# [inline (always)]
pub fn set_oblrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "External PIN reset flag"]
# [inline (always)]
pub const fn eprstf (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "External PIN reset flag"]
# [inline (always)]
pub fn set_eprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "Power reset flag"]
# [inline (always)]
pub const fn porrstf (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "Power reset flag"]
# [inline (always)]
pub fn set_porrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "Software reset flag"]
# [inline (always)]
pub const fn swrstf (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Software reset flag"]
# [inline (always)]
pub fn set_swrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Free Watchdog timer reset flag"]
# [inline (always)]
pub const fn fwdgtrstf (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Free Watchdog timer reset flag"]
# [inline (always)]
pub fn set_fwdgtrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Window watchdog timer reset flag"]
# [inline (always)]
pub const fn wwdgtrstf (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Window watchdog timer reset flag"]
# [inline (always)]
pub fn set_wwdgtrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Low-power reset flag"]
# [inline (always)]
pub const fn lprstf (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Low-power reset flag"]
# [inline (always)]
pub fn set_lprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Rstsck { # [inline (always)]
fn default () -> Rstsck { Rstsck (0) } } impl core :: fmt :: Debug for Rstsck { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rstsck") . field ("irc32ken" , & self . irc32ken ()) . field ("irc32kstb" , & self . irc32kstb ()) . field ("lockuprsten" , & self . lockuprsten ()) . field ("lohrsten" , & self . lohrsten ()) . field ("loprsten" , & self . loprsten ()) . field ("lvd0rstf" , & self . lvd0rstf ()) . field ("lockuprstf" , & self . lockuprstf ()) . field ("lvd1rstf" , & self . lvd1rstf ()) . field ("lvd2rstf" , & self . lvd2rstf ()) . field ("lohrstf" , & self . lohrstf ()) . field ("loprstf" , & self . loprstf ()) . field ("v11rstf" , & self . v11rstf ()) . field ("rstfc" , & self . rstfc ()) . field ("oblrstf" , & self . oblrstf ()) . field ("eprstf" , & self . eprstf ()) . field ("porrstf" , & self . porrstf ()) . field ("swrstf" , & self . swrstf ()) . field ("fwdgtrstf" , & self . fwdgtrstf ()) . field ("wwdgtrstf" , & self . wwdgtrstf ()) . field ("lprstf" , & self . lprstf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rstsck { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rstsck {{ irc32ken: {=bool:?}, irc32kstb: {=bool:?}, lockuprsten: {=bool:?}, lohrsten: {=bool:?}, loprsten: {=bool:?}, lvd0rstf: {=bool:?}, lockuprstf: {=bool:?}, lvd1rstf: {=bool:?}, lvd2rstf: {=bool:?}, lohrstf: {=bool:?}, loprstf: {=bool:?}, v11rstf: {=bool:?}, rstfc: {=bool:?}, oblrstf: {=bool:?}, eprstf: {=bool:?}, porrstf: {=bool:?}, swrstf: {=bool:?}, fwdgtrstf: {=bool:?}, wwdgtrstf: {=bool:?}, lprstf: {=bool:?} }}" , self . irc32ken () , self . irc32kstb () , self . lockuprsten () , self . lohrsten () , self . loprsten () , self . lvd0rstf () , self . lockuprstf () , self . lvd1rstf () , self . lvd2rstf () , self . lohrstf () , self . loprstf () , self . v11rstf () , self . rstfc () , self . oblrstf () , self . eprstf () , self . porrstf () , self . swrstf () , self . fwdgtrstf () , self . wwdgtrstf () , self . lprstf ()) } } }