#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rcu { ptr : * mut u8 } unsafe impl Send for Rcu { } unsafe impl Sync for Rcu { } impl Rcu { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn rcu_ctl0 (self) -> crate :: common :: Reg < regs :: RcuCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn rcu_cfg0 (self) -> crate :: common :: Reg < regs :: RcuCfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn rcu_int (self) -> crate :: common :: Reg < regs :: RcuInt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn rcu_ahb1rst (self) -> crate :: common :: Reg < regs :: RcuAhb1rst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn rcu_ahb2rst (self) -> crate :: common :: Reg < regs :: RcuAhb2rst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn rcu_apbrst (self) -> crate :: common :: Reg < regs :: RcuApbrst , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn rcu_ahb1en (self) -> crate :: common :: Reg < regs :: RcuAhb1en , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn rcu_ahb2en (self) -> crate :: common :: Reg < regs :: RcuAhb2en , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn rcu_apben (self) -> crate :: common :: Reg < regs :: RcuApben , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn rcu_ahb1spdpen (self) -> crate :: common :: Reg < regs :: RcuAhb1spdpen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x50usize) as _) } } # [inline (always)]
pub const fn rcu_ahb2spdpen (self) -> crate :: common :: Reg < regs :: RcuAhb2spdpen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x54usize) as _) } } # [inline (always)]
pub const fn rcu_apbspdpen (self) -> crate :: common :: Reg < regs :: RcuApbspdpen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x64usize) as _) } } # [inline (always)]
pub const fn rcu_ctl1 (self) -> crate :: common :: Reg < regs :: RcuCtl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x70usize) as _) } } # [inline (always)]
pub const fn rcu_rstsck (self) -> crate :: common :: Reg < regs :: RcuRstsck , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x74usize) as _) } } # [inline (always)]
pub const fn rcu_cfg1 (self) -> crate :: common :: Reg < regs :: RcuCfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x8cusize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhb1en (pub u32) ; impl RcuAhb1en { # [must_use]
# [inline (always)]
pub const fn rcu_ahb1en_fmcen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1en_fmcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1en_crcen (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1en_crcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1en_dmaen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1en_dmaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1en_dmamuxen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1en_dmamuxen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RcuAhb1en { # [inline (always)]
fn default () -> RcuAhb1en { RcuAhb1en (0) } } impl core :: fmt :: Debug for RcuAhb1en { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhb1en") . field ("rcu_ahb1en_fmcen" , & self . rcu_ahb1en_fmcen ()) . field ("rcu_ahb1en_crcen" , & self . rcu_ahb1en_crcen ()) . field ("rcu_ahb1en_dmaen" , & self . rcu_ahb1en_dmaen ()) . field ("rcu_ahb1en_dmamuxen" , & self . rcu_ahb1en_dmamuxen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhb1en { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhb1en {{ rcu_ahb1en_fmcen: {=bool:?}, rcu_ahb1en_crcen: {=bool:?}, rcu_ahb1en_dmaen: {=bool:?}, rcu_ahb1en_dmamuxen: {=bool:?} }}" , self . rcu_ahb1en_fmcen () , self . rcu_ahb1en_crcen () , self . rcu_ahb1en_dmaen () , self . rcu_ahb1en_dmamuxen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhb1rst (pub u32) ; impl RcuAhb1rst { # [must_use]
# [inline (always)]
pub const fn rcu_ahb1rst_crcrst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1rst_crcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1rst_dmarst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1rst_dmarst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1rst_dmamuxrst (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1rst_dmamuxrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RcuAhb1rst { # [inline (always)]
fn default () -> RcuAhb1rst { RcuAhb1rst (0) } } impl core :: fmt :: Debug for RcuAhb1rst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhb1rst") . field ("rcu_ahb1rst_crcrst" , & self . rcu_ahb1rst_crcrst ()) . field ("rcu_ahb1rst_dmarst" , & self . rcu_ahb1rst_dmarst ()) . field ("rcu_ahb1rst_dmamuxrst" , & self . rcu_ahb1rst_dmamuxrst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhb1rst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhb1rst {{ rcu_ahb1rst_crcrst: {=bool:?}, rcu_ahb1rst_dmarst: {=bool:?}, rcu_ahb1rst_dmamuxrst: {=bool:?} }}" , self . rcu_ahb1rst_crcrst () , self . rcu_ahb1rst_dmarst () , self . rcu_ahb1rst_dmamuxrst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhb1spdpen (pub u32) ; impl RcuAhb1spdpen { # [must_use]
# [inline (always)]
pub const fn rcu_ahb1spdpen_sramen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1spdpen_sramen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1spdpen_fmcen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1spdpen_fmcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1spdpen_crcen (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1spdpen_crcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1spdpen_dmaen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1spdpen_dmaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb1spdpen_dmamuxen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb1spdpen_dmamuxen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RcuAhb1spdpen { # [inline (always)]
fn default () -> RcuAhb1spdpen { RcuAhb1spdpen (0) } } impl core :: fmt :: Debug for RcuAhb1spdpen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhb1spdpen") . field ("rcu_ahb1spdpen_sramen" , & self . rcu_ahb1spdpen_sramen ()) . field ("rcu_ahb1spdpen_fmcen" , & self . rcu_ahb1spdpen_fmcen ()) . field ("rcu_ahb1spdpen_crcen" , & self . rcu_ahb1spdpen_crcen ()) . field ("rcu_ahb1spdpen_dmaen" , & self . rcu_ahb1spdpen_dmaen ()) . field ("rcu_ahb1spdpen_dmamuxen" , & self . rcu_ahb1spdpen_dmamuxen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhb1spdpen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhb1spdpen {{ rcu_ahb1spdpen_sramen: {=bool:?}, rcu_ahb1spdpen_fmcen: {=bool:?}, rcu_ahb1spdpen_crcen: {=bool:?}, rcu_ahb1spdpen_dmaen: {=bool:?}, rcu_ahb1spdpen_dmamuxen: {=bool:?} }}" , self . rcu_ahb1spdpen_sramen () , self . rcu_ahb1spdpen_fmcen () , self . rcu_ahb1spdpen_crcen () , self . rcu_ahb1spdpen_dmaen () , self . rcu_ahb1spdpen_dmamuxen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhb2en (pub u32) ; impl RcuAhb2en { # [must_use]
# [inline (always)]
pub const fn rcu_ahb2en_paen (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2en_paen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2en_pben (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2en_pben (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2en_pcen (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2en_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2en_pden (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2en_pden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2en_pfen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2en_pfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for RcuAhb2en { # [inline (always)]
fn default () -> RcuAhb2en { RcuAhb2en (0) } } impl core :: fmt :: Debug for RcuAhb2en { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhb2en") . field ("rcu_ahb2en_paen" , & self . rcu_ahb2en_paen ()) . field ("rcu_ahb2en_pben" , & self . rcu_ahb2en_pben ()) . field ("rcu_ahb2en_pcen" , & self . rcu_ahb2en_pcen ()) . field ("rcu_ahb2en_pden" , & self . rcu_ahb2en_pden ()) . field ("rcu_ahb2en_pfen" , & self . rcu_ahb2en_pfen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhb2en { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhb2en {{ rcu_ahb2en_paen: {=bool:?}, rcu_ahb2en_pben: {=bool:?}, rcu_ahb2en_pcen: {=bool:?}, rcu_ahb2en_pden: {=bool:?}, rcu_ahb2en_pfen: {=bool:?} }}" , self . rcu_ahb2en_paen () , self . rcu_ahb2en_pben () , self . rcu_ahb2en_pcen () , self . rcu_ahb2en_pden () , self . rcu_ahb2en_pfen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhb2rst (pub u32) ; impl RcuAhb2rst { # [must_use]
# [inline (always)]
pub const fn rcu_ahb2rst_parst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2rst_parst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2rst_pbrst (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2rst_pbrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2rst_pcrst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2rst_pcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2rst_pdrst (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2rst_pdrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2rst_pfrst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2rst_pfrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for RcuAhb2rst { # [inline (always)]
fn default () -> RcuAhb2rst { RcuAhb2rst (0) } } impl core :: fmt :: Debug for RcuAhb2rst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhb2rst") . field ("rcu_ahb2rst_parst" , & self . rcu_ahb2rst_parst ()) . field ("rcu_ahb2rst_pbrst" , & self . rcu_ahb2rst_pbrst ()) . field ("rcu_ahb2rst_pcrst" , & self . rcu_ahb2rst_pcrst ()) . field ("rcu_ahb2rst_pdrst" , & self . rcu_ahb2rst_pdrst ()) . field ("rcu_ahb2rst_pfrst" , & self . rcu_ahb2rst_pfrst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhb2rst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhb2rst {{ rcu_ahb2rst_parst: {=bool:?}, rcu_ahb2rst_pbrst: {=bool:?}, rcu_ahb2rst_pcrst: {=bool:?}, rcu_ahb2rst_pdrst: {=bool:?}, rcu_ahb2rst_pfrst: {=bool:?} }}" , self . rcu_ahb2rst_parst () , self . rcu_ahb2rst_pbrst () , self . rcu_ahb2rst_pcrst () , self . rcu_ahb2rst_pdrst () , self . rcu_ahb2rst_pfrst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuAhb2spdpen (pub u32) ; impl RcuAhb2spdpen { # [must_use]
# [inline (always)]
pub const fn rcu_ahb2spdpen_paen (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2spdpen_paen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2spdpen_pben (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2spdpen_pben (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2spdpen_pcen (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2spdpen_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2spdpen_pden (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2spdpen_pden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ahb2spdpen_pfen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ahb2spdpen_pfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for RcuAhb2spdpen { # [inline (always)]
fn default () -> RcuAhb2spdpen { RcuAhb2spdpen (0) } } impl core :: fmt :: Debug for RcuAhb2spdpen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuAhb2spdpen") . field ("rcu_ahb2spdpen_paen" , & self . rcu_ahb2spdpen_paen ()) . field ("rcu_ahb2spdpen_pben" , & self . rcu_ahb2spdpen_pben ()) . field ("rcu_ahb2spdpen_pcen" , & self . rcu_ahb2spdpen_pcen ()) . field ("rcu_ahb2spdpen_pden" , & self . rcu_ahb2spdpen_pden ()) . field ("rcu_ahb2spdpen_pfen" , & self . rcu_ahb2spdpen_pfen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuAhb2spdpen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuAhb2spdpen {{ rcu_ahb2spdpen_paen: {=bool:?}, rcu_ahb2spdpen_pben: {=bool:?}, rcu_ahb2spdpen_pcen: {=bool:?}, rcu_ahb2spdpen_pden: {=bool:?}, rcu_ahb2spdpen_pfen: {=bool:?} }}" , self . rcu_ahb2spdpen_paen () , self . rcu_ahb2spdpen_pben () , self . rcu_ahb2spdpen_pcen () , self . rcu_ahb2spdpen_pden () , self . rcu_ahb2spdpen_pfen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApben (pub u32) ; impl RcuApben { # [must_use]
# [inline (always)]
pub const fn rcu_apben_syscfgen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_syscfgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_cmpen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_cmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_wwdgten (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_wwdgten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_adcen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_adcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_timer0en (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_timer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_timer2en (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_timer2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_spi0en (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_spi0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_spi1en (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_spi1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_usart0en (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_usart0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_usart1en (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_usart1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_timer13en (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_timer13en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_timer15en (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_timer15en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_timer16en (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_timer16en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_usart2en (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_usart2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_i2c0en (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_i2c0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_i2c1en (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_i2c1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_dbgen (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_dbgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apben_pmuen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apben_pmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } } impl Default for RcuApben { # [inline (always)]
fn default () -> RcuApben { RcuApben (0) } } impl core :: fmt :: Debug for RcuApben { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApben") . field ("rcu_apben_syscfgen" , & self . rcu_apben_syscfgen ()) . field ("rcu_apben_cmpen" , & self . rcu_apben_cmpen ()) . field ("rcu_apben_wwdgten" , & self . rcu_apben_wwdgten ()) . field ("rcu_apben_adcen" , & self . rcu_apben_adcen ()) . field ("rcu_apben_timer0en" , & self . rcu_apben_timer0en ()) . field ("rcu_apben_timer2en" , & self . rcu_apben_timer2en ()) . field ("rcu_apben_spi0en" , & self . rcu_apben_spi0en ()) . field ("rcu_apben_spi1en" , & self . rcu_apben_spi1en ()) . field ("rcu_apben_usart0en" , & self . rcu_apben_usart0en ()) . field ("rcu_apben_usart1en" , & self . rcu_apben_usart1en ()) . field ("rcu_apben_timer13en" , & self . rcu_apben_timer13en ()) . field ("rcu_apben_timer15en" , & self . rcu_apben_timer15en ()) . field ("rcu_apben_timer16en" , & self . rcu_apben_timer16en ()) . field ("rcu_apben_usart2en" , & self . rcu_apben_usart2en ()) . field ("rcu_apben_i2c0en" , & self . rcu_apben_i2c0en ()) . field ("rcu_apben_i2c1en" , & self . rcu_apben_i2c1en ()) . field ("rcu_apben_dbgen" , & self . rcu_apben_dbgen ()) . field ("rcu_apben_pmuen" , & self . rcu_apben_pmuen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApben { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApben {{ rcu_apben_syscfgen: {=bool:?}, rcu_apben_cmpen: {=bool:?}, rcu_apben_wwdgten: {=bool:?}, rcu_apben_adcen: {=bool:?}, rcu_apben_timer0en: {=bool:?}, rcu_apben_timer2en: {=bool:?}, rcu_apben_spi0en: {=bool:?}, rcu_apben_spi1en: {=bool:?}, rcu_apben_usart0en: {=bool:?}, rcu_apben_usart1en: {=bool:?}, rcu_apben_timer13en: {=bool:?}, rcu_apben_timer15en: {=bool:?}, rcu_apben_timer16en: {=bool:?}, rcu_apben_usart2en: {=bool:?}, rcu_apben_i2c0en: {=bool:?}, rcu_apben_i2c1en: {=bool:?}, rcu_apben_dbgen: {=bool:?}, rcu_apben_pmuen: {=bool:?} }}" , self . rcu_apben_syscfgen () , self . rcu_apben_cmpen () , self . rcu_apben_wwdgten () , self . rcu_apben_adcen () , self . rcu_apben_timer0en () , self . rcu_apben_timer2en () , self . rcu_apben_spi0en () , self . rcu_apben_spi1en () , self . rcu_apben_usart0en () , self . rcu_apben_usart1en () , self . rcu_apben_timer13en () , self . rcu_apben_timer15en () , self . rcu_apben_timer16en () , self . rcu_apben_usart2en () , self . rcu_apben_i2c0en () , self . rcu_apben_i2c1en () , self . rcu_apben_dbgen () , self . rcu_apben_pmuen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApbrst (pub u32) ; impl RcuApbrst { # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_syscfgrst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_syscfgrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_cmprst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_cmprst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_wwdgtrst (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_wwdgtrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_adcrst (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_adcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_timer0rst (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_timer0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_timer2rst (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_timer2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_spi0rst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_spi0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_spi1rst (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_spi1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_usart0rst (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_usart0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_usart1rst (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_usart1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_timer13rst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_timer13rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_timer15rst (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_timer15rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_timer16rst (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_timer16rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_usart2rst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_usart2rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_i2c0rst (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_i2c0rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_i2c1rst (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_i2c1rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbrst_pmurst (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbrst_pmurst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } } impl Default for RcuApbrst { # [inline (always)]
fn default () -> RcuApbrst { RcuApbrst (0) } } impl core :: fmt :: Debug for RcuApbrst { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApbrst") . field ("rcu_apbrst_syscfgrst" , & self . rcu_apbrst_syscfgrst ()) . field ("rcu_apbrst_cmprst" , & self . rcu_apbrst_cmprst ()) . field ("rcu_apbrst_wwdgtrst" , & self . rcu_apbrst_wwdgtrst ()) . field ("rcu_apbrst_adcrst" , & self . rcu_apbrst_adcrst ()) . field ("rcu_apbrst_timer0rst" , & self . rcu_apbrst_timer0rst ()) . field ("rcu_apbrst_timer2rst" , & self . rcu_apbrst_timer2rst ()) . field ("rcu_apbrst_spi0rst" , & self . rcu_apbrst_spi0rst ()) . field ("rcu_apbrst_spi1rst" , & self . rcu_apbrst_spi1rst ()) . field ("rcu_apbrst_usart0rst" , & self . rcu_apbrst_usart0rst ()) . field ("rcu_apbrst_usart1rst" , & self . rcu_apbrst_usart1rst ()) . field ("rcu_apbrst_timer13rst" , & self . rcu_apbrst_timer13rst ()) . field ("rcu_apbrst_timer15rst" , & self . rcu_apbrst_timer15rst ()) . field ("rcu_apbrst_timer16rst" , & self . rcu_apbrst_timer16rst ()) . field ("rcu_apbrst_usart2rst" , & self . rcu_apbrst_usart2rst ()) . field ("rcu_apbrst_i2c0rst" , & self . rcu_apbrst_i2c0rst ()) . field ("rcu_apbrst_i2c1rst" , & self . rcu_apbrst_i2c1rst ()) . field ("rcu_apbrst_pmurst" , & self . rcu_apbrst_pmurst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApbrst { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApbrst {{ rcu_apbrst_syscfgrst: {=bool:?}, rcu_apbrst_cmprst: {=bool:?}, rcu_apbrst_wwdgtrst: {=bool:?}, rcu_apbrst_adcrst: {=bool:?}, rcu_apbrst_timer0rst: {=bool:?}, rcu_apbrst_timer2rst: {=bool:?}, rcu_apbrst_spi0rst: {=bool:?}, rcu_apbrst_spi1rst: {=bool:?}, rcu_apbrst_usart0rst: {=bool:?}, rcu_apbrst_usart1rst: {=bool:?}, rcu_apbrst_timer13rst: {=bool:?}, rcu_apbrst_timer15rst: {=bool:?}, rcu_apbrst_timer16rst: {=bool:?}, rcu_apbrst_usart2rst: {=bool:?}, rcu_apbrst_i2c0rst: {=bool:?}, rcu_apbrst_i2c1rst: {=bool:?}, rcu_apbrst_pmurst: {=bool:?} }}" , self . rcu_apbrst_syscfgrst () , self . rcu_apbrst_cmprst () , self . rcu_apbrst_wwdgtrst () , self . rcu_apbrst_adcrst () , self . rcu_apbrst_timer0rst () , self . rcu_apbrst_timer2rst () , self . rcu_apbrst_spi0rst () , self . rcu_apbrst_spi1rst () , self . rcu_apbrst_usart0rst () , self . rcu_apbrst_usart1rst () , self . rcu_apbrst_timer13rst () , self . rcu_apbrst_timer15rst () , self . rcu_apbrst_timer16rst () , self . rcu_apbrst_usart2rst () , self . rcu_apbrst_i2c0rst () , self . rcu_apbrst_i2c1rst () , self . rcu_apbrst_pmurst ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuApbspdpen (pub u32) ; impl RcuApbspdpen { # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_syscfgen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_syscfgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_cmpen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_cmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_wwdgten (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_wwdgten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_adcen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_adcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_timer0en (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_timer0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_timer2en (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_timer2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_spi0en (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_spi0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_spi1en (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_spi1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_usart0en (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_usart0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_usart1en (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_usart1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_timer13en (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_timer13en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_timer15en (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_timer15en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_timer16en (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_timer16en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_usart2en (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_usart2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_i2c0en (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_i2c0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_i2c1en (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_i2c1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_apbspdpen_pmuen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_apbspdpen_pmuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } } impl Default for RcuApbspdpen { # [inline (always)]
fn default () -> RcuApbspdpen { RcuApbspdpen (0) } } impl core :: fmt :: Debug for RcuApbspdpen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuApbspdpen") . field ("rcu_apbspdpen_syscfgen" , & self . rcu_apbspdpen_syscfgen ()) . field ("rcu_apbspdpen_cmpen" , & self . rcu_apbspdpen_cmpen ()) . field ("rcu_apbspdpen_wwdgten" , & self . rcu_apbspdpen_wwdgten ()) . field ("rcu_apbspdpen_adcen" , & self . rcu_apbspdpen_adcen ()) . field ("rcu_apbspdpen_timer0en" , & self . rcu_apbspdpen_timer0en ()) . field ("rcu_apbspdpen_timer2en" , & self . rcu_apbspdpen_timer2en ()) . field ("rcu_apbspdpen_spi0en" , & self . rcu_apbspdpen_spi0en ()) . field ("rcu_apbspdpen_spi1en" , & self . rcu_apbspdpen_spi1en ()) . field ("rcu_apbspdpen_usart0en" , & self . rcu_apbspdpen_usart0en ()) . field ("rcu_apbspdpen_usart1en" , & self . rcu_apbspdpen_usart1en ()) . field ("rcu_apbspdpen_timer13en" , & self . rcu_apbspdpen_timer13en ()) . field ("rcu_apbspdpen_timer15en" , & self . rcu_apbspdpen_timer15en ()) . field ("rcu_apbspdpen_timer16en" , & self . rcu_apbspdpen_timer16en ()) . field ("rcu_apbspdpen_usart2en" , & self . rcu_apbspdpen_usart2en ()) . field ("rcu_apbspdpen_i2c0en" , & self . rcu_apbspdpen_i2c0en ()) . field ("rcu_apbspdpen_i2c1en" , & self . rcu_apbspdpen_i2c1en ()) . field ("rcu_apbspdpen_pmuen" , & self . rcu_apbspdpen_pmuen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuApbspdpen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuApbspdpen {{ rcu_apbspdpen_syscfgen: {=bool:?}, rcu_apbspdpen_cmpen: {=bool:?}, rcu_apbspdpen_wwdgten: {=bool:?}, rcu_apbspdpen_adcen: {=bool:?}, rcu_apbspdpen_timer0en: {=bool:?}, rcu_apbspdpen_timer2en: {=bool:?}, rcu_apbspdpen_spi0en: {=bool:?}, rcu_apbspdpen_spi1en: {=bool:?}, rcu_apbspdpen_usart0en: {=bool:?}, rcu_apbspdpen_usart1en: {=bool:?}, rcu_apbspdpen_timer13en: {=bool:?}, rcu_apbspdpen_timer15en: {=bool:?}, rcu_apbspdpen_timer16en: {=bool:?}, rcu_apbspdpen_usart2en: {=bool:?}, rcu_apbspdpen_i2c0en: {=bool:?}, rcu_apbspdpen_i2c1en: {=bool:?}, rcu_apbspdpen_pmuen: {=bool:?} }}" , self . rcu_apbspdpen_syscfgen () , self . rcu_apbspdpen_cmpen () , self . rcu_apbspdpen_wwdgten () , self . rcu_apbspdpen_adcen () , self . rcu_apbspdpen_timer0en () , self . rcu_apbspdpen_timer2en () , self . rcu_apbspdpen_spi0en () , self . rcu_apbspdpen_spi1en () , self . rcu_apbspdpen_usart0en () , self . rcu_apbspdpen_usart1en () , self . rcu_apbspdpen_timer13en () , self . rcu_apbspdpen_timer15en () , self . rcu_apbspdpen_timer16en () , self . rcu_apbspdpen_usart2en () , self . rcu_apbspdpen_i2c0en () , self . rcu_apbspdpen_i2c1en () , self . rcu_apbspdpen_pmuen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCfg0 (pub u32) ; impl RcuCfg0 { # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_scs (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_scs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_scss (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_scss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ahbpsc (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ahbpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_apbpsc (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_apbpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 11usize)) | (((val as u32) & 0x07) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ckout1sel (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ckout1sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ckout1div (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ckout1div (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 20usize)) | (((val as u32) & 0x07) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ckout0sel (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ckout0sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 24usize)) | (((val as u32) & 0x07) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg0_ckout0div (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg0_ckout0div (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 28usize)) | (((val as u32) & 0x07) << 28usize) ; } } impl Default for RcuCfg0 { # [inline (always)]
fn default () -> RcuCfg0 { RcuCfg0 (0) } } impl core :: fmt :: Debug for RcuCfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCfg0") . field ("rcu_cfg0_scs" , & self . rcu_cfg0_scs ()) . field ("rcu_cfg0_scss" , & self . rcu_cfg0_scss ()) . field ("rcu_cfg0_ahbpsc" , & self . rcu_cfg0_ahbpsc ()) . field ("rcu_cfg0_apbpsc" , & self . rcu_cfg0_apbpsc ()) . field ("rcu_cfg0_ckout1sel" , & self . rcu_cfg0_ckout1sel ()) . field ("rcu_cfg0_ckout1div" , & self . rcu_cfg0_ckout1div ()) . field ("rcu_cfg0_ckout0sel" , & self . rcu_cfg0_ckout0sel ()) . field ("rcu_cfg0_ckout0div" , & self . rcu_cfg0_ckout0div ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCfg0 {{ rcu_cfg0_scs: {=u8:?}, rcu_cfg0_scss: {=u8:?}, rcu_cfg0_ahbpsc: {=u8:?}, rcu_cfg0_apbpsc: {=u8:?}, rcu_cfg0_ckout1sel: {=u8:?}, rcu_cfg0_ckout1div: {=u8:?}, rcu_cfg0_ckout0sel: {=u8:?}, rcu_cfg0_ckout0div: {=u8:?} }}" , self . rcu_cfg0_scs () , self . rcu_cfg0_scss () , self . rcu_cfg0_ahbpsc () , self . rcu_cfg0_apbpsc () , self . rcu_cfg0_ckout1sel () , self . rcu_cfg0_ckout1div () , self . rcu_cfg0_ckout0sel () , self . rcu_cfg0_ckout0div ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCfg1 (pub u32) ; impl RcuCfg1 { # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_usart0sel (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_usart0sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_i2c0sel (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_i2c0sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_i2c1sel (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_i2c1sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_adcsel (& self) -> u8 { let val = (self . 0 >> 7usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_adcsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 7usize)) | (((val as u32) & 0x03) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_adcpsc (& self) -> u8 { let val = (self . 0 >> 9usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_adcpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 9usize)) | (((val as u32) & 0x0f) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_cfg1_i2ssel (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_cfg1_i2ssel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } } impl Default for RcuCfg1 { # [inline (always)]
fn default () -> RcuCfg1 { RcuCfg1 (0) } } impl core :: fmt :: Debug for RcuCfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCfg1") . field ("rcu_cfg1_usart0sel" , & self . rcu_cfg1_usart0sel ()) . field ("rcu_cfg1_i2c0sel" , & self . rcu_cfg1_i2c0sel ()) . field ("rcu_cfg1_i2c1sel" , & self . rcu_cfg1_i2c1sel ()) . field ("rcu_cfg1_adcsel" , & self . rcu_cfg1_adcsel ()) . field ("rcu_cfg1_adcpsc" , & self . rcu_cfg1_adcpsc ()) . field ("rcu_cfg1_i2ssel" , & self . rcu_cfg1_i2ssel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCfg1 {{ rcu_cfg1_usart0sel: {=u8:?}, rcu_cfg1_i2c0sel: {=u8:?}, rcu_cfg1_i2c1sel: {=u8:?}, rcu_cfg1_adcsel: {=u8:?}, rcu_cfg1_adcpsc: {=u8:?}, rcu_cfg1_i2ssel: {=u8:?} }}" , self . rcu_cfg1_usart0sel () , self . rcu_cfg1_i2c0sel () , self . rcu_cfg1_i2c1sel () , self . rcu_cfg1_adcsel () , self . rcu_cfg1_adcpsc () , self . rcu_cfg1_i2ssel ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCtl0 (pub u32) ; impl RcuCtl0 { # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48men (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48men (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48mstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48mstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48madj (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48madj (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 2usize)) | (((val as u32) & 0x3f) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48mcalib (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48mcalib (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_hxtalen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_hxtalen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_hxtalstb (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_hxtalstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_hxtalbps (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_hxtalbps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_ckmen (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_ckmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48mdiv_per (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48mdiv_per (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 25usize)) | (((val as u32) & 0x07) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48m_peren (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48m_peren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl0_irc48mdiv_sys (& self) -> u8 { let val = (self . 0 >> 29usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl0_irc48mdiv_sys (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 29usize)) | (((val as u32) & 0x07) << 29usize) ; } } impl Default for RcuCtl0 { # [inline (always)]
fn default () -> RcuCtl0 { RcuCtl0 (0) } } impl core :: fmt :: Debug for RcuCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCtl0") . field ("rcu_ctl0_irc48men" , & self . rcu_ctl0_irc48men ()) . field ("rcu_ctl0_irc48mstb" , & self . rcu_ctl0_irc48mstb ()) . field ("rcu_ctl0_irc48madj" , & self . rcu_ctl0_irc48madj ()) . field ("rcu_ctl0_irc48mcalib" , & self . rcu_ctl0_irc48mcalib ()) . field ("rcu_ctl0_hxtalen" , & self . rcu_ctl0_hxtalen ()) . field ("rcu_ctl0_hxtalstb" , & self . rcu_ctl0_hxtalstb ()) . field ("rcu_ctl0_hxtalbps" , & self . rcu_ctl0_hxtalbps ()) . field ("rcu_ctl0_ckmen" , & self . rcu_ctl0_ckmen ()) . field ("rcu_ctl0_irc48mdiv_per" , & self . rcu_ctl0_irc48mdiv_per ()) . field ("rcu_ctl0_irc48m_peren" , & self . rcu_ctl0_irc48m_peren ()) . field ("rcu_ctl0_irc48mdiv_sys" , & self . rcu_ctl0_irc48mdiv_sys ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCtl0 {{ rcu_ctl0_irc48men: {=bool:?}, rcu_ctl0_irc48mstb: {=bool:?}, rcu_ctl0_irc48madj: {=u8:?}, rcu_ctl0_irc48mcalib: {=u8:?}, rcu_ctl0_hxtalen: {=bool:?}, rcu_ctl0_hxtalstb: {=bool:?}, rcu_ctl0_hxtalbps: {=bool:?}, rcu_ctl0_ckmen: {=bool:?}, rcu_ctl0_irc48mdiv_per: {=u8:?}, rcu_ctl0_irc48m_peren: {=bool:?}, rcu_ctl0_irc48mdiv_sys: {=u8:?} }}" , self . rcu_ctl0_irc48men () , self . rcu_ctl0_irc48mstb () , self . rcu_ctl0_irc48madj () , self . rcu_ctl0_irc48mcalib () , self . rcu_ctl0_hxtalen () , self . rcu_ctl0_hxtalstb () , self . rcu_ctl0_hxtalbps () , self . rcu_ctl0_ckmen () , self . rcu_ctl0_irc48mdiv_per () , self . rcu_ctl0_irc48m_peren () , self . rcu_ctl0_irc48mdiv_sys ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuCtl1 (pub u32) ; impl RcuCtl1 { # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lxtalen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lxtalen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lxtalstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lxtalstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lxtalbps (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lxtalbps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lxtaldri (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lxtaldri (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lckmen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lckmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lckmd (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lckmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lxtalstbrst (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lxtalstbrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_rtcsrc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rcu_ctl1_rtcsrc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_rtcen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_rtcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_bkprst (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_bkprst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lsckouten (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lsckouten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_ctl1_lsckoutsel (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_ctl1_lsckoutsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } } impl Default for RcuCtl1 { # [inline (always)]
fn default () -> RcuCtl1 { RcuCtl1 (0) } } impl core :: fmt :: Debug for RcuCtl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuCtl1") . field ("rcu_ctl1_lxtalen" , & self . rcu_ctl1_lxtalen ()) . field ("rcu_ctl1_lxtalstb" , & self . rcu_ctl1_lxtalstb ()) . field ("rcu_ctl1_lxtalbps" , & self . rcu_ctl1_lxtalbps ()) . field ("rcu_ctl1_lxtaldri" , & self . rcu_ctl1_lxtaldri ()) . field ("rcu_ctl1_lckmen" , & self . rcu_ctl1_lckmen ()) . field ("rcu_ctl1_lckmd" , & self . rcu_ctl1_lckmd ()) . field ("rcu_ctl1_lxtalstbrst" , & self . rcu_ctl1_lxtalstbrst ()) . field ("rcu_ctl1_rtcsrc" , & self . rcu_ctl1_rtcsrc ()) . field ("rcu_ctl1_rtcen" , & self . rcu_ctl1_rtcen ()) . field ("rcu_ctl1_bkprst" , & self . rcu_ctl1_bkprst ()) . field ("rcu_ctl1_lsckouten" , & self . rcu_ctl1_lsckouten ()) . field ("rcu_ctl1_lsckoutsel" , & self . rcu_ctl1_lsckoutsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuCtl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuCtl1 {{ rcu_ctl1_lxtalen: {=bool:?}, rcu_ctl1_lxtalstb: {=bool:?}, rcu_ctl1_lxtalbps: {=bool:?}, rcu_ctl1_lxtaldri: {=bool:?}, rcu_ctl1_lckmen: {=bool:?}, rcu_ctl1_lckmd: {=bool:?}, rcu_ctl1_lxtalstbrst: {=bool:?}, rcu_ctl1_rtcsrc: {=u8:?}, rcu_ctl1_rtcen: {=bool:?}, rcu_ctl1_bkprst: {=bool:?}, rcu_ctl1_lsckouten: {=bool:?}, rcu_ctl1_lsckoutsel: {=bool:?} }}" , self . rcu_ctl1_lxtalen () , self . rcu_ctl1_lxtalstb () , self . rcu_ctl1_lxtalbps () , self . rcu_ctl1_lxtaldri () , self . rcu_ctl1_lckmen () , self . rcu_ctl1_lckmd () , self . rcu_ctl1_lxtalstbrst () , self . rcu_ctl1_rtcsrc () , self . rcu_ctl1_rtcen () , self . rcu_ctl1_bkprst () , self . rcu_ctl1_lsckouten () , self . rcu_ctl1_lsckoutsel ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuInt (pub u32) ; impl RcuInt { # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32kstbif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32kstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_lxtalstbif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_lxtalstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc48mstbif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc48mstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_hxtalstbif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_hxtalstbif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_lckmif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_lckmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_ckmif (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_ckmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32kstbie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32kstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_lxtalstbie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_lxtalstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc48mstbie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc48mstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_hxtalstbie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_hxtalstbie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc32kstbic (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc32kstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_lxtalstbic (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_lxtalstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_irc48mstbic (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_irc48mstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_hxtalstbic (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_hxtalstbic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_lckmic (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_lckmic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_int_ckmic (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_int_ckmic (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RcuInt { # [inline (always)]
fn default () -> RcuInt { RcuInt (0) } } impl core :: fmt :: Debug for RcuInt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuInt") . field ("rcu_int_irc32kstbif" , & self . rcu_int_irc32kstbif ()) . field ("rcu_int_lxtalstbif" , & self . rcu_int_lxtalstbif ()) . field ("rcu_int_irc48mstbif" , & self . rcu_int_irc48mstbif ()) . field ("rcu_int_hxtalstbif" , & self . rcu_int_hxtalstbif ()) . field ("rcu_int_lckmif" , & self . rcu_int_lckmif ()) . field ("rcu_int_ckmif" , & self . rcu_int_ckmif ()) . field ("rcu_int_irc32kstbie" , & self . rcu_int_irc32kstbie ()) . field ("rcu_int_lxtalstbie" , & self . rcu_int_lxtalstbie ()) . field ("rcu_int_irc48mstbie" , & self . rcu_int_irc48mstbie ()) . field ("rcu_int_hxtalstbie" , & self . rcu_int_hxtalstbie ()) . field ("rcu_int_irc32kstbic" , & self . rcu_int_irc32kstbic ()) . field ("rcu_int_lxtalstbic" , & self . rcu_int_lxtalstbic ()) . field ("rcu_int_irc48mstbic" , & self . rcu_int_irc48mstbic ()) . field ("rcu_int_hxtalstbic" , & self . rcu_int_hxtalstbic ()) . field ("rcu_int_lckmic" , & self . rcu_int_lckmic ()) . field ("rcu_int_ckmic" , & self . rcu_int_ckmic ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuInt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuInt {{ rcu_int_irc32kstbif: {=bool:?}, rcu_int_lxtalstbif: {=bool:?}, rcu_int_irc48mstbif: {=bool:?}, rcu_int_hxtalstbif: {=bool:?}, rcu_int_lckmif: {=bool:?}, rcu_int_ckmif: {=bool:?}, rcu_int_irc32kstbie: {=bool:?}, rcu_int_lxtalstbie: {=bool:?}, rcu_int_irc48mstbie: {=bool:?}, rcu_int_hxtalstbie: {=bool:?}, rcu_int_irc32kstbic: {=bool:?}, rcu_int_lxtalstbic: {=bool:?}, rcu_int_irc48mstbic: {=bool:?}, rcu_int_hxtalstbic: {=bool:?}, rcu_int_lckmic: {=bool:?}, rcu_int_ckmic: {=bool:?} }}" , self . rcu_int_irc32kstbif () , self . rcu_int_lxtalstbif () , self . rcu_int_irc48mstbif () , self . rcu_int_hxtalstbif () , self . rcu_int_lckmif () , self . rcu_int_ckmif () , self . rcu_int_irc32kstbie () , self . rcu_int_lxtalstbie () , self . rcu_int_irc48mstbie () , self . rcu_int_hxtalstbie () , self . rcu_int_irc32kstbic () , self . rcu_int_lxtalstbic () , self . rcu_int_irc48mstbic () , self . rcu_int_hxtalstbic () , self . rcu_int_lckmic () , self . rcu_int_ckmic ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RcuRstsck (pub u32) ; impl RcuRstsck { # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_irc32ken (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_irc32ken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_irc32kstb (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_irc32kstb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_oblrstf (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_oblrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_rstfc (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_rstfc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_eprstf (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_eprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_porrstf (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_porrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_swrstf (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_swrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_fwdgtrstf (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_fwdgtrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_wwdgtrstf (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_wwdgtrstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn rcu_rstsck_lprstf (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rcu_rstsck_lprstf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for RcuRstsck { # [inline (always)]
fn default () -> RcuRstsck { RcuRstsck (0) } } impl core :: fmt :: Debug for RcuRstsck { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RcuRstsck") . field ("rcu_rstsck_irc32ken" , & self . rcu_rstsck_irc32ken ()) . field ("rcu_rstsck_irc32kstb" , & self . rcu_rstsck_irc32kstb ()) . field ("rcu_rstsck_oblrstf" , & self . rcu_rstsck_oblrstf ()) . field ("rcu_rstsck_rstfc" , & self . rcu_rstsck_rstfc ()) . field ("rcu_rstsck_eprstf" , & self . rcu_rstsck_eprstf ()) . field ("rcu_rstsck_porrstf" , & self . rcu_rstsck_porrstf ()) . field ("rcu_rstsck_swrstf" , & self . rcu_rstsck_swrstf ()) . field ("rcu_rstsck_fwdgtrstf" , & self . rcu_rstsck_fwdgtrstf ()) . field ("rcu_rstsck_wwdgtrstf" , & self . rcu_rstsck_wwdgtrstf ()) . field ("rcu_rstsck_lprstf" , & self . rcu_rstsck_lprstf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RcuRstsck { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RcuRstsck {{ rcu_rstsck_irc32ken: {=bool:?}, rcu_rstsck_irc32kstb: {=bool:?}, rcu_rstsck_oblrstf: {=bool:?}, rcu_rstsck_rstfc: {=bool:?}, rcu_rstsck_eprstf: {=bool:?}, rcu_rstsck_porrstf: {=bool:?}, rcu_rstsck_swrstf: {=bool:?}, rcu_rstsck_fwdgtrstf: {=bool:?}, rcu_rstsck_wwdgtrstf: {=bool:?}, rcu_rstsck_lprstf: {=bool:?} }}" , self . rcu_rstsck_irc32ken () , self . rcu_rstsck_irc32kstb () , self . rcu_rstsck_oblrstf () , self . rcu_rstsck_rstfc () , self . rcu_rstsck_eprstf () , self . rcu_rstsck_porrstf () , self . rcu_rstsck_swrstf () , self . rcu_rstsck_fwdgtrstf () , self . rcu_rstsck_wwdgtrstf () , self . rcu_rstsck_lprstf ()) } } }