#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rtc { ptr : * mut u8 } unsafe impl Send for Rtc { } unsafe impl Sync for Rtc { } impl Rtc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn rtc_inten (self) -> crate :: common :: Reg < regs :: RtcInten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [inline (always)]
pub const fn rtc_ctl (self) -> crate :: common :: Reg < regs :: RtcCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [inline (always)]
pub const fn rtc_psch (self) -> crate :: common :: Reg < regs :: RtcPsch , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [inline (always)]
pub const fn rtc_pscl (self) -> crate :: common :: Reg < regs :: RtcPscl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [inline (always)]
pub const fn rtc_divh (self) -> crate :: common :: Reg < regs :: RtcDivh , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [inline (always)]
pub const fn rtc_divl (self) -> crate :: common :: Reg < regs :: RtcDivl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [inline (always)]
pub const fn rtc_cnth (self) -> crate :: common :: Reg < regs :: RtcCnth , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [inline (always)]
pub const fn rtc_cntl (self) -> crate :: common :: Reg < regs :: RtcCntl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [inline (always)]
pub const fn rtc_alrmh (self) -> crate :: common :: Reg < regs :: RtcAlrmh , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [inline (always)]
pub const fn rtc_alrml (self) -> crate :: common :: Reg < regs :: RtcAlrml , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcAlrmh (pub u32) ; impl RtcAlrmh { # [inline (always)]
pub const fn rtc_alrmh_alrm (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub fn set_rtc_alrmh_alrm (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcAlrmh { # [inline (always)]
fn default () -> RtcAlrmh { RtcAlrmh (0) } } impl core :: fmt :: Debug for RtcAlrmh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcAlrmh") . field ("rtc_alrmh_alrm" , & self . rtc_alrmh_alrm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcAlrmh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcAlrmh {{ rtc_alrmh_alrm: {=u16:?} }}" , self . rtc_alrmh_alrm ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcAlrml (pub u32) ; impl RtcAlrml { # [inline (always)]
pub const fn rtc_alrml_alrm (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub fn set_rtc_alrml_alrm (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcAlrml { # [inline (always)]
fn default () -> RtcAlrml { RtcAlrml (0) } } impl core :: fmt :: Debug for RtcAlrml { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcAlrml") . field ("rtc_alrml_alrm" , & self . rtc_alrml_alrm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcAlrml { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcAlrml {{ rtc_alrml_alrm: {=u16:?} }}" , self . rtc_alrml_alrm ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcCnth (pub u32) ; impl RtcCnth { # [inline (always)]
pub const fn rtc_cnth_cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub fn set_rtc_cnth_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcCnth { # [inline (always)]
fn default () -> RtcCnth { RtcCnth (0) } } impl core :: fmt :: Debug for RtcCnth { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcCnth") . field ("rtc_cnth_cnt" , & self . rtc_cnth_cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcCnth { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcCnth {{ rtc_cnth_cnt: {=u16:?} }}" , self . rtc_cnth_cnt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcCntl (pub u32) ; impl RtcCntl { # [inline (always)]
pub const fn rtc_cntl_cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub fn set_rtc_cntl_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcCntl { # [inline (always)]
fn default () -> RtcCntl { RtcCntl (0) } } impl core :: fmt :: Debug for RtcCntl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcCntl") . field ("rtc_cntl_cnt" , & self . rtc_cntl_cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcCntl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcCntl {{ rtc_cntl_cnt: {=u16:?} }}" , self . rtc_cntl_cnt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcCtl (pub u32) ; impl RtcCtl { # [inline (always)]
pub const fn rtc_ctl_scif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_ctl_scif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [inline (always)]
pub const fn rtc_ctl_alrmif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_ctl_alrmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [inline (always)]
pub const fn rtc_ctl_ovif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_ctl_ovif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [inline (always)]
pub const fn rtc_ctl_rsynf (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_ctl_rsynf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [inline (always)]
pub const fn rtc_ctl_cmf (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_ctl_cmf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [inline (always)]
pub const fn rtc_ctl_lwoff (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_ctl_lwoff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for RtcCtl { # [inline (always)]
fn default () -> RtcCtl { RtcCtl (0) } } impl core :: fmt :: Debug for RtcCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcCtl") . field ("rtc_ctl_scif" , & self . rtc_ctl_scif ()) . field ("rtc_ctl_alrmif" , & self . rtc_ctl_alrmif ()) . field ("rtc_ctl_ovif" , & self . rtc_ctl_ovif ()) . field ("rtc_ctl_rsynf" , & self . rtc_ctl_rsynf ()) . field ("rtc_ctl_cmf" , & self . rtc_ctl_cmf ()) . field ("rtc_ctl_lwoff" , & self . rtc_ctl_lwoff ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcCtl {{ rtc_ctl_scif: {=bool:?}, rtc_ctl_alrmif: {=bool:?}, rtc_ctl_ovif: {=bool:?}, rtc_ctl_rsynf: {=bool:?}, rtc_ctl_cmf: {=bool:?}, rtc_ctl_lwoff: {=bool:?} }}" , self . rtc_ctl_scif () , self . rtc_ctl_alrmif () , self . rtc_ctl_ovif () , self . rtc_ctl_rsynf () , self . rtc_ctl_cmf () , self . rtc_ctl_lwoff ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcDivh (pub u32) ; impl RtcDivh { # [inline (always)]
pub const fn rtc_divh_div (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub fn set_rtc_divh_div (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } } impl Default for RtcDivh { # [inline (always)]
fn default () -> RtcDivh { RtcDivh (0) } } impl core :: fmt :: Debug for RtcDivh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcDivh") . field ("rtc_divh_div" , & self . rtc_divh_div ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcDivh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcDivh {{ rtc_divh_div: {=u8:?} }}" , self . rtc_divh_div ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcDivl (pub u32) ; impl RtcDivl { # [inline (always)]
pub const fn rtc_divl_div (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub fn set_rtc_divl_div (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcDivl { # [inline (always)]
fn default () -> RtcDivl { RtcDivl (0) } } impl core :: fmt :: Debug for RtcDivl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcDivl") . field ("rtc_divl_div" , & self . rtc_divl_div ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcDivl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcDivl {{ rtc_divl_div: {=u16:?} }}" , self . rtc_divl_div ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcInten (pub u32) ; impl RtcInten { # [inline (always)]
pub const fn rtc_inten_scie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_inten_scie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [inline (always)]
pub const fn rtc_inten_alrmie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_inten_alrmie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [inline (always)]
pub const fn rtc_inten_ovie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_rtc_inten_ovie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for RtcInten { # [inline (always)]
fn default () -> RtcInten { RtcInten (0) } } impl core :: fmt :: Debug for RtcInten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcInten") . field ("rtc_inten_scie" , & self . rtc_inten_scie ()) . field ("rtc_inten_alrmie" , & self . rtc_inten_alrmie ()) . field ("rtc_inten_ovie" , & self . rtc_inten_ovie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcInten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcInten {{ rtc_inten_scie: {=bool:?}, rtc_inten_alrmie: {=bool:?}, rtc_inten_ovie: {=bool:?} }}" , self . rtc_inten_scie () , self . rtc_inten_alrmie () , self . rtc_inten_ovie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcPsch (pub u32) ; impl RtcPsch { # [inline (always)]
pub const fn rtc_psch_psc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub fn set_rtc_psch_psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } } impl Default for RtcPsch { # [inline (always)]
fn default () -> RtcPsch { RtcPsch (0) } } impl core :: fmt :: Debug for RtcPsch { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcPsch") . field ("rtc_psch_psc" , & self . rtc_psch_psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcPsch { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcPsch {{ rtc_psch_psc: {=u8:?} }}" , self . rtc_psch_psc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcPscl (pub u32) ; impl RtcPscl { # [inline (always)]
pub const fn rtc_pscl_psc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub fn set_rtc_pscl_psc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcPscl { # [inline (always)]
fn default () -> RtcPscl { RtcPscl (0) } } impl core :: fmt :: Debug for RtcPscl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcPscl") . field ("rtc_pscl_psc" , & self . rtc_pscl_psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcPscl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcPscl {{ rtc_pscl_psc: {=u16:?} }}" , self . rtc_pscl_psc ()) } } }