#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rtc { ptr : * mut u8 } unsafe impl Send for Rtc { } unsafe impl Sync for Rtc { } impl Rtc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn rtc_time (self) -> crate :: common :: Reg < regs :: RtcTime , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn rtc_date (self) -> crate :: common :: Reg < regs :: RtcDate , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn rtc_ctl (self) -> crate :: common :: Reg < regs :: RtcCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn rtc_stat (self) -> crate :: common :: Reg < regs :: RtcStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn rtc_psc (self) -> crate :: common :: Reg < regs :: RtcPsc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn rtc_alrm0td (self) -> crate :: common :: Reg < regs :: RtcAlrm0td , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn rtc_wpk (self) -> crate :: common :: Reg < regs :: RtcWpk , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn rtc_ss (self) -> crate :: common :: Reg < regs :: RtcSs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn rtc_shiftctl (self) -> crate :: common :: Reg < regs :: RtcShiftctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn rtc_tts (self) -> crate :: common :: Reg < regs :: RtcTts , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn rtc_dts (self) -> crate :: common :: Reg < regs :: RtcDts , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn rtc_ssts (self) -> crate :: common :: Reg < regs :: RtcSsts , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn rtc_hrfc (self) -> crate :: common :: Reg < regs :: RtcHrfc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn rtc_tamp (self) -> crate :: common :: Reg < regs :: RtcTamp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn rtc_alrm0ss (self) -> crate :: common :: Reg < regs :: RtcAlrm0ss , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn rtc_bkp0 (self) -> crate :: common :: Reg < regs :: RtcBkp0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x50usize) as _) } } # [inline (always)]
pub const fn rtc_bkp1 (self) -> crate :: common :: Reg < regs :: RtcBkp1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x54usize) as _) } } # [inline (always)]
pub const fn rtc_bkp2 (self) -> crate :: common :: Reg < regs :: RtcBkp2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x58usize) as _) } } # [inline (always)]
pub const fn rtc_bkp3 (self) -> crate :: common :: Reg < regs :: RtcBkp3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x5cusize) as _) } } # [inline (always)]
pub const fn rtc_bkp4 (self) -> crate :: common :: Reg < regs :: RtcBkp4 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x60usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcAlrm0ss (pub u32) ; impl RtcAlrm0ss { # [must_use]
# [inline (always)]
pub const fn rtc_alrm0ss_ssc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x7fff ; val as u16 } # [inline (always)]
pub const fn set_rtc_alrm0ss_ssc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x7fff << 0usize)) | (((val as u32) & 0x7fff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0ss_maskssc (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0ss_maskssc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } } impl Default for RtcAlrm0ss { # [inline (always)]
fn default () -> RtcAlrm0ss { RtcAlrm0ss (0) } } impl core :: fmt :: Debug for RtcAlrm0ss { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcAlrm0ss") . field ("rtc_alrm0ss_ssc" , & self . rtc_alrm0ss_ssc ()) . field ("rtc_alrm0ss_maskssc" , & self . rtc_alrm0ss_maskssc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcAlrm0ss { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcAlrm0ss {{ rtc_alrm0ss_ssc: {=u16:?}, rtc_alrm0ss_maskssc: {=u8:?} }}" , self . rtc_alrm0ss_ssc () , self . rtc_alrm0ss_maskssc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcAlrm0td (pub u32) ; impl RtcAlrm0td { # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_scu (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_scu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_sct (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_sct (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_msks (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_alrm0td_msks (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_mnu (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_mnu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_mnt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_mnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_mskm (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_alrm0td_mskm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_hru (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_hru (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_hrt (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_hrt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_pm (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_alrm0td_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_mskh (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_alrm0td_mskh (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_dayu (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_dayu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_dayt (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_alrm0td_dayt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_dows (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_alrm0td_dows (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_alrm0td_mskd (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_alrm0td_mskd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for RtcAlrm0td { # [inline (always)]
fn default () -> RtcAlrm0td { RtcAlrm0td (0) } } impl core :: fmt :: Debug for RtcAlrm0td { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcAlrm0td") . field ("rtc_alrm0td_scu" , & self . rtc_alrm0td_scu ()) . field ("rtc_alrm0td_sct" , & self . rtc_alrm0td_sct ()) . field ("rtc_alrm0td_msks" , & self . rtc_alrm0td_msks ()) . field ("rtc_alrm0td_mnu" , & self . rtc_alrm0td_mnu ()) . field ("rtc_alrm0td_mnt" , & self . rtc_alrm0td_mnt ()) . field ("rtc_alrm0td_mskm" , & self . rtc_alrm0td_mskm ()) . field ("rtc_alrm0td_hru" , & self . rtc_alrm0td_hru ()) . field ("rtc_alrm0td_hrt" , & self . rtc_alrm0td_hrt ()) . field ("rtc_alrm0td_pm" , & self . rtc_alrm0td_pm ()) . field ("rtc_alrm0td_mskh" , & self . rtc_alrm0td_mskh ()) . field ("rtc_alrm0td_dayu" , & self . rtc_alrm0td_dayu ()) . field ("rtc_alrm0td_dayt" , & self . rtc_alrm0td_dayt ()) . field ("rtc_alrm0td_dows" , & self . rtc_alrm0td_dows ()) . field ("rtc_alrm0td_mskd" , & self . rtc_alrm0td_mskd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcAlrm0td { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcAlrm0td {{ rtc_alrm0td_scu: {=u8:?}, rtc_alrm0td_sct: {=u8:?}, rtc_alrm0td_msks: {=bool:?}, rtc_alrm0td_mnu: {=u8:?}, rtc_alrm0td_mnt: {=u8:?}, rtc_alrm0td_mskm: {=bool:?}, rtc_alrm0td_hru: {=u8:?}, rtc_alrm0td_hrt: {=u8:?}, rtc_alrm0td_pm: {=bool:?}, rtc_alrm0td_mskh: {=bool:?}, rtc_alrm0td_dayu: {=u8:?}, rtc_alrm0td_dayt: {=u8:?}, rtc_alrm0td_dows: {=bool:?}, rtc_alrm0td_mskd: {=bool:?} }}" , self . rtc_alrm0td_scu () , self . rtc_alrm0td_sct () , self . rtc_alrm0td_msks () , self . rtc_alrm0td_mnu () , self . rtc_alrm0td_mnt () , self . rtc_alrm0td_mskm () , self . rtc_alrm0td_hru () , self . rtc_alrm0td_hrt () , self . rtc_alrm0td_pm () , self . rtc_alrm0td_mskh () , self . rtc_alrm0td_dayu () , self . rtc_alrm0td_dayt () , self . rtc_alrm0td_dows () , self . rtc_alrm0td_mskd ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcBkp0 (pub u32) ; impl RtcBkp0 { # [must_use]
# [inline (always)]
pub const fn rtc_bkp0_data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_rtc_bkp0_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for RtcBkp0 { # [inline (always)]
fn default () -> RtcBkp0 { RtcBkp0 (0) } } impl core :: fmt :: Debug for RtcBkp0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcBkp0") . field ("rtc_bkp0_data" , & self . rtc_bkp0_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcBkp0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcBkp0 {{ rtc_bkp0_data: {=u32:?} }}" , self . rtc_bkp0_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcBkp1 (pub u32) ; impl RtcBkp1 { # [must_use]
# [inline (always)]
pub const fn rtc_bkp1_data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_rtc_bkp1_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for RtcBkp1 { # [inline (always)]
fn default () -> RtcBkp1 { RtcBkp1 (0) } } impl core :: fmt :: Debug for RtcBkp1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcBkp1") . field ("rtc_bkp1_data" , & self . rtc_bkp1_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcBkp1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcBkp1 {{ rtc_bkp1_data: {=u32:?} }}" , self . rtc_bkp1_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcBkp2 (pub u32) ; impl RtcBkp2 { # [must_use]
# [inline (always)]
pub const fn rtc_bkp2_data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_rtc_bkp2_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for RtcBkp2 { # [inline (always)]
fn default () -> RtcBkp2 { RtcBkp2 (0) } } impl core :: fmt :: Debug for RtcBkp2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcBkp2") . field ("rtc_bkp2_data" , & self . rtc_bkp2_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcBkp2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcBkp2 {{ rtc_bkp2_data: {=u32:?} }}" , self . rtc_bkp2_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcBkp3 (pub u32) ; impl RtcBkp3 { # [must_use]
# [inline (always)]
pub const fn rtc_bkp3_data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_rtc_bkp3_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for RtcBkp3 { # [inline (always)]
fn default () -> RtcBkp3 { RtcBkp3 (0) } } impl core :: fmt :: Debug for RtcBkp3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcBkp3") . field ("rtc_bkp3_data" , & self . rtc_bkp3_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcBkp3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcBkp3 {{ rtc_bkp3_data: {=u32:?} }}" , self . rtc_bkp3_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcBkp4 (pub u32) ; impl RtcBkp4 { # [must_use]
# [inline (always)]
pub const fn rtc_bkp4_data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_rtc_bkp4_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for RtcBkp4 { # [inline (always)]
fn default () -> RtcBkp4 { RtcBkp4 (0) } } impl core :: fmt :: Debug for RtcBkp4 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcBkp4") . field ("rtc_bkp4_data" , & self . rtc_bkp4_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcBkp4 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcBkp4 {{ rtc_bkp4_data: {=u32:?} }}" , self . rtc_bkp4_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcCtl (pub u32) ; impl RtcCtl { # [must_use]
# [inline (always)]
pub const fn rtc_ctl_tseg (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_tseg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_refen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_refen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_bpshad (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_bpshad (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_cs (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_cs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_alrm0en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_alrm0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_tsen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_tsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_alrm0ie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_alrm0ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_tsie (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_tsie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_a1h (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_a1h (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_s1h (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_s1h (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_dsm (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_dsm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_cos (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_cos (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_opol (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_opol (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_os (& self) -> u8 { let val = (self . 0 >> 21usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_ctl_os (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 21usize)) | (((val as u32) & 0x03) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_ctl_coen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_ctl_coen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RtcCtl { # [inline (always)]
fn default () -> RtcCtl { RtcCtl (0) } } impl core :: fmt :: Debug for RtcCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcCtl") . field ("rtc_ctl_tseg" , & self . rtc_ctl_tseg ()) . field ("rtc_ctl_refen" , & self . rtc_ctl_refen ()) . field ("rtc_ctl_bpshad" , & self . rtc_ctl_bpshad ()) . field ("rtc_ctl_cs" , & self . rtc_ctl_cs ()) . field ("rtc_ctl_alrm0en" , & self . rtc_ctl_alrm0en ()) . field ("rtc_ctl_tsen" , & self . rtc_ctl_tsen ()) . field ("rtc_ctl_alrm0ie" , & self . rtc_ctl_alrm0ie ()) . field ("rtc_ctl_tsie" , & self . rtc_ctl_tsie ()) . field ("rtc_ctl_a1h" , & self . rtc_ctl_a1h ()) . field ("rtc_ctl_s1h" , & self . rtc_ctl_s1h ()) . field ("rtc_ctl_dsm" , & self . rtc_ctl_dsm ()) . field ("rtc_ctl_cos" , & self . rtc_ctl_cos ()) . field ("rtc_ctl_opol" , & self . rtc_ctl_opol ()) . field ("rtc_ctl_os" , & self . rtc_ctl_os ()) . field ("rtc_ctl_coen" , & self . rtc_ctl_coen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcCtl {{ rtc_ctl_tseg: {=bool:?}, rtc_ctl_refen: {=bool:?}, rtc_ctl_bpshad: {=bool:?}, rtc_ctl_cs: {=bool:?}, rtc_ctl_alrm0en: {=bool:?}, rtc_ctl_tsen: {=bool:?}, rtc_ctl_alrm0ie: {=bool:?}, rtc_ctl_tsie: {=bool:?}, rtc_ctl_a1h: {=bool:?}, rtc_ctl_s1h: {=bool:?}, rtc_ctl_dsm: {=bool:?}, rtc_ctl_cos: {=bool:?}, rtc_ctl_opol: {=bool:?}, rtc_ctl_os: {=u8:?}, rtc_ctl_coen: {=bool:?} }}" , self . rtc_ctl_tseg () , self . rtc_ctl_refen () , self . rtc_ctl_bpshad () , self . rtc_ctl_cs () , self . rtc_ctl_alrm0en () , self . rtc_ctl_tsen () , self . rtc_ctl_alrm0ie () , self . rtc_ctl_tsie () , self . rtc_ctl_a1h () , self . rtc_ctl_s1h () , self . rtc_ctl_dsm () , self . rtc_ctl_cos () , self . rtc_ctl_opol () , self . rtc_ctl_os () , self . rtc_ctl_coen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcDate (pub u32) ; impl RtcDate { # [must_use]
# [inline (always)]
pub const fn rtc_date_dayu (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_date_dayu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_date_dayt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_date_dayt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_date_monu (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_date_monu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_date_mont (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_date_mont (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_date_dow (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_date_dow (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 13usize)) | (((val as u32) & 0x07) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_date_yru (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_date_yru (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_date_yrt (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_date_yrt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 20usize)) | (((val as u32) & 0x0f) << 20usize) ; } } impl Default for RtcDate { # [inline (always)]
fn default () -> RtcDate { RtcDate (0) } } impl core :: fmt :: Debug for RtcDate { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcDate") . field ("rtc_date_dayu" , & self . rtc_date_dayu ()) . field ("rtc_date_dayt" , & self . rtc_date_dayt ()) . field ("rtc_date_monu" , & self . rtc_date_monu ()) . field ("rtc_date_mont" , & self . rtc_date_mont ()) . field ("rtc_date_dow" , & self . rtc_date_dow ()) . field ("rtc_date_yru" , & self . rtc_date_yru ()) . field ("rtc_date_yrt" , & self . rtc_date_yrt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcDate { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcDate {{ rtc_date_dayu: {=u8:?}, rtc_date_dayt: {=u8:?}, rtc_date_monu: {=u8:?}, rtc_date_mont: {=bool:?}, rtc_date_dow: {=u8:?}, rtc_date_yru: {=u8:?}, rtc_date_yrt: {=u8:?} }}" , self . rtc_date_dayu () , self . rtc_date_dayt () , self . rtc_date_monu () , self . rtc_date_mont () , self . rtc_date_dow () , self . rtc_date_yru () , self . rtc_date_yrt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcDts (pub u32) ; impl RtcDts { # [must_use]
# [inline (always)]
pub const fn rtc_dts_dayu (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_dts_dayu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_dts_dayt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_dts_dayt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_dts_monu (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_dts_monu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_dts_mont (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_dts_mont (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_dts_dow (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_dts_dow (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 13usize)) | (((val as u32) & 0x07) << 13usize) ; } } impl Default for RtcDts { # [inline (always)]
fn default () -> RtcDts { RtcDts (0) } } impl core :: fmt :: Debug for RtcDts { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcDts") . field ("rtc_dts_dayu" , & self . rtc_dts_dayu ()) . field ("rtc_dts_dayt" , & self . rtc_dts_dayt ()) . field ("rtc_dts_monu" , & self . rtc_dts_monu ()) . field ("rtc_dts_mont" , & self . rtc_dts_mont ()) . field ("rtc_dts_dow" , & self . rtc_dts_dow ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcDts { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcDts {{ rtc_dts_dayu: {=u8:?}, rtc_dts_dayt: {=u8:?}, rtc_dts_monu: {=u8:?}, rtc_dts_mont: {=bool:?}, rtc_dts_dow: {=u8:?} }}" , self . rtc_dts_dayu () , self . rtc_dts_dayt () , self . rtc_dts_monu () , self . rtc_dts_mont () , self . rtc_dts_dow ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcHrfc (pub u32) ; impl RtcHrfc { # [must_use]
# [inline (always)]
pub const fn rtc_hrfc_cmsk (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x01ff ; val as u16 } # [inline (always)]
pub const fn set_rtc_hrfc_cmsk (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x01ff << 0usize)) | (((val as u32) & 0x01ff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_hrfc_cwnd16 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_hrfc_cwnd16 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_hrfc_cwnd8 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_hrfc_cwnd8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_hrfc_freqi (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_hrfc_freqi (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for RtcHrfc { # [inline (always)]
fn default () -> RtcHrfc { RtcHrfc (0) } } impl core :: fmt :: Debug for RtcHrfc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcHrfc") . field ("rtc_hrfc_cmsk" , & self . rtc_hrfc_cmsk ()) . field ("rtc_hrfc_cwnd16" , & self . rtc_hrfc_cwnd16 ()) . field ("rtc_hrfc_cwnd8" , & self . rtc_hrfc_cwnd8 ()) . field ("rtc_hrfc_freqi" , & self . rtc_hrfc_freqi ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcHrfc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcHrfc {{ rtc_hrfc_cmsk: {=u16:?}, rtc_hrfc_cwnd16: {=bool:?}, rtc_hrfc_cwnd8: {=bool:?}, rtc_hrfc_freqi: {=bool:?} }}" , self . rtc_hrfc_cmsk () , self . rtc_hrfc_cwnd16 () , self . rtc_hrfc_cwnd8 () , self . rtc_hrfc_freqi ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcPsc (pub u32) ; impl RtcPsc { # [must_use]
# [inline (always)]
pub const fn rtc_psc_factor_s (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x7fff ; val as u16 } # [inline (always)]
pub const fn set_rtc_psc_factor_s (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x7fff << 0usize)) | (((val as u32) & 0x7fff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_psc_factor_a (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x7f ; val as u8 } # [inline (always)]
pub const fn set_rtc_psc_factor_a (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 16usize)) | (((val as u32) & 0x7f) << 16usize) ; } } impl Default for RtcPsc { # [inline (always)]
fn default () -> RtcPsc { RtcPsc (0) } } impl core :: fmt :: Debug for RtcPsc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcPsc") . field ("rtc_psc_factor_s" , & self . rtc_psc_factor_s ()) . field ("rtc_psc_factor_a" , & self . rtc_psc_factor_a ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcPsc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcPsc {{ rtc_psc_factor_s: {=u16:?}, rtc_psc_factor_a: {=u8:?} }}" , self . rtc_psc_factor_s () , self . rtc_psc_factor_a ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcShiftctl (pub u32) ; impl RtcShiftctl { # [must_use]
# [inline (always)]
pub const fn rtc_shiftctl_sfs (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x7fff ; val as u16 } # [inline (always)]
pub const fn set_rtc_shiftctl_sfs (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x7fff << 0usize)) | (((val as u32) & 0x7fff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_shiftctl_a1s (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_shiftctl_a1s (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for RtcShiftctl { # [inline (always)]
fn default () -> RtcShiftctl { RtcShiftctl (0) } } impl core :: fmt :: Debug for RtcShiftctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcShiftctl") . field ("rtc_shiftctl_sfs" , & self . rtc_shiftctl_sfs ()) . field ("rtc_shiftctl_a1s" , & self . rtc_shiftctl_a1s ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcShiftctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcShiftctl {{ rtc_shiftctl_sfs: {=u16:?}, rtc_shiftctl_a1s: {=bool:?} }}" , self . rtc_shiftctl_sfs () , self . rtc_shiftctl_a1s ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcSs (pub u32) ; impl RtcSs { # [must_use]
# [inline (always)]
pub const fn rtc_ss_ssc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_rtc_ss_ssc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcSs { # [inline (always)]
fn default () -> RtcSs { RtcSs (0) } } impl core :: fmt :: Debug for RtcSs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcSs") . field ("rtc_ss_ssc" , & self . rtc_ss_ssc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcSs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcSs {{ rtc_ss_ssc: {=u16:?} }}" , self . rtc_ss_ssc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcSsts (pub u32) ; impl RtcSsts { # [must_use]
# [inline (always)]
pub const fn rtc_ssts_ssc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_rtc_ssts_ssc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for RtcSsts { # [inline (always)]
fn default () -> RtcSsts { RtcSsts (0) } } impl core :: fmt :: Debug for RtcSsts { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcSsts") . field ("rtc_ssts_ssc" , & self . rtc_ssts_ssc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcSsts { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcSsts {{ rtc_ssts_ssc: {=u16:?} }}" , self . rtc_ssts_ssc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcStat (pub u32) ; impl RtcStat { # [must_use]
# [inline (always)]
pub const fn rtc_stat_alrm0wf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_alrm0wf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_sopf (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_sopf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_ycm (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_ycm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_rsynf (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_rsynf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_initf (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_initf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_initm (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_initm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_alrm0f (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_alrm0f (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_tsf (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_tsf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_tsovrf (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_tsovrf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_tp0f (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_tp0f (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_tp1f (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_tp1f (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_stat_scpf (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_stat_scpf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for RtcStat { # [inline (always)]
fn default () -> RtcStat { RtcStat (0) } } impl core :: fmt :: Debug for RtcStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcStat") . field ("rtc_stat_alrm0wf" , & self . rtc_stat_alrm0wf ()) . field ("rtc_stat_sopf" , & self . rtc_stat_sopf ()) . field ("rtc_stat_ycm" , & self . rtc_stat_ycm ()) . field ("rtc_stat_rsynf" , & self . rtc_stat_rsynf ()) . field ("rtc_stat_initf" , & self . rtc_stat_initf ()) . field ("rtc_stat_initm" , & self . rtc_stat_initm ()) . field ("rtc_stat_alrm0f" , & self . rtc_stat_alrm0f ()) . field ("rtc_stat_tsf" , & self . rtc_stat_tsf ()) . field ("rtc_stat_tsovrf" , & self . rtc_stat_tsovrf ()) . field ("rtc_stat_tp0f" , & self . rtc_stat_tp0f ()) . field ("rtc_stat_tp1f" , & self . rtc_stat_tp1f ()) . field ("rtc_stat_scpf" , & self . rtc_stat_scpf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcStat {{ rtc_stat_alrm0wf: {=bool:?}, rtc_stat_sopf: {=bool:?}, rtc_stat_ycm: {=bool:?}, rtc_stat_rsynf: {=bool:?}, rtc_stat_initf: {=bool:?}, rtc_stat_initm: {=bool:?}, rtc_stat_alrm0f: {=bool:?}, rtc_stat_tsf: {=bool:?}, rtc_stat_tsovrf: {=bool:?}, rtc_stat_tp0f: {=bool:?}, rtc_stat_tp1f: {=bool:?}, rtc_stat_scpf: {=bool:?} }}" , self . rtc_stat_alrm0wf () , self . rtc_stat_sopf () , self . rtc_stat_ycm () , self . rtc_stat_rsynf () , self . rtc_stat_initf () , self . rtc_stat_initm () , self . rtc_stat_alrm0f () , self . rtc_stat_tsf () , self . rtc_stat_tsovrf () , self . rtc_stat_tp0f () , self . rtc_stat_tp1f () , self . rtc_stat_scpf ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcTamp (pub u32) ; impl RtcTamp { # [must_use]
# [inline (always)]
pub const fn rtc_tamp_tp0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_tp0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_tp0eg (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_tp0eg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_tpie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_tpie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_tp1en (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_tp1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_tp1eg (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_tp1eg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_tpts (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_tpts (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_freq (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_tamp_freq (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 8usize)) | (((val as u32) & 0x07) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_flt (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_tamp_flt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 11usize)) | (((val as u32) & 0x03) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_prch (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_tamp_prch (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 13usize)) | (((val as u32) & 0x03) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_dispu (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_dispu (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_pc13val (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_pc13val (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_pc13mde (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_pc13mde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_pc14val (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_pc14val (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_pc14mde (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_pc14mde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_pc15val (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_pc15val (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tamp_pc15mde (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tamp_pc15mde (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for RtcTamp { # [inline (always)]
fn default () -> RtcTamp { RtcTamp (0) } } impl core :: fmt :: Debug for RtcTamp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcTamp") . field ("rtc_tamp_tp0en" , & self . rtc_tamp_tp0en ()) . field ("rtc_tamp_tp0eg" , & self . rtc_tamp_tp0eg ()) . field ("rtc_tamp_tpie" , & self . rtc_tamp_tpie ()) . field ("rtc_tamp_tp1en" , & self . rtc_tamp_tp1en ()) . field ("rtc_tamp_tp1eg" , & self . rtc_tamp_tp1eg ()) . field ("rtc_tamp_tpts" , & self . rtc_tamp_tpts ()) . field ("rtc_tamp_freq" , & self . rtc_tamp_freq ()) . field ("rtc_tamp_flt" , & self . rtc_tamp_flt ()) . field ("rtc_tamp_prch" , & self . rtc_tamp_prch ()) . field ("rtc_tamp_dispu" , & self . rtc_tamp_dispu ()) . field ("rtc_tamp_pc13val" , & self . rtc_tamp_pc13val ()) . field ("rtc_tamp_pc13mde" , & self . rtc_tamp_pc13mde ()) . field ("rtc_tamp_pc14val" , & self . rtc_tamp_pc14val ()) . field ("rtc_tamp_pc14mde" , & self . rtc_tamp_pc14mde ()) . field ("rtc_tamp_pc15val" , & self . rtc_tamp_pc15val ()) . field ("rtc_tamp_pc15mde" , & self . rtc_tamp_pc15mde ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcTamp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcTamp {{ rtc_tamp_tp0en: {=bool:?}, rtc_tamp_tp0eg: {=bool:?}, rtc_tamp_tpie: {=bool:?}, rtc_tamp_tp1en: {=bool:?}, rtc_tamp_tp1eg: {=bool:?}, rtc_tamp_tpts: {=bool:?}, rtc_tamp_freq: {=u8:?}, rtc_tamp_flt: {=u8:?}, rtc_tamp_prch: {=u8:?}, rtc_tamp_dispu: {=bool:?}, rtc_tamp_pc13val: {=bool:?}, rtc_tamp_pc13mde: {=bool:?}, rtc_tamp_pc14val: {=bool:?}, rtc_tamp_pc14mde: {=bool:?}, rtc_tamp_pc15val: {=bool:?}, rtc_tamp_pc15mde: {=bool:?} }}" , self . rtc_tamp_tp0en () , self . rtc_tamp_tp0eg () , self . rtc_tamp_tpie () , self . rtc_tamp_tp1en () , self . rtc_tamp_tp1eg () , self . rtc_tamp_tpts () , self . rtc_tamp_freq () , self . rtc_tamp_flt () , self . rtc_tamp_prch () , self . rtc_tamp_dispu () , self . rtc_tamp_pc13val () , self . rtc_tamp_pc13mde () , self . rtc_tamp_pc14val () , self . rtc_tamp_pc14mde () , self . rtc_tamp_pc15val () , self . rtc_tamp_pc15mde ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcTime (pub u32) ; impl RtcTime { # [must_use]
# [inline (always)]
pub const fn rtc_time_scu (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_time_scu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_time_sct (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_time_sct (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_time_mnu (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_time_mnu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_time_mnt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_time_mnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_time_hru (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_time_hru (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_time_hrt (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_time_hrt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_time_pm (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_time_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for RtcTime { # [inline (always)]
fn default () -> RtcTime { RtcTime (0) } } impl core :: fmt :: Debug for RtcTime { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcTime") . field ("rtc_time_scu" , & self . rtc_time_scu ()) . field ("rtc_time_sct" , & self . rtc_time_sct ()) . field ("rtc_time_mnu" , & self . rtc_time_mnu ()) . field ("rtc_time_mnt" , & self . rtc_time_mnt ()) . field ("rtc_time_hru" , & self . rtc_time_hru ()) . field ("rtc_time_hrt" , & self . rtc_time_hrt ()) . field ("rtc_time_pm" , & self . rtc_time_pm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcTime { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcTime {{ rtc_time_scu: {=u8:?}, rtc_time_sct: {=u8:?}, rtc_time_mnu: {=u8:?}, rtc_time_mnt: {=u8:?}, rtc_time_hru: {=u8:?}, rtc_time_hrt: {=u8:?}, rtc_time_pm: {=bool:?} }}" , self . rtc_time_scu () , self . rtc_time_sct () , self . rtc_time_mnu () , self . rtc_time_mnt () , self . rtc_time_hru () , self . rtc_time_hrt () , self . rtc_time_pm ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcTts (pub u32) ; impl RtcTts { # [must_use]
# [inline (always)]
pub const fn rtc_tts_scu (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_tts_scu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tts_sct (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_tts_sct (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tts_mnu (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_tts_mnu (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tts_mnt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_rtc_tts_mnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tts_hru (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_rtc_tts_hru (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tts_hrt (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_rtc_tts_hrt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn rtc_tts_pm (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_rtc_tts_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for RtcTts { # [inline (always)]
fn default () -> RtcTts { RtcTts (0) } } impl core :: fmt :: Debug for RtcTts { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcTts") . field ("rtc_tts_scu" , & self . rtc_tts_scu ()) . field ("rtc_tts_sct" , & self . rtc_tts_sct ()) . field ("rtc_tts_mnu" , & self . rtc_tts_mnu ()) . field ("rtc_tts_mnt" , & self . rtc_tts_mnt ()) . field ("rtc_tts_hru" , & self . rtc_tts_hru ()) . field ("rtc_tts_hrt" , & self . rtc_tts_hrt ()) . field ("rtc_tts_pm" , & self . rtc_tts_pm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcTts { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcTts {{ rtc_tts_scu: {=u8:?}, rtc_tts_sct: {=u8:?}, rtc_tts_mnu: {=u8:?}, rtc_tts_mnt: {=u8:?}, rtc_tts_hru: {=u8:?}, rtc_tts_hrt: {=u8:?}, rtc_tts_pm: {=bool:?} }}" , self . rtc_tts_scu () , self . rtc_tts_sct () , self . rtc_tts_mnu () , self . rtc_tts_mnt () , self . rtc_tts_hru () , self . rtc_tts_hrt () , self . rtc_tts_pm ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct RtcWpk (pub u32) ; impl RtcWpk { # [must_use]
# [inline (always)]
pub const fn rtc_wpk_wpk (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_rtc_wpk_wpk (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for RtcWpk { # [inline (always)]
fn default () -> RtcWpk { RtcWpk (0) } } impl core :: fmt :: Debug for RtcWpk { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("RtcWpk") . field ("rtc_wpk_wpk" , & self . rtc_wpk_wpk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for RtcWpk { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "RtcWpk {{ rtc_wpk_wpk: {=u8:?} }}" , self . rtc_wpk_wpk ()) } } }