#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Serial Audio Interface"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sai0 { ptr : * mut u8 } unsafe impl Send for Sai0 { } unsafe impl Sync for Sai0 { } impl Sai0 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Synchronize configuration register"]
# [inline (always)]
pub const fn syncfg (self) -> crate :: common :: Reg < regs :: Syncfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Block 0 configuration registe"]
# [inline (always)]
pub const fn b0cfg0 (self) -> crate :: common :: Reg < regs :: B0cfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Block 0 configuration registe"]
# [inline (always)]
pub const fn b0cfg1 (self) -> crate :: common :: Reg < regs :: B0cfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Block 0 frame configuration regist"]
# [inline (always)]
pub const fn b0fcfg (self) -> crate :: common :: Reg < regs :: B0fcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Block 0 slot configuration regist"]
# [inline (always)]
pub const fn b0scfg (self) -> crate :: common :: Reg < regs :: B0scfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Block 0 interrupt enable regist"]
# [inline (always)]
pub const fn b0inten (self) -> crate :: common :: Reg < regs :: B0inten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Block 0 status regist"]
# [inline (always)]
pub const fn b0stat (self) -> crate :: common :: Reg < regs :: B0stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Block 0 interrupt flag clear regist"]
# [inline (always)]
pub const fn b0intc (self) -> crate :: common :: Reg < regs :: B0intc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Block 0 data regist"]
# [inline (always)]
pub const fn b0data (self) -> crate :: common :: Reg < regs :: B0data , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Block 1 configuration registe"]
# [inline (always)]
pub const fn b1cfg0 (self) -> crate :: common :: Reg < regs :: B1cfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Block 1 configuration registe"]
# [inline (always)]
pub const fn b1cfg1 (self) -> crate :: common :: Reg < regs :: B1cfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Block 1 frame configuration regist"]
# [inline (always)]
pub const fn b1fcfg (self) -> crate :: common :: Reg < regs :: B1fcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Block 1 slot configuration regist"]
# [inline (always)]
pub const fn b1scfg (self) -> crate :: common :: Reg < regs :: B1scfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "Block 1 interrupt enable regist"]
# [inline (always)]
pub const fn b1inten (self) -> crate :: common :: Reg < regs :: B1inten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "Block 1 status regist"]
# [inline (always)]
pub const fn b1stat (self) -> crate :: common :: Reg < regs :: B1stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Block 1 interrupt flag clear regist"]
# [inline (always)]
pub const fn b1intc (self) -> crate :: common :: Reg < regs :: B1intc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Block 1 data regist"]
# [inline (always)]
pub const fn b1data (self) -> crate :: common :: Reg < regs :: B1data , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "PDM control register"]
# [inline (always)]
pub const fn pdmctl (self) -> crate :: common :: Reg < regs :: Pdmctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "PDM configuration register"]
# [inline (always)]
pub const fn pdmcfg (self) -> crate :: common :: Reg < regs :: Pdmcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } } pub mod regs { # [doc = "Block 0 configuration registe"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0cfg0 (pub u32) ; impl B0cfg0 { # [doc = "Operating mode"]
# [inline (always)]
pub const fn optmod (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Operating mode"]
# [inline (always)]
pub fn set_optmod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Protocol selection"]
# [inline (always)]
pub const fn prot (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Protocol selection"]
# [inline (always)]
pub fn set_prot (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Data width"]
# [inline (always)]
pub const fn datawd (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x07 ; val as u8 } # [doc = "Data width"]
# [inline (always)]
pub fn set_datawd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 5usize)) | (((val as u32) & 0x07) << 5usize) ; } # [doc = "Shift direction"]
# [inline (always)]
pub const fn shiftdir (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Shift direction"]
# [inline (always)]
pub fn set_shiftdir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Sampling clock edge"]
# [inline (always)]
pub const fn sampedge (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Sampling clock edge"]
# [inline (always)]
pub fn set_sampedge (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Synchronization mode"]
# [inline (always)]
pub const fn syncmod (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Synchronization mode"]
# [inline (always)]
pub fn set_syncmod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Stereo and Mono mode selection"]
# [inline (always)]
pub const fn mono (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Stereo and Mono mode selection"]
# [inline (always)]
pub fn set_mono (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Output Drive"]
# [inline (always)]
pub const fn odriv (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Output Drive"]
# [inline (always)]
pub fn set_odriv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "SAI sub-block enable"]
# [inline (always)]
pub const fn saien (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "SAI sub-block enable"]
# [inline (always)]
pub fn set_saien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "DMA enable"]
# [inline (always)]
pub const fn dmaen (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "DMA enable"]
# [inline (always)]
pub fn set_dmaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Clock divider logic bypass"]
# [inline (always)]
pub const fn bypass (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Clock divider logic bypass"]
# [inline (always)]
pub fn set_bypass (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Master clock divider ratio"]
# [inline (always)]
pub const fn mdiv (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x3f ; val as u8 } # [doc = "Master clock divider ratio"]
# [inline (always)]
pub fn set_mdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 20usize)) | (((val as u32) & 0x3f) << 20usize) ; } # [doc = "The master clock oversampling rate"]
# [inline (always)]
pub const fn mospr (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "The master clock oversampling rate"]
# [inline (always)]
pub fn set_mospr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "The master clock enable"]
# [inline (always)]
pub const fn mclken (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "The master clock enable"]
# [inline (always)]
pub fn set_mclken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } } impl Default for B0cfg0 { # [inline (always)]
fn default () -> B0cfg0 { B0cfg0 (0) } } impl core :: fmt :: Debug for B0cfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0cfg0") . field ("optmod" , & self . optmod ()) . field ("prot" , & self . prot ()) . field ("datawd" , & self . datawd ()) . field ("shiftdir" , & self . shiftdir ()) . field ("sampedge" , & self . sampedge ()) . field ("syncmod" , & self . syncmod ()) . field ("mono" , & self . mono ()) . field ("odriv" , & self . odriv ()) . field ("saien" , & self . saien ()) . field ("dmaen" , & self . dmaen ()) . field ("bypass" , & self . bypass ()) . field ("mdiv" , & self . mdiv ()) . field ("mospr" , & self . mospr ()) . field ("mclken" , & self . mclken ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0cfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0cfg0 {{ optmod: {=u8:?}, prot: {=u8:?}, datawd: {=u8:?}, shiftdir: {=bool:?}, sampedge: {=bool:?}, syncmod: {=u8:?}, mono: {=bool:?}, odriv: {=bool:?}, saien: {=bool:?}, dmaen: {=bool:?}, bypass: {=bool:?}, mdiv: {=u8:?}, mospr: {=bool:?}, mclken: {=bool:?} }}" , self . optmod () , self . prot () , self . datawd () , self . shiftdir () , self . sampedge () , self . syncmod () , self . mono () , self . odriv () , self . saien () , self . dmaen () , self . bypass () , self . mdiv () , self . mospr () , self . mclken ()) } } # [doc = "Block 0 configuration registe"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0cfg1 (pub u32) ; impl B0cfg1 { # [doc = "FIFO threshold"]
# [inline (always)]
pub const fn ffth (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "FIFO threshold"]
# [inline (always)]
pub fn set_ffth (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "FIFO flush"]
# [inline (always)]
pub const fn flush (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "FIFO flush"]
# [inline (always)]
pub fn set_flush (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Serial data output management"]
# [inline (always)]
pub const fn sdom (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Serial data output management"]
# [inline (always)]
pub fn set_sdom (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Mute"]
# [inline (always)]
pub const fn mt (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Mute"]
# [inline (always)]
pub fn set_mt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Mute value"]
# [inline (always)]
pub const fn mtval (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Mute value"]
# [inline (always)]
pub fn set_mtval (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Mute frame count"]
# [inline (always)]
pub const fn mtfcnt (& self) -> u8 { let val = (self . 0 >> 7usize) & 0x3f ; val as u8 } # [doc = "Mute frame count"]
# [inline (always)]
pub fn set_mtfcnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 7usize)) | (((val as u32) & 0x3f) << 7usize) ; } # [doc = "Complement mode"]
# [inline (always)]
pub const fn cplmod (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Complement mode"]
# [inline (always)]
pub fn set_cplmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Compander mode"]
# [inline (always)]
pub const fn cpamod (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Compander mode"]
# [inline (always)]
pub fn set_cpamod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } } impl Default for B0cfg1 { # [inline (always)]
fn default () -> B0cfg1 { B0cfg1 (0) } } impl core :: fmt :: Debug for B0cfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0cfg1") . field ("ffth" , & self . ffth ()) . field ("flush" , & self . flush ()) . field ("sdom" , & self . sdom ()) . field ("mt" , & self . mt ()) . field ("mtval" , & self . mtval ()) . field ("mtfcnt" , & self . mtfcnt ()) . field ("cplmod" , & self . cplmod ()) . field ("cpamod" , & self . cpamod ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0cfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0cfg1 {{ ffth: {=u8:?}, flush: {=bool:?}, sdom: {=bool:?}, mt: {=bool:?}, mtval: {=bool:?}, mtfcnt: {=u8:?}, cplmod: {=bool:?}, cpamod: {=u8:?} }}" , self . ffth () , self . flush () , self . sdom () , self . mt () , self . mtval () , self . mtfcnt () , self . cplmod () , self . cpamod ()) } } # [doc = "Block 0 data regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0data (pub u32) ; impl B0data { # [doc = "Data"]
# [inline (always)]
pub const fn data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Data"]
# [inline (always)]
pub fn set_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for B0data { # [inline (always)]
fn default () -> B0data { B0data (0) } } impl core :: fmt :: Debug for B0data { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0data") . field ("data" , & self . data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0data { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0data {{ data: {=u32:?} }}" , self . data ()) } } # [doc = "Block 0 frame configuration regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0fcfg (pub u32) ; impl B0fcfg { # [doc = "Frame width"]
# [inline (always)]
pub const fn fwd (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Frame width"]
# [inline (always)]
pub fn set_fwd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Frame synchronization active width"]
# [inline (always)]
pub const fn fsawd (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x7f ; val as u8 } # [doc = "Frame synchronization active width"]
# [inline (always)]
pub fn set_fsawd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 8usize)) | (((val as u32) & 0x7f) << 8usize) ; } # [doc = "Frame synchronization function"]
# [inline (always)]
pub const fn fsfunc (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization function"]
# [inline (always)]
pub fn set_fsfunc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Frame synchronization active polarity"]
# [inline (always)]
pub const fn fspl (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization active polarity"]
# [inline (always)]
pub fn set_fspl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Frame synchronization offset"]
# [inline (always)]
pub const fn fsost (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization offset"]
# [inline (always)]
pub fn set_fsost (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for B0fcfg { # [inline (always)]
fn default () -> B0fcfg { B0fcfg (0) } } impl core :: fmt :: Debug for B0fcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0fcfg") . field ("fwd" , & self . fwd ()) . field ("fsawd" , & self . fsawd ()) . field ("fsfunc" , & self . fsfunc ()) . field ("fspl" , & self . fspl ()) . field ("fsost" , & self . fsost ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0fcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0fcfg {{ fwd: {=u8:?}, fsawd: {=u8:?}, fsfunc: {=bool:?}, fspl: {=bool:?}, fsost: {=bool:?} }}" , self . fwd () , self . fsawd () , self . fsfunc () , self . fspl () , self . fsost ()) } } # [doc = "Block 0 interrupt flag clear regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0intc (pub u32) ; impl B0intc { # [doc = "Overrun or underrun interrupt clear"]
# [inline (always)]
pub const fn ouerrc (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Overrun or underrun interrupt clear"]
# [inline (always)]
pub fn set_ouerrc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mute detection interrupt clear"]
# [inline (always)]
pub const fn mtdetc (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mute detection interrupt clear"]
# [inline (always)]
pub fn set_mtdetc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Clock error interrupt clear"]
# [inline (always)]
pub const fn errckc (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Clock error interrupt clear"]
# [inline (always)]
pub fn set_errckc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Audio codec not ready interrupt clear"]
# [inline (always)]
pub const fn acnrdyc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Audio codec not ready interrupt clear"]
# [inline (always)]
pub fn set_acnrdyc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Frame synchronization advanced detection interrupt clear"]
# [inline (always)]
pub const fn fsadetc (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization advanced detection interrupt clear"]
# [inline (always)]
pub fn set_fsadetc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Frame synchronization postponed detection interrupt clear"]
# [inline (always)]
pub const fn fspdetc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization postponed detection interrupt clear"]
# [inline (always)]
pub fn set_fspdetc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for B0intc { # [inline (always)]
fn default () -> B0intc { B0intc (0) } } impl core :: fmt :: Debug for B0intc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0intc") . field ("ouerrc" , & self . ouerrc ()) . field ("mtdetc" , & self . mtdetc ()) . field ("errckc" , & self . errckc ()) . field ("acnrdyc" , & self . acnrdyc ()) . field ("fsadetc" , & self . fsadetc ()) . field ("fspdetc" , & self . fspdetc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0intc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0intc {{ ouerrc: {=bool:?}, mtdetc: {=bool:?}, errckc: {=bool:?}, acnrdyc: {=bool:?}, fsadetc: {=bool:?}, fspdetc: {=bool:?} }}" , self . ouerrc () , self . mtdetc () , self . errckc () , self . acnrdyc () , self . fsadetc () , self . fspdetc ()) } } # [doc = "Block 0 interrupt enable regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0inten (pub u32) ; impl B0inten { # [doc = "FIFO overrun or underrun interrupt enable"]
# [inline (always)]
pub const fn ouerrie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "FIFO overrun or underrun interrupt enable"]
# [inline (always)]
pub fn set_ouerrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mute detection interrupt enable"]
# [inline (always)]
pub const fn mtdetie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mute detection interrupt enable"]
# [inline (always)]
pub fn set_mtdetie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error clock interrupt enable"]
# [inline (always)]
pub const fn errckie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error clock interrupt enable"]
# [inline (always)]
pub fn set_errckie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "FIFO request interrupt enable"]
# [inline (always)]
pub const fn ffreqie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "FIFO request interrupt enable"]
# [inline (always)]
pub fn set_ffreqie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Audio codec not ready interrupt enable"]
# [inline (always)]
pub const fn acnrdyie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Audio codec not ready interrupt enable"]
# [inline (always)]
pub fn set_acnrdyie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Frame synchronization advanced detection interrupt enable"]
# [inline (always)]
pub const fn fsadetie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization advanced detection interrupt enable"]
# [inline (always)]
pub fn set_fsadetie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Frame synchronization postpone detection interrupt enable"]
# [inline (always)]
pub const fn fspdetie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization postpone detection interrupt enable"]
# [inline (always)]
pub fn set_fspdetie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for B0inten { # [inline (always)]
fn default () -> B0inten { B0inten (0) } } impl core :: fmt :: Debug for B0inten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0inten") . field ("ouerrie" , & self . ouerrie ()) . field ("mtdetie" , & self . mtdetie ()) . field ("errckie" , & self . errckie ()) . field ("ffreqie" , & self . ffreqie ()) . field ("acnrdyie" , & self . acnrdyie ()) . field ("fsadetie" , & self . fsadetie ()) . field ("fspdetie" , & self . fspdetie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0inten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0inten {{ ouerrie: {=bool:?}, mtdetie: {=bool:?}, errckie: {=bool:?}, ffreqie: {=bool:?}, acnrdyie: {=bool:?}, fsadetie: {=bool:?}, fspdetie: {=bool:?} }}" , self . ouerrie () , self . mtdetie () , self . errckie () , self . ffreqie () , self . acnrdyie () , self . fsadetie () , self . fspdetie ()) } } # [doc = "Block 0 slot configuration regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0scfg (pub u32) ; impl B0scfg { # [doc = "Data offset"]
# [inline (always)]
pub const fn dataost (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [doc = "Data offset"]
# [inline (always)]
pub fn set_dataost (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [doc = "Slot width"]
# [inline (always)]
pub const fn slotwd (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Slot width"]
# [inline (always)]
pub fn set_slotwd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "Slot number within frame"]
# [inline (always)]
pub const fn slotnum (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "Slot number within frame"]
# [inline (always)]
pub fn set_slotnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "Slot activation vector"]
# [inline (always)]
pub const fn slotav (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Slot activation vector"]
# [inline (always)]
pub fn set_slotav (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for B0scfg { # [inline (always)]
fn default () -> B0scfg { B0scfg (0) } } impl core :: fmt :: Debug for B0scfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0scfg") . field ("dataost" , & self . dataost ()) . field ("slotwd" , & self . slotwd ()) . field ("slotnum" , & self . slotnum ()) . field ("slotav" , & self . slotav ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0scfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0scfg {{ dataost: {=u8:?}, slotwd: {=u8:?}, slotnum: {=u8:?}, slotav: {=u16:?} }}" , self . dataost () , self . slotwd () , self . slotnum () , self . slotav ()) } } # [doc = "Block 0 status regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B0stat (pub u32) ; impl B0stat { # [doc = "Overrun or underrun"]
# [inline (always)]
pub const fn ouerr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Overrun or underrun"]
# [inline (always)]
pub fn set_ouerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mute detection"]
# [inline (always)]
pub const fn mtdet (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mute detection"]
# [inline (always)]
pub fn set_mtdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error clock"]
# [inline (always)]
pub const fn errck (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error clock"]
# [inline (always)]
pub fn set_errck (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "FIFO request"]
# [inline (always)]
pub const fn ffreq (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "FIFO request"]
# [inline (always)]
pub fn set_ffreq (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Audio codec not ready"]
# [inline (always)]
pub const fn acnrdy (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Audio codec not ready"]
# [inline (always)]
pub fn set_acnrdy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Frame synchronization advanced detection"]
# [inline (always)]
pub const fn fsadet (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization advanced detection"]
# [inline (always)]
pub fn set_fsadet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Frame synchronization postponed detection"]
# [inline (always)]
pub const fn fspdet (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization postponed detection"]
# [inline (always)]
pub fn set_fspdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "FIFO status"]
# [inline (always)]
pub const fn ffstat (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [doc = "FIFO status"]
# [inline (always)]
pub fn set_ffstat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } } impl Default for B0stat { # [inline (always)]
fn default () -> B0stat { B0stat (0) } } impl core :: fmt :: Debug for B0stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B0stat") . field ("ouerr" , & self . ouerr ()) . field ("mtdet" , & self . mtdet ()) . field ("errck" , & self . errck ()) . field ("ffreq" , & self . ffreq ()) . field ("acnrdy" , & self . acnrdy ()) . field ("fsadet" , & self . fsadet ()) . field ("fspdet" , & self . fspdet ()) . field ("ffstat" , & self . ffstat ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B0stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B0stat {{ ouerr: {=bool:?}, mtdet: {=bool:?}, errck: {=bool:?}, ffreq: {=bool:?}, acnrdy: {=bool:?}, fsadet: {=bool:?}, fspdet: {=bool:?}, ffstat: {=u8:?} }}" , self . ouerr () , self . mtdet () , self . errck () , self . ffreq () , self . acnrdy () , self . fsadet () , self . fspdet () , self . ffstat ()) } } # [doc = "Block 1 configuration registe"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1cfg0 (pub u32) ; impl B1cfg0 { # [doc = "Operating mode"]
# [inline (always)]
pub const fn optmod (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Operating mode"]
# [inline (always)]
pub fn set_optmod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Protocol selection"]
# [inline (always)]
pub const fn prot (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Protocol selection"]
# [inline (always)]
pub fn set_prot (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Data width"]
# [inline (always)]
pub const fn datawd (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x07 ; val as u8 } # [doc = "Data width"]
# [inline (always)]
pub fn set_datawd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 5usize)) | (((val as u32) & 0x07) << 5usize) ; } # [doc = "Shift direction"]
# [inline (always)]
pub const fn shiftdir (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Shift direction"]
# [inline (always)]
pub fn set_shiftdir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Sampling clock edge"]
# [inline (always)]
pub const fn sampedge (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Sampling clock edge"]
# [inline (always)]
pub fn set_sampedge (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Synchronization mode"]
# [inline (always)]
pub const fn syncmod (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Synchronization mode"]
# [inline (always)]
pub fn set_syncmod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Stereo and Mono mode selection"]
# [inline (always)]
pub const fn mono (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Stereo and Mono mode selection"]
# [inline (always)]
pub fn set_mono (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Output Drive"]
# [inline (always)]
pub const fn odriv (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Output Drive"]
# [inline (always)]
pub fn set_odriv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "SAI sub-block enable"]
# [inline (always)]
pub const fn saien (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "SAI sub-block enable"]
# [inline (always)]
pub fn set_saien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "DMA enable"]
# [inline (always)]
pub const fn dmaen (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "DMA enable"]
# [inline (always)]
pub fn set_dmaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Clock divider logic bypass"]
# [inline (always)]
pub const fn bypass (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Clock divider logic bypass"]
# [inline (always)]
pub fn set_bypass (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Master clock divider ratio"]
# [inline (always)]
pub const fn mdiv (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x3f ; val as u8 } # [doc = "Master clock divider ratio"]
# [inline (always)]
pub fn set_mdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 20usize)) | (((val as u32) & 0x3f) << 20usize) ; } # [doc = "The master clock oversampling rate"]
# [inline (always)]
pub const fn mospr (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "The master clock oversampling rate"]
# [inline (always)]
pub fn set_mospr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "The master clock enable"]
# [inline (always)]
pub const fn mclken (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "The master clock enable"]
# [inline (always)]
pub fn set_mclken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } } impl Default for B1cfg0 { # [inline (always)]
fn default () -> B1cfg0 { B1cfg0 (0) } } impl core :: fmt :: Debug for B1cfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1cfg0") . field ("optmod" , & self . optmod ()) . field ("prot" , & self . prot ()) . field ("datawd" , & self . datawd ()) . field ("shiftdir" , & self . shiftdir ()) . field ("sampedge" , & self . sampedge ()) . field ("syncmod" , & self . syncmod ()) . field ("mono" , & self . mono ()) . field ("odriv" , & self . odriv ()) . field ("saien" , & self . saien ()) . field ("dmaen" , & self . dmaen ()) . field ("bypass" , & self . bypass ()) . field ("mdiv" , & self . mdiv ()) . field ("mospr" , & self . mospr ()) . field ("mclken" , & self . mclken ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1cfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1cfg0 {{ optmod: {=u8:?}, prot: {=u8:?}, datawd: {=u8:?}, shiftdir: {=bool:?}, sampedge: {=bool:?}, syncmod: {=u8:?}, mono: {=bool:?}, odriv: {=bool:?}, saien: {=bool:?}, dmaen: {=bool:?}, bypass: {=bool:?}, mdiv: {=u8:?}, mospr: {=bool:?}, mclken: {=bool:?} }}" , self . optmod () , self . prot () , self . datawd () , self . shiftdir () , self . sampedge () , self . syncmod () , self . mono () , self . odriv () , self . saien () , self . dmaen () , self . bypass () , self . mdiv () , self . mospr () , self . mclken ()) } } # [doc = "Block 1 configuration registe"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1cfg1 (pub u32) ; impl B1cfg1 { # [doc = "FIFO threshold"]
# [inline (always)]
pub const fn ffth (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "FIFO threshold"]
# [inline (always)]
pub fn set_ffth (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "FIFO flush"]
# [inline (always)]
pub const fn flush (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "FIFO flush"]
# [inline (always)]
pub fn set_flush (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Serial data output management"]
# [inline (always)]
pub const fn sdom (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Serial data output management"]
# [inline (always)]
pub fn set_sdom (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Mute"]
# [inline (always)]
pub const fn mt (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Mute"]
# [inline (always)]
pub fn set_mt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Mute value"]
# [inline (always)]
pub const fn mtval (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Mute value"]
# [inline (always)]
pub fn set_mtval (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Mute frame count"]
# [inline (always)]
pub const fn mtfcnt (& self) -> u8 { let val = (self . 0 >> 7usize) & 0x3f ; val as u8 } # [doc = "Mute frame count"]
# [inline (always)]
pub fn set_mtfcnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 7usize)) | (((val as u32) & 0x3f) << 7usize) ; } # [doc = "Complement mode"]
# [inline (always)]
pub const fn cplmod (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Complement mode"]
# [inline (always)]
pub fn set_cplmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Compander mode"]
# [inline (always)]
pub const fn cpamod (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Compander mode"]
# [inline (always)]
pub fn set_cpamod (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } } impl Default for B1cfg1 { # [inline (always)]
fn default () -> B1cfg1 { B1cfg1 (0) } } impl core :: fmt :: Debug for B1cfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1cfg1") . field ("ffth" , & self . ffth ()) . field ("flush" , & self . flush ()) . field ("sdom" , & self . sdom ()) . field ("mt" , & self . mt ()) . field ("mtval" , & self . mtval ()) . field ("mtfcnt" , & self . mtfcnt ()) . field ("cplmod" , & self . cplmod ()) . field ("cpamod" , & self . cpamod ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1cfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1cfg1 {{ ffth: {=u8:?}, flush: {=bool:?}, sdom: {=bool:?}, mt: {=bool:?}, mtval: {=bool:?}, mtfcnt: {=u8:?}, cplmod: {=bool:?}, cpamod: {=u8:?} }}" , self . ffth () , self . flush () , self . sdom () , self . mt () , self . mtval () , self . mtfcnt () , self . cplmod () , self . cpamod ()) } } # [doc = "Block 1 data regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1data (pub u32) ; impl B1data { # [doc = "Data"]
# [inline (always)]
pub const fn data (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Data"]
# [inline (always)]
pub fn set_data (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for B1data { # [inline (always)]
fn default () -> B1data { B1data (0) } } impl core :: fmt :: Debug for B1data { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1data") . field ("data" , & self . data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1data { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1data {{ data: {=u32:?} }}" , self . data ()) } } # [doc = "Block 1 frame configuration regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1fcfg (pub u32) ; impl B1fcfg { # [doc = "Frame width"]
# [inline (always)]
pub const fn fwd (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Frame width"]
# [inline (always)]
pub fn set_fwd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Frame synchronization active width"]
# [inline (always)]
pub const fn fsawd (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x7f ; val as u8 } # [doc = "Frame synchronization active width"]
# [inline (always)]
pub fn set_fsawd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 8usize)) | (((val as u32) & 0x7f) << 8usize) ; } # [doc = "Frame synchronization function"]
# [inline (always)]
pub const fn fsfunc (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization function"]
# [inline (always)]
pub fn set_fsfunc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Frame synchronization active polarity"]
# [inline (always)]
pub const fn fspolr (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization active polarity"]
# [inline (always)]
pub fn set_fspolr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Frame synchronization offset"]
# [inline (always)]
pub const fn fsost (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization offset"]
# [inline (always)]
pub fn set_fsost (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for B1fcfg { # [inline (always)]
fn default () -> B1fcfg { B1fcfg (0) } } impl core :: fmt :: Debug for B1fcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1fcfg") . field ("fwd" , & self . fwd ()) . field ("fsawd" , & self . fsawd ()) . field ("fsfunc" , & self . fsfunc ()) . field ("fspolr" , & self . fspolr ()) . field ("fsost" , & self . fsost ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1fcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1fcfg {{ fwd: {=u8:?}, fsawd: {=u8:?}, fsfunc: {=bool:?}, fspolr: {=bool:?}, fsost: {=bool:?} }}" , self . fwd () , self . fsawd () , self . fsfunc () , self . fspolr () , self . fsost ()) } } # [doc = "Block 1 interrupt flag clear regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1intc (pub u32) ; impl B1intc { # [doc = "Overrun or underrun interrupt clear"]
# [inline (always)]
pub const fn ouerrc (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Overrun or underrun interrupt clear"]
# [inline (always)]
pub fn set_ouerrc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mute detection interrupt clear"]
# [inline (always)]
pub const fn mtdetc (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mute detection interrupt clear"]
# [inline (always)]
pub fn set_mtdetc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Clock error interrupt clear"]
# [inline (always)]
pub const fn errckc (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Clock error interrupt clear"]
# [inline (always)]
pub fn set_errckc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Audio codec not ready interrupt clear"]
# [inline (always)]
pub const fn acnrdyc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Audio codec not ready interrupt clear"]
# [inline (always)]
pub fn set_acnrdyc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Frame synchronization advanced detection interrupt clear"]
# [inline (always)]
pub const fn fsadetc (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization advanced detection interrupt clear"]
# [inline (always)]
pub fn set_fsadetc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Frame synchronization postponed detection interrupt clear"]
# [inline (always)]
pub const fn fspdetc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization postponed detection interrupt clear"]
# [inline (always)]
pub fn set_fspdetc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for B1intc { # [inline (always)]
fn default () -> B1intc { B1intc (0) } } impl core :: fmt :: Debug for B1intc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1intc") . field ("ouerrc" , & self . ouerrc ()) . field ("mtdetc" , & self . mtdetc ()) . field ("errckc" , & self . errckc ()) . field ("acnrdyc" , & self . acnrdyc ()) . field ("fsadetc" , & self . fsadetc ()) . field ("fspdetc" , & self . fspdetc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1intc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1intc {{ ouerrc: {=bool:?}, mtdetc: {=bool:?}, errckc: {=bool:?}, acnrdyc: {=bool:?}, fsadetc: {=bool:?}, fspdetc: {=bool:?} }}" , self . ouerrc () , self . mtdetc () , self . errckc () , self . acnrdyc () , self . fsadetc () , self . fspdetc ()) } } # [doc = "Block 1 interrupt enable regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1inten (pub u32) ; impl B1inten { # [doc = "FIFO overrun or underrun interrupt enable"]
# [inline (always)]
pub const fn ouerrrie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "FIFO overrun or underrun interrupt enable"]
# [inline (always)]
pub fn set_ouerrrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mute detection interrupt enable"]
# [inline (always)]
pub const fn mtdetie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mute detection interrupt enable"]
# [inline (always)]
pub fn set_mtdetie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error clock interrupt enable"]
# [inline (always)]
pub const fn errckie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error clock interrupt enable"]
# [inline (always)]
pub fn set_errckie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "FIFO request interrupt enable"]
# [inline (always)]
pub const fn ffreqie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "FIFO request interrupt enable"]
# [inline (always)]
pub fn set_ffreqie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Audio codec not ready interrupt enable"]
# [inline (always)]
pub const fn acnrdyie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Audio codec not ready interrupt enable"]
# [inline (always)]
pub fn set_acnrdyie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Frame synchronization advanced detection interrupt enable"]
# [inline (always)]
pub const fn fsadetie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization advanced detection interrupt enable"]
# [inline (always)]
pub fn set_fsadetie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Frame synchronization postpone detection interrupt enable"]
# [inline (always)]
pub const fn fspdetie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization postpone detection interrupt enable"]
# [inline (always)]
pub fn set_fspdetie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for B1inten { # [inline (always)]
fn default () -> B1inten { B1inten (0) } } impl core :: fmt :: Debug for B1inten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1inten") . field ("ouerrrie" , & self . ouerrrie ()) . field ("mtdetie" , & self . mtdetie ()) . field ("errckie" , & self . errckie ()) . field ("ffreqie" , & self . ffreqie ()) . field ("acnrdyie" , & self . acnrdyie ()) . field ("fsadetie" , & self . fsadetie ()) . field ("fspdetie" , & self . fspdetie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1inten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1inten {{ ouerrrie: {=bool:?}, mtdetie: {=bool:?}, errckie: {=bool:?}, ffreqie: {=bool:?}, acnrdyie: {=bool:?}, fsadetie: {=bool:?}, fspdetie: {=bool:?} }}" , self . ouerrrie () , self . mtdetie () , self . errckie () , self . ffreqie () , self . acnrdyie () , self . fsadetie () , self . fspdetie ()) } } # [doc = "Block 1 slot configuration regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1scfg (pub u32) ; impl B1scfg { # [doc = "Data offset"]
# [inline (always)]
pub const fn dataost (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [doc = "Data offset"]
# [inline (always)]
pub fn set_dataost (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [doc = "Slot width"]
# [inline (always)]
pub const fn slotwd (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Slot width"]
# [inline (always)]
pub fn set_slotwd (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "Slot number within frame"]
# [inline (always)]
pub const fn slotnum (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "Slot number within frame"]
# [inline (always)]
pub fn set_slotnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "Slot activation vector"]
# [inline (always)]
pub const fn slotav (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Slot activation vector"]
# [inline (always)]
pub fn set_slotav (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for B1scfg { # [inline (always)]
fn default () -> B1scfg { B1scfg (0) } } impl core :: fmt :: Debug for B1scfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1scfg") . field ("dataost" , & self . dataost ()) . field ("slotwd" , & self . slotwd ()) . field ("slotnum" , & self . slotnum ()) . field ("slotav" , & self . slotav ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1scfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1scfg {{ dataost: {=u8:?}, slotwd: {=u8:?}, slotnum: {=u8:?}, slotav: {=u16:?} }}" , self . dataost () , self . slotwd () , self . slotnum () , self . slotav ()) } } # [doc = "Block 1 status regist"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct B1stat (pub u32) ; impl B1stat { # [doc = "Overrun or underrun"]
# [inline (always)]
pub const fn ouerr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Overrun or underrun"]
# [inline (always)]
pub fn set_ouerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mute detection"]
# [inline (always)]
pub const fn mtdet (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mute detection"]
# [inline (always)]
pub fn set_mtdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Error clock"]
# [inline (always)]
pub const fn errck (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Error clock"]
# [inline (always)]
pub fn set_errck (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "FIFO request"]
# [inline (always)]
pub const fn ffreq (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "FIFO request"]
# [inline (always)]
pub fn set_ffreq (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Audio codec not ready"]
# [inline (always)]
pub const fn acnrdy (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Audio codec not ready"]
# [inline (always)]
pub fn set_acnrdy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Frame synchronization advanced detection"]
# [inline (always)]
pub const fn fsadet (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization advanced detection"]
# [inline (always)]
pub fn set_fsadet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Frame synchronization postponed detection"]
# [inline (always)]
pub const fn fspdet (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Frame synchronization postponed detection"]
# [inline (always)]
pub fn set_fspdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "FIFO status"]
# [inline (always)]
pub const fn ffstat (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [doc = "FIFO status"]
# [inline (always)]
pub fn set_ffstat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } } impl Default for B1stat { # [inline (always)]
fn default () -> B1stat { B1stat (0) } } impl core :: fmt :: Debug for B1stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("B1stat") . field ("ouerr" , & self . ouerr ()) . field ("mtdet" , & self . mtdet ()) . field ("errck" , & self . errck ()) . field ("ffreq" , & self . ffreq ()) . field ("acnrdy" , & self . acnrdy ()) . field ("fsadet" , & self . fsadet ()) . field ("fspdet" , & self . fspdet ()) . field ("ffstat" , & self . ffstat ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for B1stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "B1stat {{ ouerr: {=bool:?}, mtdet: {=bool:?}, errck: {=bool:?}, ffreq: {=bool:?}, acnrdy: {=bool:?}, fsadet: {=bool:?}, fspdet: {=bool:?}, ffstat: {=u8:?} }}" , self . ouerr () , self . mtdet () , self . errck () , self . ffreq () , self . acnrdy () , self . fsadet () , self . fspdet () , self . ffstat ()) } } # [doc = "PDM configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pdmcfg (pub u32) ; impl Pdmcfg { # [doc = "The 0 group of left channel microphone data flow delay period"]
# [inline (always)]
pub const fn dpl0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "The 0 group of left channel microphone data flow delay period"]
# [inline (always)]
pub fn set_dpl0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "The 0 group of right channel microphone data flow delay period"]
# [inline (always)]
pub const fn dpr0 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "The 0 group of right channel microphone data flow delay period"]
# [inline (always)]
pub fn set_dpr0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "The 1st group of left channel microphone data flow delay period"]
# [inline (always)]
pub const fn dpl1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x07 ; val as u8 } # [doc = "The 1st group of left channel microphone data flow delay period"]
# [inline (always)]
pub fn set_dpl1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 8usize)) | (((val as u32) & 0x07) << 8usize) ; } # [doc = "The 1st group of right channel microphone data flow delay period"]
# [inline (always)]
pub const fn dpr1 (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "The 1st group of right channel microphone data flow delay period"]
# [inline (always)]
pub fn set_dpr1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "The 2nd group of left channel microphone data flow delay period"]
# [inline (always)]
pub const fn dpl2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [doc = "The 2nd group of left channel microphone data flow delay period"]
# [inline (always)]
pub fn set_dpl2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [doc = "The 2nd group of right channel microphone data flow delay period"]
# [inline (always)]
pub const fn dpr2 (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x07 ; val as u8 } # [doc = "The 2nd group of right channel microphone data flow delay period"]
# [inline (always)]
pub fn set_dpr2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 20usize)) | (((val as u32) & 0x07) << 20usize) ; } } impl Default for Pdmcfg { # [inline (always)]
fn default () -> Pdmcfg { Pdmcfg (0) } } impl core :: fmt :: Debug for Pdmcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pdmcfg") . field ("dpl0" , & self . dpl0 ()) . field ("dpr0" , & self . dpr0 ()) . field ("dpl1" , & self . dpl1 ()) . field ("dpr1" , & self . dpr1 ()) . field ("dpl2" , & self . dpl2 ()) . field ("dpr2" , & self . dpr2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pdmcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pdmcfg {{ dpl0: {=u8:?}, dpr0: {=u8:?}, dpl1: {=u8:?}, dpr1: {=u8:?}, dpl2: {=u8:?}, dpr2: {=u8:?} }}" , self . dpl0 () , self . dpr0 () , self . dpl1 () , self . dpr1 () , self . dpl2 () , self . dpr2 ()) } } # [doc = "PDM control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pdmctl (pub u32) ; impl Pdmctl { # [doc = "PDM enable"]
# [inline (always)]
pub const fn pdmen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "PDM enable"]
# [inline (always)]
pub fn set_pdmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Select microphones number"]
# [inline (always)]
pub const fn micnumsel (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Select microphones number"]
# [inline (always)]
pub fn set_micnumsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "PDM clock line 0 enable"]
# [inline (always)]
pub const fn clkl0en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "PDM clock line 0 enable"]
# [inline (always)]
pub fn set_clkl0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "PDM clock line 1 enable"]
# [inline (always)]
pub const fn clkl1en (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "PDM clock line 1 enable"]
# [inline (always)]
pub fn set_clkl1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } } impl Default for Pdmctl { # [inline (always)]
fn default () -> Pdmctl { Pdmctl (0) } } impl core :: fmt :: Debug for Pdmctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pdmctl") . field ("pdmen" , & self . pdmen ()) . field ("micnumsel" , & self . micnumsel ()) . field ("clkl0en" , & self . clkl0en ()) . field ("clkl1en" , & self . clkl1en ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pdmctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pdmctl {{ pdmen: {=bool:?}, micnumsel: {=u8:?}, clkl0en: {=bool:?}, clkl1en: {=bool:?} }}" , self . pdmen () , self . micnumsel () , self . clkl0en () , self . clkl1en ()) } } # [doc = "Synchronize configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Syncfg (pub u32) ; impl Syncfg { # [doc = "Synchronization inputs"]
# [inline (always)]
pub const fn syni (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Synchronization inputs"]
# [inline (always)]
pub fn set_syni (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Synchronization outputs"]
# [inline (always)]
pub const fn syno (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Synchronization outputs"]
# [inline (always)]
pub fn set_syno (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } } impl Default for Syncfg { # [inline (always)]
fn default () -> Syncfg { Syncfg (0) } } impl core :: fmt :: Debug for Syncfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Syncfg") . field ("syni" , & self . syni ()) . field ("syno" , & self . syno ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Syncfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Syncfg {{ syni: {=u8:?}, syno: {=u8:?} }}" , self . syni () , self . syno ()) } } }