#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sdio { ptr : * mut u8 } unsafe impl Send for Sdio { } unsafe impl Sync for Sdio { } impl Sdio { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn sdio_pwrctl (self) -> crate :: common :: Reg < regs :: SdioPwrctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn sdio_clkctl (self) -> crate :: common :: Reg < regs :: SdioClkctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn sdio_cmdagmt (self) -> crate :: common :: Reg < regs :: SdioCmdagmt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn sdio_cmdctl (self) -> crate :: common :: Reg < regs :: SdioCmdctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn sdio_rspcmdidx (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn sdio_resp0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn sdio_resp1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn sdio_resp2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn sdio_resp3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn sdio_datato (self) -> crate :: common :: Reg < regs :: SdioDatato , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn sdio_datalen (self) -> crate :: common :: Reg < regs :: SdioDatalen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn sdio_datactl (self) -> crate :: common :: Reg < regs :: SdioDatactl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn sdio_datacnt (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn sdio_stat (self) -> crate :: common :: Reg < regs :: SdioStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn sdio_intc (self) -> crate :: common :: Reg < regs :: SdioIntc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn sdio_inten (self) -> crate :: common :: Reg < regs :: SdioInten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn sdio_fifocnt (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x48usize) as _) } } # [inline (always)]
pub const fn sdio_fifo (self) -> crate :: common :: Reg < regs :: SdioFifo , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x80usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioClkctl (pub u32) ; impl SdioClkctl { # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_div (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_sdio_clkctl_div (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_clken (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_clkctl_clken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_clkpwrsav (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_clkctl_clkpwrsav (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_clkbyp (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_clkctl_clkbyp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_busmode (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_sdio_clkctl_busmode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 11usize)) | (((val as u32) & 0x03) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_clkedge (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_clkctl_clkedge (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_hwclken (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_clkctl_hwclken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_clkctl_div8 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_clkctl_div8 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for SdioClkctl { # [inline (always)]
fn default () -> SdioClkctl { SdioClkctl (0) } } impl core :: fmt :: Debug for SdioClkctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioClkctl") . field ("sdio_clkctl_div" , & self . sdio_clkctl_div ()) . field ("sdio_clkctl_clken" , & self . sdio_clkctl_clken ()) . field ("sdio_clkctl_clkpwrsav" , & self . sdio_clkctl_clkpwrsav ()) . field ("sdio_clkctl_clkbyp" , & self . sdio_clkctl_clkbyp ()) . field ("sdio_clkctl_busmode" , & self . sdio_clkctl_busmode ()) . field ("sdio_clkctl_clkedge" , & self . sdio_clkctl_clkedge ()) . field ("sdio_clkctl_hwclken" , & self . sdio_clkctl_hwclken ()) . field ("sdio_clkctl_div8" , & self . sdio_clkctl_div8 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioClkctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioClkctl {{ sdio_clkctl_div: {=u8:?}, sdio_clkctl_clken: {=bool:?}, sdio_clkctl_clkpwrsav: {=bool:?}, sdio_clkctl_clkbyp: {=bool:?}, sdio_clkctl_busmode: {=u8:?}, sdio_clkctl_clkedge: {=bool:?}, sdio_clkctl_hwclken: {=bool:?}, sdio_clkctl_div8: {=bool:?} }}" , self . sdio_clkctl_div () , self . sdio_clkctl_clken () , self . sdio_clkctl_clkpwrsav () , self . sdio_clkctl_clkbyp () , self . sdio_clkctl_busmode () , self . sdio_clkctl_clkedge () , self . sdio_clkctl_hwclken () , self . sdio_clkctl_div8 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioCmdagmt (pub u32) ; impl SdioCmdagmt { # [must_use]
# [inline (always)]
pub const fn sdio_cmdagmt_cmdagmt (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_sdio_cmdagmt_cmdagmt (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for SdioCmdagmt { # [inline (always)]
fn default () -> SdioCmdagmt { SdioCmdagmt (0) } } impl core :: fmt :: Debug for SdioCmdagmt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioCmdagmt") . field ("sdio_cmdagmt_cmdagmt" , & self . sdio_cmdagmt_cmdagmt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioCmdagmt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioCmdagmt {{ sdio_cmdagmt_cmdagmt: {=u32:?} }}" , self . sdio_cmdagmt_cmdagmt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioCmdctl (pub u32) ; impl SdioCmdctl { # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_cmdidx (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_sdio_cmdctl_cmdidx (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_cmdresp (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_sdio_cmdctl_cmdresp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_intwait (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_intwait (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_waitdend (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_waitdend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_csmen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_csmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_suspend (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_suspend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_encmdc (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_encmdc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_ninten (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_ninten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_cmdctl_ataen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_cmdctl_ataen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } } impl Default for SdioCmdctl { # [inline (always)]
fn default () -> SdioCmdctl { SdioCmdctl (0) } } impl core :: fmt :: Debug for SdioCmdctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioCmdctl") . field ("sdio_cmdctl_cmdidx" , & self . sdio_cmdctl_cmdidx ()) . field ("sdio_cmdctl_cmdresp" , & self . sdio_cmdctl_cmdresp ()) . field ("sdio_cmdctl_intwait" , & self . sdio_cmdctl_intwait ()) . field ("sdio_cmdctl_waitdend" , & self . sdio_cmdctl_waitdend ()) . field ("sdio_cmdctl_csmen" , & self . sdio_cmdctl_csmen ()) . field ("sdio_cmdctl_suspend" , & self . sdio_cmdctl_suspend ()) . field ("sdio_cmdctl_encmdc" , & self . sdio_cmdctl_encmdc ()) . field ("sdio_cmdctl_ninten" , & self . sdio_cmdctl_ninten ()) . field ("sdio_cmdctl_ataen" , & self . sdio_cmdctl_ataen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioCmdctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioCmdctl {{ sdio_cmdctl_cmdidx: {=u8:?}, sdio_cmdctl_cmdresp: {=u8:?}, sdio_cmdctl_intwait: {=bool:?}, sdio_cmdctl_waitdend: {=bool:?}, sdio_cmdctl_csmen: {=bool:?}, sdio_cmdctl_suspend: {=bool:?}, sdio_cmdctl_encmdc: {=bool:?}, sdio_cmdctl_ninten: {=bool:?}, sdio_cmdctl_ataen: {=bool:?} }}" , self . sdio_cmdctl_cmdidx () , self . sdio_cmdctl_cmdresp () , self . sdio_cmdctl_intwait () , self . sdio_cmdctl_waitdend () , self . sdio_cmdctl_csmen () , self . sdio_cmdctl_suspend () , self . sdio_cmdctl_encmdc () , self . sdio_cmdctl_ninten () , self . sdio_cmdctl_ataen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioDatactl (pub u32) ; impl SdioDatactl { # [must_use]
# [inline (always)]
pub const fn sdio_datactl_dataen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_dataen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_datadir (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_datadir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_transmod (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_transmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_dmaen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_dmaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_blksz (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_sdio_datactl_blksz (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_rwen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_rwen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_rwstop (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_rwstop (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_rwtype (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_rwtype (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_datactl_ioen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_datactl_ioen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } } impl Default for SdioDatactl { # [inline (always)]
fn default () -> SdioDatactl { SdioDatactl (0) } } impl core :: fmt :: Debug for SdioDatactl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioDatactl") . field ("sdio_datactl_dataen" , & self . sdio_datactl_dataen ()) . field ("sdio_datactl_datadir" , & self . sdio_datactl_datadir ()) . field ("sdio_datactl_transmod" , & self . sdio_datactl_transmod ()) . field ("sdio_datactl_dmaen" , & self . sdio_datactl_dmaen ()) . field ("sdio_datactl_blksz" , & self . sdio_datactl_blksz ()) . field ("sdio_datactl_rwen" , & self . sdio_datactl_rwen ()) . field ("sdio_datactl_rwstop" , & self . sdio_datactl_rwstop ()) . field ("sdio_datactl_rwtype" , & self . sdio_datactl_rwtype ()) . field ("sdio_datactl_ioen" , & self . sdio_datactl_ioen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioDatactl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioDatactl {{ sdio_datactl_dataen: {=bool:?}, sdio_datactl_datadir: {=bool:?}, sdio_datactl_transmod: {=bool:?}, sdio_datactl_dmaen: {=bool:?}, sdio_datactl_blksz: {=u8:?}, sdio_datactl_rwen: {=bool:?}, sdio_datactl_rwstop: {=bool:?}, sdio_datactl_rwtype: {=bool:?}, sdio_datactl_ioen: {=bool:?} }}" , self . sdio_datactl_dataen () , self . sdio_datactl_datadir () , self . sdio_datactl_transmod () , self . sdio_datactl_dmaen () , self . sdio_datactl_blksz () , self . sdio_datactl_rwen () , self . sdio_datactl_rwstop () , self . sdio_datactl_rwtype () , self . sdio_datactl_ioen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioDatalen (pub u32) ; impl SdioDatalen { # [must_use]
# [inline (always)]
pub const fn sdio_datalen_datalen (& self) -> u32 { let val = (self . 0 >> 0usize) & 0x01ff_ffff ; val as u32 } # [inline (always)]
pub const fn set_sdio_datalen_datalen (& mut self , val : u32) { self . 0 = (self . 0 & ! (0x01ff_ffff << 0usize)) | (((val as u32) & 0x01ff_ffff) << 0usize) ; } } impl Default for SdioDatalen { # [inline (always)]
fn default () -> SdioDatalen { SdioDatalen (0) } } impl core :: fmt :: Debug for SdioDatalen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioDatalen") . field ("sdio_datalen_datalen" , & self . sdio_datalen_datalen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioDatalen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioDatalen {{ sdio_datalen_datalen: {=u32:?} }}" , self . sdio_datalen_datalen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioDatato (pub u32) ; impl SdioDatato { # [must_use]
# [inline (always)]
pub const fn sdio_datato_datato (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_sdio_datato_datato (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for SdioDatato { # [inline (always)]
fn default () -> SdioDatato { SdioDatato (0) } } impl core :: fmt :: Debug for SdioDatato { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioDatato") . field ("sdio_datato_datato" , & self . sdio_datato_datato ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioDatato { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioDatato {{ sdio_datato_datato: {=u32:?} }}" , self . sdio_datato_datato ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioFifo (pub u32) ; impl SdioFifo { # [must_use]
# [inline (always)]
pub const fn sdio_fifo_fifodt (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [inline (always)]
pub const fn set_sdio_fifo_fifodt (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for SdioFifo { # [inline (always)]
fn default () -> SdioFifo { SdioFifo (0) } } impl core :: fmt :: Debug for SdioFifo { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioFifo") . field ("sdio_fifo_fifodt" , & self . sdio_fifo_fifodt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioFifo { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioFifo {{ sdio_fifo_fifodt: {=u32:?} }}" , self . sdio_fifo_fifodt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioIntc (pub u32) ; impl SdioIntc { # [must_use]
# [inline (always)]
pub const fn sdio_intc_ccrcerrc (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_ccrcerrc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_dtcrcerrc (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_dtcrcerrc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_cmdtmoutc (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_cmdtmoutc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_dttmoutc (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_dttmoutc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_txurec (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_txurec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_rxorec (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_rxorec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_cmdrecvc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_cmdrecvc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_cmdsendc (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_cmdsendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_dtendc (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_dtendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_stbitec (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_stbitec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_dtblkendc (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_dtblkendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_sdiointc (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_sdiointc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_intc_ataendc (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_intc_ataendc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for SdioIntc { # [inline (always)]
fn default () -> SdioIntc { SdioIntc (0) } } impl core :: fmt :: Debug for SdioIntc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioIntc") . field ("sdio_intc_ccrcerrc" , & self . sdio_intc_ccrcerrc ()) . field ("sdio_intc_dtcrcerrc" , & self . sdio_intc_dtcrcerrc ()) . field ("sdio_intc_cmdtmoutc" , & self . sdio_intc_cmdtmoutc ()) . field ("sdio_intc_dttmoutc" , & self . sdio_intc_dttmoutc ()) . field ("sdio_intc_txurec" , & self . sdio_intc_txurec ()) . field ("sdio_intc_rxorec" , & self . sdio_intc_rxorec ()) . field ("sdio_intc_cmdrecvc" , & self . sdio_intc_cmdrecvc ()) . field ("sdio_intc_cmdsendc" , & self . sdio_intc_cmdsendc ()) . field ("sdio_intc_dtendc" , & self . sdio_intc_dtendc ()) . field ("sdio_intc_stbitec" , & self . sdio_intc_stbitec ()) . field ("sdio_intc_dtblkendc" , & self . sdio_intc_dtblkendc ()) . field ("sdio_intc_sdiointc" , & self . sdio_intc_sdiointc ()) . field ("sdio_intc_ataendc" , & self . sdio_intc_ataendc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioIntc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioIntc {{ sdio_intc_ccrcerrc: {=bool:?}, sdio_intc_dtcrcerrc: {=bool:?}, sdio_intc_cmdtmoutc: {=bool:?}, sdio_intc_dttmoutc: {=bool:?}, sdio_intc_txurec: {=bool:?}, sdio_intc_rxorec: {=bool:?}, sdio_intc_cmdrecvc: {=bool:?}, sdio_intc_cmdsendc: {=bool:?}, sdio_intc_dtendc: {=bool:?}, sdio_intc_stbitec: {=bool:?}, sdio_intc_dtblkendc: {=bool:?}, sdio_intc_sdiointc: {=bool:?}, sdio_intc_ataendc: {=bool:?} }}" , self . sdio_intc_ccrcerrc () , self . sdio_intc_dtcrcerrc () , self . sdio_intc_cmdtmoutc () , self . sdio_intc_dttmoutc () , self . sdio_intc_txurec () , self . sdio_intc_rxorec () , self . sdio_intc_cmdrecvc () , self . sdio_intc_cmdsendc () , self . sdio_intc_dtendc () , self . sdio_intc_stbitec () , self . sdio_intc_dtblkendc () , self . sdio_intc_sdiointc () , self . sdio_intc_ataendc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioInten (pub u32) ; impl SdioInten { # [must_use]
# [inline (always)]
pub const fn sdio_inten_ccrcerrie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_ccrcerrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_dtcrcerrie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_dtcrcerrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_cmdtmoutie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_cmdtmoutie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_dttmoutie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_dttmoutie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_txureie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_txureie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_rxoreie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_rxoreie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_cmdrecvie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_cmdrecvie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_cmdsendie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_cmdsendie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_dtendie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_dtendie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_stbiteie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_stbiteie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_dtblkendie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_dtblkendie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_cmdrunie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_cmdrunie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_txrunie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_txrunie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_rxrunie (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_rxrunie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_tfhie (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_tfhie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_rfhie (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_rfhie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_tffie (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_tffie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_rffie (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_rffie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_tfeie (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_tfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_rfeie (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_rfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_txdtvalie (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_txdtvalie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_rxdtvalie (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_rxdtvalie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_sdiointie (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_sdiointie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_inten_ataendie (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_inten_ataendie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for SdioInten { # [inline (always)]
fn default () -> SdioInten { SdioInten (0) } } impl core :: fmt :: Debug for SdioInten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioInten") . field ("sdio_inten_ccrcerrie" , & self . sdio_inten_ccrcerrie ()) . field ("sdio_inten_dtcrcerrie" , & self . sdio_inten_dtcrcerrie ()) . field ("sdio_inten_cmdtmoutie" , & self . sdio_inten_cmdtmoutie ()) . field ("sdio_inten_dttmoutie" , & self . sdio_inten_dttmoutie ()) . field ("sdio_inten_txureie" , & self . sdio_inten_txureie ()) . field ("sdio_inten_rxoreie" , & self . sdio_inten_rxoreie ()) . field ("sdio_inten_cmdrecvie" , & self . sdio_inten_cmdrecvie ()) . field ("sdio_inten_cmdsendie" , & self . sdio_inten_cmdsendie ()) . field ("sdio_inten_dtendie" , & self . sdio_inten_dtendie ()) . field ("sdio_inten_stbiteie" , & self . sdio_inten_stbiteie ()) . field ("sdio_inten_dtblkendie" , & self . sdio_inten_dtblkendie ()) . field ("sdio_inten_cmdrunie" , & self . sdio_inten_cmdrunie ()) . field ("sdio_inten_txrunie" , & self . sdio_inten_txrunie ()) . field ("sdio_inten_rxrunie" , & self . sdio_inten_rxrunie ()) . field ("sdio_inten_tfhie" , & self . sdio_inten_tfhie ()) . field ("sdio_inten_rfhie" , & self . sdio_inten_rfhie ()) . field ("sdio_inten_tffie" , & self . sdio_inten_tffie ()) . field ("sdio_inten_rffie" , & self . sdio_inten_rffie ()) . field ("sdio_inten_tfeie" , & self . sdio_inten_tfeie ()) . field ("sdio_inten_rfeie" , & self . sdio_inten_rfeie ()) . field ("sdio_inten_txdtvalie" , & self . sdio_inten_txdtvalie ()) . field ("sdio_inten_rxdtvalie" , & self . sdio_inten_rxdtvalie ()) . field ("sdio_inten_sdiointie" , & self . sdio_inten_sdiointie ()) . field ("sdio_inten_ataendie" , & self . sdio_inten_ataendie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioInten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioInten {{ sdio_inten_ccrcerrie: {=bool:?}, sdio_inten_dtcrcerrie: {=bool:?}, sdio_inten_cmdtmoutie: {=bool:?}, sdio_inten_dttmoutie: {=bool:?}, sdio_inten_txureie: {=bool:?}, sdio_inten_rxoreie: {=bool:?}, sdio_inten_cmdrecvie: {=bool:?}, sdio_inten_cmdsendie: {=bool:?}, sdio_inten_dtendie: {=bool:?}, sdio_inten_stbiteie: {=bool:?}, sdio_inten_dtblkendie: {=bool:?}, sdio_inten_cmdrunie: {=bool:?}, sdio_inten_txrunie: {=bool:?}, sdio_inten_rxrunie: {=bool:?}, sdio_inten_tfhie: {=bool:?}, sdio_inten_rfhie: {=bool:?}, sdio_inten_tffie: {=bool:?}, sdio_inten_rffie: {=bool:?}, sdio_inten_tfeie: {=bool:?}, sdio_inten_rfeie: {=bool:?}, sdio_inten_txdtvalie: {=bool:?}, sdio_inten_rxdtvalie: {=bool:?}, sdio_inten_sdiointie: {=bool:?}, sdio_inten_ataendie: {=bool:?} }}" , self . sdio_inten_ccrcerrie () , self . sdio_inten_dtcrcerrie () , self . sdio_inten_cmdtmoutie () , self . sdio_inten_dttmoutie () , self . sdio_inten_txureie () , self . sdio_inten_rxoreie () , self . sdio_inten_cmdrecvie () , self . sdio_inten_cmdsendie () , self . sdio_inten_dtendie () , self . sdio_inten_stbiteie () , self . sdio_inten_dtblkendie () , self . sdio_inten_cmdrunie () , self . sdio_inten_txrunie () , self . sdio_inten_rxrunie () , self . sdio_inten_tfhie () , self . sdio_inten_rfhie () , self . sdio_inten_tffie () , self . sdio_inten_rffie () , self . sdio_inten_tfeie () , self . sdio_inten_rfeie () , self . sdio_inten_txdtvalie () , self . sdio_inten_rxdtvalie () , self . sdio_inten_sdiointie () , self . sdio_inten_ataendie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioPwrctl (pub u32) ; impl SdioPwrctl { # [must_use]
# [inline (always)]
pub const fn sdio_pwrctl_pwrctl (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_sdio_pwrctl_pwrctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } } impl Default for SdioPwrctl { # [inline (always)]
fn default () -> SdioPwrctl { SdioPwrctl (0) } } impl core :: fmt :: Debug for SdioPwrctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioPwrctl") . field ("sdio_pwrctl_pwrctl" , & self . sdio_pwrctl_pwrctl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioPwrctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioPwrctl {{ sdio_pwrctl_pwrctl: {=u8:?} }}" , self . sdio_pwrctl_pwrctl ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SdioStat (pub u32) ; impl SdioStat { # [must_use]
# [inline (always)]
pub const fn sdio_stat_ccrcerr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_ccrcerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_dtcrcerr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_dtcrcerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_cmdtmout (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_cmdtmout (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_dttmout (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_dttmout (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_txure (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_txure (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_rxore (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_rxore (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_cmdrecv (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_cmdrecv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_cmdsend (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_cmdsend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_dtend (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_dtend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_stbite (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_stbite (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_dtblkend (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_dtblkend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_cmdrun (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_cmdrun (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_txrun (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_txrun (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_rxrun (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_rxrun (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_tfh (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_tfh (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_rfh (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_rfh (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_tff (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_tff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_rff (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_rff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_tfe (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_tfe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_rfe (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_rfe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_txdtval (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_txdtval (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_rxdtval (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_rxdtval (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_sdioint (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_sdioint (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn sdio_stat_ataend (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_sdio_stat_ataend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for SdioStat { # [inline (always)]
fn default () -> SdioStat { SdioStat (0) } } impl core :: fmt :: Debug for SdioStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SdioStat") . field ("sdio_stat_ccrcerr" , & self . sdio_stat_ccrcerr ()) . field ("sdio_stat_dtcrcerr" , & self . sdio_stat_dtcrcerr ()) . field ("sdio_stat_cmdtmout" , & self . sdio_stat_cmdtmout ()) . field ("sdio_stat_dttmout" , & self . sdio_stat_dttmout ()) . field ("sdio_stat_txure" , & self . sdio_stat_txure ()) . field ("sdio_stat_rxore" , & self . sdio_stat_rxore ()) . field ("sdio_stat_cmdrecv" , & self . sdio_stat_cmdrecv ()) . field ("sdio_stat_cmdsend" , & self . sdio_stat_cmdsend ()) . field ("sdio_stat_dtend" , & self . sdio_stat_dtend ()) . field ("sdio_stat_stbite" , & self . sdio_stat_stbite ()) . field ("sdio_stat_dtblkend" , & self . sdio_stat_dtblkend ()) . field ("sdio_stat_cmdrun" , & self . sdio_stat_cmdrun ()) . field ("sdio_stat_txrun" , & self . sdio_stat_txrun ()) . field ("sdio_stat_rxrun" , & self . sdio_stat_rxrun ()) . field ("sdio_stat_tfh" , & self . sdio_stat_tfh ()) . field ("sdio_stat_rfh" , & self . sdio_stat_rfh ()) . field ("sdio_stat_tff" , & self . sdio_stat_tff ()) . field ("sdio_stat_rff" , & self . sdio_stat_rff ()) . field ("sdio_stat_tfe" , & self . sdio_stat_tfe ()) . field ("sdio_stat_rfe" , & self . sdio_stat_rfe ()) . field ("sdio_stat_txdtval" , & self . sdio_stat_txdtval ()) . field ("sdio_stat_rxdtval" , & self . sdio_stat_rxdtval ()) . field ("sdio_stat_sdioint" , & self . sdio_stat_sdioint ()) . field ("sdio_stat_ataend" , & self . sdio_stat_ataend ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SdioStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SdioStat {{ sdio_stat_ccrcerr: {=bool:?}, sdio_stat_dtcrcerr: {=bool:?}, sdio_stat_cmdtmout: {=bool:?}, sdio_stat_dttmout: {=bool:?}, sdio_stat_txure: {=bool:?}, sdio_stat_rxore: {=bool:?}, sdio_stat_cmdrecv: {=bool:?}, sdio_stat_cmdsend: {=bool:?}, sdio_stat_dtend: {=bool:?}, sdio_stat_stbite: {=bool:?}, sdio_stat_dtblkend: {=bool:?}, sdio_stat_cmdrun: {=bool:?}, sdio_stat_txrun: {=bool:?}, sdio_stat_rxrun: {=bool:?}, sdio_stat_tfh: {=bool:?}, sdio_stat_rfh: {=bool:?}, sdio_stat_tff: {=bool:?}, sdio_stat_rff: {=bool:?}, sdio_stat_tfe: {=bool:?}, sdio_stat_rfe: {=bool:?}, sdio_stat_txdtval: {=bool:?}, sdio_stat_rxdtval: {=bool:?}, sdio_stat_sdioint: {=bool:?}, sdio_stat_ataend: {=bool:?} }}" , self . sdio_stat_ccrcerr () , self . sdio_stat_dtcrcerr () , self . sdio_stat_cmdtmout () , self . sdio_stat_dttmout () , self . sdio_stat_txure () , self . sdio_stat_rxore () , self . sdio_stat_cmdrecv () , self . sdio_stat_cmdsend () , self . sdio_stat_dtend () , self . sdio_stat_stbite () , self . sdio_stat_dtblkend () , self . sdio_stat_cmdrun () , self . sdio_stat_txrun () , self . sdio_stat_rxrun () , self . sdio_stat_tfh () , self . sdio_stat_rfh () , self . sdio_stat_tff () , self . sdio_stat_rff () , self . sdio_stat_tfe () , self . sdio_stat_rfe () , self . sdio_stat_txdtval () , self . sdio_stat_rxdtval () , self . sdio_stat_sdioint () , self . sdio_stat_ataend ()) } } }