#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Serial/Quad Parallel Interface"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sqpi { ptr : * mut u8 } unsafe impl Send for Sqpi { } unsafe impl Sync for Sqpi { } impl Sqpi { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "SQPI Initial Register"]
# [inline (always)]
pub const fn init (self) -> crate :: common :: Reg < regs :: Init , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "SQPI Read Command Register"]
# [inline (always)]
pub const fn rcmd (self) -> crate :: common :: Reg < regs :: Rcmd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Write Command Register"]
# [inline (always)]
pub const fn wcmd (self) -> crate :: common :: Reg < regs :: Wcmd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "ID Low Register"]
# [inline (always)]
pub const fn idl (self) -> crate :: common :: Reg < regs :: Idl , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "ID High Register"]
# [inline (always)]
pub const fn idh (self) -> crate :: common :: Reg < regs :: Idh , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } } pub mod regs { # [doc = "ID High Register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Idh (pub u32) ; impl Idh { # [doc = "ID High Data saved for SQPI read ID command"]
# [inline (always)]
pub const fn sqpi_idh (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ID High Data saved for SQPI read ID command"]
# [inline (always)]
pub fn set_sqpi_idh (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Idh { # [inline (always)]
fn default () -> Idh { Idh (0) } } impl core :: fmt :: Debug for Idh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Idh") . field ("sqpi_idh" , & self . sqpi_idh ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Idh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Idh {{ sqpi_idh: {=u32:?} }}" , self . sqpi_idh ()) } } # [doc = "ID Low Register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Idl (pub u32) ; impl Idl { # [doc = "ID Low Data saved for SQPI Read ID Command"]
# [inline (always)]
pub const fn sqpi_idl (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ID Low Data saved for SQPI Read ID Command"]
# [inline (always)]
pub fn set_sqpi_idl (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Idl { # [inline (always)]
fn default () -> Idl { Idl (0) } } impl core :: fmt :: Debug for Idl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Idl") . field ("sqpi_idl" , & self . sqpi_idl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Idl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Idl {{ sqpi_idl: {=u32:?} }}" , self . sqpi_idl ()) } } # [doc = "SQPI Initial Register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Init (pub u32) ; impl Init { # [doc = "Bit number of SQPI controller command phase"]
# [inline (always)]
pub const fn sqpi_cmdbit (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x03 ; val as u8 } # [doc = "Bit number of SQPI controller command phase"]
# [inline (always)]
pub fn set_sqpi_cmdbit (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 16usize)) | (((val as u32) & 0x03) << 16usize) ; } # [doc = "Clock divider for SQPI output clock"]
# [inline (always)]
pub const fn sqpi_clkdiv (& self) -> u8 { let val = (self . 0 >> 18usize) & 0x3f ; val as u8 } # [doc = "Clock divider for SQPI output clock"]
# [inline (always)]
pub fn set_sqpi_clkdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 18usize)) | (((val as u32) & 0x3f) << 18usize) ; } # [doc = "Bit number of SPI PSRAM address phase."]
# [inline (always)]
pub const fn sqpi_addrbit (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x1f ; val as u8 } # [doc = "Bit number of SPI PSRAM address phase."]
# [inline (always)]
pub fn set_sqpi_addrbit (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 24usize)) | (((val as u32) & 0x1f) << 24usize) ; } # [doc = "SQPI controller external memory ID length"]
# [inline (always)]
pub const fn sqpi_idlen (& self) -> u8 { let val = (self . 0 >> 29usize) & 0x03 ; val as u8 } # [doc = "SQPI controller external memory ID length"]
# [inline (always)]
pub fn set_sqpi_idlen (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 29usize)) | (((val as u32) & 0x03) << 29usize) ; } # [doc = "Read data sample polarity."]
# [inline (always)]
pub const fn sqpi_pl (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Read data sample polarity."]
# [inline (always)]
pub fn set_sqpi_pl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Init { # [inline (always)]
fn default () -> Init { Init (0) } } impl core :: fmt :: Debug for Init { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Init") . field ("sqpi_cmdbit" , & self . sqpi_cmdbit ()) . field ("sqpi_clkdiv" , & self . sqpi_clkdiv ()) . field ("sqpi_addrbit" , & self . sqpi_addrbit ()) . field ("sqpi_idlen" , & self . sqpi_idlen ()) . field ("sqpi_pl" , & self . sqpi_pl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Init { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Init {{ sqpi_cmdbit: {=u8:?}, sqpi_clkdiv: {=u8:?}, sqpi_addrbit: {=u8:?}, sqpi_idlen: {=u8:?}, sqpi_pl: {=bool:?} }}" , self . sqpi_cmdbit () , self . sqpi_clkdiv () , self . sqpi_addrbit () , self . sqpi_idlen () , self . sqpi_pl ()) } } # [doc = "SQPI Read Command Register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rcmd (pub u32) ; impl Rcmd { # [doc = "SQPI read command for AHB read transfer"]
# [inline (always)]
pub const fn sqpi_rcmd (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "SQPI read command for AHB read transfer"]
# [inline (always)]
pub fn set_sqpi_rcmd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "SQPI read command waitcycle number after address phase"]
# [inline (always)]
pub const fn sqpi_rwaitcycle (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "SQPI read command waitcycle number after address phase"]
# [inline (always)]
pub fn set_sqpi_rwaitcycle (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "SQPI controller read command mode"]
# [inline (always)]
pub const fn sqpi_rmode (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x07 ; val as u8 } # [doc = "SQPI controller read command mode"]
# [inline (always)]
pub fn set_sqpi_rmode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 20usize)) | (((val as u32) & 0x07) << 20usize) ; } # [doc = "Send read ID command"]
# [inline (always)]
pub const fn sqpi_rid (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Send read ID command"]
# [inline (always)]
pub fn set_sqpi_rid (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Rcmd { # [inline (always)]
fn default () -> Rcmd { Rcmd (0) } } impl core :: fmt :: Debug for Rcmd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rcmd") . field ("sqpi_rcmd" , & self . sqpi_rcmd ()) . field ("sqpi_rwaitcycle" , & self . sqpi_rwaitcycle ()) . field ("sqpi_rmode" , & self . sqpi_rmode ()) . field ("sqpi_rid" , & self . sqpi_rid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rcmd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rcmd {{ sqpi_rcmd: {=u16:?}, sqpi_rwaitcycle: {=u8:?}, sqpi_rmode: {=u8:?}, sqpi_rid: {=bool:?} }}" , self . sqpi_rcmd () , self . sqpi_rwaitcycle () , self . sqpi_rmode () , self . sqpi_rid ()) } } # [doc = "Write Command Register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wcmd (pub u32) ; impl Wcmd { # [doc = "SQPI write command for AHB write transfer"]
# [inline (always)]
pub const fn spi_wcmd (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "SQPI write command for AHB write transfer"]
# [inline (always)]
pub fn set_spi_wcmd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "SQPI write command waitcycle number after address phase"]
# [inline (always)]
pub const fn sqpi_wwaitcycle (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x0f ; val as u8 } # [doc = "SQPI write command waitcycle number after address phase"]
# [inline (always)]
pub fn set_sqpi_wwaitcycle (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 16usize)) | (((val as u32) & 0x0f) << 16usize) ; } # [doc = "SQPI controller write command mode"]
# [inline (always)]
pub const fn sqpi_wmode (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x07 ; val as u8 } # [doc = "SQPI controller write command mode"]
# [inline (always)]
pub fn set_sqpi_wmode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 20usize)) | (((val as u32) & 0x07) << 20usize) ; } # [doc = "Send special command"]
# [inline (always)]
pub const fn sqpi_sc (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Send special command"]
# [inline (always)]
pub fn set_sqpi_sc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Wcmd { # [inline (always)]
fn default () -> Wcmd { Wcmd (0) } } impl core :: fmt :: Debug for Wcmd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Wcmd") . field ("spi_wcmd" , & self . spi_wcmd ()) . field ("sqpi_wwaitcycle" , & self . sqpi_wwaitcycle ()) . field ("sqpi_wmode" , & self . sqpi_wmode ()) . field ("sqpi_sc" , & self . sqpi_sc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Wcmd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Wcmd {{ spi_wcmd: {=u16:?}, sqpi_wwaitcycle: {=u8:?}, sqpi_wmode: {=u8:?}, sqpi_sc: {=bool:?} }}" , self . spi_wcmd () , self . sqpi_wwaitcycle () , self . sqpi_wmode () , self . sqpi_sc ()) } } }