#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Syscfg { ptr : * mut u8 } unsafe impl Send for Syscfg { } unsafe impl Sync for Syscfg { } impl Syscfg { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn syscfg_cfg0 (self) -> crate :: common :: Reg < regs :: SyscfgCfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn syscfg_cfg1 (self) -> crate :: common :: Reg < regs :: SyscfgCfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn syscfg_extiss0 (self) -> crate :: common :: Reg < regs :: SyscfgExtiss0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn syscfg_extiss1 (self) -> crate :: common :: Reg < regs :: SyscfgExtiss1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn syscfg_extiss2 (self) -> crate :: common :: Reg < regs :: SyscfgExtiss2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn syscfg_extiss3 (self) -> crate :: common :: Reg < regs :: SyscfgExtiss3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn syscfg_cfg2 (self) -> crate :: common :: Reg < regs :: SyscfgCfg2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn syscfg_stat (self) -> crate :: common :: Reg < regs :: SyscfgStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn syscfg_cfg3 (self) -> crate :: common :: Reg < regs :: SyscfgCfg3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn syscfg_cfg4 (self) -> crate :: common :: Reg < regs :: SyscfgCfg4 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn syscfg_cfg5 (self) -> crate :: common :: Reg < regs :: SyscfgCfg5 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn syscfg_tcmsramcs (self) -> crate :: common :: Reg < regs :: SyscfgTcmsramcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn syscfg_tcmsramkey (self) -> crate :: common :: Reg < regs :: SyscfgTcmsramkey , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn syscfg_tcmsramwp (self) -> crate :: common :: Reg < regs :: SyscfgTcmsramwp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn syscfg_cpsctl (self) -> crate :: common :: Reg < regs :: SyscfgCpsctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercisel0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn syscfg_timercisel1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x48usize) as _) } } # [inline (always)]
pub const fn syscfg_timercisel2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x4cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercisel3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x50usize) as _) } } # [inline (always)]
pub const fn syscfg_timercisel4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x54usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0100usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0104usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0108usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x010cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0110usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0114usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0118usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x011cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0120usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0124usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0128usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x012cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0130usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0134usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0138usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x013cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0140usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0144usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0148usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x014cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0150usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0154usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0158usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x015cusize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg0 (pub u32) ; impl SyscfgCfg0 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg0_boot_mode (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_syscfg_cfg0_boot_mode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg0_fmc_swp (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg0_fmc_swp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for SyscfgCfg0 { # [inline (always)]
fn default () -> SyscfgCfg0 { SyscfgCfg0 (0) } } impl core :: fmt :: Debug for SyscfgCfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg0") . field ("syscfg_cfg0_boot_mode" , & self . syscfg_cfg0_boot_mode ()) . field ("syscfg_cfg0_fmc_swp" , & self . syscfg_cfg0_fmc_swp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg0 {{ syscfg_cfg0_boot_mode: {=u8:?}, syscfg_cfg0_fmc_swp: {=bool:?} }}" , self . syscfg_cfg0_boot_mode () , self . syscfg_cfg0_fmc_swp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg1 (pub u32) ; impl SyscfgCfg1 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_pb6fmpen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_pb6fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_pb7fmpen (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_pb7fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_pb8fmpen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_pb8fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_pb9fmpen (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_pb9fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_i2c0fmpen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_i2c0fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_i2c1fmpen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_i2c1fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_i2c2fmpen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_i2c2fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_i2c3fmpen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_i2c3fmpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_fpuinten_iopie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_fpuinten_iopie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_fpuinten_dzie (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_fpuinten_dzie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_fpuinten_ufie (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_fpuinten_ufie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_fpuinten_ovfie (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_fpuinten_ovfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_fpuinten_idie (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_fpuinten_idie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_fpuinten_ixie (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_fpuinten_ixie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for SyscfgCfg1 { # [inline (always)]
fn default () -> SyscfgCfg1 { SyscfgCfg1 (0) } } impl core :: fmt :: Debug for SyscfgCfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg1") . field ("syscfg_cfg1_pb6fmpen" , & self . syscfg_cfg1_pb6fmpen ()) . field ("syscfg_cfg1_pb7fmpen" , & self . syscfg_cfg1_pb7fmpen ()) . field ("syscfg_cfg1_pb8fmpen" , & self . syscfg_cfg1_pb8fmpen ()) . field ("syscfg_cfg1_pb9fmpen" , & self . syscfg_cfg1_pb9fmpen ()) . field ("syscfg_cfg1_i2c0fmpen" , & self . syscfg_cfg1_i2c0fmpen ()) . field ("syscfg_cfg1_i2c1fmpen" , & self . syscfg_cfg1_i2c1fmpen ()) . field ("syscfg_cfg1_i2c2fmpen" , & self . syscfg_cfg1_i2c2fmpen ()) . field ("syscfg_cfg1_i2c3fmpen" , & self . syscfg_cfg1_i2c3fmpen ()) . field ("syscfg_cfg1_fpuinten_iopie" , & self . syscfg_cfg1_fpuinten_iopie ()) . field ("syscfg_cfg1_fpuinten_dzie" , & self . syscfg_cfg1_fpuinten_dzie ()) . field ("syscfg_cfg1_fpuinten_ufie" , & self . syscfg_cfg1_fpuinten_ufie ()) . field ("syscfg_cfg1_fpuinten_ovfie" , & self . syscfg_cfg1_fpuinten_ovfie ()) . field ("syscfg_cfg1_fpuinten_idie" , & self . syscfg_cfg1_fpuinten_idie ()) . field ("syscfg_cfg1_fpuinten_ixie" , & self . syscfg_cfg1_fpuinten_ixie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg1 {{ syscfg_cfg1_pb6fmpen: {=bool:?}, syscfg_cfg1_pb7fmpen: {=bool:?}, syscfg_cfg1_pb8fmpen: {=bool:?}, syscfg_cfg1_pb9fmpen: {=bool:?}, syscfg_cfg1_i2c0fmpen: {=bool:?}, syscfg_cfg1_i2c1fmpen: {=bool:?}, syscfg_cfg1_i2c2fmpen: {=bool:?}, syscfg_cfg1_i2c3fmpen: {=bool:?}, syscfg_cfg1_fpuinten_iopie: {=bool:?}, syscfg_cfg1_fpuinten_dzie: {=bool:?}, syscfg_cfg1_fpuinten_ufie: {=bool:?}, syscfg_cfg1_fpuinten_ovfie: {=bool:?}, syscfg_cfg1_fpuinten_idie: {=bool:?}, syscfg_cfg1_fpuinten_ixie: {=bool:?} }}" , self . syscfg_cfg1_pb6fmpen () , self . syscfg_cfg1_pb7fmpen () , self . syscfg_cfg1_pb8fmpen () , self . syscfg_cfg1_pb9fmpen () , self . syscfg_cfg1_i2c0fmpen () , self . syscfg_cfg1_i2c1fmpen () , self . syscfg_cfg1_i2c2fmpen () , self . syscfg_cfg1_i2c3fmpen () , self . syscfg_cfg1_fpuinten_iopie () , self . syscfg_cfg1_fpuinten_dzie () , self . syscfg_cfg1_fpuinten_ufie () , self . syscfg_cfg1_fpuinten_ovfie () , self . syscfg_cfg1_fpuinten_idie () , self . syscfg_cfg1_fpuinten_ixie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg2 (pub u32) ; impl SyscfgCfg2 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_lockup_lock (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_lockup_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_sram0_ecc_lock (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_sram0_ecc_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_lvd_lock (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_lvd_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_flash_ecc_lock (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_flash_ecc_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_sram1_ecc_lock (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_sram1_ecc_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_tcmsram_ecc_lock (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_tcmsram_ecc_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_pin_rstmd (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_pin_rstmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg2_trgsel_rstmd (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg2_trgsel_rstmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } } impl Default for SyscfgCfg2 { # [inline (always)]
fn default () -> SyscfgCfg2 { SyscfgCfg2 (0) } } impl core :: fmt :: Debug for SyscfgCfg2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg2") . field ("syscfg_cfg2_lockup_lock" , & self . syscfg_cfg2_lockup_lock ()) . field ("syscfg_cfg2_sram0_ecc_lock" , & self . syscfg_cfg2_sram0_ecc_lock ()) . field ("syscfg_cfg2_lvd_lock" , & self . syscfg_cfg2_lvd_lock ()) . field ("syscfg_cfg2_flash_ecc_lock" , & self . syscfg_cfg2_flash_ecc_lock ()) . field ("syscfg_cfg2_sram1_ecc_lock" , & self . syscfg_cfg2_sram1_ecc_lock ()) . field ("syscfg_cfg2_tcmsram_ecc_lock" , & self . syscfg_cfg2_tcmsram_ecc_lock ()) . field ("syscfg_cfg2_pin_rstmd" , & self . syscfg_cfg2_pin_rstmd ()) . field ("syscfg_cfg2_trgsel_rstmd" , & self . syscfg_cfg2_trgsel_rstmd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg2 {{ syscfg_cfg2_lockup_lock: {=bool:?}, syscfg_cfg2_sram0_ecc_lock: {=bool:?}, syscfg_cfg2_lvd_lock: {=bool:?}, syscfg_cfg2_flash_ecc_lock: {=bool:?}, syscfg_cfg2_sram1_ecc_lock: {=bool:?}, syscfg_cfg2_tcmsram_ecc_lock: {=bool:?}, syscfg_cfg2_pin_rstmd: {=bool:?}, syscfg_cfg2_trgsel_rstmd: {=bool:?} }}" , self . syscfg_cfg2_lockup_lock () , self . syscfg_cfg2_sram0_ecc_lock () , self . syscfg_cfg2_lvd_lock () , self . syscfg_cfg2_flash_ecc_lock () , self . syscfg_cfg2_sram1_ecc_lock () , self . syscfg_cfg2_tcmsram_ecc_lock () , self . syscfg_cfg2_pin_rstmd () , self . syscfg_cfg2_trgsel_rstmd ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg3 (pub u32) ; impl SyscfgCfg3 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_sram0eccmeie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg3_sram0eccmeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_sram0eccseie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg3_sram0eccseie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_flasheccie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg3_flasheccie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_ckmnmiie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg3_ckmnmiie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_nmipinie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg3_nmipinie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_sram0eccserrbits (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_cfg3_sram0eccserrbits (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 10usize)) | (((val as u32) & 0x3f) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg3_sram0ecceaddr (& self) -> u16 { let val = (self . 0 >> 17usize) & 0x7fff ; val as u16 } # [inline (always)]
pub const fn set_syscfg_cfg3_sram0ecceaddr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x7fff << 17usize)) | (((val as u32) & 0x7fff) << 17usize) ; } } impl Default for SyscfgCfg3 { # [inline (always)]
fn default () -> SyscfgCfg3 { SyscfgCfg3 (0) } } impl core :: fmt :: Debug for SyscfgCfg3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg3") . field ("syscfg_cfg3_sram0eccmeie" , & self . syscfg_cfg3_sram0eccmeie ()) . field ("syscfg_cfg3_sram0eccseie" , & self . syscfg_cfg3_sram0eccseie ()) . field ("syscfg_cfg3_flasheccie" , & self . syscfg_cfg3_flasheccie ()) . field ("syscfg_cfg3_ckmnmiie" , & self . syscfg_cfg3_ckmnmiie ()) . field ("syscfg_cfg3_nmipinie" , & self . syscfg_cfg3_nmipinie ()) . field ("syscfg_cfg3_sram0eccserrbits" , & self . syscfg_cfg3_sram0eccserrbits ()) . field ("syscfg_cfg3_sram0ecceaddr" , & self . syscfg_cfg3_sram0ecceaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg3 {{ syscfg_cfg3_sram0eccmeie: {=bool:?}, syscfg_cfg3_sram0eccseie: {=bool:?}, syscfg_cfg3_flasheccie: {=bool:?}, syscfg_cfg3_ckmnmiie: {=bool:?}, syscfg_cfg3_nmipinie: {=bool:?}, syscfg_cfg3_sram0eccserrbits: {=u8:?}, syscfg_cfg3_sram0ecceaddr: {=u16:?} }}" , self . syscfg_cfg3_sram0eccmeie () , self . syscfg_cfg3_sram0eccseie () , self . syscfg_cfg3_flasheccie () , self . syscfg_cfg3_ckmnmiie () , self . syscfg_cfg3_nmipinie () , self . syscfg_cfg3_sram0eccserrbits () , self . syscfg_cfg3_sram0ecceaddr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg4 (pub u32) ; impl SyscfgCfg4 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg4_sram1eccmeie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg4_sram1eccmeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg4_sram1eccseie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg4_sram1eccseie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg4_sram1eccserrbits (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_cfg4_sram1eccserrbits (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 10usize)) | (((val as u32) & 0x3f) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg4_sram1ecceaddr (& self) -> u16 { let val = (self . 0 >> 20usize) & 0x0fff ; val as u16 } # [inline (always)]
pub const fn set_syscfg_cfg4_sram1ecceaddr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 20usize)) | (((val as u32) & 0x0fff) << 20usize) ; } } impl Default for SyscfgCfg4 { # [inline (always)]
fn default () -> SyscfgCfg4 { SyscfgCfg4 (0) } } impl core :: fmt :: Debug for SyscfgCfg4 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg4") . field ("syscfg_cfg4_sram1eccmeie" , & self . syscfg_cfg4_sram1eccmeie ()) . field ("syscfg_cfg4_sram1eccseie" , & self . syscfg_cfg4_sram1eccseie ()) . field ("syscfg_cfg4_sram1eccserrbits" , & self . syscfg_cfg4_sram1eccserrbits ()) . field ("syscfg_cfg4_sram1ecceaddr" , & self . syscfg_cfg4_sram1ecceaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg4 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg4 {{ syscfg_cfg4_sram1eccmeie: {=bool:?}, syscfg_cfg4_sram1eccseie: {=bool:?}, syscfg_cfg4_sram1eccserrbits: {=u8:?}, syscfg_cfg4_sram1ecceaddr: {=u16:?} }}" , self . syscfg_cfg4_sram1eccmeie () , self . syscfg_cfg4_sram1eccseie () , self . syscfg_cfg4_sram1eccserrbits () , self . syscfg_cfg4_sram1ecceaddr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg5 (pub u32) ; impl SyscfgCfg5 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg5_tcmsrameccmeie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg5_tcmsrameccmeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg5_tcmsrameccseie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg5_tcmsrameccseie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg5_tcmsrameccserrbits (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_cfg5_tcmsrameccserrbits (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 10usize)) | (((val as u32) & 0x3f) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg5_tcmsramecceaddr (& self) -> u16 { let val = (self . 0 >> 19usize) & 0x1fff ; val as u16 } # [inline (always)]
pub const fn set_syscfg_cfg5_tcmsramecceaddr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x1fff << 19usize)) | (((val as u32) & 0x1fff) << 19usize) ; } } impl Default for SyscfgCfg5 { # [inline (always)]
fn default () -> SyscfgCfg5 { SyscfgCfg5 (0) } } impl core :: fmt :: Debug for SyscfgCfg5 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg5") . field ("syscfg_cfg5_tcmsrameccmeie" , & self . syscfg_cfg5_tcmsrameccmeie ()) . field ("syscfg_cfg5_tcmsrameccseie" , & self . syscfg_cfg5_tcmsrameccseie ()) . field ("syscfg_cfg5_tcmsrameccserrbits" , & self . syscfg_cfg5_tcmsrameccserrbits ()) . field ("syscfg_cfg5_tcmsramecceaddr" , & self . syscfg_cfg5_tcmsramecceaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg5 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg5 {{ syscfg_cfg5_tcmsrameccmeie: {=bool:?}, syscfg_cfg5_tcmsrameccseie: {=bool:?}, syscfg_cfg5_tcmsrameccserrbits: {=u8:?}, syscfg_cfg5_tcmsramecceaddr: {=u16:?} }}" , self . syscfg_cfg5_tcmsrameccmeie () , self . syscfg_cfg5_tcmsrameccseie () , self . syscfg_cfg5_tcmsrameccserrbits () , self . syscfg_cfg5_tcmsramecceaddr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCpsctl (pub u32) ; impl SyscfgCpsctl { # [must_use]
# [inline (always)]
pub const fn syscfg_cpsctl_cps_en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cpsctl_cps_en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cpsctl_cps_rdy (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cpsctl_cps_rdy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for SyscfgCpsctl { # [inline (always)]
fn default () -> SyscfgCpsctl { SyscfgCpsctl (0) } } impl core :: fmt :: Debug for SyscfgCpsctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCpsctl") . field ("syscfg_cpsctl_cps_en" , & self . syscfg_cpsctl_cps_en ()) . field ("syscfg_cpsctl_cps_rdy" , & self . syscfg_cpsctl_cps_rdy ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCpsctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCpsctl {{ syscfg_cpsctl_cps_en: {=bool:?}, syscfg_cpsctl_cps_rdy: {=bool:?} }}" , self . syscfg_cpsctl_cps_en () , self . syscfg_cpsctl_cps_rdy ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgExtiss0 (pub u32) ; impl SyscfgExtiss0 { # [must_use]
# [inline (always)]
pub const fn syscfg_extiss0_exti0_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss0_exti0_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss0_exti1_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss0_exti1_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss0_exti2_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss0_exti2_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss0_exti3_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss0_exti3_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for SyscfgExtiss0 { # [inline (always)]
fn default () -> SyscfgExtiss0 { SyscfgExtiss0 (0) } } impl core :: fmt :: Debug for SyscfgExtiss0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgExtiss0") . field ("syscfg_extiss0_exti0_ss" , & self . syscfg_extiss0_exti0_ss ()) . field ("syscfg_extiss0_exti1_ss" , & self . syscfg_extiss0_exti1_ss ()) . field ("syscfg_extiss0_exti2_ss" , & self . syscfg_extiss0_exti2_ss ()) . field ("syscfg_extiss0_exti3_ss" , & self . syscfg_extiss0_exti3_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgExtiss0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgExtiss0 {{ syscfg_extiss0_exti0_ss: {=u8:?}, syscfg_extiss0_exti1_ss: {=u8:?}, syscfg_extiss0_exti2_ss: {=u8:?}, syscfg_extiss0_exti3_ss: {=u8:?} }}" , self . syscfg_extiss0_exti0_ss () , self . syscfg_extiss0_exti1_ss () , self . syscfg_extiss0_exti2_ss () , self . syscfg_extiss0_exti3_ss ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgExtiss1 (pub u32) ; impl SyscfgExtiss1 { # [must_use]
# [inline (always)]
pub const fn syscfg_extiss1_exti4_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss1_exti4_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss1_exti5_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss1_exti5_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss1_exti6_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss1_exti6_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss1_exti7_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss1_exti7_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for SyscfgExtiss1 { # [inline (always)]
fn default () -> SyscfgExtiss1 { SyscfgExtiss1 (0) } } impl core :: fmt :: Debug for SyscfgExtiss1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgExtiss1") . field ("syscfg_extiss1_exti4_ss" , & self . syscfg_extiss1_exti4_ss ()) . field ("syscfg_extiss1_exti5_ss" , & self . syscfg_extiss1_exti5_ss ()) . field ("syscfg_extiss1_exti6_ss" , & self . syscfg_extiss1_exti6_ss ()) . field ("syscfg_extiss1_exti7_ss" , & self . syscfg_extiss1_exti7_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgExtiss1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgExtiss1 {{ syscfg_extiss1_exti4_ss: {=u8:?}, syscfg_extiss1_exti5_ss: {=u8:?}, syscfg_extiss1_exti6_ss: {=u8:?}, syscfg_extiss1_exti7_ss: {=u8:?} }}" , self . syscfg_extiss1_exti4_ss () , self . syscfg_extiss1_exti5_ss () , self . syscfg_extiss1_exti6_ss () , self . syscfg_extiss1_exti7_ss ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgExtiss2 (pub u32) ; impl SyscfgExtiss2 { # [must_use]
# [inline (always)]
pub const fn syscfg_extiss2_exti8_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss2_exti8_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss2_exti9_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss2_exti9_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss2_exti10_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss2_exti10_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss2_exti11_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss2_exti11_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for SyscfgExtiss2 { # [inline (always)]
fn default () -> SyscfgExtiss2 { SyscfgExtiss2 (0) } } impl core :: fmt :: Debug for SyscfgExtiss2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgExtiss2") . field ("syscfg_extiss2_exti8_ss" , & self . syscfg_extiss2_exti8_ss ()) . field ("syscfg_extiss2_exti9_ss" , & self . syscfg_extiss2_exti9_ss ()) . field ("syscfg_extiss2_exti10_ss" , & self . syscfg_extiss2_exti10_ss ()) . field ("syscfg_extiss2_exti11_ss" , & self . syscfg_extiss2_exti11_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgExtiss2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgExtiss2 {{ syscfg_extiss2_exti8_ss: {=u8:?}, syscfg_extiss2_exti9_ss: {=u8:?}, syscfg_extiss2_exti10_ss: {=u8:?}, syscfg_extiss2_exti11_ss: {=u8:?} }}" , self . syscfg_extiss2_exti8_ss () , self . syscfg_extiss2_exti9_ss () , self . syscfg_extiss2_exti10_ss () , self . syscfg_extiss2_exti11_ss ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgExtiss3 (pub u32) ; impl SyscfgExtiss3 { # [must_use]
# [inline (always)]
pub const fn syscfg_extiss3_exti12_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss3_exti12_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss3_exti13_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss3_exti13_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss3_exti14_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss3_exti14_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_extiss3_exti15_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_extiss3_exti15_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for SyscfgExtiss3 { # [inline (always)]
fn default () -> SyscfgExtiss3 { SyscfgExtiss3 (0) } } impl core :: fmt :: Debug for SyscfgExtiss3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgExtiss3") . field ("syscfg_extiss3_exti12_ss" , & self . syscfg_extiss3_exti12_ss ()) . field ("syscfg_extiss3_exti13_ss" , & self . syscfg_extiss3_exti13_ss ()) . field ("syscfg_extiss3_exti14_ss" , & self . syscfg_extiss3_exti14_ss ()) . field ("syscfg_extiss3_exti15_ss" , & self . syscfg_extiss3_exti15_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgExtiss3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgExtiss3 {{ syscfg_extiss3_exti12_ss: {=u8:?}, syscfg_extiss3_exti13_ss: {=u8:?}, syscfg_extiss3_exti14_ss: {=u8:?}, syscfg_extiss3_exti15_ss: {=u8:?} }}" , self . syscfg_extiss3_exti12_ss () , self . syscfg_extiss3_exti13_ss () , self . syscfg_extiss3_exti14_ss () , self . syscfg_extiss3_exti15_ss ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgStat (pub u32) ; impl SyscfgStat { # [must_use]
# [inline (always)]
pub const fn syscfg_stat_sram0eccmeif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_sram0eccmeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_sram0eccseif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_sram0eccseif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_flasheccif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_flasheccif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_ckmnmiif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_ckmnmiif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_nmipinif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_nmipinif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_sram1eccmeif (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_sram1eccmeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_sram1eccseif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_sram1eccseif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_tcmsrameccmeif (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_tcmsrameccmeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_stat_tcmsrameccseif (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_stat_tcmsrameccseif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for SyscfgStat { # [inline (always)]
fn default () -> SyscfgStat { SyscfgStat (0) } } impl core :: fmt :: Debug for SyscfgStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgStat") . field ("syscfg_stat_sram0eccmeif" , & self . syscfg_stat_sram0eccmeif ()) . field ("syscfg_stat_sram0eccseif" , & self . syscfg_stat_sram0eccseif ()) . field ("syscfg_stat_flasheccif" , & self . syscfg_stat_flasheccif ()) . field ("syscfg_stat_ckmnmiif" , & self . syscfg_stat_ckmnmiif ()) . field ("syscfg_stat_nmipinif" , & self . syscfg_stat_nmipinif ()) . field ("syscfg_stat_sram1eccmeif" , & self . syscfg_stat_sram1eccmeif ()) . field ("syscfg_stat_sram1eccseif" , & self . syscfg_stat_sram1eccseif ()) . field ("syscfg_stat_tcmsrameccmeif" , & self . syscfg_stat_tcmsrameccmeif ()) . field ("syscfg_stat_tcmsrameccseif" , & self . syscfg_stat_tcmsrameccseif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgStat {{ syscfg_stat_sram0eccmeif: {=bool:?}, syscfg_stat_sram0eccseif: {=bool:?}, syscfg_stat_flasheccif: {=bool:?}, syscfg_stat_ckmnmiif: {=bool:?}, syscfg_stat_nmipinif: {=bool:?}, syscfg_stat_sram1eccmeif: {=bool:?}, syscfg_stat_sram1eccseif: {=bool:?}, syscfg_stat_tcmsrameccmeif: {=bool:?}, syscfg_stat_tcmsrameccseif: {=bool:?} }}" , self . syscfg_stat_sram0eccmeif () , self . syscfg_stat_sram0eccseif () , self . syscfg_stat_flasheccif () , self . syscfg_stat_ckmnmiif () , self . syscfg_stat_nmipinif () , self . syscfg_stat_sram1eccmeif () , self . syscfg_stat_sram1eccseif () , self . syscfg_stat_tcmsrameccmeif () , self . syscfg_stat_tcmsrameccseif ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgTcmsramcs (pub u32) ; impl SyscfgTcmsramcs { # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramcs_tcmsramer (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramcs_tcmsramer (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramcs_tcmsrambsy (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramcs_tcmsrambsy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for SyscfgTcmsramcs { # [inline (always)]
fn default () -> SyscfgTcmsramcs { SyscfgTcmsramcs (0) } } impl core :: fmt :: Debug for SyscfgTcmsramcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgTcmsramcs") . field ("syscfg_tcmsramcs_tcmsramer" , & self . syscfg_tcmsramcs_tcmsramer ()) . field ("syscfg_tcmsramcs_tcmsrambsy" , & self . syscfg_tcmsramcs_tcmsrambsy ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgTcmsramcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgTcmsramcs {{ syscfg_tcmsramcs_tcmsramer: {=bool:?}, syscfg_tcmsramcs_tcmsrambsy: {=bool:?} }}" , self . syscfg_tcmsramcs_tcmsramer () , self . syscfg_tcmsramcs_tcmsrambsy ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgTcmsramkey (pub u32) ; impl SyscfgTcmsramkey { # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramkey_wp_key (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_syscfg_tcmsramkey_wp_key (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for SyscfgTcmsramkey { # [inline (always)]
fn default () -> SyscfgTcmsramkey { SyscfgTcmsramkey (0) } } impl core :: fmt :: Debug for SyscfgTcmsramkey { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgTcmsramkey") . field ("syscfg_tcmsramkey_wp_key" , & self . syscfg_tcmsramkey_wp_key ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgTcmsramkey { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgTcmsramkey {{ syscfg_tcmsramkey_wp_key: {=u8:?} }}" , self . syscfg_tcmsramkey_wp_key ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgTcmsramwp (pub u32) ; impl SyscfgTcmsramwp { # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p0wpen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p0wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p1wpen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p1wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p2wpen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p2wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p3wpen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p3wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p4wpen (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p4wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p5wpen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p5wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p6wpen (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p6wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p7wpen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p7wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p8wpen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p8wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p9wpen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p9wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p10wpen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p10wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p11wpen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p11wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p12wpen (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p12wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p13wpen (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p13wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p14wpen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p14wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p15wpen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p15wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p16wpen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p16wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p17wpen (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p17wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p18wpen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p18wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p19wpen (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p19wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p20wpen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p20wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p21wpen (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p21wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p22wpen (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p22wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p23wpen (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p23wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p24wpen (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p24wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p25wpen (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p25wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p26wpen (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p26wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p27wpen (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p27wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p28wpen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p28wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p29wpen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p29wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p30wpen (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p30wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_tcmsramwp_p31wpen (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_tcmsramwp_p31wpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for SyscfgTcmsramwp { # [inline (always)]
fn default () -> SyscfgTcmsramwp { SyscfgTcmsramwp (0) } } impl core :: fmt :: Debug for SyscfgTcmsramwp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgTcmsramwp") . field ("syscfg_tcmsramwp_p0wpen" , & self . syscfg_tcmsramwp_p0wpen ()) . field ("syscfg_tcmsramwp_p1wpen" , & self . syscfg_tcmsramwp_p1wpen ()) . field ("syscfg_tcmsramwp_p2wpen" , & self . syscfg_tcmsramwp_p2wpen ()) . field ("syscfg_tcmsramwp_p3wpen" , & self . syscfg_tcmsramwp_p3wpen ()) . field ("syscfg_tcmsramwp_p4wpen" , & self . syscfg_tcmsramwp_p4wpen ()) . field ("syscfg_tcmsramwp_p5wpen" , & self . syscfg_tcmsramwp_p5wpen ()) . field ("syscfg_tcmsramwp_p6wpen" , & self . syscfg_tcmsramwp_p6wpen ()) . field ("syscfg_tcmsramwp_p7wpen" , & self . syscfg_tcmsramwp_p7wpen ()) . field ("syscfg_tcmsramwp_p8wpen" , & self . syscfg_tcmsramwp_p8wpen ()) . field ("syscfg_tcmsramwp_p9wpen" , & self . syscfg_tcmsramwp_p9wpen ()) . field ("syscfg_tcmsramwp_p10wpen" , & self . syscfg_tcmsramwp_p10wpen ()) . field ("syscfg_tcmsramwp_p11wpen" , & self . syscfg_tcmsramwp_p11wpen ()) . field ("syscfg_tcmsramwp_p12wpen" , & self . syscfg_tcmsramwp_p12wpen ()) . field ("syscfg_tcmsramwp_p13wpen" , & self . syscfg_tcmsramwp_p13wpen ()) . field ("syscfg_tcmsramwp_p14wpen" , & self . syscfg_tcmsramwp_p14wpen ()) . field ("syscfg_tcmsramwp_p15wpen" , & self . syscfg_tcmsramwp_p15wpen ()) . field ("syscfg_tcmsramwp_p16wpen" , & self . syscfg_tcmsramwp_p16wpen ()) . field ("syscfg_tcmsramwp_p17wpen" , & self . syscfg_tcmsramwp_p17wpen ()) . field ("syscfg_tcmsramwp_p18wpen" , & self . syscfg_tcmsramwp_p18wpen ()) . field ("syscfg_tcmsramwp_p19wpen" , & self . syscfg_tcmsramwp_p19wpen ()) . field ("syscfg_tcmsramwp_p20wpen" , & self . syscfg_tcmsramwp_p20wpen ()) . field ("syscfg_tcmsramwp_p21wpen" , & self . syscfg_tcmsramwp_p21wpen ()) . field ("syscfg_tcmsramwp_p22wpen" , & self . syscfg_tcmsramwp_p22wpen ()) . field ("syscfg_tcmsramwp_p23wpen" , & self . syscfg_tcmsramwp_p23wpen ()) . field ("syscfg_tcmsramwp_p24wpen" , & self . syscfg_tcmsramwp_p24wpen ()) . field ("syscfg_tcmsramwp_p25wpen" , & self . syscfg_tcmsramwp_p25wpen ()) . field ("syscfg_tcmsramwp_p26wpen" , & self . syscfg_tcmsramwp_p26wpen ()) . field ("syscfg_tcmsramwp_p27wpen" , & self . syscfg_tcmsramwp_p27wpen ()) . field ("syscfg_tcmsramwp_p28wpen" , & self . syscfg_tcmsramwp_p28wpen ()) . field ("syscfg_tcmsramwp_p29wpen" , & self . syscfg_tcmsramwp_p29wpen ()) . field ("syscfg_tcmsramwp_p30wpen" , & self . syscfg_tcmsramwp_p30wpen ()) . field ("syscfg_tcmsramwp_p31wpen" , & self . syscfg_tcmsramwp_p31wpen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgTcmsramwp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgTcmsramwp {{ syscfg_tcmsramwp_p0wpen: {=bool:?}, syscfg_tcmsramwp_p1wpen: {=bool:?}, syscfg_tcmsramwp_p2wpen: {=bool:?}, syscfg_tcmsramwp_p3wpen: {=bool:?}, syscfg_tcmsramwp_p4wpen: {=bool:?}, syscfg_tcmsramwp_p5wpen: {=bool:?}, syscfg_tcmsramwp_p6wpen: {=bool:?}, syscfg_tcmsramwp_p7wpen: {=bool:?}, syscfg_tcmsramwp_p8wpen: {=bool:?}, syscfg_tcmsramwp_p9wpen: {=bool:?}, syscfg_tcmsramwp_p10wpen: {=bool:?}, syscfg_tcmsramwp_p11wpen: {=bool:?}, syscfg_tcmsramwp_p12wpen: {=bool:?}, syscfg_tcmsramwp_p13wpen: {=bool:?}, syscfg_tcmsramwp_p14wpen: {=bool:?}, syscfg_tcmsramwp_p15wpen: {=bool:?}, syscfg_tcmsramwp_p16wpen: {=bool:?}, syscfg_tcmsramwp_p17wpen: {=bool:?}, syscfg_tcmsramwp_p18wpen: {=bool:?}, syscfg_tcmsramwp_p19wpen: {=bool:?}, syscfg_tcmsramwp_p20wpen: {=bool:?}, syscfg_tcmsramwp_p21wpen: {=bool:?}, syscfg_tcmsramwp_p22wpen: {=bool:?}, syscfg_tcmsramwp_p23wpen: {=bool:?}, syscfg_tcmsramwp_p24wpen: {=bool:?}, syscfg_tcmsramwp_p25wpen: {=bool:?}, syscfg_tcmsramwp_p26wpen: {=bool:?}, syscfg_tcmsramwp_p27wpen: {=bool:?}, syscfg_tcmsramwp_p28wpen: {=bool:?}, syscfg_tcmsramwp_p29wpen: {=bool:?}, syscfg_tcmsramwp_p30wpen: {=bool:?}, syscfg_tcmsramwp_p31wpen: {=bool:?} }}" , self . syscfg_tcmsramwp_p0wpen () , self . syscfg_tcmsramwp_p1wpen () , self . syscfg_tcmsramwp_p2wpen () , self . syscfg_tcmsramwp_p3wpen () , self . syscfg_tcmsramwp_p4wpen () , self . syscfg_tcmsramwp_p5wpen () , self . syscfg_tcmsramwp_p6wpen () , self . syscfg_tcmsramwp_p7wpen () , self . syscfg_tcmsramwp_p8wpen () , self . syscfg_tcmsramwp_p9wpen () , self . syscfg_tcmsramwp_p10wpen () , self . syscfg_tcmsramwp_p11wpen () , self . syscfg_tcmsramwp_p12wpen () , self . syscfg_tcmsramwp_p13wpen () , self . syscfg_tcmsramwp_p14wpen () , self . syscfg_tcmsramwp_p15wpen () , self . syscfg_tcmsramwp_p16wpen () , self . syscfg_tcmsramwp_p17wpen () , self . syscfg_tcmsramwp_p18wpen () , self . syscfg_tcmsramwp_p19wpen () , self . syscfg_tcmsramwp_p20wpen () , self . syscfg_tcmsramwp_p21wpen () , self . syscfg_tcmsramwp_p22wpen () , self . syscfg_tcmsramwp_p23wpen () , self . syscfg_tcmsramwp_p24wpen () , self . syscfg_tcmsramwp_p25wpen () , self . syscfg_tcmsramwp_p26wpen () , self . syscfg_tcmsramwp_p27wpen () , self . syscfg_tcmsramwp_p28wpen () , self . syscfg_tcmsramwp_p29wpen () , self . syscfg_tcmsramwp_p30wpen () , self . syscfg_tcmsramwp_p31wpen ()) } } }