#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "System configuration controller"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Syscfg { ptr : * mut u8 } unsafe impl Send for Syscfg { } unsafe impl Sync for Syscfg { } impl Syscfg { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "System configuration register 0"]
# [inline (always)]
pub const fn cfg0 (self) -> crate :: common :: Reg < regs :: Cfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "System configuration register 1"]
# [inline (always)]
pub const fn cfg1 (self) -> crate :: common :: Reg < regs :: Cfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "EXTI sources selection register 0"]
# [inline (always)]
pub const fn extiss0 (self) -> crate :: common :: Reg < regs :: Extiss0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "EXTI sources selection register 1"]
# [inline (always)]
pub const fn extiss1 (self) -> crate :: common :: Reg < regs :: Extiss1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "EXTI sources selection register 2"]
# [inline (always)]
pub const fn extiss2 (self) -> crate :: common :: Reg < regs :: Extiss2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "EXTI sources selection register 3"]
# [inline (always)]
pub const fn extiss3 (self) -> crate :: common :: Reg < regs :: Extiss3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "System configuration register 2"]
# [inline (always)]
pub const fn cfg2 (self) -> crate :: common :: Reg < regs :: Cfg2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "System status register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "System configuration register 3"]
# [inline (always)]
pub const fn cfg3 (self) -> crate :: common :: Reg < regs :: Cfg3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "TIMER input source select register"]
# [inline (always)]
pub const fn timerinsel (self) -> crate :: common :: Reg < regs :: Timerinsel , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } } pub mod regs { # [doc = "System configuration register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg0 (pub u32) ; impl Cfg0 { # [doc = "Boot mode"]
# [inline (always)]
pub const fn boot_mode (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Boot mode"]
# [inline (always)]
pub fn set_boot_mode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "PA9 and PA12 remapping bit for small packages"]
# [inline (always)]
pub const fn pa9_pa12_rmp (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "PA9 and PA12 remapping bit for small packages"]
# [inline (always)]
pub fn set_pa9_pa12_rmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "BOOT0 and PF0 remapping bit"]
# [inline (always)]
pub const fn boot0_pf0_rmp (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "BOOT0 and PF0 remapping bit"]
# [inline (always)]
pub fn set_boot0_pf0_rmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for Cfg0 { # [inline (always)]
fn default () -> Cfg0 { Cfg0 (0) } } impl core :: fmt :: Debug for Cfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg0") . field ("boot_mode" , & self . boot_mode ()) . field ("pa9_pa12_rmp" , & self . pa9_pa12_rmp ()) . field ("boot0_pf0_rmp" , & self . boot0_pf0_rmp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg0 {{ boot_mode: {=u8:?}, pa9_pa12_rmp: {=bool:?}, boot0_pf0_rmp: {=bool:?} }}" , self . boot_mode () , self . pa9_pa12_rmp () , self . boot0_pf0_rmp ()) } } # [doc = "System configuration register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg1 (pub u32) ; impl Cfg1 { # [doc = "ADC1 channel 14 remapping bit"]
# [inline (always)]
pub const fn adc1ch14rmp (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "ADC1 channel 14 remapping bit"]
# [inline (always)]
pub fn set_adc1ch14rmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "ADC1 channel 15 remapping bit"]
# [inline (always)]
pub const fn adc1ch15rmp (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "ADC1 channel 15 remapping bit"]
# [inline (always)]
pub fn set_adc1ch15rmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "ADC0 channel 8 remapping bit"]
# [inline (always)]
pub const fn adc0ch8rmp (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "ADC0 channel 8 remapping bit"]
# [inline (always)]
pub fn set_adc0ch8rmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "ADC0 channel 9 remapping bit"]
# [inline (always)]
pub const fn adc0ch9rmp (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "ADC0 channel 9 remapping bit"]
# [inline (always)]
pub fn set_adc0ch9rmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cfg1 { # [inline (always)]
fn default () -> Cfg1 { Cfg1 (0) } } impl core :: fmt :: Debug for Cfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg1") . field ("adc1ch14rmp" , & self . adc1ch14rmp ()) . field ("adc1ch15rmp" , & self . adc1ch15rmp ()) . field ("adc0ch8rmp" , & self . adc0ch8rmp ()) . field ("adc0ch9rmp" , & self . adc0ch9rmp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg1 {{ adc1ch14rmp: {=bool:?}, adc1ch15rmp: {=bool:?}, adc0ch8rmp: {=bool:?}, adc0ch9rmp: {=bool:?} }}" , self . adc1ch14rmp () , self . adc1ch15rmp () , self . adc0ch8rmp () , self . adc0ch9rmp ()) } } # [doc = "System configuration register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg2 (pub u32) ; impl Cfg2 { # [doc = "Cortex-M33 LOCKUP output lock"]
# [inline (always)]
pub const fn lockup_lock (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Cortex-M33 LOCKUP output lock"]
# [inline (always)]
pub fn set_lockup_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SRAM ECC check error lock"]
# [inline (always)]
pub const fn sram_ecc_error_lock (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SRAM ECC check error lock"]
# [inline (always)]
pub fn set_sram_ecc_error_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "LVD lock"]
# [inline (always)]
pub const fn lvd_lock (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "LVD lock"]
# [inline (always)]
pub fn set_lvd_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for Cfg2 { # [inline (always)]
fn default () -> Cfg2 { Cfg2 (0) } } impl core :: fmt :: Debug for Cfg2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg2") . field ("lockup_lock" , & self . lockup_lock ()) . field ("sram_ecc_error_lock" , & self . sram_ecc_error_lock ()) . field ("lvd_lock" , & self . lvd_lock ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg2 {{ lockup_lock: {=bool:?}, sram_ecc_error_lock: {=bool:?}, lvd_lock: {=bool:?} }}" , self . lockup_lock () , self . sram_ecc_error_lock () , self . lvd_lock ()) } } # [doc = "System configuration register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg3 (pub u32) ; impl Cfg3 { # [doc = "SRAM multi-bits non-correction interrupt enable"]
# [inline (always)]
pub const fn srameccmeie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "SRAM multi-bits non-correction interrupt enable"]
# [inline (always)]
pub fn set_srameccmeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SRAM single bit correction interrupt enable"]
# [inline (always)]
pub const fn srameccseie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SRAM single bit correction interrupt enable"]
# [inline (always)]
pub fn set_srameccseie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Flash ECC NMI enable"]
# [inline (always)]
pub const fn flasheccie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Flash ECC NMI enable"]
# [inline (always)]
pub fn set_flasheccie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "HXTAL clock moniotor NMI enable"]
# [inline (always)]
pub const fn ckmnmiie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "HXTAL clock moniotor NMI enable"]
# [inline (always)]
pub fn set_ckmnmiie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "NMI pin interrupt enable"]
# [inline (always)]
pub const fn nmipinie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "NMI pin interrupt enable"]
# [inline (always)]
pub fn set_nmipinie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Which one bit has an SRAM ECC single-bit correctable error"]
# [inline (always)]
pub const fn srameccserrbits (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x3f ; val as u8 } # [doc = "Which one bit has an SRAM ECC single-bit correctable error"]
# [inline (always)]
pub fn set_srameccserrbits (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 12usize)) | (((val as u32) & 0x3f) << 12usize) ; } # [doc = "Record the faulting system address"]
# [inline (always)]
pub const fn sramecceaddr (& self) -> u16 { let val = (self . 0 >> 18usize) & 0x3fff ; val as u16 } # [doc = "Record the faulting system address"]
# [inline (always)]
pub fn set_sramecceaddr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x3fff << 18usize)) | (((val as u32) & 0x3fff) << 18usize) ; } } impl Default for Cfg3 { # [inline (always)]
fn default () -> Cfg3 { Cfg3 (0) } } impl core :: fmt :: Debug for Cfg3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg3") . field ("srameccmeie" , & self . srameccmeie ()) . field ("srameccseie" , & self . srameccseie ()) . field ("flasheccie" , & self . flasheccie ()) . field ("ckmnmiie" , & self . ckmnmiie ()) . field ("nmipinie" , & self . nmipinie ()) . field ("srameccserrbits" , & self . srameccserrbits ()) . field ("sramecceaddr" , & self . sramecceaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg3 {{ srameccmeie: {=bool:?}, srameccseie: {=bool:?}, flasheccie: {=bool:?}, ckmnmiie: {=bool:?}, nmipinie: {=bool:?}, srameccserrbits: {=u8:?}, sramecceaddr: {=u16:?} }}" , self . srameccmeie () , self . srameccseie () , self . flasheccie () , self . ckmnmiie () , self . nmipinie () , self . srameccserrbits () , self . sramecceaddr ()) } } # [doc = "EXTI sources selection register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extiss0 (pub u32) ; impl Extiss0 { # [doc = "EXTI 0 sources selection"]
# [inline (always)]
pub const fn exti0_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "EXTI 0 sources selection"]
# [inline (always)]
pub fn set_exti0_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "EXTI 1 sources selection"]
# [inline (always)]
pub const fn exti1_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "EXTI 1 sources selection"]
# [inline (always)]
pub fn set_exti1_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "EXTI 2 sources selection"]
# [inline (always)]
pub const fn exti2_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "EXTI 2 sources selection"]
# [inline (always)]
pub fn set_exti2_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "EXTI 3 sources selection"]
# [inline (always)]
pub const fn exti3_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "EXTI 3 sources selection"]
# [inline (always)]
pub fn set_exti3_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Extiss0 { # [inline (always)]
fn default () -> Extiss0 { Extiss0 (0) } } impl core :: fmt :: Debug for Extiss0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extiss0") . field ("exti0_ss" , & self . exti0_ss ()) . field ("exti1_ss" , & self . exti1_ss ()) . field ("exti2_ss" , & self . exti2_ss ()) . field ("exti3_ss" , & self . exti3_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extiss0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extiss0 {{ exti0_ss: {=u8:?}, exti1_ss: {=u8:?}, exti2_ss: {=u8:?}, exti3_ss: {=u8:?} }}" , self . exti0_ss () , self . exti1_ss () , self . exti2_ss () , self . exti3_ss ()) } } # [doc = "EXTI sources selection register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extiss1 (pub u32) ; impl Extiss1 { # [doc = "EXTI 4 sources selection"]
# [inline (always)]
pub const fn exti4_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "EXTI 4 sources selection"]
# [inline (always)]
pub fn set_exti4_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "EXTI 5 sources selection"]
# [inline (always)]
pub const fn exti5_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "EXTI 5 sources selection"]
# [inline (always)]
pub fn set_exti5_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "EXTI 6 sources selection"]
# [inline (always)]
pub const fn exti6_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "EXTI 6 sources selection"]
# [inline (always)]
pub fn set_exti6_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "EXTI 7 sources selection"]
# [inline (always)]
pub const fn exti7_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "EXTI 7 sources selection"]
# [inline (always)]
pub fn set_exti7_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Extiss1 { # [inline (always)]
fn default () -> Extiss1 { Extiss1 (0) } } impl core :: fmt :: Debug for Extiss1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extiss1") . field ("exti4_ss" , & self . exti4_ss ()) . field ("exti5_ss" , & self . exti5_ss ()) . field ("exti6_ss" , & self . exti6_ss ()) . field ("exti7_ss" , & self . exti7_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extiss1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extiss1 {{ exti4_ss: {=u8:?}, exti5_ss: {=u8:?}, exti6_ss: {=u8:?}, exti7_ss: {=u8:?} }}" , self . exti4_ss () , self . exti5_ss () , self . exti6_ss () , self . exti7_ss ()) } } # [doc = "EXTI sources selection register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extiss2 (pub u32) ; impl Extiss2 { # [doc = "EXTI 8 sources selection"]
# [inline (always)]
pub const fn exti8_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "EXTI 8 sources selection"]
# [inline (always)]
pub fn set_exti8_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "EXTI 9 sources selection"]
# [inline (always)]
pub const fn exti9_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "EXTI 9 sources selection"]
# [inline (always)]
pub fn set_exti9_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "EXTI 10 sources selection"]
# [inline (always)]
pub const fn exti10_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "EXTI 10 sources selection"]
# [inline (always)]
pub fn set_exti10_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "EXTI 11 sources selection"]
# [inline (always)]
pub const fn exti11_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "EXTI 11 sources selection"]
# [inline (always)]
pub fn set_exti11_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Extiss2 { # [inline (always)]
fn default () -> Extiss2 { Extiss2 (0) } } impl core :: fmt :: Debug for Extiss2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extiss2") . field ("exti8_ss" , & self . exti8_ss ()) . field ("exti9_ss" , & self . exti9_ss ()) . field ("exti10_ss" , & self . exti10_ss ()) . field ("exti11_ss" , & self . exti11_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extiss2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extiss2 {{ exti8_ss: {=u8:?}, exti9_ss: {=u8:?}, exti10_ss: {=u8:?}, exti11_ss: {=u8:?} }}" , self . exti8_ss () , self . exti9_ss () , self . exti10_ss () , self . exti11_ss ()) } } # [doc = "EXTI sources selection register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extiss3 (pub u32) ; impl Extiss3 { # [doc = "EXTI 12 sources selection"]
# [inline (always)]
pub const fn exti12_ss (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "EXTI 12 sources selection"]
# [inline (always)]
pub fn set_exti12_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "EXTI 13 sources selection"]
# [inline (always)]
pub const fn exti13_ss (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "EXTI 13 sources selection"]
# [inline (always)]
pub fn set_exti13_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "EXTI 14 sources selection"]
# [inline (always)]
pub const fn exti14_ss (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "EXTI 14 sources selection"]
# [inline (always)]
pub fn set_exti14_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "EXTI 15 sources selection"]
# [inline (always)]
pub const fn exti15_ss (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "EXTI 15 sources selection"]
# [inline (always)]
pub fn set_exti15_ss (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Extiss3 { # [inline (always)]
fn default () -> Extiss3 { Extiss3 (0) } } impl core :: fmt :: Debug for Extiss3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extiss3") . field ("exti12_ss" , & self . exti12_ss ()) . field ("exti13_ss" , & self . exti13_ss ()) . field ("exti14_ss" , & self . exti14_ss ()) . field ("exti15_ss" , & self . exti15_ss ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extiss3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extiss3 {{ exti12_ss: {=u8:?}, exti13_ss: {=u8:?}, exti14_ss: {=u8:?}, exti15_ss: {=u8:?} }}" , self . exti12_ss () , self . exti13_ss () , self . exti14_ss () , self . exti15_ss ()) } } # [doc = "System status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "SRAM multi-bits non-correction event flag"]
# [inline (always)]
pub const fn srameccmeif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "SRAM multi-bits non-correction event flag"]
# [inline (always)]
pub fn set_srameccmeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SRAM single bit correction event flag"]
# [inline (always)]
pub const fn srameccseif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SRAM single bit correction event flag"]
# [inline (always)]
pub fn set_srameccseif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Flash ECC interrupt flag"]
# [inline (always)]
pub const fn flasheccif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Flash ECC interrupt flag"]
# [inline (always)]
pub fn set_flasheccif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "HXTAL clock moniotor NMI interrupt flag"]
# [inline (always)]
pub const fn ckmnmiif (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "HXTAL clock moniotor NMI interrupt flag"]
# [inline (always)]
pub fn set_ckmnmiif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Interrupt flag from NMI pin"]
# [inline (always)]
pub const fn nmipinif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Interrupt flag from NMI pin"]
# [inline (always)]
pub fn set_nmipinif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } impl core :: fmt :: Debug for Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat") . field ("srameccmeif" , & self . srameccmeif ()) . field ("srameccseif" , & self . srameccseif ()) . field ("flasheccif" , & self . flasheccif ()) . field ("ckmnmiif" , & self . ckmnmiif ()) . field ("nmipinif" , & self . nmipinif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat {{ srameccmeif: {=bool:?}, srameccseif: {=bool:?}, flasheccif: {=bool:?}, ckmnmiif: {=bool:?}, nmipinif: {=bool:?} }}" , self . srameccmeif () , self . srameccseif () , self . flasheccif () , self . ckmnmiif () , self . nmipinif ()) } } # [doc = "TIMER input source select register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timerinsel (pub u32) ; impl Timerinsel { # [doc = "TIMER7 Channel 0 complementary input select"]
# [inline (always)]
pub const fn timer7_ch0n_sel (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "TIMER7 Channel 0 complementary input select"]
# [inline (always)]
pub fn set_timer7_ch0n_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "TIMER20 break input 3 select"]
# [inline (always)]
pub const fn timer20_brkin3_sel (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "TIMER20 break input 3 select"]
# [inline (always)]
pub fn set_timer20_brkin3_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "TIMER20 break input 2 select"]
# [inline (always)]
pub const fn timer20_brkin2_sel (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "TIMER20 break input 2 select"]
# [inline (always)]
pub fn set_timer20_brkin2_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "TIMER20 break input 1 select"]
# [inline (always)]
pub const fn timer20_brkin1_sel (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "TIMER20 break input 1 select"]
# [inline (always)]
pub fn set_timer20_brkin1_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "TIMER20 break input 0 select"]
# [inline (always)]
pub const fn timer20_brkin0_sel (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "TIMER20 break input 0 select"]
# [inline (always)]
pub fn set_timer20_brkin0_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "TIMER19 break input 3 select"]
# [inline (always)]
pub const fn timer19_brkin3_sel (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "TIMER19 break input 3 select"]
# [inline (always)]
pub fn set_timer19_brkin3_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "TIMER19 break input 2 select"]
# [inline (always)]
pub const fn timer19_brkin2_sel (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "TIMER19 break input 2 select"]
# [inline (always)]
pub fn set_timer19_brkin2_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "TIMER19 break input 1 select"]
# [inline (always)]
pub const fn timer19_brkin1_sel (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "TIMER19 break input 1 select"]
# [inline (always)]
pub fn set_timer19_brkin1_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "TIMER19 break input 0 select"]
# [inline (always)]
pub const fn timer19_brkin0_sel (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "TIMER19 break input 0 select"]
# [inline (always)]
pub fn set_timer19_brkin0_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "TIMER7 break input 3 select"]
# [inline (always)]
pub const fn timer7_brkin3_sel (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "TIMER7 break input 3 select"]
# [inline (always)]
pub fn set_timer7_brkin3_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "TIMER7 break input 2 select"]
# [inline (always)]
pub const fn timer7_brkin2_sel (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "TIMER7 break input 2 select"]
# [inline (always)]
pub fn set_timer7_brkin2_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "TIMER7 break input 1 select"]
# [inline (always)]
pub const fn timer7_brkin1_sel (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "TIMER7 break input 1 select"]
# [inline (always)]
pub fn set_timer7_brkin1_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TIMER7 break input 0 select"]
# [inline (always)]
pub const fn timer7_brkin0_sel (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "TIMER7 break input 0 select"]
# [inline (always)]
pub fn set_timer7_brkin0_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "TIMER0 break input 3 select"]
# [inline (always)]
pub const fn timer0_brkin3_sel (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "TIMER0 break input 3 select"]
# [inline (always)]
pub fn set_timer0_brkin3_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "TIMER0 break input 2 select"]
# [inline (always)]
pub const fn timer0_brkin2_sel (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "TIMER0 break input 2 select"]
# [inline (always)]
pub fn set_timer0_brkin2_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "TIMER0 break input 1 select"]
# [inline (always)]
pub const fn timer0_brkin1_sel (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "TIMER0 break input 1 select"]
# [inline (always)]
pub fn set_timer0_brkin1_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "TIMER0 break input 0 select"]
# [inline (always)]
pub const fn timer0_brkin0_sel (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "TIMER0 break input 0 select"]
# [inline (always)]
pub fn set_timer0_brkin0_sel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "TIMER20 external trigger select"]
# [inline (always)]
pub const fn timer20_eti_sel (& self) -> u8 { let val = (self . 0 >> 22usize) & 0x03 ; val as u8 } # [doc = "TIMER20 external trigger select"]
# [inline (always)]
pub fn set_timer20_eti_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 22usize)) | (((val as u32) & 0x03) << 22usize) ; } # [doc = "TIMER19 external trigger select"]
# [inline (always)]
pub const fn timer19_eti_sel (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x03 ; val as u8 } # [doc = "TIMER19 external trigger select"]
# [inline (always)]
pub fn set_timer19_eti_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 24usize)) | (((val as u32) & 0x03) << 24usize) ; } # [doc = "TIMER7 external trigger select"]
# [inline (always)]
pub const fn timer7_eti_sel (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x03 ; val as u8 } # [doc = "TIMER7 external trigger select"]
# [inline (always)]
pub fn set_timer7_eti_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 28usize)) | (((val as u32) & 0x03) << 28usize) ; } # [doc = "TIMER0 external trigger select"]
# [inline (always)]
pub const fn timer0_eti_sel (& self) -> u8 { let val = (self . 0 >> 30usize) & 0x03 ; val as u8 } # [doc = "TIMER0 external trigger select"]
# [inline (always)]
pub fn set_timer0_eti_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 30usize)) | (((val as u32) & 0x03) << 30usize) ; } } impl Default for Timerinsel { # [inline (always)]
fn default () -> Timerinsel { Timerinsel (0) } } impl core :: fmt :: Debug for Timerinsel { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timerinsel") . field ("timer7_ch0n_sel" , & self . timer7_ch0n_sel ()) . field ("timer20_brkin3_sel" , & self . timer20_brkin3_sel ()) . field ("timer20_brkin2_sel" , & self . timer20_brkin2_sel ()) . field ("timer20_brkin1_sel" , & self . timer20_brkin1_sel ()) . field ("timer20_brkin0_sel" , & self . timer20_brkin0_sel ()) . field ("timer19_brkin3_sel" , & self . timer19_brkin3_sel ()) . field ("timer19_brkin2_sel" , & self . timer19_brkin2_sel ()) . field ("timer19_brkin1_sel" , & self . timer19_brkin1_sel ()) . field ("timer19_brkin0_sel" , & self . timer19_brkin0_sel ()) . field ("timer7_brkin3_sel" , & self . timer7_brkin3_sel ()) . field ("timer7_brkin2_sel" , & self . timer7_brkin2_sel ()) . field ("timer7_brkin1_sel" , & self . timer7_brkin1_sel ()) . field ("timer7_brkin0_sel" , & self . timer7_brkin0_sel ()) . field ("timer0_brkin3_sel" , & self . timer0_brkin3_sel ()) . field ("timer0_brkin2_sel" , & self . timer0_brkin2_sel ()) . field ("timer0_brkin1_sel" , & self . timer0_brkin1_sel ()) . field ("timer0_brkin0_sel" , & self . timer0_brkin0_sel ()) . field ("timer20_eti_sel" , & self . timer20_eti_sel ()) . field ("timer19_eti_sel" , & self . timer19_eti_sel ()) . field ("timer7_eti_sel" , & self . timer7_eti_sel ()) . field ("timer0_eti_sel" , & self . timer0_eti_sel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timerinsel { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timerinsel {{ timer7_ch0n_sel: {=bool:?}, timer20_brkin3_sel: {=bool:?}, timer20_brkin2_sel: {=bool:?}, timer20_brkin1_sel: {=bool:?}, timer20_brkin0_sel: {=bool:?}, timer19_brkin3_sel: {=bool:?}, timer19_brkin2_sel: {=bool:?}, timer19_brkin1_sel: {=bool:?}, timer19_brkin0_sel: {=bool:?}, timer7_brkin3_sel: {=bool:?}, timer7_brkin2_sel: {=bool:?}, timer7_brkin1_sel: {=bool:?}, timer7_brkin0_sel: {=bool:?}, timer0_brkin3_sel: {=bool:?}, timer0_brkin2_sel: {=bool:?}, timer0_brkin1_sel: {=bool:?}, timer0_brkin0_sel: {=bool:?}, timer20_eti_sel: {=u8:?}, timer19_eti_sel: {=u8:?}, timer7_eti_sel: {=u8:?}, timer0_eti_sel: {=u8:?} }}" , self . timer7_ch0n_sel () , self . timer20_brkin3_sel () , self . timer20_brkin2_sel () , self . timer20_brkin1_sel () , self . timer20_brkin0_sel () , self . timer19_brkin3_sel () , self . timer19_brkin2_sel () , self . timer19_brkin1_sel () , self . timer19_brkin0_sel () , self . timer7_brkin3_sel () , self . timer7_brkin2_sel () , self . timer7_brkin1_sel () , self . timer7_brkin0_sel () , self . timer0_brkin3_sel () , self . timer0_brkin2_sel () , self . timer0_brkin1_sel () , self . timer0_brkin0_sel () , self . timer20_eti_sel () , self . timer19_eti_sel () , self . timer7_eti_sel () , self . timer0_eti_sel ()) } } }