#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Syscfg { ptr : * mut u8 } unsafe impl Send for Syscfg { } unsafe impl Sync for Syscfg { } impl Syscfg { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn syscfg_cfg0 (self) -> crate :: common :: Reg < regs :: SyscfgCfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn syscfg_cfg1 (self) -> crate :: common :: Reg < regs :: SyscfgCfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn syscfg_lkctl (self) -> crate :: common :: Reg < regs :: SyscfgLkctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn syscfg_busto (self) -> crate :: common :: Reg < regs :: SyscfgBusto , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x1cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercisel (self) -> crate :: common :: Reg < regs :: SyscfgTimercisel , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn syscfg_fpuinten (self) -> crate :: common :: Reg < regs :: SyscfgFpuinten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn syscfg_sramwp (self) -> crate :: common :: Reg < regs :: SyscfgSramwp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn syscfg_srameccstat (self) -> crate :: common :: Reg < regs :: SyscfgSrameccstat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x2cusize) as _) } } # [inline (always)]
pub const fn syscfg_sramecccs (self) -> crate :: common :: Reg < regs :: SyscfgSramecccs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn syscfg_bustostat (self) -> crate :: common :: Reg < regs :: SyscfgBustostat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn syscfg_timer0trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0100usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0100usize) as _) } } # [inline (always)]
pub const fn syscfg_timer0trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0104usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0104usize) as _) } } # [inline (always)]
pub const fn syscfg_timer0trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0108usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0108usize) as _) } } # [inline (always)]
pub const fn syscfg_timer1trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x010cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x010cusize) as _) } } # [inline (always)]
pub const fn syscfg_timer1trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0110usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0110usize) as _) } } # [inline (always)]
pub const fn syscfg_timer1trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0114usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0114usize) as _) } } # [inline (always)]
pub const fn syscfg_timer2trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0118usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0118usize) as _) } } # [inline (always)]
pub const fn syscfg_timer2trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x011cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x011cusize) as _) } } # [inline (always)]
pub const fn syscfg_timer2trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0120usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0120usize) as _) } } # [inline (always)]
pub const fn syscfg_timer3trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0124usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0124usize) as _) } } # [inline (always)]
pub const fn syscfg_timer3trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0128usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0128usize) as _) } } # [inline (always)]
pub const fn syscfg_timer3trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x012cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x012cusize) as _) } } # [inline (always)]
pub const fn syscfg_timer4trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0130usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0130usize) as _) } } # [inline (always)]
pub const fn syscfg_timer4trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0134usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0134usize) as _) } } # [inline (always)]
pub const fn syscfg_timer4trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0138usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_4 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0138usize) as _) } } # [inline (always)]
pub const fn syscfg_timer7trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x013cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x013cusize) as _) } } # [inline (always)]
pub const fn syscfg_timer7trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0140usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0140usize) as _) } } # [inline (always)]
pub const fn syscfg_timer7trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0144usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_5 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0144usize) as _) } } # [inline (always)]
pub const fn syscfg_timer15trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0148usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0148usize) as _) } } # [inline (always)]
pub const fn syscfg_timer15trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x014cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x014cusize) as _) } } # [inline (always)]
pub const fn syscfg_timer15trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0150usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_6 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0150usize) as _) } } # [inline (always)]
pub const fn syscfg_timer16trgcfg0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0154usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg0_7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0154usize) as _) } } # [inline (always)]
pub const fn syscfg_timer16trgcfg1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0158usize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg1_7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0158usize) as _) } } # [inline (always)]
pub const fn syscfg_timer16trgcfg2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x015cusize) as _) } } # [inline (always)]
pub const fn syscfg_timercfg2_7 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x015cusize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgBusto (pub u32) ; impl SyscfgBusto { # [must_use]
# [inline (always)]
pub const fn syscfg_busto_cpucbusto (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_busto_cpucbusto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_busto_cpusbusto (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_busto_cpusbusto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_busto_dma0busto (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_busto_dma0busto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_busto_dma1busto (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_busto_dma1busto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for SyscfgBusto { # [inline (always)]
fn default () -> SyscfgBusto { SyscfgBusto (0) } } impl core :: fmt :: Debug for SyscfgBusto { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgBusto") . field ("syscfg_busto_cpucbusto" , & self . syscfg_busto_cpucbusto ()) . field ("syscfg_busto_cpusbusto" , & self . syscfg_busto_cpusbusto ()) . field ("syscfg_busto_dma0busto" , & self . syscfg_busto_dma0busto ()) . field ("syscfg_busto_dma1busto" , & self . syscfg_busto_dma1busto ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgBusto { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgBusto {{ syscfg_busto_cpucbusto: {=bool:?}, syscfg_busto_cpusbusto: {=bool:?}, syscfg_busto_dma0busto: {=bool:?}, syscfg_busto_dma1busto: {=bool:?} }}" , self . syscfg_busto_cpucbusto () , self . syscfg_busto_cpusbusto () , self . syscfg_busto_dma0busto () , self . syscfg_busto_dma1busto ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgBustostat (pub u32) ; impl SyscfgBustostat { # [must_use]
# [inline (always)]
pub const fn syscfg_bustostat_cpucbustof (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_bustostat_cpucbustof (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_bustostat_cpusbustof (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_bustostat_cpusbustof (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_bustostat_dma0bustof (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_bustostat_dma0bustof (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_bustostat_dma1bustof (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_bustostat_dma1bustof (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for SyscfgBustostat { # [inline (always)]
fn default () -> SyscfgBustostat { SyscfgBustostat (0) } } impl core :: fmt :: Debug for SyscfgBustostat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgBustostat") . field ("syscfg_bustostat_cpucbustof" , & self . syscfg_bustostat_cpucbustof ()) . field ("syscfg_bustostat_cpusbustof" , & self . syscfg_bustostat_cpusbustof ()) . field ("syscfg_bustostat_dma0bustof" , & self . syscfg_bustostat_dma0bustof ()) . field ("syscfg_bustostat_dma1bustof" , & self . syscfg_bustostat_dma1bustof ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgBustostat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgBustostat {{ syscfg_bustostat_cpucbustof: {=bool:?}, syscfg_bustostat_cpusbustof: {=bool:?}, syscfg_bustostat_dma0bustof: {=bool:?}, syscfg_bustostat_dma1bustof: {=bool:?} }}" , self . syscfg_bustostat_cpucbustof () , self . syscfg_bustostat_cpusbustof () , self . syscfg_bustostat_dma0bustof () , self . syscfg_bustostat_dma1bustof ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg0 (pub u32) ; impl SyscfgCfg0 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg0_boot_mode (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_syscfg_cfg0_boot_mode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } } impl Default for SyscfgCfg0 { # [inline (always)]
fn default () -> SyscfgCfg0 { SyscfgCfg0 (0) } } impl core :: fmt :: Debug for SyscfgCfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg0") . field ("syscfg_cfg0_boot_mode" , & self . syscfg_cfg0_boot_mode ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg0 {{ syscfg_cfg0_boot_mode: {=u8:?} }}" , self . syscfg_cfg0_boot_mode ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgCfg1 (pub u32) ; impl SyscfgCfg1 { # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_i2c0fmp (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_i2c0fmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_cfg1_i2c1fmp (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_cfg1_i2c1fmp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for SyscfgCfg1 { # [inline (always)]
fn default () -> SyscfgCfg1 { SyscfgCfg1 (0) } } impl core :: fmt :: Debug for SyscfgCfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgCfg1") . field ("syscfg_cfg1_i2c0fmp" , & self . syscfg_cfg1_i2c0fmp ()) . field ("syscfg_cfg1_i2c1fmp" , & self . syscfg_cfg1_i2c1fmp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgCfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgCfg1 {{ syscfg_cfg1_i2c0fmp: {=bool:?}, syscfg_cfg1_i2c1fmp: {=bool:?} }}" , self . syscfg_cfg1_i2c0fmp () , self . syscfg_cfg1_i2c1fmp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgFpuinten (pub u32) ; impl SyscfgFpuinten { # [must_use]
# [inline (always)]
pub const fn syscfg_fpuinten_iopie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_fpuinten_iopie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_fpuinten_dzie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_fpuinten_dzie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_fpuinten_ufie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_fpuinten_ufie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_fpuinten_ovfie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_fpuinten_ovfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_fpuinten_iaie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_fpuinten_iaie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_fpuinten_ixie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_fpuinten_ixie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for SyscfgFpuinten { # [inline (always)]
fn default () -> SyscfgFpuinten { SyscfgFpuinten (0) } } impl core :: fmt :: Debug for SyscfgFpuinten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgFpuinten") . field ("syscfg_fpuinten_iopie" , & self . syscfg_fpuinten_iopie ()) . field ("syscfg_fpuinten_dzie" , & self . syscfg_fpuinten_dzie ()) . field ("syscfg_fpuinten_ufie" , & self . syscfg_fpuinten_ufie ()) . field ("syscfg_fpuinten_ovfie" , & self . syscfg_fpuinten_ovfie ()) . field ("syscfg_fpuinten_iaie" , & self . syscfg_fpuinten_iaie ()) . field ("syscfg_fpuinten_ixie" , & self . syscfg_fpuinten_ixie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgFpuinten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgFpuinten {{ syscfg_fpuinten_iopie: {=bool:?}, syscfg_fpuinten_dzie: {=bool:?}, syscfg_fpuinten_ufie: {=bool:?}, syscfg_fpuinten_ovfie: {=bool:?}, syscfg_fpuinten_iaie: {=bool:?}, syscfg_fpuinten_ixie: {=bool:?} }}" , self . syscfg_fpuinten_iopie () , self . syscfg_fpuinten_dzie () , self . syscfg_fpuinten_ufie () , self . syscfg_fpuinten_ovfie () , self . syscfg_fpuinten_iaie () , self . syscfg_fpuinten_ixie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgLkctl (pub u32) ; impl SyscfgLkctl { # [must_use]
# [inline (always)]
pub const fn syscfg_lkctl_lvd_lock (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_lkctl_lvd_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_lkctl_cpu_lock (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_lkctl_cpu_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_lkctl_sram_lock (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_lkctl_sram_lock (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for SyscfgLkctl { # [inline (always)]
fn default () -> SyscfgLkctl { SyscfgLkctl (0) } } impl core :: fmt :: Debug for SyscfgLkctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgLkctl") . field ("syscfg_lkctl_lvd_lock" , & self . syscfg_lkctl_lvd_lock ()) . field ("syscfg_lkctl_cpu_lock" , & self . syscfg_lkctl_cpu_lock ()) . field ("syscfg_lkctl_sram_lock" , & self . syscfg_lkctl_sram_lock ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgLkctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgLkctl {{ syscfg_lkctl_lvd_lock: {=bool:?}, syscfg_lkctl_cpu_lock: {=bool:?}, syscfg_lkctl_sram_lock: {=bool:?} }}" , self . syscfg_lkctl_lvd_lock () , self . syscfg_lkctl_cpu_lock () , self . syscfg_lkctl_sram_lock ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgSramecccs (pub u32) ; impl SyscfgSramecccs { # [must_use]
# [inline (always)]
pub const fn syscfg_sramecccs_srameccmeie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramecccs_srameccmeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramecccs_srameccseie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramecccs_srameccseie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramecccs_srameccserrbits (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x3f ; val as u8 } # [inline (always)]
pub const fn set_syscfg_sramecccs_srameccserrbits (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 10usize)) | (((val as u32) & 0x3f) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramecccs_srameccaddr (& self) -> u16 { let val = (self . 0 >> 19usize) & 0x1fff ; val as u16 } # [inline (always)]
pub const fn set_syscfg_sramecccs_srameccaddr (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x1fff << 19usize)) | (((val as u32) & 0x1fff) << 19usize) ; } } impl Default for SyscfgSramecccs { # [inline (always)]
fn default () -> SyscfgSramecccs { SyscfgSramecccs (0) } } impl core :: fmt :: Debug for SyscfgSramecccs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgSramecccs") . field ("syscfg_sramecccs_srameccmeie" , & self . syscfg_sramecccs_srameccmeie ()) . field ("syscfg_sramecccs_srameccseie" , & self . syscfg_sramecccs_srameccseie ()) . field ("syscfg_sramecccs_srameccserrbits" , & self . syscfg_sramecccs_srameccserrbits ()) . field ("syscfg_sramecccs_srameccaddr" , & self . syscfg_sramecccs_srameccaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgSramecccs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgSramecccs {{ syscfg_sramecccs_srameccmeie: {=bool:?}, syscfg_sramecccs_srameccseie: {=bool:?}, syscfg_sramecccs_srameccserrbits: {=u8:?}, syscfg_sramecccs_srameccaddr: {=u16:?} }}" , self . syscfg_sramecccs_srameccmeie () , self . syscfg_sramecccs_srameccseie () , self . syscfg_sramecccs_srameccserrbits () , self . syscfg_sramecccs_srameccaddr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgSrameccstat (pub u32) ; impl SyscfgSrameccstat { # [must_use]
# [inline (always)]
pub const fn syscfg_srameccstat_srameccmeif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_srameccstat_srameccmeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_srameccstat_srameccseif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_srameccstat_srameccseif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for SyscfgSrameccstat { # [inline (always)]
fn default () -> SyscfgSrameccstat { SyscfgSrameccstat (0) } } impl core :: fmt :: Debug for SyscfgSrameccstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgSrameccstat") . field ("syscfg_srameccstat_srameccmeif" , & self . syscfg_srameccstat_srameccmeif ()) . field ("syscfg_srameccstat_srameccseif" , & self . syscfg_srameccstat_srameccseif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgSrameccstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgSrameccstat {{ syscfg_srameccstat_srameccmeif: {=bool:?}, syscfg_srameccstat_srameccseif: {=bool:?} }}" , self . syscfg_srameccstat_srameccmeif () , self . syscfg_srameccstat_srameccseif ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgSramwp (pub u32) ; impl SyscfgSramwp { # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p0wp (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p0wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p1wp (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p1wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p2wp (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p2wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p3wp (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p3wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p4wp (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p4wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p5wp (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p5wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p6wp (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p6wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p7wp (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p7wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p8wp (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p8wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p9wp (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p9wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p10wp (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p10wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p11wp (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p11wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p12wp (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p12wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p13wp (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p13wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p14wp (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p14wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p15wp (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p15wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p16wp (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p16wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p17wp (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p17wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p18wp (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p18wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p19wp (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p19wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p20wp (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p20wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p21wp (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p21wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p22wp (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p22wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p23wp (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p23wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p24wp (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p24wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p25wp (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p25wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p26wp (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p26wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p27wp (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p27wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p28wp (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p28wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p29wp (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p29wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p30wp (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p30wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_sramwp_sram_p31wp (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_syscfg_sramwp_sram_p31wp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for SyscfgSramwp { # [inline (always)]
fn default () -> SyscfgSramwp { SyscfgSramwp (0) } } impl core :: fmt :: Debug for SyscfgSramwp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgSramwp") . field ("syscfg_sramwp_sram_p0wp" , & self . syscfg_sramwp_sram_p0wp ()) . field ("syscfg_sramwp_sram_p1wp" , & self . syscfg_sramwp_sram_p1wp ()) . field ("syscfg_sramwp_sram_p2wp" , & self . syscfg_sramwp_sram_p2wp ()) . field ("syscfg_sramwp_sram_p3wp" , & self . syscfg_sramwp_sram_p3wp ()) . field ("syscfg_sramwp_sram_p4wp" , & self . syscfg_sramwp_sram_p4wp ()) . field ("syscfg_sramwp_sram_p5wp" , & self . syscfg_sramwp_sram_p5wp ()) . field ("syscfg_sramwp_sram_p6wp" , & self . syscfg_sramwp_sram_p6wp ()) . field ("syscfg_sramwp_sram_p7wp" , & self . syscfg_sramwp_sram_p7wp ()) . field ("syscfg_sramwp_sram_p8wp" , & self . syscfg_sramwp_sram_p8wp ()) . field ("syscfg_sramwp_sram_p9wp" , & self . syscfg_sramwp_sram_p9wp ()) . field ("syscfg_sramwp_sram_p10wp" , & self . syscfg_sramwp_sram_p10wp ()) . field ("syscfg_sramwp_sram_p11wp" , & self . syscfg_sramwp_sram_p11wp ()) . field ("syscfg_sramwp_sram_p12wp" , & self . syscfg_sramwp_sram_p12wp ()) . field ("syscfg_sramwp_sram_p13wp" , & self . syscfg_sramwp_sram_p13wp ()) . field ("syscfg_sramwp_sram_p14wp" , & self . syscfg_sramwp_sram_p14wp ()) . field ("syscfg_sramwp_sram_p15wp" , & self . syscfg_sramwp_sram_p15wp ()) . field ("syscfg_sramwp_sram_p16wp" , & self . syscfg_sramwp_sram_p16wp ()) . field ("syscfg_sramwp_sram_p17wp" , & self . syscfg_sramwp_sram_p17wp ()) . field ("syscfg_sramwp_sram_p18wp" , & self . syscfg_sramwp_sram_p18wp ()) . field ("syscfg_sramwp_sram_p19wp" , & self . syscfg_sramwp_sram_p19wp ()) . field ("syscfg_sramwp_sram_p20wp" , & self . syscfg_sramwp_sram_p20wp ()) . field ("syscfg_sramwp_sram_p21wp" , & self . syscfg_sramwp_sram_p21wp ()) . field ("syscfg_sramwp_sram_p22wp" , & self . syscfg_sramwp_sram_p22wp ()) . field ("syscfg_sramwp_sram_p23wp" , & self . syscfg_sramwp_sram_p23wp ()) . field ("syscfg_sramwp_sram_p24wp" , & self . syscfg_sramwp_sram_p24wp ()) . field ("syscfg_sramwp_sram_p25wp" , & self . syscfg_sramwp_sram_p25wp ()) . field ("syscfg_sramwp_sram_p26wp" , & self . syscfg_sramwp_sram_p26wp ()) . field ("syscfg_sramwp_sram_p27wp" , & self . syscfg_sramwp_sram_p27wp ()) . field ("syscfg_sramwp_sram_p28wp" , & self . syscfg_sramwp_sram_p28wp ()) . field ("syscfg_sramwp_sram_p29wp" , & self . syscfg_sramwp_sram_p29wp ()) . field ("syscfg_sramwp_sram_p30wp" , & self . syscfg_sramwp_sram_p30wp ()) . field ("syscfg_sramwp_sram_p31wp" , & self . syscfg_sramwp_sram_p31wp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgSramwp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgSramwp {{ syscfg_sramwp_sram_p0wp: {=bool:?}, syscfg_sramwp_sram_p1wp: {=bool:?}, syscfg_sramwp_sram_p2wp: {=bool:?}, syscfg_sramwp_sram_p3wp: {=bool:?}, syscfg_sramwp_sram_p4wp: {=bool:?}, syscfg_sramwp_sram_p5wp: {=bool:?}, syscfg_sramwp_sram_p6wp: {=bool:?}, syscfg_sramwp_sram_p7wp: {=bool:?}, syscfg_sramwp_sram_p8wp: {=bool:?}, syscfg_sramwp_sram_p9wp: {=bool:?}, syscfg_sramwp_sram_p10wp: {=bool:?}, syscfg_sramwp_sram_p11wp: {=bool:?}, syscfg_sramwp_sram_p12wp: {=bool:?}, syscfg_sramwp_sram_p13wp: {=bool:?}, syscfg_sramwp_sram_p14wp: {=bool:?}, syscfg_sramwp_sram_p15wp: {=bool:?}, syscfg_sramwp_sram_p16wp: {=bool:?}, syscfg_sramwp_sram_p17wp: {=bool:?}, syscfg_sramwp_sram_p18wp: {=bool:?}, syscfg_sramwp_sram_p19wp: {=bool:?}, syscfg_sramwp_sram_p20wp: {=bool:?}, syscfg_sramwp_sram_p21wp: {=bool:?}, syscfg_sramwp_sram_p22wp: {=bool:?}, syscfg_sramwp_sram_p23wp: {=bool:?}, syscfg_sramwp_sram_p24wp: {=bool:?}, syscfg_sramwp_sram_p25wp: {=bool:?}, syscfg_sramwp_sram_p26wp: {=bool:?}, syscfg_sramwp_sram_p27wp: {=bool:?}, syscfg_sramwp_sram_p28wp: {=bool:?}, syscfg_sramwp_sram_p29wp: {=bool:?}, syscfg_sramwp_sram_p30wp: {=bool:?}, syscfg_sramwp_sram_p31wp: {=bool:?} }}" , self . syscfg_sramwp_sram_p0wp () , self . syscfg_sramwp_sram_p1wp () , self . syscfg_sramwp_sram_p2wp () , self . syscfg_sramwp_sram_p3wp () , self . syscfg_sramwp_sram_p4wp () , self . syscfg_sramwp_sram_p5wp () , self . syscfg_sramwp_sram_p6wp () , self . syscfg_sramwp_sram_p7wp () , self . syscfg_sramwp_sram_p8wp () , self . syscfg_sramwp_sram_p9wp () , self . syscfg_sramwp_sram_p10wp () , self . syscfg_sramwp_sram_p11wp () , self . syscfg_sramwp_sram_p12wp () , self . syscfg_sramwp_sram_p13wp () , self . syscfg_sramwp_sram_p14wp () , self . syscfg_sramwp_sram_p15wp () , self . syscfg_sramwp_sram_p16wp () , self . syscfg_sramwp_sram_p17wp () , self . syscfg_sramwp_sram_p18wp () , self . syscfg_sramwp_sram_p19wp () , self . syscfg_sramwp_sram_p20wp () , self . syscfg_sramwp_sram_p21wp () , self . syscfg_sramwp_sram_p22wp () , self . syscfg_sramwp_sram_p23wp () , self . syscfg_sramwp_sram_p24wp () , self . syscfg_sramwp_sram_p25wp () , self . syscfg_sramwp_sram_p26wp () , self . syscfg_sramwp_sram_p27wp () , self . syscfg_sramwp_sram_p28wp () , self . syscfg_sramwp_sram_p29wp () , self . syscfg_sramwp_sram_p30wp () , self . syscfg_sramwp_sram_p31wp ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct SyscfgTimercisel (pub u32) ; impl SyscfgTimercisel { # [must_use]
# [inline (always)]
pub const fn syscfg_timercisel_timer15_ci0_sel (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_syscfg_timercisel_timer15_ci0_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn syscfg_timercisel_timer16_ci0_sel (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_syscfg_timercisel_timer16_ci0_sel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } } impl Default for SyscfgTimercisel { # [inline (always)]
fn default () -> SyscfgTimercisel { SyscfgTimercisel (0) } } impl core :: fmt :: Debug for SyscfgTimercisel { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("SyscfgTimercisel") . field ("syscfg_timercisel_timer15_ci0_sel" , & self . syscfg_timercisel_timer15_ci0_sel ()) . field ("syscfg_timercisel_timer16_ci0_sel" , & self . syscfg_timercisel_timer16_ci0_sel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for SyscfgTimercisel { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "SyscfgTimercisel {{ syscfg_timercisel_timer15_ci0_sel: {=u8:?}, syscfg_timercisel_timer16_ci0_sel: {=u8:?} }}" , self . syscfg_timercisel_timer15_ci0_sel () , self . syscfg_timercisel_timer16_ci0_sel ()) } } }