#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Basic-timers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer5 { ptr : * mut u8 } unsafe impl Send for Timer5 { } unsafe impl Sync for Timer5 { } impl Timer5 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "DMA/Interrupt enable register"]
# [inline (always)]
pub const fn dmainten (self) -> crate :: common :: Reg < regs :: Dmainten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "status register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Software event generation register"]
# [inline (always)]
pub const fn swevg (self) -> crate :: common :: Reg < regs :: Swevg , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Counter register"]
# [inline (always)]
pub const fn cnt (self) -> crate :: common :: Reg < regs :: Cnt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Prescaler register"]
# [inline (always)]
pub const fn psc (self) -> crate :: common :: Reg < regs :: Psc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Counter auto reload register"]
# [inline (always)]
pub const fn car (self) -> crate :: common :: Reg < regs :: Car , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } } pub mod regs { # [doc = "Counter auto reload register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Car (pub u32) ; impl Car { # [doc = "Counter auto reload value"]
# [inline (always)]
pub const fn carl (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Counter auto reload value"]
# [inline (always)]
pub fn set_carl (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Car { # [inline (always)]
fn default () -> Car { Car (0) } } impl core :: fmt :: Debug for Car { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Car") . field ("carl" , & self . carl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Car { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Car {{ carl: {=u16:?} }}" , self . carl ()) } } # [doc = "Counter register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cnt (pub u32) ; impl Cnt { # [doc = "current counter value"]
# [inline (always)]
pub const fn cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "current counter value"]
# [inline (always)]
pub fn set_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Cnt { # [inline (always)]
fn default () -> Cnt { Cnt (0) } } impl core :: fmt :: Debug for Cnt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cnt") . field ("cnt" , & self . cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cnt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cnt {{ cnt: {=u16:?} }}" , self . cnt ()) } } # [doc = "control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Counter enable"]
# [inline (always)]
pub const fn cen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Counter enable"]
# [inline (always)]
pub fn set_cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Update disable"]
# [inline (always)]
pub const fn updis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Update disable"]
# [inline (always)]
pub fn set_updis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Update source"]
# [inline (always)]
pub const fn ups (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Update source"]
# [inline (always)]
pub fn set_ups (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Single pulse mode"]
# [inline (always)]
pub const fn spm (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Single pulse mode"]
# [inline (always)]
pub fn set_spm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Auto-reload shadow enable"]
# [inline (always)]
pub const fn arse (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Auto-reload shadow enable"]
# [inline (always)]
pub fn set_arse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("cen" , & self . cen ()) . field ("updis" , & self . updis ()) . field ("ups" , & self . ups ()) . field ("spm" , & self . spm ()) . field ("arse" , & self . arse ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ cen: {=bool:?}, updis: {=bool:?}, ups: {=bool:?}, spm: {=bool:?}, arse: {=bool:?} }}" , self . cen () , self . updis () , self . ups () , self . spm () , self . arse ()) } } # [doc = "control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Master mode control"]
# [inline (always)]
pub const fn mmc (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Master mode control"]
# [inline (always)]
pub fn set_mmc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("mmc" , & self . mmc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ mmc: {=u8:?} }}" , self . mmc ()) } } # [doc = "DMA/Interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmainten (pub u32) ; impl Dmainten { # [doc = "Update interrupt enable"]
# [inline (always)]
pub const fn upie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt enable"]
# [inline (always)]
pub fn set_upie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Update DMA request enable"]
# [inline (always)]
pub const fn upden (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Update DMA request enable"]
# [inline (always)]
pub fn set_upden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for Dmainten { # [inline (always)]
fn default () -> Dmainten { Dmainten (0) } } impl core :: fmt :: Debug for Dmainten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmainten") . field ("upie" , & self . upie ()) . field ("upden" , & self . upden ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmainten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmainten {{ upie: {=bool:?}, upden: {=bool:?} }}" , self . upie () , self . upden ()) } } # [doc = "status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "Update interrupt flag"]
# [inline (always)]
pub const fn upif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt flag"]
# [inline (always)]
pub fn set_upif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("upif" , & self . upif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ upif: {=bool:?} }}" , self . upif ()) } } # [doc = "Prescaler register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Psc (pub u32) ; impl Psc { # [doc = "Prescaler value of the counter clock"]
# [inline (always)]
pub const fn psc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Prescaler value of the counter clock"]
# [inline (always)]
pub fn set_psc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Psc { # [inline (always)]
fn default () -> Psc { Psc (0) } } impl core :: fmt :: Debug for Psc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Psc") . field ("psc" , & self . psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Psc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Psc {{ psc: {=u16:?} }}" , self . psc ()) } } # [doc = "Software event generation register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Swevg (pub u32) ; impl Swevg { # [doc = "Update generation"]
# [inline (always)]
pub const fn upg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update generation"]
# [inline (always)]
pub fn set_upg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for Swevg { # [inline (always)]
fn default () -> Swevg { Swevg (0) } } impl core :: fmt :: Debug for Swevg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Swevg") . field ("upg" , & self . upg ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Swevg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Swevg {{ upg: {=bool:?} }}" , self . upg ()) } } }