#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "General level1 timer"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer8 { ptr : * mut u8 } unsafe impl Send for Timer8 { } unsafe impl Sync for Timer8 { } impl Timer8 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Slave mode configuration register"]
# [inline (always)]
pub const fn smcfg (self) -> crate :: common :: Reg < regs :: Smcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Interrupt enable register"]
# [inline (always)]
pub const fn dmainten (self) -> crate :: common :: Reg < regs :: Dmainten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Interrupt flag register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Software event generation register"]
# [inline (always)]
pub const fn swevg (self) -> crate :: common :: Reg < regs :: Swevg , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Channel control register 2"]
# [inline (always)]
pub const fn chctl2 (self) -> crate :: common :: Reg < regs :: Chctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Counter register"]
# [inline (always)]
pub const fn cnt (self) -> crate :: common :: Reg < regs :: Cnt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Prescaler register"]
# [inline (always)]
pub const fn psc (self) -> crate :: common :: Reg < regs :: Psc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Counter auto reload register"]
# [inline (always)]
pub const fn car (self) -> crate :: common :: Reg < regs :: Car , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Channel 0 capture/compare value register"]
# [inline (always)]
pub const fn ch0cv (self) -> crate :: common :: Reg < regs :: Ch0cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "Channel 1 capture/compare value register"]
# [inline (always)]
pub const fn ch1cv (self) -> crate :: common :: Reg < regs :: Ch1cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Configuration register"]
# [inline (always)]
pub const fn cfg (self) -> crate :: common :: Reg < regs :: Cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xfcusize) as _) } } } pub mod regs { # [doc = "Counter auto reload register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Car (pub u32) ; impl Car { # [doc = "Counter auto reload value"]
# [inline (always)]
pub const fn carl (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Counter auto reload value"]
# [inline (always)]
pub fn set_carl (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Car { # [inline (always)]
fn default () -> Car { Car (0) } } impl core :: fmt :: Debug for Car { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Car") . field ("carl" , & self . carl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Car { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Car {{ carl: {=u16:?} }}" , self . carl ()) } } # [doc = "Configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg (pub u32) ; impl Cfg { # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub const fn chvsel (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub fn set_chvsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Cfg { # [inline (always)]
fn default () -> Cfg { Cfg (0) } } impl core :: fmt :: Debug for Cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg") . field ("chvsel" , & self . chvsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg {{ chvsel: {=bool:?} }}" , self . chvsel ()) } } # [doc = "Channel 0 capture/compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch0cv (pub u32) ; impl Ch0cv { # [doc = "Capture or compare value of channel0"]
# [inline (always)]
pub const fn ch0val (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Capture or compare value of channel0"]
# [inline (always)]
pub fn set_ch0val (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Ch0cv { # [inline (always)]
fn default () -> Ch0cv { Ch0cv (0) } } impl core :: fmt :: Debug for Ch0cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch0cv") . field ("ch0val" , & self . ch0val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch0cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch0cv {{ ch0val: {=u16:?} }}" , self . ch0val ()) } } # [doc = "Channel 1 capture/compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch1cv (pub u32) ; impl Ch1cv { # [doc = "Capture or compare value of channel1"]
# [inline (always)]
pub const fn ch1val (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Capture or compare value of channel1"]
# [inline (always)]
pub fn set_ch1val (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Ch1cv { # [inline (always)]
fn default () -> Ch1cv { Ch1cv (0) } } impl core :: fmt :: Debug for Ch1cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch1cv") . field ("ch1val" , & self . ch1val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch1cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch1cv {{ ch1val: {=u16:?} }}" , self . ch1val ()) } } # [doc = "Channel control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl2 (pub u32) ; impl Chctl2 { # [doc = "Channel 0 capture/compare function enable"]
# [inline (always)]
pub const fn ch0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare function enable"]
# [inline (always)]
pub fn set_ch0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture/compare function polarity"]
# [inline (always)]
pub const fn ch0p (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare function polarity"]
# [inline (always)]
pub fn set_ch0p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 0 complementary output polarity"]
# [inline (always)]
pub const fn ch0np (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 0 complementary output polarity"]
# [inline (always)]
pub fn set_ch0np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 1 capture/compare function enable"]
# [inline (always)]
pub const fn ch1en (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare function enable"]
# [inline (always)]
pub fn set_ch1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Channel 1 capture/compare function polarity"]
# [inline (always)]
pub const fn ch1p (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare function polarity"]
# [inline (always)]
pub fn set_ch1p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Channel 1 complementary output polarity"]
# [inline (always)]
pub const fn ch1np (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Channel 1 complementary output polarity"]
# [inline (always)]
pub fn set_ch1np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Chctl2 { # [inline (always)]
fn default () -> Chctl2 { Chctl2 (0) } } impl core :: fmt :: Debug for Chctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl2") . field ("ch0en" , & self . ch0en ()) . field ("ch0p" , & self . ch0p ()) . field ("ch0np" , & self . ch0np ()) . field ("ch1en" , & self . ch1en ()) . field ("ch1p" , & self . ch1p ()) . field ("ch1np" , & self . ch1np ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl2 {{ ch0en: {=bool:?}, ch0p: {=bool:?}, ch0np: {=bool:?}, ch1en: {=bool:?}, ch1p: {=bool:?}, ch1np: {=bool:?} }}" , self . ch0en () , self . ch0p () , self . ch0np () , self . ch1en () , self . ch1p () , self . ch1np ()) } } # [doc = "Counter register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cnt (pub u32) ; impl Cnt { # [doc = "This bit-filed indicates the current counter value. Writing to this bit-filed can change the value of the counter."]
# [inline (always)]
pub const fn cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "This bit-filed indicates the current counter value. Writing to this bit-filed can change the value of the counter."]
# [inline (always)]
pub fn set_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Cnt { # [inline (always)]
fn default () -> Cnt { Cnt (0) } } impl core :: fmt :: Debug for Cnt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cnt") . field ("cnt" , & self . cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cnt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cnt {{ cnt: {=u16:?} }}" , self . cnt ()) } } # [doc = "Control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Counter enable"]
# [inline (always)]
pub const fn cen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Counter enable"]
# [inline (always)]
pub fn set_cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Update disable."]
# [inline (always)]
pub const fn updis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Update disable."]
# [inline (always)]
pub fn set_updis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Update source"]
# [inline (always)]
pub const fn ups (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Update source"]
# [inline (always)]
pub fn set_ups (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Single pulse mode."]
# [inline (always)]
pub const fn spm (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Single pulse mode."]
# [inline (always)]
pub fn set_spm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Auto-reload shadow enable"]
# [inline (always)]
pub const fn arse (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Auto-reload shadow enable"]
# [inline (always)]
pub fn set_arse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Clock division"]
# [inline (always)]
pub const fn ckdiv (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Clock division"]
# [inline (always)]
pub fn set_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("cen" , & self . cen ()) . field ("updis" , & self . updis ()) . field ("ups" , & self . ups ()) . field ("spm" , & self . spm ()) . field ("arse" , & self . arse ()) . field ("ckdiv" , & self . ckdiv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ cen: {=bool:?}, updis: {=bool:?}, ups: {=bool:?}, spm: {=bool:?}, arse: {=bool:?}, ckdiv: {=u8:?} }}" , self . cen () , self . updis () , self . ups () , self . spm () , self . arse () , self . ckdiv ()) } } # [doc = "Interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmainten (pub u32) ; impl Dmainten { # [doc = "Update interrupt enable"]
# [inline (always)]
pub const fn upie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt enable"]
# [inline (always)]
pub fn set_upie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture/compare interrupt enable"]
# [inline (always)]
pub const fn ch0ie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare interrupt enable"]
# [inline (always)]
pub fn set_ch0ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 1 capture/compare interrupt enable"]
# [inline (always)]
pub const fn ch1ie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare interrupt enable"]
# [inline (always)]
pub fn set_ch1ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub const fn trgie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub fn set_trgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for Dmainten { # [inline (always)]
fn default () -> Dmainten { Dmainten (0) } } impl core :: fmt :: Debug for Dmainten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmainten") . field ("upie" , & self . upie ()) . field ("ch0ie" , & self . ch0ie ()) . field ("ch1ie" , & self . ch1ie ()) . field ("trgie" , & self . trgie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmainten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmainten {{ upie: {=bool:?}, ch0ie: {=bool:?}, ch1ie: {=bool:?}, trgie: {=bool:?} }}" , self . upie () , self . ch0ie () , self . ch1ie () , self . trgie ()) } } # [doc = "Interrupt flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "Update interrupt flag"]
# [inline (always)]
pub const fn upif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt flag"]
# [inline (always)]
pub fn set_upif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture/compare interrupt flag"]
# [inline (always)]
pub const fn ch0if (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare interrupt flag"]
# [inline (always)]
pub fn set_ch0if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 1 capture/compare interrupt flag"]
# [inline (always)]
pub const fn ch1if (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare interrupt flag"]
# [inline (always)]
pub fn set_ch1if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub const fn trgif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub fn set_trgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Channel 0 over capture flag"]
# [inline (always)]
pub const fn ch0of (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Channel 0 over capture flag"]
# [inline (always)]
pub fn set_ch0of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Channel 1 over capture flag"]
# [inline (always)]
pub const fn ch1of (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Channel 1 over capture flag"]
# [inline (always)]
pub fn set_ch1of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("upif" , & self . upif ()) . field ("ch0if" , & self . ch0if ()) . field ("ch1if" , & self . ch1if ()) . field ("trgif" , & self . trgif ()) . field ("ch0of" , & self . ch0of ()) . field ("ch1of" , & self . ch1of ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ upif: {=bool:?}, ch0if: {=bool:?}, ch1if: {=bool:?}, trgif: {=bool:?}, ch0of: {=bool:?}, ch1of: {=bool:?} }}" , self . upif () , self . ch0if () , self . ch1if () , self . trgif () , self . ch0of () , self . ch1of ()) } } # [doc = "Prescaler register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Psc (pub u32) ; impl Psc { # [doc = "Prescaler value of the counter clock"]
# [inline (always)]
pub const fn psc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Prescaler value of the counter clock"]
# [inline (always)]
pub fn set_psc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Psc { # [inline (always)]
fn default () -> Psc { Psc (0) } } impl core :: fmt :: Debug for Psc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Psc") . field ("psc" , & self . psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Psc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Psc {{ psc: {=u16:?} }}" , self . psc ()) } } # [doc = "Slave mode configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Smcfg (pub u32) ; impl Smcfg { # [doc = "Slave mode control"]
# [inline (always)]
pub const fn smc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "Slave mode control"]
# [inline (always)]
pub fn set_smc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "Trigger selection"]
# [inline (always)]
pub const fn trgs (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Trigger selection"]
# [inline (always)]
pub fn set_trgs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Master-slave mode"]
# [inline (always)]
pub const fn msm (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Master-slave mode"]
# [inline (always)]
pub fn set_msm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Smcfg { # [inline (always)]
fn default () -> Smcfg { Smcfg (0) } } impl core :: fmt :: Debug for Smcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Smcfg") . field ("smc" , & self . smc ()) . field ("trgs" , & self . trgs ()) . field ("msm" , & self . msm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Smcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Smcfg {{ smc: {=u8:?}, trgs: {=u8:?}, msm: {=bool:?} }}" , self . smc () , self . trgs () , self . msm ()) } } # [doc = "Software event generation register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Swevg (pub u32) ; impl Swevg { # [doc = "Update event generation"]
# [inline (always)]
pub const fn upg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update event generation"]
# [inline (always)]
pub fn set_upg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture or compare event generation"]
# [inline (always)]
pub const fn ch0g (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture or compare event generation"]
# [inline (always)]
pub fn set_ch0g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 1 capture or compare event generation"]
# [inline (always)]
pub const fn ch1g (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture or compare event generation"]
# [inline (always)]
pub fn set_ch1g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Channel 2 capture or compare event generation"]
# [inline (always)]
pub const fn ch2g (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture or compare event generation"]
# [inline (always)]
pub fn set_ch2g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 3 capture or compare event generation"]
# [inline (always)]
pub const fn ch3g (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture or compare event generation"]
# [inline (always)]
pub fn set_ch3g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Channel commutation event generation"]
# [inline (always)]
pub const fn cmtg (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Channel commutation event generation"]
# [inline (always)]
pub fn set_cmtg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Trigger event generation"]
# [inline (always)]
pub const fn trgg (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger event generation"]
# [inline (always)]
pub fn set_trgg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Break event generation"]
# [inline (always)]
pub const fn brkg (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Break event generation"]
# [inline (always)]
pub fn set_brkg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Swevg { # [inline (always)]
fn default () -> Swevg { Swevg (0) } } impl core :: fmt :: Debug for Swevg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Swevg") . field ("upg" , & self . upg ()) . field ("ch0g" , & self . ch0g ()) . field ("ch1g" , & self . ch1g ()) . field ("ch2g" , & self . ch2g ()) . field ("ch3g" , & self . ch3g ()) . field ("cmtg" , & self . cmtg ()) . field ("trgg" , & self . trgg ()) . field ("brkg" , & self . brkg ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Swevg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Swevg {{ upg: {=bool:?}, ch0g: {=bool:?}, ch1g: {=bool:?}, ch2g: {=bool:?}, ch3g: {=bool:?}, cmtg: {=bool:?}, trgg: {=bool:?}, brkg: {=bool:?} }}" , self . upg () , self . ch0g () , self . ch1g () , self . ch2g () , self . ch3g () , self . cmtg () , self . trgg () , self . brkg ()) } } }