#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "General-purpose-timers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer14 { ptr : * mut u8 } unsafe impl Send for Timer14 { } unsafe impl Sync for Timer14 { } impl Timer14 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "slave mode configuration register"]
# [inline (always)]
pub const fn smcfg (self) -> crate :: common :: Reg < regs :: Smcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "DMA/Interrupt enable register"]
# [inline (always)]
pub const fn dmainten (self) -> crate :: common :: Reg < regs :: Dmainten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "interrupt flag register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "event generation register"]
# [inline (always)]
pub const fn swevg (self) -> crate :: common :: Reg < regs :: Swevg , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "capture/compare mode register 0 (input mode)"]
# [inline (always)]
pub const fn chctl0_input (self) -> crate :: common :: Reg < regs :: Chctl0Input , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "capture/compare mode register (output mode)"]
# [inline (always)]
pub const fn chctl0_output (self) -> crate :: common :: Reg < regs :: Chctl0Output , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "capture/compare enable register"]
# [inline (always)]
pub const fn chctl2 (self) -> crate :: common :: Reg < regs :: Chctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "counter"]
# [inline (always)]
pub const fn cnt (self) -> crate :: common :: Reg < regs :: Cnt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "prescaler"]
# [inline (always)]
pub const fn psc (self) -> crate :: common :: Reg < regs :: Psc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "auto-reload register"]
# [inline (always)]
pub const fn car (self) -> crate :: common :: Reg < regs :: Car , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "repetition counter register"]
# [inline (always)]
pub const fn crep (self) -> crate :: common :: Reg < regs :: Crep , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "capture/compare register 0"]
# [inline (always)]
pub const fn ch0cv (self) -> crate :: common :: Reg < regs :: Ch0cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "capture/compare register 1"]
# [inline (always)]
pub const fn ch1cv (self) -> crate :: common :: Reg < regs :: Ch1cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "break and dead-time register"]
# [inline (always)]
pub const fn cchp (self) -> crate :: common :: Reg < regs :: Cchp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "DMA configuration register"]
# [inline (always)]
pub const fn dmacfg (self) -> crate :: common :: Reg < regs :: Dmacfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "DMA transfer buffer register"]
# [inline (always)]
pub const fn dmatb (self) -> crate :: common :: Reg < regs :: Dmatb , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "configuration register"]
# [inline (always)]
pub const fn cfg (self) -> crate :: common :: Reg < regs :: Cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xfcusize) as _) } } } pub mod regs { # [doc = "auto-reload register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Car (pub u32) ; impl Car { # [doc = "Auto-reload value"]
# [inline (always)]
pub const fn carl (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Auto-reload value"]
# [inline (always)]
pub fn set_carl (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Car { # [inline (always)]
fn default () -> Car { Car (0) } } impl core :: fmt :: Debug for Car { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Car") . field ("carl" , & self . carl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Car { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Car {{ carl: {=u16:?} }}" , self . carl ()) } } # [doc = "break and dead-time register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cchp (pub u32) ; impl Cchp { # [doc = "Dead-time generator configure"]
# [inline (always)]
pub const fn dtcfg (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Dead-time generator configure"]
# [inline (always)]
pub fn set_dtcfg (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "complementary register protect control"]
# [inline (always)]
pub const fn prot (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "complementary register protect control"]
# [inline (always)]
pub fn set_prot (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Off-state selection for Idle mode"]
# [inline (always)]
pub const fn ios (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Off-state selection for Idle mode"]
# [inline (always)]
pub fn set_ios (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Off-state selection for Run mode"]
# [inline (always)]
pub const fn ros (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Off-state selection for Run mode"]
# [inline (always)]
pub fn set_ros (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Break enable"]
# [inline (always)]
pub const fn brken (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Break enable"]
# [inline (always)]
pub fn set_brken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Break polarity"]
# [inline (always)]
pub const fn brkp (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Break polarity"]
# [inline (always)]
pub fn set_brkp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Automatic output enable"]
# [inline (always)]
pub const fn oaen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Automatic output enable"]
# [inline (always)]
pub fn set_oaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Main output enable"]
# [inline (always)]
pub const fn poen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Main output enable"]
# [inline (always)]
pub fn set_poen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Cchp { # [inline (always)]
fn default () -> Cchp { Cchp (0) } } impl core :: fmt :: Debug for Cchp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cchp") . field ("dtcfg" , & self . dtcfg ()) . field ("prot" , & self . prot ()) . field ("ios" , & self . ios ()) . field ("ros" , & self . ros ()) . field ("brken" , & self . brken ()) . field ("brkp" , & self . brkp ()) . field ("oaen" , & self . oaen ()) . field ("poen" , & self . poen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cchp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cchp {{ dtcfg: {=u8:?}, prot: {=u8:?}, ios: {=bool:?}, ros: {=bool:?}, brken: {=bool:?}, brkp: {=bool:?}, oaen: {=bool:?}, poen: {=bool:?} }}" , self . dtcfg () , self . prot () , self . ios () , self . ros () , self . brken () , self . brkp () , self . oaen () , self . poen ()) } } # [doc = "configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg (pub u32) ; impl Cfg { # [doc = "The output value selection"]
# [inline (always)]
pub const fn outsel (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "The output value selection"]
# [inline (always)]
pub fn set_outsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub const fn chvsel (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub fn set_chvsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Cfg { # [inline (always)]
fn default () -> Cfg { Cfg (0) } } impl core :: fmt :: Debug for Cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg") . field ("outsel" , & self . outsel ()) . field ("chvsel" , & self . chvsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg {{ outsel: {=bool:?}, chvsel: {=bool:?} }}" , self . outsel () , self . chvsel ()) } } # [doc = "capture/compare register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch0cv (pub u32) ; impl Ch0cv { # [doc = "Capture/Compare 0 value"]
# [inline (always)]
pub const fn ch0val (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Capture/Compare 0 value"]
# [inline (always)]
pub fn set_ch0val (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Ch0cv { # [inline (always)]
fn default () -> Ch0cv { Ch0cv (0) } } impl core :: fmt :: Debug for Ch0cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch0cv") . field ("ch0val" , & self . ch0val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch0cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch0cv {{ ch0val: {=u16:?} }}" , self . ch0val ()) } } # [doc = "capture/compare register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch1cv (pub u32) ; impl Ch1cv { # [doc = "Capture/Compare 1 value"]
# [inline (always)]
pub const fn ch1val (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Capture/Compare 1 value"]
# [inline (always)]
pub fn set_ch1val (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Ch1cv { # [inline (always)]
fn default () -> Ch1cv { Ch1cv (0) } } impl core :: fmt :: Debug for Ch1cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch1cv") . field ("ch1val" , & self . ch1val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch1cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch1cv {{ ch1val: {=u16:?} }}" , self . ch1val ()) } } # [doc = "capture/compare mode register 0 (input mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl0Input (pub u32) ; impl Chctl0Input { # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub const fn ch0ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub fn set_ch0ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Input capture 0 prescaler"]
# [inline (always)]
pub const fn ch0cappsc (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Input capture 0 prescaler"]
# [inline (always)]
pub fn set_ch0cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Input capture 0 filter"]
# [inline (always)]
pub const fn ch0capflt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Input capture 0 filter"]
# [inline (always)]
pub fn set_ch0capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Capture/Compare 1 selection"]
# [inline (always)]
pub const fn ch1ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 1 selection"]
# [inline (always)]
pub fn set_ch1ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Input capture 1 prescaler"]
# [inline (always)]
pub const fn ch1cappsc (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Input capture 1 prescaler"]
# [inline (always)]
pub fn set_ch1cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Input capture 1 filter"]
# [inline (always)]
pub const fn ch1capflt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Input capture 1 filter"]
# [inline (always)]
pub fn set_ch1capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Chctl0Input { # [inline (always)]
fn default () -> Chctl0Input { Chctl0Input (0) } } impl core :: fmt :: Debug for Chctl0Input { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl0Input") . field ("ch0ms" , & self . ch0ms ()) . field ("ch0cappsc" , & self . ch0cappsc ()) . field ("ch0capflt" , & self . ch0capflt ()) . field ("ch1ms" , & self . ch1ms ()) . field ("ch1cappsc" , & self . ch1cappsc ()) . field ("ch1capflt" , & self . ch1capflt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl0Input { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl0Input {{ ch0ms: {=u8:?}, ch0cappsc: {=u8:?}, ch0capflt: {=u8:?}, ch1ms: {=u8:?}, ch1cappsc: {=u8:?}, ch1capflt: {=u8:?} }}" , self . ch0ms () , self . ch0cappsc () , self . ch0capflt () , self . ch1ms () , self . ch1cappsc () , self . ch1capflt ()) } } # [doc = "capture/compare mode register (output mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl0Output (pub u32) ; impl Chctl0Output { # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub const fn ch0ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub fn set_ch0ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Output Compare 0 fast enable"]
# [inline (always)]
pub const fn ch0comfen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Output Compare 0 fast enable"]
# [inline (always)]
pub fn set_ch0comfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Output Compare 0 preload enable"]
# [inline (always)]
pub const fn ch0comsen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Output Compare 0 preload enable"]
# [inline (always)]
pub fn set_ch0comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Output Compare 0 mode"]
# [inline (always)]
pub const fn ch0comctl (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Output Compare 0 mode"]
# [inline (always)]
pub fn set_ch0comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Capture/Compare 1 selection"]
# [inline (always)]
pub const fn ch1ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 1 selection"]
# [inline (always)]
pub fn set_ch1ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Output Compare 1 fast enable"]
# [inline (always)]
pub const fn ch1comfen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Output Compare 1 fast enable"]
# [inline (always)]
pub fn set_ch1comfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Output Compare 1 preload enable"]
# [inline (always)]
pub const fn ch1comsen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Output Compare 1 preload enable"]
# [inline (always)]
pub fn set_ch1comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Output Compare 1 mode"]
# [inline (always)]
pub const fn ch1comctl (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Output Compare 1 mode"]
# [inline (always)]
pub fn set_ch1comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } } impl Default for Chctl0Output { # [inline (always)]
fn default () -> Chctl0Output { Chctl0Output (0) } } impl core :: fmt :: Debug for Chctl0Output { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl0Output") . field ("ch0ms" , & self . ch0ms ()) . field ("ch0comfen" , & self . ch0comfen ()) . field ("ch0comsen" , & self . ch0comsen ()) . field ("ch0comctl" , & self . ch0comctl ()) . field ("ch1ms" , & self . ch1ms ()) . field ("ch1comfen" , & self . ch1comfen ()) . field ("ch1comsen" , & self . ch1comsen ()) . field ("ch1comctl" , & self . ch1comctl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl0Output { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl0Output {{ ch0ms: {=u8:?}, ch0comfen: {=bool:?}, ch0comsen: {=bool:?}, ch0comctl: {=u8:?}, ch1ms: {=u8:?}, ch1comfen: {=bool:?}, ch1comsen: {=bool:?}, ch1comctl: {=u8:?} }}" , self . ch0ms () , self . ch0comfen () , self . ch0comsen () , self . ch0comctl () , self . ch1ms () , self . ch1comfen () , self . ch1comsen () , self . ch1comctl ()) } } # [doc = "capture/compare enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl2 (pub u32) ; impl Chctl2 { # [doc = "Capture/Compare 0 output enable"]
# [inline (always)]
pub const fn ch0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 output enable"]
# [inline (always)]
pub fn set_ch0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub const fn ch0p (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub fn set_ch0p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/Compare 0 complementary output enable"]
# [inline (always)]
pub const fn ch0nen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 complementary output enable"]
# [inline (always)]
pub fn set_ch0nen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub const fn ch0np (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub fn set_ch0np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Capture/Compare 1 output enable"]
# [inline (always)]
pub const fn ch1en (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 output enable"]
# [inline (always)]
pub fn set_ch1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub const fn ch1p (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub fn set_ch1p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub const fn ch1np (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub fn set_ch1np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Chctl2 { # [inline (always)]
fn default () -> Chctl2 { Chctl2 (0) } } impl core :: fmt :: Debug for Chctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl2") . field ("ch0en" , & self . ch0en ()) . field ("ch0p" , & self . ch0p ()) . field ("ch0nen" , & self . ch0nen ()) . field ("ch0np" , & self . ch0np ()) . field ("ch1en" , & self . ch1en ()) . field ("ch1p" , & self . ch1p ()) . field ("ch1np" , & self . ch1np ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl2 {{ ch0en: {=bool:?}, ch0p: {=bool:?}, ch0nen: {=bool:?}, ch0np: {=bool:?}, ch1en: {=bool:?}, ch1p: {=bool:?}, ch1np: {=bool:?} }}" , self . ch0en () , self . ch0p () , self . ch0nen () , self . ch0np () , self . ch1en () , self . ch1p () , self . ch1np ()) } } # [doc = "counter"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cnt (pub u32) ; impl Cnt { # [doc = "counter value"]
# [inline (always)]
pub const fn cnt (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "counter value"]
# [inline (always)]
pub fn set_cnt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Cnt { # [inline (always)]
fn default () -> Cnt { Cnt (0) } } impl core :: fmt :: Debug for Cnt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cnt") . field ("cnt" , & self . cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cnt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cnt {{ cnt: {=u16:?} }}" , self . cnt ()) } } # [doc = "repetition counter register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Crep (pub u32) ; impl Crep { # [doc = "Repetition counter value"]
# [inline (always)]
pub const fn crep (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Repetition counter value"]
# [inline (always)]
pub fn set_crep (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for Crep { # [inline (always)]
fn default () -> Crep { Crep (0) } } impl core :: fmt :: Debug for Crep { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Crep") . field ("crep" , & self . crep ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Crep { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Crep {{ crep: {=u8:?} }}" , self . crep ()) } } # [doc = "control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Counter enable"]
# [inline (always)]
pub const fn cen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Counter enable"]
# [inline (always)]
pub fn set_cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Update disable"]
# [inline (always)]
pub const fn updis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Update disable"]
# [inline (always)]
pub fn set_updis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Update request source"]
# [inline (always)]
pub const fn ups (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Update request source"]
# [inline (always)]
pub fn set_ups (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "One-pulse mode"]
# [inline (always)]
pub const fn spm (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "One-pulse mode"]
# [inline (always)]
pub fn set_spm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Auto-reload preload enable"]
# [inline (always)]
pub const fn arse (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Auto-reload preload enable"]
# [inline (always)]
pub fn set_arse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Clock division"]
# [inline (always)]
pub const fn ckdiv (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Clock division"]
# [inline (always)]
pub fn set_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("cen" , & self . cen ()) . field ("updis" , & self . updis ()) . field ("ups" , & self . ups ()) . field ("spm" , & self . spm ()) . field ("arse" , & self . arse ()) . field ("ckdiv" , & self . ckdiv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ cen: {=bool:?}, updis: {=bool:?}, ups: {=bool:?}, spm: {=bool:?}, arse: {=bool:?}, ckdiv: {=u8:?} }}" , self . cen () , self . updis () , self . ups () , self . spm () , self . arse () , self . ckdiv ()) } } # [doc = "control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Capture/compare preloaded control"]
# [inline (always)]
pub const fn ccse (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Capture/compare preloaded control"]
# [inline (always)]
pub fn set_ccse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/compare control update selection"]
# [inline (always)]
pub const fn ccuc (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/compare control update selection"]
# [inline (always)]
pub fn set_ccuc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Capture/compare DMA selection"]
# [inline (always)]
pub const fn dmas (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/compare DMA selection"]
# [inline (always)]
pub fn set_dmas (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Master mode selection"]
# [inline (always)]
pub const fn mmc (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Master mode selection"]
# [inline (always)]
pub fn set_mmc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Output Idle state 0"]
# [inline (always)]
pub const fn iso0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Output Idle state 0"]
# [inline (always)]
pub fn set_iso0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Output Idle state 0"]
# [inline (always)]
pub const fn iso0n (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Output Idle state 0"]
# [inline (always)]
pub fn set_iso0n (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Output Idle state 1"]
# [inline (always)]
pub const fn iso1 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Output Idle state 1"]
# [inline (always)]
pub fn set_iso1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("ccse" , & self . ccse ()) . field ("ccuc" , & self . ccuc ()) . field ("dmas" , & self . dmas ()) . field ("mmc" , & self . mmc ()) . field ("iso0" , & self . iso0 ()) . field ("iso0n" , & self . iso0n ()) . field ("iso1" , & self . iso1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ ccse: {=bool:?}, ccuc: {=bool:?}, dmas: {=bool:?}, mmc: {=u8:?}, iso0: {=bool:?}, iso0n: {=bool:?}, iso1: {=bool:?} }}" , self . ccse () , self . ccuc () , self . dmas () , self . mmc () , self . iso0 () , self . iso0n () , self . iso1 ()) } } # [doc = "DMA configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmacfg (pub u32) ; impl Dmacfg { # [doc = "DMA base address"]
# [inline (always)]
pub const fn dmata (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [doc = "DMA base address"]
# [inline (always)]
pub fn set_dmata (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [doc = "DMA burst length"]
# [inline (always)]
pub const fn dmatc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x1f ; val as u8 } # [doc = "DMA burst length"]
# [inline (always)]
pub fn set_dmatc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize) ; } } impl Default for Dmacfg { # [inline (always)]
fn default () -> Dmacfg { Dmacfg (0) } } impl core :: fmt :: Debug for Dmacfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmacfg") . field ("dmata" , & self . dmata ()) . field ("dmatc" , & self . dmatc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmacfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmacfg {{ dmata: {=u8:?}, dmatc: {=u8:?} }}" , self . dmata () , self . dmatc ()) } } # [doc = "DMA/Interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmainten (pub u32) ; impl Dmainten { # [doc = "Update interrupt enable"]
# [inline (always)]
pub const fn upie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt enable"]
# [inline (always)]
pub fn set_upie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/Compare 1 interrupt enable"]
# [inline (always)]
pub const fn ch0ie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 interrupt enable"]
# [inline (always)]
pub fn set_ch0ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/Compare 2 interrupt enable"]
# [inline (always)]
pub const fn ch1ie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 interrupt enable"]
# [inline (always)]
pub fn set_ch1ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "COM interrupt enable"]
# [inline (always)]
pub const fn cmtie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "COM interrupt enable"]
# [inline (always)]
pub fn set_cmtie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub const fn trgie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub fn set_trgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Break interrupt enable"]
# [inline (always)]
pub const fn brkie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Break interrupt enable"]
# [inline (always)]
pub fn set_brkie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Update DMA request enable"]
# [inline (always)]
pub const fn upden (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Update DMA request enable"]
# [inline (always)]
pub fn set_upden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Capture/Compare 0 DMA request enable"]
# [inline (always)]
pub const fn ch0den (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 DMA request enable"]
# [inline (always)]
pub fn set_ch0den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Capture/Compare 1 DMA request enable"]
# [inline (always)]
pub const fn ch1den (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 DMA request enable"]
# [inline (always)]
pub fn set_ch1den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Commutation DMA request enable"]
# [inline (always)]
pub const fn cmtden (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Commutation DMA request enable"]
# [inline (always)]
pub fn set_cmtden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Trigger DMA request enable"]
# [inline (always)]
pub const fn trgden (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Trigger DMA request enable"]
# [inline (always)]
pub fn set_trgden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } } impl Default for Dmainten { # [inline (always)]
fn default () -> Dmainten { Dmainten (0) } } impl core :: fmt :: Debug for Dmainten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmainten") . field ("upie" , & self . upie ()) . field ("ch0ie" , & self . ch0ie ()) . field ("ch1ie" , & self . ch1ie ()) . field ("cmtie" , & self . cmtie ()) . field ("trgie" , & self . trgie ()) . field ("brkie" , & self . brkie ()) . field ("upden" , & self . upden ()) . field ("ch0den" , & self . ch0den ()) . field ("ch1den" , & self . ch1den ()) . field ("cmtden" , & self . cmtden ()) . field ("trgden" , & self . trgden ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmainten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmainten {{ upie: {=bool:?}, ch0ie: {=bool:?}, ch1ie: {=bool:?}, cmtie: {=bool:?}, trgie: {=bool:?}, brkie: {=bool:?}, upden: {=bool:?}, ch0den: {=bool:?}, ch1den: {=bool:?}, cmtden: {=bool:?}, trgden: {=bool:?} }}" , self . upie () , self . ch0ie () , self . ch1ie () , self . cmtie () , self . trgie () , self . brkie () , self . upden () , self . ch0den () , self . ch1den () , self . cmtden () , self . trgden ()) } } # [doc = "DMA transfer buffer register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmatb (pub u32) ; impl Dmatb { # [doc = "DMA register for burst accesses"]
# [inline (always)]
pub const fn dmatb (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "DMA register for burst accesses"]
# [inline (always)]
pub fn set_dmatb (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Dmatb { # [inline (always)]
fn default () -> Dmatb { Dmatb (0) } } impl core :: fmt :: Debug for Dmatb { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmatb") . field ("dmatb" , & self . dmatb ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmatb { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmatb {{ dmatb: {=u16:?} }}" , self . dmatb ()) } } # [doc = "interrupt flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "Update interrupt flag"]
# [inline (always)]
pub const fn upif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt flag"]
# [inline (always)]
pub fn set_upif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/compare 0 interrupt flag"]
# [inline (always)]
pub const fn ch0if (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 0 interrupt flag"]
# [inline (always)]
pub fn set_ch0if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/Compare 1 interrupt flag"]
# [inline (always)]
pub const fn ch1if (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 interrupt flag"]
# [inline (always)]
pub fn set_ch1if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "COM interrupt flag"]
# [inline (always)]
pub const fn cmtif (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "COM interrupt flag"]
# [inline (always)]
pub fn set_cmtif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub const fn trgif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub fn set_trgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Break interrupt flag"]
# [inline (always)]
pub const fn brkif (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Break interrupt flag"]
# [inline (always)]
pub fn set_brkif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Capture/Compare 0 overcapture flag"]
# [inline (always)]
pub const fn ch0of (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 overcapture flag"]
# [inline (always)]
pub fn set_ch0of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Capture/compare 1 overcapture flag"]
# [inline (always)]
pub const fn ch1of (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 1 overcapture flag"]
# [inline (always)]
pub fn set_ch1of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("upif" , & self . upif ()) . field ("ch0if" , & self . ch0if ()) . field ("ch1if" , & self . ch1if ()) . field ("cmtif" , & self . cmtif ()) . field ("trgif" , & self . trgif ()) . field ("brkif" , & self . brkif ()) . field ("ch0of" , & self . ch0of ()) . field ("ch1of" , & self . ch1of ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ upif: {=bool:?}, ch0if: {=bool:?}, ch1if: {=bool:?}, cmtif: {=bool:?}, trgif: {=bool:?}, brkif: {=bool:?}, ch0of: {=bool:?}, ch1of: {=bool:?} }}" , self . upif () , self . ch0if () , self . ch1if () , self . cmtif () , self . trgif () , self . brkif () , self . ch0of () , self . ch1of ()) } } # [doc = "prescaler"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Psc (pub u32) ; impl Psc { # [doc = "Prescaler value"]
# [inline (always)]
pub const fn psc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Prescaler value"]
# [inline (always)]
pub fn set_psc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Psc { # [inline (always)]
fn default () -> Psc { Psc (0) } } impl core :: fmt :: Debug for Psc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Psc") . field ("psc" , & self . psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Psc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Psc {{ psc: {=u16:?} }}" , self . psc ()) } } # [doc = "slave mode configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Smcfg (pub u32) ; impl Smcfg { # [doc = "Slave mode selection"]
# [inline (always)]
pub const fn smc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "Slave mode selection"]
# [inline (always)]
pub fn set_smc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "Trigger selection"]
# [inline (always)]
pub const fn trgs (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Trigger selection"]
# [inline (always)]
pub fn set_trgs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Master/Slave mode"]
# [inline (always)]
pub const fn msm (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Master/Slave mode"]
# [inline (always)]
pub fn set_msm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Smcfg { # [inline (always)]
fn default () -> Smcfg { Smcfg (0) } } impl core :: fmt :: Debug for Smcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Smcfg") . field ("smc" , & self . smc ()) . field ("trgs" , & self . trgs ()) . field ("msm" , & self . msm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Smcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Smcfg {{ smc: {=u8:?}, trgs: {=u8:?}, msm: {=bool:?} }}" , self . smc () , self . trgs () , self . msm ()) } } # [doc = "event generation register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Swevg (pub u32) ; impl Swevg { # [doc = "Update generation"]
# [inline (always)]
pub const fn upg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update generation"]
# [inline (always)]
pub fn set_upg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/compare 0 generation"]
# [inline (always)]
pub const fn ch0g (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 0 generation"]
# [inline (always)]
pub fn set_ch0g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/compare 1 generation"]
# [inline (always)]
pub const fn ch1g (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 1 generation"]
# [inline (always)]
pub fn set_ch1g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Capture/Compare control update generation"]
# [inline (always)]
pub const fn cmtg (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare control update generation"]
# [inline (always)]
pub fn set_cmtg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Trigger generation"]
# [inline (always)]
pub const fn trgg (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger generation"]
# [inline (always)]
pub fn set_trgg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Break generation"]
# [inline (always)]
pub const fn brkg (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Break generation"]
# [inline (always)]
pub fn set_brkg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Swevg { # [inline (always)]
fn default () -> Swevg { Swevg (0) } } impl core :: fmt :: Debug for Swevg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Swevg") . field ("upg" , & self . upg ()) . field ("ch0g" , & self . ch0g ()) . field ("ch1g" , & self . ch1g ()) . field ("cmtg" , & self . cmtg ()) . field ("trgg" , & self . trgg ()) . field ("brkg" , & self . brkg ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Swevg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Swevg {{ upg: {=bool:?}, ch0g: {=bool:?}, ch1g: {=bool:?}, cmtg: {=bool:?}, trgg: {=bool:?}, brkg: {=bool:?} }}" , self . upg () , self . ch0g () , self . ch1g () , self . cmtg () , self . trgg () , self . brkg ()) } } }