#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "General-purpose-timers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer2 { ptr : * mut u8 } unsafe impl Send for Timer2 { } unsafe impl Sync for Timer2 { } impl Timer2 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "slave mode control register"]
# [inline (always)]
pub const fn smcfg (self) -> crate :: common :: Reg < regs :: Smcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "DMA/Interrupt enable register"]
# [inline (always)]
pub const fn dmainten (self) -> crate :: common :: Reg < regs :: Dmainten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "interrupt flag register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "event generation register"]
# [inline (always)]
pub const fn swevg (self) -> crate :: common :: Reg < regs :: Swevg , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "capture/compare mode register 0 (input mode)"]
# [inline (always)]
pub const fn chctl0_input (self) -> crate :: common :: Reg < regs :: Chctl0Input , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "capture/compare mode register 0 (output mode)"]
# [inline (always)]
pub const fn chctl0_output (self) -> crate :: common :: Reg < regs :: Chctl0Output , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "capture/compare mode register 1 (input mode)"]
# [inline (always)]
pub const fn chctl1_input (self) -> crate :: common :: Reg < regs :: Chctl1Input , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "capture/compare mode register 1 (output mode)"]
# [inline (always)]
pub const fn chctl1_output (self) -> crate :: common :: Reg < regs :: Chctl1Output , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "capture/compare enable register"]
# [inline (always)]
pub const fn chctl2 (self) -> crate :: common :: Reg < regs :: Chctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "counter"]
# [inline (always)]
pub const fn cnt (self) -> crate :: common :: Reg < regs :: Cnt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "prescaler"]
# [inline (always)]
pub const fn psc (self) -> crate :: common :: Reg < regs :: Psc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "auto-reload register"]
# [inline (always)]
pub const fn car (self) -> crate :: common :: Reg < regs :: Car , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "capture/compare register 1"]
# [inline (always)]
pub const fn ch0cv (self) -> crate :: common :: Reg < regs :: Ch0cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "capture/compare register 2"]
# [inline (always)]
pub const fn ch1cv (self) -> crate :: common :: Reg < regs :: Ch1cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "capture/compare register 2"]
# [inline (always)]
pub const fn ch2cv (self) -> crate :: common :: Reg < regs :: Ch2cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "capture/compare register 3"]
# [inline (always)]
pub const fn ch3cv (self) -> crate :: common :: Reg < regs :: Ch3cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "DMA control register"]
# [inline (always)]
pub const fn dmacfg (self) -> crate :: common :: Reg < regs :: Dmacfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "DMA address for full transfer"]
# [inline (always)]
pub const fn dmatb (self) -> crate :: common :: Reg < regs :: Dmatb , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "Configuration"]
# [inline (always)]
pub const fn cfg (self) -> crate :: common :: Reg < regs :: Cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xfcusize) as _) } } } pub mod regs { # [doc = "auto-reload register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Car (pub u32) ; impl Car { # [doc = "Low Auto-reload value"]
# [inline (always)]
pub const fn carl (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Low Auto-reload value"]
# [inline (always)]
pub fn set_carl (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Car { # [inline (always)]
fn default () -> Car { Car (0) } } impl core :: fmt :: Debug for Car { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Car") . field ("carl" , & self . carl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Car { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Car {{ carl: {=u32:?} }}" , self . carl ()) } } # [doc = "Configuration"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg (pub u32) ; impl Cfg { # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub const fn chvsel (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub fn set_chvsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Cfg { # [inline (always)]
fn default () -> Cfg { Cfg (0) } } impl core :: fmt :: Debug for Cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg") . field ("chvsel" , & self . chvsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg {{ chvsel: {=bool:?} }}" , self . chvsel ()) } } # [doc = "capture/compare register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch0cv (pub u32) ; impl Ch0cv { # [doc = "Low Capture/Compare 1 value"]
# [inline (always)]
pub const fn ch0val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Low Capture/Compare 1 value"]
# [inline (always)]
pub fn set_ch0val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch0cv { # [inline (always)]
fn default () -> Ch0cv { Ch0cv (0) } } impl core :: fmt :: Debug for Ch0cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch0cv") . field ("ch0val" , & self . ch0val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch0cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch0cv {{ ch0val: {=u32:?} }}" , self . ch0val ()) } } # [doc = "capture/compare register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch1cv (pub u32) ; impl Ch1cv { # [doc = "Low Capture/Compare 2 value"]
# [inline (always)]
pub const fn ch1val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Low Capture/Compare 2 value"]
# [inline (always)]
pub fn set_ch1val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch1cv { # [inline (always)]
fn default () -> Ch1cv { Ch1cv (0) } } impl core :: fmt :: Debug for Ch1cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch1cv") . field ("ch1val" , & self . ch1val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch1cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch1cv {{ ch1val: {=u32:?} }}" , self . ch1val ()) } } # [doc = "capture/compare register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch2cv (pub u32) ; impl Ch2cv { # [doc = "High Capture/Compare value (TIM2 only)"]
# [inline (always)]
pub const fn ch2val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "High Capture/Compare value (TIM2 only)"]
# [inline (always)]
pub fn set_ch2val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch2cv { # [inline (always)]
fn default () -> Ch2cv { Ch2cv (0) } } impl core :: fmt :: Debug for Ch2cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch2cv") . field ("ch2val" , & self . ch2val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch2cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch2cv {{ ch2val: {=u32:?} }}" , self . ch2val ()) } } # [doc = "capture/compare register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch3cv (pub u32) ; impl Ch3cv { # [doc = "High Capture/Compare value (TIM2 only)"]
# [inline (always)]
pub const fn ch3val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "High Capture/Compare value (TIM2 only)"]
# [inline (always)]
pub fn set_ch3val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch3cv { # [inline (always)]
fn default () -> Ch3cv { Ch3cv (0) } } impl core :: fmt :: Debug for Ch3cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch3cv") . field ("ch3val" , & self . ch3val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch3cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch3cv {{ ch3val: {=u32:?} }}" , self . ch3val ()) } } # [doc = "capture/compare mode register 0 (input mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl0Input (pub u32) ; impl Chctl0Input { # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub const fn ch0ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub fn set_ch0ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Input capture 0 prescaler"]
# [inline (always)]
pub const fn ch0cappsc (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Input capture 0 prescaler"]
# [inline (always)]
pub fn set_ch0cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Input capture 0 filter"]
# [inline (always)]
pub const fn ch0capflt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Input capture 0 filter"]
# [inline (always)]
pub fn set_ch0capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Capture/compare 1 selection"]
# [inline (always)]
pub const fn ch1ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Capture/compare 1 selection"]
# [inline (always)]
pub fn set_ch1ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Input capture 1 prescaler"]
# [inline (always)]
pub const fn ch1cappsc (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Input capture 1 prescaler"]
# [inline (always)]
pub fn set_ch1cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Input capture 1 filter"]
# [inline (always)]
pub const fn ch1capflt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Input capture 1 filter"]
# [inline (always)]
pub fn set_ch1capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Chctl0Input { # [inline (always)]
fn default () -> Chctl0Input { Chctl0Input (0) } } impl core :: fmt :: Debug for Chctl0Input { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl0Input") . field ("ch0ms" , & self . ch0ms ()) . field ("ch0cappsc" , & self . ch0cappsc ()) . field ("ch0capflt" , & self . ch0capflt ()) . field ("ch1ms" , & self . ch1ms ()) . field ("ch1cappsc" , & self . ch1cappsc ()) . field ("ch1capflt" , & self . ch1capflt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl0Input { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl0Input {{ ch0ms: {=u8:?}, ch0cappsc: {=u8:?}, ch0capflt: {=u8:?}, ch1ms: {=u8:?}, ch1cappsc: {=u8:?}, ch1capflt: {=u8:?} }}" , self . ch0ms () , self . ch0cappsc () , self . ch0capflt () , self . ch1ms () , self . ch1cappsc () , self . ch1capflt ()) } } # [doc = "capture/compare mode register 0 (output mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl0Output (pub u32) ; impl Chctl0Output { # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub const fn ch0ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 0 selection"]
# [inline (always)]
pub fn set_ch0ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Output compare 0 fast enable"]
# [inline (always)]
pub const fn ch0comfen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Output compare 0 fast enable"]
# [inline (always)]
pub fn set_ch0comfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Output compare 0 preload enable"]
# [inline (always)]
pub const fn ch0comsen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Output compare 0 preload enable"]
# [inline (always)]
pub fn set_ch0comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Output compare 0 mode"]
# [inline (always)]
pub const fn ch0comctl (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Output compare 0 mode"]
# [inline (always)]
pub fn set_ch0comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Output compare 0 clear enable"]
# [inline (always)]
pub const fn ch0comcen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Output compare 0 clear enable"]
# [inline (always)]
pub fn set_ch0comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Capture/Compare 1 selection"]
# [inline (always)]
pub const fn ch1ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 1 selection"]
# [inline (always)]
pub fn set_ch1ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Output compare 1 fast enable"]
# [inline (always)]
pub const fn ch1comfen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Output compare 1 fast enable"]
# [inline (always)]
pub fn set_ch1comfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Output compare 1 preload enable"]
# [inline (always)]
pub const fn ch1comsen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Output compare 1 preload enable"]
# [inline (always)]
pub fn set_ch1comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Output compare 1 mode"]
# [inline (always)]
pub const fn ch1comctl (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Output compare 1 mode"]
# [inline (always)]
pub fn set_ch1comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Output compare 1 clear enable"]
# [inline (always)]
pub const fn ch1comcen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Output compare 1 clear enable"]
# [inline (always)]
pub fn set_ch1comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Chctl0Output { # [inline (always)]
fn default () -> Chctl0Output { Chctl0Output (0) } } impl core :: fmt :: Debug for Chctl0Output { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl0Output") . field ("ch0ms" , & self . ch0ms ()) . field ("ch0comfen" , & self . ch0comfen ()) . field ("ch0comsen" , & self . ch0comsen ()) . field ("ch0comctl" , & self . ch0comctl ()) . field ("ch0comcen" , & self . ch0comcen ()) . field ("ch1ms" , & self . ch1ms ()) . field ("ch1comfen" , & self . ch1comfen ()) . field ("ch1comsen" , & self . ch1comsen ()) . field ("ch1comctl" , & self . ch1comctl ()) . field ("ch1comcen" , & self . ch1comcen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl0Output { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl0Output {{ ch0ms: {=u8:?}, ch0comfen: {=bool:?}, ch0comsen: {=bool:?}, ch0comctl: {=u8:?}, ch0comcen: {=bool:?}, ch1ms: {=u8:?}, ch1comfen: {=bool:?}, ch1comsen: {=bool:?}, ch1comctl: {=u8:?}, ch1comcen: {=bool:?} }}" , self . ch0ms () , self . ch0comfen () , self . ch0comsen () , self . ch0comctl () , self . ch0comcen () , self . ch1ms () , self . ch1comfen () , self . ch1comsen () , self . ch1comctl () , self . ch1comcen ()) } } # [doc = "capture/compare mode register 1 (input mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl1Input (pub u32) ; impl Chctl1Input { # [doc = "Capture/Compare 2 selection"]
# [inline (always)]
pub const fn ch2ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 2 selection"]
# [inline (always)]
pub fn set_ch2ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Input capture 2 prescaler"]
# [inline (always)]
pub const fn ch2cappsc (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Input capture 2 prescaler"]
# [inline (always)]
pub fn set_ch2cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Input capture 2 filter"]
# [inline (always)]
pub const fn ch2capflt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Input capture 2 filter"]
# [inline (always)]
pub fn set_ch2capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Capture/Compare 3 selection"]
# [inline (always)]
pub const fn ch3ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 3 selection"]
# [inline (always)]
pub fn set_ch3ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Input capture 3 prescaler"]
# [inline (always)]
pub const fn ch3cappsc (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Input capture 3 prescaler"]
# [inline (always)]
pub fn set_ch3cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Input capture 3 filter"]
# [inline (always)]
pub const fn ch3capflt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Input capture 3 filter"]
# [inline (always)]
pub fn set_ch3capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } } impl Default for Chctl1Input { # [inline (always)]
fn default () -> Chctl1Input { Chctl1Input (0) } } impl core :: fmt :: Debug for Chctl1Input { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl1Input") . field ("ch2ms" , & self . ch2ms ()) . field ("ch2cappsc" , & self . ch2cappsc ()) . field ("ch2capflt" , & self . ch2capflt ()) . field ("ch3ms" , & self . ch3ms ()) . field ("ch3cappsc" , & self . ch3cappsc ()) . field ("ch3capflt" , & self . ch3capflt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl1Input { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl1Input {{ ch2ms: {=u8:?}, ch2cappsc: {=u8:?}, ch2capflt: {=u8:?}, ch3ms: {=u8:?}, ch3cappsc: {=u8:?}, ch3capflt: {=u8:?} }}" , self . ch2ms () , self . ch2cappsc () , self . ch2capflt () , self . ch3ms () , self . ch3cappsc () , self . ch3capflt ()) } } # [doc = "capture/compare mode register 1 (output mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl1Output (pub u32) ; impl Chctl1Output { # [doc = "Capture/Compare 2 selection"]
# [inline (always)]
pub const fn ch2ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 2 selection"]
# [inline (always)]
pub fn set_ch2ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Output compare 2 fast enable"]
# [inline (always)]
pub const fn ch2comfen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Output compare 2 fast enable"]
# [inline (always)]
pub fn set_ch2comfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Output compare 2 preload enable"]
# [inline (always)]
pub const fn ch2comsen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Output compare 2 preload enable"]
# [inline (always)]
pub fn set_ch2comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Output compare 2 mode"]
# [inline (always)]
pub const fn ch2comctl (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Output compare 2 mode"]
# [inline (always)]
pub fn set_ch2comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Output compare 2 clear enable"]
# [inline (always)]
pub const fn ch2comcen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Output compare 2 clear enable"]
# [inline (always)]
pub fn set_ch2comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Capture/Compare 3 selection"]
# [inline (always)]
pub const fn ch3ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Capture/Compare 3 selection"]
# [inline (always)]
pub fn set_ch3ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Output compare 3 fast enable"]
# [inline (always)]
pub const fn ch3comfen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Output compare 3 fast enable"]
# [inline (always)]
pub fn set_ch3comfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Output compare 3 preload enable"]
# [inline (always)]
pub const fn ch3comsen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Output compare 3 preload enable"]
# [inline (always)]
pub fn set_ch3comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Output compare 3 mode"]
# [inline (always)]
pub const fn ch3comctl (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Output compare 3 mode"]
# [inline (always)]
pub fn set_ch3comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Output compare 3 clear enable"]
# [inline (always)]
pub const fn ch3comcen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Output compare 3 clear enable"]
# [inline (always)]
pub fn set_ch3comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Chctl1Output { # [inline (always)]
fn default () -> Chctl1Output { Chctl1Output (0) } } impl core :: fmt :: Debug for Chctl1Output { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl1Output") . field ("ch2ms" , & self . ch2ms ()) . field ("ch2comfen" , & self . ch2comfen ()) . field ("ch2comsen" , & self . ch2comsen ()) . field ("ch2comctl" , & self . ch2comctl ()) . field ("ch2comcen" , & self . ch2comcen ()) . field ("ch3ms" , & self . ch3ms ()) . field ("ch3comfen" , & self . ch3comfen ()) . field ("ch3comsen" , & self . ch3comsen ()) . field ("ch3comctl" , & self . ch3comctl ()) . field ("ch3comcen" , & self . ch3comcen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl1Output { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl1Output {{ ch2ms: {=u8:?}, ch2comfen: {=bool:?}, ch2comsen: {=bool:?}, ch2comctl: {=u8:?}, ch2comcen: {=bool:?}, ch3ms: {=u8:?}, ch3comfen: {=bool:?}, ch3comsen: {=bool:?}, ch3comctl: {=u8:?}, ch3comcen: {=bool:?} }}" , self . ch2ms () , self . ch2comfen () , self . ch2comsen () , self . ch2comctl () , self . ch2comcen () , self . ch3ms () , self . ch3comfen () , self . ch3comsen () , self . ch3comctl () , self . ch3comcen ()) } } # [doc = "capture/compare enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl2 (pub u32) ; impl Chctl2 { # [doc = "Capture/Compare 0 output enable"]
# [inline (always)]
pub const fn ch0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 output enable"]
# [inline (always)]
pub fn set_ch0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub const fn ch0p (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub fn set_ch0p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub const fn ch0np (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 output Polarity"]
# [inline (always)]
pub fn set_ch0np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Capture/Compare 1 output enable"]
# [inline (always)]
pub const fn ch1en (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 output enable"]
# [inline (always)]
pub fn set_ch1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub const fn ch1p (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub fn set_ch1p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub const fn ch1np (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 output Polarity"]
# [inline (always)]
pub fn set_ch1np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Capture/Compare 2 output enable"]
# [inline (always)]
pub const fn ch2en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 output enable"]
# [inline (always)]
pub fn set_ch2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Capture/Compare 2 output Polarity"]
# [inline (always)]
pub const fn ch2p (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 output Polarity"]
# [inline (always)]
pub fn set_ch2p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Capture/Compare 2 output Polarity"]
# [inline (always)]
pub const fn ch2np (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 output Polarity"]
# [inline (always)]
pub fn set_ch2np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Capture/Compare 3 output enable"]
# [inline (always)]
pub const fn ch3en (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 output enable"]
# [inline (always)]
pub fn set_ch3en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Capture/Compare 3 output Polarity"]
# [inline (always)]
pub const fn ch3p (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 output Polarity"]
# [inline (always)]
pub fn set_ch3p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Capture/Compare 3 output Polarity"]
# [inline (always)]
pub const fn ch3np (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 output Polarity"]
# [inline (always)]
pub fn set_ch3np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Chctl2 { # [inline (always)]
fn default () -> Chctl2 { Chctl2 (0) } } impl core :: fmt :: Debug for Chctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl2") . field ("ch0en" , & self . ch0en ()) . field ("ch0p" , & self . ch0p ()) . field ("ch0np" , & self . ch0np ()) . field ("ch1en" , & self . ch1en ()) . field ("ch1p" , & self . ch1p ()) . field ("ch1np" , & self . ch1np ()) . field ("ch2en" , & self . ch2en ()) . field ("ch2p" , & self . ch2p ()) . field ("ch2np" , & self . ch2np ()) . field ("ch3en" , & self . ch3en ()) . field ("ch3p" , & self . ch3p ()) . field ("ch3np" , & self . ch3np ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl2 {{ ch0en: {=bool:?}, ch0p: {=bool:?}, ch0np: {=bool:?}, ch1en: {=bool:?}, ch1p: {=bool:?}, ch1np: {=bool:?}, ch2en: {=bool:?}, ch2p: {=bool:?}, ch2np: {=bool:?}, ch3en: {=bool:?}, ch3p: {=bool:?}, ch3np: {=bool:?} }}" , self . ch0en () , self . ch0p () , self . ch0np () , self . ch1en () , self . ch1p () , self . ch1np () , self . ch2en () , self . ch2p () , self . ch2np () , self . ch3en () , self . ch3p () , self . ch3np ()) } } # [doc = "counter"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cnt (pub u32) ; impl Cnt { # [doc = "counter value"]
# [inline (always)]
pub const fn cnt (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "counter value"]
# [inline (always)]
pub fn set_cnt (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Cnt { # [inline (always)]
fn default () -> Cnt { Cnt (0) } } impl core :: fmt :: Debug for Cnt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cnt") . field ("cnt" , & self . cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cnt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cnt {{ cnt: {=u32:?} }}" , self . cnt ()) } } # [doc = "control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Counter enable"]
# [inline (always)]
pub const fn cen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Counter enable"]
# [inline (always)]
pub fn set_cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Update disable"]
# [inline (always)]
pub const fn updis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Update disable"]
# [inline (always)]
pub fn set_updis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Update request source"]
# [inline (always)]
pub const fn ups (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Update request source"]
# [inline (always)]
pub fn set_ups (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "One-pulse mode"]
# [inline (always)]
pub const fn spm (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "One-pulse mode"]
# [inline (always)]
pub fn set_spm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Direction"]
# [inline (always)]
pub const fn dir (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Direction"]
# [inline (always)]
pub fn set_dir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Center-aligned mode selection"]
# [inline (always)]
pub const fn cam (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x03 ; val as u8 } # [doc = "Center-aligned mode selection"]
# [inline (always)]
pub fn set_cam (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 5usize)) | (((val as u32) & 0x03) << 5usize) ; } # [doc = "Auto-reload preload enable"]
# [inline (always)]
pub const fn arse (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Auto-reload preload enable"]
# [inline (always)]
pub fn set_arse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Clock division"]
# [inline (always)]
pub const fn ckdiv (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Clock division"]
# [inline (always)]
pub fn set_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("cen" , & self . cen ()) . field ("updis" , & self . updis ()) . field ("ups" , & self . ups ()) . field ("spm" , & self . spm ()) . field ("dir" , & self . dir ()) . field ("cam" , & self . cam ()) . field ("arse" , & self . arse ()) . field ("ckdiv" , & self . ckdiv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ cen: {=bool:?}, updis: {=bool:?}, ups: {=bool:?}, spm: {=bool:?}, dir: {=bool:?}, cam: {=u8:?}, arse: {=bool:?}, ckdiv: {=u8:?} }}" , self . cen () , self . updis () , self . ups () , self . spm () , self . dir () , self . cam () , self . arse () , self . ckdiv ()) } } # [doc = "control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Capture/compare DMA selection"]
# [inline (always)]
pub const fn dmas (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/compare DMA selection"]
# [inline (always)]
pub fn set_dmas (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Master mode selection"]
# [inline (always)]
pub const fn mmc (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Master mode selection"]
# [inline (always)]
pub fn set_mmc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "TI0 selection"]
# [inline (always)]
pub const fn ti0s (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "TI0 selection"]
# [inline (always)]
pub fn set_ti0s (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("dmas" , & self . dmas ()) . field ("mmc" , & self . mmc ()) . field ("ti0s" , & self . ti0s ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ dmas: {=bool:?}, mmc: {=u8:?}, ti0s: {=bool:?} }}" , self . dmas () , self . mmc () , self . ti0s ()) } } # [doc = "DMA control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmacfg (pub u32) ; impl Dmacfg { # [doc = "DMA base address"]
# [inline (always)]
pub const fn dmata (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x1f ; val as u8 } # [doc = "DMA base address"]
# [inline (always)]
pub fn set_dmata (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 0usize)) | (((val as u32) & 0x1f) << 0usize) ; } # [doc = "DMA burst length"]
# [inline (always)]
pub const fn dmatc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x1f ; val as u8 } # [doc = "DMA burst length"]
# [inline (always)]
pub fn set_dmatc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize) ; } } impl Default for Dmacfg { # [inline (always)]
fn default () -> Dmacfg { Dmacfg (0) } } impl core :: fmt :: Debug for Dmacfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmacfg") . field ("dmata" , & self . dmata ()) . field ("dmatc" , & self . dmatc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmacfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmacfg {{ dmata: {=u8:?}, dmatc: {=u8:?} }}" , self . dmata () , self . dmatc ()) } } # [doc = "DMA/Interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmainten (pub u32) ; impl Dmainten { # [doc = "Update interrupt enable"]
# [inline (always)]
pub const fn upie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt enable"]
# [inline (always)]
pub fn set_upie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/Compare 0 interrupt enable"]
# [inline (always)]
pub const fn ch0ie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 interrupt enable"]
# [inline (always)]
pub fn set_ch0ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/Compare 1 interrupt enable"]
# [inline (always)]
pub const fn ch1ie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 interrupt enable"]
# [inline (always)]
pub fn set_ch1ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Capture/Compare 2 interrupt enable"]
# [inline (always)]
pub const fn ch2ie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 interrupt enable"]
# [inline (always)]
pub fn set_ch2ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Capture/Compare 3 interrupt enable"]
# [inline (always)]
pub const fn ch3ie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 interrupt enable"]
# [inline (always)]
pub fn set_ch3ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub const fn trgie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub fn set_trgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Update DMA request enable"]
# [inline (always)]
pub const fn upden (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Update DMA request enable"]
# [inline (always)]
pub fn set_upden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Capture/Compare 1 DMA request enable"]
# [inline (always)]
pub const fn ch0den (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 DMA request enable"]
# [inline (always)]
pub fn set_ch0den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Capture/Compare 1 DMA request enable"]
# [inline (always)]
pub const fn ch1den (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 DMA request enable"]
# [inline (always)]
pub fn set_ch1den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Capture/Compare 2 DMA request enable"]
# [inline (always)]
pub const fn ch2den (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 DMA request enable"]
# [inline (always)]
pub fn set_ch2den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Capture/Compare 3 DMA request enable"]
# [inline (always)]
pub const fn ch3den (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 DMA request enable"]
# [inline (always)]
pub fn set_ch3den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Trigger DMA request enable"]
# [inline (always)]
pub const fn trgden (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Trigger DMA request enable"]
# [inline (always)]
pub fn set_trgden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } } impl Default for Dmainten { # [inline (always)]
fn default () -> Dmainten { Dmainten (0) } } impl core :: fmt :: Debug for Dmainten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmainten") . field ("upie" , & self . upie ()) . field ("ch0ie" , & self . ch0ie ()) . field ("ch1ie" , & self . ch1ie ()) . field ("ch2ie" , & self . ch2ie ()) . field ("ch3ie" , & self . ch3ie ()) . field ("trgie" , & self . trgie ()) . field ("upden" , & self . upden ()) . field ("ch0den" , & self . ch0den ()) . field ("ch1den" , & self . ch1den ()) . field ("ch2den" , & self . ch2den ()) . field ("ch3den" , & self . ch3den ()) . field ("trgden" , & self . trgden ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmainten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmainten {{ upie: {=bool:?}, ch0ie: {=bool:?}, ch1ie: {=bool:?}, ch2ie: {=bool:?}, ch3ie: {=bool:?}, trgie: {=bool:?}, upden: {=bool:?}, ch0den: {=bool:?}, ch1den: {=bool:?}, ch2den: {=bool:?}, ch3den: {=bool:?}, trgden: {=bool:?} }}" , self . upie () , self . ch0ie () , self . ch1ie () , self . ch2ie () , self . ch3ie () , self . trgie () , self . upden () , self . ch0den () , self . ch1den () , self . ch2den () , self . ch3den () , self . trgden ()) } } # [doc = "DMA address for full transfer"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmatb (pub u32) ; impl Dmatb { # [doc = "DMA register for burst accesses"]
# [inline (always)]
pub const fn dmatb (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "DMA register for burst accesses"]
# [inline (always)]
pub fn set_dmatb (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Dmatb { # [inline (always)]
fn default () -> Dmatb { Dmatb (0) } } impl core :: fmt :: Debug for Dmatb { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmatb") . field ("dmatb" , & self . dmatb ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmatb { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmatb {{ dmatb: {=u32:?} }}" , self . dmatb ()) } } # [doc = "interrupt flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "Update interrupt flag"]
# [inline (always)]
pub const fn upif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt flag"]
# [inline (always)]
pub fn set_upif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/compare 0 interrupt flag"]
# [inline (always)]
pub const fn ch0if (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 0 interrupt flag"]
# [inline (always)]
pub fn set_ch0if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/Compare 1 interrupt flag"]
# [inline (always)]
pub const fn ch1if (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 1 interrupt flag"]
# [inline (always)]
pub fn set_ch1if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Capture/Compare 2 interrupt flag"]
# [inline (always)]
pub const fn ch2if (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 interrupt flag"]
# [inline (always)]
pub fn set_ch2if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Capture/Compare 3 interrupt flag"]
# [inline (always)]
pub const fn ch3if (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 interrupt flag"]
# [inline (always)]
pub fn set_ch3if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub const fn trgif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub fn set_trgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Capture/Compare 0 overcapture flag"]
# [inline (always)]
pub const fn ch0of (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 0 overcapture flag"]
# [inline (always)]
pub fn set_ch0of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Capture/compare 1 overcapture flag"]
# [inline (always)]
pub const fn ch1of (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 1 overcapture flag"]
# [inline (always)]
pub fn set_ch1of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Capture/Compare 2 overcapture flag"]
# [inline (always)]
pub const fn ch2of (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 2 overcapture flag"]
# [inline (always)]
pub fn set_ch2of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Capture/Compare 3 overcapture flag"]
# [inline (always)]
pub const fn ch3of (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Capture/Compare 3 overcapture flag"]
# [inline (always)]
pub fn set_ch3of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("upif" , & self . upif ()) . field ("ch0if" , & self . ch0if ()) . field ("ch1if" , & self . ch1if ()) . field ("ch2if" , & self . ch2if ()) . field ("ch3if" , & self . ch3if ()) . field ("trgif" , & self . trgif ()) . field ("ch0of" , & self . ch0of ()) . field ("ch1of" , & self . ch1of ()) . field ("ch2of" , & self . ch2of ()) . field ("ch3of" , & self . ch3of ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ upif: {=bool:?}, ch0if: {=bool:?}, ch1if: {=bool:?}, ch2if: {=bool:?}, ch3if: {=bool:?}, trgif: {=bool:?}, ch0of: {=bool:?}, ch1of: {=bool:?}, ch2of: {=bool:?}, ch3of: {=bool:?} }}" , self . upif () , self . ch0if () , self . ch1if () , self . ch2if () , self . ch3if () , self . trgif () , self . ch0of () , self . ch1of () , self . ch2of () , self . ch3of ()) } } # [doc = "prescaler"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Psc (pub u32) ; impl Psc { # [doc = "Prescaler value"]
# [inline (always)]
pub const fn psc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Prescaler value"]
# [inline (always)]
pub fn set_psc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Psc { # [inline (always)]
fn default () -> Psc { Psc (0) } } impl core :: fmt :: Debug for Psc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Psc") . field ("psc" , & self . psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Psc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Psc {{ psc: {=u16:?} }}" , self . psc ()) } } # [doc = "slave mode control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Smcfg (pub u32) ; impl Smcfg { # [doc = "Slave mode selection"]
# [inline (always)]
pub const fn smc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "Slave mode selection"]
# [inline (always)]
pub fn set_smc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "Trigger selection"]
# [inline (always)]
pub const fn trgs (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Trigger selection"]
# [inline (always)]
pub fn set_trgs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Master/Slave mode"]
# [inline (always)]
pub const fn msm (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Master/Slave mode"]
# [inline (always)]
pub fn set_msm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "External trigger filter"]
# [inline (always)]
pub const fn etfc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "External trigger filter"]
# [inline (always)]
pub fn set_etfc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "External trigger prescaler"]
# [inline (always)]
pub const fn etpsc (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "External trigger prescaler"]
# [inline (always)]
pub fn set_etpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "External clock enable"]
# [inline (always)]
pub const fn smc1 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "External clock enable"]
# [inline (always)]
pub fn set_smc1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "External trigger polarity"]
# [inline (always)]
pub const fn etp (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "External trigger polarity"]
# [inline (always)]
pub fn set_etp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Smcfg { # [inline (always)]
fn default () -> Smcfg { Smcfg (0) } } impl core :: fmt :: Debug for Smcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Smcfg") . field ("smc" , & self . smc ()) . field ("trgs" , & self . trgs ()) . field ("msm" , & self . msm ()) . field ("etfc" , & self . etfc ()) . field ("etpsc" , & self . etpsc ()) . field ("smc1" , & self . smc1 ()) . field ("etp" , & self . etp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Smcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Smcfg {{ smc: {=u8:?}, trgs: {=u8:?}, msm: {=bool:?}, etfc: {=u8:?}, etpsc: {=u8:?}, smc1: {=bool:?}, etp: {=bool:?} }}" , self . smc () , self . trgs () , self . msm () , self . etfc () , self . etpsc () , self . smc1 () , self . etp ()) } } # [doc = "event generation register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Swevg (pub u32) ; impl Swevg { # [doc = "Update generation"]
# [inline (always)]
pub const fn upg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update generation"]
# [inline (always)]
pub fn set_upg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Capture/compare 0 generation"]
# [inline (always)]
pub const fn ch0g (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 0 generation"]
# [inline (always)]
pub fn set_ch0g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Capture/compare 1 generation"]
# [inline (always)]
pub const fn ch1g (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 1 generation"]
# [inline (always)]
pub fn set_ch1g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Capture/compare 2 generation"]
# [inline (always)]
pub const fn ch2g (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 2 generation"]
# [inline (always)]
pub fn set_ch2g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Capture/compare 3 generation"]
# [inline (always)]
pub const fn ch3g (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Capture/compare 3 generation"]
# [inline (always)]
pub fn set_ch3g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Trigger generation"]
# [inline (always)]
pub const fn trgg (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger generation"]
# [inline (always)]
pub fn set_trgg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } } impl Default for Swevg { # [inline (always)]
fn default () -> Swevg { Swevg (0) } } impl core :: fmt :: Debug for Swevg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Swevg") . field ("upg" , & self . upg ()) . field ("ch0g" , & self . ch0g ()) . field ("ch1g" , & self . ch1g ()) . field ("ch2g" , & self . ch2g ()) . field ("ch3g" , & self . ch3g ()) . field ("trgg" , & self . trgg ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Swevg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Swevg {{ upg: {=bool:?}, ch0g: {=bool:?}, ch1g: {=bool:?}, ch2g: {=bool:?}, ch3g: {=bool:?}, trgg: {=bool:?} }}" , self . upg () , self . ch0g () , self . ch1g () , self . ch2g () , self . ch3g () , self . trgg ()) } } }