#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Trigger selection controller"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Trigsel { ptr : * mut u8 } unsafe impl Send for Trigsel { } unsafe impl Sync for Trigsel { } impl Trigsel { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Trigger selection for EXTOUT register 0"]
# [inline (always)]
pub const fn extout_0 (self) -> crate :: common :: Reg < regs :: Extout0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Trigger selection for EXTOUT register 1"]
# [inline (always)]
pub const fn extout_1 (self) -> crate :: common :: Reg < regs :: Extout1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Trigger selection for EXTOUT register 2"]
# [inline (always)]
pub const fn extout_2 (self) -> crate :: common :: Reg < regs :: Extout2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Trigger selection for EXTOUT register 3"]
# [inline (always)]
pub const fn extout_3 (self) -> crate :: common :: Reg < regs :: Extout3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Trigger selection for ADC0 register"]
# [inline (always)]
pub const fn adc0 (self) -> crate :: common :: Reg < regs :: Adc0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Trigger selection for ADC1 register"]
# [inline (always)]
pub const fn adc1 (self) -> crate :: common :: Reg < regs :: Adc1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Trigger selection for ADC2 register"]
# [inline (always)]
pub const fn adc2 (self) -> crate :: common :: Reg < regs :: Adc2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Trigger selection for ADC3 register"]
# [inline (always)]
pub const fn adc3 (self) -> crate :: common :: Reg < regs :: Adc3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Trigger selection for TIMER0_BRKIN register"]
# [inline (always)]
pub const fn timer0brkin (self) -> crate :: common :: Reg < regs :: Timer0brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Trigger selection for TIMER7_BRKIN register"]
# [inline (always)]
pub const fn timer7brkin (self) -> crate :: common :: Reg < regs :: Timer7brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "Trigger selection for TIMER14_BRKIN register"]
# [inline (always)]
pub const fn timer14brkin (self) -> crate :: common :: Reg < regs :: Timer14brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "Trigger selection for TIMER15_BRKIN register"]
# [inline (always)]
pub const fn timer15brkin (self) -> crate :: common :: Reg < regs :: Timer15brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Trigger selection for TIMER16_BRKIN register"]
# [inline (always)]
pub const fn timer16brkin (self) -> crate :: common :: Reg < regs :: Timer16brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Trigger selection for TIMER19_BRKIN register"]
# [inline (always)]
pub const fn timer19brkin (self) -> crate :: common :: Reg < regs :: Timer19brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "Trigger selection for CAN0 register"]
# [inline (always)]
pub const fn can0 (self) -> crate :: common :: Reg < regs :: Can0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "Trigger selection for CAN1 register"]
# [inline (always)]
pub const fn can1 (self) -> crate :: common :: Reg < regs :: Can1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "Trigger selection for CAN2 register"]
# [inline (always)]
pub const fn can2 (self) -> crate :: common :: Reg < regs :: Can2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "Trigger selection for TIMER0_ETI register"]
# [inline (always)]
pub const fn timer0eti (self) -> crate :: common :: Reg < regs :: Timer0eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x50usize) as _) } } # [doc = "Trigger selection for TIMER1_ETI register"]
# [inline (always)]
pub const fn timer1eti (self) -> crate :: common :: Reg < regs :: Timer1eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize) as _) } } # [doc = "Trigger selection for TIMER2_ETI register"]
# [inline (always)]
pub const fn timer2eti (self) -> crate :: common :: Reg < regs :: Timer2eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x58usize) as _) } } # [doc = "Trigger selection for TIMER3_ETI register"]
# [inline (always)]
pub const fn timer3eti (self) -> crate :: common :: Reg < regs :: Timer3eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x5cusize) as _) } } # [doc = "Trigger selection for TIMER4_ETI register"]
# [inline (always)]
pub const fn timer4eti (self) -> crate :: common :: Reg < regs :: Timer4eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x60usize) as _) } } # [doc = "Trigger selection for TIMER7_ETI register"]
# [inline (always)]
pub const fn timer7eti (self) -> crate :: common :: Reg < regs :: Timer7eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x64usize) as _) } } # [doc = "Trigger selection for TIMER19_ETI register"]
# [inline (always)]
pub const fn timer19eti (self) -> crate :: common :: Reg < regs :: Timer19eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x68usize) as _) } } # [doc = "Trigger selection for HPDF_ITRG register"]
# [inline (always)]
pub const fn hpdf (self) -> crate :: common :: Reg < regs :: Hpdf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x6cusize) as _) } } # [doc = "Trigger selection for TIMER0_ITI14 register"]
# [inline (always)]
pub const fn timer0iti14 (self) -> crate :: common :: Reg < regs :: Timer0iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x70usize) as _) } } # [doc = "Trigger selection for TIMER1_ITI14 register"]
# [inline (always)]
pub const fn timer1iti14 (self) -> crate :: common :: Reg < regs :: Timer1iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x74usize) as _) } } # [doc = "Trigger selection for TIMER2_ITI14 register"]
# [inline (always)]
pub const fn timer2iti14 (self) -> crate :: common :: Reg < regs :: Timer2iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x78usize) as _) } } # [doc = "Trigger selection for TIMER3_ITI14 register"]
# [inline (always)]
pub const fn timer3iti14 (self) -> crate :: common :: Reg < regs :: Timer3iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x7cusize) as _) } } # [doc = "Trigger selection for TIMER4_ITI14 register"]
# [inline (always)]
pub const fn timer4iti14 (self) -> crate :: common :: Reg < regs :: Timer4iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x80usize) as _) } } # [doc = "Trigger selection for TIMER7_ITI14 register"]
# [inline (always)]
pub const fn timer7iti14 (self) -> crate :: common :: Reg < regs :: Timer7iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x84usize) as _) } } # [doc = "Trigger selection for TIMER14_ITI14 register"]
# [inline (always)]
pub const fn timer14iti14 (self) -> crate :: common :: Reg < regs :: Timer14iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x88usize) as _) } } # [doc = "Trigger selection for TIMER19_ITI14 register"]
# [inline (always)]
pub const fn timer19iti14 (self) -> crate :: common :: Reg < regs :: Timer19iti14 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x8cusize) as _) } } # [doc = "Trigger selection for DAC0 register"]
# [inline (always)]
pub const fn dac0 (self) -> crate :: common :: Reg < regs :: Dac0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x90usize) as _) } } # [doc = "Trigger selection for DAC1 register"]
# [inline (always)]
pub const fn dac1 (self) -> crate :: common :: Reg < regs :: Dac1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x94usize) as _) } } # [doc = "Trigger selection for DAC2 register"]
# [inline (always)]
pub const fn dac2 (self) -> crate :: common :: Reg < regs :: Dac2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x98usize) as _) } } # [doc = "Trigger selection for DAC3 register"]
# [inline (always)]
pub const fn dac3 (self) -> crate :: common :: Reg < regs :: Dac3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x9cusize) as _) } } # [doc = "Trigger selection for DAC0 extended register"]
# [inline (always)]
pub const fn extdac0 (self) -> crate :: common :: Reg < regs :: Extdac0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xa0usize) as _) } } # [doc = "Trigger selection for DAC1 extended register"]
# [inline (always)]
pub const fn extdac1 (self) -> crate :: common :: Reg < regs :: Extdac1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xa4usize) as _) } } # [doc = "Trigger selection for DAC2 extended register"]
# [inline (always)]
pub const fn extdac2 (self) -> crate :: common :: Reg < regs :: Extdac2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xa8usize) as _) } } # [doc = "Trigger selection for DAC3 extended register"]
# [inline (always)]
pub const fn extdac3 (self) -> crate :: common :: Reg < regs :: Extdac3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xacusize) as _) } } # [doc = "Trigger selection for CLA register 0"]
# [inline (always)]
pub const fn cla_0 (self) -> crate :: common :: Reg < regs :: Cla0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xb0usize) as _) } } # [doc = "Trigger selection for CLA register 1"]
# [inline (always)]
pub const fn cla_1 (self) -> crate :: common :: Reg < regs :: Cla1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xb4usize) as _) } } # [doc = "Trigger selection for CLA register 2"]
# [inline (always)]
pub const fn cla_2 (self) -> crate :: common :: Reg < regs :: Cla2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xb8usize) as _) } } # [doc = "Trigger selection for CLA register 3"]
# [inline (always)]
pub const fn cla_3 (self) -> crate :: common :: Reg < regs :: Cla3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xbcusize) as _) } } # [doc = "Trigger selection for CLA register 4"]
# [inline (always)]
pub const fn cla_4 (self) -> crate :: common :: Reg < regs :: Cla4 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xc0usize) as _) } } } pub mod regs { # [doc = "Trigger selection for ADC0 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc0 (pub u32) ; impl Adc0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc0 { # [inline (always)]
fn default () -> Adc0 { Adc0 (0) } } impl core :: fmt :: Debug for Adc0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc0") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc0 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for ADC1 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc1 (pub u32) ; impl Adc1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc1 { # [inline (always)]
fn default () -> Adc1 { Adc1 (0) } } impl core :: fmt :: Debug for Adc1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc1") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc1 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for ADC2 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc2 (pub u32) ; impl Adc2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc2 { # [inline (always)]
fn default () -> Adc2 { Adc2 (0) } } impl core :: fmt :: Debug for Adc2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc2") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc2 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for ADC3 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc3 (pub u32) ; impl Adc3 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc3 { # [inline (always)]
fn default () -> Adc3 { Adc3 (0) } } impl core :: fmt :: Debug for Adc3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc3") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc3 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for CAN0 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Can0 (pub u32) ; impl Can0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Can0 { # [inline (always)]
fn default () -> Can0 { Can0 (0) } } impl core :: fmt :: Debug for Can0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Can0") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Can0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Can0 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for CAN1 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Can1 (pub u32) ; impl Can1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Can1 { # [inline (always)]
fn default () -> Can1 { Can1 (0) } } impl core :: fmt :: Debug for Can1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Can1") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Can1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Can1 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for CAN2 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Can2 (pub u32) ; impl Can2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Can2 { # [inline (always)]
fn default () -> Can2 { Can2 (0) } } impl core :: fmt :: Debug for Can2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Can2") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Can2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Can2 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for CLA register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cla0 (pub u32) ; impl Cla0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cla0 { # [inline (always)]
fn default () -> Cla0 { Cla0 (0) } } impl core :: fmt :: Debug for Cla0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cla0") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cla0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cla0 {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for CLA register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cla1 (pub u32) ; impl Cla1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cla1 { # [inline (always)]
fn default () -> Cla1 { Cla1 (0) } } impl core :: fmt :: Debug for Cla1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cla1") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cla1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cla1 {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for CLA register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cla2 (pub u32) ; impl Cla2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cla2 { # [inline (always)]
fn default () -> Cla2 { Cla2 (0) } } impl core :: fmt :: Debug for Cla2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cla2") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cla2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cla2 {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for CLA register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cla3 (pub u32) ; impl Cla3 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cla3 { # [inline (always)]
fn default () -> Cla3 { Cla3 (0) } } impl core :: fmt :: Debug for Cla3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cla3") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cla3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cla3 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for CLA register 4"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cla4 (pub u32) ; impl Cla4 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cla4 { # [inline (always)]
fn default () -> Cla4 { Cla4 (0) } } impl core :: fmt :: Debug for Cla4 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cla4") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cla4 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cla4 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for DAC0 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dac0 (pub u32) ; impl Dac0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Dac0 { # [inline (always)]
fn default () -> Dac0 { Dac0 (0) } } impl core :: fmt :: Debug for Dac0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dac0") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dac0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dac0 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC1 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dac1 (pub u32) ; impl Dac1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Dac1 { # [inline (always)]
fn default () -> Dac1 { Dac1 (0) } } impl core :: fmt :: Debug for Dac1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dac1") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dac1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dac1 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC2 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dac2 (pub u32) ; impl Dac2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Dac2 { # [inline (always)]
fn default () -> Dac2 { Dac2 (0) } } impl core :: fmt :: Debug for Dac2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dac2") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dac2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dac2 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC3 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dac3 (pub u32) ; impl Dac3 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Dac3 { # [inline (always)]
fn default () -> Dac3 { Dac3 (0) } } impl core :: fmt :: Debug for Dac3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dac3") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dac3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dac3 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC0 extended register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extdac0 (pub u32) ; impl Extdac0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extdac0 { # [inline (always)]
fn default () -> Extdac0 { Extdac0 (0) } } impl core :: fmt :: Debug for Extdac0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extdac0") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extdac0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extdac0 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC1 extended register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extdac1 (pub u32) ; impl Extdac1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extdac1 { # [inline (always)]
fn default () -> Extdac1 { Extdac1 (0) } } impl core :: fmt :: Debug for Extdac1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extdac1") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extdac1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extdac1 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC2 extended register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extdac2 (pub u32) ; impl Extdac2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extdac2 { # [inline (always)]
fn default () -> Extdac2 { Extdac2 (0) } } impl core :: fmt :: Debug for Extdac2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extdac2") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extdac2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extdac2 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for DAC3 extended register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extdac3 (pub u32) ; impl Extdac3 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extdac3 { # [inline (always)]
fn default () -> Extdac3 { Extdac3 (0) } } impl core :: fmt :: Debug for Extdac3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extdac3") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extdac3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extdac3 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout0 (pub u32) ; impl Extout0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout0 { # [inline (always)]
fn default () -> Extout0 { Extout0 (0) } } impl core :: fmt :: Debug for Extout0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout0") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout0 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout1 (pub u32) ; impl Extout1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout1 { # [inline (always)]
fn default () -> Extout1 { Extout1 (0) } } impl core :: fmt :: Debug for Extout1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout1") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout1 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout2 (pub u32) ; impl Extout2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout2 { # [inline (always)]
fn default () -> Extout2 { Extout2 (0) } } impl core :: fmt :: Debug for Extout2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout2") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout2 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout3 (pub u32) ; impl Extout3 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout3 { # [inline (always)]
fn default () -> Extout3 { Extout3 (0) } } impl core :: fmt :: Debug for Extout3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout3") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout3 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for HPDF_ITRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hpdf (pub u32) ; impl Hpdf { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Hpdf { # [inline (always)]
fn default () -> Hpdf { Hpdf (0) } } impl core :: fmt :: Debug for Hpdf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hpdf") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hpdf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hpdf {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER0_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer0brkin (pub u32) ; impl Timer0brkin { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer0brkin { # [inline (always)]
fn default () -> Timer0brkin { Timer0brkin (0) } } impl core :: fmt :: Debug for Timer0brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer0brkin") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer0brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer0brkin {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for TIMER0_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer0eti (pub u32) ; impl Timer0eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer0eti { # [inline (always)]
fn default () -> Timer0eti { Timer0eti (0) } } impl core :: fmt :: Debug for Timer0eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer0eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer0eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer0eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER0_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer0iti14 (pub u32) ; impl Timer0iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer0iti14 { # [inline (always)]
fn default () -> Timer0iti14 { Timer0iti14 (0) } } impl core :: fmt :: Debug for Timer0iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer0iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer0iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer0iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER14_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer14brkin (pub u32) ; impl Timer14brkin { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer14brkin { # [inline (always)]
fn default () -> Timer14brkin { Timer14brkin (0) } } impl core :: fmt :: Debug for Timer14brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer14brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer14brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer14brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER14_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer14iti14 (pub u32) ; impl Timer14iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer14iti14 { # [inline (always)]
fn default () -> Timer14iti14 { Timer14iti14 (0) } } impl core :: fmt :: Debug for Timer14iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer14iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer14iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer14iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER15_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer15brkin (pub u32) ; impl Timer15brkin { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer15brkin { # [inline (always)]
fn default () -> Timer15brkin { Timer15brkin (0) } } impl core :: fmt :: Debug for Timer15brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer15brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer15brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer15brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER16_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer16brkin (pub u32) ; impl Timer16brkin { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer16brkin { # [inline (always)]
fn default () -> Timer16brkin { Timer16brkin (0) } } impl core :: fmt :: Debug for Timer16brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer16brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer16brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer16brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER19_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer19brkin (pub u32) ; impl Timer19brkin { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer19brkin { # [inline (always)]
fn default () -> Timer19brkin { Timer19brkin (0) } } impl core :: fmt :: Debug for Timer19brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer19brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer19brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer19brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER19_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer19eti (pub u32) ; impl Timer19eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer19eti { # [inline (always)]
fn default () -> Timer19eti { Timer19eti (0) } } impl core :: fmt :: Debug for Timer19eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer19eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer19eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer19eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER19_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer19iti14 (pub u32) ; impl Timer19iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer19iti14 { # [inline (always)]
fn default () -> Timer19iti14 { Timer19iti14 (0) } } impl core :: fmt :: Debug for Timer19iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer19iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer19iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer19iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER1_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer1eti (pub u32) ; impl Timer1eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer1eti { # [inline (always)]
fn default () -> Timer1eti { Timer1eti (0) } } impl core :: fmt :: Debug for Timer1eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer1eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer1eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer1eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER1_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer1iti14 (pub u32) ; impl Timer1iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer1iti14 { # [inline (always)]
fn default () -> Timer1iti14 { Timer1iti14 (0) } } impl core :: fmt :: Debug for Timer1iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer1iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer1iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer1iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER2_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer2eti (pub u32) ; impl Timer2eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer2eti { # [inline (always)]
fn default () -> Timer2eti { Timer2eti (0) } } impl core :: fmt :: Debug for Timer2eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer2eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer2eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer2eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER2_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer2iti14 (pub u32) ; impl Timer2iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer2iti14 { # [inline (always)]
fn default () -> Timer2iti14 { Timer2iti14 (0) } } impl core :: fmt :: Debug for Timer2iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer2iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer2iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer2iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER3_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer3eti (pub u32) ; impl Timer3eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer3eti { # [inline (always)]
fn default () -> Timer3eti { Timer3eti (0) } } impl core :: fmt :: Debug for Timer3eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer3eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer3eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer3eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER3_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer3iti14 (pub u32) ; impl Timer3iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer3iti14 { # [inline (always)]
fn default () -> Timer3iti14 { Timer3iti14 (0) } } impl core :: fmt :: Debug for Timer3iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer3iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer3iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer3iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER4_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer4eti (pub u32) ; impl Timer4eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer4eti { # [inline (always)]
fn default () -> Timer4eti { Timer4eti (0) } } impl core :: fmt :: Debug for Timer4eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer4eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer4eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer4eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER4_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer4iti14 (pub u32) ; impl Timer4iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer4iti14 { # [inline (always)]
fn default () -> Timer4iti14 { Timer4iti14 (0) } } impl core :: fmt :: Debug for Timer4iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer4iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer4iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer4iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER7_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer7brkin (pub u32) ; impl Timer7brkin { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output2"]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer7brkin { # [inline (always)]
fn default () -> Timer7brkin { Timer7brkin (0) } } impl core :: fmt :: Debug for Timer7brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer7brkin") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer7brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer7brkin {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for TIMER7_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer7eti (pub u32) ; impl Timer7eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer7eti { # [inline (always)]
fn default () -> Timer7eti { Timer7eti (0) } } impl core :: fmt :: Debug for Timer7eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer7eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer7eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer7eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER7_ITI14 register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer7iti14 (pub u32) ; impl Timer7iti14 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock"]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer7iti14 { # [inline (always)]
fn default () -> Timer7iti14 { Timer7iti14 (0) } } impl core :: fmt :: Debug for Timer7iti14 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer7iti14") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer7iti14 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer7iti14 {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } }