#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Flash memory controller"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Trigsel { ptr : * mut u8 } unsafe impl Send for Trigsel { } unsafe impl Sync for Trigsel { } impl Trigsel { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Trigger selection for EXTOUT register 0"]
# [inline (always)]
pub const fn extout_0 (self) -> crate :: common :: Reg < regs :: Extout0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Trigger selection for EXTOUT register 1"]
# [inline (always)]
pub const fn extout_1 (self) -> crate :: common :: Reg < regs :: Extout1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Trigger selection for EXTOUT register 2"]
# [inline (always)]
pub const fn extout_2 (self) -> crate :: common :: Reg < regs :: Extout2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Trigger selection for EXTOUT register 3"]
# [inline (always)]
pub const fn extout_3 (self) -> crate :: common :: Reg < regs :: Extout3 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Trigger selection for TIMER0_ITI register"]
# [inline (always)]
pub const fn timer0eti (self) -> crate :: common :: Reg < regs :: Timer0eti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Trigger selection for TIMER1_ETI register"]
# [inline (always)]
pub const fn timer1iti (self) -> crate :: common :: Reg < regs :: Timer1iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Trigger selection for TIMER2_ITI register"]
# [inline (always)]
pub const fn timer2iti (self) -> crate :: common :: Reg < regs :: Timer2iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Trigger selection for TIMER3_ITI register"]
# [inline (always)]
pub const fn timer3iti (self) -> crate :: common :: Reg < regs :: Timer3iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Trigger selection for TIMER4_ITI register"]
# [inline (always)]
pub const fn timer4iti (self) -> crate :: common :: Reg < regs :: Timer4iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Trigger selection for TIMER7_ITI register"]
# [inline (always)]
pub const fn timer7iti (self) -> crate :: common :: Reg < regs :: Timer7iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Trigger selection for TIMER15_ITI register"]
# [inline (always)]
pub const fn timer15iti (self) -> crate :: common :: Reg < regs :: Timer15iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Trigger selection for TIMER16_ITI register"]
# [inline (always)]
pub const fn timer16iti (self) -> crate :: common :: Reg < regs :: Timer16iti , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "Trigger selection for DAC register"]
# [inline (always)]
pub const fn dac (self) -> crate :: common :: Reg < regs :: Dac , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "Trigger selection for ADC0_ROUTRG register"]
# [inline (always)]
pub const fn adc0_routrg (self) -> crate :: common :: Reg < regs :: Adc0Routrg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Trigger selection for ADC0_INSTRG register"]
# [inline (always)]
pub const fn adc0_instrg (self) -> crate :: common :: Reg < regs :: Adc0Instrg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Trigger selection for ADC1_ROUTRG register"]
# [inline (always)]
pub const fn adc1_routrg (self) -> crate :: common :: Reg < regs :: Adc1Routrg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "Trigger selection for ADC1_INSTRG register"]
# [inline (always)]
pub const fn adc1_instrg (self) -> crate :: common :: Reg < regs :: Adc1Instrg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "Trigger selection for ADC2_ROUTRG register"]
# [inline (always)]
pub const fn adc2_routrg (self) -> crate :: common :: Reg < regs :: Adc2Routrg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "Trigger selection for ADC2_INSTRG register"]
# [inline (always)]
pub const fn adc2_instrg (self) -> crate :: common :: Reg < regs :: Adc2Instrg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "Trigger selection for TIMER0_BRKIN register"]
# [inline (always)]
pub const fn timer0brkin (self) -> crate :: common :: Reg < regs :: Timer0brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x50usize) as _) } } # [doc = "Trigger selection for TIMER0_CHBRKIN register"]
# [inline (always)]
pub const fn timer0chbrkin (self) -> crate :: common :: Reg < regs :: Timer0chbrkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize) as _) } } # [doc = "Trigger selection for TIMER7_BRKIN register"]
# [inline (always)]
pub const fn timer7brkin (self) -> crate :: common :: Reg < regs :: Timer7brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x58usize) as _) } } # [doc = "Trigger selection for TIMER7_CHBRKIN register"]
# [inline (always)]
pub const fn timer7chbrkin (self) -> crate :: common :: Reg < regs :: Timer7chbrkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x5cusize) as _) } } # [doc = "Trigger selection for TIMER15_BRKIN register"]
# [inline (always)]
pub const fn timer15brkin (self) -> crate :: common :: Reg < regs :: Timer15brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x60usize) as _) } } # [doc = "Trigger selection for TIMER16_BRKIN register"]
# [inline (always)]
pub const fn timer16brkin (self) -> crate :: common :: Reg < regs :: Timer16brkin , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x64usize) as _) } } } pub mod regs { # [doc = "Trigger selection for ADC0_INSTRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc0Instrg (pub u32) ; impl Adc0Instrg { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc0Instrg { # [inline (always)]
fn default () -> Adc0Instrg { Adc0Instrg (0) } } impl core :: fmt :: Debug for Adc0Instrg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc0Instrg") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc0Instrg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc0Instrg {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for ADC0_ROUTRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc0Routrg (pub u32) ; impl Adc0Routrg { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc0Routrg { # [inline (always)]
fn default () -> Adc0Routrg { Adc0Routrg (0) } } impl core :: fmt :: Debug for Adc0Routrg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc0Routrg") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc0Routrg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc0Routrg {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for ADC1_INSTRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc1Instrg (pub u32) ; impl Adc1Instrg { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc1Instrg { # [inline (always)]
fn default () -> Adc1Instrg { Adc1Instrg (0) } } impl core :: fmt :: Debug for Adc1Instrg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc1Instrg") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc1Instrg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc1Instrg {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for ADC1_ROUTRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc1Routrg (pub u32) ; impl Adc1Routrg { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc1Routrg { # [inline (always)]
fn default () -> Adc1Routrg { Adc1Routrg (0) } } impl core :: fmt :: Debug for Adc1Routrg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc1Routrg") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc1Routrg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc1Routrg {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for ADC2_INSTRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc2Instrg (pub u32) ; impl Adc2Instrg { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc2Instrg { # [inline (always)]
fn default () -> Adc2Instrg { Adc2Instrg (0) } } impl core :: fmt :: Debug for Adc2Instrg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc2Instrg") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc2Instrg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc2Instrg {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for ADC2_ROUTRG register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adc2Routrg (pub u32) ; impl Adc2Routrg { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Adc2Routrg { # [inline (always)]
fn default () -> Adc2Routrg { Adc2Routrg (0) } } impl core :: fmt :: Debug for Adc2Routrg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adc2Routrg") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adc2Routrg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adc2Routrg {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for DAC register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dac (pub u32) ; impl Dac { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Dac { # [inline (always)]
fn default () -> Dac { Dac (0) } } impl core :: fmt :: Debug for Dac { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dac") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dac { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dac {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout0 (pub u32) ; impl Extout0 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout0 { # [inline (always)]
fn default () -> Extout0 { Extout0 (0) } } impl core :: fmt :: Debug for Extout0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout0") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout0 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout1 (pub u32) ; impl Extout1 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout1 { # [inline (always)]
fn default () -> Extout1 { Extout1 (0) } } impl core :: fmt :: Debug for Extout1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout1") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout1 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout2 (pub u32) ; impl Extout2 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout2 { # [inline (always)]
fn default () -> Extout2 { Extout2 (0) } } impl core :: fmt :: Debug for Extout2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout2") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout2 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for EXTOUT register 3"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Extout3 (pub u32) ; impl Extout3 { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output1"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Extout3 { # [inline (always)]
fn default () -> Extout3 { Extout3 (0) } } impl core :: fmt :: Debug for Extout3 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Extout3") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Extout3 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Extout3 {{ insel0: {=u8:?}, insel1: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . lk ()) } } # [doc = "Trigger selection for TIMER0_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer0brkin (pub u32) ; impl Timer0brkin { # [doc = "Trigger input source selection for TIMER0_BRKIN"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER0_BRKIN"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer0brkin { # [inline (always)]
fn default () -> Timer0brkin { Timer0brkin (0) } } impl core :: fmt :: Debug for Timer0brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer0brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer0brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer0brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER0_CHBRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer0chbrkin (pub u32) ; impl Timer0chbrkin { # [doc = "Trigger input source selection for TIMER0_CH0BRKIN"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER0_CH0BRKIN"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for TIMER0_CH1BRKIN"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER0_CH1BRKIN"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for TIMER0_CH2BRKIN."]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER0_CH2BRKIN."]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer0chbrkin { # [inline (always)]
fn default () -> Timer0chbrkin { Timer0chbrkin (0) } } impl core :: fmt :: Debug for Timer0chbrkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer0chbrkin") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer0chbrkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer0chbrkin {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for TIMER0_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer0eti (pub u32) ; impl Timer0eti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer0eti { # [inline (always)]
fn default () -> Timer0eti { Timer0eti (0) } } impl core :: fmt :: Debug for Timer0eti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer0eti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer0eti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer0eti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER15_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer15brkin (pub u32) ; impl Timer15brkin { # [doc = "Trigger input source selection for TIMER15_BRKIN."]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER15_BRKIN."]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer15brkin { # [inline (always)]
fn default () -> Timer15brkin { Timer15brkin (0) } } impl core :: fmt :: Debug for Timer15brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer15brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer15brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer15brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER15_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer15iti (pub u32) ; impl Timer15iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer15iti { # [inline (always)]
fn default () -> Timer15iti { Timer15iti (0) } } impl core :: fmt :: Debug for Timer15iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer15iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer15iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer15iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER16_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer16brkin (pub u32) ; impl Timer16brkin { # [doc = "Trigger input source selection for TIMER16_BRKIN"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER16_BRKIN"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer16brkin { # [inline (always)]
fn default () -> Timer16brkin { Timer16brkin (0) } } impl core :: fmt :: Debug for Timer16brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer16brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer16brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer16brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER16_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer16iti (pub u32) ; impl Timer16iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer16iti { # [inline (always)]
fn default () -> Timer16iti { Timer16iti (0) } } impl core :: fmt :: Debug for Timer16iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer16iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer16iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer16iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER1_ETI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer1iti (pub u32) ; impl Timer1iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer1iti { # [inline (always)]
fn default () -> Timer1iti { Timer1iti (0) } } impl core :: fmt :: Debug for Timer1iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer1iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer1iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer1iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER2_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer2iti (pub u32) ; impl Timer2iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer2iti { # [inline (always)]
fn default () -> Timer2iti { Timer2iti (0) } } impl core :: fmt :: Debug for Timer2iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer2iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer2iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer2iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER3_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer3iti (pub u32) ; impl Timer3iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer3iti { # [inline (always)]
fn default () -> Timer3iti { Timer3iti (0) } } impl core :: fmt :: Debug for Timer3iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer3iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer3iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer3iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER4_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer4iti (pub u32) ; impl Timer4iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer4iti { # [inline (always)]
fn default () -> Timer4iti { Timer4iti (0) } } impl core :: fmt :: Debug for Timer4iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer4iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer4iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer4iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER7_BRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer7brkin (pub u32) ; impl Timer7brkin { # [doc = "Trigger input source selection for TIMER7_BRKIN"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER7_BRKIN"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer7brkin { # [inline (always)]
fn default () -> Timer7brkin { Timer7brkin (0) } } impl core :: fmt :: Debug for Timer7brkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer7brkin") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer7brkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer7brkin {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } # [doc = "Trigger selection for TIMER7_CHBRKIN register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer7chbrkin (pub u32) ; impl Timer7chbrkin { # [doc = "Trigger input source selection for TIMER7_CH0BRKIN"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER7_CH0BRKIN"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Trigger input source selection for TIMER7_CH1BRKIN"]
# [inline (always)]
pub const fn insel1 (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER7_CH1BRKIN"]
# [inline (always)]
pub fn set_insel1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } # [doc = "Trigger input source selection for TIMER7_CH2BRKIN."]
# [inline (always)]
pub const fn insel2 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for TIMER7_CH2BRKIN."]
# [inline (always)]
pub fn set_insel2 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer7chbrkin { # [inline (always)]
fn default () -> Timer7chbrkin { Timer7chbrkin (0) } } impl core :: fmt :: Debug for Timer7chbrkin { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer7chbrkin") . field ("insel0" , & self . insel0 ()) . field ("insel1" , & self . insel1 ()) . field ("insel2" , & self . insel2 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer7chbrkin { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer7chbrkin {{ insel0: {=u8:?}, insel1: {=u8:?}, insel2: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . insel1 () , self . insel2 () , self . lk ()) } } # [doc = "Trigger selection for TIMER7_ITI register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer7iti (pub u32) ; impl Timer7iti { # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub const fn insel0 (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Trigger input source selection for output0"]
# [inline (always)]
pub fn set_insel0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub const fn lk (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "TRIGSEL register lock."]
# [inline (always)]
pub fn set_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Timer7iti { # [inline (always)]
fn default () -> Timer7iti { Timer7iti (0) } } impl core :: fmt :: Debug for Timer7iti { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Timer7iti") . field ("insel0" , & self . insel0 ()) . field ("lk" , & self . lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Timer7iti { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Timer7iti {{ insel0: {=u8:?}, lk: {=bool:?} }}" , self . insel0 () , self . lk ()) } } }