#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Touch sensing Interface"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tsi { ptr : * mut u8 } unsafe impl Send for Tsi { } unsafe impl Sync for Tsi { } impl Tsi { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "interrupt enable register"]
# [inline (always)]
pub const fn inten (self) -> crate :: common :: Reg < regs :: Inten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "interrupt flag clear register"]
# [inline (always)]
pub const fn intc (self) -> crate :: common :: Reg < regs :: Intc , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "interrupt flag register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Pin hysteresis mode register"]
# [inline (always)]
pub const fn phm (self) -> crate :: common :: Reg < regs :: Phm , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "I/O analog switch register"]
# [inline (always)]
pub const fn asw (self) -> crate :: common :: Reg < regs :: Asw , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "I/O sample configuration register"]
# [inline (always)]
pub const fn sampcfg (self) -> crate :: common :: Reg < regs :: Sampcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "I/O channel configuration register"]
# [inline (always)]
pub const fn chcfg (self) -> crate :: common :: Reg < regs :: Chcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "I/O group control register"]
# [inline (always)]
pub const fn gctl (self) -> crate :: common :: Reg < regs :: Gctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "I/O group x cycle number register"]
# [inline (always)]
pub const fn g0cycn (self) -> crate :: common :: Reg < regs :: G0cycn , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "I/O group x cycle number register"]
# [inline (always)]
pub const fn g1cycn (self) -> crate :: common :: Reg < regs :: G1cycn , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "I/O group x cycle number register"]
# [inline (always)]
pub const fn g2cycn (self) -> crate :: common :: Reg < regs :: G2cycn , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } } pub mod regs { # [doc = "I/O analog switch register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Asw (pub u32) ; impl Asw { # [doc = "G0P0 analog switch enable"]
# [inline (always)]
pub const fn g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "G0P0 analog switch enable"]
# [inline (always)]
pub fn set_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "G0P1 analog switch enable"]
# [inline (always)]
pub const fn g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "G0P1 analog switch enable"]
# [inline (always)]
pub fn set_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "G0P2 analog switch enable"]
# [inline (always)]
pub const fn g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "G0P2 analog switch enable"]
# [inline (always)]
pub fn set_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "G0P3 analog switch enable"]
# [inline (always)]
pub const fn g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "G0P3 analog switch enable"]
# [inline (always)]
pub fn set_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "G1P0 analog switch enable"]
# [inline (always)]
pub const fn g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "G1P0 analog switch enable"]
# [inline (always)]
pub fn set_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "G1P1 analog switch enable"]
# [inline (always)]
pub const fn g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "G1P1 analog switch enable"]
# [inline (always)]
pub fn set_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "G1P2 analog switch enable"]
# [inline (always)]
pub const fn g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "G1P2 analog switch enable"]
# [inline (always)]
pub fn set_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "G1P3 analog switch enable"]
# [inline (always)]
pub const fn g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "G1P3 analog switch enable"]
# [inline (always)]
pub fn set_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "G2P0 analog switch enable"]
# [inline (always)]
pub const fn g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "G2P0 analog switch enable"]
# [inline (always)]
pub fn set_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "G2P1 analog switch enable"]
# [inline (always)]
pub const fn g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "G2P1 analog switch enable"]
# [inline (always)]
pub fn set_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "G2P2 analog switch enable"]
# [inline (always)]
pub const fn g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "G2P2 analog switch enable"]
# [inline (always)]
pub fn set_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "G2P3 analog switch enable"]
# [inline (always)]
pub const fn g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "G2P3 analog switch enable"]
# [inline (always)]
pub fn set_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } } impl Default for Asw { # [inline (always)]
fn default () -> Asw { Asw (0) } } impl core :: fmt :: Debug for Asw { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Asw") . field ("g0p0" , & self . g0p0 ()) . field ("g0p1" , & self . g0p1 ()) . field ("g0p2" , & self . g0p2 ()) . field ("g0p3" , & self . g0p3 ()) . field ("g1p0" , & self . g1p0 ()) . field ("g1p1" , & self . g1p1 ()) . field ("g1p2" , & self . g1p2 ()) . field ("g1p3" , & self . g1p3 ()) . field ("g2p0" , & self . g2p0 ()) . field ("g2p1" , & self . g2p1 ()) . field ("g2p2" , & self . g2p2 ()) . field ("g2p3" , & self . g2p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Asw { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Asw {{ g0p0: {=bool:?}, g0p1: {=bool:?}, g0p2: {=bool:?}, g0p3: {=bool:?}, g1p0: {=bool:?}, g1p1: {=bool:?}, g1p2: {=bool:?}, g1p3: {=bool:?}, g2p0: {=bool:?}, g2p1: {=bool:?}, g2p2: {=bool:?}, g2p3: {=bool:?} }}" , self . g0p0 () , self . g0p1 () , self . g0p2 () , self . g0p3 () , self . g1p0 () , self . g1p1 () , self . g1p2 () , self . g1p3 () , self . g2p0 () , self . g2p1 () , self . g2p2 () , self . g2p3 ()) } } # [doc = "I/O channel configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chcfg (pub u32) ; impl Chcfg { # [doc = "G0P0 channel mode"]
# [inline (always)]
pub const fn g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "G0P0 channel mode"]
# [inline (always)]
pub fn set_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "G0P1 channel mode"]
# [inline (always)]
pub const fn g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "G0P1 channel mode"]
# [inline (always)]
pub fn set_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "G0P2 channel mode"]
# [inline (always)]
pub const fn g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "G0P2 channel mode"]
# [inline (always)]
pub fn set_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "G0P3 channel mode"]
# [inline (always)]
pub const fn g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "G0P3 channel mode"]
# [inline (always)]
pub fn set_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "G1P0 channel mode"]
# [inline (always)]
pub const fn g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "G1P0 channel mode"]
# [inline (always)]
pub fn set_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "G1P1 channel mode"]
# [inline (always)]
pub const fn g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "G1P1 channel mode"]
# [inline (always)]
pub fn set_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "G1P2 channel mode"]
# [inline (always)]
pub const fn g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "G1P2 channel mode"]
# [inline (always)]
pub fn set_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "G1P3 channel mode"]
# [inline (always)]
pub const fn g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "G1P3 channel mode"]
# [inline (always)]
pub fn set_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "G2P0 channel mode"]
# [inline (always)]
pub const fn g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "G2P0 channel mode"]
# [inline (always)]
pub fn set_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "G2P1 channel mode"]
# [inline (always)]
pub const fn g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "G2P1 channel mode"]
# [inline (always)]
pub fn set_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "G2P2 channel mode"]
# [inline (always)]
pub const fn g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "G2P2 channel mode"]
# [inline (always)]
pub fn set_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "G2P3 channel mode"]
# [inline (always)]
pub const fn g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "G2P3 channel mode"]
# [inline (always)]
pub fn set_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } } impl Default for Chcfg { # [inline (always)]
fn default () -> Chcfg { Chcfg (0) } } impl core :: fmt :: Debug for Chcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chcfg") . field ("g0p0" , & self . g0p0 ()) . field ("g0p1" , & self . g0p1 ()) . field ("g0p2" , & self . g0p2 ()) . field ("g0p3" , & self . g0p3 ()) . field ("g1p0" , & self . g1p0 ()) . field ("g1p1" , & self . g1p1 ()) . field ("g1p2" , & self . g1p2 ()) . field ("g1p3" , & self . g1p3 ()) . field ("g2p0" , & self . g2p0 ()) . field ("g2p1" , & self . g2p1 ()) . field ("g2p2" , & self . g2p2 ()) . field ("g2p3" , & self . g2p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chcfg {{ g0p0: {=bool:?}, g0p1: {=bool:?}, g0p2: {=bool:?}, g0p3: {=bool:?}, g1p0: {=bool:?}, g1p1: {=bool:?}, g1p2: {=bool:?}, g1p3: {=bool:?}, g2p0: {=bool:?}, g2p1: {=bool:?}, g2p2: {=bool:?}, g2p3: {=bool:?} }}" , self . g0p0 () , self . g0p1 () , self . g0p2 () , self . g0p3 () , self . g1p0 () , self . g1p1 () , self . g1p2 () , self . g1p3 () , self . g2p0 () , self . g2p1 () , self . g2p2 () , self . g2p3 ()) } } # [doc = "control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Touch sensing controller enable"]
# [inline (always)]
pub const fn tsien (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Touch sensing controller enable"]
# [inline (always)]
pub fn set_tsien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Start a new acquisition"]
# [inline (always)]
pub const fn tsis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Start a new acquisition"]
# [inline (always)]
pub fn set_tsis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Trigger mode selection"]
# [inline (always)]
pub const fn trgmod (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Trigger mode selection"]
# [inline (always)]
pub fn set_trgmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Edge selection"]
# [inline (always)]
pub const fn egsel (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Edge selection"]
# [inline (always)]
pub fn set_egsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "I/O Default mode"]
# [inline (always)]
pub const fn pinmod (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "I/O Default mode"]
# [inline (always)]
pub fn set_pinmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Max count value"]
# [inline (always)]
pub const fn mcn (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x07 ; val as u8 } # [doc = "Max count value"]
# [inline (always)]
pub fn set_mcn (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 5usize)) | (((val as u32) & 0x07) << 5usize) ; } # [doc = "pulse generator prescaler"]
# [inline (always)]
pub const fn ctcdiv (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "pulse generator prescaler"]
# [inline (always)]
pub fn set_ctcdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Spread spectrum prescaler"]
# [inline (always)]
pub const fn ecdiv (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Spread spectrum prescaler"]
# [inline (always)]
pub fn set_ecdiv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Spread spectrum enable"]
# [inline (always)]
pub const fn ecen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Spread spectrum enable"]
# [inline (always)]
pub fn set_ecen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Spread spectrum deviation"]
# [inline (always)]
pub const fn ecdt (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x7f ; val as u8 } # [doc = "Spread spectrum deviation"]
# [inline (always)]
pub fn set_ecdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 17usize)) | (((val as u32) & 0x7f) << 17usize) ; } # [doc = "Charge transfer pulse low"]
# [inline (always)]
pub const fn ctdt (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [doc = "Charge transfer pulse low"]
# [inline (always)]
pub fn set_ctdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [doc = "Charge transfer pulse high"]
# [inline (always)]
pub const fn cdt (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x0f ; val as u8 } # [doc = "Charge transfer pulse high"]
# [inline (always)]
pub fn set_cdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("tsien" , & self . tsien ()) . field ("tsis" , & self . tsis ()) . field ("trgmod" , & self . trgmod ()) . field ("egsel" , & self . egsel ()) . field ("pinmod" , & self . pinmod ()) . field ("mcn" , & self . mcn ()) . field ("ctcdiv" , & self . ctcdiv ()) . field ("ecdiv" , & self . ecdiv ()) . field ("ecen" , & self . ecen ()) . field ("ecdt" , & self . ecdt ()) . field ("ctdt" , & self . ctdt ()) . field ("cdt" , & self . cdt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ tsien: {=bool:?}, tsis: {=bool:?}, trgmod: {=bool:?}, egsel: {=bool:?}, pinmod: {=bool:?}, mcn: {=u8:?}, ctcdiv: {=u8:?}, ecdiv: {=bool:?}, ecen: {=bool:?}, ecdt: {=u8:?}, ctdt: {=u8:?}, cdt: {=u8:?} }}" , self . tsien () , self . tsis () , self . trgmod () , self . egsel () , self . pinmod () , self . mcn () , self . ctcdiv () , self . ecdiv () , self . ecen () , self . ecdt () , self . ctdt () , self . cdt ()) } } # [doc = "I/O group x cycle number register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct G0cycn (pub u32) ; impl G0cycn { # [doc = "Cycle number"]
# [inline (always)]
pub const fn cycn (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x3fff ; val as u16 } # [doc = "Cycle number"]
# [inline (always)]
pub fn set_cycn (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x3fff << 0usize)) | (((val as u32) & 0x3fff) << 0usize) ; } } impl Default for G0cycn { # [inline (always)]
fn default () -> G0cycn { G0cycn (0) } } impl core :: fmt :: Debug for G0cycn { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("G0cycn") . field ("cycn" , & self . cycn ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for G0cycn { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "G0cycn {{ cycn: {=u16:?} }}" , self . cycn ()) } } # [doc = "I/O group x cycle number register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct G1cycn (pub u32) ; impl G1cycn { # [doc = "Cycle number"]
# [inline (always)]
pub const fn cycn (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x3fff ; val as u16 } # [doc = "Cycle number"]
# [inline (always)]
pub fn set_cycn (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x3fff << 0usize)) | (((val as u32) & 0x3fff) << 0usize) ; } } impl Default for G1cycn { # [inline (always)]
fn default () -> G1cycn { G1cycn (0) } } impl core :: fmt :: Debug for G1cycn { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("G1cycn") . field ("cycn" , & self . cycn ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for G1cycn { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "G1cycn {{ cycn: {=u16:?} }}" , self . cycn ()) } } # [doc = "I/O group x cycle number register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct G2cycn (pub u32) ; impl G2cycn { # [doc = "Cycle number"]
# [inline (always)]
pub const fn cycn (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x3fff ; val as u16 } # [doc = "Cycle number"]
# [inline (always)]
pub fn set_cycn (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x3fff << 0usize)) | (((val as u32) & 0x3fff) << 0usize) ; } } impl Default for G2cycn { # [inline (always)]
fn default () -> G2cycn { G2cycn (0) } } impl core :: fmt :: Debug for G2cycn { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("G2cycn") . field ("cycn" , & self . cycn ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for G2cycn { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "G2cycn {{ cycn: {=u16:?} }}" , self . cycn ()) } } # [doc = "I/O group control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gctl (pub u32) ; impl Gctl { # [doc = "Analog I/O group x enable"]
# [inline (always)]
pub const fn ge0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Analog I/O group x enable"]
# [inline (always)]
pub fn set_ge0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Analog I/O group x enable"]
# [inline (always)]
pub const fn ge1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Analog I/O group x enable"]
# [inline (always)]
pub fn set_ge1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Analog I/O group x enable"]
# [inline (always)]
pub const fn ge2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Analog I/O group x enable"]
# [inline (always)]
pub fn set_ge2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Analog I/O group x status"]
# [inline (always)]
pub const fn gc0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Analog I/O group x status"]
# [inline (always)]
pub fn set_gc0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Analog I/O group x status"]
# [inline (always)]
pub const fn gc1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Analog I/O group x status"]
# [inline (always)]
pub fn set_gc1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Analog I/O group x status"]
# [inline (always)]
pub const fn gc2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Analog I/O group x status"]
# [inline (always)]
pub fn set_gc2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } } impl Default for Gctl { # [inline (always)]
fn default () -> Gctl { Gctl (0) } } impl core :: fmt :: Debug for Gctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gctl") . field ("ge0" , & self . ge0 ()) . field ("ge1" , & self . ge1 ()) . field ("ge2" , & self . ge2 ()) . field ("gc0" , & self . gc0 ()) . field ("gc1" , & self . gc1 ()) . field ("gc2" , & self . gc2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gctl {{ ge0: {=bool:?}, ge1: {=bool:?}, ge2: {=bool:?}, gc0: {=bool:?}, gc1: {=bool:?}, gc2: {=bool:?} }}" , self . ge0 () , self . ge1 () , self . ge2 () , self . gc0 () , self . gc1 () , self . gc2 ()) } } # [doc = "interrupt flag clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intc (pub u32) ; impl Intc { # [doc = "Clear charge-transfer complete flag"]
# [inline (always)]
pub const fn cctcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Clear charge-transfer complete flag"]
# [inline (always)]
pub fn set_cctcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Clear max cycle number error"]
# [inline (always)]
pub const fn cmnerr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Clear max cycle number error"]
# [inline (always)]
pub fn set_cmnerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Intc { # [inline (always)]
fn default () -> Intc { Intc (0) } } impl core :: fmt :: Debug for Intc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intc") . field ("cctcf" , & self . cctcf ()) . field ("cmnerr" , & self . cmnerr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intc {{ cctcf: {=bool:?}, cmnerr: {=bool:?} }}" , self . cctcf () , self . cmnerr ()) } } # [doc = "interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Inten (pub u32) ; impl Inten { # [doc = "Charge-transfer complete flag Interrupt Enable"]
# [inline (always)]
pub const fn ctcfie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Charge-transfer complete flag Interrupt Enable"]
# [inline (always)]
pub fn set_ctcfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Max Cycle Number Error Interrupt Enable"]
# [inline (always)]
pub const fn mnerrie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Max Cycle Number Error Interrupt Enable"]
# [inline (always)]
pub fn set_mnerrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Inten { # [inline (always)]
fn default () -> Inten { Inten (0) } } impl core :: fmt :: Debug for Inten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Inten") . field ("ctcfie" , & self . ctcfie ()) . field ("mnerrie" , & self . mnerrie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Inten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Inten {{ ctcfie: {=bool:?}, mnerrie: {=bool:?} }}" , self . ctcfie () , self . mnerrie ()) } } # [doc = "interrupt flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "End of acquisition flag"]
# [inline (always)]
pub const fn ctcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "End of acquisition flag"]
# [inline (always)]
pub fn set_ctcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Max count error flag"]
# [inline (always)]
pub const fn mnerr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Max count error flag"]
# [inline (always)]
pub fn set_mnerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("ctcf" , & self . ctcf ()) . field ("mnerr" , & self . mnerr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ ctcf: {=bool:?}, mnerr: {=bool:?} }}" , self . ctcf () , self . mnerr ()) } } # [doc = "Pin hysteresis mode register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Phm (pub u32) ; impl Phm { # [doc = "G0P0 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "G0P0 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "G0P1 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "G0P1 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "G0P2 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "G0P2 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "G0P3 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "G0P3 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "G1P0 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "G1P0 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "G1P1 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "G1P1 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "G1P2 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "G1P2 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "G1P3 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "G1P3 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "G2P0 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "G2P0 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "G2P1 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "G2P1 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "G2P2 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "G2P2 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "G2P3 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub const fn g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "G2P3 Schmitt trigger hysteresis mode"]
# [inline (always)]
pub fn set_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } } impl Default for Phm { # [inline (always)]
fn default () -> Phm { Phm (0) } } impl core :: fmt :: Debug for Phm { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Phm") . field ("g0p0" , & self . g0p0 ()) . field ("g0p1" , & self . g0p1 ()) . field ("g0p2" , & self . g0p2 ()) . field ("g0p3" , & self . g0p3 ()) . field ("g1p0" , & self . g1p0 ()) . field ("g1p1" , & self . g1p1 ()) . field ("g1p2" , & self . g1p2 ()) . field ("g1p3" , & self . g1p3 ()) . field ("g2p0" , & self . g2p0 ()) . field ("g2p1" , & self . g2p1 ()) . field ("g2p2" , & self . g2p2 ()) . field ("g2p3" , & self . g2p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Phm { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Phm {{ g0p0: {=bool:?}, g0p1: {=bool:?}, g0p2: {=bool:?}, g0p3: {=bool:?}, g1p0: {=bool:?}, g1p1: {=bool:?}, g1p2: {=bool:?}, g1p3: {=bool:?}, g2p0: {=bool:?}, g2p1: {=bool:?}, g2p2: {=bool:?}, g2p3: {=bool:?} }}" , self . g0p0 () , self . g0p1 () , self . g0p2 () , self . g0p3 () , self . g1p0 () , self . g1p1 () , self . g1p2 () , self . g1p3 () , self . g2p0 () , self . g2p1 () , self . g2p2 () , self . g2p3 ()) } } # [doc = "I/O sample configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Sampcfg (pub u32) ; impl Sampcfg { # [doc = "G0P0 sampling mode"]
# [inline (always)]
pub const fn g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "G0P0 sampling mode"]
# [inline (always)]
pub fn set_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "G0P1 sampling mode"]
# [inline (always)]
pub const fn g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "G0P1 sampling mode"]
# [inline (always)]
pub fn set_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "G0P2 sampling mode"]
# [inline (always)]
pub const fn g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "G0P2 sampling mode"]
# [inline (always)]
pub fn set_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "G0P3 sampling mode"]
# [inline (always)]
pub const fn g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "G0P3 sampling mode"]
# [inline (always)]
pub fn set_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "G1P0 sampling mode"]
# [inline (always)]
pub const fn g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "G1P0 sampling mode"]
# [inline (always)]
pub fn set_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "G1P1 sampling mode"]
# [inline (always)]
pub const fn g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "G1P1 sampling mode"]
# [inline (always)]
pub fn set_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "G1P2 sampling mode"]
# [inline (always)]
pub const fn g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "G1P2 sampling mode"]
# [inline (always)]
pub fn set_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "G1P3 sampling mode"]
# [inline (always)]
pub const fn g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "G1P3 sampling mode"]
# [inline (always)]
pub fn set_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "G2P0 sampling mode"]
# [inline (always)]
pub const fn g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "G2P0 sampling mode"]
# [inline (always)]
pub fn set_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "G2P1 sampling mode"]
# [inline (always)]
pub const fn g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "G2P1 sampling mode"]
# [inline (always)]
pub fn set_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "G2P2 sampling mode"]
# [inline (always)]
pub const fn g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "G2P2 sampling mode"]
# [inline (always)]
pub fn set_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "G2P3 sampling mode"]
# [inline (always)]
pub const fn g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "G2P3 sampling mode"]
# [inline (always)]
pub fn set_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } } impl Default for Sampcfg { # [inline (always)]
fn default () -> Sampcfg { Sampcfg (0) } } impl core :: fmt :: Debug for Sampcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Sampcfg") . field ("g0p0" , & self . g0p0 ()) . field ("g0p1" , & self . g0p1 ()) . field ("g0p2" , & self . g0p2 ()) . field ("g0p3" , & self . g0p3 ()) . field ("g1p0" , & self . g1p0 ()) . field ("g1p1" , & self . g1p1 ()) . field ("g1p2" , & self . g1p2 ()) . field ("g1p3" , & self . g1p3 ()) . field ("g2p0" , & self . g2p0 ()) . field ("g2p1" , & self . g2p1 ()) . field ("g2p2" , & self . g2p2 ()) . field ("g2p3" , & self . g2p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Sampcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Sampcfg {{ g0p0: {=bool:?}, g0p1: {=bool:?}, g0p2: {=bool:?}, g0p3: {=bool:?}, g1p0: {=bool:?}, g1p1: {=bool:?}, g1p2: {=bool:?}, g1p3: {=bool:?}, g2p0: {=bool:?}, g2p1: {=bool:?}, g2p2: {=bool:?}, g2p3: {=bool:?} }}" , self . g0p0 () , self . g0p1 () , self . g0p2 () , self . g0p3 () , self . g1p0 () , self . g1p1 () , self . g1p2 () , self . g1p3 () , self . g2p0 () , self . g2p1 () , self . g2p2 () , self . g2p3 ()) } } }