#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tsi { ptr : * mut u8 } unsafe impl Send for Tsi { } unsafe impl Sync for Tsi { } impl Tsi { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn tsi_ctl (self) -> crate :: common :: Reg < regs :: TsiCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn tsi_inten (self) -> crate :: common :: Reg < regs :: TsiInten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn tsi_intc (self) -> crate :: common :: Reg < regs :: TsiIntc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn tsi_intf (self) -> crate :: common :: Reg < regs :: TsiIntf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn tsi_phm (self) -> crate :: common :: Reg < regs :: TsiPhm , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn tsi_asw (self) -> crate :: common :: Reg < regs :: TsiAsw , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn tsi_sampcfg (self) -> crate :: common :: Reg < regs :: TsiSampcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn tsi_chcfg (self) -> crate :: common :: Reg < regs :: TsiChcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn tsi_gctl (self) -> crate :: common :: Reg < regs :: TsiGctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn tsi_g0cycn (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn tsi_g1cycn (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn tsi_g2cycn (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn tsi_g3cycn (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn tsi_g4cycn (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn tsi_g5cycn (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x48usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiAsw (pub u32) ; impl TsiAsw { # [must_use]
# [inline (always)]
pub const fn tsi_asw_g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g3p0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g3p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g3p1 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g3p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g3p2 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g3p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g3p3 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g3p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g4p0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g4p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g4p1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g4p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g4p2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g4p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g4p3 (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g4p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g5p0 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g5p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g5p1 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g5p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g5p2 (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g5p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_asw_g5p3 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_asw_g5p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for TsiAsw { # [inline (always)]
fn default () -> TsiAsw { TsiAsw (0) } } impl core :: fmt :: Debug for TsiAsw { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiAsw") . field ("tsi_asw_g0p0" , & self . tsi_asw_g0p0 ()) . field ("tsi_asw_g0p1" , & self . tsi_asw_g0p1 ()) . field ("tsi_asw_g0p2" , & self . tsi_asw_g0p2 ()) . field ("tsi_asw_g0p3" , & self . tsi_asw_g0p3 ()) . field ("tsi_asw_g1p0" , & self . tsi_asw_g1p0 ()) . field ("tsi_asw_g1p1" , & self . tsi_asw_g1p1 ()) . field ("tsi_asw_g1p2" , & self . tsi_asw_g1p2 ()) . field ("tsi_asw_g1p3" , & self . tsi_asw_g1p3 ()) . field ("tsi_asw_g2p0" , & self . tsi_asw_g2p0 ()) . field ("tsi_asw_g2p1" , & self . tsi_asw_g2p1 ()) . field ("tsi_asw_g2p2" , & self . tsi_asw_g2p2 ()) . field ("tsi_asw_g2p3" , & self . tsi_asw_g2p3 ()) . field ("tsi_asw_g3p0" , & self . tsi_asw_g3p0 ()) . field ("tsi_asw_g3p1" , & self . tsi_asw_g3p1 ()) . field ("tsi_asw_g3p2" , & self . tsi_asw_g3p2 ()) . field ("tsi_asw_g3p3" , & self . tsi_asw_g3p3 ()) . field ("tsi_asw_g4p0" , & self . tsi_asw_g4p0 ()) . field ("tsi_asw_g4p1" , & self . tsi_asw_g4p1 ()) . field ("tsi_asw_g4p2" , & self . tsi_asw_g4p2 ()) . field ("tsi_asw_g4p3" , & self . tsi_asw_g4p3 ()) . field ("tsi_asw_g5p0" , & self . tsi_asw_g5p0 ()) . field ("tsi_asw_g5p1" , & self . tsi_asw_g5p1 ()) . field ("tsi_asw_g5p2" , & self . tsi_asw_g5p2 ()) . field ("tsi_asw_g5p3" , & self . tsi_asw_g5p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiAsw { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiAsw {{ tsi_asw_g0p0: {=bool:?}, tsi_asw_g0p1: {=bool:?}, tsi_asw_g0p2: {=bool:?}, tsi_asw_g0p3: {=bool:?}, tsi_asw_g1p0: {=bool:?}, tsi_asw_g1p1: {=bool:?}, tsi_asw_g1p2: {=bool:?}, tsi_asw_g1p3: {=bool:?}, tsi_asw_g2p0: {=bool:?}, tsi_asw_g2p1: {=bool:?}, tsi_asw_g2p2: {=bool:?}, tsi_asw_g2p3: {=bool:?}, tsi_asw_g3p0: {=bool:?}, tsi_asw_g3p1: {=bool:?}, tsi_asw_g3p2: {=bool:?}, tsi_asw_g3p3: {=bool:?}, tsi_asw_g4p0: {=bool:?}, tsi_asw_g4p1: {=bool:?}, tsi_asw_g4p2: {=bool:?}, tsi_asw_g4p3: {=bool:?}, tsi_asw_g5p0: {=bool:?}, tsi_asw_g5p1: {=bool:?}, tsi_asw_g5p2: {=bool:?}, tsi_asw_g5p3: {=bool:?} }}" , self . tsi_asw_g0p0 () , self . tsi_asw_g0p1 () , self . tsi_asw_g0p2 () , self . tsi_asw_g0p3 () , self . tsi_asw_g1p0 () , self . tsi_asw_g1p1 () , self . tsi_asw_g1p2 () , self . tsi_asw_g1p3 () , self . tsi_asw_g2p0 () , self . tsi_asw_g2p1 () , self . tsi_asw_g2p2 () , self . tsi_asw_g2p3 () , self . tsi_asw_g3p0 () , self . tsi_asw_g3p1 () , self . tsi_asw_g3p2 () , self . tsi_asw_g3p3 () , self . tsi_asw_g4p0 () , self . tsi_asw_g4p1 () , self . tsi_asw_g4p2 () , self . tsi_asw_g4p3 () , self . tsi_asw_g5p0 () , self . tsi_asw_g5p1 () , self . tsi_asw_g5p2 () , self . tsi_asw_g5p3 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiChcfg (pub u32) ; impl TsiChcfg { # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g3p0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g3p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g3p1 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g3p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g3p2 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g3p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g3p3 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g3p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g4p0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g4p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g4p1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g4p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g4p2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g4p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g4p3 (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g4p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g5p0 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g5p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g5p1 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g5p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g5p2 (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g5p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_chcfg_g5p3 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_chcfg_g5p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for TsiChcfg { # [inline (always)]
fn default () -> TsiChcfg { TsiChcfg (0) } } impl core :: fmt :: Debug for TsiChcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiChcfg") . field ("tsi_chcfg_g0p0" , & self . tsi_chcfg_g0p0 ()) . field ("tsi_chcfg_g0p1" , & self . tsi_chcfg_g0p1 ()) . field ("tsi_chcfg_g0p2" , & self . tsi_chcfg_g0p2 ()) . field ("tsi_chcfg_g0p3" , & self . tsi_chcfg_g0p3 ()) . field ("tsi_chcfg_g1p0" , & self . tsi_chcfg_g1p0 ()) . field ("tsi_chcfg_g1p1" , & self . tsi_chcfg_g1p1 ()) . field ("tsi_chcfg_g1p2" , & self . tsi_chcfg_g1p2 ()) . field ("tsi_chcfg_g1p3" , & self . tsi_chcfg_g1p3 ()) . field ("tsi_chcfg_g2p0" , & self . tsi_chcfg_g2p0 ()) . field ("tsi_chcfg_g2p1" , & self . tsi_chcfg_g2p1 ()) . field ("tsi_chcfg_g2p2" , & self . tsi_chcfg_g2p2 ()) . field ("tsi_chcfg_g2p3" , & self . tsi_chcfg_g2p3 ()) . field ("tsi_chcfg_g3p0" , & self . tsi_chcfg_g3p0 ()) . field ("tsi_chcfg_g3p1" , & self . tsi_chcfg_g3p1 ()) . field ("tsi_chcfg_g3p2" , & self . tsi_chcfg_g3p2 ()) . field ("tsi_chcfg_g3p3" , & self . tsi_chcfg_g3p3 ()) . field ("tsi_chcfg_g4p0" , & self . tsi_chcfg_g4p0 ()) . field ("tsi_chcfg_g4p1" , & self . tsi_chcfg_g4p1 ()) . field ("tsi_chcfg_g4p2" , & self . tsi_chcfg_g4p2 ()) . field ("tsi_chcfg_g4p3" , & self . tsi_chcfg_g4p3 ()) . field ("tsi_chcfg_g5p0" , & self . tsi_chcfg_g5p0 ()) . field ("tsi_chcfg_g5p1" , & self . tsi_chcfg_g5p1 ()) . field ("tsi_chcfg_g5p2" , & self . tsi_chcfg_g5p2 ()) . field ("tsi_chcfg_g5p3" , & self . tsi_chcfg_g5p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiChcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiChcfg {{ tsi_chcfg_g0p0: {=bool:?}, tsi_chcfg_g0p1: {=bool:?}, tsi_chcfg_g0p2: {=bool:?}, tsi_chcfg_g0p3: {=bool:?}, tsi_chcfg_g1p0: {=bool:?}, tsi_chcfg_g1p1: {=bool:?}, tsi_chcfg_g1p2: {=bool:?}, tsi_chcfg_g1p3: {=bool:?}, tsi_chcfg_g2p0: {=bool:?}, tsi_chcfg_g2p1: {=bool:?}, tsi_chcfg_g2p2: {=bool:?}, tsi_chcfg_g2p3: {=bool:?}, tsi_chcfg_g3p0: {=bool:?}, tsi_chcfg_g3p1: {=bool:?}, tsi_chcfg_g3p2: {=bool:?}, tsi_chcfg_g3p3: {=bool:?}, tsi_chcfg_g4p0: {=bool:?}, tsi_chcfg_g4p1: {=bool:?}, tsi_chcfg_g4p2: {=bool:?}, tsi_chcfg_g4p3: {=bool:?}, tsi_chcfg_g5p0: {=bool:?}, tsi_chcfg_g5p1: {=bool:?}, tsi_chcfg_g5p2: {=bool:?}, tsi_chcfg_g5p3: {=bool:?} }}" , self . tsi_chcfg_g0p0 () , self . tsi_chcfg_g0p1 () , self . tsi_chcfg_g0p2 () , self . tsi_chcfg_g0p3 () , self . tsi_chcfg_g1p0 () , self . tsi_chcfg_g1p1 () , self . tsi_chcfg_g1p2 () , self . tsi_chcfg_g1p3 () , self . tsi_chcfg_g2p0 () , self . tsi_chcfg_g2p1 () , self . tsi_chcfg_g2p2 () , self . tsi_chcfg_g2p3 () , self . tsi_chcfg_g3p0 () , self . tsi_chcfg_g3p1 () , self . tsi_chcfg_g3p2 () , self . tsi_chcfg_g3p3 () , self . tsi_chcfg_g4p0 () , self . tsi_chcfg_g4p1 () , self . tsi_chcfg_g4p2 () , self . tsi_chcfg_g4p3 () , self . tsi_chcfg_g5p0 () , self . tsi_chcfg_g5p1 () , self . tsi_chcfg_g5p2 () , self . tsi_chcfg_g5p3 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiCtl (pub u32) ; impl TsiCtl { # [must_use]
# [inline (always)]
pub const fn tsi_ctl_tsien (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_tsien (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_tsis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_tsis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_trgmod (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_trgmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_egsel (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_egsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_pinmod (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_pinmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_mcn (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_tsi_ctl_mcn (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 5usize)) | (((val as u32) & 0x07) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_ctcdiv (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [inline (always)]
pub const fn set_tsi_ctl_ctcdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_ecdiv (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_ecdiv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_ecen (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_ctl_ecen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_ecdt (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x7f ; val as u8 } # [inline (always)]
pub const fn set_tsi_ctl_ecdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 17usize)) | (((val as u32) & 0x7f) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_ctdt (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_tsi_ctl_ctdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 24usize)) | (((val as u32) & 0x0f) << 24usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_ctl_cdt (& self) -> u8 { let val = (self . 0 >> 28usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_tsi_ctl_cdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 28usize)) | (((val as u32) & 0x0f) << 28usize) ; } } impl Default for TsiCtl { # [inline (always)]
fn default () -> TsiCtl { TsiCtl (0) } } impl core :: fmt :: Debug for TsiCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiCtl") . field ("tsi_ctl_tsien" , & self . tsi_ctl_tsien ()) . field ("tsi_ctl_tsis" , & self . tsi_ctl_tsis ()) . field ("tsi_ctl_trgmod" , & self . tsi_ctl_trgmod ()) . field ("tsi_ctl_egsel" , & self . tsi_ctl_egsel ()) . field ("tsi_ctl_pinmod" , & self . tsi_ctl_pinmod ()) . field ("tsi_ctl_mcn" , & self . tsi_ctl_mcn ()) . field ("tsi_ctl_ctcdiv" , & self . tsi_ctl_ctcdiv ()) . field ("tsi_ctl_ecdiv" , & self . tsi_ctl_ecdiv ()) . field ("tsi_ctl_ecen" , & self . tsi_ctl_ecen ()) . field ("tsi_ctl_ecdt" , & self . tsi_ctl_ecdt ()) . field ("tsi_ctl_ctdt" , & self . tsi_ctl_ctdt ()) . field ("tsi_ctl_cdt" , & self . tsi_ctl_cdt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiCtl {{ tsi_ctl_tsien: {=bool:?}, tsi_ctl_tsis: {=bool:?}, tsi_ctl_trgmod: {=bool:?}, tsi_ctl_egsel: {=bool:?}, tsi_ctl_pinmod: {=bool:?}, tsi_ctl_mcn: {=u8:?}, tsi_ctl_ctcdiv: {=u8:?}, tsi_ctl_ecdiv: {=bool:?}, tsi_ctl_ecen: {=bool:?}, tsi_ctl_ecdt: {=u8:?}, tsi_ctl_ctdt: {=u8:?}, tsi_ctl_cdt: {=u8:?} }}" , self . tsi_ctl_tsien () , self . tsi_ctl_tsis () , self . tsi_ctl_trgmod () , self . tsi_ctl_egsel () , self . tsi_ctl_pinmod () , self . tsi_ctl_mcn () , self . tsi_ctl_ctcdiv () , self . tsi_ctl_ecdiv () , self . tsi_ctl_ecen () , self . tsi_ctl_ecdt () , self . tsi_ctl_ctdt () , self . tsi_ctl_cdt ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiGctl (pub u32) ; impl TsiGctl { # [must_use]
# [inline (always)]
pub const fn tsi_gctl_ge0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_ge0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_ge1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_ge1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_ge2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_ge2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_ge3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_ge3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_ge4 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_ge4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_ge5 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_ge5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_gc0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_gc0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_gc1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_gc1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_gc2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_gc2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_gc3 (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_gc3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_gc4 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_gc4 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_gctl_gc5 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_gctl_gc5 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } } impl Default for TsiGctl { # [inline (always)]
fn default () -> TsiGctl { TsiGctl (0) } } impl core :: fmt :: Debug for TsiGctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiGctl") . field ("tsi_gctl_ge0" , & self . tsi_gctl_ge0 ()) . field ("tsi_gctl_ge1" , & self . tsi_gctl_ge1 ()) . field ("tsi_gctl_ge2" , & self . tsi_gctl_ge2 ()) . field ("tsi_gctl_ge3" , & self . tsi_gctl_ge3 ()) . field ("tsi_gctl_ge4" , & self . tsi_gctl_ge4 ()) . field ("tsi_gctl_ge5" , & self . tsi_gctl_ge5 ()) . field ("tsi_gctl_gc0" , & self . tsi_gctl_gc0 ()) . field ("tsi_gctl_gc1" , & self . tsi_gctl_gc1 ()) . field ("tsi_gctl_gc2" , & self . tsi_gctl_gc2 ()) . field ("tsi_gctl_gc3" , & self . tsi_gctl_gc3 ()) . field ("tsi_gctl_gc4" , & self . tsi_gctl_gc4 ()) . field ("tsi_gctl_gc5" , & self . tsi_gctl_gc5 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiGctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiGctl {{ tsi_gctl_ge0: {=bool:?}, tsi_gctl_ge1: {=bool:?}, tsi_gctl_ge2: {=bool:?}, tsi_gctl_ge3: {=bool:?}, tsi_gctl_ge4: {=bool:?}, tsi_gctl_ge5: {=bool:?}, tsi_gctl_gc0: {=bool:?}, tsi_gctl_gc1: {=bool:?}, tsi_gctl_gc2: {=bool:?}, tsi_gctl_gc3: {=bool:?}, tsi_gctl_gc4: {=bool:?}, tsi_gctl_gc5: {=bool:?} }}" , self . tsi_gctl_ge0 () , self . tsi_gctl_ge1 () , self . tsi_gctl_ge2 () , self . tsi_gctl_ge3 () , self . tsi_gctl_ge4 () , self . tsi_gctl_ge5 () , self . tsi_gctl_gc0 () , self . tsi_gctl_gc1 () , self . tsi_gctl_gc2 () , self . tsi_gctl_gc3 () , self . tsi_gctl_gc4 () , self . tsi_gctl_gc5 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiIntc (pub u32) ; impl TsiIntc { # [must_use]
# [inline (always)]
pub const fn tsi_intc_cctcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_intc_cctcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_intc_cmnerr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_intc_cmnerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for TsiIntc { # [inline (always)]
fn default () -> TsiIntc { TsiIntc (0) } } impl core :: fmt :: Debug for TsiIntc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiIntc") . field ("tsi_intc_cctcf" , & self . tsi_intc_cctcf ()) . field ("tsi_intc_cmnerr" , & self . tsi_intc_cmnerr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiIntc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiIntc {{ tsi_intc_cctcf: {=bool:?}, tsi_intc_cmnerr: {=bool:?} }}" , self . tsi_intc_cctcf () , self . tsi_intc_cmnerr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiInten (pub u32) ; impl TsiInten { # [must_use]
# [inline (always)]
pub const fn tsi_inten_ctcfie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_inten_ctcfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_inten_mnerrie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_inten_mnerrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for TsiInten { # [inline (always)]
fn default () -> TsiInten { TsiInten (0) } } impl core :: fmt :: Debug for TsiInten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiInten") . field ("tsi_inten_ctcfie" , & self . tsi_inten_ctcfie ()) . field ("tsi_inten_mnerrie" , & self . tsi_inten_mnerrie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiInten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiInten {{ tsi_inten_ctcfie: {=bool:?}, tsi_inten_mnerrie: {=bool:?} }}" , self . tsi_inten_ctcfie () , self . tsi_inten_mnerrie ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiIntf (pub u32) ; impl TsiIntf { # [must_use]
# [inline (always)]
pub const fn tsi_intf_ctcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_intf_ctcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_intf_mnerr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_intf_mnerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for TsiIntf { # [inline (always)]
fn default () -> TsiIntf { TsiIntf (0) } } impl core :: fmt :: Debug for TsiIntf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiIntf") . field ("tsi_intf_ctcf" , & self . tsi_intf_ctcf ()) . field ("tsi_intf_mnerr" , & self . tsi_intf_mnerr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiIntf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiIntf {{ tsi_intf_ctcf: {=bool:?}, tsi_intf_mnerr: {=bool:?} }}" , self . tsi_intf_ctcf () , self . tsi_intf_mnerr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiPhm (pub u32) ; impl TsiPhm { # [must_use]
# [inline (always)]
pub const fn tsi_phm_g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g3p0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g3p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g3p1 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g3p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g3p2 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g3p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g3p3 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g3p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g4p0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g4p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g4p1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g4p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g4p2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g4p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g4p3 (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g4p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g5p0 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g5p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g5p1 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g5p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g5p2 (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g5p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_phm_g5p3 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_phm_g5p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for TsiPhm { # [inline (always)]
fn default () -> TsiPhm { TsiPhm (0) } } impl core :: fmt :: Debug for TsiPhm { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiPhm") . field ("tsi_phm_g0p0" , & self . tsi_phm_g0p0 ()) . field ("tsi_phm_g0p1" , & self . tsi_phm_g0p1 ()) . field ("tsi_phm_g0p2" , & self . tsi_phm_g0p2 ()) . field ("tsi_phm_g0p3" , & self . tsi_phm_g0p3 ()) . field ("tsi_phm_g1p0" , & self . tsi_phm_g1p0 ()) . field ("tsi_phm_g1p1" , & self . tsi_phm_g1p1 ()) . field ("tsi_phm_g1p2" , & self . tsi_phm_g1p2 ()) . field ("tsi_phm_g1p3" , & self . tsi_phm_g1p3 ()) . field ("tsi_phm_g2p0" , & self . tsi_phm_g2p0 ()) . field ("tsi_phm_g2p1" , & self . tsi_phm_g2p1 ()) . field ("tsi_phm_g2p2" , & self . tsi_phm_g2p2 ()) . field ("tsi_phm_g2p3" , & self . tsi_phm_g2p3 ()) . field ("tsi_phm_g3p0" , & self . tsi_phm_g3p0 ()) . field ("tsi_phm_g3p1" , & self . tsi_phm_g3p1 ()) . field ("tsi_phm_g3p2" , & self . tsi_phm_g3p2 ()) . field ("tsi_phm_g3p3" , & self . tsi_phm_g3p3 ()) . field ("tsi_phm_g4p0" , & self . tsi_phm_g4p0 ()) . field ("tsi_phm_g4p1" , & self . tsi_phm_g4p1 ()) . field ("tsi_phm_g4p2" , & self . tsi_phm_g4p2 ()) . field ("tsi_phm_g4p3" , & self . tsi_phm_g4p3 ()) . field ("tsi_phm_g5p0" , & self . tsi_phm_g5p0 ()) . field ("tsi_phm_g5p1" , & self . tsi_phm_g5p1 ()) . field ("tsi_phm_g5p2" , & self . tsi_phm_g5p2 ()) . field ("tsi_phm_g5p3" , & self . tsi_phm_g5p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiPhm { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiPhm {{ tsi_phm_g0p0: {=bool:?}, tsi_phm_g0p1: {=bool:?}, tsi_phm_g0p2: {=bool:?}, tsi_phm_g0p3: {=bool:?}, tsi_phm_g1p0: {=bool:?}, tsi_phm_g1p1: {=bool:?}, tsi_phm_g1p2: {=bool:?}, tsi_phm_g1p3: {=bool:?}, tsi_phm_g2p0: {=bool:?}, tsi_phm_g2p1: {=bool:?}, tsi_phm_g2p2: {=bool:?}, tsi_phm_g2p3: {=bool:?}, tsi_phm_g3p0: {=bool:?}, tsi_phm_g3p1: {=bool:?}, tsi_phm_g3p2: {=bool:?}, tsi_phm_g3p3: {=bool:?}, tsi_phm_g4p0: {=bool:?}, tsi_phm_g4p1: {=bool:?}, tsi_phm_g4p2: {=bool:?}, tsi_phm_g4p3: {=bool:?}, tsi_phm_g5p0: {=bool:?}, tsi_phm_g5p1: {=bool:?}, tsi_phm_g5p2: {=bool:?}, tsi_phm_g5p3: {=bool:?} }}" , self . tsi_phm_g0p0 () , self . tsi_phm_g0p1 () , self . tsi_phm_g0p2 () , self . tsi_phm_g0p3 () , self . tsi_phm_g1p0 () , self . tsi_phm_g1p1 () , self . tsi_phm_g1p2 () , self . tsi_phm_g1p3 () , self . tsi_phm_g2p0 () , self . tsi_phm_g2p1 () , self . tsi_phm_g2p2 () , self . tsi_phm_g2p3 () , self . tsi_phm_g3p0 () , self . tsi_phm_g3p1 () , self . tsi_phm_g3p2 () , self . tsi_phm_g3p3 () , self . tsi_phm_g4p0 () , self . tsi_phm_g4p1 () , self . tsi_phm_g4p2 () , self . tsi_phm_g4p3 () , self . tsi_phm_g5p0 () , self . tsi_phm_g5p1 () , self . tsi_phm_g5p2 () , self . tsi_phm_g5p3 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TsiSampcfg (pub u32) ; impl TsiSampcfg { # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g0p0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g0p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g0p1 (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g0p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g0p2 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g0p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g0p3 (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g0p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g1p0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g1p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g1p1 (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g1p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g1p2 (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g1p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g1p3 (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g1p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g2p0 (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g2p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g2p1 (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g2p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g2p2 (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g2p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g2p3 (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g2p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g3p0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g3p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g3p1 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g3p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g3p2 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g3p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g3p3 (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g3p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g4p0 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g4p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g4p1 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g4p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g4p2 (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g4p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g4p3 (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g4p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g5p0 (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g5p0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g5p1 (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g5p1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g5p2 (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g5p2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [must_use]
# [inline (always)]
pub const fn tsi_sampcfg_g5p3 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tsi_sampcfg_g5p3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for TsiSampcfg { # [inline (always)]
fn default () -> TsiSampcfg { TsiSampcfg (0) } } impl core :: fmt :: Debug for TsiSampcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TsiSampcfg") . field ("tsi_sampcfg_g0p0" , & self . tsi_sampcfg_g0p0 ()) . field ("tsi_sampcfg_g0p1" , & self . tsi_sampcfg_g0p1 ()) . field ("tsi_sampcfg_g0p2" , & self . tsi_sampcfg_g0p2 ()) . field ("tsi_sampcfg_g0p3" , & self . tsi_sampcfg_g0p3 ()) . field ("tsi_sampcfg_g1p0" , & self . tsi_sampcfg_g1p0 ()) . field ("tsi_sampcfg_g1p1" , & self . tsi_sampcfg_g1p1 ()) . field ("tsi_sampcfg_g1p2" , & self . tsi_sampcfg_g1p2 ()) . field ("tsi_sampcfg_g1p3" , & self . tsi_sampcfg_g1p3 ()) . field ("tsi_sampcfg_g2p0" , & self . tsi_sampcfg_g2p0 ()) . field ("tsi_sampcfg_g2p1" , & self . tsi_sampcfg_g2p1 ()) . field ("tsi_sampcfg_g2p2" , & self . tsi_sampcfg_g2p2 ()) . field ("tsi_sampcfg_g2p3" , & self . tsi_sampcfg_g2p3 ()) . field ("tsi_sampcfg_g3p0" , & self . tsi_sampcfg_g3p0 ()) . field ("tsi_sampcfg_g3p1" , & self . tsi_sampcfg_g3p1 ()) . field ("tsi_sampcfg_g3p2" , & self . tsi_sampcfg_g3p2 ()) . field ("tsi_sampcfg_g3p3" , & self . tsi_sampcfg_g3p3 ()) . field ("tsi_sampcfg_g4p0" , & self . tsi_sampcfg_g4p0 ()) . field ("tsi_sampcfg_g4p1" , & self . tsi_sampcfg_g4p1 ()) . field ("tsi_sampcfg_g4p2" , & self . tsi_sampcfg_g4p2 ()) . field ("tsi_sampcfg_g4p3" , & self . tsi_sampcfg_g4p3 ()) . field ("tsi_sampcfg_g5p0" , & self . tsi_sampcfg_g5p0 ()) . field ("tsi_sampcfg_g5p1" , & self . tsi_sampcfg_g5p1 ()) . field ("tsi_sampcfg_g5p2" , & self . tsi_sampcfg_g5p2 ()) . field ("tsi_sampcfg_g5p3" , & self . tsi_sampcfg_g5p3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TsiSampcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TsiSampcfg {{ tsi_sampcfg_g0p0: {=bool:?}, tsi_sampcfg_g0p1: {=bool:?}, tsi_sampcfg_g0p2: {=bool:?}, tsi_sampcfg_g0p3: {=bool:?}, tsi_sampcfg_g1p0: {=bool:?}, tsi_sampcfg_g1p1: {=bool:?}, tsi_sampcfg_g1p2: {=bool:?}, tsi_sampcfg_g1p3: {=bool:?}, tsi_sampcfg_g2p0: {=bool:?}, tsi_sampcfg_g2p1: {=bool:?}, tsi_sampcfg_g2p2: {=bool:?}, tsi_sampcfg_g2p3: {=bool:?}, tsi_sampcfg_g3p0: {=bool:?}, tsi_sampcfg_g3p1: {=bool:?}, tsi_sampcfg_g3p2: {=bool:?}, tsi_sampcfg_g3p3: {=bool:?}, tsi_sampcfg_g4p0: {=bool:?}, tsi_sampcfg_g4p1: {=bool:?}, tsi_sampcfg_g4p2: {=bool:?}, tsi_sampcfg_g4p3: {=bool:?}, tsi_sampcfg_g5p0: {=bool:?}, tsi_sampcfg_g5p1: {=bool:?}, tsi_sampcfg_g5p2: {=bool:?}, tsi_sampcfg_g5p3: {=bool:?} }}" , self . tsi_sampcfg_g0p0 () , self . tsi_sampcfg_g0p1 () , self . tsi_sampcfg_g0p2 () , self . tsi_sampcfg_g0p3 () , self . tsi_sampcfg_g1p0 () , self . tsi_sampcfg_g1p1 () , self . tsi_sampcfg_g1p2 () , self . tsi_sampcfg_g1p3 () , self . tsi_sampcfg_g2p0 () , self . tsi_sampcfg_g2p1 () , self . tsi_sampcfg_g2p2 () , self . tsi_sampcfg_g2p3 () , self . tsi_sampcfg_g3p0 () , self . tsi_sampcfg_g3p1 () , self . tsi_sampcfg_g3p2 () , self . tsi_sampcfg_g3p3 () , self . tsi_sampcfg_g4p0 () , self . tsi_sampcfg_g4p1 () , self . tsi_sampcfg_g4p2 () , self . tsi_sampcfg_g4p3 () , self . tsi_sampcfg_g5p0 () , self . tsi_sampcfg_g5p1 () , self . tsi_sampcfg_g5p2 () , self . tsi_sampcfg_g5p3 ()) } } }