#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tzspc { ptr : * mut u8 } unsafe impl Send for Tzspc { } unsafe impl Sync for Tzspc { } impl Tzspc { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn tzpcu_tzspc_ctl (self) -> crate :: common :: Reg < regs :: TzpcuTzspcCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0 (self) -> crate :: common :: Reg < regs :: TzpcuTzspcSamCfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1 (self) -> crate :: common :: Reg < regs :: TzpcuTzspcSamCfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2 (self) -> crate :: common :: Reg < regs :: TzpcuTzspcSamCfg2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0 (self) -> crate :: common :: Reg < regs :: TzpcuTzspcPamCfg0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x20usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1 (self) -> crate :: common :: Reg < regs :: TzpcuTzspcPamCfg1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x24usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2 (self) -> crate :: common :: Reg < regs :: TzpcuTzspcPamCfg2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x28usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_tzmmpc0_nsm0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x30usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_tzmmpc0_nsm1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x34usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_tzmmpc0_nsm2 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x38usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_tzmmpc0_nsm3 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x3cusize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_tzmmpc1_nsm0 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x40usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_tzmmpc1_nsm1 (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x44usize) as _) } } # [inline (always)]
pub const fn tzpcu_tzspc_dbg_cfg (self) -> crate :: common :: Reg < regs :: TzpcuTzspcDbgCfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0200usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcCtl (pub u32) ; impl TzpcuTzspcCtl { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_ctl_lk (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_ctl_lk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for TzpcuTzspcCtl { # [inline (always)]
fn default () -> TzpcuTzspcCtl { TzpcuTzspcCtl (0) } } impl core :: fmt :: Debug for TzpcuTzspcCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcCtl") . field ("tzpcu_tzspc_ctl_lk" , & self . tzpcu_tzspc_ctl_lk ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcCtl {{ tzpcu_tzspc_ctl_lk: {=bool:?} }}" , self . tzpcu_tzspc_ctl_lk ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcDbgCfg (pub u32) ; impl TzpcuTzspcDbgCfg { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_dbg_cfg_iden (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_dbg_cfg_iden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_dbg_cfg_niden (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_dbg_cfg_niden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_dbg_cfg_spiden (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_dbg_cfg_spiden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_dbg_cfg_spniden (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_dbg_cfg_spniden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for TzpcuTzspcDbgCfg { # [inline (always)]
fn default () -> TzpcuTzspcDbgCfg { TzpcuTzspcDbgCfg (0) } } impl core :: fmt :: Debug for TzpcuTzspcDbgCfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcDbgCfg") . field ("tzpcu_tzspc_dbg_cfg_iden" , & self . tzpcu_tzspc_dbg_cfg_iden ()) . field ("tzpcu_tzspc_dbg_cfg_niden" , & self . tzpcu_tzspc_dbg_cfg_niden ()) . field ("tzpcu_tzspc_dbg_cfg_spiden" , & self . tzpcu_tzspc_dbg_cfg_spiden ()) . field ("tzpcu_tzspc_dbg_cfg_spniden" , & self . tzpcu_tzspc_dbg_cfg_spniden ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcDbgCfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcDbgCfg {{ tzpcu_tzspc_dbg_cfg_iden: {=bool:?}, tzpcu_tzspc_dbg_cfg_niden: {=bool:?}, tzpcu_tzspc_dbg_cfg_spiden: {=bool:?}, tzpcu_tzspc_dbg_cfg_spniden: {=bool:?} }}" , self . tzpcu_tzspc_dbg_cfg_iden () , self . tzpcu_tzspc_dbg_cfg_niden () , self . tzpcu_tzspc_dbg_cfg_spiden () , self . tzpcu_tzspc_dbg_cfg_spniden ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcPamCfg0 (pub u32) ; impl TzpcuTzspcPamCfg0 { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_timer1pam (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_timer1pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_timer2pam (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_timer2pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_timer3pam (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_timer3pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_timer4pam (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_timer4pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_timer5pam (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_timer5pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_wwdgtpam (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_wwdgtpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_fwdgtpam (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_fwdgtpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_spi1pam (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_spi1pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_usart1pam (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_usart1pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_usart2pam (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_usart2pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_i2c0pam (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_i2c0pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_i2c1pam (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_i2c1pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_usbfspam (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_usbfspam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_timer0pam (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_timer0pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg0_spi0pam (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg0_spi0pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for TzpcuTzspcPamCfg0 { # [inline (always)]
fn default () -> TzpcuTzspcPamCfg0 { TzpcuTzspcPamCfg0 (0) } } impl core :: fmt :: Debug for TzpcuTzspcPamCfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcPamCfg0") . field ("tzpcu_tzspc_pam_cfg0_timer1pam" , & self . tzpcu_tzspc_pam_cfg0_timer1pam ()) . field ("tzpcu_tzspc_pam_cfg0_timer2pam" , & self . tzpcu_tzspc_pam_cfg0_timer2pam ()) . field ("tzpcu_tzspc_pam_cfg0_timer3pam" , & self . tzpcu_tzspc_pam_cfg0_timer3pam ()) . field ("tzpcu_tzspc_pam_cfg0_timer4pam" , & self . tzpcu_tzspc_pam_cfg0_timer4pam ()) . field ("tzpcu_tzspc_pam_cfg0_timer5pam" , & self . tzpcu_tzspc_pam_cfg0_timer5pam ()) . field ("tzpcu_tzspc_pam_cfg0_wwdgtpam" , & self . tzpcu_tzspc_pam_cfg0_wwdgtpam ()) . field ("tzpcu_tzspc_pam_cfg0_fwdgtpam" , & self . tzpcu_tzspc_pam_cfg0_fwdgtpam ()) . field ("tzpcu_tzspc_pam_cfg0_spi1pam" , & self . tzpcu_tzspc_pam_cfg0_spi1pam ()) . field ("tzpcu_tzspc_pam_cfg0_usart1pam" , & self . tzpcu_tzspc_pam_cfg0_usart1pam ()) . field ("tzpcu_tzspc_pam_cfg0_usart2pam" , & self . tzpcu_tzspc_pam_cfg0_usart2pam ()) . field ("tzpcu_tzspc_pam_cfg0_i2c0pam" , & self . tzpcu_tzspc_pam_cfg0_i2c0pam ()) . field ("tzpcu_tzspc_pam_cfg0_i2c1pam" , & self . tzpcu_tzspc_pam_cfg0_i2c1pam ()) . field ("tzpcu_tzspc_pam_cfg0_usbfspam" , & self . tzpcu_tzspc_pam_cfg0_usbfspam ()) . field ("tzpcu_tzspc_pam_cfg0_timer0pam" , & self . tzpcu_tzspc_pam_cfg0_timer0pam ()) . field ("tzpcu_tzspc_pam_cfg0_spi0pam" , & self . tzpcu_tzspc_pam_cfg0_spi0pam ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcPamCfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcPamCfg0 {{ tzpcu_tzspc_pam_cfg0_timer1pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_timer2pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_timer3pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_timer4pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_timer5pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_wwdgtpam: {=bool:?}, tzpcu_tzspc_pam_cfg0_fwdgtpam: {=bool:?}, tzpcu_tzspc_pam_cfg0_spi1pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_usart1pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_usart2pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_i2c0pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_i2c1pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_usbfspam: {=bool:?}, tzpcu_tzspc_pam_cfg0_timer0pam: {=bool:?}, tzpcu_tzspc_pam_cfg0_spi0pam: {=bool:?} }}" , self . tzpcu_tzspc_pam_cfg0_timer1pam () , self . tzpcu_tzspc_pam_cfg0_timer2pam () , self . tzpcu_tzspc_pam_cfg0_timer3pam () , self . tzpcu_tzspc_pam_cfg0_timer4pam () , self . tzpcu_tzspc_pam_cfg0_timer5pam () , self . tzpcu_tzspc_pam_cfg0_wwdgtpam () , self . tzpcu_tzspc_pam_cfg0_fwdgtpam () , self . tzpcu_tzspc_pam_cfg0_spi1pam () , self . tzpcu_tzspc_pam_cfg0_usart1pam () , self . tzpcu_tzspc_pam_cfg0_usart2pam () , self . tzpcu_tzspc_pam_cfg0_i2c0pam () , self . tzpcu_tzspc_pam_cfg0_i2c1pam () , self . tzpcu_tzspc_pam_cfg0_usbfspam () , self . tzpcu_tzspc_pam_cfg0_timer0pam () , self . tzpcu_tzspc_pam_cfg0_spi0pam ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcPamCfg1 (pub u32) ; impl TzpcuTzspcPamCfg1 { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_ctcpriv (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_ctcpriv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_usart0pam (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_usart0pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_timer15pam (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_timer15pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_timer16pam (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_timer16pam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_hpdfpam (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_hpdfpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_crcpam (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_crcpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_tsipam (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_tsipam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_icachepam (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_icachepam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_adcpam (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_adcpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_caupam (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_caupam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_haupam (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_haupam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_trngpam (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_trngpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_pkcaupam (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_pkcaupam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg1_sdiopam (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg1_sdiopam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for TzpcuTzspcPamCfg1 { # [inline (always)]
fn default () -> TzpcuTzspcPamCfg1 { TzpcuTzspcPamCfg1 (0) } } impl core :: fmt :: Debug for TzpcuTzspcPamCfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcPamCfg1") . field ("tzpcu_tzspc_pam_cfg1_ctcpriv" , & self . tzpcu_tzspc_pam_cfg1_ctcpriv ()) . field ("tzpcu_tzspc_pam_cfg1_usart0pam" , & self . tzpcu_tzspc_pam_cfg1_usart0pam ()) . field ("tzpcu_tzspc_pam_cfg1_timer15pam" , & self . tzpcu_tzspc_pam_cfg1_timer15pam ()) . field ("tzpcu_tzspc_pam_cfg1_timer16pam" , & self . tzpcu_tzspc_pam_cfg1_timer16pam ()) . field ("tzpcu_tzspc_pam_cfg1_hpdfpam" , & self . tzpcu_tzspc_pam_cfg1_hpdfpam ()) . field ("tzpcu_tzspc_pam_cfg1_crcpam" , & self . tzpcu_tzspc_pam_cfg1_crcpam ()) . field ("tzpcu_tzspc_pam_cfg1_tsipam" , & self . tzpcu_tzspc_pam_cfg1_tsipam ()) . field ("tzpcu_tzspc_pam_cfg1_icachepam" , & self . tzpcu_tzspc_pam_cfg1_icachepam ()) . field ("tzpcu_tzspc_pam_cfg1_adcpam" , & self . tzpcu_tzspc_pam_cfg1_adcpam ()) . field ("tzpcu_tzspc_pam_cfg1_caupam" , & self . tzpcu_tzspc_pam_cfg1_caupam ()) . field ("tzpcu_tzspc_pam_cfg1_haupam" , & self . tzpcu_tzspc_pam_cfg1_haupam ()) . field ("tzpcu_tzspc_pam_cfg1_trngpam" , & self . tzpcu_tzspc_pam_cfg1_trngpam ()) . field ("tzpcu_tzspc_pam_cfg1_pkcaupam" , & self . tzpcu_tzspc_pam_cfg1_pkcaupam ()) . field ("tzpcu_tzspc_pam_cfg1_sdiopam" , & self . tzpcu_tzspc_pam_cfg1_sdiopam ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcPamCfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcPamCfg1 {{ tzpcu_tzspc_pam_cfg1_ctcpriv: {=bool:?}, tzpcu_tzspc_pam_cfg1_usart0pam: {=bool:?}, tzpcu_tzspc_pam_cfg1_timer15pam: {=bool:?}, tzpcu_tzspc_pam_cfg1_timer16pam: {=bool:?}, tzpcu_tzspc_pam_cfg1_hpdfpam: {=bool:?}, tzpcu_tzspc_pam_cfg1_crcpam: {=bool:?}, tzpcu_tzspc_pam_cfg1_tsipam: {=bool:?}, tzpcu_tzspc_pam_cfg1_icachepam: {=bool:?}, tzpcu_tzspc_pam_cfg1_adcpam: {=bool:?}, tzpcu_tzspc_pam_cfg1_caupam: {=bool:?}, tzpcu_tzspc_pam_cfg1_haupam: {=bool:?}, tzpcu_tzspc_pam_cfg1_trngpam: {=bool:?}, tzpcu_tzspc_pam_cfg1_pkcaupam: {=bool:?}, tzpcu_tzspc_pam_cfg1_sdiopam: {=bool:?} }}" , self . tzpcu_tzspc_pam_cfg1_ctcpriv () , self . tzpcu_tzspc_pam_cfg1_usart0pam () , self . tzpcu_tzspc_pam_cfg1_timer15pam () , self . tzpcu_tzspc_pam_cfg1_timer16pam () , self . tzpcu_tzspc_pam_cfg1_hpdfpam () , self . tzpcu_tzspc_pam_cfg1_crcpam () , self . tzpcu_tzspc_pam_cfg1_tsipam () , self . tzpcu_tzspc_pam_cfg1_icachepam () , self . tzpcu_tzspc_pam_cfg1_adcpam () , self . tzpcu_tzspc_pam_cfg1_caupam () , self . tzpcu_tzspc_pam_cfg1_haupam () , self . tzpcu_tzspc_pam_cfg1_trngpam () , self . tzpcu_tzspc_pam_cfg1_pkcaupam () , self . tzpcu_tzspc_pam_cfg1_sdiopam ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcPamCfg2 (pub u32) ; impl TzpcuTzspcPamCfg2 { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_efusepam (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_efusepam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_dbgpam (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_dbgpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_sqpi_psramregpam (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_sqpi_psramregpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_qspi_flashregpam (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_qspi_flashregpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_wifi_rfpam (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_wifi_rfpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_i2s1_addpam (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_i2s1_addpam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_dcipam (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_dcipam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_pam_cfg2_wifipam (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_pam_cfg2_wifipam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for TzpcuTzspcPamCfg2 { # [inline (always)]
fn default () -> TzpcuTzspcPamCfg2 { TzpcuTzspcPamCfg2 (0) } } impl core :: fmt :: Debug for TzpcuTzspcPamCfg2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcPamCfg2") . field ("tzpcu_tzspc_pam_cfg2_efusepam" , & self . tzpcu_tzspc_pam_cfg2_efusepam ()) . field ("tzpcu_tzspc_pam_cfg2_dbgpam" , & self . tzpcu_tzspc_pam_cfg2_dbgpam ()) . field ("tzpcu_tzspc_pam_cfg2_sqpi_psramregpam" , & self . tzpcu_tzspc_pam_cfg2_sqpi_psramregpam ()) . field ("tzpcu_tzspc_pam_cfg2_qspi_flashregpam" , & self . tzpcu_tzspc_pam_cfg2_qspi_flashregpam ()) . field ("tzpcu_tzspc_pam_cfg2_wifi_rfpam" , & self . tzpcu_tzspc_pam_cfg2_wifi_rfpam ()) . field ("tzpcu_tzspc_pam_cfg2_i2s1_addpam" , & self . tzpcu_tzspc_pam_cfg2_i2s1_addpam ()) . field ("tzpcu_tzspc_pam_cfg2_dcipam" , & self . tzpcu_tzspc_pam_cfg2_dcipam ()) . field ("tzpcu_tzspc_pam_cfg2_wifipam" , & self . tzpcu_tzspc_pam_cfg2_wifipam ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcPamCfg2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcPamCfg2 {{ tzpcu_tzspc_pam_cfg2_efusepam: {=bool:?}, tzpcu_tzspc_pam_cfg2_dbgpam: {=bool:?}, tzpcu_tzspc_pam_cfg2_sqpi_psramregpam: {=bool:?}, tzpcu_tzspc_pam_cfg2_qspi_flashregpam: {=bool:?}, tzpcu_tzspc_pam_cfg2_wifi_rfpam: {=bool:?}, tzpcu_tzspc_pam_cfg2_i2s1_addpam: {=bool:?}, tzpcu_tzspc_pam_cfg2_dcipam: {=bool:?}, tzpcu_tzspc_pam_cfg2_wifipam: {=bool:?} }}" , self . tzpcu_tzspc_pam_cfg2_efusepam () , self . tzpcu_tzspc_pam_cfg2_dbgpam () , self . tzpcu_tzspc_pam_cfg2_sqpi_psramregpam () , self . tzpcu_tzspc_pam_cfg2_qspi_flashregpam () , self . tzpcu_tzspc_pam_cfg2_wifi_rfpam () , self . tzpcu_tzspc_pam_cfg2_i2s1_addpam () , self . tzpcu_tzspc_pam_cfg2_dcipam () , self . tzpcu_tzspc_pam_cfg2_wifipam ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcSamCfg0 (pub u32) ; impl TzpcuTzspcSamCfg0 { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_timer1sam (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_timer1sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_timer2sam (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_timer2sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_timer3sam (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_timer3sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_timer4sam (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_timer4sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_timer5sam (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_timer5sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_wwdgtsam (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_wwdgtsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_fwdgtsam (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_fwdgtsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_spi1sam (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_spi1sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_usart1sam (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_usart1sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_usart2sam (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_usart2sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_i2c0sam (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_i2c0sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_i2c1sam (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_i2c1sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_usbfssam (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_usbfssam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_timer0sam (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_timer0sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg0_spi0sam (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg0_spi0sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for TzpcuTzspcSamCfg0 { # [inline (always)]
fn default () -> TzpcuTzspcSamCfg0 { TzpcuTzspcSamCfg0 (0) } } impl core :: fmt :: Debug for TzpcuTzspcSamCfg0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcSamCfg0") . field ("tzpcu_tzspc_sam_cfg0_timer1sam" , & self . tzpcu_tzspc_sam_cfg0_timer1sam ()) . field ("tzpcu_tzspc_sam_cfg0_timer2sam" , & self . tzpcu_tzspc_sam_cfg0_timer2sam ()) . field ("tzpcu_tzspc_sam_cfg0_timer3sam" , & self . tzpcu_tzspc_sam_cfg0_timer3sam ()) . field ("tzpcu_tzspc_sam_cfg0_timer4sam" , & self . tzpcu_tzspc_sam_cfg0_timer4sam ()) . field ("tzpcu_tzspc_sam_cfg0_timer5sam" , & self . tzpcu_tzspc_sam_cfg0_timer5sam ()) . field ("tzpcu_tzspc_sam_cfg0_wwdgtsam" , & self . tzpcu_tzspc_sam_cfg0_wwdgtsam ()) . field ("tzpcu_tzspc_sam_cfg0_fwdgtsam" , & self . tzpcu_tzspc_sam_cfg0_fwdgtsam ()) . field ("tzpcu_tzspc_sam_cfg0_spi1sam" , & self . tzpcu_tzspc_sam_cfg0_spi1sam ()) . field ("tzpcu_tzspc_sam_cfg0_usart1sam" , & self . tzpcu_tzspc_sam_cfg0_usart1sam ()) . field ("tzpcu_tzspc_sam_cfg0_usart2sam" , & self . tzpcu_tzspc_sam_cfg0_usart2sam ()) . field ("tzpcu_tzspc_sam_cfg0_i2c0sam" , & self . tzpcu_tzspc_sam_cfg0_i2c0sam ()) . field ("tzpcu_tzspc_sam_cfg0_i2c1sam" , & self . tzpcu_tzspc_sam_cfg0_i2c1sam ()) . field ("tzpcu_tzspc_sam_cfg0_usbfssam" , & self . tzpcu_tzspc_sam_cfg0_usbfssam ()) . field ("tzpcu_tzspc_sam_cfg0_timer0sam" , & self . tzpcu_tzspc_sam_cfg0_timer0sam ()) . field ("tzpcu_tzspc_sam_cfg0_spi0sam" , & self . tzpcu_tzspc_sam_cfg0_spi0sam ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcSamCfg0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcSamCfg0 {{ tzpcu_tzspc_sam_cfg0_timer1sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_timer2sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_timer3sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_timer4sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_timer5sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_wwdgtsam: {=bool:?}, tzpcu_tzspc_sam_cfg0_fwdgtsam: {=bool:?}, tzpcu_tzspc_sam_cfg0_spi1sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_usart1sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_usart2sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_i2c0sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_i2c1sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_usbfssam: {=bool:?}, tzpcu_tzspc_sam_cfg0_timer0sam: {=bool:?}, tzpcu_tzspc_sam_cfg0_spi0sam: {=bool:?} }}" , self . tzpcu_tzspc_sam_cfg0_timer1sam () , self . tzpcu_tzspc_sam_cfg0_timer2sam () , self . tzpcu_tzspc_sam_cfg0_timer3sam () , self . tzpcu_tzspc_sam_cfg0_timer4sam () , self . tzpcu_tzspc_sam_cfg0_timer5sam () , self . tzpcu_tzspc_sam_cfg0_wwdgtsam () , self . tzpcu_tzspc_sam_cfg0_fwdgtsam () , self . tzpcu_tzspc_sam_cfg0_spi1sam () , self . tzpcu_tzspc_sam_cfg0_usart1sam () , self . tzpcu_tzspc_sam_cfg0_usart2sam () , self . tzpcu_tzspc_sam_cfg0_i2c0sam () , self . tzpcu_tzspc_sam_cfg0_i2c1sam () , self . tzpcu_tzspc_sam_cfg0_usbfssam () , self . tzpcu_tzspc_sam_cfg0_timer0sam () , self . tzpcu_tzspc_sam_cfg0_spi0sam ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcSamCfg1 (pub u32) ; impl TzpcuTzspcSamCfg1 { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_usart0sam (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_usart0sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_timer15sam (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_timer15sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_timer16sam (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_timer16sam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_hpdfsam (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_hpdfsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_crcsam (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_crcsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_tsisam (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_tsisam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_icachesam (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_icachesam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_adcsam (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_adcsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_causam (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_causam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_hausam (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_hausam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_trngsam (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_trngsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_pkcausam (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_pkcausam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg1_sdiosam (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg1_sdiosam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for TzpcuTzspcSamCfg1 { # [inline (always)]
fn default () -> TzpcuTzspcSamCfg1 { TzpcuTzspcSamCfg1 (0) } } impl core :: fmt :: Debug for TzpcuTzspcSamCfg1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcSamCfg1") . field ("tzpcu_tzspc_sam_cfg1_usart0sam" , & self . tzpcu_tzspc_sam_cfg1_usart0sam ()) . field ("tzpcu_tzspc_sam_cfg1_timer15sam" , & self . tzpcu_tzspc_sam_cfg1_timer15sam ()) . field ("tzpcu_tzspc_sam_cfg1_timer16sam" , & self . tzpcu_tzspc_sam_cfg1_timer16sam ()) . field ("tzpcu_tzspc_sam_cfg1_hpdfsam" , & self . tzpcu_tzspc_sam_cfg1_hpdfsam ()) . field ("tzpcu_tzspc_sam_cfg1_crcsam" , & self . tzpcu_tzspc_sam_cfg1_crcsam ()) . field ("tzpcu_tzspc_sam_cfg1_tsisam" , & self . tzpcu_tzspc_sam_cfg1_tsisam ()) . field ("tzpcu_tzspc_sam_cfg1_icachesam" , & self . tzpcu_tzspc_sam_cfg1_icachesam ()) . field ("tzpcu_tzspc_sam_cfg1_adcsam" , & self . tzpcu_tzspc_sam_cfg1_adcsam ()) . field ("tzpcu_tzspc_sam_cfg1_causam" , & self . tzpcu_tzspc_sam_cfg1_causam ()) . field ("tzpcu_tzspc_sam_cfg1_hausam" , & self . tzpcu_tzspc_sam_cfg1_hausam ()) . field ("tzpcu_tzspc_sam_cfg1_trngsam" , & self . tzpcu_tzspc_sam_cfg1_trngsam ()) . field ("tzpcu_tzspc_sam_cfg1_pkcausam" , & self . tzpcu_tzspc_sam_cfg1_pkcausam ()) . field ("tzpcu_tzspc_sam_cfg1_sdiosam" , & self . tzpcu_tzspc_sam_cfg1_sdiosam ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcSamCfg1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcSamCfg1 {{ tzpcu_tzspc_sam_cfg1_usart0sam: {=bool:?}, tzpcu_tzspc_sam_cfg1_timer15sam: {=bool:?}, tzpcu_tzspc_sam_cfg1_timer16sam: {=bool:?}, tzpcu_tzspc_sam_cfg1_hpdfsam: {=bool:?}, tzpcu_tzspc_sam_cfg1_crcsam: {=bool:?}, tzpcu_tzspc_sam_cfg1_tsisam: {=bool:?}, tzpcu_tzspc_sam_cfg1_icachesam: {=bool:?}, tzpcu_tzspc_sam_cfg1_adcsam: {=bool:?}, tzpcu_tzspc_sam_cfg1_causam: {=bool:?}, tzpcu_tzspc_sam_cfg1_hausam: {=bool:?}, tzpcu_tzspc_sam_cfg1_trngsam: {=bool:?}, tzpcu_tzspc_sam_cfg1_pkcausam: {=bool:?}, tzpcu_tzspc_sam_cfg1_sdiosam: {=bool:?} }}" , self . tzpcu_tzspc_sam_cfg1_usart0sam () , self . tzpcu_tzspc_sam_cfg1_timer15sam () , self . tzpcu_tzspc_sam_cfg1_timer16sam () , self . tzpcu_tzspc_sam_cfg1_hpdfsam () , self . tzpcu_tzspc_sam_cfg1_crcsam () , self . tzpcu_tzspc_sam_cfg1_tsisam () , self . tzpcu_tzspc_sam_cfg1_icachesam () , self . tzpcu_tzspc_sam_cfg1_adcsam () , self . tzpcu_tzspc_sam_cfg1_causam () , self . tzpcu_tzspc_sam_cfg1_hausam () , self . tzpcu_tzspc_sam_cfg1_trngsam () , self . tzpcu_tzspc_sam_cfg1_pkcausam () , self . tzpcu_tzspc_sam_cfg1_sdiosam ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct TzpcuTzspcSamCfg2 (pub u32) ; impl TzpcuTzspcSamCfg2 { # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_efusesam (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_efusesam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_sqpi_psramregsam (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_sqpi_psramregsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_qspi_flashregsam (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_qspi_flashregsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_wifi_rfsam (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_wifi_rfsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_i2s1_addsam (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_i2s1_addsam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_dcisam (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_dcisam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [must_use]
# [inline (always)]
pub const fn tzpcu_tzspc_sam_cfg2_wifisam (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_tzpcu_tzspc_sam_cfg2_wifisam (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for TzpcuTzspcSamCfg2 { # [inline (always)]
fn default () -> TzpcuTzspcSamCfg2 { TzpcuTzspcSamCfg2 (0) } } impl core :: fmt :: Debug for TzpcuTzspcSamCfg2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("TzpcuTzspcSamCfg2") . field ("tzpcu_tzspc_sam_cfg2_efusesam" , & self . tzpcu_tzspc_sam_cfg2_efusesam ()) . field ("tzpcu_tzspc_sam_cfg2_sqpi_psramregsam" , & self . tzpcu_tzspc_sam_cfg2_sqpi_psramregsam ()) . field ("tzpcu_tzspc_sam_cfg2_qspi_flashregsam" , & self . tzpcu_tzspc_sam_cfg2_qspi_flashregsam ()) . field ("tzpcu_tzspc_sam_cfg2_wifi_rfsam" , & self . tzpcu_tzspc_sam_cfg2_wifi_rfsam ()) . field ("tzpcu_tzspc_sam_cfg2_i2s1_addsam" , & self . tzpcu_tzspc_sam_cfg2_i2s1_addsam ()) . field ("tzpcu_tzspc_sam_cfg2_dcisam" , & self . tzpcu_tzspc_sam_cfg2_dcisam ()) . field ("tzpcu_tzspc_sam_cfg2_wifisam" , & self . tzpcu_tzspc_sam_cfg2_wifisam ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for TzpcuTzspcSamCfg2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "TzpcuTzspcSamCfg2 {{ tzpcu_tzspc_sam_cfg2_efusesam: {=bool:?}, tzpcu_tzspc_sam_cfg2_sqpi_psramregsam: {=bool:?}, tzpcu_tzspc_sam_cfg2_qspi_flashregsam: {=bool:?}, tzpcu_tzspc_sam_cfg2_wifi_rfsam: {=bool:?}, tzpcu_tzspc_sam_cfg2_i2s1_addsam: {=bool:?}, tzpcu_tzspc_sam_cfg2_dcisam: {=bool:?}, tzpcu_tzspc_sam_cfg2_wifisam: {=bool:?} }}" , self . tzpcu_tzspc_sam_cfg2_efusesam () , self . tzpcu_tzspc_sam_cfg2_sqpi_psramregsam () , self . tzpcu_tzspc_sam_cfg2_qspi_flashregsam () , self . tzpcu_tzspc_sam_cfg2_wifi_rfsam () , self . tzpcu_tzspc_sam_cfg2_i2s1_addsam () , self . tzpcu_tzspc_sam_cfg2_dcisam () , self . tzpcu_tzspc_sam_cfg2_wifisam ()) } } }