#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]




# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Uart { ptr : * mut u8 } unsafe impl Send for Uart { } unsafe impl Sync for Uart { } impl Uart { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn uart_stat0 (self) -> crate :: common :: Reg < regs :: UartStat0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0usize) as _) } } # [inline (always)]
pub const fn uart_data (self) -> crate :: common :: Reg < regs :: UartData , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x04usize) as _) } } # [inline (always)]
pub const fn uart_baud (self) -> crate :: common :: Reg < regs :: UartBaud , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x08usize) as _) } } # [inline (always)]
pub const fn uart_ctl0 (self) -> crate :: common :: Reg < regs :: UartCtl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x0cusize) as _) } } # [inline (always)]
pub const fn uart_ctl1 (self) -> crate :: common :: Reg < regs :: UartCtl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x10usize) as _) } } # [inline (always)]
pub const fn uart_ctl2 (self) -> crate :: common :: Reg < regs :: UartCtl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x14usize) as _) } } # [inline (always)]
pub const fn uart_gp (self) -> crate :: common :: Reg < regs :: UartGp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0x18usize) as _) } } # [inline (always)]
pub const fn uart_chc (self) -> crate :: common :: Reg < regs :: UartChc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . wrapping_add (0xc0usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartBaud (pub u32) ; impl UartBaud { # [must_use]
# [inline (always)]
pub const fn uart_baud_fradiv (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_uart_baud_fradiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_baud_intdiv (& self) -> u16 { let val = (self . 0 >> 4usize) & 0xffff ; val as u16 } # [inline (always)]
pub const fn set_uart_baud_intdiv (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 4usize)) | (((val as u32) & 0xffff) << 4usize) ; } } impl Default for UartBaud { # [inline (always)]
fn default () -> UartBaud { UartBaud (0) } } impl core :: fmt :: Debug for UartBaud { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartBaud") . field ("uart_baud_fradiv" , & self . uart_baud_fradiv ()) . field ("uart_baud_intdiv" , & self . uart_baud_intdiv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartBaud { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartBaud {{ uart_baud_fradiv: {=u8:?}, uart_baud_intdiv: {=u16:?} }}" , self . uart_baud_fradiv () , self . uart_baud_intdiv ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartChc (pub u32) ; impl UartChc { # [must_use]
# [inline (always)]
pub const fn uart_chc_pcm (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_chc_pcm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_chc_eperr (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_chc_eperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for UartChc { # [inline (always)]
fn default () -> UartChc { UartChc (0) } } impl core :: fmt :: Debug for UartChc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartChc") . field ("uart_chc_pcm" , & self . uart_chc_pcm ()) . field ("uart_chc_eperr" , & self . uart_chc_eperr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartChc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartChc {{ uart_chc_pcm: {=bool:?}, uart_chc_eperr: {=bool:?} }}" , self . uart_chc_pcm () , self . uart_chc_eperr ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartCtl0 (pub u32) ; impl UartCtl0 { # [must_use]
# [inline (always)]
pub const fn uart_ctl0_sbkcmd (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_sbkcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_rwu (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_rwu (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_ren (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_ren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_ten (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_ten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_idleie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_idleie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_rbneie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_rbneie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_tcie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_tcie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_tbeie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_tbeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_perrie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_perrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_pm (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_pcen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_wm (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_wm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_wl0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_wl0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_men (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_men (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_uen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_uen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_ovsmod (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_ovsmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl0_wl1 (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl0_wl1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } } impl Default for UartCtl0 { # [inline (always)]
fn default () -> UartCtl0 { UartCtl0 (0) } } impl core :: fmt :: Debug for UartCtl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartCtl0") . field ("uart_ctl0_sbkcmd" , & self . uart_ctl0_sbkcmd ()) . field ("uart_ctl0_rwu" , & self . uart_ctl0_rwu ()) . field ("uart_ctl0_ren" , & self . uart_ctl0_ren ()) . field ("uart_ctl0_ten" , & self . uart_ctl0_ten ()) . field ("uart_ctl0_idleie" , & self . uart_ctl0_idleie ()) . field ("uart_ctl0_rbneie" , & self . uart_ctl0_rbneie ()) . field ("uart_ctl0_tcie" , & self . uart_ctl0_tcie ()) . field ("uart_ctl0_tbeie" , & self . uart_ctl0_tbeie ()) . field ("uart_ctl0_perrie" , & self . uart_ctl0_perrie ()) . field ("uart_ctl0_pm" , & self . uart_ctl0_pm ()) . field ("uart_ctl0_pcen" , & self . uart_ctl0_pcen ()) . field ("uart_ctl0_wm" , & self . uart_ctl0_wm ()) . field ("uart_ctl0_wl0" , & self . uart_ctl0_wl0 ()) . field ("uart_ctl0_men" , & self . uart_ctl0_men ()) . field ("uart_ctl0_uen" , & self . uart_ctl0_uen ()) . field ("uart_ctl0_ovsmod" , & self . uart_ctl0_ovsmod ()) . field ("uart_ctl0_wl1" , & self . uart_ctl0_wl1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartCtl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartCtl0 {{ uart_ctl0_sbkcmd: {=bool:?}, uart_ctl0_rwu: {=bool:?}, uart_ctl0_ren: {=bool:?}, uart_ctl0_ten: {=bool:?}, uart_ctl0_idleie: {=bool:?}, uart_ctl0_rbneie: {=bool:?}, uart_ctl0_tcie: {=bool:?}, uart_ctl0_tbeie: {=bool:?}, uart_ctl0_perrie: {=bool:?}, uart_ctl0_pm: {=bool:?}, uart_ctl0_pcen: {=bool:?}, uart_ctl0_wm: {=bool:?}, uart_ctl0_wl0: {=bool:?}, uart_ctl0_men: {=bool:?}, uart_ctl0_uen: {=bool:?}, uart_ctl0_ovsmod: {=bool:?}, uart_ctl0_wl1: {=bool:?} }}" , self . uart_ctl0_sbkcmd () , self . uart_ctl0_rwu () , self . uart_ctl0_ren () , self . uart_ctl0_ten () , self . uart_ctl0_idleie () , self . uart_ctl0_rbneie () , self . uart_ctl0_tcie () , self . uart_ctl0_tbeie () , self . uart_ctl0_perrie () , self . uart_ctl0_pm () , self . uart_ctl0_pcen () , self . uart_ctl0_wm () , self . uart_ctl0_wl0 () , self . uart_ctl0_men () , self . uart_ctl0_uen () , self . uart_ctl0_ovsmod () , self . uart_ctl0_wl1 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartCtl1 (pub u32) ; impl UartCtl1 { # [must_use]
# [inline (always)]
pub const fn uart_ctl1_addr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [inline (always)]
pub const fn set_uart_ctl1_addr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl1_lblen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl1_lblen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl1_lbdie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl1_lbdie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl1_stb (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [inline (always)]
pub const fn set_uart_ctl1_stb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl1_lmen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl1_lmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } } impl Default for UartCtl1 { # [inline (always)]
fn default () -> UartCtl1 { UartCtl1 (0) } } impl core :: fmt :: Debug for UartCtl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartCtl1") . field ("uart_ctl1_addr" , & self . uart_ctl1_addr ()) . field ("uart_ctl1_lblen" , & self . uart_ctl1_lblen ()) . field ("uart_ctl1_lbdie" , & self . uart_ctl1_lbdie ()) . field ("uart_ctl1_stb" , & self . uart_ctl1_stb ()) . field ("uart_ctl1_lmen" , & self . uart_ctl1_lmen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartCtl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartCtl1 {{ uart_ctl1_addr: {=u8:?}, uart_ctl1_lblen: {=bool:?}, uart_ctl1_lbdie: {=bool:?}, uart_ctl1_stb: {=u8:?}, uart_ctl1_lmen: {=bool:?} }}" , self . uart_ctl1_addr () , self . uart_ctl1_lblen () , self . uart_ctl1_lbdie () , self . uart_ctl1_stb () , self . uart_ctl1_lmen ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartCtl2 (pub u32) ; impl UartCtl2 { # [must_use]
# [inline (always)]
pub const fn uart_ctl2_errie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_iren (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_iren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_irlp (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_irlp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_hden (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_hden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_denr (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_denr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_dent (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_dent (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_osb (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_osb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_rinv (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_rinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_tinv (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_tinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_dinv (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_dinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_ctl2_msbf (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_ctl2_msbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for UartCtl2 { # [inline (always)]
fn default () -> UartCtl2 { UartCtl2 (0) } } impl core :: fmt :: Debug for UartCtl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartCtl2") . field ("uart_ctl2_errie" , & self . uart_ctl2_errie ()) . field ("uart_ctl2_iren" , & self . uart_ctl2_iren ()) . field ("uart_ctl2_irlp" , & self . uart_ctl2_irlp ()) . field ("uart_ctl2_hden" , & self . uart_ctl2_hden ()) . field ("uart_ctl2_denr" , & self . uart_ctl2_denr ()) . field ("uart_ctl2_dent" , & self . uart_ctl2_dent ()) . field ("uart_ctl2_osb" , & self . uart_ctl2_osb ()) . field ("uart_ctl2_rinv" , & self . uart_ctl2_rinv ()) . field ("uart_ctl2_tinv" , & self . uart_ctl2_tinv ()) . field ("uart_ctl2_dinv" , & self . uart_ctl2_dinv ()) . field ("uart_ctl2_msbf" , & self . uart_ctl2_msbf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartCtl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartCtl2 {{ uart_ctl2_errie: {=bool:?}, uart_ctl2_iren: {=bool:?}, uart_ctl2_irlp: {=bool:?}, uart_ctl2_hden: {=bool:?}, uart_ctl2_denr: {=bool:?}, uart_ctl2_dent: {=bool:?}, uart_ctl2_osb: {=bool:?}, uart_ctl2_rinv: {=bool:?}, uart_ctl2_tinv: {=bool:?}, uart_ctl2_dinv: {=bool:?}, uart_ctl2_msbf: {=bool:?} }}" , self . uart_ctl2_errie () , self . uart_ctl2_iren () , self . uart_ctl2_irlp () , self . uart_ctl2_hden () , self . uart_ctl2_denr () , self . uart_ctl2_dent () , self . uart_ctl2_osb () , self . uart_ctl2_rinv () , self . uart_ctl2_tinv () , self . uart_ctl2_dinv () , self . uart_ctl2_msbf ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartData (pub u32) ; impl UartData { # [must_use]
# [inline (always)]
pub const fn uart_data_data (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x03ff ; val as u16 } # [inline (always)]
pub const fn set_uart_data_data (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x03ff << 0usize)) | (((val as u32) & 0x03ff) << 0usize) ; } } impl Default for UartData { # [inline (always)]
fn default () -> UartData { UartData (0) } } impl core :: fmt :: Debug for UartData { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartData") . field ("uart_data_data" , & self . uart_data_data ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartData { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartData {{ uart_data_data: {=u16:?} }}" , self . uart_data_data ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartGp (pub u32) ; impl UartGp { # [must_use]
# [inline (always)]
pub const fn uart_gp_psc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [inline (always)]
pub const fn set_uart_gp_psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } } impl Default for UartGp { # [inline (always)]
fn default () -> UartGp { UartGp (0) } } impl core :: fmt :: Debug for UartGp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartGp") . field ("uart_gp_psc" , & self . uart_gp_psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartGp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartGp {{ uart_gp_psc: {=u8:?} }}" , self . uart_gp_psc ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UartStat0 (pub u32) ; impl UartStat0 { # [must_use]
# [inline (always)]
pub const fn uart_stat0_perr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_perr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_ferr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_ferr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_nerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_nerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_orerr (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_orerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_idlef (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_idlef (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_rbne (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_rbne (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_tc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_tc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_tbe (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_tbe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [must_use]
# [inline (always)]
pub const fn uart_stat0_lbdf (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [inline (always)]
pub const fn set_uart_stat0_lbdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for UartStat0 { # [inline (always)]
fn default () -> UartStat0 { UartStat0 (0) } } impl core :: fmt :: Debug for UartStat0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("UartStat0") . field ("uart_stat0_perr" , & self . uart_stat0_perr ()) . field ("uart_stat0_ferr" , & self . uart_stat0_ferr ()) . field ("uart_stat0_nerr" , & self . uart_stat0_nerr ()) . field ("uart_stat0_orerr" , & self . uart_stat0_orerr ()) . field ("uart_stat0_idlef" , & self . uart_stat0_idlef ()) . field ("uart_stat0_rbne" , & self . uart_stat0_rbne ()) . field ("uart_stat0_tc" , & self . uart_stat0_tc ()) . field ("uart_stat0_tbe" , & self . uart_stat0_tbe ()) . field ("uart_stat0_lbdf" , & self . uart_stat0_lbdf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for UartStat0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "UartStat0 {{ uart_stat0_perr: {=bool:?}, uart_stat0_ferr: {=bool:?}, uart_stat0_nerr: {=bool:?}, uart_stat0_orerr: {=bool:?}, uart_stat0_idlef: {=bool:?}, uart_stat0_rbne: {=bool:?}, uart_stat0_tc: {=bool:?}, uart_stat0_tbe: {=bool:?}, uart_stat0_lbdf: {=bool:?} }}" , self . uart_stat0_perr () , self . uart_stat0_ferr () , self . uart_stat0_nerr () , self . uart_stat0_orerr () , self . uart_stat0_idlef () , self . uart_stat0_rbne () , self . uart_stat0_tc () , self . uart_stat0_tbe () , self . uart_stat0_lbdf ()) } } }