#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Universal synchronous asynchronous receiver transmitter"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Usart1 { ptr : * mut u8 } unsafe impl Send for Usart1 { } unsafe impl Sync for Usart1 { } impl Usart1 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Control register 2"]
# [inline (always)]
pub const fn ctl2 (self) -> crate :: common :: Reg < regs :: Ctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Baud rate register"]
# [inline (always)]
pub const fn baud (self) -> crate :: common :: Reg < regs :: Baud , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Command register"]
# [inline (always)]
pub const fn cmd (self) -> crate :: common :: Reg < regs :: Cmd , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Interrupt & status register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Interrupt flag clear register"]
# [inline (always)]
pub const fn intc (self) -> crate :: common :: Reg < regs :: Intc , crate :: common :: W > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Receive data register"]
# [inline (always)]
pub const fn rdata (self) -> crate :: common :: Reg < regs :: Rdata , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Transmit data register"]
# [inline (always)]
pub const fn tdata (self) -> crate :: common :: Reg < regs :: Tdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "coherence control register"]
# [inline (always)]
pub const fn chc (self) -> crate :: common :: Reg < regs :: Chc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xc0usize) as _) } } # [doc = "USART receive FIFO control and status register"]
# [inline (always)]
pub const fn rfcs (self) -> crate :: common :: Reg < regs :: Rfcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xd0usize) as _) } } } pub mod regs { # [doc = "Baud rate register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Baud (pub u32) ; impl Baud { # [doc = "integer of baud-rate divider"]
# [inline (always)]
pub const fn brr_fra (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "integer of baud-rate divider"]
# [inline (always)]
pub fn set_brr_fra (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "integer of baud-rate divider"]
# [inline (always)]
pub const fn brr_int (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x0fff ; val as u16 } # [doc = "integer of baud-rate divider"]
# [inline (always)]
pub fn set_brr_int (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 4usize)) | (((val as u32) & 0x0fff) << 4usize) ; } } impl Default for Baud { # [inline (always)]
fn default () -> Baud { Baud (0) } } impl core :: fmt :: Debug for Baud { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Baud") . field ("brr_fra" , & self . brr_fra ()) . field ("brr_int" , & self . brr_int ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Baud { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Baud {{ brr_fra: {=u8:?}, brr_int: {=u16:?} }}" , self . brr_fra () , self . brr_int ()) } } # [doc = "coherence control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chc (pub u32) ; impl Chc { # [doc = "Hardware flow control coherence mode"]
# [inline (always)]
pub const fn hcm (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Hardware flow control coherence mode"]
# [inline (always)]
pub fn set_hcm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Early parity error flag"]
# [inline (always)]
pub const fn eperr (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Early parity error flag"]
# [inline (always)]
pub fn set_eperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for Chc { # [inline (always)]
fn default () -> Chc { Chc (0) } } impl core :: fmt :: Debug for Chc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chc") . field ("hcm" , & self . hcm ()) . field ("eperr" , & self . eperr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chc {{ hcm: {=bool:?}, eperr: {=bool:?} }}" , self . hcm () , self . eperr ()) } } # [doc = "Command register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cmd (pub u32) ; impl Cmd { # [doc = "Send break request"]
# [inline (always)]
pub const fn sbkcmd (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Send break request"]
# [inline (always)]
pub fn set_sbkcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Mute mode request"]
# [inline (always)]
pub const fn mmcmd (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Mute mode request"]
# [inline (always)]
pub fn set_mmcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Receive data flush request"]
# [inline (always)]
pub const fn rxfcmd (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Receive data flush request"]
# [inline (always)]
pub fn set_rxfcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for Cmd { # [inline (always)]
fn default () -> Cmd { Cmd (0) } } impl core :: fmt :: Debug for Cmd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cmd") . field ("sbkcmd" , & self . sbkcmd ()) . field ("mmcmd" , & self . mmcmd ()) . field ("rxfcmd" , & self . rxfcmd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cmd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cmd {{ sbkcmd: {=bool:?}, mmcmd: {=bool:?}, rxfcmd: {=bool:?} }}" , self . sbkcmd () , self . mmcmd () , self . rxfcmd ()) } } # [doc = "Control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "USART enable"]
# [inline (always)]
pub const fn uen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "USART enable"]
# [inline (always)]
pub fn set_uen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Receiver enable"]
# [inline (always)]
pub const fn ren (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Receiver enable"]
# [inline (always)]
pub fn set_ren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Transmitter enable"]
# [inline (always)]
pub const fn ten (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Transmitter enable"]
# [inline (always)]
pub fn set_ten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "IDLE interrupt enable"]
# [inline (always)]
pub const fn idleie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "IDLE interrupt enable"]
# [inline (always)]
pub fn set_idleie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "RXNE interrupt enable"]
# [inline (always)]
pub const fn rbneie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "RXNE interrupt enable"]
# [inline (always)]
pub fn set_rbneie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Transmission complete interrupt enable"]
# [inline (always)]
pub const fn tcie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmission complete interrupt enable"]
# [inline (always)]
pub fn set_tcie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "interrupt enable"]
# [inline (always)]
pub const fn tbeie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "interrupt enable"]
# [inline (always)]
pub fn set_tbeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "PE interrupt enable"]
# [inline (always)]
pub const fn perrie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "PE interrupt enable"]
# [inline (always)]
pub fn set_perrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Parity selection"]
# [inline (always)]
pub const fn pm (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Parity selection"]
# [inline (always)]
pub fn set_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Parity control enable"]
# [inline (always)]
pub const fn pcen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Parity control enable"]
# [inline (always)]
pub fn set_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Receiver wakeup method"]
# [inline (always)]
pub const fn wm (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Receiver wakeup method"]
# [inline (always)]
pub fn set_wm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Word length"]
# [inline (always)]
pub const fn wl (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Word length"]
# [inline (always)]
pub fn set_wl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Mute mode enable"]
# [inline (always)]
pub const fn men (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Mute mode enable"]
# [inline (always)]
pub fn set_men (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Character match interrupt enable"]
# [inline (always)]
pub const fn amie (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Character match interrupt enable"]
# [inline (always)]
pub fn set_amie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Oversampling mode"]
# [inline (always)]
pub const fn ovsmod (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Oversampling mode"]
# [inline (always)]
pub fn set_ovsmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Driver Enable deassertion time"]
# [inline (always)]
pub const fn ded (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x1f ; val as u8 } # [doc = "Driver Enable deassertion time"]
# [inline (always)]
pub fn set_ded (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 16usize)) | (((val as u32) & 0x1f) << 16usize) ; } # [doc = "Driver Enable assertion time"]
# [inline (always)]
pub const fn dea (& self) -> u8 { let val = (self . 0 >> 21usize) & 0x1f ; val as u8 } # [doc = "Driver Enable assertion time"]
# [inline (always)]
pub fn set_dea (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 21usize)) | (((val as u32) & 0x1f) << 21usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("uen" , & self . uen ()) . field ("ren" , & self . ren ()) . field ("ten" , & self . ten ()) . field ("idleie" , & self . idleie ()) . field ("rbneie" , & self . rbneie ()) . field ("tcie" , & self . tcie ()) . field ("tbeie" , & self . tbeie ()) . field ("perrie" , & self . perrie ()) . field ("pm" , & self . pm ()) . field ("pcen" , & self . pcen ()) . field ("wm" , & self . wm ()) . field ("wl" , & self . wl ()) . field ("men" , & self . men ()) . field ("amie" , & self . amie ()) . field ("ovsmod" , & self . ovsmod ()) . field ("ded" , & self . ded ()) . field ("dea" , & self . dea ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ uen: {=bool:?}, ren: {=bool:?}, ten: {=bool:?}, idleie: {=bool:?}, rbneie: {=bool:?}, tcie: {=bool:?}, tbeie: {=bool:?}, perrie: {=bool:?}, pm: {=bool:?}, pcen: {=bool:?}, wm: {=bool:?}, wl: {=bool:?}, men: {=bool:?}, amie: {=bool:?}, ovsmod: {=bool:?}, ded: {=u8:?}, dea: {=u8:?} }}" , self . uen () , self . ren () , self . ten () , self . idleie () , self . rbneie () , self . tcie () , self . tbeie () , self . perrie () , self . pm () , self . pcen () , self . wm () , self . wl () , self . men () , self . amie () , self . ovsmod () , self . ded () , self . dea ()) } } # [doc = "Control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "7-bit Address Detection/4-bit Address Detection"]
# [inline (always)]
pub const fn addm (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "7-bit Address Detection/4-bit Address Detection"]
# [inline (always)]
pub fn set_addm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Last bit clock pulse"]
# [inline (always)]
pub const fn clen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Last bit clock pulse"]
# [inline (always)]
pub fn set_clen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Clock phase"]
# [inline (always)]
pub const fn cph (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Clock phase"]
# [inline (always)]
pub fn set_cph (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Clock polarity"]
# [inline (always)]
pub const fn cpl (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Clock polarity"]
# [inline (always)]
pub fn set_cpl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "STOP bits"]
# [inline (always)]
pub const fn stb (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "STOP bits"]
# [inline (always)]
pub fn set_stb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Swap TX/RX pins"]
# [inline (always)]
pub const fn strp (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Swap TX/RX pins"]
# [inline (always)]
pub fn set_strp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "RX pin active level inversion"]
# [inline (always)]
pub const fn rinv (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "RX pin active level inversion"]
# [inline (always)]
pub fn set_rinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TX pin active level inversion"]
# [inline (always)]
pub const fn tinv (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "TX pin active level inversion"]
# [inline (always)]
pub fn set_tinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Data bit level inversion"]
# [inline (always)]
pub const fn dinv (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Data bit level inversion"]
# [inline (always)]
pub fn set_dinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Most significant bit first"]
# [inline (always)]
pub const fn msbf (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Most significant bit first"]
# [inline (always)]
pub fn set_msbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Address of the USART terminal"]
# [inline (always)]
pub const fn addr (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Address of the USART terminal"]
# [inline (always)]
pub fn set_addr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("addm" , & self . addm ()) . field ("clen" , & self . clen ()) . field ("cph" , & self . cph ()) . field ("cpl" , & self . cpl ()) . field ("stb" , & self . stb ()) . field ("strp" , & self . strp ()) . field ("rinv" , & self . rinv ()) . field ("tinv" , & self . tinv ()) . field ("dinv" , & self . dinv ()) . field ("msbf" , & self . msbf ()) . field ("addr" , & self . addr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ addm: {=bool:?}, clen: {=bool:?}, cph: {=bool:?}, cpl: {=bool:?}, stb: {=u8:?}, strp: {=bool:?}, rinv: {=bool:?}, tinv: {=bool:?}, dinv: {=bool:?}, msbf: {=bool:?}, addr: {=u8:?} }}" , self . addm () , self . clen () , self . cph () , self . cpl () , self . stb () , self . strp () , self . rinv () , self . tinv () , self . dinv () , self . msbf () , self . addr ()) } } # [doc = "Control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl2 (pub u32) ; impl Ctl2 { # [doc = "Error interrupt enable"]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Error interrupt enable"]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Half-duplex selection"]
# [inline (always)]
pub const fn hden (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Half-duplex selection"]
# [inline (always)]
pub fn set_hden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "DMA enable receiver"]
# [inline (always)]
pub const fn denr (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "DMA enable receiver"]
# [inline (always)]
pub fn set_denr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "DMA enable transmitter"]
# [inline (always)]
pub const fn dent (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "DMA enable transmitter"]
# [inline (always)]
pub fn set_dent (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "RTS enable"]
# [inline (always)]
pub const fn rtsen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "RTS enable"]
# [inline (always)]
pub fn set_rtsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "CTS enable"]
# [inline (always)]
pub const fn ctsen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "CTS enable"]
# [inline (always)]
pub fn set_ctsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "CTS interrupt enable"]
# [inline (always)]
pub const fn ctsie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "CTS interrupt enable"]
# [inline (always)]
pub fn set_ctsie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "One sample bit method enable"]
# [inline (always)]
pub const fn osb (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "One sample bit method enable"]
# [inline (always)]
pub fn set_osb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Overrun Disable"]
# [inline (always)]
pub const fn ovrd (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Overrun Disable"]
# [inline (always)]
pub fn set_ovrd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "DMA Disable on Reception Error"]
# [inline (always)]
pub const fn ddre (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "DMA Disable on Reception Error"]
# [inline (always)]
pub fn set_ddre (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Driver enable mode"]
# [inline (always)]
pub const fn dem (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Driver enable mode"]
# [inline (always)]
pub fn set_dem (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Driver enable polarity selection"]
# [inline (always)]
pub const fn dep (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Driver enable polarity selection"]
# [inline (always)]
pub fn set_dep (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Ctl2 { # [inline (always)]
fn default () -> Ctl2 { Ctl2 (0) } } impl core :: fmt :: Debug for Ctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl2") . field ("errie" , & self . errie ()) . field ("hden" , & self . hden ()) . field ("denr" , & self . denr ()) . field ("dent" , & self . dent ()) . field ("rtsen" , & self . rtsen ()) . field ("ctsen" , & self . ctsen ()) . field ("ctsie" , & self . ctsie ()) . field ("osb" , & self . osb ()) . field ("ovrd" , & self . ovrd ()) . field ("ddre" , & self . ddre ()) . field ("dem" , & self . dem ()) . field ("dep" , & self . dep ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl2 {{ errie: {=bool:?}, hden: {=bool:?}, denr: {=bool:?}, dent: {=bool:?}, rtsen: {=bool:?}, ctsen: {=bool:?}, ctsie: {=bool:?}, osb: {=bool:?}, ovrd: {=bool:?}, ddre: {=bool:?}, dem: {=bool:?}, dep: {=bool:?} }}" , self . errie () , self . hden () , self . denr () , self . dent () , self . rtsen () , self . ctsen () , self . ctsie () , self . osb () , self . ovrd () , self . ddre () , self . dem () , self . dep ()) } } # [doc = "Interrupt flag clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intc (pub u32) ; impl Intc { # [doc = "Parity error clear flag"]
# [inline (always)]
pub const fn pec (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Parity error clear flag"]
# [inline (always)]
pub fn set_pec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Frame error clear flag"]
# [inline (always)]
pub const fn fec (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Frame error clear flag"]
# [inline (always)]
pub fn set_fec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Noise detected clear flag"]
# [inline (always)]
pub const fn nec (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Noise detected clear flag"]
# [inline (always)]
pub fn set_nec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Overrun error clear flag"]
# [inline (always)]
pub const fn orec (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Overrun error clear flag"]
# [inline (always)]
pub fn set_orec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Idle line detected clear flag"]
# [inline (always)]
pub const fn idlec (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Idle line detected clear flag"]
# [inline (always)]
pub fn set_idlec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Transmission complete clear flag"]
# [inline (always)]
pub const fn tcc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmission complete clear flag"]
# [inline (always)]
pub fn set_tcc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "CTS clear flag"]
# [inline (always)]
pub const fn ctsc (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "CTS clear flag"]
# [inline (always)]
pub fn set_ctsc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Character match clear flag"]
# [inline (always)]
pub const fn amc (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Character match clear flag"]
# [inline (always)]
pub fn set_amc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } } impl Default for Intc { # [inline (always)]
fn default () -> Intc { Intc (0) } } impl core :: fmt :: Debug for Intc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intc") . field ("pec" , & self . pec ()) . field ("fec" , & self . fec ()) . field ("nec" , & self . nec ()) . field ("orec" , & self . orec ()) . field ("idlec" , & self . idlec ()) . field ("tcc" , & self . tcc ()) . field ("ctsc" , & self . ctsc ()) . field ("amc" , & self . amc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intc {{ pec: {=bool:?}, fec: {=bool:?}, nec: {=bool:?}, orec: {=bool:?}, idlec: {=bool:?}, tcc: {=bool:?}, ctsc: {=bool:?}, amc: {=bool:?} }}" , self . pec () , self . fec () , self . nec () , self . orec () , self . idlec () , self . tcc () , self . ctsc () , self . amc ()) } } # [doc = "Receive data register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rdata (pub u32) ; impl Rdata { # [doc = "Receive data value"]
# [inline (always)]
pub const fn rdata (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x01ff ; val as u16 } # [doc = "Receive data value"]
# [inline (always)]
pub fn set_rdata (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x01ff << 0usize)) | (((val as u32) & 0x01ff) << 0usize) ; } } impl Default for Rdata { # [inline (always)]
fn default () -> Rdata { Rdata (0) } } impl core :: fmt :: Debug for Rdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rdata") . field ("rdata" , & self . rdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rdata {{ rdata: {=u16:?} }}" , self . rdata ()) } } # [doc = "USART receive FIFO control and status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rfcs (pub u32) ; impl Rfcs { # [doc = "Receive FIFO enable"]
# [inline (always)]
pub const fn rfen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO enable"]
# [inline (always)]
pub fn set_rfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Receive FIFO full interrupt enable"]
# [inline (always)]
pub const fn rffie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO full interrupt enable"]
# [inline (always)]
pub fn set_rffie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Receive FIFO empty flag"]
# [inline (always)]
pub const fn rfe (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO empty flag"]
# [inline (always)]
pub fn set_rfe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Receive FIFO full flag"]
# [inline (always)]
pub const fn rff (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO full flag"]
# [inline (always)]
pub fn set_rff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Receive FIFO count number"]
# [inline (always)]
pub const fn rfcnt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Receive FIFO count number"]
# [inline (always)]
pub fn set_rfcnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Receive FIFO full interrupt flag"]
# [inline (always)]
pub const fn rffint (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO full interrupt flag"]
# [inline (always)]
pub fn set_rffint (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Rfcs { # [inline (always)]
fn default () -> Rfcs { Rfcs (0) } } impl core :: fmt :: Debug for Rfcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rfcs") . field ("rfen" , & self . rfen ()) . field ("rffie" , & self . rffie ()) . field ("rfe" , & self . rfe ()) . field ("rff" , & self . rff ()) . field ("rfcnt" , & self . rfcnt ()) . field ("rffint" , & self . rffint ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rfcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rfcs {{ rfen: {=bool:?}, rffie: {=bool:?}, rfe: {=bool:?}, rff: {=bool:?}, rfcnt: {=u8:?}, rffint: {=bool:?} }}" , self . rfen () , self . rffie () , self . rfe () , self . rff () , self . rfcnt () , self . rffint ()) } } # [doc = "Interrupt & status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "Parity error"]
# [inline (always)]
pub const fn perr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Parity error"]
# [inline (always)]
pub fn set_perr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Framing error"]
# [inline (always)]
pub const fn ferr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Framing error"]
# [inline (always)]
pub fn set_ferr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Noise detected flag"]
# [inline (always)]
pub const fn nerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Noise detected flag"]
# [inline (always)]
pub fn set_nerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Overrun error"]
# [inline (always)]
pub const fn orerr (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Overrun error"]
# [inline (always)]
pub fn set_orerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Idle line detected"]
# [inline (always)]
pub const fn idlef (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Idle line detected"]
# [inline (always)]
pub fn set_idlef (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Read data register not empty"]
# [inline (always)]
pub const fn rbne (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Read data register not empty"]
# [inline (always)]
pub fn set_rbne (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Transmission complete"]
# [inline (always)]
pub const fn tc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmission complete"]
# [inline (always)]
pub fn set_tc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Transmit data register empty"]
# [inline (always)]
pub const fn tbe (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Transmit data register empty"]
# [inline (always)]
pub fn set_tbe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "CTS interrupt flag"]
# [inline (always)]
pub const fn ctsf (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "CTS interrupt flag"]
# [inline (always)]
pub fn set_ctsf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "CTS flag"]
# [inline (always)]
pub const fn cts (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "CTS flag"]
# [inline (always)]
pub fn set_cts (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Busy flag"]
# [inline (always)]
pub const fn bsy (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Busy flag"]
# [inline (always)]
pub fn set_bsy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "character match flag"]
# [inline (always)]
pub const fn amf (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "character match flag"]
# [inline (always)]
pub fn set_amf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Send break flag"]
# [inline (always)]
pub const fn sbf (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Send break flag"]
# [inline (always)]
pub fn set_sbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Receiver wakeup from Mute mode"]
# [inline (always)]
pub const fn rwu (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Receiver wakeup from Mute mode"]
# [inline (always)]
pub fn set_rwu (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Transmit enable acknowledge flag"]
# [inline (always)]
pub const fn tea (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "Transmit enable acknowledge flag"]
# [inline (always)]
pub fn set_tea (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Receive enable acknowledge flag"]
# [inline (always)]
pub const fn rea (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Receive enable acknowledge flag"]
# [inline (always)]
pub fn set_rea (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } impl core :: fmt :: Debug for Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat") . field ("perr" , & self . perr ()) . field ("ferr" , & self . ferr ()) . field ("nerr" , & self . nerr ()) . field ("orerr" , & self . orerr ()) . field ("idlef" , & self . idlef ()) . field ("rbne" , & self . rbne ()) . field ("tc" , & self . tc ()) . field ("tbe" , & self . tbe ()) . field ("ctsf" , & self . ctsf ()) . field ("cts" , & self . cts ()) . field ("bsy" , & self . bsy ()) . field ("amf" , & self . amf ()) . field ("sbf" , & self . sbf ()) . field ("rwu" , & self . rwu ()) . field ("tea" , & self . tea ()) . field ("rea" , & self . rea ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat {{ perr: {=bool:?}, ferr: {=bool:?}, nerr: {=bool:?}, orerr: {=bool:?}, idlef: {=bool:?}, rbne: {=bool:?}, tc: {=bool:?}, tbe: {=bool:?}, ctsf: {=bool:?}, cts: {=bool:?}, bsy: {=bool:?}, amf: {=bool:?}, sbf: {=bool:?}, rwu: {=bool:?}, tea: {=bool:?}, rea: {=bool:?} }}" , self . perr () , self . ferr () , self . nerr () , self . orerr () , self . idlef () , self . rbne () , self . tc () , self . tbe () , self . ctsf () , self . cts () , self . bsy () , self . amf () , self . sbf () , self . rwu () , self . tea () , self . rea ()) } } # [doc = "Transmit data register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tdata (pub u32) ; impl Tdata { # [doc = "Transmit data value"]
# [inline (always)]
pub const fn tdata (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x01ff ; val as u16 } # [doc = "Transmit data value"]
# [inline (always)]
pub fn set_tdata (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x01ff << 0usize)) | (((val as u32) & 0x01ff) << 0usize) ; } } impl Default for Tdata { # [inline (always)]
fn default () -> Tdata { Tdata (0) } } impl core :: fmt :: Debug for Tdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Tdata") . field ("tdata" , & self . tdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Tdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Tdata {{ tdata: {=u16:?} }}" , self . tdata ()) } } }