#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wwdgt { ptr : * mut u8 } unsafe impl Send for Wwdgt { } unsafe impl Sync for Wwdgt { } impl Wwdgt { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [inline (always)]
pub const fn wwdgt_ctl (self) -> crate :: common :: Reg < regs :: WwdgtCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [inline (always)]
pub const fn wwdgt_cfg (self) -> crate :: common :: Reg < regs :: WwdgtCfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [inline (always)]
pub const fn wwdgt_stat (self) -> crate :: common :: Reg < regs :: WwdgtStat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } } pub mod regs { # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct WwdgtCfg (pub u32) ; impl WwdgtCfg { # [inline (always)]
pub const fn wwdgt_cfg_win (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [inline (always)]
pub fn set_wwdgt_cfg_win (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } # [inline (always)]
pub const fn wwdgt_cfg_psc_0_1 (& self) -> u8 { let val = (self . 0 >> 7usize) & 0x03 ; val as u8 } # [inline (always)]
pub fn set_wwdgt_cfg_psc_0_1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 7usize)) | (((val as u32) & 0x03) << 7usize) ; } # [inline (always)]
pub const fn wwdgt_cfg_ewie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_wwdgt_cfg_ewie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [inline (always)]
pub const fn wwdgt_cfg_psc_2_3 (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x03 ; val as u8 } # [inline (always)]
pub fn set_wwdgt_cfg_psc_2_3 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 16usize)) | (((val as u32) & 0x03) << 16usize) ; } } impl Default for WwdgtCfg { # [inline (always)]
fn default () -> WwdgtCfg { WwdgtCfg (0) } } impl core :: fmt :: Debug for WwdgtCfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("WwdgtCfg") . field ("wwdgt_cfg_win" , & self . wwdgt_cfg_win ()) . field ("wwdgt_cfg_psc_0_1" , & self . wwdgt_cfg_psc_0_1 ()) . field ("wwdgt_cfg_ewie" , & self . wwdgt_cfg_ewie ()) . field ("wwdgt_cfg_psc_2_3" , & self . wwdgt_cfg_psc_2_3 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for WwdgtCfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "WwdgtCfg {{ wwdgt_cfg_win: {=u8:?}, wwdgt_cfg_psc_0_1: {=u8:?}, wwdgt_cfg_ewie: {=bool:?}, wwdgt_cfg_psc_2_3: {=u8:?} }}" , self . wwdgt_cfg_win () , self . wwdgt_cfg_psc_0_1 () , self . wwdgt_cfg_ewie () , self . wwdgt_cfg_psc_2_3 ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct WwdgtCtl (pub u32) ; impl WwdgtCtl { # [inline (always)]
pub const fn wwdgt_ctl_cnt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x7f ; val as u8 } # [inline (always)]
pub fn set_wwdgt_ctl_cnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 0usize)) | (((val as u32) & 0x7f) << 0usize) ; } # [inline (always)]
pub const fn wwdgt_ctl_wdgten (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_wwdgt_ctl_wdgten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for WwdgtCtl { # [inline (always)]
fn default () -> WwdgtCtl { WwdgtCtl (0) } } impl core :: fmt :: Debug for WwdgtCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("WwdgtCtl") . field ("wwdgt_ctl_cnt" , & self . wwdgt_ctl_cnt ()) . field ("wwdgt_ctl_wdgten" , & self . wwdgt_ctl_wdgten ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for WwdgtCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "WwdgtCtl {{ wwdgt_ctl_cnt: {=u8:?}, wwdgt_ctl_wdgten: {=bool:?} }}" , self . wwdgt_ctl_cnt () , self . wwdgt_ctl_wdgten ()) } } # [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct WwdgtStat (pub u32) ; impl WwdgtStat { # [inline (always)]
pub const fn wwdgt_stat_ewif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [inline (always)]
pub fn set_wwdgt_stat_ewif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } } impl Default for WwdgtStat { # [inline (always)]
fn default () -> WwdgtStat { WwdgtStat (0) } } impl core :: fmt :: Debug for WwdgtStat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("WwdgtStat") . field ("wwdgt_stat_ewif" , & self . wwdgt_stat_ewif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for WwdgtStat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "WwdgtStat {{ wwdgt_stat_ewif: {=bool:?} }}" , self . wwdgt_stat_ewif ()) } } }