[package]
name = "mcu-metapac"
version = "21.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/itswenb/embassy-mcu-compat-generated"
description = "厂商无关 MCU 的原生 PAC 与 metadata。"

# `cargo publish` is unable to figure out which .rs files are needed due to the include! magic.
include = [
    "**/*.rs",
    "**/*.x",
    "Cargo.toml",
    "README.md",
]

[package.metadata.docs.rs]
features = ["gd32f103c8", "pac", "metadata"]
default-target = "thumbv7m-none-eabi"
targets = []
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.embassy_docs]
features = ["pac", "metadata"]
flavors = [
    { regex_feature = "stm32f0.*", target = "thumbv6m-none-eabi" },
    { regex_feature = "stm32f1.*", target = "thumbv7m-none-eabi" },
    { regex_feature = "stm32f2.*", target = "thumbv7m-none-eabi" },
    { regex_feature = "stm32f3.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32f4.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32f7.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32c0.*", target = "thumbv6m-none-eabi" },
    { regex_feature = "stm32g0.*", target = "thumbv6m-none-eabi" },
    { regex_feature = "stm32g4.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32h5.*", target = "thumbv8m.main-none-eabihf" },
    { regex_feature = "stm32h7.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32l0.*", target = "thumbv6m-none-eabi" },
    { regex_feature = "stm32l1.*", target = "thumbv7m-none-eabi" },
    { regex_feature = "stm32l4.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32l5.*", target = "thumbv8m.main-none-eabihf" },
    { regex_feature = "stm32u0.*", target = "thumbv6m-none-eabi" },
    { regex_feature = "stm32u3.*", target = "thumbv8m.main-none-eabihf" },
    { regex_feature = "stm32u5.*", target = "thumbv8m.main-none-eabihf" },
    { regex_feature = "stm32wb0.*", target = "thumbv6m-none-eabi" },
    { regex_feature = "stm32wba.*", target = "thumbv8m.main-none-eabihf" },
    { regex_feature = "stm32wb.*", target = "thumbv7em-none-eabi" },
    { regex_feature = "stm32wl.*", target = "thumbv7em-none-eabi" },
]

[dependencies]
cortex-m = "0.7.6"
cortex-m-rt = { version = ">=0.6.15,<0.8", optional = true }
defmt = { version = "0.3.0", optional = true }

[features]
default = ["pac"]

# Build the actual PAC. Set by default.
# If you just want the metadata, unset it with `default-features = false`.
pac = []

# Build the chip metadata.
# If set, a const `stm32_metapac::METADATA` will be exported, containing all the
# metadata for the currently selected chip.
metadata = []

# Implement the `defmt::Format` trait for many types.
defmt = ["dep:defmt"]

rt = ["cortex-m-rt/device"]

# Chip-selection features
gd32a103cb = []
gd32a103rb = []
gd32a103tb = []
gd32a103vb = []
gd32a490ii = []
gd32a490ik = []
gd32a490zi = []
gd32a490zk = []
gd32a503cb = []
gd32a503cc = []
gd32a503kb = []
gd32a503kc = []
gd32a503rb = []
gd32a503rc = []
gd32a503rd = []
gd32a503vb = []
gd32a503vc = []
gd32a503vd = []
gd32a508ve = []
gd32a508ze = []
gd32a513cb = []
gd32a513cc = []
gd32a513kb = []
gd32a513kc = []
gd32a513rb = []
gd32a513rc = []
gd32a513rd = []
gd32a513vb = []
gd32a513vc = []
gd32a513vd = []
gd32c103cb = []
gd32c103cbxxa = []
gd32c103rb = []
gd32c103rbxxa = []
gd32c103tb = []
gd32c103tbxxa = []
gd32c103vb = []
gd32c113cb = []
gd32c113rb = []
gd32c113tb = []
gd32c113vb = []
gd32c211ex = []
gd32c211fx = []
gd32c211jx = []
gd32c221c8 = []
gd32c221f8 = []
gd32c221k8 = []
gd32c231c6 = []
gd32c231c8 = []
gd32c231f6 = []
gd32c231f8 = []
gd32c231g6 = []
gd32c231g8 = []
gd32c231k6 = []
gd32c231k8 = []
gd32e103c8 = []
gd32e103cb = []
gd32e103r8 = []
gd32e103rb = []
gd32e103t8 = []
gd32e103tb = []
gd32e103v8 = []
gd32e103vb = []
gd32e113c8 = []
gd32e113cb = []
gd32e113r8 = []
gd32e113rb = []
gd32e113t8 = []
gd32e113tb = []
gd32e113v8 = []
gd32e113vb = []
gd32e225cb = []
gd32e225f8 = []
gd32e225gb = []
gd32e225kb = []
gd32e230c4 = []
gd32e230c6 = []
gd32e230c8 = []
gd32e230e8 = []
gd32e230f4 = []
gd32e230f6 = []
gd32e230f8 = []
gd32e230g4 = []
gd32e230g6 = []
gd32e230g8 = []
gd32e230k4 = []
gd32e230k6 = []
gd32e230k8 = []
gd32e231c4 = []
gd32e231c6 = []
gd32e231c8 = []
gd32e231k8 = []
gd32e231t8 = []
gd32e235c4 = []
gd32e235c6 = []
gd32e235c8 = []
gd32e235cb = []
gd32e235e8 = []
gd32e235eb = []
gd32e235f4 = []
gd32e235f6 = []
gd32e235f8 = []
gd32e235fb = []
gd32e235g4 = []
gd32e235g6 = []
gd32e235g8 = []
gd32e235gb = []
gd32e235k4 = []
gd32e235k6 = []
gd32e235k8 = []
gd32e235kb = []
gd32e502cb = []
gd32e502cc = []
gd32e502kb = []
gd32e502kc = []
gd32e502rb = []
gd32e502rc = []
gd32e502rd = []
gd32e502vb = []
gd32e502vc = []
gd32e502vd = []
gd32e503cc = []
gd32e503ce = []
gd32e503rc = []
gd32e503re = []
gd32e503vc = []
gd32e503ve = []
gd32e503zc = []
gd32e503ze = []
gd32e505rb = []
gd32e505rc = []
gd32e505re = []
gd32e505vc = []
gd32e505ve = []
gd32e505zc = []
gd32e505ze = []
gd32e507rc = []
gd32e507re = []
gd32e507vc = []
gd32e507ve = []
gd32e507zc = []
gd32e507ze = []
gd32e508re = []
gd32e508ve = []
gd32e508ze = []
gd32e513cc = []
gd32e513ce = []
gd32e513rc = []
gd32e513re = []
gd32e513vc = []
gd32e513ve = []
gd32e513zc = []
gd32e513ze = []
gd32e515ce = []
gd32e515re = []
gd32e517rc = []
gd32e517re = []
gd32e517vc = []
gd32e517ve = []
gd32e517zc = []
gd32e517ze = []
gd32e518ce = []
gd32e518re = []
gd32e518ve = []
gd32e518ze = []
gd32eprtrd = []
gd32eprtre = []
gd32eprtvd = []
gd32eprtve = []
gd32f101c4 = []
gd32f101c6 = []
gd32f101c8 = []
gd32f101cb = []
gd32f101r4 = []
gd32f101r6 = []
gd32f101r8 = []
gd32f101rb = []
gd32f101rc = []
gd32f101rd = []
gd32f101re = []
gd32f101rf = []
gd32f101rg = []
gd32f101ri = []
gd32f101rk = []
gd32f101t4 = []
gd32f101t6 = []
gd32f101t8 = []
gd32f101tb = []
gd32f101v8 = []
gd32f101vb = []
gd32f101vc = []
gd32f101vd = []
gd32f101ve = []
gd32f101vf = []
gd32f101vg = []
gd32f101vi = []
gd32f101vk = []
gd32f101zc = []
gd32f101zd = []
gd32f101ze = []
gd32f101zf = []
gd32f101zg = []
gd32f101zi = []
gd32f101zk = []
gd32f103c4 = []
gd32f103c6 = []
gd32f103c8 = []
gd32f103cb = []
gd32f103r4 = []
gd32f103r6 = []
gd32f103r8 = []
gd32f103rb = []
gd32f103rc = []
gd32f103rd = []
gd32f103re = []
gd32f103rf = []
gd32f103rg = []
gd32f103ri = []
gd32f103rk = []
gd32f103t4 = []
gd32f103t6 = []
gd32f103t8 = []
gd32f103tb = []
gd32f103v8 = []
gd32f103vb = []
gd32f103vc = []
gd32f103vd = []
gd32f103ve = []
gd32f103vf = []
gd32f103vg = []
gd32f103vi = []
gd32f103vk = []
gd32f103zc = []
gd32f103zd = []
gd32f103ze = []
gd32f103zf = []
gd32f103zg = []
gd32f103zi = []
gd32f103zk = []
gd32f105r8 = []
gd32f105rb = []
gd32f105rc = []
gd32f105rd = []
gd32f105re = []
gd32f105rf = []
gd32f105rg = []
gd32f105v8 = []
gd32f105vb = []
gd32f105vc = []
gd32f105vd = []
gd32f105ve = []
gd32f105vf = []
gd32f105vg = []
gd32f105zc = []
gd32f105zd = []
gd32f105ze = []
gd32f105zf = []
gd32f105zg = []
gd32f107rb = []
gd32f107rc = []
gd32f107rd = []
gd32f107re = []
gd32f107rf = []
gd32f107rg = []
gd32f107vb = []
gd32f107vc = []
gd32f107vd = []
gd32f107ve = []
gd32f107vf = []
gd32f107vg = []
gd32f107zc = []
gd32f107zd = []
gd32f107ze = []
gd32f107zf = []
gd32f107zg = []
gd32f130c4 = []
gd32f130c6 = []
gd32f130c8 = []
gd32f130f4 = []
gd32f130f6 = []
gd32f130f8 = []
gd32f130g4 = []
gd32f130g6 = []
gd32f130g8 = []
gd32f130k4 = []
gd32f130k6 = []
gd32f130k8 = []
gd32f130r8 = []
gd32f150c4 = []
gd32f150c6 = []
gd32f150c8 = []
gd32f150g4 = []
gd32f150g6 = []
gd32f150g8 = []
gd32f150k4 = []
gd32f150k6 = []
gd32f150k8 = []
gd32f150r4 = []
gd32f150r6 = []
gd32f150r8 = []
gd32f205rc = []
gd32f205re = []
gd32f205rg = []
gd32f205rk = []
gd32f205vc = []
gd32f205ve = []
gd32f205vg = []
gd32f205vk = []
gd32f205zc = []
gd32f205ze = []
gd32f205zg = []
gd32f205zk = []
gd32f207ie = []
gd32f207ig = []
gd32f207ik = []
gd32f207rc = []
gd32f207re = []
gd32f207rg = []
gd32f207rk = []
gd32f207vc = []
gd32f207ve = []
gd32f207vg = []
gd32f207vk = []
gd32f207zc = []
gd32f207ze = []
gd32f207zg = []
gd32f207zk = []
gd32f303cb = []
gd32f303cc = []
gd32f303ce = []
gd32f303cg = []
gd32f303rb = []
gd32f303rc = []
gd32f303re = []
gd32f303rg = []
gd32f303ri = []
gd32f303rk = []
gd32f303vb = []
gd32f303vc = []
gd32f303ve = []
gd32f303vg = []
gd32f303vi = []
gd32f303vk = []
gd32f303zc = []
gd32f303ze = []
gd32f303zg = []
gd32f303zi = []
gd32f303zk = []
gd32f305rb = []
gd32f305rc = []
gd32f305re = []
gd32f305rg = []
gd32f305vc = []
gd32f305ve = []
gd32f305vg = []
gd32f305zc = []
gd32f305ze = []
gd32f305zg = []
gd32f307rc = []
gd32f307re = []
gd32f307rg = []
gd32f307vc = []
gd32f307ve = []
gd32f307vg = []
gd32f307zc = []
gd32f307ze = []
gd32f307zg = []
gd32f310c8 = []
gd32f310cb = []
gd32f310f4 = []
gd32f310f6 = []
gd32f310f8 = []
gd32f310g8 = []
gd32f310k6 = []
gd32f310k8 = []
gd32f330c4 = []
gd32f330c6 = []
gd32f330c8 = []
gd32f330cb = []
gd32f330f4 = []
gd32f330f6 = []
gd32f330f8 = []
gd32f330g4 = []
gd32f330g6 = []
gd32f330g8 = []
gd32f330k4 = []
gd32f330k6 = []
gd32f330k8 = []
gd32f330r8 = []
gd32f330rb = []
gd32f350c4 = []
gd32f350c6 = []
gd32f350c8 = []
gd32f350cb = []
gd32f350g4 = []
gd32f350g6 = []
gd32f350g8 = []
gd32f350k4 = []
gd32f350k6 = []
gd32f350k8 = []
gd32f350r4 = []
gd32f350r6 = []
gd32f350r8 = []
gd32f350rb = []
gd32f355c8 = []
gd32f355cb = []
gd32f355f8 = []
gd32f355g8 = []
gd32f355k8 = []
gd32f355r8 = []
gd32f355rb = []
gd32f370c8 = []
gd32f370cb = []
gd32f370f8 = []
gd32f370g8 = []
gd32f370k8 = []
gd32f370r8 = []
gd32f370rb = []
gd32f403cc = []
gd32f403ce = []
gd32f403cg = []
gd32f403rc = []
gd32f403re = []
gd32f403rg = []
gd32f403ri = []
gd32f403rk = []
gd32f403vc = []
gd32f403ve = []
gd32f403vg = []
gd32f403vi = []
gd32f403vk = []
gd32f403zc = []
gd32f403ze = []
gd32f403zg = []
gd32f403zi = []
gd32f403zk = []
gd32f405re = []
gd32f405rg = []
gd32f405rk = []
gd32f405vg = []
gd32f405vk = []
gd32f405zg = []
gd32f405zk = []
gd32f407ie = []
gd32f407ig = []
gd32f407ik = []
gd32f407re = []
gd32f407rg = []
gd32f407rk = []
gd32f407ve = []
gd32f407vg = []
gd32f407vk = []
gd32f407ze = []
gd32f407zg = []
gd32f407zk = []
gd32f425re = []
gd32f425rg = []
gd32f425rk = []
gd32f425vg = []
gd32f425vk = []
gd32f425zg = []
gd32f425zk = []
gd32f427ie = []
gd32f427ig = []
gd32f427ik = []
gd32f427re = []
gd32f427rg = []
gd32f427rk = []
gd32f427ve = []
gd32f427vg = []
gd32f427vk = []
gd32f427ze = []
gd32f427zg = []
gd32f427zk = []
gd32f450ig = []
gd32f450ii = []
gd32f450ik = []
gd32f450ve = []
gd32f450vg = []
gd32f450vi = []
gd32f450vk = []
gd32f450ze = []
gd32f450zg = []
gd32f450zi = []
gd32f450zk = []
gd32f470ig = []
gd32f470ii = []
gd32f470ik = []
gd32f470ve = []
gd32f470vg = []
gd32f470vi = []
gd32f470vk = []
gd32f470ze = []
gd32f470zg = []
gd32f470zi = []
gd32f470zk = []
gd32f502cb = []
gd32f502cc = []
gd32f502ce = []
gd32f502cg = []
gd32f502kb = []
gd32f502kc = []
gd32f502ke = []
gd32f502rb = []
gd32f502rc = []
gd32f502re = []
gd32f502rg = []
gd32f502vc = []
gd32f502ve = []
gd32f502vg = []
gd32f503cc = []
gd32f503ce = []
gd32f503cg = []
gd32f503kc = []
gd32f503ke = []
gd32f503rc = []
gd32f503re = []
gd32f503rg = []
gd32f503vc = []
gd32f503ve = []
gd32f503vg = []
gd32f505ce = []
gd32f505cg = []
gd32f505re = []
gd32f505rg = []
gd32f505ve = []
gd32f505vg = []
gd32f527im = []
gd32f527is = []
gd32f527rm = []
gd32f527rs = []
gd32f527vm = []
gd32f527vs = []
gd32f527zm = []
gd32f527zs = []
gd32f5hcpi = []
gd32f5hcri = []
gd32g533cc = []
gd32g533mc = []
gd32g533rc = []
gd32g553cc = []
gd32g553ce = []
gd32g553mc = []
gd32g553me = []
gd32g553qc = []
gd32g553qe = []
gd32g553rc = []
gd32g553re = []
gd32g553vc = []
gd32g553ve = []
gd32h737ig = []
gd32h737ii = []
gd32h737im = []
gd32h737vg = []
gd32h737vi = []
gd32h737vm = []
gd32h737zg = []
gd32h737zi = []
gd32h737zm = []
gd32h757vg = []
gd32h757vi = []
gd32h757vm = []
gd32h757zg = []
gd32h757zi = []
gd32h757zm = []
gd32h759ig = []
gd32h759ii = []
gd32h759im = []
gd32h75eym = []
gd32h767im = []
gd32h767vm = []
gd32h767zm = []
gd32h779ii = []
gd32h779ip = []
gd32h779iw = []
gd32h779vi = []
gd32h779vp = []
gd32h779vw = []
gd32h779zi = []
gd32h779zp = []
gd32h779zw = []
gd32h77dii = []
gd32h77dip = []
gd32h77diw = []
gd32h77eii = []
gd32h77eip = []
gd32h77eiw = []
gd32h77rap = []
gd32l233c8 = []
gd32l233cb = []
gd32l233cc = []
gd32l233k8 = []
gd32l233kb = []
gd32l233r8 = []
gd32l233rb = []
gd32l233rc = []
gd32l235c8 = []
gd32l235cb = []
gd32l235e8 = []
gd32l235eb = []
gd32l235k8 = []
gd32l235kb = []
gd32l235r8 = []
gd32l235rb = []
gd32m531cb = []
gd32m531cc = []
gd32m531cz = []
gd32m531rb = []
gd32m531rc = []
gd32m531rz = []
gd32vf103c4 = []
gd32vf103c6 = []
gd32vf103c8 = []
gd32vf103cb = []
gd32vf103r4 = []
gd32vf103r6 = []
gd32vf103r8 = []
gd32vf103rb = []
gd32vf103t4 = []
gd32vf103t6 = []
gd32vf103t8 = []
gd32vf103tb = []
gd32vf103v8 = []
gd32vf103vb = []
gd32vw553hi = []
gd32vw553hm = []
gd32vw553ki = []
gd32vw553km = []
gd32w515p0 = []
gd32w515pi = []
gd32w515tg = []
gd32w515ti = []
gd32a711ar = []
gd32a711av = []
gd32a711az = []
gd32a711br = []
gd32a711bv = []
gd32a711bz = []
gd32a711cv = []
gd32a712ai = []
gd32a712av = []
gd32a712az = []
gd32a712bi = []
gd32a712bv = []
gd32a712bz = []
gd32a714ai = []
gd32a714av = []
gd32a714ax = []
gd32a714az = []
gd32a714bi = []
gd32a714bv = []
gd32a714bz = []
gd32a722ai = []
gd32a722ax = []
gd32a722az = []
gd32a722bi = []
gd32a722bx = []
gd32a722bz = []
gd32a724ai = []
gd32a724ax = []
gd32a724az = []
gd32a724bi = []
gd32a724bx = []
gd32a724bz = []
gd32a741ai = []
gd32a741av = []
gd32a741az = []
gd32a742ai = []
gd32a742av = []
gd32a742az = []
gd32a742bi = []
gd32a742bv = []
gd32a742bz = []
gd32a744ai = []
gd32a744av = []
gd32a744ax = []
gd32a744az = []
gd32a744bi = []
gd32a744bv = []
gd32a744bz = []
