#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Ethernet: media access control"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct EnetMac { ptr : * mut u8 } unsafe impl Send for EnetMac { } unsafe impl Sync for EnetMac { } impl EnetMac { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Ethernet MAC configuration register (MAC_CFG)"]
# [inline (always)]
pub const fn mac_cfg (self) -> crate :: common :: Reg < regs :: MacCfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Ethernet MAC frame filter register (MAC_FRMF)"]
# [inline (always)]
pub const fn mac_frmf (self) -> crate :: common :: Reg < regs :: MacFrmf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Ethernet MAC hash list high register"]
# [inline (always)]
pub const fn mac_hlh (self) -> crate :: common :: Reg < regs :: MacHlh , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Ethernet MAC hash list low register"]
# [inline (always)]
pub const fn mac_hll (self) -> crate :: common :: Reg < regs :: MacHll , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Ethernet MAC PHY control register (MAC_PHY_CTL)"]
# [inline (always)]
pub const fn mac_phy_ctl (self) -> crate :: common :: Reg < regs :: MacPhyCtl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Ethernet MAC MII data register (MAC_PHY_DATA)"]
# [inline (always)]
pub const fn mac_phy_data (self) -> crate :: common :: Reg < regs :: MacPhyData , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Ethernet MAC flow control register (MAC_FCTL)"]
# [inline (always)]
pub const fn mac_fctl (self) -> crate :: common :: Reg < regs :: MacFctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Ethernet MAC VLAN tag register (MAC_VLT)"]
# [inline (always)]
pub const fn mac_vlt (self) -> crate :: common :: Reg < regs :: MacVlt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Ethernet MAC remote wakeup frame filter register (MAC_RWFF)"]
# [inline (always)]
pub const fn mac_rwff (self) -> crate :: common :: Reg < u32 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Ethernet MAC wakeup management register (MAC_WUM)"]
# [inline (always)]
pub const fn mac_wum (self) -> crate :: common :: Reg < regs :: MacWum , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Ethernet MAC interrupt flag register (MAC_INTF)"]
# [inline (always)]
pub const fn mac_intf (self) -> crate :: common :: Reg < regs :: MacIntf , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Ethernet MAC interrupt mask register (MAC_INTMSK)"]
# [inline (always)]
pub const fn mac_intmsk (self) -> crate :: common :: Reg < regs :: MacIntmsk , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Ethernet MAC address 0 high register (MAC_ADDR0H)"]
# [inline (always)]
pub const fn mac_addr0h (self) -> crate :: common :: Reg < regs :: MacAddr0h , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "Ethernet MAC address 0 low register"]
# [inline (always)]
pub const fn mac_addr0l (self) -> crate :: common :: Reg < regs :: MacAddr0l , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "Ethernet MAC address 1 high register (MAC_ADDR1H)"]
# [inline (always)]
pub const fn mac_addr1h (self) -> crate :: common :: Reg < regs :: MacAddr1h , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "Ethernet MAC address1 low register"]
# [inline (always)]
pub const fn mac_addr1l (self) -> crate :: common :: Reg < regs :: MacAddr1l , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "Ethernet MAC address 2 high register (MAC_ADDR2H)"]
# [inline (always)]
pub const fn mac_addr2h (self) -> crate :: common :: Reg < regs :: MacAddr2h , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x50usize) as _) } } # [doc = "Ethernet MAC address 2 low register"]
# [inline (always)]
pub const fn mac_addr2l (self) -> crate :: common :: Reg < regs :: MacAddr2l , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize) as _) } } # [doc = "Ethernet MAC address 3 high register (MAC_ADDR3H)"]
# [inline (always)]
pub const fn mac_addr3h (self) -> crate :: common :: Reg < regs :: MacAddr3h , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x58usize) as _) } } # [doc = "Ethernet MAC address 3 low register"]
# [inline (always)]
pub const fn mac_addr3l (self) -> crate :: common :: Reg < regs :: MacAddr3l , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x5cusize) as _) } } } pub mod regs { # [doc = "Ethernet MAC address 0 high register (MAC_ADDR0H)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr0h (pub u32) ; impl MacAddr0h { # [doc = "MAC address0 high"]
# [inline (always)]
pub const fn addr0h (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "MAC address0 high"]
# [inline (always)]
pub fn set_addr0h (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Always 1"]
# [inline (always)]
pub const fn mo (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Always 1"]
# [inline (always)]
pub fn set_mo (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for MacAddr0h { # [inline (always)]
fn default () -> MacAddr0h { MacAddr0h (0) } } impl core :: fmt :: Debug for MacAddr0h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr0h") . field ("addr0h" , & self . addr0h ()) . field ("mo" , & self . mo ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr0h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr0h {{ addr0h: {=u16:?}, mo: {=bool:?} }}" , self . addr0h () , self . mo ()) } } # [doc = "Ethernet MAC address 0 low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr0l (pub u32) ; impl MacAddr0l { # [doc = "MAC address0 low"]
# [inline (always)]
pub const fn addr0l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "MAC address0 low"]
# [inline (always)]
pub fn set_addr0l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for MacAddr0l { # [inline (always)]
fn default () -> MacAddr0l { MacAddr0l (0) } } impl core :: fmt :: Debug for MacAddr0l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr0l") . field ("addr0l" , & self . addr0l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr0l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr0l {{ addr0l: {=u32:?} }}" , self . addr0l ()) } } # [doc = "Ethernet MAC address 1 high register (MAC_ADDR1H)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr1h (pub u32) ; impl MacAddr1h { # [doc = "MAC address1 high"]
# [inline (always)]
pub const fn addr1h (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "MAC address1 high"]
# [inline (always)]
pub fn set_addr1h (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Mask byte"]
# [inline (always)]
pub const fn mb (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x3f ; val as u8 } # [doc = "Mask byte"]
# [inline (always)]
pub fn set_mb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 24usize)) | (((val as u32) & 0x3f) << 24usize) ; } # [doc = "Source address filter"]
# [inline (always)]
pub const fn saf (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Source address filter"]
# [inline (always)]
pub fn set_saf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Address filter enable"]
# [inline (always)]
pub const fn afe (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Address filter enable"]
# [inline (always)]
pub fn set_afe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for MacAddr1h { # [inline (always)]
fn default () -> MacAddr1h { MacAddr1h (0) } } impl core :: fmt :: Debug for MacAddr1h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr1h") . field ("addr1h" , & self . addr1h ()) . field ("mb" , & self . mb ()) . field ("saf" , & self . saf ()) . field ("afe" , & self . afe ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr1h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr1h {{ addr1h: {=u16:?}, mb: {=u8:?}, saf: {=bool:?}, afe: {=bool:?} }}" , self . addr1h () , self . mb () , self . saf () , self . afe ()) } } # [doc = "Ethernet MAC address1 low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr1l (pub u32) ; impl MacAddr1l { # [doc = "MAC address1 low"]
# [inline (always)]
pub const fn addr1l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "MAC address1 low"]
# [inline (always)]
pub fn set_addr1l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for MacAddr1l { # [inline (always)]
fn default () -> MacAddr1l { MacAddr1l (0) } } impl core :: fmt :: Debug for MacAddr1l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr1l") . field ("addr1l" , & self . addr1l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr1l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr1l {{ addr1l: {=u32:?} }}" , self . addr1l ()) } } # [doc = "Ethernet MAC address 2 high register (MAC_ADDR2H)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr2h (pub u32) ; impl MacAddr2h { # [doc = "Ethernet MAC address 2 high register"]
# [inline (always)]
pub const fn addr2h (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Ethernet MAC address 2 high register"]
# [inline (always)]
pub fn set_addr2h (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Mask byte"]
# [inline (always)]
pub const fn mb (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x3f ; val as u8 } # [doc = "Mask byte"]
# [inline (always)]
pub fn set_mb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 24usize)) | (((val as u32) & 0x3f) << 24usize) ; } # [doc = "Source address filter"]
# [inline (always)]
pub const fn saf (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Source address filter"]
# [inline (always)]
pub fn set_saf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Address filter enable"]
# [inline (always)]
pub const fn afe (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Address filter enable"]
# [inline (always)]
pub fn set_afe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for MacAddr2h { # [inline (always)]
fn default () -> MacAddr2h { MacAddr2h (0) } } impl core :: fmt :: Debug for MacAddr2h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr2h") . field ("addr2h" , & self . addr2h ()) . field ("mb" , & self . mb ()) . field ("saf" , & self . saf ()) . field ("afe" , & self . afe ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr2h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr2h {{ addr2h: {=u16:?}, mb: {=u8:?}, saf: {=bool:?}, afe: {=bool:?} }}" , self . addr2h () , self . mb () , self . saf () , self . afe ()) } } # [doc = "Ethernet MAC address 2 low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr2l (pub u32) ; impl MacAddr2l { # [doc = "MAC address2 low"]
# [inline (always)]
pub const fn addr2l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "MAC address2 low"]
# [inline (always)]
pub fn set_addr2l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for MacAddr2l { # [inline (always)]
fn default () -> MacAddr2l { MacAddr2l (0) } } impl core :: fmt :: Debug for MacAddr2l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr2l") . field ("addr2l" , & self . addr2l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr2l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr2l {{ addr2l: {=u32:?} }}" , self . addr2l ()) } } # [doc = "Ethernet MAC address 3 high register (MAC_ADDR3H)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr3h (pub u32) ; impl MacAddr3h { # [doc = "MAC address3 high"]
# [inline (always)]
pub const fn addr3h (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "MAC address3 high"]
# [inline (always)]
pub fn set_addr3h (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Mask byte"]
# [inline (always)]
pub const fn mb (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x3f ; val as u8 } # [doc = "Mask byte"]
# [inline (always)]
pub fn set_mb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 24usize)) | (((val as u32) & 0x3f) << 24usize) ; } # [doc = "Source address filter"]
# [inline (always)]
pub const fn saf (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Source address filter"]
# [inline (always)]
pub fn set_saf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Address filter enable"]
# [inline (always)]
pub const fn afe (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Address filter enable"]
# [inline (always)]
pub fn set_afe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for MacAddr3h { # [inline (always)]
fn default () -> MacAddr3h { MacAddr3h (0) } } impl core :: fmt :: Debug for MacAddr3h { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr3h") . field ("addr3h" , & self . addr3h ()) . field ("mb" , & self . mb ()) . field ("saf" , & self . saf ()) . field ("afe" , & self . afe ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr3h { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr3h {{ addr3h: {=u16:?}, mb: {=u8:?}, saf: {=bool:?}, afe: {=bool:?} }}" , self . addr3h () , self . mb () , self . saf () , self . afe ()) } } # [doc = "Ethernet MAC address 3 low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacAddr3l (pub u32) ; impl MacAddr3l { # [doc = "MAC address3 low"]
# [inline (always)]
pub const fn addr3l (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "MAC address3 low"]
# [inline (always)]
pub fn set_addr3l (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for MacAddr3l { # [inline (always)]
fn default () -> MacAddr3l { MacAddr3l (0) } } impl core :: fmt :: Debug for MacAddr3l { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacAddr3l") . field ("addr3l" , & self . addr3l ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacAddr3l { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacAddr3l {{ addr3l: {=u32:?} }}" , self . addr3l ()) } } # [doc = "Ethernet MAC configuration register (MAC_CFG)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacCfg (pub u32) ; impl MacCfg { # [doc = "Receiver enable"]
# [inline (always)]
pub const fn ren (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Receiver enable"]
# [inline (always)]
pub fn set_ren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Transmitter enable"]
# [inline (always)]
pub const fn ten (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Transmitter enable"]
# [inline (always)]
pub fn set_ten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Deferral check"]
# [inline (always)]
pub const fn dfc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Deferral check"]
# [inline (always)]
pub fn set_dfc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Back-off limit"]
# [inline (always)]
pub const fn bol (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x03 ; val as u8 } # [doc = "Back-off limit"]
# [inline (always)]
pub fn set_bol (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 5usize)) | (((val as u32) & 0x03) << 5usize) ; } # [doc = "Automatic pad/CRC drop"]
# [inline (always)]
pub const fn apcd (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Automatic pad/CRC drop"]
# [inline (always)]
pub fn set_apcd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Retry disable"]
# [inline (always)]
pub const fn rtd (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Retry disable"]
# [inline (always)]
pub fn set_rtd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "IP frame checksum offload"]
# [inline (always)]
pub const fn ipfco (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "IP frame checksum offload"]
# [inline (always)]
pub fn set_ipfco (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Duplex mode"]
# [inline (always)]
pub const fn dpm (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Duplex mode"]
# [inline (always)]
pub fn set_dpm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Loopback mode"]
# [inline (always)]
pub const fn lbm (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Loopback mode"]
# [inline (always)]
pub fn set_lbm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Receive own disable"]
# [inline (always)]
pub const fn rod (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Receive own disable"]
# [inline (always)]
pub fn set_rod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Fast Ethernet speed"]
# [inline (always)]
pub const fn spd (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Fast Ethernet speed"]
# [inline (always)]
pub fn set_spd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Carrier sense disable"]
# [inline (always)]
pub const fn csd (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Carrier sense disable"]
# [inline (always)]
pub fn set_csd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Inter frame gap bit selection"]
# [inline (always)]
pub const fn igbs (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x07 ; val as u8 } # [doc = "Inter frame gap bit selection"]
# [inline (always)]
pub fn set_igbs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 17usize)) | (((val as u32) & 0x07) << 17usize) ; } # [doc = "Jabber disable"]
# [inline (always)]
pub const fn jbd (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Jabber disable"]
# [inline (always)]
pub fn set_jbd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "Watchdog disable"]
# [inline (always)]
pub const fn wdd (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "Watchdog disable"]
# [inline (always)]
pub fn set_wdd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for MacCfg { # [inline (always)]
fn default () -> MacCfg { MacCfg (0) } } impl core :: fmt :: Debug for MacCfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacCfg") . field ("ren" , & self . ren ()) . field ("ten" , & self . ten ()) . field ("dfc" , & self . dfc ()) . field ("bol" , & self . bol ()) . field ("apcd" , & self . apcd ()) . field ("rtd" , & self . rtd ()) . field ("ipfco" , & self . ipfco ()) . field ("dpm" , & self . dpm ()) . field ("lbm" , & self . lbm ()) . field ("rod" , & self . rod ()) . field ("spd" , & self . spd ()) . field ("csd" , & self . csd ()) . field ("igbs" , & self . igbs ()) . field ("jbd" , & self . jbd ()) . field ("wdd" , & self . wdd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacCfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacCfg {{ ren: {=bool:?}, ten: {=bool:?}, dfc: {=bool:?}, bol: {=u8:?}, apcd: {=bool:?}, rtd: {=bool:?}, ipfco: {=bool:?}, dpm: {=bool:?}, lbm: {=bool:?}, rod: {=bool:?}, spd: {=bool:?}, csd: {=bool:?}, igbs: {=u8:?}, jbd: {=bool:?}, wdd: {=bool:?} }}" , self . ren () , self . ten () , self . dfc () , self . bol () , self . apcd () , self . rtd () , self . ipfco () , self . dpm () , self . lbm () , self . rod () , self . spd () , self . csd () , self . igbs () , self . jbd () , self . wdd ()) } } # [doc = "Ethernet MAC flow control register (MAC_FCTL)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacFctl (pub u32) ; impl MacFctl { # [doc = "Flow control busy/back pressure activate"]
# [inline (always)]
pub const fn flcb_bkpa (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Flow control busy/back pressure activate"]
# [inline (always)]
pub fn set_flcb_bkpa (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Transmit flow control enable"]
# [inline (always)]
pub const fn tfcen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Transmit flow control enable"]
# [inline (always)]
pub fn set_tfcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Receive flow control enable"]
# [inline (always)]
pub const fn rfcen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Receive flow control enable"]
# [inline (always)]
pub fn set_rfcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Unicast pause frame detect"]
# [inline (always)]
pub const fn upfdt (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Unicast pause frame detect"]
# [inline (always)]
pub fn set_upfdt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Pause low threshold"]
# [inline (always)]
pub const fn plts (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Pause low threshold"]
# [inline (always)]
pub fn set_plts (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "Disable Zero-quanta pause"]
# [inline (always)]
pub const fn dzqp (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Disable Zero-quanta pause"]
# [inline (always)]
pub fn set_dzqp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Pause time"]
# [inline (always)]
pub const fn ptm (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Pause time"]
# [inline (always)]
pub fn set_ptm (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for MacFctl { # [inline (always)]
fn default () -> MacFctl { MacFctl (0) } } impl core :: fmt :: Debug for MacFctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacFctl") . field ("flcb_bkpa" , & self . flcb_bkpa ()) . field ("tfcen" , & self . tfcen ()) . field ("rfcen" , & self . rfcen ()) . field ("upfdt" , & self . upfdt ()) . field ("plts" , & self . plts ()) . field ("dzqp" , & self . dzqp ()) . field ("ptm" , & self . ptm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacFctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacFctl {{ flcb_bkpa: {=bool:?}, tfcen: {=bool:?}, rfcen: {=bool:?}, upfdt: {=bool:?}, plts: {=u8:?}, dzqp: {=bool:?}, ptm: {=u16:?} }}" , self . flcb_bkpa () , self . tfcen () , self . rfcen () , self . upfdt () , self . plts () , self . dzqp () , self . ptm ()) } } # [doc = "Ethernet MAC frame filter register (MAC_FRMF)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacFrmf (pub u32) ; impl MacFrmf { # [doc = "Promiscuous mode"]
# [inline (always)]
pub const fn pm (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Promiscuous mode"]
# [inline (always)]
pub fn set_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Hash unicast filter"]
# [inline (always)]
pub const fn huf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Hash unicast filter"]
# [inline (always)]
pub fn set_huf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Hash multicast filter"]
# [inline (always)]
pub const fn hmf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Hash multicast filter"]
# [inline (always)]
pub fn set_hmf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Destination address inverse filtering"]
# [inline (always)]
pub const fn daiflt (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Destination address inverse filtering"]
# [inline (always)]
pub fn set_daiflt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "multicast filter disable"]
# [inline (always)]
pub const fn mfd (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "multicast filter disable"]
# [inline (always)]
pub fn set_mfd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Broadcast frames disable"]
# [inline (always)]
pub const fn bfrmd (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Broadcast frames disable"]
# [inline (always)]
pub fn set_bfrmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Pass control frames"]
# [inline (always)]
pub const fn pcfrm (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x03 ; val as u8 } # [doc = "Pass control frames"]
# [inline (always)]
pub fn set_pcfrm (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 6usize)) | (((val as u32) & 0x03) << 6usize) ; } # [doc = "Source address inverse filtering"]
# [inline (always)]
pub const fn saiflt (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Source address inverse filtering"]
# [inline (always)]
pub fn set_saiflt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Source address filter"]
# [inline (always)]
pub const fn saflt (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Source address filter"]
# [inline (always)]
pub fn set_saflt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Hash or perfect filter"]
# [inline (always)]
pub const fn hpflt (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Hash or perfect filter"]
# [inline (always)]
pub fn set_hpflt (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Frames all receive"]
# [inline (always)]
pub const fn far (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Frames all receive"]
# [inline (always)]
pub fn set_far (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for MacFrmf { # [inline (always)]
fn default () -> MacFrmf { MacFrmf (0) } } impl core :: fmt :: Debug for MacFrmf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacFrmf") . field ("pm" , & self . pm ()) . field ("huf" , & self . huf ()) . field ("hmf" , & self . hmf ()) . field ("daiflt" , & self . daiflt ()) . field ("mfd" , & self . mfd ()) . field ("bfrmd" , & self . bfrmd ()) . field ("pcfrm" , & self . pcfrm ()) . field ("saiflt" , & self . saiflt ()) . field ("saflt" , & self . saflt ()) . field ("hpflt" , & self . hpflt ()) . field ("far" , & self . far ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacFrmf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacFrmf {{ pm: {=bool:?}, huf: {=bool:?}, hmf: {=bool:?}, daiflt: {=bool:?}, mfd: {=bool:?}, bfrmd: {=bool:?}, pcfrm: {=u8:?}, saiflt: {=bool:?}, saflt: {=bool:?}, hpflt: {=bool:?}, far: {=bool:?} }}" , self . pm () , self . huf () , self . hmf () , self . daiflt () , self . mfd () , self . bfrmd () , self . pcfrm () , self . saiflt () , self . saflt () , self . hpflt () , self . far ()) } } # [doc = "Ethernet MAC hash list high register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacHlh (pub u32) ; impl MacHlh { # [doc = "Hash list high"]
# [inline (always)]
pub const fn hlh (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Hash list high"]
# [inline (always)]
pub fn set_hlh (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for MacHlh { # [inline (always)]
fn default () -> MacHlh { MacHlh (0) } } impl core :: fmt :: Debug for MacHlh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacHlh") . field ("hlh" , & self . hlh ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacHlh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacHlh {{ hlh: {=u32:?} }}" , self . hlh ()) } } # [doc = "Ethernet MAC hash list low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacHll (pub u32) ; impl MacHll { # [doc = "Hash list low"]
# [inline (always)]
pub const fn hll (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Hash list low"]
# [inline (always)]
pub fn set_hll (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for MacHll { # [inline (always)]
fn default () -> MacHll { MacHll (0) } } impl core :: fmt :: Debug for MacHll { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacHll") . field ("hll" , & self . hll ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacHll { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacHll {{ hll: {=u32:?} }}" , self . hll ()) } } # [doc = "Ethernet MAC interrupt flag register (MAC_INTF)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacIntf (pub u32) ; impl MacIntf { # [doc = "WUM status"]
# [inline (always)]
pub const fn wum (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "WUM status"]
# [inline (always)]
pub fn set_wum (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "MSC status"]
# [inline (always)]
pub const fn msc (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "MSC status"]
# [inline (always)]
pub fn set_msc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "MSC receive status"]
# [inline (always)]
pub const fn mscr (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "MSC receive status"]
# [inline (always)]
pub fn set_mscr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "MSC transmit status"]
# [inline (always)]
pub const fn msct (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "MSC transmit status"]
# [inline (always)]
pub fn set_msct (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Time stamp trigger status"]
# [inline (always)]
pub const fn tmst (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Time stamp trigger status"]
# [inline (always)]
pub fn set_tmst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } } impl Default for MacIntf { # [inline (always)]
fn default () -> MacIntf { MacIntf (0) } } impl core :: fmt :: Debug for MacIntf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacIntf") . field ("wum" , & self . wum ()) . field ("msc" , & self . msc ()) . field ("mscr" , & self . mscr ()) . field ("msct" , & self . msct ()) . field ("tmst" , & self . tmst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacIntf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacIntf {{ wum: {=bool:?}, msc: {=bool:?}, mscr: {=bool:?}, msct: {=bool:?}, tmst: {=bool:?} }}" , self . wum () , self . msc () , self . mscr () , self . msct () , self . tmst ()) } } # [doc = "Ethernet MAC interrupt mask register (MAC_INTMSK)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacIntmsk (pub u32) ; impl MacIntmsk { # [doc = "WUM interrupt mask"]
# [inline (always)]
pub const fn wumim (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "WUM interrupt mask"]
# [inline (always)]
pub fn set_wumim (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Time stamp trigger interrupt mask"]
# [inline (always)]
pub const fn tmstim (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Time stamp trigger interrupt mask"]
# [inline (always)]
pub fn set_tmstim (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } } impl Default for MacIntmsk { # [inline (always)]
fn default () -> MacIntmsk { MacIntmsk (0) } } impl core :: fmt :: Debug for MacIntmsk { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacIntmsk") . field ("wumim" , & self . wumim ()) . field ("tmstim" , & self . tmstim ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacIntmsk { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacIntmsk {{ wumim: {=bool:?}, tmstim: {=bool:?} }}" , self . wumim () , self . tmstim ()) } } # [doc = "Ethernet MAC PHY control register (MAC_PHY_CTL)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacPhyCtl (pub u32) ; impl MacPhyCtl { # [doc = "PHY busy"]
# [inline (always)]
pub const fn pb (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "PHY busy"]
# [inline (always)]
pub fn set_pb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "PHY write"]
# [inline (always)]
pub const fn pw (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "PHY write"]
# [inline (always)]
pub fn set_pw (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Clock range"]
# [inline (always)]
pub const fn clr (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x07 ; val as u8 } # [doc = "Clock range"]
# [inline (always)]
pub fn set_clr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 2usize)) | (((val as u32) & 0x07) << 2usize) ; } # [doc = "PHY register"]
# [inline (always)]
pub const fn pr (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x1f ; val as u8 } # [doc = "PHY register"]
# [inline (always)]
pub fn set_pr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 6usize)) | (((val as u32) & 0x1f) << 6usize) ; } # [doc = "PHY address"]
# [inline (always)]
pub const fn pa (& self) -> u8 { let val = (self . 0 >> 11usize) & 0x1f ; val as u8 } # [doc = "PHY address"]
# [inline (always)]
pub fn set_pa (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 11usize)) | (((val as u32) & 0x1f) << 11usize) ; } } impl Default for MacPhyCtl { # [inline (always)]
fn default () -> MacPhyCtl { MacPhyCtl (0) } } impl core :: fmt :: Debug for MacPhyCtl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacPhyCtl") . field ("pb" , & self . pb ()) . field ("pw" , & self . pw ()) . field ("clr" , & self . clr ()) . field ("pr" , & self . pr ()) . field ("pa" , & self . pa ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacPhyCtl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacPhyCtl {{ pb: {=bool:?}, pw: {=bool:?}, clr: {=u8:?}, pr: {=u8:?}, pa: {=u8:?} }}" , self . pb () , self . pw () , self . clr () , self . pr () , self . pa ()) } } # [doc = "Ethernet MAC MII data register (MAC_PHY_DATA)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacPhyData (pub u32) ; impl MacPhyData { # [doc = "PHY data"]
# [inline (always)]
pub const fn pd (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "PHY data"]
# [inline (always)]
pub fn set_pd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for MacPhyData { # [inline (always)]
fn default () -> MacPhyData { MacPhyData (0) } } impl core :: fmt :: Debug for MacPhyData { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacPhyData") . field ("pd" , & self . pd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacPhyData { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacPhyData {{ pd: {=u16:?} }}" , self . pd ()) } } # [doc = "Ethernet MAC VLAN tag register (MAC_VLT)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacVlt (pub u32) ; impl MacVlt { # [doc = "VLAN tag identifier (for receive frames)"]
# [inline (always)]
pub const fn vlti (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "VLAN tag identifier (for receive frames)"]
# [inline (always)]
pub fn set_vlti (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "12-bit VLAN tag comparison"]
# [inline (always)]
pub const fn vltc (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "12-bit VLAN tag comparison"]
# [inline (always)]
pub fn set_vltc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } } impl Default for MacVlt { # [inline (always)]
fn default () -> MacVlt { MacVlt (0) } } impl core :: fmt :: Debug for MacVlt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacVlt") . field ("vlti" , & self . vlti ()) . field ("vltc" , & self . vltc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacVlt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacVlt {{ vlti: {=u16:?}, vltc: {=bool:?} }}" , self . vlti () , self . vltc ()) } } # [doc = "Ethernet MAC wakeup management register (MAC_WUM)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct MacWum (pub u32) ; impl MacWum { # [doc = "Power down"]
# [inline (always)]
pub const fn pwd (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Power down"]
# [inline (always)]
pub fn set_pwd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Magic Packet enable"]
# [inline (always)]
pub const fn mpen (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Magic Packet enable"]
# [inline (always)]
pub fn set_mpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Wakeup frame enable"]
# [inline (always)]
pub const fn wfen (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Wakeup frame enable"]
# [inline (always)]
pub fn set_wfen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Magic packet received"]
# [inline (always)]
pub const fn mpkr (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Magic packet received"]
# [inline (always)]
pub fn set_mpkr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Wakeup frame received"]
# [inline (always)]
pub const fn wufr (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Wakeup frame received"]
# [inline (always)]
pub fn set_wufr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Global unicast"]
# [inline (always)]
pub const fn gu (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Global unicast"]
# [inline (always)]
pub fn set_gu (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Wakeup frame filter register pointer reset"]
# [inline (always)]
pub const fn wuffrpr (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Wakeup frame filter register pointer reset"]
# [inline (always)]
pub fn set_wuffrpr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for MacWum { # [inline (always)]
fn default () -> MacWum { MacWum (0) } } impl core :: fmt :: Debug for MacWum { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("MacWum") . field ("pwd" , & self . pwd ()) . field ("mpen" , & self . mpen ()) . field ("wfen" , & self . wfen ()) . field ("mpkr" , & self . mpkr ()) . field ("wufr" , & self . wufr ()) . field ("gu" , & self . gu ()) . field ("wuffrpr" , & self . wuffrpr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for MacWum { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "MacWum {{ pwd: {=bool:?}, mpen: {=bool:?}, wfen: {=bool:?}, mpkr: {=bool:?}, wufr: {=bool:?}, gu: {=bool:?}, wuffrpr: {=bool:?} }}" , self . pwd () , self . mpen () , self . wfen () , self . mpkr () , self . wufr () , self . gu () , self . wuffrpr ()) } } }