#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Programmable current reference"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Iref { ptr : * mut u8 } unsafe impl Send for Iref { } unsafe impl Sync for Iref { } impl Iref { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "control register"]
# [inline (always)]
pub const fn ctl (self) -> crate :: common :: Reg < regs :: Ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0300usize) as _) } } } pub mod regs { # [doc = "control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl (pub u32) ; impl Ctl { # [doc = "Current step data"]
# [inline (always)]
pub const fn csdt (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [doc = "Current step data"]
# [inline (always)]
pub fn set_csdt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [doc = "Sink current mode"]
# [inline (always)]
pub const fn scmod (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Sink current mode"]
# [inline (always)]
pub fn set_scmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Current precision trim"]
# [inline (always)]
pub const fn cpt (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x1f ; val as u8 } # [doc = "Current precision trim"]
# [inline (always)]
pub fn set_cpt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 8usize)) | (((val as u32) & 0x1f) << 8usize) ; } # [doc = "Step selection"]
# [inline (always)]
pub const fn ssel (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Step selection"]
# [inline (always)]
pub fn set_ssel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Current reference enable"]
# [inline (always)]
pub const fn cren (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Current reference enable"]
# [inline (always)]
pub fn set_cren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Ctl { # [inline (always)]
fn default () -> Ctl { Ctl (0) } } impl core :: fmt :: Debug for Ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl") . field ("csdt" , & self . csdt ()) . field ("scmod" , & self . scmod ()) . field ("cpt" , & self . cpt ()) . field ("ssel" , & self . ssel ()) . field ("cren" , & self . cren ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl {{ csdt: {=u8:?}, scmod: {=bool:?}, cpt: {=u8:?}, ssel: {=bool:?}, cren: {=bool:?} }}" , self . csdt () , self . scmod () , self . cpt () , self . ssel () , self . cren ()) } } }
