#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "RAM ECC monitor unit 1"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rameccmu1 { ptr : * mut u8 } unsafe impl Send for Rameccmu1 { } unsafe impl Sync for Rameccmu1 { } impl Rameccmu1 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "RAMECCMU global interruput register"]
# [inline (always)]
pub const fn int (self) -> crate :: common :: Reg < regs :: Int , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "monitor 0 control register"]
# [inline (always)]
pub const fn m0ctl (self) -> crate :: common :: Reg < regs :: M0ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "monitor 0 status register"]
# [inline (always)]
pub const fn m0stat (self) -> crate :: common :: Reg < regs :: M0stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "monitor 0 failing address register"]
# [inline (always)]
pub const fn m0faddr (self) -> crate :: common :: Reg < regs :: M0faddr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "monitor 0 failing data low register"]
# [inline (always)]
pub const fn m0fdl (self) -> crate :: common :: Reg < regs :: M0fdl , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "monitor 0 failing data high register"]
# [inline (always)]
pub const fn m0fdh (self) -> crate :: common :: Reg < regs :: M0fdh , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x30usize) as _) } } # [doc = "monitor 0 failing ECC error code register"]
# [inline (always)]
pub const fn m0fecode (self) -> crate :: common :: Reg < regs :: M0fecode , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "monitor 1 control register"]
# [inline (always)]
pub const fn m1ctl (self) -> crate :: common :: Reg < regs :: M1ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "monitor 1 status register"]
# [inline (always)]
pub const fn m1stat (self) -> crate :: common :: Reg < regs :: M1stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x44usize) as _) } } # [doc = "monitor 1 failing address register"]
# [inline (always)]
pub const fn m1faddr (self) -> crate :: common :: Reg < regs :: M1faddr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x48usize) as _) } } # [doc = "monitor 1 failing data low register"]
# [inline (always)]
pub const fn m1fdl (self) -> crate :: common :: Reg < regs :: M1fdl , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x4cusize) as _) } } # [doc = "monitor 0 failing data high register"]
# [inline (always)]
pub const fn m1fdh (self) -> crate :: common :: Reg < regs :: M1fdh , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x50usize) as _) } } # [doc = "monitor 1 failing ECC error code register"]
# [inline (always)]
pub const fn m1fecode (self) -> crate :: common :: Reg < regs :: M1fecode , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize) as _) } } # [doc = "monitor 0 control register"]
# [inline (always)]
pub const fn m2ctl (self) -> crate :: common :: Reg < regs :: M2ctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x60usize) as _) } } # [doc = "monitor 0 status register"]
# [inline (always)]
pub const fn m2stat (self) -> crate :: common :: Reg < regs :: M2stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x64usize) as _) } } # [doc = "monitor 0 failing address register"]
# [inline (always)]
pub const fn m2faddr (self) -> crate :: common :: Reg < regs :: M2faddr , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x68usize) as _) } } # [doc = "monitor 0 failing data low register"]
# [inline (always)]
pub const fn m2fdl (self) -> crate :: common :: Reg < regs :: M2fdl , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x6cusize) as _) } } # [doc = "monitor 0 failing data high register"]
# [inline (always)]
pub const fn m2fdh (self) -> crate :: common :: Reg < regs :: M2fdh , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x70usize) as _) } } # [doc = "monitor 0 failing ECC error code register"]
# [inline (always)]
pub const fn m2fecode (self) -> crate :: common :: Reg < regs :: M2fecode , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x74usize) as _) } } } pub mod regs { # [doc = "RAMECCMU global interruput register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Int (pub u32) ; impl Int { # [doc = "Global ECC interrupt enable"]
# [inline (always)]
pub const fn geie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Global ECC interrupt enable"]
# [inline (always)]
pub fn set_geie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Global ECC single error interrupt enable"]
# [inline (always)]
pub const fn geserrie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Global ECC single error interrupt enable"]
# [inline (always)]
pub fn set_geserrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Global ECC double error interrupt enable"]
# [inline (always)]
pub const fn gederrie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Global ECC double error interrupt enable"]
# [inline (always)]
pub fn set_gederrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Global ECC double error on byte write interrupt enable"]
# [inline (always)]
pub const fn gederrbwie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Global ECC double error on byte write interrupt enable"]
# [inline (always)]
pub fn set_gederrbwie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } } impl Default for Int { # [inline (always)]
fn default () -> Int { Int (0) } } impl core :: fmt :: Debug for Int { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Int") . field ("geie" , & self . geie ()) . field ("geserrie" , & self . geserrie ()) . field ("gederrie" , & self . gederrie ()) . field ("gederrbwie" , & self . gederrbwie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Int { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Int {{ geie: {=bool:?}, geserrie: {=bool:?}, gederrie: {=bool:?}, gederrbwie: {=bool:?} }}" , self . geie () , self . geserrie () , self . gederrie () , self . gederrbwie ()) } } # [doc = "monitor 0 control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M0ctl (pub u32) ; impl M0ctl { # [doc = "ECC single error interrupt enable"]
# [inline (always)]
pub const fn eccserrie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "ECC single error interrupt enable"]
# [inline (always)]
pub fn set_eccserrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "ECC double error interrupt enable"]
# [inline (always)]
pub const fn eccderrie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "ECC double error interrupt enable"]
# [inline (always)]
pub fn set_eccderrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "ECC double error on byte write interrupt enable"]
# [inline (always)]
pub const fn eccderrbwie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "ECC double error on byte write interrupt enable"]
# [inline (always)]
pub fn set_eccderrbwie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "ECC error latching enable"]
# [inline (always)]
pub const fn eccerrlaten (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "ECC error latching enable"]
# [inline (always)]
pub fn set_eccerrlaten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for M0ctl { # [inline (always)]
fn default () -> M0ctl { M0ctl (0) } } impl core :: fmt :: Debug for M0ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M0ctl") . field ("eccserrie" , & self . eccserrie ()) . field ("eccderrie" , & self . eccderrie ()) . field ("eccderrbwie" , & self . eccderrbwie ()) . field ("eccerrlaten" , & self . eccerrlaten ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M0ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M0ctl {{ eccserrie: {=bool:?}, eccderrie: {=bool:?}, eccderrbwie: {=bool:?}, eccerrlaten: {=bool:?} }}" , self . eccserrie () , self . eccderrie () , self . eccderrbwie () , self . eccerrlaten ()) } } # [doc = "monitor 0 failing address register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M0faddr (pub u32) ; impl M0faddr { # [doc = "ECC error failing address"]
# [inline (always)]
pub const fn eccfaddr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC error failing address"]
# [inline (always)]
pub fn set_eccfaddr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M0faddr { # [inline (always)]
fn default () -> M0faddr { M0faddr (0) } } impl core :: fmt :: Debug for M0faddr { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M0faddr") . field ("eccfaddr" , & self . eccfaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M0faddr { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M0faddr {{ eccfaddr: {=u32:?} }}" , self . eccfaddr ()) } } # [doc = "monitor 0 failing data high register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M0fdh (pub u32) ; impl M0fdh { # [doc = "ECC failing data high bitss"]
# [inline (always)]
pub const fn eccfdh (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing data high bitss"]
# [inline (always)]
pub fn set_eccfdh (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M0fdh { # [inline (always)]
fn default () -> M0fdh { M0fdh (0) } } impl core :: fmt :: Debug for M0fdh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M0fdh") . field ("eccfdh" , & self . eccfdh ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M0fdh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M0fdh {{ eccfdh: {=u32:?} }}" , self . eccfdh ()) } } # [doc = "monitor 0 failing data low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M0fdl (pub u32) ; impl M0fdl { # [doc = "ECC failing data low bits"]
# [inline (always)]
pub const fn eccfdl (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing data low bits"]
# [inline (always)]
pub fn set_eccfdl (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M0fdl { # [inline (always)]
fn default () -> M0fdl { M0fdl (0) } } impl core :: fmt :: Debug for M0fdl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M0fdl") . field ("eccfdl" , & self . eccfdl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M0fdl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M0fdl {{ eccfdl: {=u32:?} }}" , self . eccfdl ()) } } # [doc = "monitor 0 failing ECC error code register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M0fecode (pub u32) ; impl M0fecode { # [doc = "ECC failing error code"]
# [inline (always)]
pub const fn eccfecode (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing error code"]
# [inline (always)]
pub fn set_eccfecode (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M0fecode { # [inline (always)]
fn default () -> M0fecode { M0fecode (0) } } impl core :: fmt :: Debug for M0fecode { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M0fecode") . field ("eccfecode" , & self . eccfecode ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M0fecode { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M0fecode {{ eccfecode: {=u32:?} }}" , self . eccfecode ()) } } # [doc = "monitor 0 status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M0stat (pub u32) ; impl M0stat { # [doc = "ECC single error detected and corrected flag"]
# [inline (always)]
pub const fn eccserrdcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "ECC single error detected and corrected flag"]
# [inline (always)]
pub fn set_eccserrdcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "ECC double error detected flag"]
# [inline (always)]
pub const fn eccderrdf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "ECC double error detected flag"]
# [inline (always)]
pub fn set_eccderrdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "ECC double error on byte write detected flag"]
# [inline (always)]
pub const fn eccderrbwdf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "ECC double error on byte write detected flag"]
# [inline (always)]
pub fn set_eccderrbwdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for M0stat { # [inline (always)]
fn default () -> M0stat { M0stat (0) } } impl core :: fmt :: Debug for M0stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M0stat") . field ("eccserrdcf" , & self . eccserrdcf ()) . field ("eccderrdf" , & self . eccderrdf ()) . field ("eccderrbwdf" , & self . eccderrbwdf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M0stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M0stat {{ eccserrdcf: {=bool:?}, eccderrdf: {=bool:?}, eccderrbwdf: {=bool:?} }}" , self . eccserrdcf () , self . eccderrdf () , self . eccderrbwdf ()) } } # [doc = "monitor 1 control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M1ctl (pub u32) ; impl M1ctl { # [doc = "ECC single error interrupt enable"]
# [inline (always)]
pub const fn eccserrie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "ECC single error interrupt enable"]
# [inline (always)]
pub fn set_eccserrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "ECC double error interrupt enable"]
# [inline (always)]
pub const fn eccderrie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "ECC double error interrupt enable"]
# [inline (always)]
pub fn set_eccderrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "ECC double error on byte write interrupt enable"]
# [inline (always)]
pub const fn eccderrbwie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "ECC double error on byte write interrupt enable"]
# [inline (always)]
pub fn set_eccderrbwie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "ECC error latching enable"]
# [inline (always)]
pub const fn eccerrlaten (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "ECC error latching enable"]
# [inline (always)]
pub fn set_eccerrlaten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for M1ctl { # [inline (always)]
fn default () -> M1ctl { M1ctl (0) } } impl core :: fmt :: Debug for M1ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M1ctl") . field ("eccserrie" , & self . eccserrie ()) . field ("eccderrie" , & self . eccderrie ()) . field ("eccderrbwie" , & self . eccderrbwie ()) . field ("eccerrlaten" , & self . eccerrlaten ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M1ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M1ctl {{ eccserrie: {=bool:?}, eccderrie: {=bool:?}, eccderrbwie: {=bool:?}, eccerrlaten: {=bool:?} }}" , self . eccserrie () , self . eccderrie () , self . eccderrbwie () , self . eccerrlaten ()) } } # [doc = "monitor 1 failing address register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M1faddr (pub u32) ; impl M1faddr { # [doc = "ECC error failing address"]
# [inline (always)]
pub const fn eccfaddr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC error failing address"]
# [inline (always)]
pub fn set_eccfaddr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M1faddr { # [inline (always)]
fn default () -> M1faddr { M1faddr (0) } } impl core :: fmt :: Debug for M1faddr { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M1faddr") . field ("eccfaddr" , & self . eccfaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M1faddr { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M1faddr {{ eccfaddr: {=u32:?} }}" , self . eccfaddr ()) } } # [doc = "monitor 0 failing data high register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M1fdh (pub u32) ; impl M1fdh { # [doc = "ECC failing data high bitss"]
# [inline (always)]
pub const fn eccfdh (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing data high bitss"]
# [inline (always)]
pub fn set_eccfdh (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M1fdh { # [inline (always)]
fn default () -> M1fdh { M1fdh (0) } } impl core :: fmt :: Debug for M1fdh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M1fdh") . field ("eccfdh" , & self . eccfdh ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M1fdh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M1fdh {{ eccfdh: {=u32:?} }}" , self . eccfdh ()) } } # [doc = "monitor 1 failing data low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M1fdl (pub u32) ; impl M1fdl { # [doc = "ECC failing data low bits"]
# [inline (always)]
pub const fn eccfdl (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing data low bits"]
# [inline (always)]
pub fn set_eccfdl (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M1fdl { # [inline (always)]
fn default () -> M1fdl { M1fdl (0) } } impl core :: fmt :: Debug for M1fdl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M1fdl") . field ("eccfdl" , & self . eccfdl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M1fdl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M1fdl {{ eccfdl: {=u32:?} }}" , self . eccfdl ()) } } # [doc = "monitor 1 failing ECC error code register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M1fecode (pub u32) ; impl M1fecode { # [doc = "ECC failing error code"]
# [inline (always)]
pub const fn eccfecode (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing error code"]
# [inline (always)]
pub fn set_eccfecode (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M1fecode { # [inline (always)]
fn default () -> M1fecode { M1fecode (0) } } impl core :: fmt :: Debug for M1fecode { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M1fecode") . field ("eccfecode" , & self . eccfecode ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M1fecode { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M1fecode {{ eccfecode: {=u32:?} }}" , self . eccfecode ()) } } # [doc = "monitor 1 status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M1stat (pub u32) ; impl M1stat { # [doc = "ECC single error detected and corrected flag"]
# [inline (always)]
pub const fn eccserrdcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "ECC single error detected and corrected flag"]
# [inline (always)]
pub fn set_eccserrdcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "ECC double error detected flag"]
# [inline (always)]
pub const fn eccderrdf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "ECC double error detected flag"]
# [inline (always)]
pub fn set_eccderrdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "ECC double error on byte write detected flag"]
# [inline (always)]
pub const fn eccderrbwdf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "ECC double error on byte write detected flag"]
# [inline (always)]
pub fn set_eccderrbwdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for M1stat { # [inline (always)]
fn default () -> M1stat { M1stat (0) } } impl core :: fmt :: Debug for M1stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M1stat") . field ("eccserrdcf" , & self . eccserrdcf ()) . field ("eccderrdf" , & self . eccderrdf ()) . field ("eccderrbwdf" , & self . eccderrbwdf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M1stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M1stat {{ eccserrdcf: {=bool:?}, eccderrdf: {=bool:?}, eccderrbwdf: {=bool:?} }}" , self . eccserrdcf () , self . eccderrdf () , self . eccderrbwdf ()) } } # [doc = "monitor 0 control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M2ctl (pub u32) ; impl M2ctl { # [doc = "ECC single error interrupt enable"]
# [inline (always)]
pub const fn eccserrie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "ECC single error interrupt enable"]
# [inline (always)]
pub fn set_eccserrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "ECC double error interrupt enable"]
# [inline (always)]
pub const fn eccderrie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "ECC double error interrupt enable"]
# [inline (always)]
pub fn set_eccderrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "ECC double error on byte write interrupt enable"]
# [inline (always)]
pub const fn eccderrbwie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "ECC double error on byte write interrupt enable"]
# [inline (always)]
pub fn set_eccderrbwie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "ECC error latching enable"]
# [inline (always)]
pub const fn eccerrlaten (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "ECC error latching enable"]
# [inline (always)]
pub fn set_eccerrlaten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } } impl Default for M2ctl { # [inline (always)]
fn default () -> M2ctl { M2ctl (0) } } impl core :: fmt :: Debug for M2ctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M2ctl") . field ("eccserrie" , & self . eccserrie ()) . field ("eccderrie" , & self . eccderrie ()) . field ("eccderrbwie" , & self . eccderrbwie ()) . field ("eccerrlaten" , & self . eccerrlaten ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M2ctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M2ctl {{ eccserrie: {=bool:?}, eccderrie: {=bool:?}, eccderrbwie: {=bool:?}, eccerrlaten: {=bool:?} }}" , self . eccserrie () , self . eccderrie () , self . eccderrbwie () , self . eccerrlaten ()) } } # [doc = "monitor 0 failing address register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M2faddr (pub u32) ; impl M2faddr { # [doc = "ECC error failing address"]
# [inline (always)]
pub const fn eccfaddr (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC error failing address"]
# [inline (always)]
pub fn set_eccfaddr (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M2faddr { # [inline (always)]
fn default () -> M2faddr { M2faddr (0) } } impl core :: fmt :: Debug for M2faddr { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M2faddr") . field ("eccfaddr" , & self . eccfaddr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M2faddr { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M2faddr {{ eccfaddr: {=u32:?} }}" , self . eccfaddr ()) } } # [doc = "monitor 0 failing data high register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M2fdh (pub u32) ; impl M2fdh { # [doc = "ECC failing data high bitss"]
# [inline (always)]
pub const fn eccfdh (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing data high bitss"]
# [inline (always)]
pub fn set_eccfdh (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M2fdh { # [inline (always)]
fn default () -> M2fdh { M2fdh (0) } } impl core :: fmt :: Debug for M2fdh { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M2fdh") . field ("eccfdh" , & self . eccfdh ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M2fdh { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M2fdh {{ eccfdh: {=u32:?} }}" , self . eccfdh ()) } } # [doc = "monitor 0 failing data low register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M2fdl (pub u32) ; impl M2fdl { # [doc = "ECC failing data low bits"]
# [inline (always)]
pub const fn eccfdl (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing data low bits"]
# [inline (always)]
pub fn set_eccfdl (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M2fdl { # [inline (always)]
fn default () -> M2fdl { M2fdl (0) } } impl core :: fmt :: Debug for M2fdl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M2fdl") . field ("eccfdl" , & self . eccfdl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M2fdl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M2fdl {{ eccfdl: {=u32:?} }}" , self . eccfdl ()) } } # [doc = "monitor 0 failing ECC error code register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M2fecode (pub u32) ; impl M2fecode { # [doc = "ECC failing error code"]
# [inline (always)]
pub const fn eccfecode (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "ECC failing error code"]
# [inline (always)]
pub fn set_eccfecode (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for M2fecode { # [inline (always)]
fn default () -> M2fecode { M2fecode (0) } } impl core :: fmt :: Debug for M2fecode { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M2fecode") . field ("eccfecode" , & self . eccfecode ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M2fecode { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M2fecode {{ eccfecode: {=u32:?} }}" , self . eccfecode ()) } } # [doc = "monitor 0 status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct M2stat (pub u32) ; impl M2stat { # [doc = "ECC single error detected and corrected flag"]
# [inline (always)]
pub const fn eccserrdcf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "ECC single error detected and corrected flag"]
# [inline (always)]
pub fn set_eccserrdcf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "ECC double error detected flag"]
# [inline (always)]
pub const fn eccderrdf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "ECC double error detected flag"]
# [inline (always)]
pub fn set_eccderrdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "ECC double error on byte write detected flag"]
# [inline (always)]
pub const fn eccderrbwdf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "ECC double error on byte write detected flag"]
# [inline (always)]
pub fn set_eccderrbwdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } } impl Default for M2stat { # [inline (always)]
fn default () -> M2stat { M2stat (0) } } impl core :: fmt :: Debug for M2stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("M2stat") . field ("eccserrdcf" , & self . eccserrdcf ()) . field ("eccderrdf" , & self . eccderrdf ()) . field ("eccderrbwdf" , & self . eccderrbwdf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for M2stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "M2stat {{ eccserrdcf: {=bool:?}, eccderrdf: {=bool:?}, eccderrbwdf: {=bool:?} }}" , self . eccserrdcf () , self . eccderrdf () , self . eccderrbwdf ()) } } }
