#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "General-purpose-timers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Timer1 { ptr : * mut u8 } unsafe impl Send for Timer1 { } unsafe impl Sync for Timer1 { } impl Timer1 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Slave mode configuration register"]
# [inline (always)]
pub const fn smcfg (self) -> crate :: common :: Reg < regs :: Smcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "DMA and interrupt enable register"]
# [inline (always)]
pub const fn dmainten (self) -> crate :: common :: Reg < regs :: Dmainten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Interrupt flag register"]
# [inline (always)]
pub const fn intf (self) -> crate :: common :: Reg < regs :: Intf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Software event generation register"]
# [inline (always)]
pub const fn swevg (self) -> crate :: common :: Reg < regs :: Swevg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Channel control register 0 (input mode)"]
# [inline (always)]
pub const fn chctl0_input (self) -> crate :: common :: Reg < regs :: Chctl0Input , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Channel control register 0 (output mode)"]
# [inline (always)]
pub const fn chctl0_output (self) -> crate :: common :: Reg < regs :: Chctl0Output , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Channel control register 1 (input mode)"]
# [inline (always)]
pub const fn chctl1_input (self) -> crate :: common :: Reg < regs :: Chctl1Input , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Channel control register 1 (output mode)"]
# [inline (always)]
pub const fn chctl1_output (self) -> crate :: common :: Reg < regs :: Chctl1Output , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Channel control register 2"]
# [inline (always)]
pub const fn chctl2 (self) -> crate :: common :: Reg < regs :: Chctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "counter"]
# [inline (always)]
pub const fn cnt (self) -> crate :: common :: Reg < regs :: Cnt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "prescaler"]
# [inline (always)]
pub const fn psc (self) -> crate :: common :: Reg < regs :: Psc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Counter auto reload register"]
# [inline (always)]
pub const fn car (self) -> crate :: common :: Reg < regs :: Car , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Channel 0 capture/compare value register"]
# [inline (always)]
pub const fn ch0cv (self) -> crate :: common :: Reg < regs :: Ch0cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x34usize) as _) } } # [doc = "Channel 1 capture/compare value register"]
# [inline (always)]
pub const fn ch1cv (self) -> crate :: common :: Reg < regs :: Ch1cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "Channel 2 capture/compare value register"]
# [inline (always)]
pub const fn ch2cv (self) -> crate :: common :: Reg < regs :: Ch2cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Channel 3 capture/compare value register"]
# [inline (always)]
pub const fn ch3cv (self) -> crate :: common :: Reg < regs :: Ch3cv , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x40usize) as _) } } # [doc = "Channel 0 additional compare value register"]
# [inline (always)]
pub const fn ch0comv_add (self) -> crate :: common :: Reg < regs :: Ch0comvAdd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x64usize) as _) } } # [doc = "Channel 1 additional compare value register"]
# [inline (always)]
pub const fn ch1comv_add (self) -> crate :: common :: Reg < regs :: Ch1comvAdd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x68usize) as _) } } # [doc = "Channel 2 additional compare value register"]
# [inline (always)]
pub const fn ch2comv_add (self) -> crate :: common :: Reg < regs :: Ch2comvAdd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x6cusize) as _) } } # [doc = "Channel 3 additional compare value register"]
# [inline (always)]
pub const fn ch3comv_add (self) -> crate :: common :: Reg < regs :: Ch3comvAdd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x70usize) as _) } } # [doc = "Control register 2"]
# [inline (always)]
pub const fn ctl2 (self) -> crate :: common :: Reg < regs :: Ctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x74usize) as _) } } # [doc = "Watchdog counter register"]
# [inline (always)]
pub const fn wdgper (self) -> crate :: common :: Reg < regs :: Wdgper , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x94usize) as _) } } # [doc = "DMA configuration register"]
# [inline (always)]
pub const fn dmacfg (self) -> crate :: common :: Reg < regs :: Dmacfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xe0usize) as _) } } # [doc = "DMA transfer buffer register"]
# [inline (always)]
pub const fn dmatb (self) -> crate :: common :: Reg < regs :: Dmatb , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xe4usize) as _) } } # [doc = "Configuration register"]
# [inline (always)]
pub const fn cfg (self) -> crate :: common :: Reg < regs :: Cfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xfcusize) as _) } } } pub mod regs { # [doc = "Counter auto reload register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Car (pub u32) ; impl Car { # [doc = "Counter auto reload value"]
# [inline (always)]
pub const fn carl (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Counter auto reload value"]
# [inline (always)]
pub fn set_carl (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Car { # [inline (always)]
fn default () -> Car { Car (0) } } impl core :: fmt :: Debug for Car { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Car") . field ("carl" , & self . carl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Car { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Car {{ carl: {=u32:?} }}" , self . carl ()) } } # [doc = "Configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cfg (pub u32) ; impl Cfg { # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub const fn chvsel (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Write CHxVAL register selection"]
# [inline (always)]
pub fn set_chvsel (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } } impl Default for Cfg { # [inline (always)]
fn default () -> Cfg { Cfg (0) } } impl core :: fmt :: Debug for Cfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cfg") . field ("chvsel" , & self . chvsel ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cfg {{ chvsel: {=bool:?} }}" , self . chvsel ()) } } # [doc = "Channel 0 additional compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch0comvAdd (pub u32) ; impl Ch0comvAdd { # [doc = "Additional compare value of channel 0"]
# [inline (always)]
pub const fn ch0comval_add (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Additional compare value of channel 0"]
# [inline (always)]
pub fn set_ch0comval_add (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch0comvAdd { # [inline (always)]
fn default () -> Ch0comvAdd { Ch0comvAdd (0) } } impl core :: fmt :: Debug for Ch0comvAdd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch0comvAdd") . field ("ch0comval_add" , & self . ch0comval_add ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch0comvAdd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch0comvAdd {{ ch0comval_add: {=u32:?} }}" , self . ch0comval_add ()) } } # [doc = "Channel 0 capture/compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch0cv (pub u32) ; impl Ch0cv { # [doc = "Capture or compare value of channel0"]
# [inline (always)]
pub const fn ch0val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Capture or compare value of channel0"]
# [inline (always)]
pub fn set_ch0val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch0cv { # [inline (always)]
fn default () -> Ch0cv { Ch0cv (0) } } impl core :: fmt :: Debug for Ch0cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch0cv") . field ("ch0val" , & self . ch0val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch0cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch0cv {{ ch0val: {=u32:?} }}" , self . ch0val ()) } } # [doc = "Channel 1 additional compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch1comvAdd (pub u32) ; impl Ch1comvAdd { # [doc = "Additional compare value of channel 1"]
# [inline (always)]
pub const fn ch1comval_add (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Additional compare value of channel 1"]
# [inline (always)]
pub fn set_ch1comval_add (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch1comvAdd { # [inline (always)]
fn default () -> Ch1comvAdd { Ch1comvAdd (0) } } impl core :: fmt :: Debug for Ch1comvAdd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch1comvAdd") . field ("ch1comval_add" , & self . ch1comval_add ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch1comvAdd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch1comvAdd {{ ch1comval_add: {=u32:?} }}" , self . ch1comval_add ()) } } # [doc = "Channel 1 capture/compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch1cv (pub u32) ; impl Ch1cv { # [doc = "Capture or compare value of channel1"]
# [inline (always)]
pub const fn ch1val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Capture or compare value of channel1"]
# [inline (always)]
pub fn set_ch1val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch1cv { # [inline (always)]
fn default () -> Ch1cv { Ch1cv (0) } } impl core :: fmt :: Debug for Ch1cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch1cv") . field ("ch1val" , & self . ch1val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch1cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch1cv {{ ch1val: {=u32:?} }}" , self . ch1val ()) } } # [doc = "Channel 2 additional compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch2comvAdd (pub u32) ; impl Ch2comvAdd { # [doc = "Additional compare value of channel 2"]
# [inline (always)]
pub const fn ch2comval_add (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Additional compare value of channel 2"]
# [inline (always)]
pub fn set_ch2comval_add (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch2comvAdd { # [inline (always)]
fn default () -> Ch2comvAdd { Ch2comvAdd (0) } } impl core :: fmt :: Debug for Ch2comvAdd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch2comvAdd") . field ("ch2comval_add" , & self . ch2comval_add ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch2comvAdd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch2comvAdd {{ ch2comval_add: {=u32:?} }}" , self . ch2comval_add ()) } } # [doc = "Channel 2 capture/compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch2cv (pub u32) ; impl Ch2cv { # [doc = "Capture or compare value of channel 2"]
# [inline (always)]
pub const fn ch2val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Capture or compare value of channel 2"]
# [inline (always)]
pub fn set_ch2val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch2cv { # [inline (always)]
fn default () -> Ch2cv { Ch2cv (0) } } impl core :: fmt :: Debug for Ch2cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch2cv") . field ("ch2val" , & self . ch2val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch2cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch2cv {{ ch2val: {=u32:?} }}" , self . ch2val ()) } } # [doc = "Channel 3 additional compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch3comvAdd (pub u32) ; impl Ch3comvAdd { # [doc = "Additional compare value of channel 3"]
# [inline (always)]
pub const fn ch3comval_add (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Additional compare value of channel 3"]
# [inline (always)]
pub fn set_ch3comval_add (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch3comvAdd { # [inline (always)]
fn default () -> Ch3comvAdd { Ch3comvAdd (0) } } impl core :: fmt :: Debug for Ch3comvAdd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch3comvAdd") . field ("ch3comval_add" , & self . ch3comval_add ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch3comvAdd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch3comvAdd {{ ch3comval_add: {=u32:?} }}" , self . ch3comval_add ()) } } # [doc = "Channel 3 capture/compare value register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ch3cv (pub u32) ; impl Ch3cv { # [doc = "Capture or compare value of channel 3"]
# [inline (always)]
pub const fn ch3val (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Capture or compare value of channel 3"]
# [inline (always)]
pub fn set_ch3val (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Ch3cv { # [inline (always)]
fn default () -> Ch3cv { Ch3cv (0) } } impl core :: fmt :: Debug for Ch3cv { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ch3cv") . field ("ch3val" , & self . ch3val ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ch3cv { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ch3cv {{ ch3val: {=u32:?} }}" , self . ch3val ()) } } # [doc = "Channel control register 0 (input mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl0Input (pub u32) ; impl Chctl0Input { # [doc = "Channel 0 mode selection"]
# [inline (always)]
pub const fn ch0ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Channel 0 mode selection"]
# [inline (always)]
pub fn set_ch0ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Channel 0 input capture prescaler"]
# [inline (always)]
pub const fn ch0cappsc (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Channel 0 input capture prescaler"]
# [inline (always)]
pub fn set_ch0cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Channel 0 input capture filter control"]
# [inline (always)]
pub const fn ch0capflt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Channel 0 input capture filter control"]
# [inline (always)]
pub fn set_ch0capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Channel 1 mode selection"]
# [inline (always)]
pub const fn ch1ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Channel 1 mode selection"]
# [inline (always)]
pub fn set_ch1ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Channel 1 input capture prescaler"]
# [inline (always)]
pub const fn ch1cappsc (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Channel 1 input capture prescaler"]
# [inline (always)]
pub fn set_ch1cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Channel 1 input capture filter control"]
# [inline (always)]
pub const fn ch1capflt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Channel 1 input capture filter control"]
# [inline (always)]
pub fn set_ch1capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } # [doc = "2th bit of CH0MS"]
# [inline (always)]
pub const fn ch0ms_2 (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH0MS"]
# [inline (always)]
pub fn set_ch0ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "2th bit of CH1MS"]
# [inline (always)]
pub const fn ch1ms_2 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH1MS"]
# [inline (always)]
pub fn set_ch1ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Chctl0Input { # [inline (always)]
fn default () -> Chctl0Input { Chctl0Input (0) } } impl core :: fmt :: Debug for Chctl0Input { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl0Input") . field ("ch0ms" , & self . ch0ms ()) . field ("ch0cappsc" , & self . ch0cappsc ()) . field ("ch0capflt" , & self . ch0capflt ()) . field ("ch1ms" , & self . ch1ms ()) . field ("ch1cappsc" , & self . ch1cappsc ()) . field ("ch1capflt" , & self . ch1capflt ()) . field ("ch0ms_2" , & self . ch0ms_2 ()) . field ("ch1ms_2" , & self . ch1ms_2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl0Input { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl0Input {{ ch0ms: {=u8:?}, ch0cappsc: {=u8:?}, ch0capflt: {=u8:?}, ch1ms: {=u8:?}, ch1cappsc: {=u8:?}, ch1capflt: {=u8:?}, ch0ms_2: {=bool:?}, ch1ms_2: {=bool:?} }}" , self . ch0ms () , self . ch0cappsc () , self . ch0capflt () , self . ch1ms () , self . ch1cappsc () , self . ch1capflt () , self . ch0ms_2 () , self . ch1ms_2 ()) } } # [doc = "Channel control register 0 (output mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl0Output (pub u32) ; impl Chctl0Output { # [doc = "Channel 0 I/O mode selection"]
# [inline (always)]
pub const fn ch0ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Channel 0 I/O mode selection"]
# [inline (always)]
pub fn set_ch0ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Channel 0 compare output shadow enable"]
# [inline (always)]
pub const fn ch0comsen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 0 compare output shadow enable"]
# [inline (always)]
pub fn set_ch0comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 0 compare output control"]
# [inline (always)]
pub const fn ch0comctl (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Channel 0 compare output control"]
# [inline (always)]
pub fn set_ch0comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Channel 0 output compare clear enable"]
# [inline (always)]
pub const fn ch0comcen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Channel 0 output compare clear enable"]
# [inline (always)]
pub fn set_ch0comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Channel 1 mode selection"]
# [inline (always)]
pub const fn ch1ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Channel 1 mode selection"]
# [inline (always)]
pub fn set_ch1ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Channel 1 output compare shadow enable"]
# [inline (always)]
pub const fn ch1comsen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Channel 1 output compare shadow enable"]
# [inline (always)]
pub fn set_ch1comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Channel 1 compare output control"]
# [inline (always)]
pub const fn ch1comctl (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Channel 1 compare output control"]
# [inline (always)]
pub fn set_ch1comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Channel 1 output compare clear enable"]
# [inline (always)]
pub const fn ch1comcen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Channel 1 output compare clear enable"]
# [inline (always)]
pub fn set_ch1comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Bit 3 of channel 1 compare output control"]
# [inline (always)]
pub const fn ch0comctl_3 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Bit 3 of channel 1 compare output control"]
# [inline (always)]
pub fn set_ch0comctl_3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Bit 3 of channel 1 compare output control"]
# [inline (always)]
pub const fn ch1comctl_3 (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Bit 3 of channel 1 compare output control"]
# [inline (always)]
pub fn set_ch1comctl_3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Channel 0 additional compare output shadow enable"]
# [inline (always)]
pub const fn ch0comaddsen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Channel 0 additional compare output shadow enable"]
# [inline (always)]
pub fn set_ch0comaddsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Channel 1 additional compare output shadow enable"]
# [inline (always)]
pub const fn ch1comaddsen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Channel 1 additional compare output shadow enable"]
# [inline (always)]
pub fn set_ch1comaddsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "2th bit of CH0MS"]
# [inline (always)]
pub const fn ch0ms_2 (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH0MS"]
# [inline (always)]
pub fn set_ch0ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "2th bit of CH1MS"]
# [inline (always)]
pub const fn ch1ms_2 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH1MS"]
# [inline (always)]
pub fn set_ch1ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Chctl0Output { # [inline (always)]
fn default () -> Chctl0Output { Chctl0Output (0) } } impl core :: fmt :: Debug for Chctl0Output { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl0Output") . field ("ch0ms" , & self . ch0ms ()) . field ("ch0comsen" , & self . ch0comsen ()) . field ("ch0comctl" , & self . ch0comctl ()) . field ("ch0comcen" , & self . ch0comcen ()) . field ("ch1ms" , & self . ch1ms ()) . field ("ch1comsen" , & self . ch1comsen ()) . field ("ch1comctl" , & self . ch1comctl ()) . field ("ch1comcen" , & self . ch1comcen ()) . field ("ch0comctl_3" , & self . ch0comctl_3 ()) . field ("ch1comctl_3" , & self . ch1comctl_3 ()) . field ("ch0comaddsen" , & self . ch0comaddsen ()) . field ("ch1comaddsen" , & self . ch1comaddsen ()) . field ("ch0ms_2" , & self . ch0ms_2 ()) . field ("ch1ms_2" , & self . ch1ms_2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl0Output { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl0Output {{ ch0ms: {=u8:?}, ch0comsen: {=bool:?}, ch0comctl: {=u8:?}, ch0comcen: {=bool:?}, ch1ms: {=u8:?}, ch1comsen: {=bool:?}, ch1comctl: {=u8:?}, ch1comcen: {=bool:?}, ch0comctl_3: {=bool:?}, ch1comctl_3: {=bool:?}, ch0comaddsen: {=bool:?}, ch1comaddsen: {=bool:?}, ch0ms_2: {=bool:?}, ch1ms_2: {=bool:?} }}" , self . ch0ms () , self . ch0comsen () , self . ch0comctl () , self . ch0comcen () , self . ch1ms () , self . ch1comsen () , self . ch1comctl () , self . ch1comcen () , self . ch0comctl_3 () , self . ch1comctl_3 () , self . ch0comaddsen () , self . ch1comaddsen () , self . ch0ms_2 () , self . ch1ms_2 ()) } } # [doc = "Channel control register 1 (input mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl1Input (pub u32) ; impl Chctl1Input { # [doc = "Channel 2 mode selection"]
# [inline (always)]
pub const fn ch2ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Channel 2 mode selection"]
# [inline (always)]
pub fn set_ch2ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Channel 2 input capture prescaler"]
# [inline (always)]
pub const fn ch2cappsc (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "Channel 2 input capture prescaler"]
# [inline (always)]
pub fn set_ch2cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Channel 2 input capture filter control"]
# [inline (always)]
pub const fn ch2capflt (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Channel 2 input capture filter control"]
# [inline (always)]
pub fn set_ch2capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Channel 3 mode selection"]
# [inline (always)]
pub const fn ch3ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Channel 3 mode selection"]
# [inline (always)]
pub fn set_ch3ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Channel 3 input capture prescaler"]
# [inline (always)]
pub const fn ch3cappsc (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Channel 3 input capture prescaler"]
# [inline (always)]
pub fn set_ch3cappsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Channel 3 input capture filter control"]
# [inline (always)]
pub const fn ch3capflt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x0f ; val as u8 } # [doc = "Channel 3 input capture filter control"]
# [inline (always)]
pub fn set_ch3capflt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 12usize)) | (((val as u32) & 0x0f) << 12usize) ; } # [doc = "2th bit of CH2MS"]
# [inline (always)]
pub const fn ch2ms_2 (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH2MS"]
# [inline (always)]
pub fn set_ch2ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "2th bit of CH3MS"]
# [inline (always)]
pub const fn ch3ms_2 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH3MS"]
# [inline (always)]
pub fn set_ch3ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Chctl1Input { # [inline (always)]
fn default () -> Chctl1Input { Chctl1Input (0) } } impl core :: fmt :: Debug for Chctl1Input { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl1Input") . field ("ch2ms" , & self . ch2ms ()) . field ("ch2cappsc" , & self . ch2cappsc ()) . field ("ch2capflt" , & self . ch2capflt ()) . field ("ch3ms" , & self . ch3ms ()) . field ("ch3cappsc" , & self . ch3cappsc ()) . field ("ch3capflt" , & self . ch3capflt ()) . field ("ch2ms_2" , & self . ch2ms_2 ()) . field ("ch3ms_2" , & self . ch3ms_2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl1Input { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl1Input {{ ch2ms: {=u8:?}, ch2cappsc: {=u8:?}, ch2capflt: {=u8:?}, ch3ms: {=u8:?}, ch3cappsc: {=u8:?}, ch3capflt: {=u8:?}, ch2ms_2: {=bool:?}, ch3ms_2: {=bool:?} }}" , self . ch2ms () , self . ch2cappsc () , self . ch2capflt () , self . ch3ms () , self . ch3cappsc () , self . ch3capflt () , self . ch2ms_2 () , self . ch3ms_2 ()) } } # [doc = "Channel control register 1 (output mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl1Output (pub u32) ; impl Chctl1Output { # [doc = "Channel 2 I/O mode selection"]
# [inline (always)]
pub const fn ch2ms (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Channel 2 I/O mode selection"]
# [inline (always)]
pub fn set_ch2ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "Channel 2 compare output shadow enable"]
# [inline (always)]
pub const fn ch2comsen (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 2 compare output shadow enable"]
# [inline (always)]
pub fn set_ch2comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 2 compare output control"]
# [inline (always)]
pub const fn ch2comctl (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Channel 2 compare output control"]
# [inline (always)]
pub fn set_ch2comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Channel 2 output compare clear enable"]
# [inline (always)]
pub const fn ch2comcen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Channel 2 output compare clear enable"]
# [inline (always)]
pub fn set_ch2comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Channel 3 mode selection"]
# [inline (always)]
pub const fn ch3ms (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Channel 3 mode selection"]
# [inline (always)]
pub fn set_ch3ms (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Channel 3 output compare shadow enable"]
# [inline (always)]
pub const fn ch3comsen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Channel 3 output compare shadow enable"]
# [inline (always)]
pub fn set_ch3comsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Channel 3 compare output control"]
# [inline (always)]
pub const fn ch3comctl (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Channel 3 compare output control"]
# [inline (always)]
pub fn set_ch3comctl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Channel 3 output compare clear enable"]
# [inline (always)]
pub const fn ch3comcen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Channel 3 output compare clear enable"]
# [inline (always)]
pub fn set_ch3comcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "BIT 3 of channel 2 compare output control"]
# [inline (always)]
pub const fn ch2comctl_3 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "BIT 3 of channel 2 compare output control"]
# [inline (always)]
pub fn set_ch2comctl_3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "BIT 3 of channel 3 compare output control"]
# [inline (always)]
pub const fn ch3comctl_3 (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "BIT 3 of channel 3 compare output control"]
# [inline (always)]
pub fn set_ch3comctl_3 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Channel 2 additional compare output shadow enable"]
# [inline (always)]
pub const fn ch2comaddsen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Channel 2 additional compare output shadow enable"]
# [inline (always)]
pub fn set_ch2comaddsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Channel 3 additional compare output shadow enable"]
# [inline (always)]
pub const fn ch3comaddsen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Channel 3 additional compare output shadow enable"]
# [inline (always)]
pub fn set_ch3comaddsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "2th bit of CH2MS"]
# [inline (always)]
pub const fn ch2ms_2 (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH2MS"]
# [inline (always)]
pub fn set_ch2ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "2th bit of CH3MS"]
# [inline (always)]
pub const fn ch3ms_2 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "2th bit of CH3MS"]
# [inline (always)]
pub fn set_ch3ms_2 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Chctl1Output { # [inline (always)]
fn default () -> Chctl1Output { Chctl1Output (0) } } impl core :: fmt :: Debug for Chctl1Output { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl1Output") . field ("ch2ms" , & self . ch2ms ()) . field ("ch2comsen" , & self . ch2comsen ()) . field ("ch2comctl" , & self . ch2comctl ()) . field ("ch2comcen" , & self . ch2comcen ()) . field ("ch3ms" , & self . ch3ms ()) . field ("ch3comsen" , & self . ch3comsen ()) . field ("ch3comctl" , & self . ch3comctl ()) . field ("ch3comcen" , & self . ch3comcen ()) . field ("ch2comctl_3" , & self . ch2comctl_3 ()) . field ("ch3comctl_3" , & self . ch3comctl_3 ()) . field ("ch2comaddsen" , & self . ch2comaddsen ()) . field ("ch3comaddsen" , & self . ch3comaddsen ()) . field ("ch2ms_2" , & self . ch2ms_2 ()) . field ("ch3ms_2" , & self . ch3ms_2 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl1Output { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl1Output {{ ch2ms: {=u8:?}, ch2comsen: {=bool:?}, ch2comctl: {=u8:?}, ch2comcen: {=bool:?}, ch3ms: {=u8:?}, ch3comsen: {=bool:?}, ch3comctl: {=u8:?}, ch3comcen: {=bool:?}, ch2comctl_3: {=bool:?}, ch3comctl_3: {=bool:?}, ch2comaddsen: {=bool:?}, ch3comaddsen: {=bool:?}, ch2ms_2: {=bool:?}, ch3ms_2: {=bool:?} }}" , self . ch2ms () , self . ch2comsen () , self . ch2comctl () , self . ch2comcen () , self . ch3ms () , self . ch3comsen () , self . ch3comctl () , self . ch3comcen () , self . ch2comctl_3 () , self . ch3comctl_3 () , self . ch2comaddsen () , self . ch3comaddsen () , self . ch2ms_2 () , self . ch3ms_2 ()) } } # [doc = "Channel control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chctl2 (pub u32) ; impl Chctl2 { # [doc = "Channel 0 capture/compare function enable"]
# [inline (always)]
pub const fn ch0en (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare function enable"]
# [inline (always)]
pub fn set_ch0en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture/compare function polarity"]
# [inline (always)]
pub const fn ch0p (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare function polarity"]
# [inline (always)]
pub fn set_ch0p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Multi mode channel 0 output polarity"]
# [inline (always)]
pub const fn ch0np (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Multi mode channel 0 output polarity"]
# [inline (always)]
pub fn set_ch0np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 1 capture/compare function enable"]
# [inline (always)]
pub const fn ch1en (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare function enable"]
# [inline (always)]
pub fn set_ch1en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Channel 1 capture/compare function polarity"]
# [inline (always)]
pub const fn ch1p (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare function polarity"]
# [inline (always)]
pub fn set_ch1p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Multi mode channel 1 output polarity"]
# [inline (always)]
pub const fn ch1np (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Multi mode channel 1 output polarity"]
# [inline (always)]
pub fn set_ch1np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Channel 2 capture/compare function enable"]
# [inline (always)]
pub const fn ch2en (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture/compare function enable"]
# [inline (always)]
pub fn set_ch2en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Channel 2 capture/compare function polarity"]
# [inline (always)]
pub const fn ch2p (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture/compare function polarity"]
# [inline (always)]
pub fn set_ch2p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Multi mode channel 2 capture/compare polarity"]
# [inline (always)]
pub const fn ch2np (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Multi mode channel 2 capture/compare polarity"]
# [inline (always)]
pub fn set_ch2np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Channel 3 capture/compare function enable"]
# [inline (always)]
pub const fn ch3en (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture/compare function enable"]
# [inline (always)]
pub fn set_ch3en (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Channel 3 capture/compare function polarity"]
# [inline (always)]
pub const fn ch3p (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture/compare function polarity"]
# [inline (always)]
pub fn set_ch3p (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Multi mode channel 3 capture/compare polarity"]
# [inline (always)]
pub const fn ch3np (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Multi mode channel 3 capture/compare polarity"]
# [inline (always)]
pub fn set_ch3np (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Chctl2 { # [inline (always)]
fn default () -> Chctl2 { Chctl2 (0) } } impl core :: fmt :: Debug for Chctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chctl2") . field ("ch0en" , & self . ch0en ()) . field ("ch0p" , & self . ch0p ()) . field ("ch0np" , & self . ch0np ()) . field ("ch1en" , & self . ch1en ()) . field ("ch1p" , & self . ch1p ()) . field ("ch1np" , & self . ch1np ()) . field ("ch2en" , & self . ch2en ()) . field ("ch2p" , & self . ch2p ()) . field ("ch2np" , & self . ch2np ()) . field ("ch3en" , & self . ch3en ()) . field ("ch3p" , & self . ch3p ()) . field ("ch3np" , & self . ch3np ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chctl2 {{ ch0en: {=bool:?}, ch0p: {=bool:?}, ch0np: {=bool:?}, ch1en: {=bool:?}, ch1p: {=bool:?}, ch1np: {=bool:?}, ch2en: {=bool:?}, ch2p: {=bool:?}, ch2np: {=bool:?}, ch3en: {=bool:?}, ch3p: {=bool:?}, ch3np: {=bool:?} }}" , self . ch0en () , self . ch0p () , self . ch0np () , self . ch1en () , self . ch1p () , self . ch1np () , self . ch2en () , self . ch2p () , self . ch2np () , self . ch3en () , self . ch3p () , self . ch3np ()) } } # [doc = "counter"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cnt (pub u32) ; impl Cnt { # [doc = "current counter value"]
# [inline (always)]
pub const fn cnt (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "current counter value"]
# [inline (always)]
pub fn set_cnt (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Cnt { # [inline (always)]
fn default () -> Cnt { Cnt (0) } } impl core :: fmt :: Debug for Cnt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cnt") . field ("cnt" , & self . cnt ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cnt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cnt {{ cnt: {=u32:?} }}" , self . cnt ()) } } # [doc = "Control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "Counter enable"]
# [inline (always)]
pub const fn cen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Counter enable"]
# [inline (always)]
pub fn set_cen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Update disable"]
# [inline (always)]
pub const fn updis (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Update disable"]
# [inline (always)]
pub fn set_updis (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Update source"]
# [inline (always)]
pub const fn ups (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Update source"]
# [inline (always)]
pub fn set_ups (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Single pulse mode"]
# [inline (always)]
pub const fn spm (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Single pulse mode"]
# [inline (always)]
pub fn set_spm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Direction"]
# [inline (always)]
pub const fn dir (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Direction"]
# [inline (always)]
pub fn set_dir (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Counter align mode selection"]
# [inline (always)]
pub const fn cam (& self) -> u8 { let val = (self . 0 >> 5usize) & 0x03 ; val as u8 } # [doc = "Counter align mode selection"]
# [inline (always)]
pub fn set_cam (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 5usize)) | (((val as u32) & 0x03) << 5usize) ; } # [doc = "Auto-reload shadow enable"]
# [inline (always)]
pub const fn arse (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Auto-reload shadow enable"]
# [inline (always)]
pub fn set_arse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Clock division"]
# [inline (always)]
pub const fn ckdiv (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Clock division"]
# [inline (always)]
pub fn set_ckdiv (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "UPIF bit backup enable"]
# [inline (always)]
pub const fn upifbuen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "UPIF bit backup enable"]
# [inline (always)]
pub fn set_upifbuen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("cen" , & self . cen ()) . field ("updis" , & self . updis ()) . field ("ups" , & self . ups ()) . field ("spm" , & self . spm ()) . field ("dir" , & self . dir ()) . field ("cam" , & self . cam ()) . field ("arse" , & self . arse ()) . field ("ckdiv" , & self . ckdiv ()) . field ("upifbuen" , & self . upifbuen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ cen: {=bool:?}, updis: {=bool:?}, ups: {=bool:?}, spm: {=bool:?}, dir: {=bool:?}, cam: {=u8:?}, arse: {=bool:?}, ckdiv: {=u8:?}, upifbuen: {=bool:?} }}" , self . cen () , self . updis () , self . ups () , self . spm () , self . dir () , self . cam () , self . arse () , self . ckdiv () , self . upifbuen ()) } } # [doc = "Control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Commutation control shadow enable"]
# [inline (always)]
pub const fn ccse (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Commutation control shadow enable"]
# [inline (always)]
pub fn set_ccse (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Commutation control shadow register update control"]
# [inline (always)]
pub const fn ccuc_0 (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Commutation control shadow register update control"]
# [inline (always)]
pub fn set_ccuc_0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "DMA request source selection"]
# [inline (always)]
pub const fn dmas (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "DMA request source selection"]
# [inline (always)]
pub fn set_dmas (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Master mode control 0"]
# [inline (always)]
pub const fn mmc0 (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x07 ; val as u8 } # [doc = "Master mode control 0"]
# [inline (always)]
pub fn set_mmc0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 4usize)) | (((val as u32) & 0x07) << 4usize) ; } # [doc = "Channel 0 trigger input selection"]
# [inline (always)]
pub const fn ti0s (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Channel 0 trigger input selection"]
# [inline (always)]
pub fn set_ti0s (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("ccse" , & self . ccse ()) . field ("ccuc_0" , & self . ccuc_0 ()) . field ("dmas" , & self . dmas ()) . field ("mmc0" , & self . mmc0 ()) . field ("ti0s" , & self . ti0s ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ ccse: {=bool:?}, ccuc_0: {=bool:?}, dmas: {=bool:?}, mmc0: {=u8:?}, ti0s: {=bool:?} }}" , self . ccse () , self . ccuc_0 () , self . dmas () , self . mmc0 () , self . ti0s ()) } } # [doc = "Control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl2 (pub u32) ; impl Ctl2 { # [doc = "Channel 0 output match pulse select"]
# [inline (always)]
pub const fn ch0ompsel (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x03 ; val as u8 } # [doc = "Channel 0 output match pulse select"]
# [inline (always)]
pub fn set_ch0ompsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 8usize)) | (((val as u32) & 0x03) << 8usize) ; } # [doc = "Channel 1 output match pulse select"]
# [inline (always)]
pub const fn ch1ompsel (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x03 ; val as u8 } # [doc = "Channel 1 output match pulse select"]
# [inline (always)]
pub fn set_ch1ompsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize) ; } # [doc = "Channel 2 output match pulse select"]
# [inline (always)]
pub const fn ch2ompsel (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "Channel 2 output match pulse select"]
# [inline (always)]
pub fn set_ch2ompsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Channel 3 output match pulse select"]
# [inline (always)]
pub const fn ch3ompsel (& self) -> u8 { let val = (self . 0 >> 14usize) & 0x03 ; val as u8 } # [doc = "Channel 3 output match pulse select"]
# [inline (always)]
pub fn set_ch3ompsel (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 14usize)) | (((val as u32) & 0x03) << 14usize) ; } # [doc = "Quadrature decoder signal jump detection enable"]
# [inline (always)]
pub const fn decjden (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Quadrature decoder signal jump detection enable"]
# [inline (always)]
pub fn set_decjden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Quadrature decoder signal disconnection detection enable"]
# [inline (always)]
pub const fn decdisden (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Quadrature decoder signal disconnection detection enable"]
# [inline (always)]
pub fn set_decdisden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Channel 0 composite PWM mode enable"]
# [inline (always)]
pub const fn ch0cpwmen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Channel 0 composite PWM mode enable"]
# [inline (always)]
pub fn set_ch0cpwmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Channel 1 composite PWM mode enable"]
# [inline (always)]
pub const fn ch1cpwmen (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Channel 1 composite PWM mode enable"]
# [inline (always)]
pub fn set_ch1cpwmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Channel 2 composite PWM mode enable"]
# [inline (always)]
pub const fn ch2cpwmen (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Channel 2 composite PWM mode enable"]
# [inline (always)]
pub fn set_ch2cpwmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Channel 3 composite PWM mode enable"]
# [inline (always)]
pub const fn ch3cpwmen (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Channel 3 composite PWM mode enable"]
# [inline (always)]
pub fn set_ch3cpwmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ctl2 { # [inline (always)]
fn default () -> Ctl2 { Ctl2 (0) } } impl core :: fmt :: Debug for Ctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl2") . field ("ch0ompsel" , & self . ch0ompsel ()) . field ("ch1ompsel" , & self . ch1ompsel ()) . field ("ch2ompsel" , & self . ch2ompsel ()) . field ("ch3ompsel" , & self . ch3ompsel ()) . field ("decjden" , & self . decjden ()) . field ("decdisden" , & self . decdisden ()) . field ("ch0cpwmen" , & self . ch0cpwmen ()) . field ("ch1cpwmen" , & self . ch1cpwmen ()) . field ("ch2cpwmen" , & self . ch2cpwmen ()) . field ("ch3cpwmen" , & self . ch3cpwmen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl2 {{ ch0ompsel: {=u8:?}, ch1ompsel: {=u8:?}, ch2ompsel: {=u8:?}, ch3ompsel: {=u8:?}, decjden: {=bool:?}, decdisden: {=bool:?}, ch0cpwmen: {=bool:?}, ch1cpwmen: {=bool:?}, ch2cpwmen: {=bool:?}, ch3cpwmen: {=bool:?} }}" , self . ch0ompsel () , self . ch1ompsel () , self . ch2ompsel () , self . ch3ompsel () , self . decjden () , self . decdisden () , self . ch0cpwmen () , self . ch1cpwmen () , self . ch2cpwmen () , self . ch3cpwmen ()) } } # [doc = "DMA configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmacfg (pub u32) ; impl Dmacfg { # [doc = "DMA transfer access start address"]
# [inline (always)]
pub const fn dmata (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x3f ; val as u8 } # [doc = "DMA transfer access start address"]
# [inline (always)]
pub fn set_dmata (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 0usize)) | (((val as u32) & 0x3f) << 0usize) ; } # [doc = "DMA transfer count"]
# [inline (always)]
pub const fn dmatc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x3f ; val as u8 } # [doc = "DMA transfer count"]
# [inline (always)]
pub fn set_dmatc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x3f << 8usize)) | (((val as u32) & 0x3f) << 8usize) ; } } impl Default for Dmacfg { # [inline (always)]
fn default () -> Dmacfg { Dmacfg (0) } } impl core :: fmt :: Debug for Dmacfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmacfg") . field ("dmata" , & self . dmata ()) . field ("dmatc" , & self . dmatc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmacfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmacfg {{ dmata: {=u8:?}, dmatc: {=u8:?} }}" , self . dmata () , self . dmatc ()) } } # [doc = "DMA and interrupt enable register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmainten (pub u32) ; impl Dmainten { # [doc = "Update interrupt enable"]
# [inline (always)]
pub const fn upie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt enable"]
# [inline (always)]
pub fn set_upie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture/compare interrupt enable"]
# [inline (always)]
pub const fn ch0ie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare interrupt enable"]
# [inline (always)]
pub fn set_ch0ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 1 capture/compare interrupt enable"]
# [inline (always)]
pub const fn ch1ie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare interrupt enable"]
# [inline (always)]
pub fn set_ch1ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Channel 2 capture/compare interrupt enable"]
# [inline (always)]
pub const fn ch2ie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture/compare interrupt enable"]
# [inline (always)]
pub fn set_ch2ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 3 capture/compare interrupt enable"]
# [inline (always)]
pub const fn ch3ie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture/compare interrupt enable"]
# [inline (always)]
pub fn set_ch3ie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub const fn trgie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt enable"]
# [inline (always)]
pub fn set_trgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Update DMA request enable"]
# [inline (always)]
pub const fn upden (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Update DMA request enable"]
# [inline (always)]
pub fn set_upden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Channel 0 capture/compare DMA request enable"]
# [inline (always)]
pub const fn ch0den (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare DMA request enable"]
# [inline (always)]
pub fn set_ch0den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Channel 1 capture/compare DMA request enable"]
# [inline (always)]
pub const fn ch1den (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare DMA request enable"]
# [inline (always)]
pub fn set_ch1den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Channel 2 capture/compare DMA request enable"]
# [inline (always)]
pub const fn ch2den (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture/compare DMA request enable"]
# [inline (always)]
pub fn set_ch2den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Channel 3 capture/compare DMA request enable"]
# [inline (always)]
pub const fn ch3den (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture/compare DMA request enable"]
# [inline (always)]
pub fn set_ch3den (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Trigger DMA request enable"]
# [inline (always)]
pub const fn trgden (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Trigger DMA request enable"]
# [inline (always)]
pub fn set_trgden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Quadrature decoder signal jump (the two signals jump at the same time) interrupt enable"]
# [inline (always)]
pub const fn decjie (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Quadrature decoder signal jump (the two signals jump at the same time) interrupt enable"]
# [inline (always)]
pub fn set_decjie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Quadrature decoder signal disconnection interrupt enable"]
# [inline (always)]
pub const fn decdisie (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Quadrature decoder signal disconnection interrupt enable"]
# [inline (always)]
pub fn set_decdisie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Channel 0 additional compare interrupt enable"]
# [inline (always)]
pub const fn ch0comaddie (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Channel 0 additional compare interrupt enable"]
# [inline (always)]
pub fn set_ch0comaddie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Channel 1 additional compare interrupt enable"]
# [inline (always)]
pub const fn ch1comaddie (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Channel 1 additional compare interrupt enable"]
# [inline (always)]
pub fn set_ch1comaddie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Channel 2 additional compare interrupt enable"]
# [inline (always)]
pub const fn ch2comaddie (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Channel 2 additional compare interrupt enable"]
# [inline (always)]
pub fn set_ch2comaddie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Channel 3 additional compare interrupt enable"]
# [inline (always)]
pub const fn ch3comaddie (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Channel 3 additional compare interrupt enable"]
# [inline (always)]
pub fn set_ch3comaddie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Dmainten { # [inline (always)]
fn default () -> Dmainten { Dmainten (0) } } impl core :: fmt :: Debug for Dmainten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmainten") . field ("upie" , & self . upie ()) . field ("ch0ie" , & self . ch0ie ()) . field ("ch1ie" , & self . ch1ie ()) . field ("ch2ie" , & self . ch2ie ()) . field ("ch3ie" , & self . ch3ie ()) . field ("trgie" , & self . trgie ()) . field ("upden" , & self . upden ()) . field ("ch0den" , & self . ch0den ()) . field ("ch1den" , & self . ch1den ()) . field ("ch2den" , & self . ch2den ()) . field ("ch3den" , & self . ch3den ()) . field ("trgden" , & self . trgden ()) . field ("decjie" , & self . decjie ()) . field ("decdisie" , & self . decdisie ()) . field ("ch0comaddie" , & self . ch0comaddie ()) . field ("ch1comaddie" , & self . ch1comaddie ()) . field ("ch2comaddie" , & self . ch2comaddie ()) . field ("ch3comaddie" , & self . ch3comaddie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmainten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmainten {{ upie: {=bool:?}, ch0ie: {=bool:?}, ch1ie: {=bool:?}, ch2ie: {=bool:?}, ch3ie: {=bool:?}, trgie: {=bool:?}, upden: {=bool:?}, ch0den: {=bool:?}, ch1den: {=bool:?}, ch2den: {=bool:?}, ch3den: {=bool:?}, trgden: {=bool:?}, decjie: {=bool:?}, decdisie: {=bool:?}, ch0comaddie: {=bool:?}, ch1comaddie: {=bool:?}, ch2comaddie: {=bool:?}, ch3comaddie: {=bool:?} }}" , self . upie () , self . ch0ie () , self . ch1ie () , self . ch2ie () , self . ch3ie () , self . trgie () , self . upden () , self . ch0den () , self . ch1den () , self . ch2den () , self . ch3den () , self . trgden () , self . decjie () , self . decdisie () , self . ch0comaddie () , self . ch1comaddie () , self . ch2comaddie () , self . ch3comaddie ()) } } # [doc = "DMA transfer buffer register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Dmatb (pub u32) ; impl Dmatb { # [doc = "DMA transfer buffer"]
# [inline (always)]
pub const fn dmatb (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "DMA transfer buffer"]
# [inline (always)]
pub fn set_dmatb (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Dmatb { # [inline (always)]
fn default () -> Dmatb { Dmatb (0) } } impl core :: fmt :: Debug for Dmatb { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Dmatb") . field ("dmatb" , & self . dmatb ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Dmatb { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Dmatb {{ dmatb: {=u32:?} }}" , self . dmatb ()) } } # [doc = "Interrupt flag register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intf (pub u32) ; impl Intf { # [doc = "Update interrupt flag"]
# [inline (always)]
pub const fn upif (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update interrupt flag"]
# [inline (always)]
pub fn set_upif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture/compare interrupt flag"]
# [inline (always)]
pub const fn ch0if (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture/compare interrupt flag"]
# [inline (always)]
pub fn set_ch0if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 1 capture/compare interrupt flag"]
# [inline (always)]
pub const fn ch1if (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture/compare interrupt flag"]
# [inline (always)]
pub fn set_ch1if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Channel 2 capture/compare interrupt flag"]
# [inline (always)]
pub const fn ch2if (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture/compare interrupt flag"]
# [inline (always)]
pub fn set_ch2if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 3 capture/compare interrupt flag"]
# [inline (always)]
pub const fn ch3if (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture/compare interrupt flag"]
# [inline (always)]
pub fn set_ch3if (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub const fn trgif (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger interrupt flag"]
# [inline (always)]
pub fn set_trgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Channel 0 over capture flag"]
# [inline (always)]
pub const fn ch0of (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Channel 0 over capture flag"]
# [inline (always)]
pub fn set_ch0of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Channel 1 over capture flag"]
# [inline (always)]
pub const fn ch1of (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Channel 1 over capture flag"]
# [inline (always)]
pub fn set_ch1of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Channel 2 over capture flag"]
# [inline (always)]
pub const fn ch2of (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Channel 2 over capture flag"]
# [inline (always)]
pub fn set_ch2of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Channel 3 over capture flag"]
# [inline (always)]
pub const fn ch3of (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Channel 3 over capture flag"]
# [inline (always)]
pub fn set_ch3of (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Quadrature decoder signal jump (the two signals jump at the same time) interrupt flag"]
# [inline (always)]
pub const fn decjif (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Quadrature decoder signal jump (the two signals jump at the same time) interrupt flag"]
# [inline (always)]
pub fn set_decjif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Quadrature decoder signal disconnection interrupt flag"]
# [inline (always)]
pub const fn decdisif (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Quadrature decoder signal disconnection interrupt flag"]
# [inline (always)]
pub fn set_decdisif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Channel 0 additional compare interrupt flag"]
# [inline (always)]
pub const fn ch0comaddif (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Channel 0 additional compare interrupt flag"]
# [inline (always)]
pub fn set_ch0comaddif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Channel 1 additional compare interrupt flag"]
# [inline (always)]
pub const fn ch1comaddif (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Channel 1 additional compare interrupt flag"]
# [inline (always)]
pub fn set_ch1comaddif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Channel 2 additional compare interrupt flag"]
# [inline (always)]
pub const fn ch2comaddif (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Channel 2 additional compare interrupt flag"]
# [inline (always)]
pub fn set_ch2comaddif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Channel 3 additional compare interrupt flag"]
# [inline (always)]
pub const fn ch3comaddif (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Channel 3 additional compare interrupt flag"]
# [inline (always)]
pub fn set_ch3comaddif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Intf { # [inline (always)]
fn default () -> Intf { Intf (0) } } impl core :: fmt :: Debug for Intf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intf") . field ("upif" , & self . upif ()) . field ("ch0if" , & self . ch0if ()) . field ("ch1if" , & self . ch1if ()) . field ("ch2if" , & self . ch2if ()) . field ("ch3if" , & self . ch3if ()) . field ("trgif" , & self . trgif ()) . field ("ch0of" , & self . ch0of ()) . field ("ch1of" , & self . ch1of ()) . field ("ch2of" , & self . ch2of ()) . field ("ch3of" , & self . ch3of ()) . field ("decjif" , & self . decjif ()) . field ("decdisif" , & self . decdisif ()) . field ("ch0comaddif" , & self . ch0comaddif ()) . field ("ch1comaddif" , & self . ch1comaddif ()) . field ("ch2comaddif" , & self . ch2comaddif ()) . field ("ch3comaddif" , & self . ch3comaddif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intf {{ upif: {=bool:?}, ch0if: {=bool:?}, ch1if: {=bool:?}, ch2if: {=bool:?}, ch3if: {=bool:?}, trgif: {=bool:?}, ch0of: {=bool:?}, ch1of: {=bool:?}, ch2of: {=bool:?}, ch3of: {=bool:?}, decjif: {=bool:?}, decdisif: {=bool:?}, ch0comaddif: {=bool:?}, ch1comaddif: {=bool:?}, ch2comaddif: {=bool:?}, ch3comaddif: {=bool:?} }}" , self . upif () , self . ch0if () , self . ch1if () , self . ch2if () , self . ch3if () , self . trgif () , self . ch0of () , self . ch1of () , self . ch2of () , self . ch3of () , self . decjif () , self . decdisif () , self . ch0comaddif () , self . ch1comaddif () , self . ch2comaddif () , self . ch3comaddif ()) } } # [doc = "prescaler"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Psc (pub u32) ; impl Psc { # [doc = "Prescaler value of the counter clock"]
# [inline (always)]
pub const fn psc (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Prescaler value of the counter clock"]
# [inline (always)]
pub fn set_psc (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Psc { # [inline (always)]
fn default () -> Psc { Psc (0) } } impl core :: fmt :: Debug for Psc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Psc") . field ("psc" , & self . psc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Psc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Psc {{ psc: {=u16:?} }}" , self . psc ()) } } # [doc = "Slave mode configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Smcfg (pub u32) ; impl Smcfg { # [doc = "Master-slave mode"]
# [inline (always)]
pub const fn msm (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Master-slave mode"]
# [inline (always)]
pub fn set_msm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "External trigger filter control"]
# [inline (always)]
pub const fn etfc (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "External trigger filter control"]
# [inline (always)]
pub fn set_etfc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "External trigger prescaler"]
# [inline (always)]
pub const fn etpsc (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "External trigger prescaler"]
# [inline (always)]
pub fn set_etpsc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "Part of SMC is used to enable external clock mode 1"]
# [inline (always)]
pub const fn smc1 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Part of SMC is used to enable external clock mode 1"]
# [inline (always)]
pub fn set_smc1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "External trigger polarity"]
# [inline (always)]
pub const fn etp (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "External trigger polarity"]
# [inline (always)]
pub fn set_etp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } } impl Default for Smcfg { # [inline (always)]
fn default () -> Smcfg { Smcfg (0) } } impl core :: fmt :: Debug for Smcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Smcfg") . field ("msm" , & self . msm ()) . field ("etfc" , & self . etfc ()) . field ("etpsc" , & self . etpsc ()) . field ("smc1" , & self . smc1 ()) . field ("etp" , & self . etp ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Smcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Smcfg {{ msm: {=bool:?}, etfc: {=u8:?}, etpsc: {=u8:?}, smc1: {=bool:?}, etp: {=bool:?} }}" , self . msm () , self . etfc () , self . etpsc () , self . smc1 () , self . etp ()) } } # [doc = "Software event generation register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Swevg (pub u32) ; impl Swevg { # [doc = "Update event generation"]
# [inline (always)]
pub const fn upg (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Update event generation"]
# [inline (always)]
pub fn set_upg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Channel 0 capture or compare event generation"]
# [inline (always)]
pub const fn ch0g (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Channel 0 capture or compare event generation"]
# [inline (always)]
pub fn set_ch0g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Channel 1 capture or compare event generation"]
# [inline (always)]
pub const fn ch1g (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Channel 1 capture or compare event generation"]
# [inline (always)]
pub fn set_ch1g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Channel 2 capture or compare event generation"]
# [inline (always)]
pub const fn ch2g (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Channel 2 capture or compare event generation"]
# [inline (always)]
pub fn set_ch2g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Channel 3 capture or compare event generation"]
# [inline (always)]
pub const fn ch3g (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Channel 3 capture or compare event generation"]
# [inline (always)]
pub fn set_ch3g (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Trigger event generation"]
# [inline (always)]
pub const fn trgg (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Trigger event generation"]
# [inline (always)]
pub fn set_trgg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Channel 0 additional compare event generation"]
# [inline (always)]
pub const fn ch0comaddg (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Channel 0 additional compare event generation"]
# [inline (always)]
pub fn set_ch0comaddg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Channel 1 additional compare event generation"]
# [inline (always)]
pub const fn ch1comaddg (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Channel 1 additional compare event generation"]
# [inline (always)]
pub fn set_ch1comaddg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Channel 2 additional compare event generation"]
# [inline (always)]
pub const fn ch2comaddg (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Channel 2 additional compare event generation"]
# [inline (always)]
pub fn set_ch2comaddg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Channel 3 additional compare event generation"]
# [inline (always)]
pub const fn ch3comaddg (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Channel 3 additional compare event generation"]
# [inline (always)]
pub fn set_ch3comaddg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Swevg { # [inline (always)]
fn default () -> Swevg { Swevg (0) } } impl core :: fmt :: Debug for Swevg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Swevg") . field ("upg" , & self . upg ()) . field ("ch0g" , & self . ch0g ()) . field ("ch1g" , & self . ch1g ()) . field ("ch2g" , & self . ch2g ()) . field ("ch3g" , & self . ch3g ()) . field ("trgg" , & self . trgg ()) . field ("ch0comaddg" , & self . ch0comaddg ()) . field ("ch1comaddg" , & self . ch1comaddg ()) . field ("ch2comaddg" , & self . ch2comaddg ()) . field ("ch3comaddg" , & self . ch3comaddg ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Swevg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Swevg {{ upg: {=bool:?}, ch0g: {=bool:?}, ch1g: {=bool:?}, ch2g: {=bool:?}, ch3g: {=bool:?}, trgg: {=bool:?}, ch0comaddg: {=bool:?}, ch1comaddg: {=bool:?}, ch2comaddg: {=bool:?}, ch3comaddg: {=bool:?} }}" , self . upg () , self . ch0g () , self . ch1g () , self . ch2g () , self . ch3g () , self . trgg () , self . ch0comaddg () , self . ch1comaddg () , self . ch2comaddg () , self . ch3comaddg ()) } } # [doc = "Watchdog counter register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Wdgper (pub u32) ; impl Wdgper { # [doc = "Watchdog timeout count"]
# [inline (always)]
pub const fn wdgper (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Watchdog timeout count"]
# [inline (always)]
pub fn set_wdgper (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Wdgper { # [inline (always)]
fn default () -> Wdgper { Wdgper (0) } } impl core :: fmt :: Debug for Wdgper { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Wdgper") . field ("wdgper" , & self . wdgper ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Wdgper { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Wdgper {{ wdgper: {=u32:?} }}" , self . wdgper ()) } } }
