#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Trigonometric Math Unit"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tmu { ptr : * mut u8 } unsafe impl Send for Tmu { } unsafe impl Sync for Tmu { } impl Tmu { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control and status register"]
# [inline (always)]
pub const fn cs (self) -> crate :: common :: Reg < regs :: Cs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Input data register"]
# [inline (always)]
pub const fn idata (self) -> crate :: common :: Reg < regs :: Idata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Output Data register"]
# [inline (always)]
pub const fn odata (self) -> crate :: common :: Reg < regs :: Odata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } } pub mod regs { # [doc = "Control and status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cs (pub u32) ; impl Cs { # [doc = "Mode of CORDIC operation"]
# [inline (always)]
pub const fn mode (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Mode of CORDIC operation"]
# [inline (always)]
pub fn set_mode (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Number of iterations"]
# [inline (always)]
pub const fn itrtnum (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x0f ; val as u8 } # [doc = "Number of iterations"]
# [inline (always)]
pub fn set_itrtnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 4usize)) | (((val as u32) & 0x0f) << 4usize) ; } # [doc = "Scaling factor"]
# [inline (always)]
pub const fn factor (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x07 ; val as u8 } # [doc = "Scaling factor"]
# [inline (always)]
pub fn set_factor (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 8usize)) | (((val as u32) & 0x07) << 8usize) ; } # [doc = "Enable interrupt request to read ODATA"]
# [inline (always)]
pub const fn rie (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Enable interrupt request to read ODATA"]
# [inline (always)]
pub fn set_rie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Enable DMA request to read ODATA"]
# [inline (always)]
pub const fn rden (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Enable DMA request to read ODATA"]
# [inline (always)]
pub fn set_rden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Enable DMA request to write IDATA"]
# [inline (always)]
pub const fn wden (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Enable DMA request to write IDATA"]
# [inline (always)]
pub fn set_wden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "The number of times that the ODATA needs to be read"]
# [inline (always)]
pub const fn onum (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "The number of times that the ODATA needs to be read"]
# [inline (always)]
pub fn set_onum (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "The number of times that the IDATA needs to be written"]
# [inline (always)]
pub const fn inum (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "The number of times that the IDATA needs to be written"]
# [inline (always)]
pub fn set_inum (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "Width of output data"]
# [inline (always)]
pub const fn owidth (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "Width of output data"]
# [inline (always)]
pub fn set_owidth (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Width of input data"]
# [inline (always)]
pub const fn iwidth (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Width of input data"]
# [inline (always)]
pub fn set_iwidth (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "End of TMU operation flag"]
# [inline (always)]
pub const fn endf (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "End of TMU operation flag"]
# [inline (always)]
pub fn set_endf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Cs { # [inline (always)]
fn default () -> Cs { Cs (0) } } impl core :: fmt :: Debug for Cs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cs") . field ("mode" , & self . mode ()) . field ("itrtnum" , & self . itrtnum ()) . field ("factor" , & self . factor ()) . field ("rie" , & self . rie ()) . field ("rden" , & self . rden ()) . field ("wden" , & self . wden ()) . field ("onum" , & self . onum ()) . field ("inum" , & self . inum ()) . field ("owidth" , & self . owidth ()) . field ("iwidth" , & self . iwidth ()) . field ("endf" , & self . endf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cs {{ mode: {=u8:?}, itrtnum: {=u8:?}, factor: {=u8:?}, rie: {=bool:?}, rden: {=bool:?}, wden: {=bool:?}, onum: {=bool:?}, inum: {=bool:?}, owidth: {=bool:?}, iwidth: {=bool:?}, endf: {=bool:?} }}" , self . mode () , self . itrtnum () , self . factor () , self . rie () , self . rden () , self . wden () , self . onum () , self . inum () , self . owidth () , self . iwidth () , self . endf ()) } } # [doc = "Input data register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Idata (pub u32) ; impl Idata { # [doc = "The input data"]
# [inline (always)]
pub const fn idata (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "The input data"]
# [inline (always)]
pub fn set_idata (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Idata { # [inline (always)]
fn default () -> Idata { Idata (0) } } impl core :: fmt :: Debug for Idata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Idata") . field ("idata" , & self . idata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Idata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Idata {{ idata: {=u32:?} }}" , self . idata ()) } } # [doc = "Output Data register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Odata (pub u32) ; impl Odata { # [doc = "The output data"]
# [inline (always)]
pub const fn odata (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "The output data"]
# [inline (always)]
pub fn set_odata (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Odata { # [inline (always)]
fn default () -> Odata { Odata (0) } } impl core :: fmt :: Debug for Odata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Odata") . field ("odata" , & self . odata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Odata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Odata {{ odata: {=u32:?} }}" , self . odata ()) } } }