#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "USB high speed global registers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Usbhs1Global { ptr : * mut u8 } unsafe impl Send for Usbhs1Global { } unsafe impl Sync for Usbhs1Global { } impl Usbhs1Global { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Global OTG control and status register (USBFS_GOTGCS)"]
# [inline (always)]
pub const fn gotgcs (self) -> crate :: common :: Reg < regs :: Gotgcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Global OTG interrupt flag register (USBHS_GOTGINTF)"]
# [inline (always)]
pub const fn gotgintf (self) -> crate :: common :: Reg < regs :: Gotgintf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Global AHB control and status register (USBHS_GAHBCS)"]
# [inline (always)]
pub const fn gahbcs (self) -> crate :: common :: Reg < regs :: Gahbcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Global USB control and status register (USBHS_GUSBCSR)"]
# [inline (always)]
pub const fn gusbcs (self) -> crate :: common :: Reg < regs :: Gusbcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Global reset control register (USBHS_GRSTCTL)"]
# [inline (always)]
pub const fn grstctl (self) -> crate :: common :: Reg < regs :: Grstctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Global interrupt flag register (USBFS_GINTF)"]
# [inline (always)]
pub const fn gintf (self) -> crate :: common :: Reg < regs :: Gintf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Global interrupt enable register (USBHS_GINTEN)"]
# [inline (always)]
pub const fn ginten (self) -> crate :: common :: Reg < regs :: Ginten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Global Receive status read(Device mode)"]
# [inline (always)]
pub const fn grstatr_device (self) -> crate :: common :: Reg < regs :: GrstatrDevice , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Global Receive status read(Host mode)"]
# [inline (always)]
pub const fn grstatr_host (self) -> crate :: common :: Reg < regs :: GrstatrHost , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Global Receive status pop(Device mode)"]
# [inline (always)]
pub const fn grstatp_device (self) -> crate :: common :: Reg < regs :: GrstatpDevice , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Global Receive status pop(Host mode)"]
# [inline (always)]
pub const fn grstatp_host (self) -> crate :: common :: Reg < regs :: GrstatpHost , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Global Receive FIFO size register (USBHS_GRFLEN)"]
# [inline (always)]
pub const fn grflen (self) -> crate :: common :: Reg < regs :: Grflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Device IN endpoint 0 transmit FIFO length (Device mode)"]
# [inline (always)]
pub const fn diep0tflen (self) -> crate :: common :: Reg < regs :: Diep0tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Host non-periodic transmit FIFO length register (Host mode)"]
# [inline (always)]
pub const fn hnptflen (self) -> crate :: common :: Reg < regs :: Hnptflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Host non-periodic transmit FIFO/queue status register (HNPTFQSTAT)"]
# [inline (always)]
pub const fn hnptfqstat (self) -> crate :: common :: Reg < regs :: Hnptfqstat , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Global core configuration register (USBFS_GCCFG)"]
# [inline (always)]
pub const fn gccfg (self) -> crate :: common :: Reg < regs :: Gccfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "core ID register"]
# [inline (always)]
pub const fn cid (self) -> crate :: common :: Reg < regs :: Cid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Global core LPM configuration register"]
# [inline (always)]
pub const fn glpmcfg (self) -> crate :: common :: Reg < regs :: Glpmcfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x54usize) as _) } } # [doc = "Power down register (USBHS_PWRD)"]
# [inline (always)]
pub const fn pwrd (self) -> crate :: common :: Reg < regs :: Pwrd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x58usize) as _) } } # [doc = "ADP control andstatus register"]
# [inline (always)]
pub const fn adpctl (self) -> crate :: common :: Reg < regs :: Adpctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x60usize) as _) } } # [doc = "Host periodic transmit FIFO length register (HPTFLEN)"]
# [inline (always)]
pub const fn hptflen (self) -> crate :: common :: Reg < regs :: Hptflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0100usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [inline (always)]
pub const fn diep1tflen (self) -> crate :: common :: Reg < regs :: Diep1tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0104usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [inline (always)]
pub const fn diep2tflen (self) -> crate :: common :: Reg < regs :: Diep2tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0108usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [inline (always)]
pub const fn diep3tflen (self) -> crate :: common :: Reg < regs :: Diep3tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x010cusize) as _) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [inline (always)]
pub const fn diep4tflen (self) -> crate :: common :: Reg < regs :: Diep4tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0110usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register (FS_DIEP5TXFLEN)"]
# [inline (always)]
pub const fn diep5tflen (self) -> crate :: common :: Reg < regs :: Diep5tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0114usize) as _) } } } pub mod regs { # [doc = "ADP control andstatus register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Adpctl (pub u32) ; impl Adpctl { # [doc = "Time of probe discharge"]
# [inline (always)]
pub const fn dschgpr (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x03 ; val as u8 } # [doc = "Time of probe discharge"]
# [inline (always)]
pub fn set_dschgpr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 0usize)) | (((val as u32) & 0x03) << 0usize) ; } # [doc = "The resolution of CHGT value"]
# [inline (always)]
pub const fn resopr (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x03 ; val as u8 } # [doc = "The resolution of CHGT value"]
# [inline (always)]
pub fn set_resopr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 2usize)) | (((val as u32) & 0x03) << 2usize) ; } # [doc = "Period of probe"]
# [inline (always)]
pub const fn perpr (& self) -> u8 { let val = (self . 0 >> 4usize) & 0x03 ; val as u8 } # [doc = "Period of probe"]
# [inline (always)]
pub fn set_perpr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 4usize)) | (((val as u32) & 0x03) << 4usize) ; } # [doc = "The latest time that VBUS ramps from VADPSINK to VADPPRB"]
# [inline (always)]
pub const fn chgt (& self) -> u16 { let val = (self . 0 >> 6usize) & 0x07ff ; val as u16 } # [doc = "The latest time that VBUS ramps from VADPSINK to VADPPRB"]
# [inline (always)]
pub fn set_chgt (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 6usize)) | (((val as u32) & 0x07ff) << 6usize) ; } # [doc = "ADP probe enable"]
# [inline (always)]
pub const fn pren (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "ADP probe enable"]
# [inline (always)]
pub fn set_pren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "ADP sense enable"]
# [inline (always)]
pub const fn snen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "ADP sense enable"]
# [inline (always)]
pub fn set_snen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "ADP reset"]
# [inline (always)]
pub const fn adprst (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "ADP reset"]
# [inline (always)]
pub fn set_adprst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "ADP enable"]
# [inline (always)]
pub const fn adpen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "ADP enable"]
# [inline (always)]
pub fn set_adpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "ADP probe interrupt flag"]
# [inline (always)]
pub const fn adpprf (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "ADP probe interrupt flag"]
# [inline (always)]
pub fn set_adpprf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "ADP sense interrupt flag"]
# [inline (always)]
pub const fn adpsnf (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "ADP sense interrupt flag"]
# [inline (always)]
pub fn set_adpsnf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "ADP timeout interrupt flag"]
# [inline (always)]
pub const fn adptf (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "ADP timeout interrupt flag"]
# [inline (always)]
pub fn set_adptf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "The mask of ADP probe interrupt flag"]
# [inline (always)]
pub const fn adpprfm (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "The mask of ADP probe interrupt flag"]
# [inline (always)]
pub fn set_adpprfm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "The mask of ADP sense interrupt flag"]
# [inline (always)]
pub const fn adpsnfm (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "The mask of ADP sense interrupt flag"]
# [inline (always)]
pub fn set_adpsnfm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "The mask of ADP timeout interrupt flag"]
# [inline (always)]
pub const fn adptfm (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "The mask of ADP timeout interrupt flag"]
# [inline (always)]
pub fn set_adptfm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "Read and write request"]
# [inline (always)]
pub const fn rwr (& self) -> u8 { let val = (self . 0 >> 27usize) & 0x03 ; val as u8 } # [doc = "Read and write request"]
# [inline (always)]
pub fn set_rwr (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 27usize)) | (((val as u32) & 0x03) << 27usize) ; } } impl Default for Adpctl { # [inline (always)]
fn default () -> Adpctl { Adpctl (0) } } impl core :: fmt :: Debug for Adpctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Adpctl") . field ("dschgpr" , & self . dschgpr ()) . field ("resopr" , & self . resopr ()) . field ("perpr" , & self . perpr ()) . field ("chgt" , & self . chgt ()) . field ("pren" , & self . pren ()) . field ("snen" , & self . snen ()) . field ("adprst" , & self . adprst ()) . field ("adpen" , & self . adpen ()) . field ("adpprf" , & self . adpprf ()) . field ("adpsnf" , & self . adpsnf ()) . field ("adptf" , & self . adptf ()) . field ("adpprfm" , & self . adpprfm ()) . field ("adpsnfm" , & self . adpsnfm ()) . field ("adptfm" , & self . adptfm ()) . field ("rwr" , & self . rwr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Adpctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Adpctl {{ dschgpr: {=u8:?}, resopr: {=u8:?}, perpr: {=u8:?}, chgt: {=u16:?}, pren: {=bool:?}, snen: {=bool:?}, adprst: {=bool:?}, adpen: {=bool:?}, adpprf: {=bool:?}, adpsnf: {=bool:?}, adptf: {=bool:?}, adpprfm: {=bool:?}, adpsnfm: {=bool:?}, adptfm: {=bool:?}, rwr: {=u8:?} }}" , self . dschgpr () , self . resopr () , self . perpr () , self . chgt () , self . pren () , self . snen () , self . adprst () , self . adpen () , self . adpprf () , self . adpsnf () , self . adptf () , self . adpprfm () , self . adpsnfm () , self . adptfm () , self . rwr ()) } } # [doc = "core ID register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cid (pub u32) ; impl Cid { # [doc = "Core ID"]
# [inline (always)]
pub const fn cid (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Core ID"]
# [inline (always)]
pub fn set_cid (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Cid { # [inline (always)]
fn default () -> Cid { Cid (0) } } impl core :: fmt :: Debug for Cid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cid") . field ("cid" , & self . cid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cid {{ cid: {=u32:?} }}" , self . cid ()) } } # [doc = "Device IN endpoint 0 transmit FIFO length (Device mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep0tflen (pub u32) ; impl Diep0tflen { # [doc = "in endpoint 0 Tx RAM start address"]
# [inline (always)]
pub const fn iep0txrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "in endpoint 0 Tx RAM start address"]
# [inline (always)]
pub fn set_iep0txrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "in endpoint 0 Tx FIFO depth"]
# [inline (always)]
pub const fn iep0txfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "in endpoint 0 Tx FIFO depth"]
# [inline (always)]
pub fn set_iep0txfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep0tflen { # [inline (always)]
fn default () -> Diep0tflen { Diep0tflen (0) } } impl core :: fmt :: Debug for Diep0tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep0tflen") . field ("iep0txrsar" , & self . iep0txrsar ()) . field ("iep0txfd" , & self . iep0txfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep0tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep0tflen {{ iep0txrsar: {=u16:?}, iep0txfd: {=u16:?} }}" , self . iep0txrsar () , self . iep0txfd ()) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep1tflen (pub u32) ; impl Diep1tflen { # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep1tflen { # [inline (always)]
fn default () -> Diep1tflen { Diep1tflen (0) } } impl core :: fmt :: Debug for Diep1tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep1tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep1tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep1tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep2tflen (pub u32) ; impl Diep2tflen { # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep2tflen { # [inline (always)]
fn default () -> Diep2tflen { Diep2tflen (0) } } impl core :: fmt :: Debug for Diep2tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep2tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep2tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep2tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep3tflen (pub u32) ; impl Diep3tflen { # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep3tflen { # [inline (always)]
fn default () -> Diep3tflen { Diep3tflen (0) } } impl core :: fmt :: Debug for Diep3tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep3tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep3tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep3tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "device IN endpoint transmit FIFO size register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep4tflen (pub u32) ; impl Diep4tflen { # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep4tflen { # [inline (always)]
fn default () -> Diep4tflen { Diep4tflen (0) } } impl core :: fmt :: Debug for Diep4tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep4tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep4tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep4tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "device IN endpoint transmit FIFO size register (FS_DIEP5TXFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep5tflen (pub u32) ; impl Diep5tflen { # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep5tflen { # [inline (always)]
fn default () -> Diep5tflen { Diep5tflen (0) } } impl core :: fmt :: Debug for Diep5tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep5tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep5tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep5tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "Global AHB control and status register (USBHS_GAHBCS)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gahbcs (pub u32) ; impl Gahbcs { # [doc = "Global interrupt enable"]
# [inline (always)]
pub const fn ginten (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Global interrupt enable"]
# [inline (always)]
pub fn set_ginten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "The AHB burst type used by DMA"]
# [inline (always)]
pub const fn burst (& self) -> u8 { let val = (self . 0 >> 1usize) & 0x0f ; val as u8 } # [doc = "The AHB burst type used by DMA"]
# [inline (always)]
pub fn set_burst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 1usize)) | (((val as u32) & 0x0f) << 1usize) ; } # [doc = "DMA function Enable"]
# [inline (always)]
pub const fn dmaen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "DMA function Enable"]
# [inline (always)]
pub fn set_dmaen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Tx FIFO threshold"]
# [inline (always)]
pub const fn txfth (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Tx FIFO threshold"]
# [inline (always)]
pub fn set_txfth (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Periodic Tx FIFO threshold"]
# [inline (always)]
pub const fn ptxfth (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Periodic Tx FIFO threshold"]
# [inline (always)]
pub fn set_ptxfth (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for Gahbcs { # [inline (always)]
fn default () -> Gahbcs { Gahbcs (0) } } impl core :: fmt :: Debug for Gahbcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gahbcs") . field ("ginten" , & self . ginten ()) . field ("burst" , & self . burst ()) . field ("dmaen" , & self . dmaen ()) . field ("txfth" , & self . txfth ()) . field ("ptxfth" , & self . ptxfth ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gahbcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gahbcs {{ ginten: {=bool:?}, burst: {=u8:?}, dmaen: {=bool:?}, txfth: {=bool:?}, ptxfth: {=bool:?} }}" , self . ginten () , self . burst () , self . dmaen () , self . txfth () , self . ptxfth ()) } } # [doc = "Global core configuration register (USBFS_GCCFG)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gccfg (pub u32) ; impl Gccfg { # [doc = "Data connect detection status"]
# [inline (always)]
pub const fn dcdf (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Data connect detection status"]
# [inline (always)]
pub fn set_dcdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Primary detection status"]
# [inline (always)]
pub const fn pdf (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Primary detection status"]
# [inline (always)]
pub fn set_pdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Secondary detection status"]
# [inline (always)]
pub const fn sdf (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Secondary detection status"]
# [inline (always)]
pub fn set_sdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "PS2 detection status"]
# [inline (always)]
pub const fn ps2f (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "PS2 detection status"]
# [inline (always)]
pub fn set_ps2f (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Battery charging detection enable"]
# [inline (always)]
pub const fn bcden (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Battery charging detection enable"]
# [inline (always)]
pub fn set_bcden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Data connect detection mode enable"]
# [inline (always)]
pub const fn dcdmen (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Data connect detection mode enable"]
# [inline (always)]
pub fn set_dcdmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Primary detection mode enable"]
# [inline (always)]
pub const fn pdmen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Primary detection mode enable"]
# [inline (always)]
pub fn set_pdmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Secondary detection mode enable"]
# [inline (always)]
pub const fn sdmen (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Secondary detection mode enable"]
# [inline (always)]
pub fn set_sdmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Power on"]
# [inline (always)]
pub const fn pwron (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Power on"]
# [inline (always)]
pub fn set_pwron (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "SOF output enable"]
# [inline (always)]
pub const fn sofoen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "SOF output enable"]
# [inline (always)]
pub fn set_sofoen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "Enable of VBUS sensing comparator to detect VBUS valid"]
# [inline (always)]
pub const fn vden (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "Enable of VBUS sensing comparator to detect VBUS valid"]
# [inline (always)]
pub fn set_vden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } } impl Default for Gccfg { # [inline (always)]
fn default () -> Gccfg { Gccfg (0) } } impl core :: fmt :: Debug for Gccfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gccfg") . field ("dcdf" , & self . dcdf ()) . field ("pdf" , & self . pdf ()) . field ("sdf" , & self . sdf ()) . field ("ps2f" , & self . ps2f ()) . field ("bcden" , & self . bcden ()) . field ("dcdmen" , & self . dcdmen ()) . field ("pdmen" , & self . pdmen ()) . field ("sdmen" , & self . sdmen ()) . field ("pwron" , & self . pwron ()) . field ("sofoen" , & self . sofoen ()) . field ("vden" , & self . vden ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gccfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gccfg {{ dcdf: {=bool:?}, pdf: {=bool:?}, sdf: {=bool:?}, ps2f: {=bool:?}, bcden: {=bool:?}, dcdmen: {=bool:?}, pdmen: {=bool:?}, sdmen: {=bool:?}, pwron: {=bool:?}, sofoen: {=bool:?}, vden: {=bool:?} }}" , self . dcdf () , self . pdf () , self . sdf () , self . ps2f () , self . bcden () , self . dcdmen () , self . pdmen () , self . sdmen () , self . pwron () , self . sofoen () , self . vden ()) } } # [doc = "Global interrupt enable register (USBHS_GINTEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ginten (pub u32) ; impl Ginten { # [doc = "Mode fault interrupt enable"]
# [inline (always)]
pub const fn mfie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mode fault interrupt enable"]
# [inline (always)]
pub fn set_mfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "OTG interrupt enable"]
# [inline (always)]
pub const fn otgie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "OTG interrupt enable"]
# [inline (always)]
pub fn set_otgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Start of frame interrupt enable"]
# [inline (always)]
pub const fn sofie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Start of frame interrupt enable"]
# [inline (always)]
pub fn set_sofie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Receive FIFO non-empty interrupt enable"]
# [inline (always)]
pub const fn rxfneie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO non-empty interrupt enable"]
# [inline (always)]
pub fn set_rxfneie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Non-periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub const fn nptxfeie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Non-periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub fn set_nptxfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Global non-periodic IN NAK effective interrupt enable"]
# [inline (always)]
pub const fn gnpinakie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Global non-periodic IN NAK effective interrupt enable"]
# [inline (always)]
pub fn set_gnpinakie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Global OUT NAK effective interrupt enable"]
# [inline (always)]
pub const fn gonakie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Global OUT NAK effective interrupt enable"]
# [inline (always)]
pub fn set_gonakie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Early suspend interrupt enable"]
# [inline (always)]
pub const fn espie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Early suspend interrupt enable"]
# [inline (always)]
pub fn set_espie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "USB suspend interrupt enable"]
# [inline (always)]
pub const fn spie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "USB suspend interrupt enable"]
# [inline (always)]
pub fn set_spie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "USB reset interrupt enable"]
# [inline (always)]
pub const fn rstie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "USB reset interrupt enable"]
# [inline (always)]
pub fn set_rstie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Enumeration finish interrupt enable"]
# [inline (always)]
pub const fn enumfie (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Enumeration finish interrupt enable"]
# [inline (always)]
pub fn set_enumfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Isochronous OUT packet dropped interrupt enable"]
# [inline (always)]
pub const fn isoopdie (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Isochronous OUT packet dropped interrupt enable"]
# [inline (always)]
pub fn set_isoopdie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "End of periodic frame interrupt enable"]
# [inline (always)]
pub const fn eopfie (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "End of periodic frame interrupt enable"]
# [inline (always)]
pub fn set_eopfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "IN endpoints interrupt enable"]
# [inline (always)]
pub const fn iepie (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "IN endpoints interrupt enable"]
# [inline (always)]
pub fn set_iepie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "OUT endpoints interrupt enable"]
# [inline (always)]
pub const fn oepie (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "OUT endpoints interrupt enable"]
# [inline (always)]
pub fn set_oepie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "isochronous IN transfer not complete interrupt enable"]
# [inline (always)]
pub const fn isoincie (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "isochronous IN transfer not complete interrupt enable"]
# [inline (always)]
pub fn set_isoincie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "periodic transfer not compelete Interrupt enable(Host mode)/isochronous OUT transfer not complete interrupt enable(Device mode)"]
# [inline (always)]
pub const fn pxncie_isooncie (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "periodic transfer not compelete Interrupt enable(Host mode)/isochronous OUT transfer not complete interrupt enable(Device mode)"]
# [inline (always)]
pub fn set_pxncie_isooncie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Host port interrupt enable"]
# [inline (always)]
pub const fn hpie (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Host port interrupt enable"]
# [inline (always)]
pub fn set_hpie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Host channels interrupt enable"]
# [inline (always)]
pub const fn hcie (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Host channels interrupt enable"]
# [inline (always)]
pub fn set_hcie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub const fn ptxfeie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub fn set_ptxfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "LPM interrupt enable"]
# [inline (always)]
pub const fn lpmie (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "LPM interrupt enable"]
# [inline (always)]
pub fn set_lpmie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "ID pin status change interrupt enable"]
# [inline (always)]
pub const fn idpscie (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "ID pin status change interrupt enable"]
# [inline (always)]
pub fn set_idpscie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Disconnect interrupt enable"]
# [inline (always)]
pub const fn discie (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Disconnect interrupt enable"]
# [inline (always)]
pub fn set_discie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Session interrupt enable"]
# [inline (always)]
pub const fn sesie (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Session interrupt enable"]
# [inline (always)]
pub fn set_sesie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Wakeup interrupt enable"]
# [inline (always)]
pub const fn wkupie (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Wakeup interrupt enable"]
# [inline (always)]
pub fn set_wkupie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ginten { # [inline (always)]
fn default () -> Ginten { Ginten (0) } } impl core :: fmt :: Debug for Ginten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ginten") . field ("mfie" , & self . mfie ()) . field ("otgie" , & self . otgie ()) . field ("sofie" , & self . sofie ()) . field ("rxfneie" , & self . rxfneie ()) . field ("nptxfeie" , & self . nptxfeie ()) . field ("gnpinakie" , & self . gnpinakie ()) . field ("gonakie" , & self . gonakie ()) . field ("espie" , & self . espie ()) . field ("spie" , & self . spie ()) . field ("rstie" , & self . rstie ()) . field ("enumfie" , & self . enumfie ()) . field ("isoopdie" , & self . isoopdie ()) . field ("eopfie" , & self . eopfie ()) . field ("iepie" , & self . iepie ()) . field ("oepie" , & self . oepie ()) . field ("isoincie" , & self . isoincie ()) . field ("pxncie_isooncie" , & self . pxncie_isooncie ()) . field ("hpie" , & self . hpie ()) . field ("hcie" , & self . hcie ()) . field ("ptxfeie" , & self . ptxfeie ()) . field ("lpmie" , & self . lpmie ()) . field ("idpscie" , & self . idpscie ()) . field ("discie" , & self . discie ()) . field ("sesie" , & self . sesie ()) . field ("wkupie" , & self . wkupie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ginten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ginten {{ mfie: {=bool:?}, otgie: {=bool:?}, sofie: {=bool:?}, rxfneie: {=bool:?}, nptxfeie: {=bool:?}, gnpinakie: {=bool:?}, gonakie: {=bool:?}, espie: {=bool:?}, spie: {=bool:?}, rstie: {=bool:?}, enumfie: {=bool:?}, isoopdie: {=bool:?}, eopfie: {=bool:?}, iepie: {=bool:?}, oepie: {=bool:?}, isoincie: {=bool:?}, pxncie_isooncie: {=bool:?}, hpie: {=bool:?}, hcie: {=bool:?}, ptxfeie: {=bool:?}, lpmie: {=bool:?}, idpscie: {=bool:?}, discie: {=bool:?}, sesie: {=bool:?}, wkupie: {=bool:?} }}" , self . mfie () , self . otgie () , self . sofie () , self . rxfneie () , self . nptxfeie () , self . gnpinakie () , self . gonakie () , self . espie () , self . spie () , self . rstie () , self . enumfie () , self . isoopdie () , self . eopfie () , self . iepie () , self . oepie () , self . isoincie () , self . pxncie_isooncie () , self . hpie () , self . hcie () , self . ptxfeie () , self . lpmie () , self . idpscie () , self . discie () , self . sesie () , self . wkupie ()) } } # [doc = "Global interrupt flag register (USBFS_GINTF)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gintf (pub u32) ; impl Gintf { # [doc = "Current operation mode"]
# [inline (always)]
pub const fn copm (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Current operation mode"]
# [inline (always)]
pub fn set_copm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mode fault interrupt flag"]
# [inline (always)]
pub const fn mfif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mode fault interrupt flag"]
# [inline (always)]
pub fn set_mfif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "OTG interrupt flag"]
# [inline (always)]
pub const fn otgif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "OTG interrupt flag"]
# [inline (always)]
pub fn set_otgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Start of frame"]
# [inline (always)]
pub const fn sof (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Start of frame"]
# [inline (always)]
pub fn set_sof (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "RxFIFO non-empty interrupt flag"]
# [inline (always)]
pub const fn rxfneif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "RxFIFO non-empty interrupt flag"]
# [inline (always)]
pub fn set_rxfneif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Non-periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub const fn nptxfeif (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Non-periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub fn set_nptxfeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Global Non-Periodic IN NAK effective"]
# [inline (always)]
pub const fn gnpinak (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Global Non-Periodic IN NAK effective"]
# [inline (always)]
pub fn set_gnpinak (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Global OUT NAK effective"]
# [inline (always)]
pub const fn gonak (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Global OUT NAK effective"]
# [inline (always)]
pub fn set_gonak (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Early suspend"]
# [inline (always)]
pub const fn esp (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Early suspend"]
# [inline (always)]
pub fn set_esp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "USB suspend"]
# [inline (always)]
pub const fn sp (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "USB suspend"]
# [inline (always)]
pub fn set_sp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "USB reset"]
# [inline (always)]
pub const fn rst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "USB reset"]
# [inline (always)]
pub fn set_rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Enumeration finished"]
# [inline (always)]
pub const fn enumf (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Enumeration finished"]
# [inline (always)]
pub fn set_enumf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Isochronous OUT packet dropped interrupt"]
# [inline (always)]
pub const fn isoopdif (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Isochronous OUT packet dropped interrupt"]
# [inline (always)]
pub fn set_isoopdif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "End of periodic frame interrupt flag"]
# [inline (always)]
pub const fn eopfif (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "End of periodic frame interrupt flag"]
# [inline (always)]
pub fn set_eopfif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "IN endpoint interrupt flag"]
# [inline (always)]
pub const fn iepif (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "IN endpoint interrupt flag"]
# [inline (always)]
pub fn set_iepif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "OUT endpoint interrupt flag"]
# [inline (always)]
pub const fn oepif (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "OUT endpoint interrupt flag"]
# [inline (always)]
pub fn set_oepif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Isochronous IN transfer Not Complete Interrupt Flag"]
# [inline (always)]
pub const fn isoincif (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Isochronous IN transfer Not Complete Interrupt Flag"]
# [inline (always)]
pub fn set_isoincif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "periodic transfer not complete interrupt flag(Host mode)/isochronous OUT transfer not complete interrupt flag(Device mode)"]
# [inline (always)]
pub const fn pxncif_isooncif (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "periodic transfer not complete interrupt flag(Host mode)/isochronous OUT transfer not complete interrupt flag(Device mode)"]
# [inline (always)]
pub fn set_pxncif_isooncif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Host port interrupt flag"]
# [inline (always)]
pub const fn hpif (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Host port interrupt flag"]
# [inline (always)]
pub fn set_hpif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Host channels interrupt flag"]
# [inline (always)]
pub const fn hcif (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Host channels interrupt flag"]
# [inline (always)]
pub fn set_hcif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub const fn ptxfeif (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub fn set_ptxfeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "LPM interrupt flag"]
# [inline (always)]
pub const fn lpmif (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "LPM interrupt flag"]
# [inline (always)]
pub fn set_lpmif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "ID pin status change"]
# [inline (always)]
pub const fn idpsc (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "ID pin status change"]
# [inline (always)]
pub fn set_idpsc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Disconnect interrupt flag"]
# [inline (always)]
pub const fn discif (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Disconnect interrupt flag"]
# [inline (always)]
pub fn set_discif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Session interrupt flag"]
# [inline (always)]
pub const fn sesif (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Session interrupt flag"]
# [inline (always)]
pub fn set_sesif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Wakeup interrupt flag"]
# [inline (always)]
pub const fn wkupif (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Wakeup interrupt flag"]
# [inline (always)]
pub fn set_wkupif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Gintf { # [inline (always)]
fn default () -> Gintf { Gintf (0) } } impl core :: fmt :: Debug for Gintf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gintf") . field ("copm" , & self . copm ()) . field ("mfif" , & self . mfif ()) . field ("otgif" , & self . otgif ()) . field ("sof" , & self . sof ()) . field ("rxfneif" , & self . rxfneif ()) . field ("nptxfeif" , & self . nptxfeif ()) . field ("gnpinak" , & self . gnpinak ()) . field ("gonak" , & self . gonak ()) . field ("esp" , & self . esp ()) . field ("sp" , & self . sp ()) . field ("rst" , & self . rst ()) . field ("enumf" , & self . enumf ()) . field ("isoopdif" , & self . isoopdif ()) . field ("eopfif" , & self . eopfif ()) . field ("iepif" , & self . iepif ()) . field ("oepif" , & self . oepif ()) . field ("isoincif" , & self . isoincif ()) . field ("pxncif_isooncif" , & self . pxncif_isooncif ()) . field ("hpif" , & self . hpif ()) . field ("hcif" , & self . hcif ()) . field ("ptxfeif" , & self . ptxfeif ()) . field ("lpmif" , & self . lpmif ()) . field ("idpsc" , & self . idpsc ()) . field ("discif" , & self . discif ()) . field ("sesif" , & self . sesif ()) . field ("wkupif" , & self . wkupif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gintf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gintf {{ copm: {=bool:?}, mfif: {=bool:?}, otgif: {=bool:?}, sof: {=bool:?}, rxfneif: {=bool:?}, nptxfeif: {=bool:?}, gnpinak: {=bool:?}, gonak: {=bool:?}, esp: {=bool:?}, sp: {=bool:?}, rst: {=bool:?}, enumf: {=bool:?}, isoopdif: {=bool:?}, eopfif: {=bool:?}, iepif: {=bool:?}, oepif: {=bool:?}, isoincif: {=bool:?}, pxncif_isooncif: {=bool:?}, hpif: {=bool:?}, hcif: {=bool:?}, ptxfeif: {=bool:?}, lpmif: {=bool:?}, idpsc: {=bool:?}, discif: {=bool:?}, sesif: {=bool:?}, wkupif: {=bool:?} }}" , self . copm () , self . mfif () , self . otgif () , self . sof () , self . rxfneif () , self . nptxfeif () , self . gnpinak () , self . gonak () , self . esp () , self . sp () , self . rst () , self . enumf () , self . isoopdif () , self . eopfif () , self . iepif () , self . oepif () , self . isoincif () , self . pxncif_isooncif () , self . hpif () , self . hcif () , self . ptxfeif () , self . lpmif () , self . idpsc () , self . discif () , self . sesif () , self . wkupif ()) } } # [doc = "Global core LPM configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Glpmcfg (pub u32) ; impl Glpmcfg { # [doc = "LPM enable"]
# [inline (always)]
pub const fn lpmen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "LPM enable"]
# [inline (always)]
pub fn set_lpmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "ACK in LPM transaction enable"]
# [inline (always)]
pub const fn acklpm (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "ACK in LPM transaction enable"]
# [inline (always)]
pub fn set_acklpm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Best effort service latency"]
# [inline (always)]
pub const fn besl (& self) -> u8 { let val = (self . 0 >> 2usize) & 0x0f ; val as u8 } # [doc = "Best effort service latency"]
# [inline (always)]
pub fn set_besl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 2usize)) | (((val as u32) & 0x0f) << 2usize) ; } # [doc = "RemoteWake value"]
# [inline (always)]
pub const fn rew (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "RemoteWake value"]
# [inline (always)]
pub fn set_rew (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Shallow sleep enable"]
# [inline (always)]
pub const fn ssen (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Shallow sleep enable"]
# [inline (always)]
pub fn set_ssen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "BESL threshold"]
# [inline (always)]
pub const fn beslth (& self) -> u8 { let val = (self . 0 >> 8usize) & 0x0f ; val as u8 } # [doc = "BESL threshold"]
# [inline (always)]
pub fn set_beslth (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 8usize)) | (((val as u32) & 0x0f) << 8usize) ; } # [doc = "Deep sleep enable"]
# [inline (always)]
pub const fn dsen (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Deep sleep enable"]
# [inline (always)]
pub fn set_dsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Response of LPM"]
# [inline (always)]
pub const fn lpmrsp (& self) -> u8 { let val = (self . 0 >> 13usize) & 0x03 ; val as u8 } # [doc = "Response of LPM"]
# [inline (always)]
pub fn set_lpmrsp (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 13usize)) | (((val as u32) & 0x03) << 13usize) ; } # [doc = "Sleep status"]
# [inline (always)]
pub const fn lpmslps (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Sleep status"]
# [inline (always)]
pub fn set_lpmslps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Resume can be sent after sleep state"]
# [inline (always)]
pub const fn rsok (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Resume can be sent after sleep state"]
# [inline (always)]
pub fn set_rsok (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Channel number index when send LPM transaction"]
# [inline (always)]
pub const fn lpmchi (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Channel number index when send LPM transaction"]
# [inline (always)]
pub fn set_lpmchi (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } # [doc = "LPM retry count"]
# [inline (always)]
pub const fn lpmrc (& self) -> u8 { let val = (self . 0 >> 21usize) & 0x07 ; val as u8 } # [doc = "LPM retry count"]
# [inline (always)]
pub fn set_lpmrc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 21usize)) | (((val as u32) & 0x07) << 21usize) ; } # [doc = "Send LPM transaction"]
# [inline (always)]
pub const fn lpmsnd (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Send LPM transaction"]
# [inline (always)]
pub fn set_lpmsnd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "LPM retry count status"]
# [inline (always)]
pub const fn lpmrcs (& self) -> u8 { let val = (self . 0 >> 25usize) & 0x07 ; val as u8 } # [doc = "LPM retry count status"]
# [inline (always)]
pub fn set_lpmrcs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 25usize)) | (((val as u32) & 0x07) << 25usize) ; } # [doc = "LPM Errata selection enable"]
# [inline (always)]
pub const fn beslen (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "LPM Errata selection enable"]
# [inline (always)]
pub fn set_beslen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } } impl Default for Glpmcfg { # [inline (always)]
fn default () -> Glpmcfg { Glpmcfg (0) } } impl core :: fmt :: Debug for Glpmcfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Glpmcfg") . field ("lpmen" , & self . lpmen ()) . field ("acklpm" , & self . acklpm ()) . field ("besl" , & self . besl ()) . field ("rew" , & self . rew ()) . field ("ssen" , & self . ssen ()) . field ("beslth" , & self . beslth ()) . field ("dsen" , & self . dsen ()) . field ("lpmrsp" , & self . lpmrsp ()) . field ("lpmslps" , & self . lpmslps ()) . field ("rsok" , & self . rsok ()) . field ("lpmchi" , & self . lpmchi ()) . field ("lpmrc" , & self . lpmrc ()) . field ("lpmsnd" , & self . lpmsnd ()) . field ("lpmrcs" , & self . lpmrcs ()) . field ("beslen" , & self . beslen ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Glpmcfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Glpmcfg {{ lpmen: {=bool:?}, acklpm: {=bool:?}, besl: {=u8:?}, rew: {=bool:?}, ssen: {=bool:?}, beslth: {=u8:?}, dsen: {=bool:?}, lpmrsp: {=u8:?}, lpmslps: {=bool:?}, rsok: {=bool:?}, lpmchi: {=u8:?}, lpmrc: {=u8:?}, lpmsnd: {=bool:?}, lpmrcs: {=u8:?}, beslen: {=bool:?} }}" , self . lpmen () , self . acklpm () , self . besl () , self . rew () , self . ssen () , self . beslth () , self . dsen () , self . lpmrsp () , self . lpmslps () , self . rsok () , self . lpmchi () , self . lpmrc () , self . lpmsnd () , self . lpmrcs () , self . beslen ()) } } # [doc = "Global OTG control and status register (USBFS_GOTGCS)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gotgcs (pub u32) ; impl Gotgcs { # [doc = "SRP success"]
# [inline (always)]
pub const fn srps (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "SRP success"]
# [inline (always)]
pub fn set_srps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SRP request"]
# [inline (always)]
pub const fn srpreq (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SRP request"]
# [inline (always)]
pub fn set_srpreq (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Override enable of VBUS valid"]
# [inline (always)]
pub const fn voe (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Override enable of VBUS valid"]
# [inline (always)]
pub fn set_voe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Override value of VBUS valid"]
# [inline (always)]
pub const fn vov (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Override value of VBUS valid"]
# [inline (always)]
pub fn set_vov (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Override enable of A-peripheral session valid"]
# [inline (always)]
pub const fn avoe (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Override enable of A-peripheral session valid"]
# [inline (always)]
pub fn set_avoe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Override value of A-peripheral session valid"]
# [inline (always)]
pub const fn avov (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Override value of A-peripheral session valid"]
# [inline (always)]
pub fn set_avov (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Override enable of B-peripheral session valid"]
# [inline (always)]
pub const fn bvoe (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Override enable of B-peripheral session valid"]
# [inline (always)]
pub fn set_bvoe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Override value of B-peripheral session valid"]
# [inline (always)]
pub const fn bvov (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Override value of B-peripheral session valid"]
# [inline (always)]
pub fn set_bvov (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "HNP success"]
# [inline (always)]
pub const fn hnps (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "HNP success"]
# [inline (always)]
pub fn set_hnps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "HNP request"]
# [inline (always)]
pub const fn hnpreq (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "HNP request"]
# [inline (always)]
pub fn set_hnpreq (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Host HNP enable"]
# [inline (always)]
pub const fn hhnpen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Host HNP enable"]
# [inline (always)]
pub fn set_hhnpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Device HNP enabled"]
# [inline (always)]
pub const fn dhnpen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Device HNP enabled"]
# [inline (always)]
pub fn set_dhnpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Embedded host enable"]
# [inline (always)]
pub const fn ehe (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Embedded host enable"]
# [inline (always)]
pub fn set_ehe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "ID pin status"]
# [inline (always)]
pub const fn idps (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "ID pin status"]
# [inline (always)]
pub fn set_idps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Debounce interval"]
# [inline (always)]
pub const fn di (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Debounce interval"]
# [inline (always)]
pub fn set_di (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "A-session valid"]
# [inline (always)]
pub const fn asv (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "A-session valid"]
# [inline (always)]
pub fn set_asv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "B-session valid"]
# [inline (always)]
pub const fn bsv (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "B-session valid"]
# [inline (always)]
pub fn set_bsv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Select OTG version"]
# [inline (always)]
pub const fn ov (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Select OTG version"]
# [inline (always)]
pub fn set_ov (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } } impl Default for Gotgcs { # [inline (always)]
fn default () -> Gotgcs { Gotgcs (0) } } impl core :: fmt :: Debug for Gotgcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gotgcs") . field ("srps" , & self . srps ()) . field ("srpreq" , & self . srpreq ()) . field ("voe" , & self . voe ()) . field ("vov" , & self . vov ()) . field ("avoe" , & self . avoe ()) . field ("avov" , & self . avov ()) . field ("bvoe" , & self . bvoe ()) . field ("bvov" , & self . bvov ()) . field ("hnps" , & self . hnps ()) . field ("hnpreq" , & self . hnpreq ()) . field ("hhnpen" , & self . hhnpen ()) . field ("dhnpen" , & self . dhnpen ()) . field ("ehe" , & self . ehe ()) . field ("idps" , & self . idps ()) . field ("di" , & self . di ()) . field ("asv" , & self . asv ()) . field ("bsv" , & self . bsv ()) . field ("ov" , & self . ov ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gotgcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gotgcs {{ srps: {=bool:?}, srpreq: {=bool:?}, voe: {=bool:?}, vov: {=bool:?}, avoe: {=bool:?}, avov: {=bool:?}, bvoe: {=bool:?}, bvov: {=bool:?}, hnps: {=bool:?}, hnpreq: {=bool:?}, hhnpen: {=bool:?}, dhnpen: {=bool:?}, ehe: {=bool:?}, idps: {=bool:?}, di: {=bool:?}, asv: {=bool:?}, bsv: {=bool:?}, ov: {=bool:?} }}" , self . srps () , self . srpreq () , self . voe () , self . vov () , self . avoe () , self . avov () , self . bvoe () , self . bvov () , self . hnps () , self . hnpreq () , self . hhnpen () , self . dhnpen () , self . ehe () , self . idps () , self . di () , self . asv () , self . bsv () , self . ov ()) } } # [doc = "Global OTG interrupt flag register (USBHS_GOTGINTF)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gotgintf (pub u32) ; impl Gotgintf { # [doc = "Session end"]
# [inline (always)]
pub const fn sesend (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Session end"]
# [inline (always)]
pub fn set_sesend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Session request success status change"]
# [inline (always)]
pub const fn srpend (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Session request success status change"]
# [inline (always)]
pub fn set_srpend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "HNP end"]
# [inline (always)]
pub const fn hnpend (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "HNP end"]
# [inline (always)]
pub fn set_hnpend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Host negotiation request detected"]
# [inline (always)]
pub const fn hnpdet (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Host negotiation request detected"]
# [inline (always)]
pub fn set_hnpdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "A-device timeout"]
# [inline (always)]
pub const fn adto (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "A-device timeout"]
# [inline (always)]
pub fn set_adto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Debounce finish"]
# [inline (always)]
pub const fn df (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Debounce finish"]
# [inline (always)]
pub fn set_df (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "There is a change in the value of ID input"]
# [inline (always)]
pub const fn idchg (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "There is a change in the value of ID input"]
# [inline (always)]
pub fn set_idchg (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } } impl Default for Gotgintf { # [inline (always)]
fn default () -> Gotgintf { Gotgintf (0) } } impl core :: fmt :: Debug for Gotgintf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gotgintf") . field ("sesend" , & self . sesend ()) . field ("srpend" , & self . srpend ()) . field ("hnpend" , & self . hnpend ()) . field ("hnpdet" , & self . hnpdet ()) . field ("adto" , & self . adto ()) . field ("df" , & self . df ()) . field ("idchg" , & self . idchg ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gotgintf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gotgintf {{ sesend: {=bool:?}, srpend: {=bool:?}, hnpend: {=bool:?}, hnpdet: {=bool:?}, adto: {=bool:?}, df: {=bool:?}, idchg: {=bool:?} }}" , self . sesend () , self . srpend () , self . hnpend () , self . hnpdet () , self . adto () , self . df () , self . idchg ()) } } # [doc = "Global Receive FIFO size register (USBHS_GRFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Grflen (pub u32) ; impl Grflen { # [doc = "Rx FIFO depth"]
# [inline (always)]
pub const fn rxfd (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Rx FIFO depth"]
# [inline (always)]
pub fn set_rxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Grflen { # [inline (always)]
fn default () -> Grflen { Grflen (0) } } impl core :: fmt :: Debug for Grflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Grflen") . field ("rxfd" , & self . rxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Grflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Grflen {{ rxfd: {=u16:?} }}" , self . rxfd ()) } } # [doc = "Global Receive status pop(Device mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatpDevice (pub u32) ; impl GrstatpDevice { # [doc = "Endpoint number"]
# [inline (always)]
pub const fn epnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Endpoint number"]
# [inline (always)]
pub fn set_epnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Recieve packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Recieve packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatpDevice { # [inline (always)]
fn default () -> GrstatpDevice { GrstatpDevice (0) } } impl core :: fmt :: Debug for GrstatpDevice { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatpDevice") . field ("epnum" , & self . epnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatpDevice { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatpDevice {{ epnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . epnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global Receive status pop(Host mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatpHost (pub u32) ; impl GrstatpHost { # [doc = "Channel number"]
# [inline (always)]
pub const fn cnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Channel number"]
# [inline (always)]
pub fn set_cnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Reivece packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Reivece packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatpHost { # [inline (always)]
fn default () -> GrstatpHost { GrstatpHost (0) } } impl core :: fmt :: Debug for GrstatpHost { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatpHost") . field ("cnum" , & self . cnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatpHost { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatpHost {{ cnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . cnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global Receive status read(Device mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatrDevice (pub u32) ; impl GrstatrDevice { # [doc = "Endpoint number"]
# [inline (always)]
pub const fn epnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Endpoint number"]
# [inline (always)]
pub fn set_epnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Recieve packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Recieve packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatrDevice { # [inline (always)]
fn default () -> GrstatrDevice { GrstatrDevice (0) } } impl core :: fmt :: Debug for GrstatrDevice { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatrDevice") . field ("epnum" , & self . epnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatrDevice { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatrDevice {{ epnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . epnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global Receive status read(Host mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatrHost (pub u32) ; impl GrstatrHost { # [doc = "Channel number"]
# [inline (always)]
pub const fn cnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Channel number"]
# [inline (always)]
pub fn set_cnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Reivece packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Reivece packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatrHost { # [inline (always)]
fn default () -> GrstatrHost { GrstatrHost (0) } } impl core :: fmt :: Debug for GrstatrHost { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatrHost") . field ("cnum" , & self . cnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatrHost { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatrHost {{ cnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . cnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global reset control register (USBHS_GRSTCTL)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Grstctl (pub u32) ; impl Grstctl { # [doc = "Core soft reset"]
# [inline (always)]
pub const fn csrst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Core soft reset"]
# [inline (always)]
pub fn set_csrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "HCLK soft reset"]
# [inline (always)]
pub const fn hcsrst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "HCLK soft reset"]
# [inline (always)]
pub fn set_hcsrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Host frame counter reset"]
# [inline (always)]
pub const fn hfcrst (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Host frame counter reset"]
# [inline (always)]
pub fn set_hfcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "RxFIFO flush"]
# [inline (always)]
pub const fn rxff (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "RxFIFO flush"]
# [inline (always)]
pub fn set_rxff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "TxFIFO flush"]
# [inline (always)]
pub const fn txff (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "TxFIFO flush"]
# [inline (always)]
pub fn set_txff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "TxFIFO number"]
# [inline (always)]
pub const fn txfnum (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x1f ; val as u8 } # [doc = "TxFIFO number"]
# [inline (always)]
pub fn set_txfnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 6usize)) | (((val as u32) & 0x1f) << 6usize) ; } # [doc = "DMA Busy"]
# [inline (always)]
pub const fn dmabsy (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "DMA Busy"]
# [inline (always)]
pub fn set_dmabsy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "DMA Idle state"]
# [inline (always)]
pub const fn dmaidl (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "DMA Idle state"]
# [inline (always)]
pub fn set_dmaidl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Grstctl { # [inline (always)]
fn default () -> Grstctl { Grstctl (0) } } impl core :: fmt :: Debug for Grstctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Grstctl") . field ("csrst" , & self . csrst ()) . field ("hcsrst" , & self . hcsrst ()) . field ("hfcrst" , & self . hfcrst ()) . field ("rxff" , & self . rxff ()) . field ("txff" , & self . txff ()) . field ("txfnum" , & self . txfnum ()) . field ("dmabsy" , & self . dmabsy ()) . field ("dmaidl" , & self . dmaidl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Grstctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Grstctl {{ csrst: {=bool:?}, hcsrst: {=bool:?}, hfcrst: {=bool:?}, rxff: {=bool:?}, txff: {=bool:?}, txfnum: {=u8:?}, dmabsy: {=bool:?}, dmaidl: {=bool:?} }}" , self . csrst () , self . hcsrst () , self . hfcrst () , self . rxff () , self . txff () , self . txfnum () , self . dmabsy () , self . dmaidl ()) } } # [doc = "Global USB control and status register (USBHS_GUSBCSR)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gusbcs (pub u32) ; impl Gusbcs { # [doc = "Timeout calibration"]
# [inline (always)]
pub const fn toc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "Timeout calibration"]
# [inline (always)]
pub fn set_toc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "HS current software enable"]
# [inline (always)]
pub const fn hs_eft_fe (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "HS current software enable"]
# [inline (always)]
pub fn set_hs_eft_fe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Embedded HS PHY selected"]
# [inline (always)]
pub const fn embphy_hs (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Embedded HS PHY selected"]
# [inline (always)]
pub fn set_embphy_hs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Embedded FS PHY selected"]
# [inline (always)]
pub const fn embphy_fs (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Embedded FS PHY selected"]
# [inline (always)]
pub fn set_embphy_fs (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "SRP capability enable"]
# [inline (always)]
pub const fn srpcen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "SRP capability enable"]
# [inline (always)]
pub fn set_srpcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "HNP capability enable"]
# [inline (always)]
pub const fn hnpcen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "HNP capability enable"]
# [inline (always)]
pub fn set_hnpcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "USB turnaround time"]
# [inline (always)]
pub const fn utt (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x0f ; val as u8 } # [doc = "USB turnaround time"]
# [inline (always)]
pub fn set_utt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 10usize)) | (((val as u32) & 0x0f) << 10usize) ; } # [doc = "ULPI external VBUS driver"]
# [inline (always)]
pub const fn ulpievd (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "ULPI external VBUS driver"]
# [inline (always)]
pub fn set_ulpievd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "ULPI external over-current indicator"]
# [inline (always)]
pub const fn ulpieoi (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "ULPI external over-current indicator"]
# [inline (always)]
pub fn set_ulpieoi (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Force host mode"]
# [inline (always)]
pub const fn fhm (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Force host mode"]
# [inline (always)]
pub fn set_fhm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Force device mode"]
# [inline (always)]
pub const fn fdm (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Force device mode"]
# [inline (always)]
pub fn set_fdm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for Gusbcs { # [inline (always)]
fn default () -> Gusbcs { Gusbcs (0) } } impl core :: fmt :: Debug for Gusbcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gusbcs") . field ("toc" , & self . toc ()) . field ("hs_eft_fe" , & self . hs_eft_fe ()) . field ("embphy_hs" , & self . embphy_hs ()) . field ("embphy_fs" , & self . embphy_fs ()) . field ("srpcen" , & self . srpcen ()) . field ("hnpcen" , & self . hnpcen ()) . field ("utt" , & self . utt ()) . field ("ulpievd" , & self . ulpievd ()) . field ("ulpieoi" , & self . ulpieoi ()) . field ("fhm" , & self . fhm ()) . field ("fdm" , & self . fdm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gusbcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gusbcs {{ toc: {=u8:?}, hs_eft_fe: {=bool:?}, embphy_hs: {=bool:?}, embphy_fs: {=bool:?}, srpcen: {=bool:?}, hnpcen: {=bool:?}, utt: {=u8:?}, ulpievd: {=bool:?}, ulpieoi: {=bool:?}, fhm: {=bool:?}, fdm: {=bool:?} }}" , self . toc () , self . hs_eft_fe () , self . embphy_hs () , self . embphy_fs () , self . srpcen () , self . hnpcen () , self . utt () , self . ulpievd () , self . ulpieoi () , self . fhm () , self . fdm ()) } } # [doc = "Host non-periodic transmit FIFO length register (Host mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hnptflen (pub u32) ; impl Hnptflen { # [doc = "host non-periodic transmit Tx RAM start address"]
# [inline (always)]
pub const fn hnptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "host non-periodic transmit Tx RAM start address"]
# [inline (always)]
pub fn set_hnptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "host non-periodic TxFIFO depth"]
# [inline (always)]
pub const fn hnptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "host non-periodic TxFIFO depth"]
# [inline (always)]
pub fn set_hnptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Hnptflen { # [inline (always)]
fn default () -> Hnptflen { Hnptflen (0) } } impl core :: fmt :: Debug for Hnptflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hnptflen") . field ("hnptxrsar" , & self . hnptxrsar ()) . field ("hnptxfd" , & self . hnptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hnptflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hnptflen {{ hnptxrsar: {=u16:?}, hnptxfd: {=u16:?} }}" , self . hnptxrsar () , self . hnptxfd ()) } } # [doc = "Host non-periodic transmit FIFO/queue status register (HNPTFQSTAT)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hnptfqstat (pub u32) ; impl Hnptfqstat { # [doc = "Non-periodic TxFIFO space"]
# [inline (always)]
pub const fn nptxfs (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Non-periodic TxFIFO space"]
# [inline (always)]
pub fn set_nptxfs (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Non-periodic transmit request queue space"]
# [inline (always)]
pub const fn nptxrqs (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Non-periodic transmit request queue space"]
# [inline (always)]
pub fn set_nptxrqs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Top of the non-periodic transmit request queue"]
# [inline (always)]
pub const fn nptxrqtop (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x7f ; val as u8 } # [doc = "Top of the non-periodic transmit request queue"]
# [inline (always)]
pub fn set_nptxrqtop (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 24usize)) | (((val as u32) & 0x7f) << 24usize) ; } } impl Default for Hnptfqstat { # [inline (always)]
fn default () -> Hnptfqstat { Hnptfqstat (0) } } impl core :: fmt :: Debug for Hnptfqstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hnptfqstat") . field ("nptxfs" , & self . nptxfs ()) . field ("nptxrqs" , & self . nptxrqs ()) . field ("nptxrqtop" , & self . nptxrqtop ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hnptfqstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hnptfqstat {{ nptxfs: {=u16:?}, nptxrqs: {=u8:?}, nptxrqtop: {=u8:?} }}" , self . nptxfs () , self . nptxrqs () , self . nptxrqtop ()) } } # [doc = "Host periodic transmit FIFO length register (HPTFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hptflen (pub u32) ; impl Hptflen { # [doc = "Host periodic TxFIFO start address"]
# [inline (always)]
pub const fn hptxfsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Host periodic TxFIFO start address"]
# [inline (always)]
pub fn set_hptxfsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Host periodic TxFIFO depth"]
# [inline (always)]
pub const fn hptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Host periodic TxFIFO depth"]
# [inline (always)]
pub fn set_hptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Hptflen { # [inline (always)]
fn default () -> Hptflen { Hptflen (0) } } impl core :: fmt :: Debug for Hptflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hptflen") . field ("hptxfsar" , & self . hptxfsar ()) . field ("hptxfd" , & self . hptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hptflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hptflen {{ hptxfsar: {=u16:?}, hptxfd: {=u16:?} }}" , self . hptxfsar () , self . hptxfd ()) } } # [doc = "Power down register (USBHS_PWRD)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pwrd (pub u32) ; impl Pwrd { # [doc = "ADP module enable"]
# [inline (always)]
pub const fn adpmen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "ADP module enable"]
# [inline (always)]
pub fn set_adpmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "ADP event interrupt flag"]
# [inline (always)]
pub const fn adpf (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "ADP event interrupt flag"]
# [inline (always)]
pub fn set_adpf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } } impl Default for Pwrd { # [inline (always)]
fn default () -> Pwrd { Pwrd (0) } } impl core :: fmt :: Debug for Pwrd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pwrd") . field ("adpmen" , & self . adpmen ()) . field ("adpf" , & self . adpf ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pwrd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pwrd {{ adpmen: {=bool:?}, adpf: {=bool:?} }}" , self . adpmen () , self . adpf ()) } } }
