#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "Universal synchronous/asynchronous receiver /transmitter"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Usart0 { ptr : * mut u8 } unsafe impl Send for Usart0 { } unsafe impl Sync for Usart0 { } impl Usart0 { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Control register 0"]
# [inline (always)]
pub const fn ctl0 (self) -> crate :: common :: Reg < regs :: Ctl0 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Control register 1"]
# [inline (always)]
pub const fn ctl1 (self) -> crate :: common :: Reg < regs :: Ctl1 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Control register 2"]
# [inline (always)]
pub const fn ctl2 (self) -> crate :: common :: Reg < regs :: Ctl2 , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Baud rate generator register"]
# [inline (always)]
pub const fn baud (self) -> crate :: common :: Reg < regs :: Baud , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Prescaler and guard time configuration register"]
# [inline (always)]
pub const fn gp (self) -> crate :: common :: Reg < regs :: Gp , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Receiver timeout register"]
# [inline (always)]
pub const fn rt (self) -> crate :: common :: Reg < regs :: Rt , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Command register"]
# [inline (always)]
pub const fn cmd (self) -> crate :: common :: Reg < regs :: Cmd , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Status register"]
# [inline (always)]
pub const fn stat (self) -> crate :: common :: Reg < regs :: Stat , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Interrupt status clear register"]
# [inline (always)]
pub const fn intc (self) -> crate :: common :: Reg < regs :: Intc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Receive data register"]
# [inline (always)]
pub const fn rdata (self) -> crate :: common :: Reg < regs :: Rdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Transmit data register"]
# [inline (always)]
pub const fn tdata (self) -> crate :: common :: Reg < regs :: Tdata , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "USART coherence control register"]
# [inline (always)]
pub const fn chc (self) -> crate :: common :: Reg < regs :: Chc , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xc0usize) as _) } } # [doc = "USART FIFO control and status register"]
# [inline (always)]
pub const fn fcs (self) -> crate :: common :: Reg < regs :: Fcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0xd0usize) as _) } } } pub mod regs { # [doc = "Baud rate generator register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Baud (pub u32) ; impl Baud { # [doc = "Fraction of baud-rate divider"]
# [inline (always)]
pub const fn brr_div (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Fraction of baud-rate divider"]
# [inline (always)]
pub fn set_brr_div (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Integer of baud-rate divider"]
# [inline (always)]
pub const fn brr_int (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x0fff ; val as u16 } # [doc = "Integer of baud-rate divider"]
# [inline (always)]
pub fn set_brr_int (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x0fff << 4usize)) | (((val as u32) & 0x0fff) << 4usize) ; } } impl Default for Baud { # [inline (always)]
fn default () -> Baud { Baud (0) } } impl core :: fmt :: Debug for Baud { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Baud") . field ("brr_div" , & self . brr_div ()) . field ("brr_int" , & self . brr_int ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Baud { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Baud {{ brr_div: {=u8:?}, brr_int: {=u16:?} }}" , self . brr_div () , self . brr_int ()) } } # [doc = "USART coherence control register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Chc (pub u32) ; impl Chc { # [doc = "Hardware flow control coherence mode"]
# [inline (always)]
pub const fn hcm (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Hardware flow control coherence mode"]
# [inline (always)]
pub fn set_hcm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Early parity error flag"]
# [inline (always)]
pub const fn eperr (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Early parity error flag"]
# [inline (always)]
pub fn set_eperr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for Chc { # [inline (always)]
fn default () -> Chc { Chc (0) } } impl core :: fmt :: Debug for Chc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Chc") . field ("hcm" , & self . hcm ()) . field ("eperr" , & self . eperr ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Chc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Chc {{ hcm: {=bool:?}, eperr: {=bool:?} }}" , self . hcm () , self . eperr ()) } } # [doc = "Command register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cmd (pub u32) ; impl Cmd { # [doc = "Send break command"]
# [inline (always)]
pub const fn sbkcmd (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Send break command"]
# [inline (always)]
pub fn set_sbkcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Mute mode command"]
# [inline (always)]
pub const fn mmcmd (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Mute mode command"]
# [inline (always)]
pub fn set_mmcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Receive data flush command"]
# [inline (always)]
pub const fn rxfcmd (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Receive data flush command"]
# [inline (always)]
pub fn set_rxfcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Transmit data flush request"]
# [inline (always)]
pub const fn txfcmd (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Transmit data flush request"]
# [inline (always)]
pub fn set_txfcmd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } } impl Default for Cmd { # [inline (always)]
fn default () -> Cmd { Cmd (0) } } impl core :: fmt :: Debug for Cmd { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cmd") . field ("sbkcmd" , & self . sbkcmd ()) . field ("mmcmd" , & self . mmcmd ()) . field ("rxfcmd" , & self . rxfcmd ()) . field ("txfcmd" , & self . txfcmd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cmd { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cmd {{ sbkcmd: {=bool:?}, mmcmd: {=bool:?}, rxfcmd: {=bool:?}, txfcmd: {=bool:?} }}" , self . sbkcmd () , self . mmcmd () , self . rxfcmd () , self . txfcmd ()) } } # [doc = "Control register 0"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl0 (pub u32) ; impl Ctl0 { # [doc = "USART enable"]
# [inline (always)]
pub const fn uen (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "USART enable"]
# [inline (always)]
pub fn set_uen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "USART enable in Deep-sleep mode"]
# [inline (always)]
pub const fn uesm (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "USART enable in Deep-sleep mode"]
# [inline (always)]
pub fn set_uesm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Receiver enable"]
# [inline (always)]
pub const fn ren (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Receiver enable"]
# [inline (always)]
pub fn set_ren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Transmitter enable"]
# [inline (always)]
pub const fn ten (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Transmitter enable"]
# [inline (always)]
pub fn set_ten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "IDLE line detected interrupt enable"]
# [inline (always)]
pub const fn idleie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "IDLE line detected interrupt enable"]
# [inline (always)]
pub fn set_idleie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Interrupt enable"]
# [inline (always)]
pub const fn rbneie_rfneie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Interrupt enable"]
# [inline (always)]
pub fn set_rbneie_rfneie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Transmission complete interrupt enable"]
# [inline (always)]
pub const fn tcie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmission complete interrupt enable"]
# [inline (always)]
pub fn set_tcie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Interrupt enable"]
# [inline (always)]
pub const fn tbeie_tfnfie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Interrupt enable"]
# [inline (always)]
pub fn set_tbeie_tfnfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Parity error interrupt enable"]
# [inline (always)]
pub const fn perrie (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Parity error interrupt enable"]
# [inline (always)]
pub fn set_perrie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Parity mode"]
# [inline (always)]
pub const fn pm (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Parity mode"]
# [inline (always)]
pub fn set_pm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Parity control enable"]
# [inline (always)]
pub const fn pcen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Parity control enable"]
# [inline (always)]
pub fn set_pcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Wakeup method in mute mode"]
# [inline (always)]
pub const fn wm (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Wakeup method in mute mode"]
# [inline (always)]
pub fn set_wm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Word length"]
# [inline (always)]
pub const fn wl0 (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Word length"]
# [inline (always)]
pub fn set_wl0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Mute mode enable"]
# [inline (always)]
pub const fn men (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Mute mode enable"]
# [inline (always)]
pub fn set_men (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "ADDR0 match interrupt enable"]
# [inline (always)]
pub const fn amie0 (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "ADDR0 match interrupt enable"]
# [inline (always)]
pub fn set_amie0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Oversample mode"]
# [inline (always)]
pub const fn ovsmod (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Oversample mode"]
# [inline (always)]
pub fn set_ovsmod (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Driver Enable de-assertion time"]
# [inline (always)]
pub const fn ded (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x1f ; val as u8 } # [doc = "Driver Enable de-assertion time"]
# [inline (always)]
pub fn set_ded (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 16usize)) | (((val as u32) & 0x1f) << 16usize) ; } # [doc = "Driver Enable assertion time"]
# [inline (always)]
pub const fn dea (& self) -> u8 { let val = (self . 0 >> 21usize) & 0x1f ; val as u8 } # [doc = "Driver Enable assertion time"]
# [inline (always)]
pub fn set_dea (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 21usize)) | (((val as u32) & 0x1f) << 21usize) ; } # [doc = "Receiver timeout interrupt enable"]
# [inline (always)]
pub const fn rtie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Receiver timeout interrupt enable"]
# [inline (always)]
pub fn set_rtie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "End of Block interrupt enable"]
# [inline (always)]
pub const fn ebie (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "End of Block interrupt enable"]
# [inline (always)]
pub fn set_ebie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "Word length 1"]
# [inline (always)]
pub const fn wl1 (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "Word length 1"]
# [inline (always)]
pub fn set_wl1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "ADDR1 match interrupt enable"]
# [inline (always)]
pub const fn amie1 (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "ADDR1 match interrupt enable"]
# [inline (always)]
pub fn set_amie1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ctl0 { # [inline (always)]
fn default () -> Ctl0 { Ctl0 (0) } } impl core :: fmt :: Debug for Ctl0 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl0") . field ("uen" , & self . uen ()) . field ("uesm" , & self . uesm ()) . field ("ren" , & self . ren ()) . field ("ten" , & self . ten ()) . field ("idleie" , & self . idleie ()) . field ("rbneie_rfneie" , & self . rbneie_rfneie ()) . field ("tcie" , & self . tcie ()) . field ("tbeie_tfnfie" , & self . tbeie_tfnfie ()) . field ("perrie" , & self . perrie ()) . field ("pm" , & self . pm ()) . field ("pcen" , & self . pcen ()) . field ("wm" , & self . wm ()) . field ("wl0" , & self . wl0 ()) . field ("men" , & self . men ()) . field ("amie0" , & self . amie0 ()) . field ("ovsmod" , & self . ovsmod ()) . field ("ded" , & self . ded ()) . field ("dea" , & self . dea ()) . field ("rtie" , & self . rtie ()) . field ("ebie" , & self . ebie ()) . field ("wl1" , & self . wl1 ()) . field ("amie1" , & self . amie1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl0 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl0 {{ uen: {=bool:?}, uesm: {=bool:?}, ren: {=bool:?}, ten: {=bool:?}, idleie: {=bool:?}, rbneie_rfneie: {=bool:?}, tcie: {=bool:?}, tbeie_tfnfie: {=bool:?}, perrie: {=bool:?}, pm: {=bool:?}, pcen: {=bool:?}, wm: {=bool:?}, wl0: {=bool:?}, men: {=bool:?}, amie0: {=bool:?}, ovsmod: {=bool:?}, ded: {=u8:?}, dea: {=u8:?}, rtie: {=bool:?}, ebie: {=bool:?}, wl1: {=bool:?}, amie1: {=bool:?} }}" , self . uen () , self . uesm () , self . ren () , self . ten () , self . idleie () , self . rbneie_rfneie () , self . tcie () , self . tbeie_tfnfie () , self . perrie () , self . pm () , self . pcen () , self . wm () , self . wl0 () , self . men () , self . amie0 () , self . ovsmod () , self . ded () , self . dea () , self . rtie () , self . ebie () , self . wl1 () , self . amie1 ()) } } # [doc = "Control register 1"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl1 (pub u32) ; impl Ctl1 { # [doc = "Match Address Mode Enable 0"]
# [inline (always)]
pub const fn amen0 (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Match Address Mode Enable 0"]
# [inline (always)]
pub fn set_amen0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Address detection mode 0"]
# [inline (always)]
pub const fn addm0 (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Address detection mode 0"]
# [inline (always)]
pub fn set_addm0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "LIN break frame length"]
# [inline (always)]
pub const fn lblen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "LIN break frame length"]
# [inline (always)]
pub fn set_lblen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "LIN break detection interrupt enable"]
# [inline (always)]
pub const fn lbdie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "LIN break detection interrupt enable"]
# [inline (always)]
pub fn set_lbdie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "CK length"]
# [inline (always)]
pub const fn clen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "CK length"]
# [inline (always)]
pub fn set_clen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Clock phase"]
# [inline (always)]
pub const fn cph (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Clock phase"]
# [inline (always)]
pub fn set_cph (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Clock polarity"]
# [inline (always)]
pub const fn cpl (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Clock polarity"]
# [inline (always)]
pub fn set_cpl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "CK pin enable"]
# [inline (always)]
pub const fn cken (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "CK pin enable"]
# [inline (always)]
pub fn set_cken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "STOP bits length"]
# [inline (always)]
pub const fn stb (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x03 ; val as u8 } # [doc = "STOP bits length"]
# [inline (always)]
pub fn set_stb (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 12usize)) | (((val as u32) & 0x03) << 12usize) ; } # [doc = "LIN mode enable"]
# [inline (always)]
pub const fn lmen (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "LIN mode enable"]
# [inline (always)]
pub fn set_lmen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Swap TX/RX pins"]
# [inline (always)]
pub const fn strp (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Swap TX/RX pins"]
# [inline (always)]
pub fn set_strp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "RX pin level inversion"]
# [inline (always)]
pub const fn rinv (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "RX pin level inversion"]
# [inline (always)]
pub fn set_rinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "TX pin level inversion"]
# [inline (always)]
pub const fn tinv (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "TX pin level inversion"]
# [inline (always)]
pub fn set_tinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Data bit level inversion"]
# [inline (always)]
pub const fn dinv (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Data bit level inversion"]
# [inline (always)]
pub fn set_dinv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Most significant bit first"]
# [inline (always)]
pub const fn msbf (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Most significant bit first"]
# [inline (always)]
pub fn set_msbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Receiver timeout enable"]
# [inline (always)]
pub const fn rten (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "Receiver timeout enable"]
# [inline (always)]
pub fn set_rten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "Address 0 of the USART terminal"]
# [inline (always)]
pub const fn addr0 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Address 0 of the USART terminal"]
# [inline (always)]
pub fn set_addr0 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for Ctl1 { # [inline (always)]
fn default () -> Ctl1 { Ctl1 (0) } } impl core :: fmt :: Debug for Ctl1 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl1") . field ("amen0" , & self . amen0 ()) . field ("addm0" , & self . addm0 ()) . field ("lblen" , & self . lblen ()) . field ("lbdie" , & self . lbdie ()) . field ("clen" , & self . clen ()) . field ("cph" , & self . cph ()) . field ("cpl" , & self . cpl ()) . field ("cken" , & self . cken ()) . field ("stb" , & self . stb ()) . field ("lmen" , & self . lmen ()) . field ("strp" , & self . strp ()) . field ("rinv" , & self . rinv ()) . field ("tinv" , & self . tinv ()) . field ("dinv" , & self . dinv ()) . field ("msbf" , & self . msbf ()) . field ("rten" , & self . rten ()) . field ("addr0" , & self . addr0 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl1 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl1 {{ amen0: {=bool:?}, addm0: {=bool:?}, lblen: {=bool:?}, lbdie: {=bool:?}, clen: {=bool:?}, cph: {=bool:?}, cpl: {=bool:?}, cken: {=bool:?}, stb: {=u8:?}, lmen: {=bool:?}, strp: {=bool:?}, rinv: {=bool:?}, tinv: {=bool:?}, dinv: {=bool:?}, msbf: {=bool:?}, rten: {=bool:?}, addr0: {=u8:?} }}" , self . amen0 () , self . addm0 () , self . lblen () , self . lbdie () , self . clen () , self . cph () , self . cpl () , self . cken () , self . stb () , self . lmen () , self . strp () , self . rinv () , self . tinv () , self . dinv () , self . msbf () , self . rten () , self . addr0 ()) } } # [doc = "Control register 2"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ctl2 (pub u32) ; impl Ctl2 { # [doc = "Error interrupt enable"]
# [inline (always)]
pub const fn errie (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Error interrupt enable"]
# [inline (always)]
pub fn set_errie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "IrDA mode enable"]
# [inline (always)]
pub const fn iren (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "IrDA mode enable"]
# [inline (always)]
pub fn set_iren (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "IrDA low-power"]
# [inline (always)]
pub const fn irlp (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "IrDA low-power"]
# [inline (always)]
pub fn set_irlp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Half-duplex enable"]
# [inline (always)]
pub const fn hden (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Half-duplex enable"]
# [inline (always)]
pub fn set_hden (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "NACK enable in Smartcard mode"]
# [inline (always)]
pub const fn nken (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "NACK enable in Smartcard mode"]
# [inline (always)]
pub fn set_nken (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Smartcard mode enable"]
# [inline (always)]
pub const fn scen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Smartcard mode enable"]
# [inline (always)]
pub fn set_scen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "DMA enable for reception"]
# [inline (always)]
pub const fn denr (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "DMA enable for reception"]
# [inline (always)]
pub fn set_denr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "DMA enable for transmission"]
# [inline (always)]
pub const fn dent (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "DMA enable for transmission"]
# [inline (always)]
pub fn set_dent (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "RTS enable"]
# [inline (always)]
pub const fn rtsen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "RTS enable"]
# [inline (always)]
pub fn set_rtsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "CTS enable"]
# [inline (always)]
pub const fn ctsen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "CTS enable"]
# [inline (always)]
pub fn set_ctsen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "CTS interrupt enable"]
# [inline (always)]
pub const fn ctsie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "CTS interrupt enable"]
# [inline (always)]
pub fn set_ctsie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "One sample bit method"]
# [inline (always)]
pub const fn osb (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "One sample bit method"]
# [inline (always)]
pub fn set_osb (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Overrun disable"]
# [inline (always)]
pub const fn ovrd (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "Overrun disable"]
# [inline (always)]
pub fn set_ovrd (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Disable DMA on reception error"]
# [inline (always)]
pub const fn ddre (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Disable DMA on reception error"]
# [inline (always)]
pub fn set_ddre (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Driver enable mode"]
# [inline (always)]
pub const fn dem (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Driver enable mode"]
# [inline (always)]
pub fn set_dem (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "Driver enable polarity mode"]
# [inline (always)]
pub const fn dep (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Driver enable polarity mode"]
# [inline (always)]
pub fn set_dep (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Match Address Mode Enable 1"]
# [inline (always)]
pub const fn amen1 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Match Address Mode Enable 1"]
# [inline (always)]
pub fn set_amen1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Smartcard auto-retry number"]
# [inline (always)]
pub const fn scrtnum (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x07 ; val as u8 } # [doc = "Smartcard auto-retry number"]
# [inline (always)]
pub fn set_scrtnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 17usize)) | (((val as u32) & 0x07) << 17usize) ; } # [doc = "Wakeup mode from Deep-sleep mode"]
# [inline (always)]
pub const fn wum (& self) -> u8 { let val = (self . 0 >> 20usize) & 0x03 ; val as u8 } # [doc = "Wakeup mode from Deep-sleep mode"]
# [inline (always)]
pub fn set_wum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 20usize)) | (((val as u32) & 0x03) << 20usize) ; } # [doc = "Wakeup from Deep-sleep mode interrupt enable"]
# [inline (always)]
pub const fn wuie (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Wakeup from Deep-sleep mode interrupt enable"]
# [inline (always)]
pub fn set_wuie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "Address detection mode 1"]
# [inline (always)]
pub const fn addm1 (& self) -> bool { let val = (self . 0 >> 23usize) & 0x01 ; val != 0 } # [doc = "Address detection mode 1"]
# [inline (always)]
pub fn set_addm1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 23usize)) | (((val as u32) & 0x01) << 23usize) ; } # [doc = "Address 1 of the USART terminal"]
# [inline (always)]
pub const fn addr1 (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Address 1 of the USART terminal"]
# [inline (always)]
pub fn set_addr1 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for Ctl2 { # [inline (always)]
fn default () -> Ctl2 { Ctl2 (0) } } impl core :: fmt :: Debug for Ctl2 { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ctl2") . field ("errie" , & self . errie ()) . field ("iren" , & self . iren ()) . field ("irlp" , & self . irlp ()) . field ("hden" , & self . hden ()) . field ("nken" , & self . nken ()) . field ("scen" , & self . scen ()) . field ("denr" , & self . denr ()) . field ("dent" , & self . dent ()) . field ("rtsen" , & self . rtsen ()) . field ("ctsen" , & self . ctsen ()) . field ("ctsie" , & self . ctsie ()) . field ("osb" , & self . osb ()) . field ("ovrd" , & self . ovrd ()) . field ("ddre" , & self . ddre ()) . field ("dem" , & self . dem ()) . field ("dep" , & self . dep ()) . field ("amen1" , & self . amen1 ()) . field ("scrtnum" , & self . scrtnum ()) . field ("wum" , & self . wum ()) . field ("wuie" , & self . wuie ()) . field ("addm1" , & self . addm1 ()) . field ("addr1" , & self . addr1 ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ctl2 { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ctl2 {{ errie: {=bool:?}, iren: {=bool:?}, irlp: {=bool:?}, hden: {=bool:?}, nken: {=bool:?}, scen: {=bool:?}, denr: {=bool:?}, dent: {=bool:?}, rtsen: {=bool:?}, ctsen: {=bool:?}, ctsie: {=bool:?}, osb: {=bool:?}, ovrd: {=bool:?}, ddre: {=bool:?}, dem: {=bool:?}, dep: {=bool:?}, amen1: {=bool:?}, scrtnum: {=u8:?}, wum: {=u8:?}, wuie: {=bool:?}, addm1: {=bool:?}, addr1: {=u8:?} }}" , self . errie () , self . iren () , self . irlp () , self . hden () , self . nken () , self . scen () , self . denr () , self . dent () , self . rtsen () , self . ctsen () , self . ctsie () , self . osb () , self . ovrd () , self . ddre () , self . dem () , self . dep () , self . amen1 () , self . scrtnum () , self . wum () , self . wuie () , self . addm1 () , self . addr1 ()) } } # [doc = "USART FIFO control and status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Fcs (pub u32) ; impl Fcs { # [doc = "Early NACK when smartcard mode is selected"]
# [inline (always)]
pub const fn elnack (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Early NACK when smartcard mode is selected"]
# [inline (always)]
pub fn set_elnack (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Bit 3_4 of receive FIFO counter number"]
# [inline (always)]
pub const fn rfcnt_3_4 (& self) -> u8 { let val = (self . 0 >> 1usize) & 0x03 ; val as u8 } # [doc = "Bit 3_4 of receive FIFO counter number"]
# [inline (always)]
pub fn set_rfcnt_3_4 (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 1usize)) | (((val as u32) & 0x03) << 1usize) ; } # [doc = "Receive FIFO threshold flag"]
# [inline (always)]
pub const fn rft (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO threshold flag"]
# [inline (always)]
pub fn set_rft (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Transmit FIFO threshold flag"]
# [inline (always)]
pub const fn tft (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO threshold flag"]
# [inline (always)]
pub fn set_tft (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Transmit FIFO empty flag"]
# [inline (always)]
pub const fn tfe (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO empty flag"]
# [inline (always)]
pub fn set_tfe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Transmit FIFO full flag"]
# [inline (always)]
pub const fn tff (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO full flag"]
# [inline (always)]
pub fn set_tff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "FIFO enable"]
# [inline (always)]
pub const fn fen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "FIFO enable"]
# [inline (always)]
pub fn set_fen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "Receive FIFO full interrupt enable"]
# [inline (always)]
pub const fn rffie (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO full interrupt enable"]
# [inline (always)]
pub fn set_rffie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Receive FIFO empty flag"]
# [inline (always)]
pub const fn rfe (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO empty flag"]
# [inline (always)]
pub fn set_rfe (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Receive FIFO full flag"]
# [inline (always)]
pub const fn rff (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO full flag"]
# [inline (always)]
pub fn set_rff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "Receive FIFO counter number"]
# [inline (always)]
pub const fn rfcnt (& self) -> u8 { let val = (self . 0 >> 12usize) & 0x07 ; val as u8 } # [doc = "Receive FIFO counter number"]
# [inline (always)]
pub fn set_rfcnt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 12usize)) | (((val as u32) & 0x07) << 12usize) ; } # [doc = "Receive FIFO full interrupt flag"]
# [inline (always)]
pub const fn rffif (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO full interrupt flag"]
# [inline (always)]
pub fn set_rffif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "Receive FIFO threshold configuration"]
# [inline (always)]
pub const fn rftcfg (& self) -> u8 { let val = (self . 0 >> 16usize) & 0x07 ; val as u8 } # [doc = "Receive FIFO threshold configuration"]
# [inline (always)]
pub fn set_rftcfg (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 16usize)) | (((val as u32) & 0x07) << 16usize) ; } # [doc = "Transmit FIFO threshold configuration"]
# [inline (always)]
pub const fn tftcfg (& self) -> u8 { let val = (self . 0 >> 19usize) & 0x07 ; val as u8 } # [doc = "Transmit FIFO threshold configuration"]
# [inline (always)]
pub fn set_tftcfg (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 19usize)) | (((val as u32) & 0x07) << 19usize) ; } # [doc = "Receive FIFO threshold interrupt flag"]
# [inline (always)]
pub const fn rftif (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO threshold interrupt flag"]
# [inline (always)]
pub fn set_rftif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } # [doc = "Transmit FIFO empty interrupt flag"]
# [inline (always)]
pub const fn tfeif (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO empty interrupt flag"]
# [inline (always)]
pub fn set_tfeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Transmit FIFO threshold interrupt flag"]
# [inline (always)]
pub const fn tftif (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO threshold interrupt flag"]
# [inline (always)]
pub fn set_tftif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Transmit FIFO empty flag clear"]
# [inline (always)]
pub const fn tfec (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO empty flag clear"]
# [inline (always)]
pub fn set_tfec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "Receive FIFO threshold interrupt enable"]
# [inline (always)]
pub const fn rftie (& self) -> bool { let val = (self . 0 >> 27usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO threshold interrupt enable"]
# [inline (always)]
pub fn set_rftie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 27usize)) | (((val as u32) & 0x01) << 27usize) ; } # [doc = "Transmit FIFO threshold interrupt enable"]
# [inline (always)]
pub const fn tftie (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO threshold interrupt enable"]
# [inline (always)]
pub fn set_tftie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Transmit FIFO empty interrupt enable"]
# [inline (always)]
pub const fn tfeie (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Transmit FIFO empty interrupt enable"]
# [inline (always)]
pub fn set_tfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Fcs { # [inline (always)]
fn default () -> Fcs { Fcs (0) } } impl core :: fmt :: Debug for Fcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Fcs") . field ("elnack" , & self . elnack ()) . field ("rfcnt_3_4" , & self . rfcnt_3_4 ()) . field ("rft" , & self . rft ()) . field ("tft" , & self . tft ()) . field ("tfe" , & self . tfe ()) . field ("tff" , & self . tff ()) . field ("fen" , & self . fen ()) . field ("rffie" , & self . rffie ()) . field ("rfe" , & self . rfe ()) . field ("rff" , & self . rff ()) . field ("rfcnt" , & self . rfcnt ()) . field ("rffif" , & self . rffif ()) . field ("rftcfg" , & self . rftcfg ()) . field ("tftcfg" , & self . tftcfg ()) . field ("rftif" , & self . rftif ()) . field ("tfeif" , & self . tfeif ()) . field ("tftif" , & self . tftif ()) . field ("tfec" , & self . tfec ()) . field ("rftie" , & self . rftie ()) . field ("tftie" , & self . tftie ()) . field ("tfeie" , & self . tfeie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Fcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Fcs {{ elnack: {=bool:?}, rfcnt_3_4: {=u8:?}, rft: {=bool:?}, tft: {=bool:?}, tfe: {=bool:?}, tff: {=bool:?}, fen: {=bool:?}, rffie: {=bool:?}, rfe: {=bool:?}, rff: {=bool:?}, rfcnt: {=u8:?}, rffif: {=bool:?}, rftcfg: {=u8:?}, tftcfg: {=u8:?}, rftif: {=bool:?}, tfeif: {=bool:?}, tftif: {=bool:?}, tfec: {=bool:?}, rftie: {=bool:?}, tftie: {=bool:?}, tfeie: {=bool:?} }}" , self . elnack () , self . rfcnt_3_4 () , self . rft () , self . tft () , self . tfe () , self . tff () , self . fen () , self . rffie () , self . rfe () , self . rff () , self . rfcnt () , self . rffif () , self . rftcfg () , self . tftcfg () , self . rftif () , self . tfeif () , self . tftif () , self . tfec () , self . rftie () , self . tftie () , self . tfeie ()) } } # [doc = "Prescaler and guard time configuration register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gp (pub u32) ; impl Gp { # [doc = "Prescaler value for dividing the system clock"]
# [inline (always)]
pub const fn psc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0xff ; val as u8 } # [doc = "Prescaler value for dividing the system clock"]
# [inline (always)]
pub fn set_psc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 0usize)) | (((val as u32) & 0xff) << 0usize) ; } # [doc = "Guard time value in smartcard mode"]
# [inline (always)]
pub const fn guat (& self) -> u8 { let val = (self . 0 >> 8usize) & 0xff ; val as u8 } # [doc = "Guard time value in smartcard mode"]
# [inline (always)]
pub fn set_guat (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 8usize)) | (((val as u32) & 0xff) << 8usize) ; } } impl Default for Gp { # [inline (always)]
fn default () -> Gp { Gp (0) } } impl core :: fmt :: Debug for Gp { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gp") . field ("psc" , & self . psc ()) . field ("guat" , & self . guat ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gp { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gp {{ psc: {=u8:?}, guat: {=u8:?} }}" , self . psc () , self . guat ()) } } # [doc = "Interrupt status clear register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Intc (pub u32) ; impl Intc { # [doc = "Parity error clear"]
# [inline (always)]
pub const fn pec (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Parity error clear"]
# [inline (always)]
pub fn set_pec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Frame error flag clear"]
# [inline (always)]
pub const fn fec (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Frame error flag clear"]
# [inline (always)]
pub fn set_fec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Noise detected clear"]
# [inline (always)]
pub const fn nec (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Noise detected clear"]
# [inline (always)]
pub fn set_nec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Overrun error clear"]
# [inline (always)]
pub const fn orec (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Overrun error clear"]
# [inline (always)]
pub fn set_orec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Idle line detected clear"]
# [inline (always)]
pub const fn idlec (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Idle line detected clear"]
# [inline (always)]
pub fn set_idlec (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Transmission complete clear"]
# [inline (always)]
pub const fn tcc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmission complete clear"]
# [inline (always)]
pub fn set_tcc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "LIN break detected clear"]
# [inline (always)]
pub const fn lbdc (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "LIN break detected clear"]
# [inline (always)]
pub fn set_lbdc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "CTS change clear"]
# [inline (always)]
pub const fn ctsc (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "CTS change clear"]
# [inline (always)]
pub fn set_ctsc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Receiver timeout clear"]
# [inline (always)]
pub const fn rtc (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Receiver timeout clear"]
# [inline (always)]
pub fn set_rtc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "End of block clear"]
# [inline (always)]
pub const fn ebc (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "End of block clear"]
# [inline (always)]
pub fn set_ebc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "ADDR1 match clear"]
# [inline (always)]
pub const fn amc1 (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "ADDR1 match clear"]
# [inline (always)]
pub fn set_amc1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "ADDR0 match clear"]
# [inline (always)]
pub const fn amc0 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "ADDR0 match clear"]
# [inline (always)]
pub fn set_amc0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Wakeup from Deep-sleep mode clear"]
# [inline (always)]
pub const fn wuc (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Wakeup from Deep-sleep mode clear"]
# [inline (always)]
pub fn set_wuc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } } impl Default for Intc { # [inline (always)]
fn default () -> Intc { Intc (0) } } impl core :: fmt :: Debug for Intc { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Intc") . field ("pec" , & self . pec ()) . field ("fec" , & self . fec ()) . field ("nec" , & self . nec ()) . field ("orec" , & self . orec ()) . field ("idlec" , & self . idlec ()) . field ("tcc" , & self . tcc ()) . field ("lbdc" , & self . lbdc ()) . field ("ctsc" , & self . ctsc ()) . field ("rtc" , & self . rtc ()) . field ("ebc" , & self . ebc ()) . field ("amc1" , & self . amc1 ()) . field ("amc0" , & self . amc0 ()) . field ("wuc" , & self . wuc ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Intc { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Intc {{ pec: {=bool:?}, fec: {=bool:?}, nec: {=bool:?}, orec: {=bool:?}, idlec: {=bool:?}, tcc: {=bool:?}, lbdc: {=bool:?}, ctsc: {=bool:?}, rtc: {=bool:?}, ebc: {=bool:?}, amc1: {=bool:?}, amc0: {=bool:?}, wuc: {=bool:?} }}" , self . pec () , self . fec () , self . nec () , self . orec () , self . idlec () , self . tcc () , self . lbdc () , self . ctsc () , self . rtc () , self . ebc () , self . amc1 () , self . amc0 () , self . wuc ()) } } # [doc = "Receive data register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rdata (pub u32) ; impl Rdata { # [doc = "Receive Data value"]
# [inline (always)]
pub const fn rdata (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x03ff ; val as u16 } # [doc = "Receive Data value"]
# [inline (always)]
pub fn set_rdata (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x03ff << 0usize)) | (((val as u32) & 0x03ff) << 0usize) ; } } impl Default for Rdata { # [inline (always)]
fn default () -> Rdata { Rdata (0) } } impl core :: fmt :: Debug for Rdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rdata") . field ("rdata" , & self . rdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rdata {{ rdata: {=u16:?} }}" , self . rdata ()) } } # [doc = "Receiver timeout register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Rt (pub u32) ; impl Rt { # [doc = "Receiver timeout threshold"]
# [inline (always)]
pub const fn rt (& self) -> u32 { let val = (self . 0 >> 0usize) & 0x00ff_ffff ; val as u32 } # [doc = "Receiver timeout threshold"]
# [inline (always)]
pub fn set_rt (& mut self , val : u32) { self . 0 = (self . 0 & ! (0x00ff_ffff << 0usize)) | (((val as u32) & 0x00ff_ffff) << 0usize) ; } # [doc = "Block Length"]
# [inline (always)]
pub const fn bl (& self) -> u8 { let val = (self . 0 >> 24usize) & 0xff ; val as u8 } # [doc = "Block Length"]
# [inline (always)]
pub fn set_bl (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 24usize)) | (((val as u32) & 0xff) << 24usize) ; } } impl Default for Rt { # [inline (always)]
fn default () -> Rt { Rt (0) } } impl core :: fmt :: Debug for Rt { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Rt") . field ("rt" , & self . rt ()) . field ("bl" , & self . bl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Rt { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Rt {{ rt: {=u32:?}, bl: {=u8:?} }}" , self . rt () , self . bl ()) } } # [doc = "Status register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Stat (pub u32) ; impl Stat { # [doc = "Parity error flag"]
# [inline (always)]
pub const fn perr (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Parity error flag"]
# [inline (always)]
pub fn set_perr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Frame error flag"]
# [inline (always)]
pub const fn ferr (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Frame error flag"]
# [inline (always)]
pub fn set_ferr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Noise error flag"]
# [inline (always)]
pub const fn nerr (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Noise error flag"]
# [inline (always)]
pub fn set_nerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Overrun error"]
# [inline (always)]
pub const fn orerr (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Overrun error"]
# [inline (always)]
pub fn set_orerr (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "IDLE line detected flag"]
# [inline (always)]
pub const fn idlef (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "IDLE line detected flag"]
# [inline (always)]
pub fn set_idlef (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Interrupt enable"]
# [inline (always)]
pub const fn rbne_rfne (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Interrupt enable"]
# [inline (always)]
pub fn set_rbne_rfne (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Transmission completed"]
# [inline (always)]
pub const fn tc (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Transmission completed"]
# [inline (always)]
pub fn set_tc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "When FIFO is disabled:"]
# [inline (always)]
pub const fn tbe_tfnf (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "When FIFO is disabled:"]
# [inline (always)]
pub fn set_tbe_tfnf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "LIN break detected flag"]
# [inline (always)]
pub const fn lbdf (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "LIN break detected flag"]
# [inline (always)]
pub fn set_lbdf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "CTS change flag"]
# [inline (always)]
pub const fn ctsf (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "CTS change flag"]
# [inline (always)]
pub fn set_ctsf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "CTS level"]
# [inline (always)]
pub const fn cts (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "CTS level"]
# [inline (always)]
pub fn set_cts (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Receiver timeout flag"]
# [inline (always)]
pub const fn rtf (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Receiver timeout flag"]
# [inline (always)]
pub fn set_rtf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "End of block flag"]
# [inline (always)]
pub const fn ebf (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "End of block flag"]
# [inline (always)]
pub fn set_ebf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "ADDR1 match flag"]
# [inline (always)]
pub const fn amf1 (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "ADDR1 match flag"]
# [inline (always)]
pub fn set_amf1 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Busy flag"]
# [inline (always)]
pub const fn bsy (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Busy flag"]
# [inline (always)]
pub fn set_bsy (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "ADDR0 match flag"]
# [inline (always)]
pub const fn amf0 (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "ADDR0 match flag"]
# [inline (always)]
pub fn set_amf0 (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "Send break flag"]
# [inline (always)]
pub const fn sbf (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "Send break flag"]
# [inline (always)]
pub fn set_sbf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Receiver wakeup from mute mode"]
# [inline (always)]
pub const fn rwu (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Receiver wakeup from mute mode"]
# [inline (always)]
pub fn set_rwu (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Wakeup from Deep-sleep mode flag"]
# [inline (always)]
pub const fn wuf (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Wakeup from Deep-sleep mode flag"]
# [inline (always)]
pub fn set_wuf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "Transmit enable acknowledge flag"]
# [inline (always)]
pub const fn tea (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "Transmit enable acknowledge flag"]
# [inline (always)]
pub fn set_tea (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Receive enable acknowledge flag"]
# [inline (always)]
pub const fn rea (& self) -> bool { let val = (self . 0 >> 22usize) & 0x01 ; val != 0 } # [doc = "Receive enable acknowledge flag"]
# [inline (always)]
pub fn set_rea (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 22usize)) | (((val as u32) & 0x01) << 22usize) ; } } impl Default for Stat { # [inline (always)]
fn default () -> Stat { Stat (0) } } impl core :: fmt :: Debug for Stat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Stat") . field ("perr" , & self . perr ()) . field ("ferr" , & self . ferr ()) . field ("nerr" , & self . nerr ()) . field ("orerr" , & self . orerr ()) . field ("idlef" , & self . idlef ()) . field ("rbne_rfne" , & self . rbne_rfne ()) . field ("tc" , & self . tc ()) . field ("tbe_tfnf" , & self . tbe_tfnf ()) . field ("lbdf" , & self . lbdf ()) . field ("ctsf" , & self . ctsf ()) . field ("cts" , & self . cts ()) . field ("rtf" , & self . rtf ()) . field ("ebf" , & self . ebf ()) . field ("amf1" , & self . amf1 ()) . field ("bsy" , & self . bsy ()) . field ("amf0" , & self . amf0 ()) . field ("sbf" , & self . sbf ()) . field ("rwu" , & self . rwu ()) . field ("wuf" , & self . wuf ()) . field ("tea" , & self . tea ()) . field ("rea" , & self . rea ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Stat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Stat {{ perr: {=bool:?}, ferr: {=bool:?}, nerr: {=bool:?}, orerr: {=bool:?}, idlef: {=bool:?}, rbne_rfne: {=bool:?}, tc: {=bool:?}, tbe_tfnf: {=bool:?}, lbdf: {=bool:?}, ctsf: {=bool:?}, cts: {=bool:?}, rtf: {=bool:?}, ebf: {=bool:?}, amf1: {=bool:?}, bsy: {=bool:?}, amf0: {=bool:?}, sbf: {=bool:?}, rwu: {=bool:?}, wuf: {=bool:?}, tea: {=bool:?}, rea: {=bool:?} }}" , self . perr () , self . ferr () , self . nerr () , self . orerr () , self . idlef () , self . rbne_rfne () , self . tc () , self . tbe_tfnf () , self . lbdf () , self . ctsf () , self . cts () , self . rtf () , self . ebf () , self . amf1 () , self . bsy () , self . amf0 () , self . sbf () , self . rwu () , self . wuf () , self . tea () , self . rea ()) } } # [doc = "Transmit data register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Tdata (pub u32) ; impl Tdata { # [doc = "Transmit Data value"]
# [inline (always)]
pub const fn tdata (& self) -> u16 { let val = (self . 0 >> 0usize) & 0x03ff ; val as u16 } # [doc = "Transmit Data value"]
# [inline (always)]
pub fn set_tdata (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x03ff << 0usize)) | (((val as u32) & 0x03ff) << 0usize) ; } } impl Default for Tdata { # [inline (always)]
fn default () -> Tdata { Tdata (0) } } impl core :: fmt :: Debug for Tdata { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Tdata") . field ("tdata" , & self . tdata ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Tdata { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Tdata {{ tdata: {=u16:?} }}" , self . tdata ()) } } }
