#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "USB on the go high speed"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Usbhs0Pwrclk { ptr : * mut u8 } unsafe impl Send for Usbhs0Pwrclk { } unsafe impl Sync for Usbhs0Pwrclk { } impl Usbhs0Pwrclk { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "power and clock gating control register (PWRCLKCTL)"]
# [inline (always)]
pub const fn pwrclkctl (self) -> crate :: common :: Reg < regs :: Pwrclkctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } } pub mod regs { # [doc = "power and clock gating control register (PWRCLKCTL)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Pwrclkctl (pub u32) ; impl Pwrclkctl { # [doc = "Stop the USB clock"]
# [inline (always)]
pub const fn suclk (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Stop the USB clock"]
# [inline (always)]
pub fn set_suclk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Stop HCLK"]
# [inline (always)]
pub const fn shclk (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Stop HCLK"]
# [inline (always)]
pub fn set_shclk (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "PHY is in suspend status"]
# [inline (always)]
pub const fn susp (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "PHY is in suspend status"]
# [inline (always)]
pub fn set_susp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "internal clock gating enable"]
# [inline (always)]
pub const fn scgen (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "internal clock gating enable"]
# [inline (always)]
pub fn set_scgen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "PHY is in shallow sleep status"]
# [inline (always)]
pub const fn ssleep (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "PHY is in shallow sleep status"]
# [inline (always)]
pub fn set_ssleep (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "PHY is in deep sleep status"]
# [inline (always)]
pub const fn dsleep (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "PHY is in deep sleep status"]
# [inline (always)]
pub fn set_dsleep (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } } impl Default for Pwrclkctl { # [inline (always)]
fn default () -> Pwrclkctl { Pwrclkctl (0) } } impl core :: fmt :: Debug for Pwrclkctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Pwrclkctl") . field ("suclk" , & self . suclk ()) . field ("shclk" , & self . shclk ()) . field ("susp" , & self . susp ()) . field ("scgen" , & self . scgen ()) . field ("ssleep" , & self . ssleep ()) . field ("dsleep" , & self . dsleep ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Pwrclkctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Pwrclkctl {{ suclk: {=bool:?}, shclk: {=bool:?}, susp: {=bool:?}, scgen: {=bool:?}, ssleep: {=bool:?}, dsleep: {=bool:?} }}" , self . suclk () , self . shclk () , self . susp () , self . scgen () , self . ssleep () , self . dsleep ()) } } }