#![allow(clippy::missing_safety_doc)]
                #![allow(clippy::identity_op)]
                #![allow(clippy::unnecessary_cast)]
                #![allow(clippy::erasing_op)]

# [doc = "USB full speed global registers"]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct UsbfsGlobal { ptr : * mut u8 } unsafe impl Send for UsbfsGlobal { } unsafe impl Sync for UsbfsGlobal { } impl UsbfsGlobal { # [inline (always)]
pub const unsafe fn from_ptr (ptr : * mut ()) -> Self { Self { ptr : ptr as _ , } } # [inline (always)]
pub const fn as_ptr (& self) -> * mut () { self . ptr as _ } # [doc = "Global OTG control and status register (USBFS_GOTGCS)"]
# [inline (always)]
pub const fn gotgcs (self) -> crate :: common :: Reg < regs :: Gotgcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0usize) as _) } } # [doc = "Global OTG interrupt flag register (USBFS_GOTGINTF)"]
# [inline (always)]
pub const fn gotgintf (self) -> crate :: common :: Reg < regs :: Gotgintf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x04usize) as _) } } # [doc = "Global AHB control and status register (USBFS_GAHBCS)"]
# [inline (always)]
pub const fn gahbcs (self) -> crate :: common :: Reg < regs :: Gahbcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x08usize) as _) } } # [doc = "Global USB control and status register (OTG_FS_GUSBCSR)"]
# [inline (always)]
pub const fn gusbcs (self) -> crate :: common :: Reg < regs :: Gusbcs , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0cusize) as _) } } # [doc = "Global reset control register (USBFS_GRSTCTL)"]
# [inline (always)]
pub const fn grstctl (self) -> crate :: common :: Reg < regs :: Grstctl , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x10usize) as _) } } # [doc = "Global interrupt flag register (USBFS_GINTF)"]
# [inline (always)]
pub const fn gintf (self) -> crate :: common :: Reg < regs :: Gintf , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x14usize) as _) } } # [doc = "Global interrupt enable register (USBFS_GINTEN)"]
# [inline (always)]
pub const fn ginten (self) -> crate :: common :: Reg < regs :: Ginten , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x18usize) as _) } } # [doc = "Global Receive status read(Device mode)"]
# [inline (always)]
pub const fn grstatr_device (self) -> crate :: common :: Reg < regs :: GrstatrDevice , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Global Receive status read(Host mode)"]
# [inline (always)]
pub const fn grstatr_host (self) -> crate :: common :: Reg < regs :: GrstatrHost , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x1cusize) as _) } } # [doc = "Global Receive status pop(Device mode)"]
# [inline (always)]
pub const fn grstatp_device (self) -> crate :: common :: Reg < regs :: GrstatpDevice , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Global Receive status pop(Host mode)"]
# [inline (always)]
pub const fn grstatp_host (self) -> crate :: common :: Reg < regs :: GrstatpHost , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x20usize) as _) } } # [doc = "Global Receive FIFO size register (USBFS_GRFLEN)"]
# [inline (always)]
pub const fn grflen (self) -> crate :: common :: Reg < regs :: Grflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x24usize) as _) } } # [doc = "Device IN endpoint 0 transmit FIFO length (Device mode)"]
# [inline (always)]
pub const fn diep0tflen (self) -> crate :: common :: Reg < regs :: Diep0tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Host non-periodic transmit FIFO length register (Host mode)"]
# [inline (always)]
pub const fn hnptflen (self) -> crate :: common :: Reg < regs :: Hnptflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x28usize) as _) } } # [doc = "Host non-periodic transmit FIFO/queue status register (HNPTFQSTAT)"]
# [inline (always)]
pub const fn hnptfqstat (self) -> crate :: common :: Reg < regs :: Hnptfqstat , crate :: common :: R > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x2cusize) as _) } } # [doc = "Global core configuration register (USBFS_GCCFG)"]
# [inline (always)]
pub const fn gccfg (self) -> crate :: common :: Reg < regs :: Gccfg , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x38usize) as _) } } # [doc = "core ID register"]
# [inline (always)]
pub const fn cid (self) -> crate :: common :: Reg < regs :: Cid , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x3cusize) as _) } } # [doc = "Host periodic transmit FIFO length register (HPTFLEN)"]
# [inline (always)]
pub const fn hptflen (self) -> crate :: common :: Reg < regs :: Hptflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0100usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register (DIEP1TFLEN)"]
# [inline (always)]
pub const fn diep1tflen (self) -> crate :: common :: Reg < regs :: Diep1tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0104usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register (DIEP2TFLEN)"]
# [inline (always)]
pub const fn diep2tflen (self) -> crate :: common :: Reg < regs :: Diep2tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x0108usize) as _) } } # [doc = "device IN endpoint transmit FIFO size register (FS_DIEP3TXFLEN)"]
# [inline (always)]
pub const fn diep3tflen (self) -> crate :: common :: Reg < regs :: Diep3tflen , crate :: common :: RW > { unsafe { crate :: common :: Reg :: from_ptr (self . ptr . add (0x010cusize) as _) } } } pub mod regs { # [doc = "core ID register"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Cid (pub u32) ; impl Cid { # [doc = "Core ID"]
# [inline (always)]
pub const fn cid (& self) -> u32 { let val = (self . 0 >> 0usize) & 0xffff_ffff ; val as u32 } # [doc = "Core ID"]
# [inline (always)]
pub fn set_cid (& mut self , val : u32) { self . 0 = (self . 0 & ! (0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize) ; } } impl Default for Cid { # [inline (always)]
fn default () -> Cid { Cid (0) } } impl core :: fmt :: Debug for Cid { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Cid") . field ("cid" , & self . cid ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Cid { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Cid {{ cid: {=u32:?} }}" , self . cid ()) } } # [doc = "Device IN endpoint 0 transmit FIFO length (Device mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep0tflen (pub u32) ; impl Diep0tflen { # [doc = "in endpoint 0 Tx RAM start address"]
# [inline (always)]
pub const fn iep0txrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "in endpoint 0 Tx RAM start address"]
# [inline (always)]
pub fn set_iep0txrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "in endpoint 0 Tx FIFO depth"]
# [inline (always)]
pub const fn iep0txfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "in endpoint 0 Tx FIFO depth"]
# [inline (always)]
pub fn set_iep0txfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep0tflen { # [inline (always)]
fn default () -> Diep0tflen { Diep0tflen (0) } } impl core :: fmt :: Debug for Diep0tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep0tflen") . field ("iep0txrsar" , & self . iep0txrsar ()) . field ("iep0txfd" , & self . iep0txfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep0tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep0tflen {{ iep0txrsar: {=u16:?}, iep0txfd: {=u16:?} }}" , self . iep0txrsar () , self . iep0txfd ()) } } # [doc = "device IN endpoint transmit FIFO size register (DIEP1TFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep1tflen (pub u32) ; impl Diep1tflen { # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep1tflen { # [inline (always)]
fn default () -> Diep1tflen { Diep1tflen (0) } } impl core :: fmt :: Debug for Diep1tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep1tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep1tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep1tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "device IN endpoint transmit FIFO size register (DIEP2TFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep2tflen (pub u32) ; impl Diep2tflen { # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep2tflen { # [inline (always)]
fn default () -> Diep2tflen { Diep2tflen (0) } } impl core :: fmt :: Debug for Diep2tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep2tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep2tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep2tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "device IN endpoint transmit FIFO size register (FS_DIEP3TXFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Diep3tflen (pub u32) ; impl Diep3tflen { # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub const fn ieptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "IN endpoint FIFO4 transmit RAM start address"]
# [inline (always)]
pub fn set_ieptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub const fn ieptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "IN endpoint TxFIFO depth"]
# [inline (always)]
pub fn set_ieptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Diep3tflen { # [inline (always)]
fn default () -> Diep3tflen { Diep3tflen (0) } } impl core :: fmt :: Debug for Diep3tflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Diep3tflen") . field ("ieptxrsar" , & self . ieptxrsar ()) . field ("ieptxfd" , & self . ieptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Diep3tflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Diep3tflen {{ ieptxrsar: {=u16:?}, ieptxfd: {=u16:?} }}" , self . ieptxrsar () , self . ieptxfd ()) } } # [doc = "Global AHB control and status register (USBFS_GAHBCS)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gahbcs (pub u32) ; impl Gahbcs { # [doc = "Global interrupt enable"]
# [inline (always)]
pub const fn ginten (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Global interrupt enable"]
# [inline (always)]
pub fn set_ginten (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Tx FIFO threshold"]
# [inline (always)]
pub const fn txfth (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Tx FIFO threshold"]
# [inline (always)]
pub fn set_txfth (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Periodic Tx FIFO threshold"]
# [inline (always)]
pub const fn ptxfth (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Periodic Tx FIFO threshold"]
# [inline (always)]
pub fn set_ptxfth (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } } impl Default for Gahbcs { # [inline (always)]
fn default () -> Gahbcs { Gahbcs (0) } } impl core :: fmt :: Debug for Gahbcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gahbcs") . field ("ginten" , & self . ginten ()) . field ("txfth" , & self . txfth ()) . field ("ptxfth" , & self . ptxfth ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gahbcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gahbcs {{ ginten: {=bool:?}, txfth: {=bool:?}, ptxfth: {=bool:?} }}" , self . ginten () , self . txfth () , self . ptxfth ()) } } # [doc = "Global core configuration register (USBFS_GCCFG)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gccfg (pub u32) ; impl Gccfg { # [doc = "Power on"]
# [inline (always)]
pub const fn pwron (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "Power on"]
# [inline (always)]
pub fn set_pwron (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "The VBUS A-device Comparer enable"]
# [inline (always)]
pub const fn vbusacen (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "The VBUS A-device Comparer enable"]
# [inline (always)]
pub fn set_vbusacen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "The VBUS B-device Comparer enable"]
# [inline (always)]
pub const fn vbusbcen (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "The VBUS B-device Comparer enable"]
# [inline (always)]
pub fn set_vbusbcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "SOF output enable"]
# [inline (always)]
pub const fn sofoen (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "SOF output enable"]
# [inline (always)]
pub fn set_sofoen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "VBUS ignored"]
# [inline (always)]
pub const fn vbusig (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "VBUS ignored"]
# [inline (always)]
pub fn set_vbusig (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } } impl Default for Gccfg { # [inline (always)]
fn default () -> Gccfg { Gccfg (0) } } impl core :: fmt :: Debug for Gccfg { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gccfg") . field ("pwron" , & self . pwron ()) . field ("vbusacen" , & self . vbusacen ()) . field ("vbusbcen" , & self . vbusbcen ()) . field ("sofoen" , & self . sofoen ()) . field ("vbusig" , & self . vbusig ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gccfg { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gccfg {{ pwron: {=bool:?}, vbusacen: {=bool:?}, vbusbcen: {=bool:?}, sofoen: {=bool:?}, vbusig: {=bool:?} }}" , self . pwron () , self . vbusacen () , self . vbusbcen () , self . sofoen () , self . vbusig ()) } } # [doc = "Global interrupt enable register (USBFS_GINTEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Ginten (pub u32) ; impl Ginten { # [doc = "Mode fault interrupt enable"]
# [inline (always)]
pub const fn mfie (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mode fault interrupt enable"]
# [inline (always)]
pub fn set_mfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "OTG interrupt enable"]
# [inline (always)]
pub const fn otgie (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "OTG interrupt enable"]
# [inline (always)]
pub fn set_otgie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Start of frame interrupt enable"]
# [inline (always)]
pub const fn sofie (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Start of frame interrupt enable"]
# [inline (always)]
pub fn set_sofie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "Receive FIFO non-empty interrupt enable"]
# [inline (always)]
pub const fn rxfneie (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "Receive FIFO non-empty interrupt enable"]
# [inline (always)]
pub fn set_rxfneie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Non-periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub const fn nptxfeie (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Non-periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub fn set_nptxfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Global non-periodic IN NAK effective interrupt enable"]
# [inline (always)]
pub const fn gnpinakie (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Global non-periodic IN NAK effective interrupt enable"]
# [inline (always)]
pub fn set_gnpinakie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Global OUT NAK effective interrupt enable"]
# [inline (always)]
pub const fn gonakie (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Global OUT NAK effective interrupt enable"]
# [inline (always)]
pub fn set_gonakie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Early suspend interrupt enable"]
# [inline (always)]
pub const fn espie (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Early suspend interrupt enable"]
# [inline (always)]
pub fn set_espie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "USB suspend interrupt enable"]
# [inline (always)]
pub const fn spie (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "USB suspend interrupt enable"]
# [inline (always)]
pub fn set_spie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "USB reset interrupt enable"]
# [inline (always)]
pub const fn rstie (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "USB reset interrupt enable"]
# [inline (always)]
pub fn set_rstie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Enumeration finish interrupt enable"]
# [inline (always)]
pub const fn enumfie (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Enumeration finish interrupt enable"]
# [inline (always)]
pub fn set_enumfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Isochronous OUT packet dropped interrupt enable"]
# [inline (always)]
pub const fn isoopdie (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Isochronous OUT packet dropped interrupt enable"]
# [inline (always)]
pub fn set_isoopdie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "End of periodic frame interrupt enable"]
# [inline (always)]
pub const fn eopfie (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "End of periodic frame interrupt enable"]
# [inline (always)]
pub fn set_eopfie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "IN endpoints interrupt enable"]
# [inline (always)]
pub const fn iepie (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "IN endpoints interrupt enable"]
# [inline (always)]
pub fn set_iepie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "OUT endpoints interrupt enable"]
# [inline (always)]
pub const fn oepie (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "OUT endpoints interrupt enable"]
# [inline (always)]
pub fn set_oepie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "isochronous IN transfer not complete interrupt enable"]
# [inline (always)]
pub const fn isoincie (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "isochronous IN transfer not complete interrupt enable"]
# [inline (always)]
pub fn set_isoincie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "periodic transfer not compelete Interrupt enable(Host mode)/isochronous OUT transfer not complete interrupt enable(Device mode)"]
# [inline (always)]
pub const fn pxncie_isooncie (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "periodic transfer not compelete Interrupt enable(Host mode)/isochronous OUT transfer not complete interrupt enable(Device mode)"]
# [inline (always)]
pub fn set_pxncie_isooncie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Host port interrupt enable"]
# [inline (always)]
pub const fn hpie (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Host port interrupt enable"]
# [inline (always)]
pub fn set_hpie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Host channels interrupt enable"]
# [inline (always)]
pub const fn hcie (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Host channels interrupt enable"]
# [inline (always)]
pub fn set_hcie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub const fn ptxfeie (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Periodic TxFIFO empty interrupt enable"]
# [inline (always)]
pub fn set_ptxfeie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "ID pin status change interrupt enable"]
# [inline (always)]
pub const fn idpscie (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "ID pin status change interrupt enable"]
# [inline (always)]
pub fn set_idpscie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Disconnect interrupt enable"]
# [inline (always)]
pub const fn discie (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Disconnect interrupt enable"]
# [inline (always)]
pub fn set_discie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Session interrupt enable"]
# [inline (always)]
pub const fn sesie (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Session interrupt enable"]
# [inline (always)]
pub fn set_sesie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Wakeup interrupt enable"]
# [inline (always)]
pub const fn wkupie (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Wakeup interrupt enable"]
# [inline (always)]
pub fn set_wkupie (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Ginten { # [inline (always)]
fn default () -> Ginten { Ginten (0) } } impl core :: fmt :: Debug for Ginten { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Ginten") . field ("mfie" , & self . mfie ()) . field ("otgie" , & self . otgie ()) . field ("sofie" , & self . sofie ()) . field ("rxfneie" , & self . rxfneie ()) . field ("nptxfeie" , & self . nptxfeie ()) . field ("gnpinakie" , & self . gnpinakie ()) . field ("gonakie" , & self . gonakie ()) . field ("espie" , & self . espie ()) . field ("spie" , & self . spie ()) . field ("rstie" , & self . rstie ()) . field ("enumfie" , & self . enumfie ()) . field ("isoopdie" , & self . isoopdie ()) . field ("eopfie" , & self . eopfie ()) . field ("iepie" , & self . iepie ()) . field ("oepie" , & self . oepie ()) . field ("isoincie" , & self . isoincie ()) . field ("pxncie_isooncie" , & self . pxncie_isooncie ()) . field ("hpie" , & self . hpie ()) . field ("hcie" , & self . hcie ()) . field ("ptxfeie" , & self . ptxfeie ()) . field ("idpscie" , & self . idpscie ()) . field ("discie" , & self . discie ()) . field ("sesie" , & self . sesie ()) . field ("wkupie" , & self . wkupie ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Ginten { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Ginten {{ mfie: {=bool:?}, otgie: {=bool:?}, sofie: {=bool:?}, rxfneie: {=bool:?}, nptxfeie: {=bool:?}, gnpinakie: {=bool:?}, gonakie: {=bool:?}, espie: {=bool:?}, spie: {=bool:?}, rstie: {=bool:?}, enumfie: {=bool:?}, isoopdie: {=bool:?}, eopfie: {=bool:?}, iepie: {=bool:?}, oepie: {=bool:?}, isoincie: {=bool:?}, pxncie_isooncie: {=bool:?}, hpie: {=bool:?}, hcie: {=bool:?}, ptxfeie: {=bool:?}, idpscie: {=bool:?}, discie: {=bool:?}, sesie: {=bool:?}, wkupie: {=bool:?} }}" , self . mfie () , self . otgie () , self . sofie () , self . rxfneie () , self . nptxfeie () , self . gnpinakie () , self . gonakie () , self . espie () , self . spie () , self . rstie () , self . enumfie () , self . isoopdie () , self . eopfie () , self . iepie () , self . oepie () , self . isoincie () , self . pxncie_isooncie () , self . hpie () , self . hcie () , self . ptxfeie () , self . idpscie () , self . discie () , self . sesie () , self . wkupie ()) } } # [doc = "Global interrupt flag register (USBFS_GINTF)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gintf (pub u32) ; impl Gintf { # [doc = "Current operation mode"]
# [inline (always)]
pub const fn copm (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Current operation mode"]
# [inline (always)]
pub fn set_copm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "Mode fault interrupt flag"]
# [inline (always)]
pub const fn mfif (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "Mode fault interrupt flag"]
# [inline (always)]
pub fn set_mfif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "OTG interrupt flag"]
# [inline (always)]
pub const fn otgif (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "OTG interrupt flag"]
# [inline (always)]
pub fn set_otgif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Start of frame"]
# [inline (always)]
pub const fn sof (& self) -> bool { let val = (self . 0 >> 3usize) & 0x01 ; val != 0 } # [doc = "Start of frame"]
# [inline (always)]
pub fn set_sof (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 3usize)) | (((val as u32) & 0x01) << 3usize) ; } # [doc = "RxFIFO non-empty interrupt flag"]
# [inline (always)]
pub const fn rxfneif (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "RxFIFO non-empty interrupt flag"]
# [inline (always)]
pub fn set_rxfneif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "Non-periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub const fn nptxfeif (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "Non-periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub fn set_nptxfeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "Global Non-Periodic IN NAK effective"]
# [inline (always)]
pub const fn gnpinak (& self) -> bool { let val = (self . 0 >> 6usize) & 0x01 ; val != 0 } # [doc = "Global Non-Periodic IN NAK effective"]
# [inline (always)]
pub fn set_gnpinak (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize) ; } # [doc = "Global OUT NAK effective"]
# [inline (always)]
pub const fn gonak (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Global OUT NAK effective"]
# [inline (always)]
pub fn set_gonak (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "Early suspend"]
# [inline (always)]
pub const fn esp (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Early suspend"]
# [inline (always)]
pub fn set_esp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "USB suspend"]
# [inline (always)]
pub const fn sp (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "USB suspend"]
# [inline (always)]
pub fn set_sp (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "USB reset"]
# [inline (always)]
pub const fn rst (& self) -> bool { let val = (self . 0 >> 12usize) & 0x01 ; val != 0 } # [doc = "USB reset"]
# [inline (always)]
pub fn set_rst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize) ; } # [doc = "Enumeration finished"]
# [inline (always)]
pub const fn enumf (& self) -> bool { let val = (self . 0 >> 13usize) & 0x01 ; val != 0 } # [doc = "Enumeration finished"]
# [inline (always)]
pub fn set_enumf (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize) ; } # [doc = "Isochronous OUT packet dropped interrupt"]
# [inline (always)]
pub const fn isoopdif (& self) -> bool { let val = (self . 0 >> 14usize) & 0x01 ; val != 0 } # [doc = "Isochronous OUT packet dropped interrupt"]
# [inline (always)]
pub fn set_isoopdif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize) ; } # [doc = "End of periodic frame interrupt flag"]
# [inline (always)]
pub const fn eopfif (& self) -> bool { let val = (self . 0 >> 15usize) & 0x01 ; val != 0 } # [doc = "End of periodic frame interrupt flag"]
# [inline (always)]
pub fn set_eopfif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize) ; } # [doc = "IN endpoint interrupt flag"]
# [inline (always)]
pub const fn iepif (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "IN endpoint interrupt flag"]
# [inline (always)]
pub fn set_iepif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "OUT endpoint interrupt flag"]
# [inline (always)]
pub const fn oepif (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "OUT endpoint interrupt flag"]
# [inline (always)]
pub fn set_oepif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } # [doc = "Isochronous IN transfer Not Complete Interrupt Flag"]
# [inline (always)]
pub const fn isoincif (& self) -> bool { let val = (self . 0 >> 20usize) & 0x01 ; val != 0 } # [doc = "Isochronous IN transfer Not Complete Interrupt Flag"]
# [inline (always)]
pub fn set_isoincif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 20usize)) | (((val as u32) & 0x01) << 20usize) ; } # [doc = "periodic transfer not complete interrupt flag(Host mode)/isochronous OUT transfer not complete interrupt flag(Device mode)"]
# [inline (always)]
pub const fn pxncif_isooncif (& self) -> bool { let val = (self . 0 >> 21usize) & 0x01 ; val != 0 } # [doc = "periodic transfer not complete interrupt flag(Host mode)/isochronous OUT transfer not complete interrupt flag(Device mode)"]
# [inline (always)]
pub fn set_pxncif_isooncif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 21usize)) | (((val as u32) & 0x01) << 21usize) ; } # [doc = "Host port interrupt flag"]
# [inline (always)]
pub const fn hpif (& self) -> bool { let val = (self . 0 >> 24usize) & 0x01 ; val != 0 } # [doc = "Host port interrupt flag"]
# [inline (always)]
pub fn set_hpif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 24usize)) | (((val as u32) & 0x01) << 24usize) ; } # [doc = "Host channels interrupt flag"]
# [inline (always)]
pub const fn hcif (& self) -> bool { let val = (self . 0 >> 25usize) & 0x01 ; val != 0 } # [doc = "Host channels interrupt flag"]
# [inline (always)]
pub fn set_hcif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 25usize)) | (((val as u32) & 0x01) << 25usize) ; } # [doc = "Periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub const fn ptxfeif (& self) -> bool { let val = (self . 0 >> 26usize) & 0x01 ; val != 0 } # [doc = "Periodic TxFIFO empty interrupt flag"]
# [inline (always)]
pub fn set_ptxfeif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 26usize)) | (((val as u32) & 0x01) << 26usize) ; } # [doc = "ID pin status change"]
# [inline (always)]
pub const fn idpsc (& self) -> bool { let val = (self . 0 >> 28usize) & 0x01 ; val != 0 } # [doc = "ID pin status change"]
# [inline (always)]
pub fn set_idpsc (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 28usize)) | (((val as u32) & 0x01) << 28usize) ; } # [doc = "Disconnect interrupt flag"]
# [inline (always)]
pub const fn discif (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Disconnect interrupt flag"]
# [inline (always)]
pub fn set_discif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Session interrupt flag"]
# [inline (always)]
pub const fn sesif (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Session interrupt flag"]
# [inline (always)]
pub fn set_sesif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } # [doc = "Wakeup interrupt flag"]
# [inline (always)]
pub const fn wkupif (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "Wakeup interrupt flag"]
# [inline (always)]
pub fn set_wkupif (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Gintf { # [inline (always)]
fn default () -> Gintf { Gintf (0) } } impl core :: fmt :: Debug for Gintf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gintf") . field ("copm" , & self . copm ()) . field ("mfif" , & self . mfif ()) . field ("otgif" , & self . otgif ()) . field ("sof" , & self . sof ()) . field ("rxfneif" , & self . rxfneif ()) . field ("nptxfeif" , & self . nptxfeif ()) . field ("gnpinak" , & self . gnpinak ()) . field ("gonak" , & self . gonak ()) . field ("esp" , & self . esp ()) . field ("sp" , & self . sp ()) . field ("rst" , & self . rst ()) . field ("enumf" , & self . enumf ()) . field ("isoopdif" , & self . isoopdif ()) . field ("eopfif" , & self . eopfif ()) . field ("iepif" , & self . iepif ()) . field ("oepif" , & self . oepif ()) . field ("isoincif" , & self . isoincif ()) . field ("pxncif_isooncif" , & self . pxncif_isooncif ()) . field ("hpif" , & self . hpif ()) . field ("hcif" , & self . hcif ()) . field ("ptxfeif" , & self . ptxfeif ()) . field ("idpsc" , & self . idpsc ()) . field ("discif" , & self . discif ()) . field ("sesif" , & self . sesif ()) . field ("wkupif" , & self . wkupif ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gintf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gintf {{ copm: {=bool:?}, mfif: {=bool:?}, otgif: {=bool:?}, sof: {=bool:?}, rxfneif: {=bool:?}, nptxfeif: {=bool:?}, gnpinak: {=bool:?}, gonak: {=bool:?}, esp: {=bool:?}, sp: {=bool:?}, rst: {=bool:?}, enumf: {=bool:?}, isoopdif: {=bool:?}, eopfif: {=bool:?}, iepif: {=bool:?}, oepif: {=bool:?}, isoincif: {=bool:?}, pxncif_isooncif: {=bool:?}, hpif: {=bool:?}, hcif: {=bool:?}, ptxfeif: {=bool:?}, idpsc: {=bool:?}, discif: {=bool:?}, sesif: {=bool:?}, wkupif: {=bool:?} }}" , self . copm () , self . mfif () , self . otgif () , self . sof () , self . rxfneif () , self . nptxfeif () , self . gnpinak () , self . gonak () , self . esp () , self . sp () , self . rst () , self . enumf () , self . isoopdif () , self . eopfif () , self . iepif () , self . oepif () , self . isoincif () , self . pxncif_isooncif () , self . hpif () , self . hcif () , self . ptxfeif () , self . idpsc () , self . discif () , self . sesif () , self . wkupif ()) } } # [doc = "Global OTG control and status register (USBFS_GOTGCS)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gotgcs (pub u32) ; impl Gotgcs { # [doc = "SRP success"]
# [inline (always)]
pub const fn srps (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "SRP success"]
# [inline (always)]
pub fn set_srps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "SRP request"]
# [inline (always)]
pub const fn srpreq (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "SRP request"]
# [inline (always)]
pub fn set_srpreq (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Host success"]
# [inline (always)]
pub const fn hnps (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Host success"]
# [inline (always)]
pub fn set_hnps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "HNP request"]
# [inline (always)]
pub const fn hnpreq (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "HNP request"]
# [inline (always)]
pub fn set_hnpreq (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Host HNP enable"]
# [inline (always)]
pub const fn hhnpen (& self) -> bool { let val = (self . 0 >> 10usize) & 0x01 ; val != 0 } # [doc = "Host HNP enable"]
# [inline (always)]
pub fn set_hhnpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 10usize)) | (((val as u32) & 0x01) << 10usize) ; } # [doc = "Device HNP enabled"]
# [inline (always)]
pub const fn dhnpen (& self) -> bool { let val = (self . 0 >> 11usize) & 0x01 ; val != 0 } # [doc = "Device HNP enabled"]
# [inline (always)]
pub fn set_dhnpen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 11usize)) | (((val as u32) & 0x01) << 11usize) ; } # [doc = "ID pin status"]
# [inline (always)]
pub const fn idps (& self) -> bool { let val = (self . 0 >> 16usize) & 0x01 ; val != 0 } # [doc = "ID pin status"]
# [inline (always)]
pub fn set_idps (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize) ; } # [doc = "Debounce interval"]
# [inline (always)]
pub const fn di (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Debounce interval"]
# [inline (always)]
pub fn set_di (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "A-session valid"]
# [inline (always)]
pub const fn asv (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "A-session valid"]
# [inline (always)]
pub fn set_asv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "B-session valid"]
# [inline (always)]
pub const fn bsv (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "B-session valid"]
# [inline (always)]
pub fn set_bsv (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } } impl Default for Gotgcs { # [inline (always)]
fn default () -> Gotgcs { Gotgcs (0) } } impl core :: fmt :: Debug for Gotgcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gotgcs") . field ("srps" , & self . srps ()) . field ("srpreq" , & self . srpreq ()) . field ("hnps" , & self . hnps ()) . field ("hnpreq" , & self . hnpreq ()) . field ("hhnpen" , & self . hhnpen ()) . field ("dhnpen" , & self . dhnpen ()) . field ("idps" , & self . idps ()) . field ("di" , & self . di ()) . field ("asv" , & self . asv ()) . field ("bsv" , & self . bsv ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gotgcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gotgcs {{ srps: {=bool:?}, srpreq: {=bool:?}, hnps: {=bool:?}, hnpreq: {=bool:?}, hhnpen: {=bool:?}, dhnpen: {=bool:?}, idps: {=bool:?}, di: {=bool:?}, asv: {=bool:?}, bsv: {=bool:?} }}" , self . srps () , self . srpreq () , self . hnps () , self . hnpreq () , self . hhnpen () , self . dhnpen () , self . idps () , self . di () , self . asv () , self . bsv ()) } } # [doc = "Global OTG interrupt flag register (USBFS_GOTGINTF)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gotgintf (pub u32) ; impl Gotgintf { # [doc = "Session end"]
# [inline (always)]
pub const fn sesend (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Session end"]
# [inline (always)]
pub fn set_sesend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "Session request success status change"]
# [inline (always)]
pub const fn srpend (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "Session request success status change"]
# [inline (always)]
pub fn set_srpend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "HNP end"]
# [inline (always)]
pub const fn hnpend (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "HNP end"]
# [inline (always)]
pub fn set_hnpend (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "Host negotiation request detected"]
# [inline (always)]
pub const fn hnpdet (& self) -> bool { let val = (self . 0 >> 17usize) & 0x01 ; val != 0 } # [doc = "Host negotiation request detected"]
# [inline (always)]
pub fn set_hnpdet (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 17usize)) | (((val as u32) & 0x01) << 17usize) ; } # [doc = "A-device timeout"]
# [inline (always)]
pub const fn adto (& self) -> bool { let val = (self . 0 >> 18usize) & 0x01 ; val != 0 } # [doc = "A-device timeout"]
# [inline (always)]
pub fn set_adto (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 18usize)) | (((val as u32) & 0x01) << 18usize) ; } # [doc = "Debounce finish"]
# [inline (always)]
pub const fn df (& self) -> bool { let val = (self . 0 >> 19usize) & 0x01 ; val != 0 } # [doc = "Debounce finish"]
# [inline (always)]
pub fn set_df (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 19usize)) | (((val as u32) & 0x01) << 19usize) ; } } impl Default for Gotgintf { # [inline (always)]
fn default () -> Gotgintf { Gotgintf (0) } } impl core :: fmt :: Debug for Gotgintf { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gotgintf") . field ("sesend" , & self . sesend ()) . field ("srpend" , & self . srpend ()) . field ("hnpend" , & self . hnpend ()) . field ("hnpdet" , & self . hnpdet ()) . field ("adto" , & self . adto ()) . field ("df" , & self . df ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gotgintf { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gotgintf {{ sesend: {=bool:?}, srpend: {=bool:?}, hnpend: {=bool:?}, hnpdet: {=bool:?}, adto: {=bool:?}, df: {=bool:?} }}" , self . sesend () , self . srpend () , self . hnpend () , self . hnpdet () , self . adto () , self . df ()) } } # [doc = "Global Receive FIFO size register (USBFS_GRFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Grflen (pub u32) ; impl Grflen { # [doc = "Rx FIFO depth"]
# [inline (always)]
pub const fn rxfd (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Rx FIFO depth"]
# [inline (always)]
pub fn set_rxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } } impl Default for Grflen { # [inline (always)]
fn default () -> Grflen { Grflen (0) } } impl core :: fmt :: Debug for Grflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Grflen") . field ("rxfd" , & self . rxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Grflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Grflen {{ rxfd: {=u16:?} }}" , self . rxfd ()) } } # [doc = "Global Receive status pop(Device mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatpDevice (pub u32) ; impl GrstatpDevice { # [doc = "Endpoint number"]
# [inline (always)]
pub const fn epnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Endpoint number"]
# [inline (always)]
pub fn set_epnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Recieve packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Recieve packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatpDevice { # [inline (always)]
fn default () -> GrstatpDevice { GrstatpDevice (0) } } impl core :: fmt :: Debug for GrstatpDevice { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatpDevice") . field ("epnum" , & self . epnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatpDevice { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatpDevice {{ epnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . epnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global Receive status pop(Host mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatpHost (pub u32) ; impl GrstatpHost { # [doc = "Channel number"]
# [inline (always)]
pub const fn cnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Channel number"]
# [inline (always)]
pub fn set_cnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Reivece packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Reivece packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatpHost { # [inline (always)]
fn default () -> GrstatpHost { GrstatpHost (0) } } impl core :: fmt :: Debug for GrstatpHost { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatpHost") . field ("cnum" , & self . cnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatpHost { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatpHost {{ cnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . cnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global Receive status read(Device mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatrDevice (pub u32) ; impl GrstatrDevice { # [doc = "Endpoint number"]
# [inline (always)]
pub const fn epnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Endpoint number"]
# [inline (always)]
pub fn set_epnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Recieve packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Recieve packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatrDevice { # [inline (always)]
fn default () -> GrstatrDevice { GrstatrDevice (0) } } impl core :: fmt :: Debug for GrstatrDevice { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatrDevice") . field ("epnum" , & self . epnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatrDevice { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatrDevice {{ epnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . epnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global Receive status read(Host mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct GrstatrHost (pub u32) ; impl GrstatrHost { # [doc = "Channel number"]
# [inline (always)]
pub const fn cnum (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x0f ; val as u8 } # [doc = "Channel number"]
# [inline (always)]
pub fn set_cnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 0usize)) | (((val as u32) & 0x0f) << 0usize) ; } # [doc = "Byte count"]
# [inline (always)]
pub const fn bcount (& self) -> u16 { let val = (self . 0 >> 4usize) & 0x07ff ; val as u16 } # [doc = "Byte count"]
# [inline (always)]
pub fn set_bcount (& mut self , val : u16) { self . 0 = (self . 0 & ! (0x07ff << 4usize)) | (((val as u32) & 0x07ff) << 4usize) ; } # [doc = "Data PID"]
# [inline (always)]
pub const fn dpid (& self) -> u8 { let val = (self . 0 >> 15usize) & 0x03 ; val as u8 } # [doc = "Data PID"]
# [inline (always)]
pub fn set_dpid (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x03 << 15usize)) | (((val as u32) & 0x03) << 15usize) ; } # [doc = "Reivece packet status"]
# [inline (always)]
pub const fn rpckst (& self) -> u8 { let val = (self . 0 >> 17usize) & 0x0f ; val as u8 } # [doc = "Reivece packet status"]
# [inline (always)]
pub fn set_rpckst (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 17usize)) | (((val as u32) & 0x0f) << 17usize) ; } } impl Default for GrstatrHost { # [inline (always)]
fn default () -> GrstatrHost { GrstatrHost (0) } } impl core :: fmt :: Debug for GrstatrHost { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("GrstatrHost") . field ("cnum" , & self . cnum ()) . field ("bcount" , & self . bcount ()) . field ("dpid" , & self . dpid ()) . field ("rpckst" , & self . rpckst ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for GrstatrHost { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "GrstatrHost {{ cnum: {=u8:?}, bcount: {=u16:?}, dpid: {=u8:?}, rpckst: {=u8:?} }}" , self . cnum () , self . bcount () , self . dpid () , self . rpckst ()) } } # [doc = "Global reset control register (USBFS_GRSTCTL)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Grstctl (pub u32) ; impl Grstctl { # [doc = "Core soft reset"]
# [inline (always)]
pub const fn csrst (& self) -> bool { let val = (self . 0 >> 0usize) & 0x01 ; val != 0 } # [doc = "Core soft reset"]
# [inline (always)]
pub fn set_csrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize) ; } # [doc = "HCLK soft reset"]
# [inline (always)]
pub const fn hcsrst (& self) -> bool { let val = (self . 0 >> 1usize) & 0x01 ; val != 0 } # [doc = "HCLK soft reset"]
# [inline (always)]
pub fn set_hcsrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize) ; } # [doc = "Host frame counter reset"]
# [inline (always)]
pub const fn hfcrst (& self) -> bool { let val = (self . 0 >> 2usize) & 0x01 ; val != 0 } # [doc = "Host frame counter reset"]
# [inline (always)]
pub fn set_hfcrst (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize) ; } # [doc = "RxFIFO flush"]
# [inline (always)]
pub const fn rxff (& self) -> bool { let val = (self . 0 >> 4usize) & 0x01 ; val != 0 } # [doc = "RxFIFO flush"]
# [inline (always)]
pub fn set_rxff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize) ; } # [doc = "TxFIFO flush"]
# [inline (always)]
pub const fn txff (& self) -> bool { let val = (self . 0 >> 5usize) & 0x01 ; val != 0 } # [doc = "TxFIFO flush"]
# [inline (always)]
pub fn set_txff (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 5usize)) | (((val as u32) & 0x01) << 5usize) ; } # [doc = "TxFIFO number"]
# [inline (always)]
pub const fn txfnum (& self) -> u8 { let val = (self . 0 >> 6usize) & 0x1f ; val as u8 } # [doc = "TxFIFO number"]
# [inline (always)]
pub fn set_txfnum (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x1f << 6usize)) | (((val as u32) & 0x1f) << 6usize) ; } # [doc = "AHB master idle"]
# [inline (always)]
pub const fn ahbmidl (& self) -> bool { let val = (self . 0 >> 31usize) & 0x01 ; val != 0 } # [doc = "AHB master idle"]
# [inline (always)]
pub fn set_ahbmidl (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 31usize)) | (((val as u32) & 0x01) << 31usize) ; } } impl Default for Grstctl { # [inline (always)]
fn default () -> Grstctl { Grstctl (0) } } impl core :: fmt :: Debug for Grstctl { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Grstctl") . field ("csrst" , & self . csrst ()) . field ("hcsrst" , & self . hcsrst ()) . field ("hfcrst" , & self . hfcrst ()) . field ("rxff" , & self . rxff ()) . field ("txff" , & self . txff ()) . field ("txfnum" , & self . txfnum ()) . field ("ahbmidl" , & self . ahbmidl ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Grstctl { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Grstctl {{ csrst: {=bool:?}, hcsrst: {=bool:?}, hfcrst: {=bool:?}, rxff: {=bool:?}, txff: {=bool:?}, txfnum: {=u8:?}, ahbmidl: {=bool:?} }}" , self . csrst () , self . hcsrst () , self . hfcrst () , self . rxff () , self . txff () , self . txfnum () , self . ahbmidl ()) } } # [doc = "Global USB control and status register (OTG_FS_GUSBCSR)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Gusbcs (pub u32) ; impl Gusbcs { # [doc = "Timeout calibration"]
# [inline (always)]
pub const fn toc (& self) -> u8 { let val = (self . 0 >> 0usize) & 0x07 ; val as u8 } # [doc = "Timeout calibration"]
# [inline (always)]
pub fn set_toc (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x07 << 0usize)) | (((val as u32) & 0x07) << 0usize) ; } # [doc = "Full speed serial transceiver select"]
# [inline (always)]
pub const fn fssts (& self) -> bool { let val = (self . 0 >> 7usize) & 0x01 ; val != 0 } # [doc = "Full speed serial transceiver select"]
# [inline (always)]
pub fn set_fssts (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 7usize)) | (((val as u32) & 0x01) << 7usize) ; } # [doc = "SRP capability enable"]
# [inline (always)]
pub const fn srpcen (& self) -> bool { let val = (self . 0 >> 8usize) & 0x01 ; val != 0 } # [doc = "SRP capability enable"]
# [inline (always)]
pub fn set_srpcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 8usize)) | (((val as u32) & 0x01) << 8usize) ; } # [doc = "HNP capability enable"]
# [inline (always)]
pub const fn hnpcen (& self) -> bool { let val = (self . 0 >> 9usize) & 0x01 ; val != 0 } # [doc = "HNP capability enable"]
# [inline (always)]
pub fn set_hnpcen (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 9usize)) | (((val as u32) & 0x01) << 9usize) ; } # [doc = "USB turnaround time"]
# [inline (always)]
pub const fn utt (& self) -> u8 { let val = (self . 0 >> 10usize) & 0x0f ; val as u8 } # [doc = "USB turnaround time"]
# [inline (always)]
pub fn set_utt (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x0f << 10usize)) | (((val as u32) & 0x0f) << 10usize) ; } # [doc = "Force host mode"]
# [inline (always)]
pub const fn fhm (& self) -> bool { let val = (self . 0 >> 29usize) & 0x01 ; val != 0 } # [doc = "Force host mode"]
# [inline (always)]
pub fn set_fhm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 29usize)) | (((val as u32) & 0x01) << 29usize) ; } # [doc = "Force device mode"]
# [inline (always)]
pub const fn fdm (& self) -> bool { let val = (self . 0 >> 30usize) & 0x01 ; val != 0 } # [doc = "Force device mode"]
# [inline (always)]
pub fn set_fdm (& mut self , val : bool) { self . 0 = (self . 0 & ! (0x01 << 30usize)) | (((val as u32) & 0x01) << 30usize) ; } } impl Default for Gusbcs { # [inline (always)]
fn default () -> Gusbcs { Gusbcs (0) } } impl core :: fmt :: Debug for Gusbcs { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Gusbcs") . field ("toc" , & self . toc ()) . field ("fssts" , & self . fssts ()) . field ("srpcen" , & self . srpcen ()) . field ("hnpcen" , & self . hnpcen ()) . field ("utt" , & self . utt ()) . field ("fhm" , & self . fhm ()) . field ("fdm" , & self . fdm ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Gusbcs { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Gusbcs {{ toc: {=u8:?}, fssts: {=bool:?}, srpcen: {=bool:?}, hnpcen: {=bool:?}, utt: {=u8:?}, fhm: {=bool:?}, fdm: {=bool:?} }}" , self . toc () , self . fssts () , self . srpcen () , self . hnpcen () , self . utt () , self . fhm () , self . fdm ()) } } # [doc = "Host non-periodic transmit FIFO length register (Host mode)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hnptflen (pub u32) ; impl Hnptflen { # [doc = "host non-periodic transmit Tx RAM start address"]
# [inline (always)]
pub const fn hnptxrsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "host non-periodic transmit Tx RAM start address"]
# [inline (always)]
pub fn set_hnptxrsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "host non-periodic TxFIFO depth"]
# [inline (always)]
pub const fn hnptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "host non-periodic TxFIFO depth"]
# [inline (always)]
pub fn set_hnptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Hnptflen { # [inline (always)]
fn default () -> Hnptflen { Hnptflen (0) } } impl core :: fmt :: Debug for Hnptflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hnptflen") . field ("hnptxrsar" , & self . hnptxrsar ()) . field ("hnptxfd" , & self . hnptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hnptflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hnptflen {{ hnptxrsar: {=u16:?}, hnptxfd: {=u16:?} }}" , self . hnptxrsar () , self . hnptxfd ()) } } # [doc = "Host non-periodic transmit FIFO/queue status register (HNPTFQSTAT)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hnptfqstat (pub u32) ; impl Hnptfqstat { # [doc = "Non-periodic TxFIFO space"]
# [inline (always)]
pub const fn nptxfs (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Non-periodic TxFIFO space"]
# [inline (always)]
pub fn set_nptxfs (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Non-periodic transmit request queue space"]
# [inline (always)]
pub const fn nptxrqs (& self) -> u8 { let val = (self . 0 >> 16usize) & 0xff ; val as u8 } # [doc = "Non-periodic transmit request queue space"]
# [inline (always)]
pub fn set_nptxrqs (& mut self , val : u8) { self . 0 = (self . 0 & ! (0xff << 16usize)) | (((val as u32) & 0xff) << 16usize) ; } # [doc = "Top of the non-periodic transmit request queue"]
# [inline (always)]
pub const fn nptxrqtop (& self) -> u8 { let val = (self . 0 >> 24usize) & 0x7f ; val as u8 } # [doc = "Top of the non-periodic transmit request queue"]
# [inline (always)]
pub fn set_nptxrqtop (& mut self , val : u8) { self . 0 = (self . 0 & ! (0x7f << 24usize)) | (((val as u32) & 0x7f) << 24usize) ; } } impl Default for Hnptfqstat { # [inline (always)]
fn default () -> Hnptfqstat { Hnptfqstat (0) } } impl core :: fmt :: Debug for Hnptfqstat { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hnptfqstat") . field ("nptxfs" , & self . nptxfs ()) . field ("nptxrqs" , & self . nptxrqs ()) . field ("nptxrqtop" , & self . nptxrqtop ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hnptfqstat { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hnptfqstat {{ nptxfs: {=u16:?}, nptxrqs: {=u8:?}, nptxrqtop: {=u8:?} }}" , self . nptxfs () , self . nptxrqs () , self . nptxrqtop ()) } } # [doc = "Host periodic transmit FIFO length register (HPTFLEN)"]
# [repr (transparent)]
# [derive (Copy , Clone , Eq , PartialEq)]
pub struct Hptflen (pub u32) ; impl Hptflen { # [doc = "Host periodic TxFIFO start address"]
# [inline (always)]
pub const fn hptxfsar (& self) -> u16 { let val = (self . 0 >> 0usize) & 0xffff ; val as u16 } # [doc = "Host periodic TxFIFO start address"]
# [inline (always)]
pub fn set_hptxfsar (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 0usize)) | (((val as u32) & 0xffff) << 0usize) ; } # [doc = "Host periodic TxFIFO depth"]
# [inline (always)]
pub const fn hptxfd (& self) -> u16 { let val = (self . 0 >> 16usize) & 0xffff ; val as u16 } # [doc = "Host periodic TxFIFO depth"]
# [inline (always)]
pub fn set_hptxfd (& mut self , val : u16) { self . 0 = (self . 0 & ! (0xffff << 16usize)) | (((val as u32) & 0xffff) << 16usize) ; } } impl Default for Hptflen { # [inline (always)]
fn default () -> Hptflen { Hptflen (0) } } impl core :: fmt :: Debug for Hptflen { fn fmt (& self , f : & mut core :: fmt :: Formatter) -> core :: fmt :: Result { f . debug_struct ("Hptflen") . field ("hptxfsar" , & self . hptxfsar ()) . field ("hptxfd" , & self . hptxfd ()) . finish () } } # [cfg (feature = "defmt")]
impl defmt :: Format for Hptflen { fn format (& self , f : defmt :: Formatter) { defmt :: write ! (f , "Hptflen {{ hptxfsar: {=u16:?}, hptxfd: {=u16:?} }}" , self . hptxfsar () , self . hptxfd ()) } } }